### ISSUE TITLE
Provide stable link in details view

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/Nominatim#1000]
It would be nice if somewhere in the details view there was a link to the same details page but with osmid and osmtype parameters, so that it becomes easier to provide details links that are usable between databases.

To make the link really stable, we'd theoretically need an additional class parameter as an OSM object may appear multiple times in the placex table with different values in the class column.

CC @mtmail

**Comment by mtmail** [comment]
Test cases:

https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=510260718
https://www.openstreetmap.org/way/510260718

``` 
 place_id  | osm_type |  osm_id   |  class   |      type
-----------+----------+-----------+----------+----------------
 172546795 | W        | 510260718 | boundary | protected_area
 172546931 | W        | 510260718 | historic | fortress
 172546996 | W        | 510260718 | military | fortress
 172546648 | W        | 510260718 | tourism  | attraction
```

https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=3731908753
https://www.openstreetmap.org/node/3731908753

```
 place_id | osm_type |   osm_id   |  class  |    type
----------+----------+------------+---------+-------------
 49613115 | N        | 3731908753 | tourism | wine_cellar
 49613027 | N        | 3731908753 | craft   | winery
 49612926 | N        | 3731908753 | shop    | alcohol
```
