### ISSUE TITLE
Zip code 94087 returns empty results

### ISSUE THREAD

**Issue by amit201610** [openstreetmap/Nominatim#1007]
when I query with zip code 94087 which belongs to sunnyvale, california I get empty results.

**Comment by mtmail** [comment]
Thanks amit.

For internal use: examples of addresses tagged with `addr:postcode=94087`
https://www.openstreetmap.org/way/261404686
https://www.openstreetmap.org/way/299691564
https://www.openstreetmap.org/way/38199541

**Comment by amit201610** [comment]
Just to add more details to the issue:
This gives correct results:
https://nominatim.openstreetmap.org/?format=json&addressdetails=1&postalcode=94536
But this returns empty data:
https://nominatim.openstreetmap.org/?format=json&addressdetails=1&postalcode=94087
Thanks
Amit

**Comment by lonvia** [comment]
The non-printable character was indeed the culprit and term normalization should normally get rid of it. Not sure if this is a problem on the import side or in the normalization process. I'll try to create a reproducible test case.
