### ISSUE TITLE
Nederlands - 4 digit postcodes not found

### ISSUE THREAD

**Issue by bijdepinkenzijn** [openstreetmap/Nominatim#1009]
@lonvia We started a foundation in our evenings/weekends to connect elderly people to one another (www.leukeluitjes.nl). We use the Nominatim API for a script to match (lonely) elderly people to other (lonely) elderly people based on their zip code. Up until a week ago all worked fine, we love it and we received a lot of great positive responses from elderly people!! 
But now it doesn't work anymore and we receive error messages for zipcode city combinations that worked before, did anything change in the API recently? (e.g. "1964 Heemskerk could not be located")
It would be great if we could get your feedback, thanks for your great work!

**Comment by mtmail** [comment]
Lovely service.

I believe the OpenStreetMap data changed. In my database I find 3725 addresses with 1964XX (6 character) postcodes. What Nominatim does is group the same postcodes and calculate a center point. What it should for Nederlands is (also) look for the first 4 characters only and calculate a center point. I think at some point in the past, or until recently, there was an address in the OpenStreetMap data with a postcode of 1964 (4 characters). Now arguably the data improved and Nominatim needs to change its logic. 

Is all you need a mapping of 4 character postcode to a name? You can have a look at http://download.geonames.org/export/zip/ (NL.zip of course) in the meantime. It's far less than one megabyte and would save you API requests.

**Comment by lonvia** [comment]
Nothing has changed in Nominatim with regard to these postcodes, so I guess somebody has cleaned up addresses in the Netherlands in OpenStreetMap. As @mtmail says, deriving a 4-digit postcode from the 6-digit postcode available in OSM would be a new feature. I've opened a new ticket #1011 to describe the issue a bit more detailed from the developer's point of view. Closing this ticket.
