### ISSUE TITLE
Missing address from reverse geocoding result

### ISSUE THREAD

**Issue by zoharby** [openstreetmap/Nominatim#1012]
We have our own instance of Nomination, version 3.1.0, built with Tiger data from [here](https://nominatim.org/data/tiger2017-nominatim-preprocessed.tar.gz).

We're encountering a strange behavior in which the correct OSM way is returned, but the returned address is empty.
For example, for https://nominatim.openstreetmap.org/reverse?lat=32.232274&lon=-97.761754&addressdetails=1&format=jsonv2&accept-language=en, the result is:
```json
{
  "place_id": "212818388",
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": "21246697",
  "lat": "32.2321365306122",
  "lon": "-97.7616453265306",
  "place_rank": "30",
  "category": "place",
  "type": "house",
  "importance": "-1.15",
  "addresstype": "place",
  "name": null,
  "display_name": "532, Stadium Drive, Glen Rose, Somervell County, Texas, 76043, United States of America",
  "address": {
    "house_number": "532",
    "road": "Stadium Drive",
    "city": "Glen Rose",
    "county": "Somervell County",
    "state": "Texas",
    "postcode": "76043",
    "country": "United States of America",
    "country_code": "us"
  },
  "boundingbox": [
    "32.232036530612",
    "32.232236530612",
    "-97.761745326531",
    "-97.761545326531"
  ]
}
```

But, when we run the same query in our own server, we get:
```json
{
  "place_id": "219481994",
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": "21246697",
  "lat": "32.2321365306122",
  "lon": "-97.7616453265306",
  "place_rank": "30",
  "category": "place",
  "type": "house",
  "importance": "-1.15",
  "addresstype": "place",
  "display_name": "",
  "name": null,
  "address": [],
  "boundingbox": [
    "32.232036530612",
    "32.232236530612",
    "-97.761745326531",
    "-97.761545326531"
  ]
}
```

[Debug output](https://nominatim.openstreetmap.org/reverse?lat=32.232274&lon=-97.761754&addressdetails=1&format=jsonv2&accept-language=en&debug=1) from official server:
[debug_info_osm_org.txt](https://github.com/openstreetmap/Nominatim/files/1898336/debug_info_osm_org.txt)

Debug output from our own server:
[debug_info_own_server.txt](https://github.com/openstreetmap/Nominatim/files/1898364/debug_info_own_server.txt)

So, I can see that our instance finds the correct street way ID, and also finds a Tiger object with house number 532.
But, no idea why it returns an empty address... Any help will be appreciated!

**Comment by mtmail** [comment]
Updated @zoharby description with indentation, moved debug output into external files for readability.

**Comment by zoharby** [comment]
I have a strong feeling this issue is somehow related to the Tiger data, as the problem occurs very frequently for US coordinates, and seems to not occur at all in other countries.

**Comment by zoharby** [comment]
OK, we found the problem. Looks like we somehow didn't apply the final config step when building the server:
`./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions`
which caused this mis-behavior with the Tiger data.

Not really sure about the internals, but perhaps it would be better if some error was returned instead of an empty address in such a case.
