### ISSUE TITLE
Incorrect result for explicit city/state search

### ISSUE THREAD

**Issue by jkingfish** [openstreetmap/Nominatim#1021]
I am experiencing an issue when querying for a specific city/state/country_code combo that I receive a completely incorrect result.

For example, when searching:
`curl -s 'https://nominatim.openstreetmap.org/search?q=Rosemont%2C+Illinois%2C+US&format=jsonv2&accept-language=en'`

I get the following:
```[{"place_id":"177809015","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"relation","osm_id":"133205","boundingbox":["39.324776","39.337731","-77.630271","-77.610926"],"lat":"39.3292681","lon":"-77.62249","display_name":"Rosemont, Frederick County, Maryland, United States of America","place_rank":"16","category":"boundary","type":"administrative","importance":0.18080884753072,"icon":"https:\/\/nominatim.openstreetmap.org\/images\/mapicons\/poi_boundary_administrative.p.20.png"}]```

Obviously, the wrong state for the search query I am sending. However, when I use the State Code abbreviation, like this:
`curl -s 'https://nominatim.openstreetmap.org/search?q=Rosemont%2C+Il%2C+US&format=jsonv2&accept-language=en'`

I get the proper results for Illinois and NOT Maryland...

Can you explain the difference? I have looked at the details view on the OpenStreetMap sight and see no indicator why Maryland would be a match.

**Comment by lonvia** [comment]
A badly mapped postcode again: https://www.openstreetmap.org/way/64375639

We really need to downgrade unlikely postcodes.

**Comment by lonvia** [comment]
I have edited the way and removed the bad postcode. The results should be better again tomorrow after postcodes have updated. The issue of downgrading postcodes is covered in #988. Closing here.
