### ISSUE TITLE
ImportError: No module named _osmium

### ISSUE THREAD

**Issue by jhward** [openstreetmap/Nominatim#1022]
This is what I'm getting when I run " ./utils/update.php --init-updates" on a CentOS 7 box

`[nominatim@localhost build]$ ./utils/update.php --init-updates
2018-04-22 20:59:50 == Create Functions
NOTICE: drop cascades to function get_addressdata(bigint,integer)
NOTICE: drop cascades to function get_wikipedia_match(hstore,character varying)
Summary of warnings:

2018-04-22 20:59:50 == Setup finished.
Traceback (most recent call last):
File "/srv/nominatim/osmium-2.14.0/tools/pyosmium-get-changes", line 22, in
from osmium.replication import server as rserv
File "/srv/nominatim/osmium-2.14.0/tools/osmium/init.py", line 1, in
from osmium._osmium import *
ImportError: No module named _osmium
ERROR: Error running pyosmium tools
Error running pyosmium tools
[nominatim@localhost build]$`

**Comment by jhward** [comment]
It seems to be missing C++ & Python libraries. The box this is is on is very much bare bones, I had to run a "yum -y install wget bz2 unzip" just to get things to work.

I have no clue, help me if you can!

**Comment by lonvia** [comment]
Not really a Nominatim issue. Please refer to the installation manuals of libosmium and pyosmium.
