### ISSUE TITLE
Query timing out. 

### ISSUE THREAD

**Issue by midhunkrishna** [openstreetmap/Nominatim#1023]
I had done an import of North America and Srilanka using the following Docker file (a section)
```bash
USER nominatim

# Download and merge North America (includes Canada and Mexico) and Srilanka
RUN curl -L 'http://download.geofabrik.de/north-america-latest.osm.pbf' \
    --create-dirs -o /srv/nominatim/src/north-america-latest.osm.pbf
RUN curl -L 'http://download.geofabrik.de/asia/sri-lanka-latest.osm.pbf' \
    --create-dirs -o /srv/nominatim/src/sri-lanka-latest.osm.pbf

RUN osmconvert /srv/nominatim/src/north-america-latest.osm.pbf \
    -o=/srv/nominatim/src/north-america-latest.o5m
RUN osmconvert /srv/nominatim/src/sri-lanka-latest.osm.pbf \
    -o=/srv/nominatim/src/sri-lanka-latest.o5m

RUN osmconvert /srv/nominatim/src/north-america-latest.o5m \
    /srv/nominatim/src/sri-lanka-latest.o5m \
    -o=/srv/nominatim/src/data.o5m

RUN osmconvert /srv/nominatim/src/data.o5m \
    -o=/srv/nominatim/src/data.osm.pbf;


# Filter administrative boundaries
USER nominatim
ARG BUILD_THREADS=16
ARG IMPORT_ADMINISTRATIVE=false
COPY scripts/filter_administrative.sh \
      /srv/nominatim/scripts/filter_administrative.sh
RUN /srv/nominatim/scripts/filter_administrative.sh

# Add postgresql users
USER root
RUN service postgresql start && \
    sudo -u postgres createuser -s nominatim && \
    sudo -u postgres createuser www-data && \
    service postgresql stop

# Tune postgresql configuration for import
USER root
ARG BUILD_MEMORY=32GB
ENV PGCONFIG_URL https://api.pgconfig.org/v1/tuning/get-config
RUN IMPORT_CONFIG_URL="${PGCONFIG_URL}? \
      format=alter_system& \
      pg_version=${PGSQL_VERSION}& \
      total_ram=${BUILD_MEMORY}& \
      max_connections=$((8 * ${BUILD_THREADS} + 32))& \
      environment_name=DW& \
      include_pgbadger=false" && \
    IMPORT_CONFIG_URL=${IMPORT_CONFIG_URL// /} && \
    service postgresql start && \
    ( curl -sSL "${IMPORT_CONFIG_URL}"; \
      echo $'ALTER SYSTEM SET fsync TO \'off\';\n'; \
      echo $'ALTER SYSTEM SET full_page_writes TO \'off\';\n'; \
      echo $'ALTER SYSTEM SET logging_collector TO \'off\';\n'; \
    ) | sudo -u postgres psql -e && \
    service postgresql stop
```

The import is going in fine, but when i search for New York from the debugging interface I get an error

url => http://address:8080/search.php?q=New+York&polygon_geojson=1&viewbox=

```
Internal Server Error
Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.

Message: Could not get places for search terms.

SQL Error: DB Error: unknown error

Details:

SELECT place_id,0::int as exactmatch FROM search_name WHERE name_vector @> ARRAY[5638674] ORDER BY (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75001-(search_rank::float/40) ELSE importance END) DESC LIMIT 20 [nativecode=ERROR:  canceling statement due to statement timeout]
```

Is it sql timing out due to index issues? Whats the next best approach to debug this?

I have a total available RAM of 8 GB for running and 8 cores, but while the query is running, the ram usage is never above 600MB

**Comment by mtmail** [comment]
Can you connect to the database manually using `psql`?

Does http://address:8080/search.php report a different error? (It's somewhat readable what queries search.php is running https://github.com/openstreetmap/Nominatim/blob/master/website/status.php)

Do you see any errors in the postgresql log file?

**Comment by midhunkrishna** [comment]
@mtmail I am able to connecto to psql. 
The search.php did initially gave me a `Could not get word tokens` which went away with the fix mentioned [here](https://wiki.openstreetmap.org/wiki/Nominatim/Installation/Troubleshooting#The_browser_shows_Could_not_get_word_tokens )

After that, the above pasted is what I am getting. I checked the apache logs, there was no errors there. 
I am doing the whole thing in a docker machine, and I thought this may be due to the less postgres runtime memmory I have set in the tuning step. So i increased the whole memory and have scehduled for a rebuilt. 

Once it is up, will add resutls returned in  http://address:8080/search.php?q=New+York&polygon_geojson=1&viewbox=&debug=1

**Comment by lonvia** [comment]
Please make sure that there was/is no error during import and check that the indices on the `search_name` table have been created. There should be 4 indexes there.

**Comment by lonvia** [comment]
These are the indexes for `search_name_0` which is a different table but all the indexes for `search_name` seem to be there. What does the following say

    EXPLAIN SELECT place_id,0::int as exactmatch FROM search_name 
    WHERE name_vector @> ARRAY[5639492] ORDER BY
    (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75001-(search_rank::float/40) ELSE importance END) DESC LIMIT 20

It may run for a long time but also try

    EXPLAIN ANALYSE SELECT place_id,0::int as exactmatch FROM search_name 
    WHERE name_vector @> ARRAY[5639492] ORDER BY
    (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75001-(search_rank::float/40) ELSE importance END) DESC LIMIT 20

**Comment by midhunkrishna** [comment]
Explain
```
                      QUERY PLAN                                                
                                                       
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
-------------------------------------------------------
 Limit  (cost=8558.43..8558.48 rows=20 width=20)
   ->  Sort  (cost=8558.43..8563.87 rows=2175 width=20)
         Sort Key: (CASE WHEN ((importance = '0'::double precision) OR (importan
ce IS NULL)) THEN ('0.75001'::double precision - ((search_rank)::double precisio
n / '40'::double precision)) ELSE importance END) DESC
         ->  Bitmap Heap Scan on search_name  (cost=44.86..8500.55 rows=2175 wid
th=20)
               Recheck Cond: (name_vector @> '{5639492}'::integer[])
               ->  Bitmap Index Scan on idx_search_name_name_vector  (cost=0.00.
.44.32 rows=2175 width=0)
                     Index Cond: (name_vector @> '{5639492}'::integer[])
(7 rows)

**Comment by midhunkrishna** [comment]
@lonvia The queries are working correctly now. When I thought about the last explain analyze posted, it seemed the planning was talking all the time. I ran 

`psql -d nominatim -c 'ANALYZE VERBOSE'`

and everything is super fast now. 

Thank you for all your help. Appreciate it. :+1:
