### ISSUE TITLE
Not all parts of a street are found

### ISSUE THREAD

**Issue by avanc** [openstreetmap/Nominatim#1025]
While searching for a street within a viewbox, nominatim only returns several chunks for that street:
https://nominatim.openstreetmap.org/search.php?q=Celler+Straße&polygon_geojson=1&viewbox=9.70419%2C52.38568%2C9.76513%2C52.37259&bounded=1

However, I would expect all parts are found:
http://overpass-turbo.eu/s/yk9

**Comment by lonvia** [comment]
Try with parameter `dedupe=0`.

**Comment by avanc** [comment]
Sorry, I forgot to respond.
dedupe=0 was exactly what I needed.
Thanks!
