### ISSUE TITLE
Exact address not found when adding country to structured query

### ISSUE THREAD

**Issue by scaidermern** [openstreetmap/Nominatim#1034]
From here: https://stackoverflow.com/questions/50182917/openstreetmap-overpass-api-validate-tag-if-present

This query returns the expected result (https://www.openstreetmap.org/way/10594513):
`https://nominatim.openstreetmap.org/search?street=213 Brünner Straße&postalcode=1210`

The same query with a country specified doesn't return an exact match:
`https://nominatim.openstreetmap.org/search?street=213 Brünner Straße&postalcode=1210&country=AT`

**Comment by lonvia** [comment]
This is a regression from the postcode rewrite. Search results for the street were no longer narrowed down to the ones that have a matching house number.

Fix deployed on nominatim.osm.org.
