### ISSUE TITLE
On reverse search when returning way set geometry to point close to query, not centroid of way

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1035]
On reverse search when a way is found Nominatim returns the centroid of the way which might be far away from the search point.

Example
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=21.016857&lon=-100.392592&zoom=18
(small red circle = search point, blue circle = the returned centroid)

Here the search point is right on the street, but centroid is 15km away. Probably an extreme case because the way is some 50km long https://www.openstreetmap.org/way/184939434

![image](https://user-images.githubusercontent.com/3727288/39705602-2897649a-520f-11e8-8ea4-f6adde73b350.png)

**Comment by lonvia** [comment]
Fixed with #1054.
