### ISSUE TITLE
corresponding place objects aren't found if too far away

### ISSUE THREAD

**Issue by Luzandro** [openstreetmap/Nominatim#1036]
When using addr:place the corresponding place object often isn't found because it's too far away and an incorrect address is created by Nominatim.

For example "Höflach 45a, Fehring" gets to "Pischaunweg 45a, Hartl, Fehring"
https://nominatim.openstreetmap.org/details.php?place_id=152494028

To work around this issue some people are adding the place name as incorrect alt_name tags to nearby streets or change the place nodes to areas that include all addresses, but where the center of the areas might end up at locations that aren't anywhere near the actual place anymore - see the distribution of addr:place=Höflach for example: https://overpass-turbo.eu/s/yAx

**Comment by lonvia** [comment]
I've now increased the radius slightly. Let's see how that goes performance-wise.

I have forcefully updated the example above and it now shows the right address. Other places will gradually update as the data changes.
