### ISSUE TITLE
reverse geocode performance issue

### ISSUE THREAD

**Issue by massimo4** [openstreetmap/Nominatim#1039]
Hi,
we use nominatim db for reverse geocoding. The general performance are good but we use a lot of reverse geocoding per second...
My issue is that... after the first import or an update a query like this:

SELECT	place_id,parent_place_id,rank_search,country_code,
		ST_distance('0101000020E6100000CCB73EAC37922C40149337C0CC6F4440', geometry) as distance
FROM	placex
WHERE	ST_DWithin('0101000020E6100000CCB73EAC37922C40149337C0CC6F4440', geometry, 0.0008)
		AND rank_search = 30
		AND (name is not null or housenumber is not null) 
		AND class not in ('waterway','railway','tunnel','bridge','man_made')
		AND indexed_status = 0 
		AND (ST_GeometryType(geometry) not in ('ST_Polygon','ST_MultiPolygon')
		OR ST_DWithin('0101000020E6100000CCB73EAC37922C40149337C0CC6F4440', centroid, 0.0008))
		ORDER BY distance ASC limit 1;

take about 40-50ms and 4700 buffer hits.
The same query after an update whitout indexing step take 1-2ms ad 160 buffers hits.
If, after that, I take an indexing step, the performance gets worse again.
The difference is very strong, like the use of cpu and the reverse geocoding capacity...

Any ideas?

**Comment by mtmail** [comment]
That's a level of individual support we simply (time, resources) can't offer. There's no company behind Nominatim. You can try the mailing list to see if other Nominatim users saw/see the same issue.
