### ISSUE TITLE
Project which identifies invalid house addresses?

### ISSUE THREAD

**Issue by fukejs** [openstreetmap/Nominatim#1040]
Hi.
Does exist some OSM Project that indentifies addresses of buildings that cannot be searched with Nominatim?

Fot example this https://www.openstreetmap.org/way/224488751 building is not searched as " Scheibe 90, St. Leonhard im Pitztal" because "Scheibe" is tagged as addr:street and should be addr:place.

Or this https://www.openstreetmap.org/way/493028529 building is not searched as "Haupttürnitzrotte 12, Annaberg" because place Haupttürnitzrotte is tagged as place=locality, which is not supported.

Can editors of OSM see invalid house addresses somewhere to correct them?

**Comment by mtmail** [comment]
Of the https://wiki.openstreetmap.org/wiki/Quality_assurance I see only OSMI marking that as error. Possible nobody wrote logic/plugins for the other validators yet.

http://tools.geofabrik.de/osmi/?view=addresses&lon=10.85322&lat=47.05783&zoom=18&overlays=buildings,buildings_with_addresses,postal_code,entrances_deprecated,entrances,no_addr_street,street_not_found,place_not_found,misformatted_housenumber_lenient,nodes_with_addresses_defined,nodes_with_addresses_interpolated,interpolation,interpolation_errors,connection_lines,nearest_points,nearest_roads,nearest_areas,addrx_on_nonclosed_way

https://www.keepright.at/report_map.php?zoom=14&lon=10.85322&lat=47.05783

http://osmose.openstreetmap.fr/en/map/#zoom=18&lon=10.85322&lat=47.05783

I checked JOSM validation plugin as well

**Comment by fukejs** [comment]
Now I look at FixAddresses https://wiki.openstreetmap.org/wiki/JOSM/Plugins/FixAddresses JOSM Plugin and I think it also helps.
