### ISSUE TITLE
How to continue importing the data?

### ISSUE THREAD

**Issue by cheeta2018** [openstreetmap/Nominatim#1042]
Hello,I have a question;.
I use the following command   " ./utils/setup.php --osm-file <data file> --all [--osm2pgsql-cache 28000] 2>&1 | tee setup.log  "  to import my data to the nominatim, but I closed the terminal window halfway,so the meaning of it is that have terminated this command .  
 Can I continue to import the data on the basis of the original before closed the terminal window? What should I do?
Thank you very  much!!!

**Comment by mtmail** [comment]
If the import was already in the indexing stage, you can follow http://nominatim.org/release-docs/latest/admin/Faq/#i-accidentally-killed-the-import-process-after-it-has-been-running-for-many-hours-can-it-be-resumed

**Comment by cheeta2018** [comment]
Thank you very much!
