### ISSUE TITLE
Broken links in the docs

### ISSUE THREAD

**Issue by rkcpi** [openstreetmap/Nominatim#1045]
The links for Ubuntu and CentOS specific installation instructions are broken in the docs: https://github.com/openstreetmap/Nominatim/blob/master/docs/admin/Installation.md

They lead to https://github.com/openstreetmap/Nominatim/blob/master/docs/appendix/Install-on-Ubuntu-16.md and https://github.com/openstreetmap/Nominatim/blob/master/docs/appendix/Install-on-Centos-7.md respectively. Those links result in a 404.

**Comment by lonvia** [comment]
The documentation is not meant to be read in github but needs to be compiled. See http://nominatim.org/release-docs/develop/ for a daily updated version of the latest documentation for current master.
