### ISSUE TITLE
Using nominatim3.1.0 on Ubuntu 16.04 -- getting Internal Server Error - SQL Error: DB Error: no such table

### ISSUE THREAD

**Issue by kshankar2017** [openstreetmap/Nominatim#1048]
Followed all the procedures in http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-16/
Installed postgres and apache as root. Installed nominatim as user 'nominatim'.
Then accessed
http://localhost
Got confirmation that apache2 installed correctly.
http://localhost/nominatim?debug=1
Getting Internal Server Error
SQL Error: DB Error: no such table
and a stack trace complaining that "import_status" does not exist. Any ideas ?

URL:  http://23.92.27.60/nominatim/?debug=1

Internal Server Error

Message: Database request failed

SQL Error: DB Error: no such table

Details:

object(DB_Error)#6 (8) {
  ["error_message_prefix"]=>
  string(0) ""
  ["mode"]=>
  int(1)
  ["level"]=>
  int(1024)
  ["code"]=>
  int(-18)
  ["message"]=>
  string(23) "DB Error: no such table"
  ["userinfo"]=>
  string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
  ["backtrace"]=>
  array(10) {
    [0]=>
    array(6) {
      ["file"]=>
      string(23) "/usr/share/php/PEAR.php"
      ["line"]=>
      int(945)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(10) "PEAR_Error"
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        string(23) "DB Error: no such table"
        [1]=>
        int(-18)
        [2]=>
        int(1)
        [3]=>
        int(1024)
        [4]=>
        string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
      }
    }
    [1]=>
    array(7) {
      ["file"]=>
      string(21) "/usr/share/php/DB.php"
      ["line"]=>
      int(966)
      ["function"]=>
      string(10) "PEAR_Error"
      ["class"]=>
      string(10) "PEAR_Error"
      ["object"]=>
      *RECURSION*
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        string(23) "DB Error: no such table"
        [1]=>
        int(-18)
        [2]=>
        int(1)
        [3]=>
        int(1024)
        [4]=>
        string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
      }
    }
    [2]=>
    array(7) {
      ["file"]=>
      string(23) "/usr/share/php/PEAR.php"
      ["line"]=>
      int(575)
      ["function"]=>
      string(8) "DB_Error"
      ["class"]=>
      string(8) "DB_Error"
      ["object"]=>
      *RECURSION*
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(4) {
        [0]=>
        int(-18)
        [1]=>
        int(1)
        [2]=>
        int(1024)
        [3]=>
        string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
      }
    }
    [3]=>
    array(7) {
      ["file"]=>
      string(23) "/usr/share/php/PEAR.php"
      ["line"]=>
      int(223)
      ["function"]=>
      string(11) "_raiseError"
      ["class"]=>
      string(4) "PEAR"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(8) {
        [0]=>
        object(DB_pgsql)#1 (28) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["features"]=>
          array(7) {
            ["limit"]=>
            string(5) "alter"
            ["new_link"]=>
            string(5) "4.3.0"
            ["numrows"]=>
            bool(true)
            ["pconnect"]=>
            bool(true)
            ["prepare"]=>
            bool(false)
            ["ssl"]=>
            bool(true)
            ["transactions"]=>
            bool(true)
          }
          ["errorcode_map"]=>
          array(0) {
          }
          ["connection"]=>
          resource(1) of type (pgsql link)
          ["dsn"]=>
          array(9) {
            ["phptype"]=>
            string(5) "pgsql"
            ["dbsyntax"]=>
            string(5) "pgsql"
            ["username"]=>
            string(0) ""
            ["password"]=>
            bool(false)
            ["protocol"]=>
            string(3) "tcp"
            ["hostspec"]=>
            string(0) ""
            ["port"]=>
            bool(false)
            ["socket"]=>
            bool(false)
            ["database"]=>
            string(9) "nominatim"
          }
          ["autocommit"]=>
          bool(true)
          ["transaction_opcount"]=>
          int(0)
          ["affected"]=>
          int(0)
          ["row"]=>
          array(0) {
          }
          ["_num_rows"]=>
          array(0) {
          }
          ["fetchmode"]=>
          int(2)
          ["fetchmode_object_class"]=>
          string(8) "stdClass"
          ["was_connected"]=>
          NULL
          ["last_query"]=>
          string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
          ["options"]=>
          array(8) {
            ["result_buffering"]=>
            int(500)
            ["persistent"]=>
            bool(false)
            ["ssl"]=>
            bool(false)
            ["debug"]=>
            int(0)
            ["seqname_format"]=>
            string(6) "%s_seq"
            ["autofree"]=>
            bool(false)
            ["portability"]=>
            int(0)
            ["optimize"]=>
            string(11) "performance"
          }
          ["last_parameters"]=>
          array(0) {
          }
          ["prepare_tokens"]=>
          array(0) {
          }
          ["prepare_types"]=>
          array(0) {
          }
          ["prepared_queries"]=>
          array(0) {
          }
          ["_last_query_manip"]=>
          bool(false)
          ["_next_query_manip"]=>
          bool(false)
          ["_debug"]=>
          bool(false)
          ["_default_error_mode"]=>
          NULL
          ["_default_error_options"]=>
          NULL
          ["_default_error_handler"]=>
          string(0) ""
          ["_error_class"]=>
          string(8) "DB_Error"
          ["_expected_errors"]=>
          array(0) {
          }
        }
        [1]=>
        NULL
        [2]=>
        int(-18)
        [3]=>
        int(1)
        [4]=>
        int(1024)
        [5]=>
        string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
        [6]=>
        string(8) "DB_Error"
        [7]=>
        bool(true)
      }
    }
    [4]=>
    array(7) {
      ["file"]=>
      string(28) "/usr/share/php/DB/common.php"
      ["line"]=>
      int(1908)
      ["function"]=>
      string(6) "__call"
      ["class"]=>
      string(4) "PEAR"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(2) {
        [0]=>
        string(10) "raiseError"
        [1]=>
        array(7) {
          [0]=>
          NULL
          [1]=>
          int(-18)
          [2]=>
          NULL
          [3]=>
          NULL
          [4]=>
          string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
          [5]=>
          string(8) "DB_Error"
          [6]=>
          bool(true)
        }
      }
    }
    [5]=>
    array(7) {
      ["file"]=>
      string(27) "/usr/share/php/DB/pgsql.php"
      ["line"]=>
      int(790)
      ["function"]=>
      string(10) "raiseError"
      ["class"]=>
      string(9) "DB_common"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(5) {
        [0]=>
        int(-18)
        [1]=>
        NULL
        [2]=>
        NULL
        [3]=>
        string(309) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^]"
        [4]=>
        string(185) "ERROR:  relation "import_status" does not exist
LINE 1: ...tes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_sta...
                                                             ^"
      }
    }
    [6]=>
    array(7) {
      ["file"]=>
      string(27) "/usr/share/php/DB/pgsql.php"
      ["line"]=>
      int(337)
      ["function"]=>
      string(15) "pgsqlRaiseError"
      ["class"]=>
      string(8) "DB_pgsql"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(0) {
      }
    }
    [7]=>
    array(7) {
      ["file"]=>
      string(28) "/usr/share/php/DB/common.php"
      ["line"]=>
      int(1216)
      ["function"]=>
      string(11) "simpleQuery"
      ["class"]=>
      string(8) "DB_pgsql"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
      }
    }
    [8]=>
    array(7) {
      ["file"]=>
      string(28) "/usr/share/php/DB/common.php"
      ["line"]=>
      int(1289)
      ["function"]=>
      string(5) "query"
      ["class"]=>
      string(9) "DB_common"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
      }
    }
    [9]=>
    array(7) {
      ["file"]=>
      string(55) "/srv/nominatim/Nominatim-3.1.0/build/website/search.php"
      ["line"]=>
      int(69)
      ["function"]=>
      string(6) "getOne"
      ["class"]=>
      string(9) "DB_common"
      ["object"]=>
      object(DB_pgsql)#1 (28) {
        ["phptype"]=>
        string(5) "pgsql"
        ["dbsyntax"]=>
        string(5) "pgsql"
        ["features"]=>
        array(7) {
          ["limit"]=>
          string(5) "alter"
          ["new_link"]=>
          string(5) "4.3.0"
          ["numrows"]=>
          bool(true)
          ["pconnect"]=>
          bool(true)
          ["prepare"]=>
          bool(false)
          ["ssl"]=>
          bool(true)
          ["transactions"]=>
          bool(true)
        }
        ["errorcode_map"]=>
        array(0) {
        }
        ["connection"]=>
        resource(1) of type (pgsql link)
        ["dsn"]=>
        array(9) {
          ["phptype"]=>
          string(5) "pgsql"
          ["dbsyntax"]=>
          string(5) "pgsql"
          ["username"]=>
          string(0) ""
          ["password"]=>
          bool(false)
          ["protocol"]=>
          string(3) "tcp"
          ["hostspec"]=>
          string(0) ""
          ["port"]=>
          bool(false)
          ["socket"]=>
          bool(false)
          ["database"]=>
          string(9) "nominatim"
        }
        ["autocommit"]=>
        bool(true)
        ["transaction_opcount"]=>
        int(0)
        ["affected"]=>
        int(0)
        ["row"]=>
        array(0) {
        }
        ["_num_rows"]=>
        array(0) {
        }
        ["fetchmode"]=>
        int(2)
        ["fetchmode_object_class"]=>
        string(8) "stdClass"
        ["was_connected"]=>
        NULL
        ["last_query"]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
        ["options"]=>
        array(8) {
          ["result_buffering"]=>
          int(500)
          ["persistent"]=>
          bool(false)
          ["ssl"]=>
          bool(false)
          ["debug"]=>
          int(0)
          ["seqname_format"]=>
          string(6) "%s_seq"
          ["autofree"]=>
          bool(false)
          ["portability"]=>
          int(0)
          ["optimize"]=>
          string(11) "performance"
        }
        ["last_parameters"]=>
        array(0) {
        }
        ["prepare_tokens"]=>
        array(0) {
        }
        ["prepare_types"]=>
        array(0) {
        }
        ["prepared_queries"]=>
        array(0) {
        }
        ["_last_query_manip"]=>
        bool(false)
        ["_next_query_manip"]=>
        bool(false)
        ["_debug"]=>
        bool(false)
        ["_default_error_mode"]=>
        NULL
        ["_default_error_options"]=>
        NULL
        ["_default_error_handler"]=>
        string(0) ""
        ["_error_class"]=>
        string(8) "DB_Error"
        ["_expected_errors"]=>
        array(0) {
        }
      }
      ["type"]=>
      string(2) "->"
      ["args"]=>
      array(1) {
        [0]=>
        string(110) "select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1"
      }
    }
  }
  ["callback"]=>
  NULL
}

**Comment by kshankar2017** [comment]
The users apache, nominatim, postgres and www-data are all created with appropriate privileges.
nominatim=# \du
                                   List of roles
 Role name |                         Attributes                         | Member of
-----------+------------------------------------------------------------+-----------
 apache    |                                                            | {}
 nominatim | Superuser, Create role, Create DB                          | {}
 postgres  | Superuser, Create role, Create DB, Replication, Bypass RLS | {}
 www-data  |                                                            | {}

nominatim=# \c
psql (9.5.12, server 9.5.13)
You are now connected to database "nominatim" as user "nominatim".

**Comment by mtmail** [comment]
After installing, did you run the data import process http://nominatim.org/release-docs/latest/admin/Import-and-Update/ ? Do you see errors in the setup.log file?

**Comment by kshankar2017** [comment]
No I don't believe psql when connected to nominatim database shows import_status table.
Here is what I did. As 'nominatim' user
nominatim> psql -d nominatim
nominatim-# \dt
                   List of relations
 Schema |           Name           | Type  |   Owner
--------+--------------------------+-------+-----------
 public | country_name             | table | nominatim
 public | country_naturalearthdata | table | nominatim
 public | country_osm_grid         | table | nominatim
 public | gb_postcode              | table | nominatim
 public | location_property_tiger  | table | nominatim
 public | place_boundingbox        | table | nominatim
 public | spatial_ref_sys          | table | nominatim
 public | us_postcode              | table | nominatim
(8 rows)

Yes I do get errors when I do an import. Running as user 'nominatim'
nominatim@li657-60:~/Nominatim/build$ ./utils/setup.php --osm-file ./map.osm --all 2>&1 | tee /tmp/setup.log
2018-05-25 10:20:33 == Create DB
ERROR: database already exists (pgsql://@/nominatim)
database already exists (pgsql://@/nominatim)

Any ideas ? Thank you very much.

**Comment by mtmail** [comment]
Does `osm2pgsql` fail immediately or after it imported some places already? You can check the number of records in the `planet_osm_nodes`, `planet_osm_ways`, `planet_osm_rels` tables. For the nodes tables 0 is fine because you use the flatnode file.

Usually the issue with `osm2pgsql` is lacking resources, mostly not enough RAM for the data to be imported. If you have monitoring tools or graphing tools on the server check how much RAM was used during import. If it's a virtual machine it might have been configured not to swap memory (though swapping makes an import even slower).

Best next step is trying to import a small countries, or one US state, first. I use Luxembourg or Monaco when testing.

If RAM usage is too high for the north-america file then the only solution is adding more RAM or using another server. The http://nominatim.org/release-docs/latest/admin/Installation/#hardware recommend 32GB for the full planet. 

> database already exists (pgsql://@/nominatim)

Yes, just run `dropdb nominatim` to delete the database before a new installation.

**Comment by kshankar2017** [comment]
Thank you you were right I was getting out of memory error in /var/log/syslog from osm2pgsql program.
So I reduced my osm2pgsql-cache from 5000 to 2000 and was able to successfully import us-northeast-latest.osm.pbf in 2 hours 11 mins. I still need to find a way to compile the entire US and Canada at least.
North America is not needed. Any place I can access just US + Canada ?

**Comment by mtmail** [comment]
You can import multiple countries. See http://nominatim.org/release-docs/latest/admin/Faq/#can-i-import-only-a-few-countries-and-also-keep-them-up-to-date
