### ISSUE TITLE
"Boulevard" not implicit when searching an address

### ISSUE THREAD

**Issue by Peuc** [openstreetmap/Nominatim#1049]
When looking for an address, user may not know way type (avenue, street, boulevard…), so Nominatim searches any type, when not provided.

However, for some reason this doesn't work for Boulevard type. i.e. :
- [2998 rue Édouard Montpetit, Laval](https://www.openstreetmap.org/search?query=2998%20rue%20Édouard%20Montpetit,%20Laval) and [2998 Édouard Montpetit, Laval](https://www.openstreetmap.org/search?query=2998%20Édouard%20Montpetit,%20Laval) both return the same result
- [2370 Boulevard Daniel-Johnson, Laval](https://www.openstreetmap.org/search?query=2370%20Boulevard%20Daniel-Johnson%2C%20Laval) works while [2370 Daniel-Johnson, Laval](https://www.openstreetmap.org/search?query=2370%20Daniel-Johnson%2C%20Laval) doesn't.

According to a few tests, only "Boulevard" has the problem.

**Comment by nitrique** [comment]
Hi,

Same here with "boulevard du Maréchal Joffre, Bourg la Reine" works, "boulevard Maréchal Joffre, Bourg la Reine" didn't.

**Comment by lonvia** [comment]
Nothing to do with "boulevard" really. Nominatim isn't particular good with searching for partial matches.

**Comment by nitrique** [comment]
Yes, but same "prediction" and matching problem, kinda

**Comment by lonvia** [comment]
The initial example works again, likely because of improved search result ranking.

The example with "boulevard du Maréchal Joffre" is actually a particle problem ("Maréchal Joffre, Bourg la Reine"). This is already covered in #753. Closing here.
