### ISSUE TITLE
Ontario, Canada Postal Code Inaccuracies 

### ISSUE THREAD

**Issue by alextrosta** [openstreetmap/Nominatim#1052]
Hello, 

I am conducting an analysis of Ontario, Canada by comparing actual street addresses to results returned by nominatim. 
I have found that many correct matches (accurate responses from nominatim) have incorrect postal codes tagged. 

I am aware (from here: 

https://wiki.openstreetmap.org/wiki/Nominatim/FAQ#My_postcode_is_missing.2Fwrong_but_I.27ve_fixed_it_in_the_OSM_data._What_is_wrong.3F

that "Support for post codes in Nominatim currently is very primitive.", but am wondering about the postal code computation process that tags the addresses of OSM with Postal Codes. 

For example, searching for "800 spadina road, toronto" results in:

https://nominatim.openstreetmap.org/search.php?q=800+spadina+road&polygon_geojson=1&viewbox=

This address is correct, but the postal code isn't (it should be M5P 3N2).
However, the returned Postal Code tag (M5N 1B9) is of a nearby location. 

(See:
https://www.google.ca/maps/place/Toronto,+ON+M5N+1B9/@43.7025891,-79.4218995,17.75z/data=!4m5!3m4!1s0x882b330ba221bbe1:0x7ce9a4fa366004db!8m2!3d43.7028714!4d-79.420805

My question is: how was this postal code value attached to this entry? 

Was it computed by means of locality? 

That is, if a new address is added to OSM, and the user doesn't input a postal code value, does OSM look for a nearby address _with_ a postal code tag, and attaches that value to the new entry?
If this is the case, what constitutes _"nearby"_ in this case? 

I am aware of the request to "not post bugs about postal codes", but since my query is regarding the postal code tagging process itself and not about an individual postal code, I was hoping for some information regarding this process. 

Any input would be greatly appreciated,

Alex

**Comment by lonvia** [comment]
See https://www.openstreetmap.org/user/lonvia/diary/43143
