### ISSUE TITLE
Docker-nominatim: Update not set up - --init-updates

### ISSUE THREAD

**Issue by fberdejo** [openstreetmap/Nominatim#1055]
Dear All,

I have a question regarding updating the nominatim data on docker. but unfortunately, I encounter this message.. Updates not set up. Please run ./utils/update.php --init-updates

When I run this command
 docker exec -it nominatim sudo -u nominatim ./src/utils/update.php --init-updates : 

Functions
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
NOTICE:  drop cascades to function get_addressdata(bigint,integer)
DROP TYPE
CREATE TYPE
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
NOTICE:  drop cascades to function get_wikipedia_match(hstore,character varying)

Instruction that I follow. This is working for a 3 months
https://hub.docker.com/r/mediagis/nominatim/

Hope you can help about this issue.. thank you in advance

**Comment by mtmail** [comment]
Do you have any records in the `import_status` table? What is the last date (last record) when the import worked?

What is your `CONST_Replication_Url`? You can find that in the build-directory/settings/local.php file. (not exactly sure what the path to the build directory is on docker).

I think the issue might be http vs https in the Replication_Url. https://planet.openstreetmap.org/ started enforcing https a couple of weeks ago. That server redirects but not all clients, including what Nominatim uses in the background, are able to follow such a redirect. In that case https://github.com/openstreetmap/Nominatim/issues/1051 is similar.

**Comment by fberdejo** [comment]
Hi

I find the local.ph in nominatim-docker-master/3.0/local.php

// Paths
 @define('CONST_Postgresql_Version', '9.5');
 @define('CONST_Postgis_Version', '2.2');
 // Website settings
 @define('CONST_Website_BaseURL', '/');
 @define('CONST_Replication_Url', 'http://download.geofabrik.de/asia/philippines-updates');
 @define('CONST_Replication_MaxInterval', '86400');     // Process each update separately, osmosis cannot merge multiple updates
 @define('CONST_Replication_Update_Interval', '86400');  // How often upstream publishes diffs
 @define('CONST_Replication_Recheck_Interval', '900');   // How long to sleep if no update found yet
 @define('CONST_Pyosmium_Binary', '/usr/local/bin/pyosmium-get-changes');

Hope this can help.. thank you

**Comment by mtmail** [comment]
The people who wrote the docker configuration and documentation have their own issue tracker https://github.com/mediagis/nominatim-docker/issues so that might be more helpful. I don't see any similar past issues in there.

What are the last lines of your `import_status` table in Postgresql? You said (the update?) worked for three months so there should be entries in the table.

**Comment by lonvia** [comment]
As @mtmail states, issues with external docker setups should be reported with the creators of those images. Closing here.

**Comment by fberdejo** [comment]
Hi.. 

How can run this "Please run ./utils/update.php --init-updates"

Thanks.
