### ISSUE TITLE
Polygonpoints of municipality areas does not return for "osm_type": "relation"

### ISSUE THREAD

**Issue by chandulaPerera** [openstreetmap/Nominatim#1064]
I want to get polygon points ("osm_type": "relation") for municipality areas in Sweden. It works well with 277 areas. But I am not able to get polygon points for following municipality areas.

_Bergs kommun , Borlänge kommun  , Falköpings kommun , Gagnefs kommun , Haparanda kommun  , Kalix kommun  , Kramfors kommun , Leksands kommun , Lilla Edets kommun , Linköpings kommun  , Mora kommun ,Mullsjö kommun , Orusts kommun , Pajala kommun ,  Rättviks kommun , Simrishamns kommun , Skara kommun , Skövde kommun , Tomelilla kommun , Ängelholms kommun , Överkalix kommun , Övertorneå kommun_

The query, which I am using is,
https://nominatim.openstreetmap.org/search?city=Link%C3%B6pings%20kommun&country=sweden&format=json&polygon=1&addressdetails=1

The response does not contain "polygonpoints" for "osm_type": "relation". Could you please explain me how can I get these information.

**Comment by mtmail** [comment]
I think they're all in OSM, just harder to find. For example Falköpings kommun exists as node https://www.openstreetmap.org/node/302269787 and relation https://www.openstreetmap.org/relation/935600 and Nominatim in this case returns the node. When you link the places together it helps Nominatim. Add a `admin_centre` role to the relation https://wiki.openstreetmap.org/wiki/Relation:boundary#Relation_members

That said maybe all you need is https://wambachers-osm.website/boundaries/

![image](https://user-images.githubusercontent.com/3727288/41465054-c2876c70-709c-11e8-92eb-3cbe34c1bf2b.png)

**Comment by lonvia** [comment]
Yes, please use Wambachers boundary service. Systematic downloads like this are forbidden by the usage policy for nominatim.openstreetmap.org.

That said, you need to use one of the other `polygon_*` formats. The `polygon` format does not support multipolygons.

**Comment by chandulaPerera** [comment]
Thanks a lot.
