### ISSUE TITLE
clientaccesspolicy.xml 

### ISSUE THREAD

**Issue by my-poi** [openstreetmap/Nominatim#1066]
Hello, 

is it possible to add https://nominatim.openstreetmap.org/clientaccesspolicy.xml

Regards,
Maciej

**Comment by lonvia** [comment]
I have no idea what exactly should go into such a file but googling seems to suggest that it has something to do with cross-site policies for WCF services. Given that Nominatim is a simple web service, the answer is likely, no, we cannot add that.

**Comment by my-poi** [comment]
OK! No problem.
