### ISSUE TITLE
Postgres library issue while setup nominatim

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1067]
Check below logs, which was getting while setup nominatim in CentOS 7.4.1708.
(I have installed Postgres 9.5.10 only, don't know how it says lib version as 9.2)
Please help me to solve this issue.

> php /Nominatim-3.1.0/build/utils/setup.php --osm-file andorra-latest.osm.pbf --all

> 2018-06-19 09:31:34 == Create DB
> 2018-06-19 09:31:34 == Setup DB
> Postgres version found: 9.5
> NOTICE:  extension "hstore" already exists, skipping
> NOTICE:  extension "postgis" already exists, skipping
> Postgis version found: 2.4
> 
> ERROR: Failed to load nominatim module. Reason:
> CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS 'Nominatim-3.1.0/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text); [nativecode=ERROR:  incompatible library "Nominatim-3.1.0/build/module/nominatim.so": version mismatch
> DETAIL:  Server is version 9.5, library is version 9.2.]

**Comment by mtmail** [comment]
So I believe your `libpq.so` is version 9.2 while your postgres server (try `psql --version`) is version 9.5.

Check the output of the `cmake` command during the installation. https://github.com/openstreetmap/Nominatim/blob/master/vagrant/Install-on-Centos-7.sh#L158

Example for latest Ubuntu operating system
```
-- Found PostgreSQL: /usr/lib/x86_64-linux-gnu/libpq.so (found version "10.4 (Ubuntu 10.4-2.pgdg14.04+1)") 
```

https://serverfault.com/questions/316703/how-to-install-libpq-dev-on-centos-5-5 might give hints how to update the library. You can run the cmake and make steps several times until you see them matching.
