### ISSUE TITLE
Address hierarchy's field "county" is randomly filled with county or commune data

### ISSUE THREAD

**Issue by krrybarc** [openstreetmap/Nominatim#1070]
I have noticed strange, undeterministic behaviour in the Nominatim API regarding the address hierarchy returned with the geocoded coordinates. It certainly occurs with Polish data, but I think I have seen it with Nordic (SE, FI, NO) as well. 

In one case Nominatim puts commune data into "county" field (see address.county - "**gmina** Nowy Targ"):

[ {
  "place_id" : "30017894",
  "licence" : "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type" : "way",
  "osm_id" : "323880733",
  "boundingbox" : [ "49.4131799", "49.4632921", "19.8897876", "19.9883404" ],
  "lat" : "49.4399151",
  "lon" : "19.9439785",
  "display_name" : "Wielki Rogoźnik, Rogoźnik, gmina Nowy Targ, powiat nowotarski, województwo małopolskie, 34-471, Polska",
  "place_rank" : "17",
  "category" : "waterway",
  "type" : "river",
  "importance" : 0.08125,
  "address" : {
    "river" : "Wielki Rogoźnik",
    "village" : "Rogoźnik",
    "county" : "gmina Nowy Targ",
    "state" : "województwo małopolskie",
    "postcode" : "34-471",
    "country" : "Polska",
    "country_code" : "pl"
  },
  "extratags" : { },
  "namedetails" : {
    "name" : "Wielki Rogoźnik"
  }
} ]

And in another case Nominatim puts county data into "county" field (see address.county - "**powiat** kłodzki"): 

[ {
  "place_id" : "2772733",
  "licence" : "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type" : "node",
  "osm_id" : "2009983803",
  "boundingbox" : [ "50.4360684", "50.4361684", "16.23825", "16.23835" ],
  "lat" : "50.4361184",
  "lon" : "16.2383",
  "display_name" : "Karolinka, 5, Zdrojowa, Słone, Kudowa-Zdrój, powiat kłodzki, województwo dolnośląskie, 57-351, Polska",
  "place_rank" : "30",
  "category" : "shop",
  "type" : "convenience",
  "importance" : 0.52025,
  "icon" : "http://osm.abs.assecobs.pl/nominatim/images/mapicons/shopping_convenience.p.20.png",
  "address" : {
    "convenience" : "Karolinka",
    "house_number" : "5",
    "road" : "Zdrojowa",
    "suburb" : "Słone",
    "town" : "Kudowa-Zdrój",
    "county" : "powiat kłodzki",
    "state" : "województwo dolnośląskie",
    "postcode" : "57-351",
    "country" : "Polska",
    "country_code" : "pl"
  },
  "extratags" : { },
  "namedetails" : {
    "name" : "Karolinka"
  }
}, {
  "place_id" : "22408815",
  "licence" : "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type" : "way",
  "osm_id" : "190367945",
  "boundingbox" : [ "50.436081", "50.4362244", "16.2381315", "16.2383714" ],
  "lat" : "50.43616325",
  "lon" : "16.238244685024",
  "display_name" : "5, Zdrojowa, Słone, Kudowa-Zdrój, powiat kłodzki, województwo dolnośląskie, 57-350, Polska",
  "place_rank" : "30",
  "category" : "building",
  "type" : "yes",
  "importance" : 0.52025,
  "address" : {
    "house_number" : "5",
    "road" : "Zdrojowa",
    "suburb" : "Słone",
    "town" : "Kudowa-Zdrój",
    "county" : "powiat kłodzki",
    "state" : "województwo dolnośląskie",
    "postcode" : "57-350",
    "country" : "Polska",
    "country_code" : "pl"
  },
  "extratags" : { },
  "namedetails" : { }
} ]

All the data is availavble in the "diplay_name" field, but in some cases commune - "gmina" is taken, and for others county - "powiat" is taken. I would like to provide the user with the address hierarchy, but it's of no use if the "county" field is filled randomly. Could anyone help me explain this behaviour?

**Comment by lonvia** [comment]
See #1080. Closing here.
