### ISSUE TITLE
Subdomain wikidata_id.openstreetmap.org to redirect to the corresponding relation

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/Nominatim#1071]
In nowadays the [**OSM relation ID** is a Wikidata property for authority control, with reciprocal use of Wikidata](https://www.wikidata.org/wiki/Property:P402), but this "reciprocal use of Wikidata" is not complete:

* We can point to *OSM relation ID* by the *URL template* `https://www.openstreetmap.org/relation/$1`.

* but, at OSM **we can't point to the *Wikidata ID***... The proposal is something like `https://wikidata_id.openstreetmap.org/$1`.

Example: Berlin is the [entity Q64](http://wikidata.org/entity/Q64) at Wikidata, and the [relation 62422](https://www.openstreetmap.org/relation/62422) at OSM. So,

* `https://www.openstreetmap.org/relation/62422` resolves the *OSM relation ID* of Berlin.
* `https://wikidata_id.openstreetmap.org/Q64` will resolve (same results) *Wikidata ID* of Berlin.

**Comment by lonvia** [comment]
This has nothing to do with Nominatim. If you want to look up a Wikidata ID, use the wikidata service.
