### ISSUE TITLE
Add some ref keys in index

### ISSUE THREAD

**Issue by gustavecha** [openstreetmap/Nominatim#1073]
Hi,

Several mappers and I use to compete some specific ref keys on street cabinets or service buildings
I wonder how it can be possible for Nominatim to index them ?

This may be connex to https://github.com/openstreetmap/Nominatim/issues/523

Some examples are :
https://wiki.openstreetmap.org/wiki/Key:ref:ERDF:gdo
https://wiki.openstreetmap.org/wiki/Key:ref:FR:ARCEP
https://wiki.openstreetmap.org/wiki/Key:ref:FR:PTT

e.g https://www.openstreetmap.org/way/317218591
This building has no postal address, but a ref:ERDF:gdo number which it may be good to find in osm.org search results

There are not so much occurrences currently but this will get more important in few months.
Let me know if you need more input about this

All the best

**Comment by lonvia** [comment]
As said before for power: this is far too niche for Nominatim. This does not only go for these particular ones related to power infrastructure but for all refs that are there for the sole use of referencing to other databases, public or otherwise. These are unlikely to ever be searchable.

**Comment by gustavecha** [comment]
Hi,
Thanks for the reply
I respectably disagree with you about the searchability of those refs.
People who find name=* convenient instead of any ref:* key want objects to show up on search results of osm.org
Refs aren't only dedicated to link with other databases, people can look for them to find a particular feature in the street.
Looking for a street name isn't different than looking for a particular ref. A street name is an actual ref.

**Comment by fgnievinski** [comment]
I'd like to document nominatim's support for ref tags:
https://wiki.openstreetmap.org/wiki/Key:ref#Examples_on_ways

my impression is nominatim generally supports ref tags, except for refs in relations? #413
