### ISSUE TITLE
Cannot restart updates

### ISSUE THREAD

**Issue by gordocabron** [openstreetmap/Nominatim#1074]
Hi,

after a server downtime I tried to restart the updates using pyosmium that were running in a detached screen under my user. I get the following error message:

``
xxxx@geocoder:~$  sudo -u nominatim /srv/nominatim/Nominatim-3.1.0/build/utils/update.php --import-osmosis-all
Currently at sequence 1922 (22/06/2018 19:59:01) - t indexed
/srv/nominatim/.local/bin/pyosmium-get-changes --server https://download.geofabrik.de/europe-updates -o /srv/nominatim/Nominatim-3.1.0/build/osmosischange.osc -s 30 -I 1922
PHP Warning:  unlink(/srv/nominatim/Nominatim-3.1.0/build/osmosischange.osc): No such file or directory in /srv/nominatim/Nominatim-3.1.0/build/utils/update.php on line 303
Traceback (most recent call last):
  File "/srv/nominatim/.local/bin/pyosmium-get-changes", line 22, in <module>
    from osmium.replication import server as rserv
ImportError: No module named osmium.replication
ERROR: updates failed.
``

Any help would be much appreciated!

**Comment by mtmail** [comment]
The PHP warning is harmless, and got fixed in https://github.com/openstreetmap/Nominatim/commit/1d6861 a while back (but after 3.1.0 was released).

The command as you run it works for me, so I think we can rule out file permissions or such.

Try reinstalling the python module. Maybe python got upgraded in the meanwhile?

```
sudo su nominatim
cd
pip install --upgrade pip
# bug in pip version 10.0
# https://stackoverflow.com/questions/28210269/importerror-cannot-import-name-main-when-running-pip-version-command-in-windo
# pip install --user osmium
python -m pip install --user osmium

cd ~/Nominatim/build
./utils/update.php --import-osmosis-all 
```

**Comment by gordocabron** [comment]
mtmail,
Thanks for the answer. It seems to work now.
