### ISSUE TITLE
SQL Error: DB Error: unknown error

### ISSUE THREAD

**Issue by JavidSalmanov** [openstreetmap/Nominatim#1075]
SELECT place_id, 0::int as exactmatch FROM search_name WHERE name_vector @> ARRAY[3386] ORDER BY (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75-(search_rank::float/40) ELSE importance END) DESC LIMIT 20 [nativecode=ERROR:  canceling statement due to statement timeout]

**Comment by mtmail** [comment]
Timeout sounds like the database server is down. Please check your postgresql error log. 

Any other information that might help us to reproduce this error? Nominatim version, operating system, which data was imported, which query was run, if it worked before...

**Comment by lonvia** [comment]
Normal answer when query takes to long. Not a bug.
