### ISSUE TITLE
ubuntu 16.04 - apache2 403 forbidden problem - 127.0.0.1 and 127.0.1.1 mixed

### ISSUE THREAD

**Issue by marcopolo88** [openstreetmap/Nominatim#1078]
![screenshot from 2018-06-30 20-49-22](https://user-images.githubusercontent.com/14142694/42125785-1f9c7e44-7ca7-11e8-8d09-99f7b91354d5.png)
OSM data is imported already, no errors there any more

calling apache2, i do not understand why not all content is served by localhost, the apache2 config seems broken and I cannot resolve it.
If Someone could point me into the right direction? thank you so much

all in all 2 days on this, first with old 2.5 installation that I could not make to handle diff updates, ok decided to give 3.1 a chance, however need to trial and error quite often
this server is needed only for local use - no webserver security aspects to be considered

sudo nano nominatim.conf
nominatim.conf is created as per ubuntu installation guide and active without error messages

```
sudo a2enconf nominatim
Conf nominatim already enabled
ubu@ubu-VirtualBox:/etc/apache2$ 
```

```
Directory "/srv/nominatim/Nominatim-3.1.0/build/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  DirectoryIndex search.php
  Require all granted
</Directory>
Alias /nominatim /srv/nominatim/Nominatim-3.1.0/build/website
```
sites-enabled/000-default.conf file contents (avoided all use of environment variables as they are notoriously non permanent)
```
<VirtualHost *:80>

        ServerAdmin webmaster@localhost
        DocumentRoot /srv/nominatim

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
<Directory "/srv/nominatim/Nominatim-3.1.0/build/website">
  Options FollowSymLinks MultiViews
  AddType text/html   .php
  DirectoryIndex search.php
  Require all granted
</Directory>

Alias /nominatim /srv/nominatim/Nominatim-3.1.0/build/website

</VirtualHost>
```

/etc/hosts file:
```
127.0.0.1	localhost
127.0.1.1	ubu-VirtualBox

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

added ServerName to apache2.conf:
```
# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
ServerName localhost
```

**Comment by mtmail** [comment]
The URLs to CSS files in the HTML are created using the PHP `CONST_Website_BaseURL` variable. 

You can see the default in `<build directory>/settings/settings.php`
```php
@define('CONST_Website_BaseURL', 'http://'.php_uname('n').'/');
```

To overwrite the setting edit `local.php` in the same directory and add something like
```php
@define('CONST_Website_BaseURL', 'http://localhost/nominatim/');
```
though I'm pretty sure just
```php
@define('CONST_Website_BaseURL', '/nominatim/');
```
will work, too. That's what we do in https://github.com/openstreetmap/Nominatim/blob/master/vagrant/Install-on-Ubuntu-16.sh (near the end of the script).


>
> this server is needed only for local use 

Maybe you don't need a webserver at all? Try the `utils/query.php` script which executes PHP directly (and thus faster as well)

```
build$ utils/query.php -h
Usage: query.php
Query database from command line. Returns search result as JSON.

  -h, --help                    Show Help
  -q, --quiet                   Quiet output
  -v, --verbose                 Verbose output
  --search                      Search for given term or coordinate
  --accept-language             Preferred language order for showing search results
  --bounded                     Restrict results to given viewbox
  --nodedupe                    Do not remove duplicate results
  --limit                       Maximum number of results returned (default: 10)
  --exclude_place_ids           Comma-separated list of place ids to exclude from results
  --featureType                 Restrict results to certain features (country, state,city,settlement)
  --countrycodes                Comma-separated list of countries to restrict search to
  --viewbox                     Prefer results in given view box
```

**Comment by marcopolo88** [comment]
thank you @mtmail 
the local.php was maintained, but it was not copied to the build dir
that was all to it. thanks for the prompt fix
also for the direct query approach with query.php, that i was not aware of
however just read, that it does not support reverse geocoding (returning the name and address for coordinates)
