### ISSUE TITLE
Inconsistency in Reverse Geocoding

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1079]
When issuing the call
`https://nominatim.openstreetmap.org/reverse.php?lat=48.6633406&lon=2.1694739&zoom=18&format=xml`

the response XML is:
`
<reversegeocode timestamp="Wed, 27 Jun 18 20:37:34 +0000" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="lat=48.6633406&lon=2.1694739&zoom=18&format=xml">
<result place_id="149396199" osm_type="way" osm_id="339557982" ref="C 2" lat="48.6637295" lon="2.1711255" boundingbox="48.6636207,48.6646961,2.1669847,2.1730246">
Rue du Château, Saint-Jean-de-Beauregard, Palaiseau, Essonne, Ile-de-France, Metropolitan France, 91940, France
</result>
<addressparts>
<road>Rue du Château</road>
<village>Saint-Jean-de-Beauregard</village>
<county>Palaiseau</county>
<state>Ile-de-France</state>
<country>France</country>
<postcode>91940</postcode>
<country_code>fr</country_code>
</addressparts>
</reversegeocode>
`

The `<result>` row goes 
  ...  Palaiseau, Essonne, Ile-de-France, ...
the `<adressparts>` section does not contain **Essonne**. No way to tell which is right.

**Comment by mtmail** [comment]
Palaiseau (`admin_level=7`, https://www.openstreetmap.org/relation/1638083) and Essonne (`admin_level=6`, https://www.openstreetmap.org/relation/7401) both map to the `<addressparts>` field `county`.

admin_level 6 in France is a usually a département, admin_level 7 in France usually an arrondissement. https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

So the `result` is more accurate in listing both. At the same time it's also too accurate (too long to display) and the average reader might say it contains too much information.

**Comment by InI4** [comment]
@mtmail I understand the original data is not optimal? OK, this is bad. But this is not my point. 

My point is arguing with users seeing Essonne everywhere in Nominatim UI, but my app (using the <addressparts> tags) not knowing about it. Shouldn't Nominatim simply deliver consistent results and data issues should be fixed in the data? I mean, there could be more than one county in nesting order in the XML, this is not a map.

**Comment by lonvia** [comment]
Made a collection issue for all these reports. There is really nothing more to say about this, except to give the advise to always take `addressdetails` with a grain of salt and preferably use `display_name` when possible.

Closing in favour of #1080.
