### ISSUE TITLE
reverse lookup returns wrong information for zoom=9 in Berlin

### ISSUE THREAD

**Issue by beinhaerter** [openstreetmap/Nominatim#1081]
[This search with zoom=10](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=52.5&lon=13.5&zoom=10) correctly returns "Lichtenberg, Berlin, Germany (Administrative) 52.5321606,13.5118927" and displays a map with this as a center point.
But [this search with same coords but zoom=9](https://nominatim.openstreetmap.org/reverse.php?format=html&lat=52.5&lon=13.5&zoom=9) returns "Mecklenburg-Strelitz, Mecklenburg-Vorpommern, 17094, Germany (County) 53.487,13.3213183". As you can see in the results latitude and longitude are changed massively.

What I am really trying to achieve is to use the URL "https://nominatim.openstreetmap.org/reverse?format=json&lat=...&lon=...&zoom=...&addressdetails=1" in my project and use/display the display_name. Using zoom=9 I get exactly the display_name that I want (you can check the difference between these examples for [zoom=9](https://nominatim.openstreetmap.org/reverse?format=json&lat=48&lon=8&zoom=9&addressdetails=1) and [zoom=10](https://nominatim.openstreetmap.org/reverse?format=json&lat=48&lon=8&zoom=10&addressdetails=1)). But as zoom=9 does not work for coordinates in Berlin (and probably others) I am forced to use zoom=10.

Regards
Werner

**Comment by lonvia** [comment]
That has been solved with #1054, which is now live on osm.org.
