### ISSUE TITLE
Class 'Transliterator' not found

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1082]
Hi,
Got error as **Class 'Transliterator' not found** while calling geocode in my own setup of Nominatim-3.1.0 in centos7. I am using nginx server and installed php-intl too. (https://github.com/openstreetmap/Nominatim/issues/747).

Note:
Tried as separate test PHP code for Transliterator(as follows) and its working. But in Geocode.php met Class 'Transliterator' not found.

> 
> $str = 'àáâãäçèéêëìíîïñòóôõöùúûüýÿ
> ÀÁÂÃÄÇÈÉÊËÌÍÎÏÑÒÓÔÕÖÙÚÛÜÝ';
> $rule = 'NFD; [:Nonspacing Mark:] Remove; NFC';
> 
> $myTrans = Transliterator::create($rule); 
> echo $myTrans->transliterate($str);
> 

**EDIT: If i called above test PHP in a browser or curl, met the same error. But working fine in terminal**

Thanks in advance for any help.

**Comment by mtmail** [comment]
I tested our CentOS7 Vagrant setup (https://github.com/openstreetmap/Nominatim/tree/master/vagrant), disabled Apache and setup nginx, imported one country (Monaco) but don't see the same error.

```
$ rpm --query centos-release
centos-release-7-5.1804.el7.centos.2.x86_64

[vagrant@localhost build]$ curl 'http://localhost/search.php?q=Monaco&format=json&pretty=1'
[
    {
        "place_id": "100195",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright",
        "osm_type": "node",
        "osm_id": "1790048269",
        "boundingbox": [
            "43.5711424",
            "43.8911424",
            "7.2597576",
            "7.5797576"
        ],
        "lat": "43.7311424",
        "lon": "7.4197576",
        "display_name": "Monaco, 98020, Monaco",
        "class": "place",
        "type": "city",
        "importance": 0.20375,
        "icon": "\/nominatim\/images\/mapicons\/poi_place_city.p.20.png"
    }
]
```

So that rules out SELinux permission issues or missing packages at least.

Did you have to install `php-intl`? Does restarting the services help?
```
sudo systemctl restart nginx
sudo systemctl restart php-fpm
```

Any error messages in `/var/log/php-fpm/`?

Does searching via the command-line work?

```
[vagrant@localhost build]$ utils/query.php --search Monaco
[
    {
        "osm_type": "N",
        "osm_id": "1790048269",
        "class": "place",
        "type": "city",
        ....
```

**Comment by Rajavelu** [comment]
@mtmail Thanks for your response.
No errors in php-fpm.log
Refer below responses:

> Nominatim-3.1.0/build>curl 'http://localhost:8080/search.php?q=Andorro&format=json&pretty=1'
> <br />
> <b>Fatal error</b>:  Class 'Transliterator' not found in <b>/home/sas/Nominatim/Nominatim-3.1.0/lib/Geocode.php</b> on line <b>52</b><br />



> Nominatim-3.1.0/build>utils/query.php --search Andorro
> [
>     {
>         "osm_type": "R",
>         "osm_id": "9407",
>         "class": "boundary",
>         "type": "administrative",
>         "admin_level": "2",
>         "rank_search": "4",
>         "rank_address": "4",
>         "place_id": "102431",
>         "parent_place_id": "0",
>         "housenumber": "-1",
>         "country_code": "ad",
>         "langaddress": "Andorra",
>         "placename": "Andorra",
>         "ref": "Andorra",
>         "lon": "1.5732033",
>         "lat": "42.5407167",
>         "importance": 0.1625,
>         "addressimportance": null,
>         "extra_place": "country",
>         "addresstype": "boundary",
>         "aBoundingBox": [
>             "42.4288238",
>             "42.6559357",
>             "1.4135781",
>             "1.7863837"
>         ],
>         "icon": "http://172.20.13.194/images/mapicons/poi_boundary_administrative.p.20.png",
>         "label": "Country",
>         "name": "Andorra",
>         "foundorder": 0.0018
>     }
> ]



> Nominatim-3.1.0/build>curl 'http://localhost:8080/reverse.php?format=json&lat=42.5407167&lon=1.5732033'
> {"place_id":"102364","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"way","osm_id":"7934428","lat":"42.5355903","lon":"1.5750401","display_name":"Encamp, AD200, Andorra","address":{"town":"Encamp","county":"Encamp","postcode":"AD200","country":"Andorra","country_code":"ad"},"boundingbox":["42.5341492","42.5365136","1.574053","1.5760746"]}sas@172.20.13.194~/Nominatim/Nominatim-3.1.0/build>
> 


If I comment that Transliterator line in Geocode.php. search.php also working fine. So the issue is Transliterator class not accessible from Geocode.php

**Comment by Rajavelu** [comment]
@mtmail Thanks for your response, and which version of php & php-fpm you are using?
If I called above test PHP(with Transliterator) in a browser or in curl, met the same error. But working fine when running in the terminal(php test.php)

**The issue was installed php-7.2.6 and php5-fpm together.**

**Comment by mtmail** [comment]
> which version of php & php-fpm you are using?

The default for CentOS when fresh installed. That's PHP 5.4.

Is it possible you have two different versions of PHP installed on your system?

Try running `php -r 'echo phpversion();'` on command line. And add `var_dump(phpversion());` inside `Geocode.php` to figure out which PHP version is running in the `php5-fpm` environment (the output might go into the webserver error log).

**Comment by lonvia** [comment]
The discussion in this ticket has drifted into matters of generic system and database administration and as such out of scope for this issue tracker. Please use google and generic help sites like stackoverflow to resolve the issue. Closing here.
