### ISSUE TITLE
connection timeout in update.php --init-updates

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1083]
Met the following connection timeout error while init updates.

> /Nominatim-3.1.0/build>./utils/update.php --init-updates
> PHP Warning:  file_get_contents(https://download.geofabrik.de/europe/andorra-updates/state.txt): failed to open stream: Connection timed out in /home/user/Nominatim-3.1.0/build/utils/update.php on line 65
> 
> Cannot find state.txt file at the configured replication URL.
> Does the URL point to a directory containing OSM update data?
> 
> ERROR: replication URL not reachable.
> replication URL not reachable.
> 
> Nominatim-3.1.0/build>curl 'https://download.geofabrik.de/europe/andorra-updates/state.txt'
>  original OSM minutely replication sequence number 3043991
> timestamp=2018-07-04T19\:59\:02Z
> sequenceNumber=1933

**Comment by mtmail** [comment]
Works fine for me (centos7, php5.4)

```
php -r 'echo file_get_contents("https://download.geofabrik.de/europe/andorra-updates/state.txt");'
# original OSM minutely replication sequence number 3043991
timestamp=2018-07-04T19\:59\:02Z
sequenceNumber=1933
```

Check if other URLs work, e.g. 'https://example.com'. If not check if `allow-url-fopen` is set to `On` in your `php.ini` (probably /etc/php.ini) http://www.php.net/manual/en/filesystem.configuration.php#ini.allow-url-fopen

**Comment by lonvia** [comment]
The discussion in this ticket has drifted into matters of generic system and database administration and as such out of scope for this issue tracker. Please use google and generic help sites like stackoverflow to resolve the issue. Closing here.
