### ISSUE TITLE
Error when accessing localhost/nominatim

### ISSUE THREAD

**Issue by suryabh4** [openstreetmap/Nominatim#1088]
I installed nominatim after following instructions on the install page - http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-16/

I restarted apache as instructed. Now I am getting this error in the browser - 

Internal Server Error

Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.

Message: Database request failed

SQL Error: DB Error: insufficient permissions

Details:

select TO_CHAR(lastimportdate - '2 minutes'::interval,'YYYY/MM/DD HH24:MI')||' GMT' from import_status limit 1 [nativecode=ERROR:  permission denied for relation import_status]

----------------
Please advise

**Comment by mtmail** [comment]
Which user is the apache2 process running as? https://serverfault.com/questions/125865/finding-out-what-user-apache-is-running-as

With the Nominatim Ubuntu16 install instructions we assume it's `www-data`. Part of the instructions for example contain `sudo -u postgres createuser www-data` and `build/utils/setup.php` will allow (grant) that user read access to all tables in the `nominatim` database.

Another part in the instructions says `chmod a+x $USERHOME` (which is /srv/nominatim by default) to make sure system processes (and user `www-data`) can access the `nominatim.so` file.

Your issue is likely that whatever user Apache2 is using to render the page cannot access the `nominatim.so` file. `chmod a+x` to that file and all parent directories likely solves it.

**Comment by suryabh4** [comment]
The apache2 is running as user "suryabh". I had changed it from default in the config

suryabh@suryabh:/srv/nominatim/Nominatim-3.1.0/build/utils$ /usr/sbin/service apache2 start
suryabh@suryabh:/srv/nominatim/Nominatim-3.1.0/build/utils$ ps aux | egrep '(apache|httpd)'
root      4703  0.1  0.3 133976 29976 ?        Ss   16:39   0:00 /usr/sbin/apache2 -k start
suryabh   4706  0.0  0.0 134000  7948 ?        S    16:39   0:00 /usr/sbin/apache2 -k start
suryabh   4707  0.0  0.0 134000  7948 ?        S    16:39   0:00 /usr/sbin/apache2 -k start
suryabh   4708  0.0  0.0 134000  7948 ?        S    16:39   0:00 /usr/sbin/apache2 -k start
suryabh   4709  0.0  0.0 134000  7948 ?        S    16:39   0:00 /usr/sbin/apache2 -k start
suryabh   4710  0.0  0.0 134000  7948 ?        S    16:39   0:00 /usr/sbin/apache2 -k start
suryabh   4721  0.0  0.0   5112   840 pts/18   S+   16:39   0:00 grep -E --color=auto (apache|httpd)
suryabh  30481  0.0  0.0   4316   588 pts/17   S+   16:02   0:00 tail -f /var/log/apache2/error.log

I also executed the grant commands - 

sudo -u postgres psql nominatim

GRANT usage ON SCHEMA public TO "suryabh";
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "suryabh";

Permissions on the folder - 
suryabh@suryabh:/srv/nominatim$ pwd
/srv/nominatim
suryabh@suryabh:/srv/nominatim$ ls -lhrt
total 46M
-rwxr-x---  1 suryabh suryabh  46M Jul 11 15:56 Nominatim-3.1.0.tar.bz2
drwxr-x--- 18 suryabh suryabh 4.0K Jul 11 15:57 Nominatim-3.1.0

**Comment by suryabh4** [comment]
output from postgresql log - 
2018-07-11 16:55:43.999 CDT [5383] suryabh@nominatim ERROR:  could not access file "/srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so": Permission denied
2018-07-11 16:55:43.999 CDT [5383] suryabh@nominatim CONTEXT:  PL/pgSQL function make_standard_name(text) line 5 at assignment
2018-07-11 16:55:43.999 CDT [5383] suryabh@nominatim STATEMENT:  SELECT make_standard_name('3039 E MEADOWLARK LN')
2018-07-11 16:56:03.721 CDT [5379] ERROR:  function transliteration(text) does not exist at character 23
2018-07-11 16:56:03.721 CDT [5379] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-07-11 16:56:03.721 CDT [5379] QUERY:  SELECT gettokenstring(transliteration(name))
2018-07-11 16:56:03.721 CDT [5379] CONTEXT:  PL/pgSQL function public.make_standard_name(text) line 5 at assignment
	automatic analyze of table "nominatim.public.placex"

**Comment by mtmail** [comment]
`drwxr-x--- 18 suryabh suryabh 4.0K Jul 11 15:57 Nominatim-3.1.0`

... here (user) `suryabh` can read&write&execute and everybody in (group) `suryabh` can read&execute. What we need is everybody (e.g. postgresql process) to be able to execute.

Run `chmod a+x` on `nominatim.so` and all parent directories down to `/srv`.

**Comment by suryabh4** [comment]
thanks for the quick response. Followed your guidelines. 
Now getting a different error - 
Internal Server Error

Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software. If you think it is a bug, feel free to report it over on Github. Please include the URL that caused the problem and the complete error details below.

Message: Cannot normalize query string (is it a UTF-8 string?)

SQL Error: DB Error: unknown error

Details:

SELECT make_standard_name('3039 E MEADOWLARK LN') [nativecode=ERROR:  could not load library "/srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so": /srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so: cannot open shared object file: Permission denied
CONTEXT:  PL/pgSQL function make_standard_name(text) line 5 at assignment]

**Comment by mtmail** [comment]
That's the same error.

Does the `nominatim.so` file exist? Is the database on the same machine as apache? Does the following command work?
`sudo -u postgres ls -la /srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so`

**Comment by suryabh4** [comment]
Thanks again for your feedback. I tried the change - chmod a+r on the nominatim.so and it seems to have fixed the issue with the error. But I am still not getting any search results -

![image](https://user-images.githubusercontent.com/24609841/42603332-fb97d57c-8532-11e8-9610-008219470e1d.png)

**Comment by mtmail** [comment]
That's good news.

The name of the street in OpenStreetMap data is Meadowlark, not Maedowlark https://www.openstreetmap.org/way/21548732

Is Appleton or Meadowlark itself found?

**Comment by suryabh4** [comment]
yeah I can search for City like - Appleton - 

![image](https://user-images.githubusercontent.com/24609841/42603878-5b49ccbc-8535-11e8-8f2e-00df859a731d.png)

I am new to using OSM but I noticed that when I search with a house number and Street name the search returns valid result. Whereas if I search with house Number + street Name + City + state + Zip the search comes up empty. 

![image](https://user-images.githubusercontent.com/24609841/42603966-cf4ba374-8535-11e8-8f9c-c87b150f89df.png)

With City and Zip
![image](https://user-images.githubusercontent.com/24609841/42604009-22c1396a-8536-11e8-8059-2bf41e560b41.png)

I did import the Tiger data in the DB.

Is there a recommended way to search in OSM ?

**Comment by mtmail** [comment]
Nominatim installation issues solved. Closing this issue.

The street Security Boulevard is technically outside the city boundaries of Green Bay (https://www.openstreetmap.org/relation/251488). I can't tell if the data in OpenStreetMap is wrong or outdated here.

> Is there a recommended way to search in OSM ?

Commas between address parts help. Lowest to highest (street -> state/country) order for most western world countries is best. Nominatim has trouble when street number is right next to the postcode. Coverage of US 9 digit postcodes is too low (better shorten to 5 digit).

**Comment by suryabh4** [comment]
@mtmail Thanks for your help.
