### ISSUE TITLE
External UK postcode table not found

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1091]
Hi,
Got the following message while setup Nominatim 
**WARNING: external UK postcode table not found.**

My Nominatim_src/data directory contains the following files:
country_name.sql  country_naturalearthdata.sql  country_osm_grid.sql.gz  gb_postcode_table.sql  us_postcode.sql  wikipedia_article.sql.bin  wikipedia_redirect.sql.bin  words.sql

Sorry, If this is not an issue.

**One more doubt regarding Flatnode files:**
I have setup Postgres as cluster model (master & slave).
Imported planet data with Flatnode_File config in master server & DB data will sync to slave(not flatnode file)
Now I want to query(geocode/reverse) in both master & slave. Is there any problem(performance/data related) will arrive while querying in slave?

**Comment by lonvia** [comment]
It is not an issue. That's why it is only a warning that tells you that you did not download the optional UK postcodes. See http://nominatim.org/release-docs/latest/admin/Import-and-Update/#uk-postcodes.

**Comment by Rajavelu** [comment]
Oh! Sorry. I thought i downloaded the same.
Is it possible to add UK postal codes after initial import of planet data?

**Comment by Rajavelu** [comment]
@lonvia Thanks for your reply. Sorry, i thought its already downloaded. Now i want to import the same(gb_postcode.sql, after initial import). Need to create UK postcode table before import?

**Comment by mtmail** [comment]
@Rajavelu 

Table schema is here https://github.com/openstreetmap/Nominatim/blob/master/data/gb_postcode_table.sql

Then run `GRANT SELECT ON TABLE gb_postcode TO "{www-user}";` (found in file `sql/tables.sql`). `{www-user}` needs to be replaced with the user Apache2 runs under, e.g. on Ubuntu that's `www-data`.

Now import the downloaded `gb_postcode_data.sql.gz` file

Lastly run `utils/setup.php --calculate-postcodes` from your `build` directory. This will copy data form the `gb_postcode` table to the `location_postcodes` table. Takes 20 minutes.
