### ISSUE TITLE
Searching for streets using abbreviated names fails in certain cases

### ISSUE THREAD

**Issue by jdhoek** [openstreetmap/Nominatim#1093]
On holiday in Italy I attempted to look up a street in Lecco called the [*Via Bovara*](https://www.openstreetmap.org/way/51097837), and was surprised to find that OSM couldn't find the relevant result. In this case the street itself was present on the map, but only with its official full name: *Via Giuseppe Bovara*.

The street in OSM does not have a `short_name` defined, which might have helped, but because this way of abbreviating (i.e., leaving out the given name of the person the street was named after) seems so common, it should probably work without having a dedicated `short_name`.

Some digging showed that my query (*Via Bovara, Lecco*) was problematic:

# Search results

## Via Bovara, Lecco

* Via Bovara, Piazza Rossé, Valmadrera, LC, Lombardy, 23900, Italy 

*(no further results)*

This is a different street in a nearby town. **This search query fails to show the Via Giuseppe Bovara in Lecco (the town).**

## Lecco, Via Bovara

* Via Bovara, Piazza Rossé, Valmadrera, LC, Lombardy, 23900, Italy

*more results*

*(the first three results, with one more irrelevant result following)*

This search query works with only one *more results* click.

## Via Bovara

* Via Bovara, Piazza Rossé, Valmadrera, LC, Lombardy, 23900, Italy

*more results*

* Bovara, Trevi, PG, Umbria, 06039, Italy (suburb)

*more results*

* Via Giuseppe Bovara, Castello, Lecco, LC, Lombardy, 23900, Italy 

*(the first three results, with a couple of other irrelevant results following)*

This search query works, but takes some digging.

## Via Giuseppe Bovara

Works as expected.

## Via Giuseppe Bovara, Lecco

Works as expected.

## Lecco, Via Giuseppe Bovara

Works as expected.

# Expected results

I would expect that both *Via Bovara, Lecco* and *Lecco, Via Bovara* return the same results.

**Comment by ernstgumpinger** [comment]
Hi there,
I had the same problem with searching for a street in Mauguio, France. The official street name is _rue antoine de saint-exupéry_. Searching for _rue saint exupéry_ gives "No restults found". I also believe that _rue saint exupéry_ should give the expected result _rue antoine de saint-exupéry_ ...
 Is there any possibility to add a link in a database between the search key and the expected result ?

**Comment by mtmail** [comment]
@ernstgumpinger There is https://wiki.openstreetmap.org/wiki/Nominatim/TestCases and last week we added support for the https://github.com/geocoders/geocoder-tester/tree/master/geocoder_tester/world format. A regular test suite/output is still missing.

**Comment by ernstgumpinger** [comment]
Ok great, thank you for your answer. Can I already add new queries and expected results to https://github.com/geocoders/geocoder-tester/blob/master/geocoder_tester/world/france/languedocroussillon/test_from_user_input.csv for example ?

**Comment by mtmail** [comment]
@ernstgumpinger Yes, I think so. I don't know if they prefer a new file or just add rows to an existing file. https://github.com/geocoders/geocoder-tester/pulls?q=is%3Apr+is%3Aclosed

**Comment by lonvia** [comment]
This has been reported quite a lot of times already. Closing in favour of #679.

**Comment by jdhoek** [comment]
@lonvia I'm not seeing the *Lecco, Via Bovara* (works) versus *Via Bovara, Lecco* (fails) issue I've reported here in #679 though, unless I'm overlooking it.
