### ISSUE TITLE
I cannot update data 

### ISSUE THREAD

**Issue by touatily** [openstreetmap/Nominatim#1096]
When running 
`sudo -u nominatim ./utils/update.php --init-updates`

I get this:

> 2018-07-17 09:34:04 == Create Functions
> NOTICE:  drop cascades to function get_addressdata(bigint,integer)
> NOTICE:  drop cascades to function get_wikipedia_match(hstore,character varying)
> Summary of warnings:
> 
> 
> 2018-07-17 09:34:04 == Setup finished.
> sh: 1: /nonexistent: not found
> ERROR: Error running pyosmium tools
> Error running pyosmium tools
>

**Comment by mtmail** [comment]
So it tries to run `CONST_Pyosmium_Binary`
https://github.com/openstreetmap/Nominatim/blob/master/utils/update.php#L84

The default is indeed `/nonexistent`. When you follow the instructions in http://nominatim.org/release-docs/latest/admin/Import-and-Update/#installing-the-newest-version-of-pyosmium you should have an entry `build/settings/local.php` which points to the binary.

**Comment by lonvia** [comment]
#1099 tries to improve the error message. Closing here.
