### ISSUE TITLE
Postgres automatic analyze fails to find function

### ISSUE THREAD

**Issue by otbutz** [openstreetmap/Nominatim#1097]
```
2018-07-17 06:59:35.908 UTC [30641] ERROR:  function transliteration(text) does not exist at character 23
2018-07-17 06:59:35.908 UTC [30641] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-07-17 06:59:35.908 UTC [30641] QUERY:  SELECT gettokenstring(transliteration(name))
2018-07-17 06:59:35.908 UTC [30641] CONTEXT:  PL/pgSQL function public.make_standard_name(text) line 5 at assignment
        automatic analyze of table "nominatim.public.placex"
```

The following works though:
```
# psql -d nominatim -U www-data -c "SELECT transliteration('some w€êîrd text')"
 transliteration
-----------------
 some weird text
(1 row)
```
```
# psql -d nominatim -U postgres -c "SELECT transliteration('some w€êîrd text')"
 transliteration
-----------------
 some weird text
(1 row)
```

A search with Nominatim doesn't trigger any errors aswell. Seems like the analyzer process doesn't pick up the function correctly?

OS: Ubuntu 18.04
Postgres version: 10.4
Postgis version: 2.4

**Comment by mtmail** [comment]
I once chased this error message but couldn't figure it out. You probably see it in your error exactly every minute. When you restart postgresql it's still every minute just slightly shifted. When you remove any traffic from the database (e.g. shut down webserver) it still happens. When you remove autovacuuming it disappears. Since searches themselves are not affected I ignore it.

**Comment by lonvia** [comment]
@mtmail Did you also see this with Postgres 10.4 or also with earlier versions?

**Comment by mtmail** [comment]
@lonvia 10.4. I can't remember seeing it in older versions and don't have old log files to check.

**Comment by otbutz** [comment]
Done: https://www.postgresql.org/message-id/2118571382.49.1531905290326.JavaMail.tbutz%40BART

**Comment by otbutz** [comment]
To quote Tome Lane:
> In recent PG releases, autovacuum executes stuff under a restrictive
search_path setting (just pg_catalog, in fact).  So you need to do
something explicit to reference stuff in other schemas; either schema
qualify the name, or add a "SET search_path" clause to the function
definition.  This is good practice anyway: what you're seeing is that this
function fails with any search_path other than the one you use by default.

User search path:
```
# psql -U www-data -d nominatim -c "SHOW search_path;"
   search_path
-----------------
 "$user", public
(1 row)
```

Execution with the user search path works:
```
# psql -U www-data -d nominatim -c "SELECT transliteration('some w€êîrd text');"
 transliteration
-----------------
 some weird text
(1 row)
```

Execution with a restricted search path doesn't:
```
# psql -U www-data-d nominatim -c "SET search_path TO pg_catalog; SELECT transliteration('some w€êîrd text');"
ERROR:  function transliteration(unknown) does not exist
LINE 1: SET search_path TO pg_catalog; SELECT transliteration('some ...
                                              ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

But it works if the function is addressed by its schema:
```
# psql -U www-data -d nominatim -c "SET search_path TO pg_catalog; SELECT public.transliteration('some w€êîrd text');"
 transliteration
-----------------
 some weird text
(1 row)
```

**Comment by lonvia** [comment]
Thanks for following up on this.  Could you confirm that the following will fix the issue for you:

```
--- a/sql/functions.sql
+++ b/sql/functions.sql
@@ -35,7 +35,7 @@ CREATE OR REPLACE FUNCTION make_standard_name(name TEXT) RETURNS TEXT
 DECLARE
   o TEXT;
 BEGIN
-  o := gettokenstring(transliteration(name));
+  o := public.gettokenstring(public.transliteration(name));
   RETURN trim(substr(o,1,length(o)));
 END;
 $$
```
You need to rerun `./utils/setup.php --create-functions--enable-diff-updates ` after applying the patch.

I do wonder though, how the analyser managed to find make_standard_name in the first place. It is in the public namespace as well.

**Comment by otbutz** [comment]
Will give it a try today. But maybe we should prefix all function calls in tables/indices/triggers.
The schema should also be configurable. `public` is perfectly acceptable as default but it should be possible to change it.

**Comment by mtmail** [comment]
Tested it on Ubuntu 18, postgresql 10 and the error messages are gone after the patch.

**Comment by otbutz** [comment]
Fixed it for me aswell.

**Comment by lonvia** [comment]
I've pushed the fix now but I'm not entirely happy with it. Prefixing each functions really doesn't improve readability. So eventually we should probably go to a configurable schema which is set for each function via SET schema_path.

**Comment by otbutz** [comment]
+1 for a configurable schema
