### ISSUE TITLE
record "location" has no field "postcode"

### ISSUE THREAD

**Issue by touatily** [openstreetmap/Nominatim#1098]
Executing `./utils/update.php --import-osmosis-all`

getting this:

> Starting rank 14
> index_placex: UPDATE failed: ERROR:  record "location" has no field "postcode"
> CONTEXT:  SQL statement "SELECT location.postcode is not null"
> PL/pgSQL function placex_update() line 645 at IF
> Error: 1

**Comment by touatily** [comment]
More information, from the web interface, when type an url, fro example:

`ip-address/nominatim/reverse.php?lat=56.4520581&lon=4.804445&addressdetails=1`


Message: Could not lookup place

SQL Error: DB Error: no such table

Details:

SELECT     osm_type,    osm_id,    class,    type,    admin_level,    rank_search,    rank_address,    min(place_id) AS place_id,    min(parent_place_id) AS parent_place_id,    -1 as housenumber,    country_code,get_address_by_language(place_id,-1,ARRAY['short_name:fr-FR','name:fr-FR','short_name:fr','name:fr','short_name:en-US','name:en-US','short_name:en','name:en','short_name','name','brand','official_name:fr-FR','official_name:fr','official_name:en-US','official_name:en','official_name','ref','type']) AS langaddress,    get_name_by_language(name,ARRAY['short_name:fr-FR','name:fr-FR','short_name:fr','name:fr','short_name:en-US','name:en-US','short_name:en','name:en','short_name','name','brand','official_name:fr-FR','official_name:fr','official_name:en-US','official_name:en','official_name','ref','type']) AS placename,    get_name_by_language(name, ARRAY['ref']) AS ref,    avg(ST_X(centroid)) AS lon,     avg(ST_Y(centroid)) AS lat,     COALESCE(importance,0.75-(rank_search::float/40)) AS importance, (SELECT max(ai_p.importance * (ai_p.rank_address + 2))   FROM place_addressline ai_s, placex ai_p   WHERE ai_s.place_id = min(CASE WHEN placex.rank_search < 28 THEN placex.place_id ELSE placex.parent_place_id END)     AND ai_p.place_id = ai_s.address_place_id      AND ai_s.isaddress      AND ai_p.importance is not null) AS addressimportance,    (extratags->'place') AS extra_place  FROM placex WHERE place_id in (7453495)    AND (        placex.rank_address between 0 and 30     OR (extratags->'place') = 'city'       )     AND linked_place_id is null  GROUP BY      osm_type,      osm_id,      class,      type,      admin_level,      rank_search,      rank_address,      housenumber,     country_code,      importance,      langaddress,      placename,      ref,      extratags->'place'  [nativecode=ERROR:  relation "location_postcode" does not exist
LINE 2:       FROM location_postcode
                   ^
QUERY:  select parent_place_id, country_code, rank_address, postcode, 'place', 'postcode'
      FROM location_postcode
      WHERE place_id = in_place_id
CONTEXT:  PL/pgSQL function get_addressdata(bigint,integer) line 49 at SQL statement
PL/pgSQL function get_address_by_language(bigint,integer,text[]) line 12 at FOR over SELECT rows]

**Comment by mtmail** [comment]
`relation "location_postcode" does not exist` is the main error to look at.

The table got introduced in Nominatim v3.1 (https://www.nominatim.org/release-history/, see the release notes). It is possible you updated the Nominatim code but didn't reimport the database? The release notes has a link to a migration guide.

**Comment by touatily** [comment]
I followed the instructions for migartion 

and I got this error:

> Starting rank 14
> index_placex: UPDATE failed: ERROR:  record "location" has no field "postcode"
> CONTEXT:  SQL statement "SELECT location.postcode is not null"
> PL/pgSQL function placex_update() line 645 at IF
> ERROR: Error executing external command: /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 3 -r 5 -R 25
> Error executing external command: /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 3 -r 5 -R 25
>

**Comment by touatily** [comment]
I followed the steps in the migrations guide: [migration](http://nominatim.org/release-docs/3.1.0/admin/Migration/#300-310)

Everything was ok except the last one : `./utils/setup.php --calculate-postcodes --index --index-noanalyse`

It generated the error I shared in my previous comment.

**Comment by lonvia** [comment]
Try running the following SQL on your database:

```
drop type if exists nearfeaturecentr cascade;
create type nearfeaturecentr as (
  place_id BIGINT,
  keywords int[],
  rank_address smallint,
  rank_search smallint,
  distance float,
  isguess boolean,
  postcode TEXT,
  centroid GEOMETRY
);
```

then rerun the `setup.php` command.

**Comment by touatily** [comment]
I created the type, then when I run the setup.php I got this:


> Starting rank 12
> index_placex: UPDATE failed: ERROR:  function getnearfeatures(smallint, geometry, integer, integer[]) does not exist
> LINE 1: SELECT * from getNearFeatures(NEW.partition,
>                       ^
> HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
> QUERY:  SELECT * from getNearFeatures(NEW.partition,
>                                   CASE WHEN NEW.rank_search >= 26
>                                              AND NEW.rank_search < 30
>                                        THEN NEW.geometry
>                                        ELSE place_centroid END,
>                                   search_maxrank, isin_tokens)
> CONTEXT:  PL/pgSQL function placex_update() line 598 at FOR over SELECT rows
> ERROR: Error executing external command: /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 3 -r 5 -R 25
> Error executing external command: /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 3 -r 5 -R 25

**Comment by lonvia** [comment]
Bother. Running `./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions` again should fix that last issue.

**Comment by touatily** [comment]
This solved the issue.
Thanks.
