### ISSUE TITLE
Japanese, address without Comma should be considered the same character.

### ISSUE THREAD

**Issue by jeltaqq** [openstreetmap/Nominatim#1100]
Search results for example. "大阪市, 中央区, 大手前二丁目" and "大阪市中央区大手前二丁目" should produce identical results.
This maybe an exceptional address format, but with the same contents.

```
Address
Local name 	Type 	OSM 	Address rank 	Admin level 	Distance 	
大手前二丁目 	place:hamlet 	node 2441090307 	16 		0 	details >
中央区 	place:suburb 	relation 358727 	16 	8 	0 	details >
大阪市 	place:city 	relation 358674 	14 	7 	0 	details >
大阪府 	place:province 	relation 341906 	8 	4 	0 	details >
540-0008 	place:postcode 		5 		0 	
日本 	place:country 	relation 382313 	4 	2 	~2 m 	details >
jp 	place:country_code 		4 		0 	
```
https://nominatim.openstreetmap.org/details.php?place_id=25170580

**Comment by lonvia** [comment]
With #1412 resolved, we are now doing better for searches without comma. If this is still an issue, please provide a number of example queries together with the expected result.

**Comment by lonvia** [comment]
Closing for now. Feel free to reopen if there is still trouble.

**Comment by jeltaqq** [comment]
Thank you lonvia. It's working as expected.
