### ISSUE TITLE
Geocoding special addresses (Mannheim, Germany)

### ISSUE THREAD

**Issue by BugHunter2k** [openstreetmap/Nominatim#1101]
In Mannheim (Germany) there is the so called 'Quadratestadt' where addresses are a little bit different. 
I've seen that nominatim couldn't geocode these addresses. Is this known and are there plans for fixing this?

This is what it looks like on map: https://www.openstreetmap.org/#map=16/49.4886/8.4647

Here some Informations:
https://en.wikipedia.org/wiki/Mannheim#Block_Numbering_and_Computer_Mapping
https://de.wikipedia.org/wiki/Quadratestadt

**Comment by lonvia** [comment]
Nominatim has no problems whatsoever with these addresses provided they are tagged correctly. Example:

https://nominatim.openstreetmap.org/search.php?q=C3+17%2C+Mannheim

Each Quadrat is currently tagged already with `place=neighbourhood` and `name=<quadrat number>`. To add an address to that put `addr:place=<quadrat number>` together with `addr:housenumber=xx`. Do _not_ tag any `addr:street`. I know that it is common practice in Mannheim at the moment to use both `addr:place` and `addr:street` but that is wrong. The addresses do not refer to a street.
