### ISSUE TITLE
Nominatim in Jupyter Notebook

### ISSUE THREAD

**Issue by reuschp** [openstreetmap/Nominatim#1103]
Hi there,

I am new to OSM and wanted to play around with it in a Jupiter Notebook.

I checked out the readme and wanted to implement the example.
But somehow it does not do what it is supposed to.
Please check out the error messages in the attachment.

Any suggestion is greatly appreciated.

Thanks
Pascal

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/41440181/42948688-572ac6cc-8b70-11e8-8c13-9e62c385ec2f.png">

**Comment by lonvia** [comment]
You have reached the wrong issue tracker. You need to ask the people who wrote the python module, likely https://github.com/mocnik-science/osm-python-tools in that case.
