### ISSUE TITLE
postal code calculation in New Zealand

### ISSUE THREAD

**Issue by kkaiser** [openstreetmap/Nominatim#1106]
Hello,

I was wondering how nominatim calculates postal codes, suburbs etc. in New Zealand. I have a lot of cases where it doesn't make sense. As an example take `487 Dominion Road, Mount Eden, Auckland 1024` which results in:
```
({'house_number': '487',
  'road': 'Dominion Road',
  'suburb': 'Kingsland',
  'city': 'Albert-Eden',
  'state': 'Auckland',
  'postcode': '1026',
  'country': 'New Zealand/Aotearoa',
  'country_code': 'nz'},
 -36.8860396,
 174.7475602)
```
Now the lat/lon coordinates are perfectly fine, but `postcode`, `suburb` and also `city` are quite questionable, here some sources:
* official: https://www.nzpost.co.nz/tools/address-postcode-finder/address/352746/487-dominion-road-mount-eden-auckland-1024
* resolved as: https://nominatim.openstreetmap.org/details.php?place_id=227601607
* resolved postal code is 1026 which is [Avondale](https://nominatim.openstreetmap.org/details.php?place_id=334908) and as the link shows nominatim has the correct postal for this suburb.
* mentioned suburb [Kingsland](https://nominatim.openstreetmap.org/details.php?place_id=260868) would be postal code 1021, which is also correct for the suburb as place itself.

So I would expect:
```

({'house_number': '487',
  'road': 'Dominion Road',
  'suburb': 'Mount Eden',
  'city': 'Auckland',
  'state': 'Auckland',
  'postcode': '1024',
  'country': 'New Zealand/Aotearoa',
  'country_code': 'nz'},
 -36.8860396,
 174.7475602)
```
* [Mount Eden](https://nominatim.openstreetmap.org/details.php?place_id=27695677)
* [1024](https://nominatim.openstreetmap.org/details.php?place_id=27695677)

Some more examples:
* 7 McGregor Street, Wellington 6022 => resolved to 6023
* 107 College Road, Edgecumbe 3120 => resolved to 3193

It seems like the postal code areas/polygons are fine but the calculation if a point is inside a polygon doesn't fit.

**Comment by lonvia** [comment]
This all looks like a severe case of missing data in OpenStreetMap.

There are no place areas or admin boundaries mapped for the suburb, so Nominatim has to take an educated guess from the place nodes, which tends to go wrong.

Postcode coverage doesn't look better. The house in question does not have a postcode and neither does anything in the vicinity. The only postcodes with 1024 are in the area of Edenvale Cresent, so naturally Nominatims guess about where the area for that postcode should be is off.

For a more in-depth explanation how postcodes are computed from OSM data see [this diary post](https://www.openstreetmap.org/user/lonvia/diary/43143).

Closing here as this is a data issue not an issue with the software.
