### ISSUE TITLE
Implement Fuzzy Search

### ISSUE THREAD

**Issue by ADepic** [openstreetmap/Nominatim#1107]
Currently you have to spell / search you result exactly to get a desired result. By implementing [Fuzzy Search](https://en.wikipedia.org/wiki/Approximate_string_matching) and/or [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) nominatim, and by extension openstreetmap,  will be greatly improved

**Comment by lonvia** [comment]
Duplicate of #759.
