### ISSUE TITLE
Allow custom locations for PHP binary

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/Nominatim#1109]
All utility scripts and tests currently expect that the php binary is at `/usr/bin/php`. This can be worked around when calling utility scripts by explicitly using a different binary but fails when the scripts are invoked from within another script, most notably during tests and in `utils/update.php`.

Allowing custom PHP binaries includes:
* detect PHP binary in `CMakeLists.txt` and allow to overwrite the automatic detection
* replace all shebangs in utility scripts with detected PHP binary on install
* use PHP_BINARY when calling php scripts from other php
* use detected PHP binary in tests

**Comment by otbutz** [comment]
Why not `#!/usr/bin/env  php` ?

**Comment by lonvia** [comment]
Possibly a better default, yes. I still think being able to configure as well would be nice.

**Comment by ThomasBarris** [comment]
I need help to understand 
> use PHP_BINARY when calling php scripts from other php
If other scripts call php scripts in utils/ the shebang of the callee is used as the caller does not use a link to a specific php binary afaik. How should other scripts use PHP_BIN?

**Comment by lonvia** [comment]
The shebang is only used when executing a script directly, e.g. as `./utils/setup.php`. You can always chose to use a different php binary for executing the script by calling <php executable> <script>, e.g. `/usr/local/bin/php-7.2 utils/setup.php`. This is what the PHP scripts should do. Instead of calling scripts directly (`passthru(CONST_InstallPath.'/utils/setup.php'`), use the same php binary as the currently executed php script. That binary is available in [PHP_BINARY](http://php.net/manual/en/reserved.constants.php), so something along the lines `passthru(PHP_BINARY.' '.CONST_InstallPath.'/utils/setup.php'` should work.

**Comment by lonvia** [comment]
Fixed in 38304136.
