### ISSUE TITLE
Wrong castelruggero name/location

### ISSUE THREAD

**Issue by Gaetanodaff** [openstreetmap/Nominatim#1116]
Dear All,
I do liven in Castel Ruggero.
The actual name is Castel Ruggero.
the street name is Via di Castel Ruggero, 33.
Linked to my business Castel Ruggero. 
website is www.castelruggero.com
FB page https://www.facebook.com/fattoriacastelruggero/
When opened the location is sending us in Croatia, not Italy. 
Please correct the details.

Thanks 
Gaetano d'Afflitto

**Comment by mtmail** [comment]
The building was named "Castelruggero" in OpenStreetMap 7 years ago. I corrected the name based on the website. https://www.openstreetmap.org/changeset/61014187

It now gets found
https://www.openstreetmap.org/search?query=Castel+Ruggero

If you want to change the name of the street, you can use the 'Edit' button (similar to wikipedia), see https://www.openstreetmap.org/fixthemap
