### ISSUE TITLE
Import and keep up-to-date multiple country extracts 

### ISSUE THREAD

**Issue by touatily** [openstreetmap/Nominatim#1117]
The solution provided in [issue #60](https://github.com/openstreetmap/Nominatim/issues/60) doesn't really work for me

It generates many errors: 
* Caused by: java.io.FileNotFoundException: europe_france_martinique.osc.gz (Permission denied)
* All osc.gz files are with 0 nodes.

**Comment by mtmail** [comment]
> It generates many errors

Please post what you ran and all errors

> `FileNotFoundException`

Does the file exist?

> `Permission denied`

Have you checked the file permissions?

**Comment by touatily** [comment]
The first I run the script, there no "Permission denied" error, it creates all directories and *.osc.gz files

Next times, I tells "Permission denied" even if I remove all ..osc.gz  files !
File permissions are good I think, the user "nominatim has write access"

**Comment by touatily** [comment]
Even the first times, .osc.gz files have 0 nodes:

> Using XML parser.
>   parse time: 0s
> Node stats: total(0), max(0) in 0s
> Way stats: total(0), max(0) in 0s
> Relation stats: total(0), max(0) in 0s
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
>

**Comment by mtmail** [comment]
You need to run the script line by line. Then report which line it fails, what the exact input and output is. We can't run the script for you or start guessing.

**Comment by touatily** [comment]
* The first time that I run the script with directory or file already created, it executes well but all osv.gz files are empty (with 0 nodes)


* Next times:
The ligne that fails is 
`/usr/bin/osmosis --rri workingDirectory=${DIR}/. --wxc ${FILENAME}.osc.gz`
telling permission denied !

**Comment by mtmail** [comment]
Did you try the suggestion in https://github.com/openstreetmap/Nominatim/issues/60#issuecomment-307757305 ?

**Comment by mtmail** [comment]
Please post the full script you're running.

Which version of `osmosis` are you running?

What is the output of `ls -la $NOMINATIM/updates/*/*`

**Comment by touatily** [comment]
* Script (I changed the extension from sh to txt) : [import_data.txt](https://github.com/openstreetmap/Nominatim/files/2224302/import_data.txt)
* Version Osmosis : 0.44.1
* `ls -la $NOMINATIM/updates/*/*`:

> -rw-r--r-- 1 nominatim nominatim 76 Jul 24 16:13 updates/europe_belgium/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_belgium/download.lock
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_belgium/state.txt
> -rw-r--r-- 1 nominatim nominatim 75 Jul 24 16:13 updates/europe_france/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_france/download.lock
> -rw-r--r-- 1 nominatim nominatim 86 Jul 24 16:13 updates/europe_france_guadeloupe/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_france_guadeloupe/download.lock
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_france_guadeloupe/state.txt
> -rw-r--r-- 1 nominatim nominatim 82 Jul 24 16:13 updates/europe_france_guyane/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_france_guyane/download.lock
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_france_guyane/state.txt
> -rw-r--r-- 1 nominatim nominatim 86 Jul 24 16:13 updates/europe_france_martinique/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_france_martinique/download.lock
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_france_martinique/state.txt
> -rw-r--r-- 1 nominatim nominatim 83 Jul 24 16:13 updates/europe_france_mayotte/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_france_mayotte/download.lock
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_france_mayotte/state.txt
> -rw-r--r-- 1 nominatim nominatim 83 Jul 24 16:13 updates/europe_france_reunion/configuration.txt
> -rw-r--r-- 1 nominatim nominatim  0 Jul 24 17:26 updates/europe_france_reunion/download.lock
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_france_reunion/state.txt
> -rw-r--r-- 1 nominatim nominatim 84 Jul 24 17:26 updates/europe_france/state.txt
>

**Comment by mtmail** [comment]
The `state.txt` file contain a timestamp and sequence number of the last applied changes to your database. If the file doesn't exist yet it will be created and thus it points to today's date. When you run the script on the same day (today) there wouldn't be any changes to download.

Example:

The file `updates/europe_france_reunion/state.txt` probably contains sequence 1947 (see http://download.geofabrik.de/europe/france/reunion-updates/state.txt). Try replacing it with older state.txt data, e.g. http://download.geofabrik.de/europe/france/reunion-updates/000/001/931.state.txt and it should create a .osc.gz file covering 16 days. (Don't import that into your database).

When you know the date of the original import you can set the state.txt accordingly to catch up with the latest OpenStreetMap data. If you don't know the date you can check the `import_status` table in the nominatim database.

**Comment by touatily** [comment]
Why souldn't I import that into my database? is it a mistake to re-import data?

`select * from import_status;` gives this:

>    lastimportdate    | sequence_id | indexed
> ---------------------+-------------+---------
>  2018-07-23 19:59:01 |        1952 | t
> (1 row)

Is it for all coutries or only the county that I specified in `settings/local.php`

**Comment by mtmail** [comment]
> Why souldn't I import that into my database?

I just mean my example of the last 16 days.

> select * from import_status; gives this:

Yeah, I removed that from my previous comment. It's the latest imported country, so it's not clear which one. The date helps though to find the right sequence_ids for each state.txt files.

**Comment by touatily** [comment]
The script seems to do its jobs well, it imports data.
However, in the web interface, the date orresponding to the data last update hasn't changed!

Is it normal ? or should I add a command in the script that modifies this date?

**Comment by mtmail** [comment]
Normal I think. The date comes from the `import_status` table. The custom script (using osmosis) is not writing into the table (`build/utils/update.php` doe, but that's not used here for multiple countries).

**Comment by touatily** [comment]
Last questions:
question1:
If the original import was done last month for example, and my `state.txt` contains the sequence of today, 
When I run the script tomorrow, `update.php --import-diff' will import updates data since last month or only from today ?
In other words, if I specify a wrong sequence number (greater than the one of the original import) in my `state.txt` file, would I miss some data?

question2:
If I specify a sequence number smaller than the one of the actual import, what will happen exactly?

**Comment by touatily** [comment]
You didn't answer my last question !

**Comment by mtmail** [comment]
If you set the wrong date (sequence number, state.txt) as first value for an incremental update then you end up with inconsistent data. Too early and and the update will try to create places that already exist in the database, too late and and you miss places that exist in OpenStreetMap.
