### ISSUE TITLE
Nominatim is down

### ISSUE THREAD

**Issue by LNFWebsite** [openstreetmap/Nominatim#1118]
Not sure how else to notify the devs, but as of 7/24/2018 23:05 PM UTC, the OSM Nominatim server is down.

http://www.isitdownrightnow.com/nominatim.openstreetmap.org.html states that it has been down for more than a week.

Just wanted to let you guys know.

**Comment by mtmail** [comment]
Started 9pm UTC, I emailed https://wiki.osmfoundation.org/wiki/Operations_Working_Group just in case. 

t's my understanding that one of the servers is literally traveling to another country (London->Amsterdam) right now but not both. https://twitter.com/OSM_Tech/status/1021758931650134017

http://www.isitdownrightnow.com/ might be IP blocked and always show the service down. 

![image](https://user-images.githubusercontent.com/3727288/43174325-bd02a27e-8fb9-11e8-87a6-384fd3bc90a9.png)

**Comment by PyvesB** [comment]
Got a [response on Twitter](https://twitter.com/OSM_Tech/status/1022026630351515648), this seems to be now fixed. 😉

**Comment by mtmail** [comment]
Reopening for visibility because currently I get a HTTP 503 error.

**Comment by eliasasaid1** [comment]
I am also receiving 503 error anyone else still receiving the same error?

**Comment by PyvesB** [comment]
Not systematically, but yes, a lot of 503 responses are coming back for me as well.

**Comment by LNFWebsite** [comment]
Could this be a DDOS attack? Because some requests go through and some hang. I was using OSM to see if there was any difference and found out that the entire map was slow to load (don't know if they share the same server).

**Comment by lonvia** [comment]
The main nominatim server is currently travelling and the backup server is not as powerful. Expect intermittent delays at least until tomorrow, possibly longer. That said, this is the wrong place to report or discuss that. It is an operational issue for nominatim.openstreetmap.org, none for the software.
