### ISSUE TITLE
`new_query_log` table empty

### ISSUE THREAD

**Issue by touatily** [openstreetmap/Nominatim#1121]
Is it normal that the table `new_query_log` is empty?

How to log queries?

![image](https://user-images.githubusercontent.com/27826148/43408843-a072fc36-9422-11e8-9f8e-b0ef7c666cab.png)

**Comment by Alex2782** [comment]
settings.php

CONST_Log_DB is true or false?

```
// Log settings
// Set to true to log into new_query_log table.
// You should set up a cron job that regularly clears out this table.
@define('CONST_Log_DB', false);
// Set to a file name to enable logging to a file.
@define('CONST_Log_File', false);

```

**Comment by touatily** [comment]
It was false, I set it to true and it logs queries.

Thanks!
