### ISSUE TITLE
Incorrect address heirarchy

### ISSUE THREAD

**Issue by ryanedgar** [openstreetmap/Nominatim#1123]
[https://www.openstreetmap.org/way/38708450](https://www.openstreetmap.org/way/38708450) and [https://nominatim.openstreetmap.org/details.php?place_id=80819364](https://nominatim.openstreetmap.org/details.php?place_id=80819364)

These links are for Marquis Gardens. The address hierarchy is incorrect, and searching for the correct address used by Royal Mail in OSM will not return any results.

The address should be:
Marquis Gardens,
Bangor,
County Down
...

The address in OSM is:
Marquis Gardens,
Ballyvarnet, _(this is not necessary - it's just an electoral boundary)_
Conlig, _(this is a village about 1 mile south of Bangor)_
County Down
...

I believe the issue is due to Ballyvarnet being included as a child of Conlig instead of Bangor.

**Comment by lonvia** [comment]
Nominatim does not have enough information here. Bangor and Conlig are both mapped as place nodes only, so Nominatim does have to take an educated guess to which town the road belongs. Conlig happens to be a tiny bit closer and so it wins. Add boundaries for Bangor and Conlig in OSM to fix the problem.

Closing as data issue here.
