### ISSUE TITLE
Docker containers: setup.php cannot connect to second container with postgresql

### ISSUE THREAD

**Issue by olablt** [openstreetmap/Nominatim#1125]
I am building the nominatim web server and postgresql database on two different docker containers.

When I run this command from web server (Centos7 container):

```
sudo -u nominatim psql -h postgis -lqt
```

I get the list of the databases on the host `postgis`. When I request the web page I get the error `Unable to connect to PostgreSQL server: FATAL:  database "nominatim" does not exist]` - it successfully connected to the database but did not find the database - GOOD.

But when I run 

```
sudo -u nominatim ./utils/setup.php --osm-file /app/data/lithuania-latest.osm.pbf --all -v
```

I get the error

```
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /app/src/lib/cmd.php on line 134
2018-08-04 19:17:35 == module path: /app/src/build/module
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /app/src/lib/cmd.php on line 134
2018-08-04 19:17:35 == Create DB
createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim -U nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim -U nominatim
```

My `local.php`

```
<?php
 // General settings
 @define('CONST_Database_DSN', 'pgsql://nominatim:nominatim@' . getenv('PGHOST') . ':5432/nominatim'); // <driver>://<username>:<password>@<host>:<port>/<database>
 @define('CONST_Website_BaseURL', '/');
 // Software versions
 @define('CONST_Postgresql_Version', '9.6');
 @define('CONST_Postgis_Version', '2.3');
```

Did I miss something?

**Comment by lonvia** [comment]
It looks like the host name is not picked up by the setup script (missing -h option for createdb). Check that

* PGHOST is correctly exported and visible to the setup script (particularly tricky in connection with sudo)
* you are really using the latest master of Nominatim
* that you have recently run cmake in your build directory to pick up the latest version of the setup script

**Comment by olablt** [comment]
```
# sudo -u nominatim echo $PGHOST
postgis
```

created file `vi test.php`
```
#!/usr/bin/php -Cq
<?php
        echo getenv("PGHOST");
```
then
```
# ./test.php
postgis
```
but after
```
sudo -u nominatim ./test.php
```
got nothing!

**Comment by lonvia** [comment]
The first command does not do what you think. `$PGHOST` is first replaced (while still in the calling user's env) and then the sudo command is executed. In any case, if the variable is set under your user and you want to hand it into sudo command, you have to preserve the environment: `sudo -E -u nominatim ...`. Note that this comes with a couple of security implications that your should read about first.

**Comment by olablt** [comment]
nominatim.so must be on both containers?

```
[root@f9bdfdf54cf7 build]# sudo -E -u nominatim ./utils/setup.php --osm-file /app/data/lithuania-latest.osm.pbf --all --import-data
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /app/src/lib/cmd.php on line 134
2018-08-05 08:03:56 == module path: /app/src/build/module
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /app/src/lib/cmd.php on line 134
2018-08-05 08:03:56 == Create DB
could not find a "createdb" to execute
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /app/src/lib/cmd.php on line 134
2018-08-05 08:03:56 == Setup DB
Postgres version found: 9.6
could not find a "psql" to execute
could not find a "psql" to execute
could not find a "psql" to execute
could not find a "psql" to execute
Postgis version found: 2.4

ERROR: Failed to load nominatim module. Reason:
CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/app/src/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text); [nativecode=ERROR:  could not access file "/app/src/build/module/nominatim.so": No such file or directory]

ERROR: error loading nominatim.so module
error loading nominatim.so module
```

**Comment by olablt** [comment]
figured out. thank you @lonvia !

**Comment by phlegx** [comment]
@olablt May I ask how you solved it with the `nominatim.so` module? Getting the same error.

**Comment by sebojanko** [comment]
Hi,
did you solve this? I'm currently trying to make it work, any help would be appreciated!

```
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]:  Database server failed to load /app/nominatim/build/module/nominatim.so module

  thrown in /app/nominatim/lib/DB.php on line 61
```
I read on many places this file should be available to postgres, but where do I put it?

**Comment by phlegx** [comment]
As a quick hack I currently simply install and build nominatim in my postgres docker container:

```# # Nominatim install
RUN git clone --recursive https://github.com/openstreetmap/Nominatim /app/src
RUN cd /app/src && git checkout tags/$NOMINATIM_VERSION && git submodule update --recursive --init && \
    mkdir build && cd build && cmake .. && make
```

Here is the list of packages I addionially install atm (Could be less needed, it is been a while I quickly hacked it together)

````    apt-get install -y build-essential cmake g++ libboost-dev libboost-system-dev \
    libboost-filesystem-dev libexpat1-dev zlib1g-dev libxml2-dev\
    libbz2-dev libpq-dev libgeos-dev libgeos++-dev libproj-dev \
    postgresql-server-dev-$POSTGRES_VERSION postgresql-client-$POSTGRES_VERSION \
    apache2 php php-pgsql libapache2-mod-php php-pear php-db \
    php-intl git curl sudo vim \
    python-pip libboost-python-dev \
    osmosis && \
```

**Comment by sebojanko** [comment]
I'll try that, thanks!

**Comment by Pesonet1** [comment]
> As a quick hack I currently simply install and build nominatim in my postgres docker container:
> 
> ```
> RUN git clone --recursive https://github.com/openstreetmap/Nominatim /app/src
> RUN cd /app/src && git checkout tags/$NOMINATIM_VERSION && git submodule update --recursive --init && \
>     mkdir build && cd build && cmake .. && make
> ```
> 
> Here is the list of packages I addionially install atm (Could be less of them needed, it is been a while I quickly hacked it together)
> 
> ```
>     libboost-filesystem-dev libexpat1-dev zlib1g-dev libxml2-dev\
>     libbz2-dev libpq-dev libgeos-dev libgeos++-dev libproj-dev \
>     postgresql-server-dev-$POSTGRES_VERSION postgresql-client-$POSTGRES_VERSION \
>     apache2 php php-pgsql libapache2-mod-php php-pear php-db \
>     php-intl git curl sudo vim \
>     python-pip libboost-python-dev \
>     osmosis && \
> ```
> 
> Best would be imho to have a postgres Module, i that is possible.

Another possibility is just to add custom script that copies nominatim.so file from running nominatim container to temp folder and copies it into database container e.g.

$ docker cp nominatim-container-name:/app/src/build/module/nominatim.so nominatim.so
$ docker exec -it database-container-name mkdir –p app/src/build/module
$ docker cp nominatim.so database-container-name:/app/src/build/module/nominatim.so

I used the above example with kartoza/postgis container.

However, this requires that before running nominatim setup.php script nomatim.so file is copied into database container. Therefore, a separate step is required to start nominatim container for copying the nominatim.so file before running the setup script.
