### ISSUE TITLE
How to get official_name: en?

### ISSUE THREAD

**Issue by nonuzer** [openstreetmap/Nominatim#1131]
Good afternoon.

Is it possible to get "official_name: en"?

The problem is that I get "short_name: en".
For example.
Instead of "People's Republic of China" (official_name: en) i get "PRC" (short_name: en)

https://nominatim.openstreetmap.org/reverse.php?format=json&lat=27.916766641249065&lon=116.89453125000001&zoom=18&accept-language=en

Thank you.

**Comment by Alex2782** [comment]
without `accept-language=en`
`"country":"China"`


https://nominatim.openstreetmap.org/reverse.php?format=json&lat=27.916766641249065&lon=116.89453125000001&zoom=18

`{"place_id":"227339582","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"relation","osm_id":"8023868","lat":"27.9084331","lon":"116.8871498","display_name":"黄通乡, Jinxi County, Fuzhou City, Jiangxi, China","address":{"city":"黄通乡","county":"Jinxi County","state_district":"Fuzhou City","state":"Jiangxi","country":"China","country_code":"cn"},"boundingbox":["27.8492268","27.9612865","116.8346643","116.980079"]}
`

**Comment by nonuzer** [comment]
2 Alex2782
Did you open my link? I use accept-language=en

`{"place_id":"227339582","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"relation","osm_id":"8023868","lat":"27.9084331","lon":"116.8871498","display_name":"黄通乡, Jinxi County, Fuzhou City, Jiangxi, PRC","address":{"city":"黄通乡","county":"Jinxi County","state_district":"Fuzhou City","state":"Jiangxi","country":"PRC","country_code":"cn"},"boundingbox":["27.8492268","27.9612865","116.8346643","116.980079"]}`

**Comment by Alex2782** [comment]
Yes, but i dont know why it different.
I can't see there no configurations for fieldnames, only for language.

`debug=1`
https://nominatim.openstreetmap.org/reverse.php?format=json&lat=27.916766641249065&lon=116.89453125000001&zoom=18&debug=1


                           4 => 'place_id' => '179243334'
                                'osm_type' => 'R'
                                'osm_id' => '270056'
                                'name' => [VERY LONG LIST with also **official_name: en** ]
                                'localname' => 'China'


`get_name_by_language` 
`$sSQL .= '  get_name_by_language(name,'.$mLangPref.') as localname';`

**Comment by lonvia** [comment]
You can use `namedetails=1` to get additional names for an object. On the touchy subject of short_names that are not short names but refs, see #783. Closing here as a duplicate.
