### ISSUE TITLE
expand "SP" to "Szkoła Podstawowa", at least in Poland

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#1134]
It is a typical shortening (supported for example by Google Maps search).

It appears to be not supported - see https://github.com/openstreetmap/Nominatim/search?q=SP&unscoped_q=SP

For example, I would expect "SP 93, Kraków" to find https://www.openstreetmap.org/way/230183651#map=19/50.07372/19.90089

Currently nothing is found.

**Comment by lonvia** [comment]
Please add abbreviations to https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations.

**Comment by matkoniecz** [comment]
"Implemented? not yet" in https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#Polski_-_Polish is a bit discouraging, but I will add this case
