### ISSUE TITLE
Wrong reverse geocodding (no building numbers)

### ISSUE THREAD

**Issue by armenmargaryan** [openstreetmap/Nominatim#1136]
Hi,

Seems recently reverse geocoding started to not response building number

For example:
https://nominatim.openstreetmap.org/reverse?format=json&lat=40.191729&lon=44.470370&zoom=18&addressdetails=1
returns: Ajapnyak, Yerevan ..
but should return: 38, Leningradyan street, ....

if i pick up lat, lng from a bit button near to road then it response with correct building number : https://nominatim.openstreetmap.org/reverse?format=json&lat=40.191518&lon=44.470735&zoom=18&addressdetails=1

And it is not only for this bulging but i found many such coordinates ?

Can you pls check and fix it ? or what is the issue ? 
because before it was working in **100%** for same buildings 

Thank you, 
Armen

**Comment by lonvia** [comment]
#1054 changed the way zoom=18 works, returning the closest building _or_ street (only building before). That part was intended. It unintentionally takes the distance to the building center into account though which leads to the error you see. Fix is coming shortly.
