### ISSUE TITLE
Viewbox, SQL small and SQL large

### ISSUE THREAD

**Issue by Alex2782** [openstreetmap/Nominatim#1137]
File:  lib/SearchContext.php

- the variables sqlViewboxSmall and sqlViewboxLarge  always **(?)** have the same values, is this a bug?
- "sqlViewboxLarge" calculates the values with "min"- and "max"-functions, and then add or subtract again the difference = always same values, i think.

**example (debug)**
https://nominatim.openstreetmap.org/search.php?q=bergstr%201&polygon_geojson=1&viewbox=-13.24951%2C54.23955%2C12.50244%2C47.30903&debug=1

```
' (SQL, small)' => 'ST_SetSRID(ST_MakeBox2D(ST_Point(-13.249510,47.309030),ST_Point(12.502440,54.239550)),4326)'
' (SQL, large)' => 'ST_SetSRID(ST_MakeBox2D(ST_Point(-13.249510,47.309030),ST_Point(12.502440,54.239550)),4326)'
```

```
    public function setViewboxFromBox(&$aViewBox, $bBounded)
    {
        $this->bViewboxBounded = $bBounded;
        $this->sqlViewboxCentre = '';
        $this->sqlViewboxSmall = sprintf(
            'ST_SetSRID(ST_MakeBox2D(ST_Point(%F,%F),ST_Point(%F,%F)),4326)',
            $aViewBox[0],
            $aViewBox[1],
            $aViewBox[2],
            $aViewBox[3]
        );

        $fHeight = $aViewBox[0] - $aViewBox[2];
        $fWidth = $aViewBox[1] - $aViewBox[3];
        $this->sqlViewboxLarge = sprintf(
            'ST_SetSRID(ST_MakeBox2D(ST_Point(%F,%F),ST_Point(%F,%F)),4326)',
            max($aViewBox[0], $aViewBox[2]) + $fHeight,
            max($aViewBox[1], $aViewBox[3]) + $fWidth,
            min($aViewBox[0], $aViewBox[2]) - $fHeight,
            min($aViewBox[1], $aViewBox[3]) - $fWidth
        );
    }
```

**Comment by lonvia** [comment]
I noticed that as well recently and thought it was just a glitch in the debug output. But you are right. fHeight and fWidth happened to be negative thus extending the box in the wrong direction. Thanks for reporting, fix will go live in a couple of minutes.
