### ISSUE TITLE
update fail 

### ISSUE THREAD

**Issue by mevisol** [openstreetmap/Nominatim#1142]
Hi im import europe pbf now im try update database and receive this error 

./utils/update.php --import-osmosis-all
Currently at sequence 1978 (17/08/2018 20:12:36) - t indexed
/srv/nominatim/.local/bin/pyosmium-get-changes --server https://download.geofabrik.de/europe-updates/ -o /srv/nominatim/Nominatim-3.1.0/build/osmosischange.osc -s 30 -I 1978
/srv/nominatim/Nominatim-3.1.0/build/osm2pgsql/osm2pgsql -klas --number-processes 1 -C 2000 -O gazetteer -d nominatim -P 5432 --flat-nodes /dupa/flatnode.file /srv/nominatim/Nominatim-3.1.0/build/osmosischange.osc
osm2pgsql version 0.96.0 (64 bit id space)

Using projection SRS 4326 (Latlong)
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
Mid: loading persistent node cache from /dupa/flatnode.file
Mid: pgsql, cache=2000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /srv/nominatim/Nominatim-3.1.0/build/osmosischange.osc
Using XML parser.
node cache: stored: 26(100.00%), storage efficiency: 0.32% (dense blocks: 1, sparse nodes: 25), hit rate: -nan%
Osm2pgsql failed due to ERROR: DELETE FROM place WHERE osm_type = 'N' AND osm_id = 310467 failed: ERROR:  invalid page in block 18 of relation base/16386/2619
CONTEXT:  SQL statement "UPDATE placex set indexed_status = 100 where osm_type = OLD.osm_type and osm_id = OLD.osm_id and class = OLD.class and type = OLD.type"
PL/pgSQL function place_delete() line 18 at SQL statement

Error executing osm2pgsql: 1

**Comment by lonvia** [comment]
Your database is corrupted. If you are lucky, the block in question is just an index which you might then drop and recreate. If the block belongs to a table you are out of luck and have to reimport from scratch.  How to figure out what exactly is corrupted is unfortunately beyond the scope of this bug tracker. You have to consult a database expert. 

NB: You should first find out what caused the corruption before attempting any repair. It might just be a hard reboot (e.g. after power failure), it might also be a broken hard disk or memory.

**Comment by mevisol** [comment]
yes database is corrupted im load again its work thx
