### ISSUE TITLE
Failure to reverse geocode a point in Brazil, with zoom lower than 5

### ISSUE THREAD

**Issue by matafagafo** [openstreetmap/Nominatim#1145]
When I try to reverse geocode this point in Brazil

https://nominatim.openstreetmap.org/reverse?format=json&lat=-29.6998&lon=-51.4796

I always receive **"Unable to geocode"** for zoom levels lower then 5, like bellow link with zoom 0

https://nominatim.openstreetmap.org/reverse?format=json&lat=-29.6998&lon=-51.4796&zoom=0

Thanks !

**Comment by lonvia** [comment]
That was indeed a bug. Fix will go live in a couple of hours.

Note that the reverse handling has slightly changed and Nominatim now always returns countries for zoom 0 to 4.

**Comment by matafagafo** [comment]
Thanks for your help !
But I tried now (almost 48 hours after your commit) and the problem is still happening in Nominatim server.
Is this expected ?

**Comment by lonvia** [comment]
No. Looks like the fix was incomplete.

**Comment by lonvia** [comment]
This time I tested your example on the production server. Now it really works.
