### ISSUE TITLE
nominatim.so Permission denied when importing Data

### ISSUE THREAD

**Issue by hageethr** [openstreetmap/Nominatim#1149]
Hi All,
i have installed the nominatim but when i tried to import data it shows below Error 

ERROR: Failed to load nominatim module. Reason:
CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text); [nativecode=ERROR:  could not access file "/srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so": Permission denied]

i have check the permission using
"sudo -u postgres ls -la /srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so"
and result is 
"-rwxr-xr-x. 1 nominatim nominatim 342408 Aug 20 22:54 /srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so"

please help.

**Comment by mtmail** [comment]
Hmm, the permissions seem alright.

I extended the FAQ based on a while back after this rather confusing issue discussion https://github.com/openstreetmap/Nominatim/issues/1088 The content isn't linked live yet, but you can preview it on https://github.com/mtmail/Nominatim/blob/92f86de938fcb2fb18b22531bf491512e5b8c190/docs/admin/Faq.md (look for "Could not load library").

Is the database (postgresql) on the same physical machine as the software?

**Comment by hageethr** [comment]
Yes both are in same machine,
I have check the link and permissions are same as described.
this thing happens when i try to import data using
./utils/setup.php --osm-file <MyFile> --all [--osm2pgsql-cache 28000] 2>&1 | tee setup.log

**Comment by mtmail** [comment]
Which operating system and version are you using? E.g. "Ubuntu 16". On Ubuntu I don't see the dot after the last "x" for example "-rwxr-xr-x. 1 nominatim nominatim 342408"

**Comment by hageethr** [comment]
im using CentOS Linux release 7.5.1804

**Comment by mtmail** [comment]
Can you doublecheck the SELinux security settings? http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/#adding-selinux-security-settings Those might have to be run again after the installation (which writes new files and nominatim.so is one of them).

**Comment by hageethr** [comment]
I have added those three settings and do a reboot nothing happens still get the same Error..

**Comment by Alex2782** [comment]
i have also CentOS 7 (VM), the documentation is wrong when using the release version and not github?

/srv/nominatim/Nominatim-3.1.0/**build**/module/nominatim.so"


> sudo semanage fcontext -a -t httpd_sys_content_t "$USERHOME/Nominatim-3.1.0/(website|lib|settings)(/.*)?"
> sudo semanage fcontext -a -t lib_t "$USERHOME/Nominatim-3.1.0/module/nominatim.so"
> sudo restorecon -R -v $USERHOME/Nominatim-3.1.0

insert here "build"-path

try this
---------

1. sudo semanage fcontext -a -t httpd_sys_content_t "$USERHOME/Nominatim-3.1.0/**build/**(website|lib|settings)(/.*)?"
2. sudo semanage fcontext -a -t lib_t "$USERHOME/Nominatim-3.1.0/**build**/module/nominatim.so"
3. sudo restorecon -R -v $USERHOME/Nominatim-3.1.0/**build**

**Comment by hageethr** [comment]
still not working..
I'm planing to install fresh copy of centos and do the installation again. can you point me a correct walk through documentation to install nominatim.

**Comment by mtmail** [comment]
> can you point me a correct walk through documentation to install nominatim.

For testing and debugging we use https://github.com/openstreetmap/Nominatim/blob/master/vagrant/Install-on-Centos-7.sh

The http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/ documentation gets generated from the comments of the .sh file.

**Comment by lonvia** [comment]
Additional note: the newest documentation from master is here in readable form: http://nominatim.org/release-docs/develop/appendix/Install-on-Centos-7/ The SELinux instructions have been fixed there already.

**Comment by lonvia** [comment]
Closing as this is rather a generic system administration problem.
