### ISSUE TITLE
Sort out order of importance

### ISSUE THREAD

**Issue by ADepic** [openstreetmap/Nominatim#1156]
[Dallas Texas](https://www.openstreetmap.org/search?query=dallas%20texas#map=18/19.50556/-99.07625) returns a residential road in mexico, even when viewbox is turned on and mexico is out of view. The city is only seen if you press more results. Simply searching "Dallas" gives the right result.

Another example is the search "[konkan](https://www.openstreetmap.org/search?query=konkan#map=13/10.3724/-9.4326)" giving hamlets, schools and restuarents instead of the administrative division known as the [konkan division](https://www.openstreetmap.org/relation/8593769#map=6/16.190/75.729). Administrative divisions & and things such as place=city, should be given a lot more importance over exact matches. 

Can you please sort out the order of importance?

Also  a search for [tendring](https://www.openstreetmap.org/search?query=tendring#map=13/51.8787/1.1109) doesn't give the [tendring district](https://www.openstreetmap.org/relation/76494#map=10/51.8637/1.1139) clearly marked as admin_level=8 but instead gives a [another boundary called tendring](https://www.openstreetmap.org/relation/76840) marked as admin_level=10, clearly less important. Searching for [tendring district](https://www.openstreetmap.org/search?query=tendring%20district#map=10/51.8638/1.1144) gives a correct result, but now it is claimed to be a village, but when querying features it was a city boundary.

**Comment by lonvia** [comment]
Nominatim has a strong preference for exact matches up to the point where it does not show partial matches in the first batch of results. This is not exactly a bug. Searches for "Dellas, Texas", "konkan division", "tendring district" work as expected.

Closing in favour of #94 which this issue already.
