### ISSUE TITLE
Reverse Geocoding in a custum list of GeoJson

### ISSUE THREAD

**Issue by Namec** [openstreetmap/Nominatim#1157]
Hello All,

currently i am looking to use Nominatim strentgh to do some reverse geocoding in a list of GeoJson's Areas.

currently doig this by storing the geometries in an SQL database and then doing some SQL stuff, to make it work.

i am sure, that Nominatim can do this more quickly than ever, while making me free some ressources for other tasks.

anyone already figured how to deal with this ?

**Comment by mtmail** [comment]
You posted the same question word-for-word on https://github.com/pelias/pelias/issues/741 as well. Closing here.

> anyone already figured how to deal with this ?

You can try https://help.openstreetmap.org/ to reach other Nominatim users.
