### ISSUE TITLE
Nominatim - Possible Database Compromise

### ISSUE THREAD

**Issue by dmchaledev** [openstreetmap/Nominatim#1158]
Looks like someone may have compromised your DB and changed all permutations of the United States to return USA, Creedon Republic. This confused the hell out of me this morning and appears to have happened around 05:00 UTC on 8/26. I don't see mention of it anywhere in the issues here or on your site at https://nominatim.openstreetmap.org. I've included a Python 2 snippet below for reproducing the issue with common permutations of the US 

from geopy.geocoders import Nominatim

language = 'en'
geolocator = Nominatim()
region_list = ["US",
		      "USA",
		      "United States"]

for region in region_list:
    try:
        if region != '':
            location = geolocator.geocode(query=region, language=language)
            time.sleep(1)
            country = location.raw['display_name'].split(',')[-1].lstrip()
            print('Region:', region)
            print('Location:', location.address)
            print('Country:', country)
    except:
    	print('Not found')

**Comment by dmchaledev** [comment]
https://nominatim.openstreetmap.org/details.php?place_id=236465485

**Comment by lonvia** [comment]
Thanks for reporting. I've removed the offending way and the database is cleaning itself now. Should be done in a couple of minutes.

**Comment by mtmail** [comment]
I changed the title from "Possible Database Compromise" because the root cause was vandalism in the OpenStreetMap data. After it was corrected Nominatim didn't automatically update its own database.

For other Nominatim admins, you can remove the place by running
```
1. mark all children of place unindexed
update placex set indexed_status=1 where parent_place_id=(select place_id from placex where osm_type='W' and osm_id=617866825);

2. delete the place. This will also mark some children unindexed (recursive)
delete from placex where osm_type='W' and osm_id=617866825;

3. as user nominatim (or however Nominatim was installed) run
~/Nominatim/build$ time ./utils/update.php --index

Takes at least 30 minutes.
```

**Comment by lonvia** [comment]
There is also a special database maintenance function for that: find the `place_id` of the offending place (e.g. via /details.php?osmtype=N&osmid=617866825) in your database. Then run the following SQL statement:

```
SELECT place_force_delete(<place_id>);
```

If you have continuous updates running, then they take care of fixing the rest. Otherwise run `./utils/update.php` as advised by @mtmail.
