### ISSUE TITLE
specialphrases.php, whitelisting

### ISSUE THREAD

**Issue by Alex2782** [openstreetmap/Nominatim#1159]
https://github.com/openstreetmap/Nominatim/blob/master/settings/phrase_settings.php
```
// If a class is in the white list then all types will 
// be ignored except the ones given in the list.
// Also use this list to exclude an entire class from
// special phrases.

$aTagsWhitelist
 = array(
    'highway' => array('bus_stop', 'rest_area', 'raceway'),
    'building' => array(),
   );
```

https://github.com/openstreetmap/Nominatim/blob/master/utils/specialphrases.php
```
// whitelisting: if class is in whitelist, allow only tags in the list
if (isset($aTagsWhitelist[$sClass]) && !in_array($sType, $aTagsWhitelist[$sClass])) {
    //fwrite(STDERR, "Non-Whitelisted: ".$sClass."/".$sType."\n");
    continue;
}
```

`./utils/specialphrases.php --wiki-import > /tmp/specialphrases.sql`

less /tmp/specialphrases.sql

**i see there not only "highway" + "building" (whitelist-config)**

`select getorcreate_amenityoperator(make_standard_name('Airport in'), 'airport in', 'aeroway', 'aerodrome', 'in');
`

----------------------

**Bugfix** -> **if  (whitelist-config set and class is not in Whitelist) or**
 (class is in Whitelist and type not in class-array) 
**then continue**

```
// whitelisting: if class is in whitelist, allow only tags in the list
 if ((isset($aTagsWhitelist) and !isset($aTagsWhitelist[$sClass])) || (isset($aTagsWhitelist[$sClass]) && !in_array($sType, $aTagsWhitelist[$sClass])) ) {
    //fwrite(STDERR, "Non-Whitelisted: ".$sClass."/".$sType."\n");
    continue;
}

```

**Comment by lonvia** [comment]
The whitelist is only for filtering types not classes. If a class does not show up in the list, then no filtering is applied at all. This is intentional and not a bug.

**Comment by Alex2782** [comment]
ok thanks
