### ISSUE TITLE
Search.php is not working while reverse.php is working fine

### ISSUE THREAD

**Issue by noerv** [openstreetmap/Nominatim#1162]
I face some troubles regarding the installation of nominatim. The search.php results with 
"##Nominatimserver## is currently unable to handle this request. HTTP ERROR 500". 

I have installed Nominatim 3.1.0 on a Ubuntu 18.04 with postegres 10 and run ./utils/setup.php --index --create-search-indices twice to be sure that the indices are created successfully. 
However the output of the "setup.php..." is "Starting rank 0   Done 0 in 0 @ 0.000000 per second - FINISHED" for each rank. 

My guess is that the indices are not build correct as the reverse search is working fine.

Any ideas what I can do/check?

I am happy to provide you with more information if needed.

**Comment by geomark** [comment]
I don't think that Postgres 10 supports the version of Postgis extensions that Nominatim is currently using. I tried this myself but it didn't work. It appears to be working fine with Postrgres 9.5 though.  You can try this Docker image: https://github.com/mediagis/nominatim-docker/tree/master/3.1 .

**Comment by noerv** [comment]
Many thanks for your hint. 
I will try the docker image.

**Comment by lonvia** [comment]
Nominatim works fine with postgres 10, in fact much faster than with postgres 9.x. Please also use the latest Nominatim 3.2.

Your database has no data, so indexes is the least of your problems. Please describe exactly what you did for the setup and provide a full log.

**Comment by noerv** [comment]
The database has a size of 800GB and the placex table is also filled. Where can I find the full log file you mentioned?

**Comment by noerv** [comment]
Ah okay. I run the setup.php twice to be sure that the indices are created. There comes the Rank 0... message from.
I have also checked the indices in postgres and they exist.

**Comment by noerv** [comment]
The update of Nominatim from 3.1.0 to 3.2.0 worked well. It was a problem of using postgres 10 with Nominatim 3.1.0 instead of Nominatim 3.2.0
