### ISSUE TITLE
Error while importing wikipedia articles

### ISSUE THREAD

**Issue by pbaylis** [openstreetmap/Nominatim#1163]
I'm installing Nominatim 3.2.0 on a fresh install of Ubuntu 18.04 on my local server. Server has 128GB memory and the install is on a 500GB SSD with about 400 GB free space. Postgresql is 10.5 and Postgis is 2.4.3. I modified the Postgresql settings following the [instructions](http://nominatim.org/release-docs/latest/admin/Installation/#postgresql-tuning).

I'm only importing a portion of the United States, and I downloaded the Wikipedia rankings data. I get the following error while trying to run the import:

```
2018-09-04 09:23:24 == Create Functions
2018-09-04 09:23:24 == Create Tables
2018-09-04 09:23:24 == Recreate Functions
2018-09-04 09:23:24 == Create Partition Tables
2018-09-04 09:23:26 == Create Partition Functions
2018-09-04 09:23:26 == Importing wikipedia articles
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 2787; 1259 2164299 INDEX idx_osm_id brian
pg_restore: [archiver (db)] could not execute query: ERROR:  index "idx_osm_id" does not exist
    Command was: DROP INDEX public.idx_osm_id;

pg_restore: [archiver (db)] Error from TOC entry 2789; 2606 2164220 CONSTRAINT pagelinks_pkey brian
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "pagelinks_pkey" of relation "wikipedia_article" does not exist
    Command was: ALTER TABLE ONLY public.wikipedia_article DROP CONSTRAINT pagelinks_pkey;

pg_restore: [archiver (db)] Error from TOC entry 362; 1259 2164210 TABLE wikipedia_article brian
pg_restore: [archiver (db)] could not execute query: ERROR:  role "brian" does not exist
    Command was: ALTER TABLE public.wikipedia_article OWNER TO brian;
```
The installation keeps running after this, but I wonder if this means that the wikipedia import has failed?

**Comment by lonvia** [comment]
You can safely ignore these errors.

**Comment by s0m30n3** [comment]
Adding ''--no-owner" to pgsqlRunDropAndRestore function (file  <Nominatim src>/lib/setup/SetupClass.php) removes some of these errors.
It's a simple one line fix.

Documentation can also be improved with something like "Import process will generate some errors you can safely ignore".
