### ISSUE TITLE
Planet mirror data for update

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1164]
Hi,
Sorry. This is not issue.
I have asked in help.osm, but still didn't got proper answer, So asking here too.

I setup nominatim with planet data from planet.openstreetmap.org.
Can I use osm mirrors(https://wiki.openstreetmap.org/wiki/Planet.osm#Planet.osm_mirrors) for regular(daily) update? 
particularly, https://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day ?
bcoz, met some proxy error while getting data from other source.

**Comment by mtmail** [comment]
Yes, as long as it says "Diffs=yes". As you can see in the table some mirrors only offer daily diffs, not minutely.
