### ISSUE TITLE
Search php didn't return specific result data

### ISSUE THREAD

**Issue by Rajavelu** [openstreetmap/Nominatim#1165]
Hi,
Check below reverse geocoding url: https://nominatim.openstreetmap.org/reverse?format=json&lat=43.642388&lon=-79.374265

Got data as: Toronto Star, 1, Yonge Street, South Core, Old Toronto, Toronto, Ontario, M5E 1E5, Canada

But can't get the same data in geocode url(got some other data, not the expected one): https://nominatim.openstreetmap.org/search?format=json&limit=5&addressdetails=1&q=1,%20Yonge%20Street

How to get above data in geocode(using query string)?

**Comment by mtmail** [comment]
In this case adding the city name returns the Toronto Star address

```
curl -s 'https://nominatim.openstreetmap.org/search?format=json&limit=5&addressdetails=1&q=1,Yonge+Street,Toronto' | jq '.[] | .display_name'
"Toronto Star, 1, Yonge Street, South Core, Old Toronto, Toronto, Ontario, M5E 1E5, Canada"
"1, Yonge Street, St. John, North York, Toronto, Ontario, M2P 2E3, Canada"
"Boreal College, 1, Yonge Street, South Core, Old Toronto, Toronto, Ontario, M5E, Canada"
"INS Market, 1, Yonge Street, South Core, Old Toronto, Toronto, Ontario, M5E, Canada"
"Fit for Life Sandwich Bar, 1, Yonge Street, South Core, Old Toronto, Toronto, Ontario, M5E, Canada"
```

Without the city name the bus stop's `ref=1` https://www.openstreetmap.org/node/2215262534 gets treated as a name and direct name matches rank higher (house number matches happen later in the search logic).

**Comment by Rajavelu** [comment]
@mtmail  Thanks for your reply.

> Without the city name the bus stop's ref=1 https://www.openstreetmap.org/node/2215262534 gets treated as a name and direct name matches rank higher (house number matches happen later in the search logic).

Return this data(as matches rank higher) is fine. 
But when we give limit as max (or more than 1), expected lower rank results also. But got only 1 result.

**Comment by lonvia** [comment]
There are almost 800 'yonge street' in the database. Searching through all of them for one which might have a house number one is not possible without a significant loss of performance.
