### ISSUE TITLE
Search for Australia (eez) returns Fiji postcode address.

### ISSUE THREAD

**Issue by LM-Mason** [openstreetmap/Nominatim#1166]
Hello

When searching for Australia (exclusive economic zone), Nominatim computes an address/postcode of +679:
https://nominatim.openstreetmap.org/details.php?place_id=238107206

Which are located in Fiji:
https://overpass-turbo.eu/s/BI2

Ideally, this relation should not be returning any postcode as the address. The relation also contains the is_in:country=Australia tag.

Any suggestions on how to fix? Thanks.

**Comment by mtmail** [comment]
You're right. Fiji doesn't seem to have postcodes at all https://en.wikipedia.org/wiki/List_of_postal_codes (and various other web search results). And `+679` happens to be the international phone dialing code so all the `addr:postcode` values must be wrong. I see at least one user used the maps.me mobile app to add places so it might have been a bug in that software (pre-filled field?)

Attached a list of affected places. Once those are fixed (not sure if you're offering help here, would be great) Nominatim will update. The update process runs every night.

[fiji_679_postcode.txt](https://github.com/openstreetmap/Nominatim/files/2360563/fiji_679_postcode.txt)

**Comment by LM-Mason** [comment]
They are now gone, as well a few others that were not +679. I'll wait and see what the changes do to the address.

**Comment by lonvia** [comment]
Looks like it worked. Please note that postcodes are only updated when the place in question is edited. So it might be that you still find the postcode here and there when searching.
