### ISSUE TITLE
Installation issue - pg_restore of wikipedia_article data file failed

### ISSUE THREAD

**Issue by GFCGitHum** [openstreetmap/Nominatim#1169]
**The only geocoding usable, it's html, but the query's result don't have housenumber and details button**

**Query** 
https://nominatim43.siunet.it/nominatim/reverse.php?format=html&lat=44.50155&lon=11.33989&zoom=18
**Result**
![image](https://user-images.githubusercontent.com/33733335/45269383-8506bd80-b48d-11e8-8586-7b883788149d.png)

**Query**
https://nominatim43.siunet.it/nominatim/reverse.php?format=json&lat=44.50155&lon=11.33989&zoom=18
**Result**
{"error":"Unable to geocode"}

**If I use Nomiminatim 3.1.0 Ubuntu 16.04**

**Query**
https://nominatim40.siunet.it/nominatim/reverse.php?format=html&lat=44.50155&lon=11.33989&zoom=18
**Result**
![image](https://user-images.githubusercontent.com/33733335/45269435-97cdc200-b48e-11e8-9ea2-4653cacec1b2.png)

**Query**
https://nominatim40.siunet.it/nominatim/reverse.php?format=json&lat=44.50155&lon=11.33989&zoom=18
**Result**
{"place_id":"421487","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"node","osm_id":"1704756187","lat":"44.5015307","lon":"11.3398676","display_name":"71, Via Guglielmo Marconi, Saragozza-Porto, Bologna, BO, Emilia-Romagna, 40122, Italia","address":{"house_number":"71","road":"Via Guglielmo Marconi","suburb":"Saragozza-Porto","city":"Bologna","county":"BO","state":"Emilia-Romagna","postcode":"40122","country":"Italia","country_code":"it"},"boundingbox":["44.5014307","44.5016307","11.3397676","11.3399676"]}

**Comment by mtmail** [comment]
`{"error":"Unable to geocode"}` means no result was found. I see from the first screenshot the HTML output also doesn't show a result.

The same query works on https://nominatim.openstreetmap.org/reverse.php?format=html&lat=44.50155&lon=11.33989&zoom=18

Do you see the same error for every query or is this only for this one coordinate?

Which version of Nominatim are you running on your `nominatim43` server? Was the server fresh installed or an upgrade? If upgrade then which version was installed before?

**Comment by GFCGitHum** [comment]
Hi mtmail,

I don't upgrade, I have made a new machine with Ubuntu 16.04 and Nominatim 3.2.0, I know, on your server it's perfect.
{"error":"Unable to geocode"} it's for every query

Now I have 3 virtual machine Ubuntu 16.04 and Nominatim 3.1.0.
I need the house number on ZOOM 18 for my service 

![image](https://user-images.githubusercontent.com/33733335/45269733-14629f80-b493-11e8-8db7-fc44c29f47f5.png)

**Comment by mtmail** [comment]
The HTML output shows no results. I think the red circle on the map might be misleading: it shows the position of the search, not a result. Results would be a blue circle on the map (plus the red circle).

Did the import of the data finish?

Can you find addresses in that city with the forward search? E.g. does `Via Guglielmo Marconi, porto, bologna, italia` return results?

How many records does the `placex` table have?

**Comment by GFCGitHum** [comment]
Oh no,

SELECT COUNT(*) FROM placex;
Result 0

Setup.log

2018-09-09 03:14:22 == module path: /srv/nominatim/Nominatim/build/module
2018-09-09 03:14:23 == Create DB
2018-09-09 03:14:23 == Setup DB
Postgres version found: 9.5
Postgis version found: 2.2
2018-09-09 03:14:28 == WARNING: external UK postcode table not found.
2018-09-09 03:14:29 == Import data
osm2pgsql version 0.96.0 (64 bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=3494MB, maxblocks=55904*65536, allocation method=11
Mid: loading persistent node cache from /srv/nominatim/flatnode.file
Mid: pgsql, cache=3494
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /srv/nominatim/Nominatim/data/italy-latest.osm.pbf
Using PBF parser.
Processing: Node(50k 50.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)
........
.........
Processing: Node(169753k 239.8k/s) Way(18362k 65.11k/s) Relation(276850 8389.39/s)  parse time: 1023s
Node stats: total(169753725), max(5891602347) in 708s
Way stats: total(18362338), max(623930839) in 282s
Relation stats: total(287398), max(8664057) in 33s
.......
.......
Osm2pgsql took 1038s overall
2018-09-09 03:31:48 == Create Functions
2018-09-09 03:31:48 == Create Tables
2018-09-09 03:31:48 == Recreate Functions
2018-09-09 03:31:48 == Create Partition Tables
2018-09-09 03:31:55 == Create Partition Functions
2018-09-09 03:31:56 == Importing wikipedia articles
pg_restore: [archiver (db)] Error while PROCESSING TOC:
pg_restore: [archiver (db)] Error from TOC entry 2787; 1259 2164299 INDEX idx_osm_id brian
pg_restore: [archiver (db)] could not execute query: ERROR:  index "idx_osm_id" does not exist
    Command was: DROP INDEX public.idx_osm_id;

pg_restore: [archiver (db)] Error from TOC entry 2789; 2606 2164220 CONSTRAINT pagelinks_pkey brian
pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "pagelinks_pkey" of relation "wikipedia_article" does not exist
    Command was: ALTER TABLE ONLY public.wikipedia_article DROP CONSTRAINT pagelinks_pkey;

**Comment by mtmail** [comment]
The wikipedia import warnings should be fine (see https://github.com/openstreetmap/Nominatim/issues/1163)

What are the last lines in your `Setup.log` file? You might be able to resume the import (see https://www.nominatim.org/release-docs/latest/admin/Faq/#installation-issues). Otherwise deleting the database (`dropdb Nominatim`) and running the `utils/setup.php` command again are best.

**Comment by GFCGitHum** [comment]
This is my last line:

pg_restore: [archiver (db)] could not execute query: ERROR:  constraint "pagelinks_pkey" of relation "wikipedia_article" does not exist
    Command was: ALTER TABLE ONLY public.wikipedia_article DROP CONSTRAINT pagelinks_pkey;

**Comment by mtmail** [comment]
OK, I thought github might have truncated the output after copy&pasting.

Which version of Postgresql are you using?

Did the wikipedia data file download fine? They're located in `/srv/nominatim/Nominatim/data/`. Mine show
```
$ ls -lah wikipedia_*
-rw-r--r-- 1 nominatim nominatim 1.2G <date> wikipedia_article.sql.bin
-rw-r--r-- 1 nominatim nominatim 229M <date> wikipedia_redirect.sql.bin
$ md5sum wikipedia_*
559314f46e414b494dcef0d9bb099fb8  wikipedia_article.sql.bin
7836296e86eeaf1cb2d3d65f827e9d88  wikipedia_redirect.sql.bin
```

**Comment by GFCGitHum** [comment]
I run command:

I run the command:

./utils/setup.php --index --create-search-indices --create-country-names
[sudo] password for datamove:
2018-09-10 01:35:55 == module path: /srv/nominatim/Nominatim/build/module
2018-09-10 01:35:55 == Index ranks 0 - 4
nominatim version 3.2.0

Starting indexing rank (0 to 4) using 15 threads
Starting rank 0
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 1
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 2
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 3
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 4
  Done 0 in 0 @ 0.000000 per second - FINISHED

2018-09-10 01:36:36 == Index ranks 5 - 25
nominatim version 3.2.0

Starting indexing rank (5 to 25) using 15 threads
Starting rank 5
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 6
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 7
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 8
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 9
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 10
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 11
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 12
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 13
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 14
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 15
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 16
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 17
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 18
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 19
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 20
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 21
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 22
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 23
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 24
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 25
  Done 0 in 0 @ 0.000000 per second - FINISHED

2018-09-10 01:37:44 == Index ranks 26 - 30
nominatim version 3.2.0

Starting indexing rank (26 to 30) using 15 threads
Starting rank 26
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 27
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 28
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 29
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting interpolation lines (location_property_osmline)
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 30
  Done 0 in 0 @ 0.000000 per second - FINISHED

2018-09-10 01:37:44 == Index postcodes
2018-09-10 01:37:44 == Create Search indices
ERROR:  relation "idx_word_word_id" already exists
ERROR: pgsql returned with error code (3)
pgsql returned with error code (3)

But placex is empty

datamove@DMNOM32:/srv/nominatim/Nominatim/data$ ls -lah wikipedia_*
-rw-rw-r-- 1 nominatim nominatim 1.2G Sep  8 23:41 wikipedia_article.sql.bin
-rw-rw-r-- 1 nominatim nominatim 229M Aug 13  2017 wikipedia_redirect.sql.bin

datamove@DMNOM32:/srv/nominatim/Nominatim/data$ md5sum wikipedia_*
559314f46e414b494dcef0d9bb099fb8  wikipedia_article.sql.bin
7836296e86eeaf1cb2d3d65f827e9d88  wikipedia_redirect.sql.bin

**Comment by GFCGitHum** [comment]
Sorry I miss one answer 

DB Server PostgreSQL versione 9.5.14 (With schemas)

I attach the conf file

[postgresql.conf.TXT](https://github.com/openstreetmap/Nominatim/files/2364769/postgresql.conf.TXT)

**Comment by mtmail** [comment]
Looks like the `./utils/setup.php --index ` doesn't work here, it tried to index an empty table.

Please try a full reimport. 1. `dropdb Nominatim` to delete the whole database, then follow the import instructions again. http://nominatim.org/release-docs/latest/admin/Import-and-Update/

**Comment by GFCGitHum** [comment]
Ok I try now.

Many thanks
Franco

**Comment by lonvia** [comment]
I assume this has fixed itself.
