### ISSUE TITLE
Santa Clara, California returns non-US results

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1170]
https://nominatim.openstreetmap.org/search.php?q=santa+clara%2C+california returns
```
California, Santa Isabel de las Lajas, Cienfuegos, Cuba (Hamlet)
California, Población Martín, San Nicolás, Provincia de Punilla, Ñuble Region, Chile (Residential)
```
when clicking 'search more results' the first result is the expected city (https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=2221647&class=boundary)
```
Santa Clara, Santa Clara County, California, USA (City)
```

Similar for https://nominatim.openstreetmap.org/search.php?q=los+angeles%2C+california where returned 9 results are buildings, shops while after clicking 'search more results' it's the expected city.

https://nominatim.openstreetmap.org/search.php?q=san+francisco%2C+california returns a place in Colombia, a bus stop and a bakery. Again clicking 'search more results' returns the expected city.

https://nominatim.openstreetmap.org/search.php?q=san+mateo%2C+california returns a street named "California" in the San Mateo, California county.

https://nominatim.openstreetmap.org/search.php?q=san+carlos%2C+california returns results in Chile and Ecuador.

I found nothing wrong with the city nodes/relations or the California one. Nothing too obvious in the debug view. Setting the viewbox to a local area makes no difference.

**Comment by lonvia** [comment]
Fix will go live in a bit. Lets see if that breaks other things.
