### ISSUE TITLE
3.0.0 -> 3.1.0 -> 3.2.0 migration 

### ISSUE THREAD

**Issue by jdvjdv82** [openstreetmap/Nominatim#1171]
hello
while migrating from 3.0.0 to 3.1.0
i was able to Create postcode table and indexes and it took almost day
i just skipped the last step to delete old artificial postcodes.

so far so good

unfortunatelly i am not able to create any of the new indexes in 3.1.0 -> 3.2.0 "tutorial"
```
nominatim=# CREATE INDEX idx_placex_geometry_reverse_lookupPoint
nominatim-#   ON placex USING gist (geometry) {ts:search-index}
nominatim-#   WHERE (name is not null or housenumber is not null or rank_address between 26 and 27)
nominatim-#     AND class not in ('railway','tunnel','bridge','man_made')
nominatim-#     AND rank_address >= 26 AND indexed_status = 0 AND linked_place_id is null;
```
i am always getting this error message
```
ERROR:  syntax error at or near "{"
LINE 2:   ON placex USING gist (geometry) {ts:search-index}
                                          ^
```
any idea please?

btw: if i will grant website user to access the `country_osm_grid table`, then system works

**Comment by lonvia** [comment]
Simply remove the stuff in curly braces from the INDEX commands. That was a copy&paste error. I will fix the documentation shortly.
