### ISSUE TITLE
getAddressDetails with parameter false does not work

### ISSUE THREAD

**Issue by BogdanArdelean** [openstreetmap/Nominatim#1172]
In Nominatim/lib/AddressDetails.php, method getAddressDetails does not work when called with parameter set to false.
`return array_filter($this->aAddressLines, 'AddressDetails::isAddress');` is called with erroneous second parameter.
Shouldn't it be `return array_filter($this->aAddressLines, array(__CLASS__, 'isAddress'));`?

**Comment by mtmail** [comment]
Makes sense. I think we didn't notice because the only call with `false` comes from `hierarchy.php` and we stopped supporting the endpoint (undocumented, no feature tests in the test suite). I'll prepare a patch and test for the class.
