### ISSUE TITLE
Problem with street name, Hungary, Kertköz utca

### ISSUE THREAD

**Issue by hydroxyweb** [openstreetmap/Nominatim#1175]
Hi,
there is a problem with a street name in Hungary. There is a Kertköz utca, but the API returns with Kert köz, which is wrong. 
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=47.567980882099995&lon=19.1232705116272&zoom=18
The Kertköz utca is the longer one, parallel with Lóvasút köz.

**Comment by mtmail** [comment]
You can edit the street name on https://www.openstreetmap.org/way/30193460 directly. Nominatim updates almost real-time (well, wait 10 minutes after the change). https://www.openstreetmap.org/fixthemap

But I see in the history of the place https://www.openstreetmap.org/way/30193460/history somebody else changed it "Kertköz utca" -> "Kert köz" 7 months ago. I can't read/understand the Hungarian comments. If the street has two names, e.g. one historic and both are valid, see https://wiki.openstreetmap.org/wiki/Names for tagging.

**Comment by ImreSamu** [comment]
Hi @hydroxyweb 
If you have a similar data problems,  You can reach the Hungarian OSM members here, and ask a help.
* https://www.facebook.com/groups/osm.hu/
* https://groups.google.com/forum/#!forum/openstreetmap-hungary
* https://www.meetup.com/OpenStreetMap-Hungary

or you can add an OSM notes for the local mappers.
* https://wiki.openstreetmap.org/wiki/Notes#Adding_notes
