### ISSUE TITLE
minutely update of planet - "batchsize is too large" database error

### ISSUE THREAD

**Issue by llomgui** [openstreetmap/Nominatim#1177]
Hey,

I was updating the database, after few hours I got this error:

> Currently at sequence 3130400 (03/09/2018 01:59:13) - t indexed
> /usr/bin/pyosmium-get-changes --server https://planet.openstreetmap.org/replication/minute -o /data/nominatim/Nominatim-3.2.0/build/osmosischange.osc -s 10000 -I 3130400
> /data/nominatim/Nominatim-3.2.0/build/osm2pgsql/osm2pgsql -klas --number-processes 1 -C 2000 -O gazetteer -d nominatim -P 5432 --flat-nodes /data/flatnode.file /data/nominatim/Nominatim-3.2.0/build/osmosischange.osc
> osm2pgsql version 0.96.0 (64 bit id space)
> 
> Using projection SRS 4326 (Latlong)
> Allocating memory for dense node cache
> Allocating dense node cache in one big chunk
> Allocating memory for sparse node cache
> Sharing dense sparse
> Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
> Mid: loading persistent node cache from /data/flatnode.file
> Mid: pgsql, cache=2000
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> 
> Reading in file: /data/nominatim/Nominatim-3.2.0/build/osmosischange.osc
> Using XML parser.
> Processing: Node(27329k 13.0k/s) Way(4076k 0.84k/s) Relation(95910 114.72/s)  parse time: 7812s
> Node stats: total(27329249), max(5903906204) in 2101s
> Way stats: total(4076861), max(625276619) in 4875s
> Relation stats: total(96104), max(8689181) in 836s
> Setting up table: planet_osm_nodes
> Setting up table: planet_osm_ways
> Setting up table: planet_osm_rels
> 
> Going over pending ways...
> 	0 ways are pending
> 
> Using 1 helper-processes
> Finished processing 0 ways in 0 s
> 
> 
> Going over pending relations...
> 	0 relations are pending
> 
> Using 1 helper-processes
> Finished processing 0 relations in 0 s
> 
> node cache: stored: 27329249(100.00%), storage efficiency: 80.32% (dense blocks: 3052, sparse nodes: 4511938), hit rate: 20.56%
> Stopping table: planet_osm_nodes
> Stopped table: planet_osm_nodes in 0s
> Stopping table: planet_osm_ways
> Stopped table: planet_osm_ways in 0s
> Stopping table: planet_osm_rels
> Stopped table: planet_osm_rels in 0s
> 
> Osm2pgsql took 7812s overall
> string(191) "INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('2018-09-13 12:34:59',3145558,7539160914,'2018-09-13 13:02:26','2018-09-13 15:12:38','import')"
> ERROR: 1
> INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('2018-09-13 12:34:59',3145558,7539160914,'2018-09-13 13:02:26','2018-09-13 15:12:38','import') [nativecode=ERROR:  integer out of range]

Can you tell me what I did wrong? Maybe it's because "batchsize" is too large and I should use another way to update the database?

**Comment by mtmail** [comment]
The `import_osmosis_log` table (https://github.com/openstreetmap/Nominatim/blob/master/sql/tables.sql#L10) might need to change to accommodate such large batch sizes.

unsigned `integer` allows "only"  2,147,483,647 (https://www.postgresql.org/docs/9.1/static/datatype-numeric.html)

In my production table, with daily updates, the largest value is 1,034,987,698 so it's not too far off one could be 3x that.

Can you try to change the column type? `ALTER TABLE import_osmosis_log ALTER COLUMN batchsize TYPE bigint;`
