### ISSUE TITLE
Make response compatible with geojson

### ISSUE THREAD

**Issue by sfkeller** [openstreetmap/Nominatim#118]
Ex ante: Nominatim is one of the most valuable and promising OSM services!

Nominatim response (parameter "polygon_geojson") suggests that the response is a valid GeoJSON format - but it's not currently.

Actually it would be very easy to make it valid with the following changes:
1. Replace "geojson" with "geometry".
2. Put "FeatureCollection" header in front.
3. For every feature, nest everything except geometry in attribute "properties".

See example below:
--S.

Example GET request: http://nominatim.openstreetmap.org/search?q=Oberseestrasse+10,+Rapperswil&format=jsonv2&polygon_geojson=1&addressdetails=1

Original Nominatim response:
    {
        "place_id": "44203959",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
        "osm_type": "way",
        "osm_id": "34179470",
        "boundingbox": [
            "47.2229156494141",
            "47.2242317199707",
            "8.82080268859863",
            "8.82882499694824"
        ],
        "lat": "47.224015",
        "lon": "8.824787",
        "display_name": "Oberseestrasse, Rapperswil-Jona, Wahlkreis See-Gaster, St. Gallen, 8645, Schweiz",
        "place_rank": "26",
        "category": "highway",
        "type": "tertiary",
        "importance": 0.5,
        "address": {
            "road": "Oberseestrasse",
            "city": "Rapperswil-Jona",
            "county": "Wahlkreis See-Gaster",
            "state": "St. Gallen",
            "postcode": "8645",
            "country": "Schweiz",
            "country_code": "ch"
        },
        "geometry": {
            "type": "LineString",
            "coordinates": [
                [
                    8.8208036,
                    47.2241061
                ],

Header snippet of correct GeoJSON response:
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "place_id": "44203959",
       ...

**Comment by lonvia** [comment]
I'd be happy to take a pull request for another template implementing geojson but chances are small that I will find the time to implement this myself.
