### ISSUE TITLE
Did not find address

### ISSUE THREAD

**Issue by eriosw** [openstreetmap/Nominatim#1190]
Did not find the address: 
Langegg 31, 8463 Leutschach an der Weinstraße

I think the address is entered correctly in OSM.
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=222290871&class=building

**Comment by mtmail** [comment]
House numbers can be associated with a street or a place (usually hamlet, village). Often small villages simply don't name their streets. In this case Langegg is a village https://de.wikipedia.org/wiki/Leutschach_an_der_Weinstra%C3%9Fe#Gemeindegliederung but there's no Langegg in OpenStreetMap data. Well, there's many in Austria by that name, but none close to this address.

I see a bus stop "Kapelle" at Langeggstrasse but no Kapelle (small church) on the map https://www.openstreetmap.org/node/2677499691 Could that be the village center?

If you add such a village https://www.openstreetmap.org/fixthemap and then change `addr:street` to `addr:place` on https://www.openstreetmap.org/way/222290871 it should be found. Nominatim search updates almost realtime.
