### ISSUE TITLE
Unable to Update Nominatim

### ISSUE THREAD

**Issue by fberdejo** [openstreetmap/Nominatim#1196]
Dear All,

Currently, Nominatim Docker (Nominatim version 3.0) by mediagis/nominatim. My issue is I cannot update contentiously. I already setup the updates in local.php 

LOCAL.PHP
<?php
 // Paths
 @define('CONST_Postgresql_Version', '9.5');
 @define('CONST_Postgis_Version', '2.2');
 // Website settings
 @define('CONST_Website_BaseURL', '/');
 @define('CONST_Replication_Url', 'http://download.geofabrik.de/asia/philippines-updates');
 @define('CONST_Replication_MaxInterval', '86400');     // Process each update separately, osmosis cannot merge multiple updates
 @define('CONST_Replication_Update_Interval', '86400');  // How often upstream publishes diffs
 @define('CONST_Replication_Recheck_Interval', '900');   // How long to sleep if no update found yet
 @define('CONST_Pyosmium_Binary', '/usr/local/bin/pyosmium-get-changes');

![image](https://user-images.githubusercontent.com/39943666/46268071-120fd480-c56b-11e8-81af-d2af65fb62a3.png)

![image](https://user-images.githubusercontent.com/39943666/46268041-dffe7280-c56a-11e8-8e02-e702b3ad4f2e.png)

Can someone help me.. thank you in advance.

**Comment by lonvia** [comment]
If you use mediagis/nominatim, then that is where you should ask for help about its setup.
