### ISSUE TITLE
Question: Updating Nominatim data of multiple regions

### ISSUE THREAD

**Issue by mbutler-79** [openstreetmap/Nominatim#1197]
Hi, 
I wanna to know when I decide to update nominatim, I can only update those data already downloaded? because I've downloaded osm data about two continets of planet from this source (https://download.geofabrik.de/ ).
so I can update just osm data of the same two continents from this link?
https://planet.openstreetmap.org/replication/

Thanks in Advance

**Comment by mtmail** [comment]
Updates are https://wiki.openstreetmap.org/wiki/OsmChange files. Basically they contain "add this place", "modify this place", "delete this place" and that needs to fit what is already in the database.

If you imported two regions (continents or countries or states) from https://download.geofabrik.de/ then you can keep them updated using this script https://gist.github.com/mdeweerd/9bc5f60f2d6733e907f3, of course modify it for your regions. The script was posted in https://github.com/openstreetmap/Nominatim/issues/60 and users report it works. I haven't tested it myself.

**Comment by casaulenbo** [comment]
hi

I am using Nominatim 3.2.0, and according to [instruction ](http://www.nominatim.org/release-docs/latest/admin/Import-and-Update/#updating-nominatim) it's said that we don't need osmosis any more.

But if i want to update multi countries, this script from [issue #60](https://github.com/openstreetmap/Nominatim/issues/60) is using this command `/usr/bin/osmosis --rri workingDirectory=${DIR}/. --wxc ${DIR}/${FILENAME}.osc.gz` with cause error: osmosis not found.

So the question is: in case of update multi countries (which nominatim 3.2.0) and must install osmosis?

Thank for your help!
