### ISSUE TITLE
Question about running update process adhoc or irregular

### ISSUE THREAD

**Issue by mbutler-79** [openstreetmap/Nominatim#1201]
Hi,
I wanted to know how can I update nominatim without setting this line in settings/local.php : 
```php
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/minute');
```

I mean I don't want to sync with osm, I want to update nominatim whenever I would like.
for example I have a osm data for two months ago, now I want to update them. but I don't know if I set replicarion service with above value, all data are updated from two months ago until now ?
how can I sure that updating process is correct ?

better to use this address ?
http://download.geofabrik.de/europe-updates/

Thanks in Advance

**Comment by mtmail** [comment]
On https://www.nominatim.org/release-docs/latest/admin/Import-and-Update/#updates you can see an example for Ireland with daily updates (86400 seconds = 1 day).

The update URL should match where you originally got the import data from. If you imported http://download.geofabrik.de/europe-latest.osm.pbf the yes, http://download.geofabrik.de/europe-updates/ should be used.

> I want to update nominatim whenever I would like.

The install instructions say `./utils/update.php --import-osmosis-all`. Instead run `./utils/update.php --import-osmosis` however often you like. E.g. in a cron job one per week. Or irregular manually.

>  all data are updated from two months ago until now?

Yes. Nominatim keeps track what was already updated using the `import_status` database table. If you run the update manually then it will start from the last known date (state). If you imported the Europe data two months ago it will run 60 updates. `./utils/update.php --check-for-updates` will tell you how many  updates.

**Comment by mbutler-79** [comment]
I appreciate for your help, it`s working great
