### ISSUE TITLE
village/municipality Die not found

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/Nominatim#1202]
Die is a village and a municipality in France
in osm db
village https://www.openstreetmap.org/node/1430593250
municipality https://www.openstreetmap.org/relation/66441
in nominatim db
https://nominatim.openstreetmap.org/details?osmtype=N&osmid=1430593250
https://nominatim.openstreetmap.org/details?osmtype=R&osmid=66441

but a query with "Die" found nothing
https://nominatim.openstreetmap.org/search.php?q=Die
and I don't see/understand why with the debug
https://nominatim.openstreetmap.org/search.php?q=Die&debug=1

maybe it's related to
https://github.com/openstreetmap/Nominatim/blob/26bc83c9844ceba531837bfed79cd51b12a6b45a/module/nominatim.c#L262

**Comment by nylnook** [comment]
Thanks for the report ;)

**Comment by mtmail** [comment]
Possible explanation: In German 'die' is a stop word, like 'le' or 'la' in French.

**Comment by lonvia** [comment]
There is a very, very old ticket about that already: https://trac.openstreetmap.org/ticket/4994

Another problem which needs to be solved via #1208. Closing here.
