### ISSUE TITLE
partial match from the beginning should be weighted similar to full match

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/Nominatim#1203]
If I search for "Maxxi Roma", which is a big national museum in Rome, the first hit is a bicycle parking and the second as well. Only after I click on "more results" I get the museum:
https://nominatim.openstreetmap.org/search.php?q=maxxi+roma

The museum has a wikipedia link, ist a big relation, compared to the bicycle parking nodes.
museum:
https://nominatim.openstreetmap.org/details.php?place_id=240108647
nodes:
https://nominatim.openstreetmap.org/details.php?place_id=22832733
https://nominatim.openstreetmap.org/details.php?place_id=22770243

I am not sure what is the cause, added now a short name to the museum thinking that maybe it is because of the full match being weighted much higher than the partial match, or maybe museums should be generally prefered more over parkings, as long as one doesn't specify "parking" in the search

**Comment by dieterdreist** [comment]
it is fixed. Minutely updates \o/ This concrete case was fixed by adding the short name, museum at first position now. I even get it with q=maxxi and a mapscreen at the other side of the world.

Not sure if this is an exceptional case, maybe the partial match if it is from the beginning should in general rank similar or equal to a full match.

**Comment by lonvia** [comment]
This problem is clearly not as simple as 'partial match in the beginning is important'. This heuristics already fails terribly with pretty much every street name in Italy.

**Comment by dieterdreist** [comment]
sent from a phone

> On 12. Oct 2018, at 17:30, Sarah Hoffmann <notifications@github.com> wrote:
> 
> This problem is clearly not as simple as 'partial match in the beginning is important'. This heuristics already fails terribly with pretty much every street name in Italy.


Yes, it would be too simple, focusing on the beginning was probably not the right idea, a complete but partial
match (whole search string is contained) is often good (clearly there are some exceptions, especially search strings with many hits like this should lead to more focus on other factors).

Do you agree the result was not optimal?

In this particular case another way to look at it would be understanding the spatial distribution, but it might be too expensive. The first three matches are all in a very small area (and actually the 2 parkings are inside the museum polygon), outside of this you have to leave the continent to find other matches. Nominatim did a good job in finding these three and putting them on top. But it shouldn’t be completely agnostic towards the feature type, some things are more likely to be looked for by name and could be prioritized (e.g. you do not search for a phone or post box with a name, bicycle parkings may be an edge case as some may have names (in other places like the Netherlands)).(Of course, as you know, the mere fact something has a wp article already makes it stand out from the mass of things).
