### ISSUE TITLE
Allow Region Search By Code

### ISSUE THREAD

**Issue by kiler129** [openstreetmap/Nominatim#1206]
In USA almost noone uses full state names, instead everyone uses codes (e.g. IL for Illinois). 

Nominatim support for searching by codes seems spoty. E.g. take this example:
 - https://nominatim.openstreetmap.org/search.php?q=8907+Warner+Ave+Ste+123%2C+Huntington+Beach%2C+California&polygon_geojson=1&viewbox=
 - https://nominatim.openstreetmap.org/search.php?q=8907+Warner+Ave+Ste+123%2C+Huntington+Beach%2C+CA&polygon_geojson=1&viewbox=

First result returns results while second does not. What's interesting removing "Ste" causes both to work.

**Comment by lonvia** [comment]
As you noticed correctly, this has nothing to do whatsoever with searching with state codes. That works fine. It's those crappy postcodes again. The amount of bad postcode data in OSM is just astonishing and the US seems to be especially bad.

Fixes are #988 and parsing postcodes by format, for which I have now opened #1207. Closing here as known issue.

**Comment by lonvia** [comment]
I stand corrected. The issue here is indeed 'ste 123' which is a term that's not in OSM. Nominatim needs a full match, it cannot leave out terms from the query. That the first one works is purely coincidental.
