### ISSUE TITLE
Postcode areas are ignored in address computation

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/Nominatim#1209]
(Original issue: https://github.com/komoot/photon/issues/358)

German postcode areas seem to be missing in the addresses at the moment.

Examples:
 * [Buttendorf](https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=736804065&class=place) should be in [90574](https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3351238&class=place)
 * [Escherndorf](https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=360020751&class=place) should be in [97332](https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=1177813&class=place)

**Comment by jbelien** [comment]
> Is this the same issue that prevents this way to be mapped in the correct postal zone?
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=31288048&class=highway

Indeed, this street should be in postal code `2180` instead of `2030` since 1st January 2019.
The postal code relation are updated in OSM but it doesn't apply in Nominatim...

- Postalcode `2030` : https://www.openstreetmap.org/relation/3365424
- Postalcode `2180` : https://www.openstreetmap.org/relation/3365440

**Comment by mtmail** [comment]
Yes, same issue. Thanks for the Belgium examples.

**Comment by lonvia** [comment]
That was just outdated entries. Due to some optimizations not all objects are updated when an area is changed. I've updated everything in the two areas now and it should be fine again.

**Comment by jbelien** [comment]
Thanks a lot @lonvia \o/

**Comment by fabiowoj** [comment]
@lonvia , its possible to update Brazil postal codes too? Because the postal code 70235-070 from Federal District is not return data in nominatim. Thanks for your attention.

**Comment by mtmail** [comment]
@fabiowoj That's a different issue. There's no address/building with postcode 70235 in OpenStreetMap data. It should be in or near SQS 205. If you know the area you can add the postcode to a building.
![image](https://user-images.githubusercontent.com/3727288/58968502-73e9a380-87b6-11e9-8761-2329870611a3.png)

**Comment by lonvia** [comment]
Turns out that this is intentional because German postcodes have a relatively low rank of 21.
