### ISSUE TITLE
state missing in reverse geocoding

### ISSUE THREAD

**Issue by RazAlon** [openstreetmap/Nominatim#121]
I was told it's a good idea to report it, see last few comments in:

https://help.openstreetmap.org/questions/31439/state-is-missing-in-reverse-geocoding

**Comment by lonvia** [comment]
The example query was: http://nominatim.openstreetmap.org/reverse?lat=39.062966597302903&lon=-94.608148997737700

The address hierarchy should actually contain both states and choose one of the two for the address.
