### ISSUE TITLE
reverse gets two different result for the same place (xml,json)

### ISSUE THREAD

**Issue by touatily** [openstreetmap/Nominatim#1211]
Hi,

I have Nominatim installed in a server, and I got something strange:
[XML result](http://reversegeocoding.omogen.online/reverse.php?lat=49.0271482&lon=2.3699513999999997&addressdetails=1)
[JSON result](https://nominatim.openstreetmap.org/reverse?lat=49.0271482&lon=2.3699513999999997&addressdetails=1&format=json)

The XML response show that `Ecouen` is a city.
However, in the JSON result, `Ecouen` is a village!

Can you explain this please?

**Comment by mtmail** [comment]
The search logic is the same for output formats. In the Nominatim database two places are linked together:

1. the boundary https://www.openstreetmap.org/relation/534455 as `boundary=administrative`
`admin_level=8` which is usually a town. Or at least Nominatim returns it in the `town` key in the output. https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#10_admin_level_values_for_specific_countries says for France it's a commune (https://en.wikipedia.org/wiki/Communes_of_France)
2. the center https://www.openstreetmap.org/node/26698460 as `place=village`

So Nominatim gets conflicting information when merging the two into one. It looks like sometimes the place gets returns as town, other as village. The server nominatim.openstreetmap.org also caches responses so one wouldn't see fluctuation.

https://en.wikipedia.org/wiki/%C3%89couen says the place is a commune and thus I'd argue the place node should be `place=town`. Same for the nearby Ézanville (https://www.openstreetmap.org/node/26696066 https://en.wikipedia.org/wiki/%C3%89zanville)

Looking at other places nearby Domont, Sarcelles, Villiers-le-Bel are tagged as town.

If you're familiar with editing OpenStreetMap you can change the places. I'd suggest checking with French OpenStreetMap mappers in case there was earlier discussion or agreement how communes should be tagged https://lists.openstreetmap.org/listinfo/talk-fr
