### ISSUE TITLE
Question about running update process adhoc or irregular for planet...

### ISSUE THREAD

**Issue by mbutler-79** [openstreetmap/Nominatim#1212]
Hi,
I have a question about if I want to update nominatim irregularly for planet based on minutely, hourly or daily, I should set any of these addresses in setting/local.php in nominatim folder?
```php
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/minute');
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/hour');
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day');
```
or I should use another address ?
I want to update planet data irregularly, not sync with osm.
I know about updating nominatim data for some special countries, but don't know about planet...

Thanks in Advance

**Comment by mtmail** [comment]
Yes, for the whole planet one of the three URLs will work fine.

**Comment by mbutler-79** [comment]
Thank you for your response
when I was updating nominatim based a specific country, I had to run this command until --check-for-update would return 'Database up to date.' : 
```bash 
/home/nominatim/Nominatim-3.1.0/build/utils/update.php --import-osmosis
```
in every time above command is run, you should check result of this command: 
```bash
/home/nominatim/Nominatim-3.1.0/build/utils/update.php --check-for-updates
```

**Comment by mtmail** [comment]
You can also use `--import-osmosis-all`, which will do the same: run updates until there are none left.
