### ISSUE TITLE
Oracle Linux with pgsql 10 installed unto /user/pgsql-10 cmake failing with errors

### ISSUE THREAD

**Issue by ssefick** [openstreetmap/Nominatim#1217]
Hello,

I am trying to build Nominatim on Oracle Enterprise Linux 7.x. I have installed postgresql 10 from the postgresql repositories. The install is located in /usr/pgsql-10/

Thank you for any help in advance.

I am receiving the below error messages. I will provide whatever I am able to in order to help debug.

-- Building osm2pgsql 0.96.0
cmake ../Nominatim-3.2.0
-- Building osm2pgsql 0.96.0
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   filesystem
CMake Warning at /usr/share/cmake/Modules/FindPostgreSQL.cmake:109 (message):
  Couldn't determine PostgreSQL configuration.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:121 (fail_if)
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:127 (run_pg_config)
  osm2pgsql/CMakeLists.txt:117 (find_package)

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY_DIRS
  PostgreSQL_INCLUDE_DIRS PostgreSQL_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:173 (find_package_handle_standard_args)
  osm2pgsql/CMakeLists.txt:117 (find_package)

**Comment by mtmail** [comment]
The https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindPostgreSQL.cmake logic is somewhat readable in what it tries and which environment variables one can set for non-standard install locations.

Easiest seems to be to set a `PostgreSQL_ROOT` environment variable to `/usr/pgsql-10/`.
