### ISSUE TITLE
Nominatim geocoding slow performance

### ISSUE THREAD

**Issue by ramazotti7** [openstreetmap/Nominatim#1218]
Dear developers and nominatim users,

I've been using the nominatim for over 2 years now and I'm thrilled.
With a server reorganization and installation of the version 3.2.0 however I have massive performance problems.

As a data import I have cut together several countries with Osmosis (Central Europe), which also worked well. After the installation I found out that the inquiry of an address over the Nominatim takes approx. 3-5 seconds (on the old server the reaction time is far under 1 second / version 2.5.0).

Then I fought through the various posts here, but unfortunately could not find a solution.

These are my tests where I can see that the query is not using the index - I don´t know why?

```
\d search_name
                          Table "public.search_name"
       Column       |          Type           | Collation | Nullable | Default
--------------------+-------------------------+-----------+----------+---------
 place_id           | bigint                  |           |          |
 importance         | double precision        |           |          |
 search_rank        | smallint                |           |          |
 address_rank       | smallint                |           |          |
 name_vector        | integer[]               |           |          |
 nameaddress_vector | integer[]               |           |          |
 country_code       | character varying(2)    |           |          |
 centroid           | geometry(Geometry,4326) |           |          |
Indexes:
    "idx_search_name_centroid" gist (centroid)
    "idx_search_name_name_vector" gin (name_vector) WITH (fastupdate=off)
    "idx_search_name_nameaddress_vector" gin (nameaddress_vector) WITH (fastupdate=off)
    "idx_search_name_place_id" btree (place_id)
```

```
\d placex
                             Table "public.placex"
     Column      |            Type             | Collation | Nullable | Default
-----------------+-----------------------------+-----------+----------+---------
 place_id        | bigint                      |           | not null |
 parent_place_id | bigint                      |           |          |
 linked_place_id | bigint                      |           |          |
 importance      | double precision            |           |          |
 indexed_date    | timestamp without time zone |           |          |
 geometry_sector | integer                     |           |          |
 rank_address    | smallint                    |           |          |
 rank_search     | smallint                    |           |          |
 partition       | smallint                    |           |          |
 indexed_status  | smallint                    |           |          |
 osm_id          | bigint                      |           | not null |
 osm_type        | character(1)                |           | not null |
 class           | text                        |           | not null |
 type            | text                        |           | not null |
 name            | hstore                      |           |          |
 admin_level     | smallint                    |           |          |
 address         | hstore                      |           |          |
 extratags       | hstore                      |           |          |
 geometry        | geometry(Geometry,4326)     |           | not null |
 wikipedia       | text                        |           |          |
 country_code    | character varying(2)        |           |          |
 housenumber     | text                        |           |          |
 postcode        | text                        |           |          |
 centroid        | geometry(Geometry,4326)     |           |          |
Indexes:
    "idx_place_id" UNIQUE, btree (place_id)
    "idx_placex_adminname" btree (make_standard_name(name -> 'name'::text), rank_search) WHERE osm_type = 'N'::bpchar AND rank_search < 26
    "idx_placex_geometry" gist (geometry)
    "idx_placex_geometry_reverse_lookuppoint" gist (geometry) WHERE (name IS NOT NULL OR housenumber IS NOT NULL OR rank_address >= 26 AND rank_address <= 27) AND (class <> ALL (ARRAY['railway'::text, 'tunnel'::text, 'bridge'::text, 'man_made'::text])) AND rank_address >= 26 AND indexed_status = 0 AND linked_place_id IS NULL
    "idx_placex_geometry_reverse_lookuppolygon" gist (geometry) WHERE (st_geometrytype(geometry) = ANY (ARRAY['ST_Polygon'::text, 'ST_MultiPolygon'::text])) AND rank_address >= 4 AND rank_address <= 25 AND type <> 'postcode'::text AND name IS NOT NULL AND indexed_status = 0 AND linked_place_id IS NULL
    "idx_placex_geometry_reverse_placenode" gist (geometry) WHERE osm_type = 'N'::bpchar AND rank_search >= 5 AND rank_search <= 25 AND class = 'place'::text AND type <> 'postcode'::text AND name IS NOT NULL AND indexed_status = 0 AND linked_place_id IS NULL
    "idx_placex_linked_place_id" btree (linked_place_id) WHERE linked_place_id IS NOT NULL
    "idx_placex_osmid" btree (osm_type, osm_id)
    "idx_placex_parent_place_id" btree (parent_place_id) WHERE parent_place_id IS NOT NULL
    "idx_placex_pendingsector" btree (rank_search, geometry_sector) WHERE indexed_status > 0
    "idx_placex_rank_address" btree (rank_address)
    "idx_placex_rank_search" btree (rank_search)
Triggers:
    placex_before_delete AFTER DELETE ON placex FOR EACH ROW EXECUTE PROCEDURE placex_delete()
    placex_before_insert BEFORE INSERT ON placex FOR EACH ROW EXECUTE PROCEDURE placex_insert()
    placex_before_update BEFORE UPDATE ON placex FOR EACH ROW EXECUTE PROCEDURE placex_update() 
```

```
EXPLAIN ANALYSE 
select place_id, (select count(*) from (select unnest(ARRAY[3812153,25341452]) 
INTERSECT select unnest(nameaddress_vector))s) as exactmatch 
from search_name 
where 	name_vector @> ARRAY[594748] 
	and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[9322262,60932,4043821] 
	and country_code = 'de' 
order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2;

"Limit  (cost=2054940.32..2054940.32 rows=1 width=24) (actual time=6119.010..6119.010 rows=0 loops=1)"
"  ->  Sort  (cost=2054940.32..2054940.32 rows=1 width=24) (actual time=6119.010..6119.010 rows=0 loops=1)"
"        Sort Key: (CASE WHEN ((search_name.importance = '0'::double precision) OR (search_name.importance IS NULL)) THEN ('0.75'::double precision - ((search_name.search_rank)::double precision / '40'::double precision)) ELSE search_name.importance END) DE (...)"
"        Sort Method: quicksort  Memory: 25kB"
"        ->  Seq Scan on search_name  (cost=0.00..2054940.31 rows=1 width=24) (actual time=6119.006..6119.006 rows=0 loops=1)"
"              Filter: ((name_vector @> '{594748}'::integer[]) AND ((country_code)::text = 'de'::text) AND (array_cat(nameaddress_vector, '{}'::integer[]) @> '{9322262,60932,4043821}'::integer[]))"
"              Rows Removed by Filter: 22431175"
"              SubPlan 1"
"                ->  Aggregate  (cost=3.53..3.54 rows=1 width=8) (never executed)"
"                      ->  Subquery Scan on s  (cost=0.00..3.52 rows=1 width=0) (never executed)"
"                            ->  HashSetOp Intersect  (cost=0.00..3.51 rows=1 width=8) (never executed)"
"                                  ->  Append  (cost=0.00..3.01 rows=200 width=8) (never executed)"
"                                        ->  Subquery Scan on "*SELECT* 1"  (cost=0.00..1.51 rows=100 width=8) (never executed)"
"                                              ->  Result  (cost=0.00..0.51 rows=100 width=4) (never executed)"
"                                        ->  Subquery Scan on "*SELECT* 2"  (cost=0.00..1.51 rows=100 width=8) (never executed)"
"                                              ->  Result  (cost=0.00..0.51 rows=100 width=4) (never executed)"
"Planning time: 0.127 ms"
"Execution time: 6119.038 ms"
```

I have a fast ubuntu 16.04 server with SSD and NVMe (no normal Harddisk) and 64 MB RAM. The processors benchmark ist 15000+
The postgresql.conf is configured like my old server and checked against the recommendation.

I hope someone can help me soon.
Thanks a lot in advance.
Rainer

**Comment by ramazotti7** [comment]
I closed my request by mistake :-( 
No I opend it and hope someone can help me.
greetings Rainer

**Comment by mtmail** [comment]
Can you share which address you searched that the `EXPLAIN ANALYSE` refers to? I ran the same and get different output but it's probably because the ids (place_id) are different in my database.

**Comment by ramazotti7** [comment]
Hello and thank you for your answer.

the query is above the result and I found this select in this forum for testing: 

EXPLAIN ANALYSE 
select place_id, (select count(*) from (select unnest(ARRAY[3812153,25341452]) 
INTERSECT select unnest(nameaddress_vector))s) as exactmatch 
from search_name 
where 	name_vector @> ARRAY[594748] 
	and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[9322262,60932,4043821] 
	and country_code = 'de' 
order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC, exactmatch DESC limit 2;



But it is the same, if I sent a normal query over the url like the follow:
http://ip/nominatim/search?format=json&addressdetails=1&polygon=0&limit=5&street=5%2CMettackerweg&postalcode=79111&city=Freiburg+im+Breisgau&countrycodes=de

I get the answer in around 4-5 seconds.

**Comment by mtmail** [comment]
On my installation I get
```
->  Bitmap Heap Scan on search_name  (cost=109.77..34194.64 rows=1 width=24) (actual time=0.349..0.350 rows=0 loops=1)
```
while you get
```
->  Seq Scan on search_name  (cost=0.00..2054940.31 rows=1 width=24) (actual time=6119.006..6119.006 rows=0 loops=1)
```

The index definitions you posted look good though. It's worth testing to recreate the index (https://www.postgresql.org/docs/9.6/static/sql-reindex.html)

**Comment by ramazotti7** [comment]
I´ve done the reindex (only for this 2 tables):
reindex table search_name;
reindex table place;

but the query time and the result (seq scan) is the same

**Comment by ramazotti7** [comment]
After the partial indexing had brought nothing, I reindexed all the tables. 

export PGOPTIONS="-P";
psql nominatim
nominatim=> REINDEX DATABASE broken_db;

Unfortunately with the same result: The search is sequential.
Now I do not know how to help further, how the problem can be further limited or solved.

**Comment by ramazotti7** [comment]
Ok. I don´t know until now, what the problem was (perhaps the import of data whithout a flatnode-file?), but I installed the data complete new an make only a VACUUM FULL ANALYSE, nothing else.

Now it is like it should: 
 Planning time: 0.857 ms
 Execution time: 0.202 ms

@mtmail: Thank you a lot for your help

**Comment by mtmail** [comment]
I'm glad it works now. You already followed all best practices, you look at previous closed issues and ran the reindexing correctly. From the table schemas you posted everything looked alright. Full reinstall/reimport would've been the next step. I wish I knew what causes those queries to run slow.

**Comment by ramazotti7** [comment]
Now, by chance, I discovered the problem that triggered the massive performance loss for me:
the installation of the extension intarray in the postgres (CREATE EXTENSION intarray).

Why is that?

This does not seem to be a problem in the old Nominatim versions.

**Comment by lonvia** [comment]
Nothing particular has changed in Nominatim with respect to use of int[]. My guess would rather be that you have also changed postgres versions between updates and something has changed there. Nominatim is using int[] operations quite extensively. If the intarray extension replaces the operation in a way that is incompatible with the installed GIN indexes, then you might end up with the behaviour you see. You might have success with replacing the relevant indexes with the variants from the intarray extension.

But that's all guessing from my side. I haven't actually tried any of this.

**Comment by ramazotti7** [comment]
Thank you Sarah, for your detailed explanation of what I can understand well. The Postgres version is still the 9.6 but I will take a closer look at it.
