### ISSUE TITLE
Exact address match has lower priority than partially matching street if house number not on first position

### ISSUE THREAD

**Issue by scaidermern** [openstreetmap/Nominatim#1221]
This query returns the correct results: [64 Bergstraße, Dresden](https://nominatim.openstreetmap.org/search.php?q=64+Bergstraße%2C+Dresden)

However in Germany the house number usually comes after the street. However this query doesn't work as expected: [Bergstraße 64, Dresden](https://nominatim.openstreetmap.org/search.php?q=Bergstra%C3%9Fe+64%2C+Dresden)

(My browser sends `Accept-Language:"de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3"`, unsure if this has any influence here)

Results:
1. [Bergstraße, Räcknitz/Zschertnitz, Räcknitz, Plauen, Dresden](https://nominatim.openstreetmap.org/details.php?place_id=69194742), importance 0.350619650139669: A street that matches only partially, i.e. the "64" from the query isn't part of the tags. Also, the street has a pretty large distance to the house number 64.
2. [Bergstraße, Räcknitz/Zschertnitz, Kaitz, Plauen, Dresden](https://nominatim.openstreetmap.org/details.php?place_id=69040748), importance 0.350619650139669: Similar to result 1.
3. [Technische Universität Dresden, 64, Bergstraße, Räcknitz/Zschertnitz, Räcknitz, Plauen, Dresden](https://nominatim.openstreetmap.org/details.php?place_id=53352074), importance 0.33100000000000007: Toilets inside the building I'm searching for.
4. [Hörsaalzentrum, 64, Bergstraße, Räcknitz/Zschertnitz, Räcknitz, Plauen, Dresden](https://nominatim.openstreetmap.org/details.php?place_id=79403929), importance 0.33100000000000007: The address I'm looking for.

In #1086 it is stated that Nominatim should be fine if the house number appears right before the comma instead of the beginning of the query.

**Comment by lonvia** [comment]
Fixed by #988.
