### ISSUE TITLE
Lookup for way 116968867 returns nothing (it's a building)

### ISSUE THREAD

**Issue by Codain** [openstreetmap/Nominatim#1223]
Consider this building: https://www.openstreetmap.org/way/116968867

Lookup query does not return any result:
https://nominatim.openstreetmap.org/lookup?osm_ids=W116968867

Same issue with following buildings which are close to previous one:

- https://nominatim.openstreetmap.org/lookup?osm_ids=W116968899
- https://nominatim.openstreetmap.org/lookup?osm_ids=R8292395
- https://nominatim.openstreetmap.org/lookup?osm_ids=W116968343
- https://nominatim.openstreetmap.org/lookup?osm_ids=W116968881

Interestingly this one works: https://nominatim.openstreetmap.org/lookup?osm_ids=W116968352

Is there something wrong with those buildings or the API?

**Comment by lonvia** [comment]
This result is as expected. Nominatim does not index buildings that do not have a name or housenumber. Doing so would double the size of the database, so this not something that is going to change. If you need the address of such a building use `/reverse` with the centroid coordinate of the building.
