### ISSUE TITLE
 export.php does not do what it should (or error lies with me)

### ISSUE THREAD

**Issue by ramazotti7** [openstreetmap/Nominatim#1226]
I want to get a list of placeid; street; postcode; city; country out of nominatim and want to use export.php for this. The reason is that we do a phonetic preprocessing of the addresses to eliminate typographical errors as much as possible.

If I called the function like follows:
./utils/export.php --output-type street;city;postcode;country;county;placeid;state --output-format placeid;street;postcode;city;country  --output-all-postcodes

I get something like this:
"Ailinger Straße",Schmitthennersiedlung,Friedrichshafen,Bodenseekreis,Baden-Württemberg,Deutschland

But that's not what I stated in the output format.

What did I wrong?

**Comment by mtmail** [comment]
`output-type` needs only a single value. It describes the maximum rank, default is `street`, so you can omit it.

For `output-format` put the parameter value is quotes.

`./utils/export.php --restrict-to-country de --output-format "placeid;street;postcode;city;country" --output-all-postcodes`
```
107109819,"1000 Mark Weg",76337,Waldbronn,Deutschland
81122863,1000m-Weg,72270,Baiersbronn,Deutschland
81175584,1000m-Weg,77728,Oppenau,Deutschland
```

**Comment by ramazotti7** [comment]
Thank you a lot for your help, mtmail -now, it´s also clear for me ;-)
Greetings Rainer
