### ISSUE TITLE
Short names for cities are used in address return for reverse geocoding

### ISSUE THREAD

**Issue by markus0m** [openstreetmap/Nominatim#1227]
Example: https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=49.5&lon=11.1&addressdetails=1&accept-language=cz

This gives "Nbg" in the city field of the address data, which is an irritating short name that nobody but a local can make anything out of.
The short_name field is probably used as a fallback here, but prioritized higher than a missing language.

This short name should _never_ be used in an address return, not in any language.
It's completely confusing and messing up the data set.
English, local language or any other full name would be better.

**Comment by mtmail** [comment]
Related https://github.com/openstreetmap/Nominatim/issues/783 and https://github.com/openstreetmap/Nominatim/issues/891

It's irritating but in this case I think it's clear "Nbg" is not "a recognizable, commonly used short version of" (https://wiki.openstreetmap.org/w/index.php?title=Key:name&uselang=en-US) Nuremburg/Nürnberg.

Can you remove it from the https://www.openstreetmap.org/node/1569338041 ?

**Comment by markus0m** [comment]
Thanks for the related issues I had missed.
Removed and closed!
