### ISSUE TITLE
1500 District Avenue in Burlington, MA 01803 - wrong zip code on openstreetmap

### ISSUE THREAD

**Issue by breathes** [openstreetmap/Nominatim#1228]
The app returns 01805 instead of 01803

**Comment by breathes** [comment]
https://maps.internetbrands.com/geoloc/search.php?q=1500+District+Avenue%2C+Burlington%2C+MA+01803&polygon_geojson=1&viewbox=-1151.71875%2C42.03297%2C1008.28125%2C42.03297

**Comment by mtmail** [comment]
Please provide details, not just copy&paste URLs of error messages.

**Comment by mtmail** [comment]
https://nominatim.openstreetmap.org/search.php?q=1500+District+Avenue+in+Burlington%2C+MA returns postcode 01803 now. In OpenStreetMap data I added a postcode to a nearby restaurant based on their website (https://www.openstreetmap.org/changeset/64200272) yesterday.

As for https://maps.internetbrands.com/geoloc/search.php the website reads "Data last updated:
2017/12/04 01:56 GMT " so nothing we can do about that. You'd need to contact the administrators at internetbrands.com
