### ISSUE TITLE
Nominatim picks up wrong place name

### ISSUE THREAD

**Issue by otbutz** [openstreetmap/Nominatim#1229]
Addresses belonging to this [hamlet](https://www.openstreetmap.org/node/303612727#map=16/48.7324/12.2934) end up in the results with place name from this [isolated dwelling](https://www.openstreetmap.org/node/4594846187).

Both are nodes with a `place=` tag but Nominatim picks the one which is more than 2 kilometers away from the houses in this hamlet.

![hamlet_vs_isolat_dwelling](https://user-images.githubusercontent.com/22315436/48143664-931b6380-e2af-11e8-9b27-f27382a04daf.png)

Example: https://nominatim.openstreetmap.org/details.php?place_id=149139573

![grafik](https://user-images.githubusercontent.com/22315436/48143812-e55c8480-e2af-11e8-95ed-1b484eeff989.png)

**Comment by lonvia** [comment]
Admin-level problem. Greilsberg is at the same level as Bayerbach and as the latter is an area, it wins. (You'll see that Greilsberg is there but greyed out.). Waldeck is considered a lower level and still within the search perimeter, so it is included, as there is none larger.

This is all a known problem and will get ~~fixed~~ improved at some point.

**Comment by lonvia** [comment]
Closing in favour of #575 which already talks about reducing the search perimeter for isolated_dwellings.
