### ISSUE TITLE
Internal Server Error Details: Could not get places for search terms.

### ISSUE THREAD

**Issue by DimmoK** [openstreetmap/Nominatim#1231]
Hello.

Sorry for my English.

I installed Nominatim and import and index OSM data.
When I try find any city then  error:

>Internal Server Error
>Nominatim has encountered an internal error while processing your request. This is most likely because of a bug in the software.

>Details: Could not get places for search terms.

>Feel free to report the bug in the OSM bug database. Please include the error message above and the URL you used.

Nominatim version 2.5.1

Thank's

**Comment by DimmoK** [comment]
I look postgres log file

2018-11-08 12:04:32 MSK ERROR:  canceling statement due to statement timeout
2018-11-08 12:04:32 MSK STATEMENT:  select place_id, 0::int as exactmatch from search_name where name_vector @> ARRAY[1144753] order by (case when importance = 0 OR importance IS NULL then 0.75-(search_rank::float/40) else importance end) DESC limit 20

Maybe the problem is in Postgres?

**Comment by otbutz** [comment]
> canceling statement due to statement timeout

Seems like your database is to slow. Hardware specs?

**Comment by lonvia** [comment]
Make sure you have all indexes on search_name, in particular `idx_search_name_name_vector`. If they are not there, then chances are, your import did not complete successfully. If the index is there, run an `ANALYZE` on the database.

I'm sorry to say, that we cannot any support beyond that for an version as old as 2.5.1.
