### ISSUE TITLE
Nominatim does not find partial string match

### ISSUE THREAD

**Issue by sommerluk** [openstreetmap/Nominatim#1232]
When searching for “[groupe médical du plateau](https://nominatim.openstreetmap.org/search.php?q=groupe+m%C3%A9dical+du+plateau&polygon_geojson=1&viewbox=)” than Nominatim does not find any result.

However, when searching for “[polyclinique groupe médical du plateau](https://nominatim.openstreetmap.org/search.php?q=polyclinique+groupe+m%C3%A9dical+du+plateau&polygon_geojson=1&viewbox=)” it does find [the corresponding OSM element](https://www.openstreetmap.org/node/4437963790) who’s name value is “Polyclinique Groupe Médical du Plateau”

I would expect that also the first, shorter search term would also find the same OSM element.

**Comment by lonvia** [comment]
Duplicate of #94.
