### ISSUE TITLE
Either map or OSM ID is misleading (Russia)

### ISSUE THREAD

**Issue by bobfromspace** [openstreetmap/Nominatim#1235]
On the page devoted to [Russian city district Pereslav'-Zalessky](https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=912501&class=boundary) the map shows the boundaries for Pereslavskiy municipal district while the ID is for the city (check the visualization [here).](http://polygons.openstreetmap.fr/get_image.py?id=912501&params=0) Along with that, the page for Pereslavskiy municipal district with correct ID is missing.

**Comment by mtmail** [comment]
Wouldn't the visualization be wrong here?

http://polygons.openstreetmap.fr/ "will generate the whole geometry of the given OSM relation id". And http://polygons.openstreetmap.fr/get_image.py?id=912501&params=0 shows the boundary of https://www.openstreetmap.org/relation/3354167 and not https://www.openstreetmap.org/relation/912501

**Comment by lonvia** [comment]
I have no idea what this polygon tool is doing but it's clearly the one that is wrong here.
