### ISSUE TITLE
Can't lookup it's own result strings for Hildesheim

### ISSUE THREAD

**Issue by riher** [openstreetmap/Nominatim#1236]
At least for Hildesheim, if I search for places and then again search for the result string, Nominatim can't find the place. (Remove "Europa" at the end, and it'll work)

This renders the directions function for the main website unusable for Hildesheim (and probably other places).

Compare this issue: https://github.com/openstreetmap/openstreetmap-website/issues/1874

**Comment by lonvia** [comment]
Nominatim does not give any guarantees that search is an inverse operation of reverse and will never do so. Any application that relies on such a behaviour is broken.

That said, we really should get rid of the continents in the database as they are just broken. So leaving the ticket open for that.

**Comment by riher** [comment]
Naive question, as I have just today started to get into OSM: Where is the relation city <-> continent stored? In the default OSM editor this doesn't seem editable.

**Comment by lonvia** [comment]
It is not store directly anywhere. Nominatim computes the address indirectly from the objects for the city and the continent.

**Comment by riher** [comment]
Why doesn't this apply to, for example, Berlin then? It's also in Europe.

**Comment by mtmail** [comment]
Europe exists as node (center point) only (https://www.openstreetmap.org/node/25871341) to there is no relation city<->continent. Searching for "Europe" works, adding "Europe" to an address likely fails. Similar for any feature covering multiple countries like the alps, a mountain range.

A solution might be to create a relation (multipolygon) for the continents but that immediately adds more problems, the least where exactly the boundaries are. Features larger than countries are controversial in OpenStreetMap http://nominatim.org/release-docs/develop/api/Faq/#4-can-you-return-the-continent

**Comment by riher** [comment]
@mtmail Thanks for the reply. This still adds more confusion, as to why Europe is listed here: https://nominatim.openstreetmap.org/details.php?place_id=198030068 as part of the "Address", but not for (most?) other places in Germany.
Any thoughts?

**Comment by mtmail** [comment]
I think it's the `is_in=Hildesheim,Niedersachsen,Bundesrepublik Deutschland,Europ` vallue of https://www.openstreetmap.org/node/18318938 because cities closer to the Europe node don't show the contintent in their address hierarchy.

@lonvia How about skipping the continent in the address string (`display_name`) generation? https://nominatim.openstreetmap.org/search.php?q=hildesheim&format=jsonv2&pretty=1

**Comment by lonvia** [comment]
I intended to remove all place=continent as candidates for addresses (i.e. rank_address = 0). I think it's also time to let the `is_in` tag vanish quietly.

**Comment by riher** [comment]
@mtmail Which cities do you mean specifically? For example [Dingelstädt](https://www.openstreetmap.org/relation/2394547#map=9/51.4609/10.5084) has no `is_in` but shows the same problem.
