### ISSUE TITLE
Nominatim Reverse Geocoding taking too long to get results

### ISSUE THREAD

**Issue by LawrenceWlt** [openstreetmap/Nominatim#1241]
I installed Nominatim (whole planet) on Ubuntu Server (16.04) with the following

**Specifications.**

```
RAM: 32 GB
CPU Cores: 8
Postgresql 9.5
Apache 2.4 server
```

Postgresql Configurations:

```
max_connections = 500
shared_buffers = 8GB
effective_cache_size = 24GB
maintenance_work_mem = 2GB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 4194kB
min_wal_size = 1GB
max_wal_size = 2GB
max_worker_processes = 8
``` 

Some reverse geocoding calls on Zoom 16 are taking very long time to get results, between 5s - 90s! CPU usage on average doesn't exceed 20%. It doesn't also utilize the effective_cache_size memory, only 2GB is used. Is there anything I can do to improve the performance?

**Comment by mtmail** [comment]
How long did the initial installation take roughly? Is the harddrive local or network mounted, SSD assume? Is the issue new or from the beginning? Which version of Nominatim are you using?

From database point of view run a reverse query with &debug=1 to see raw SQL queries, then run an `ANALYSE EXPLAIN` in the postgresql console. Examples https://github.com/openstreetmap/Nominatim/issues?utf8=%E2%9C%93&q=is%3Aissue+table+scan Basically we'd check if indices are used or the query does full table scans.

**Comment by LawrenceWlt** [comment]
Initial Installation took 48 hours to finish. The harddrive is local and a SSD. The issue occurs when there is a high load (CPU usage is minimal and the RAM usage also is minimal even when the load is high). Using Nominatim 3.2.0.

Running **EXPLAIN ANALYSE** over any query I get the following:

```
Planning time: 2.445 ms
Execution time: 25.197 ms
```

I have followed this [thread ](https://github.com/openstreetmap/Nominatim/issues/1218) and all the indexes are present.

**Comment by lonvia** [comment]
A reverse API call involves a couple of queries to the database. You need to find out wish one exactly is the slow one. In your postgresql config set `log_min_duration_statement` to something like 1000 and reload postgresql. Then rerun the slow reverse API call and then check in postgres' logs which queries where logged.

Please also run the same reverse API queries on nominatim.osm.org to confirm that it is not a general problem with the code.

**Comment by LawrenceWlt** [comment]
Actually the issue is not on Nominatim. It was caused by the server we are using to send requests. maxconnection was set to 2. Increasing the maxconnection to 50 made the response < 800ms.
