### ISSUE TITLE
Can I start an asynchronous import process?

### ISSUE THREAD

**Issue by Snickbrack** [openstreetmap/Nominatim#1243]
Hi,

can I start the import process with import.php as an async task?

Or does it blocks the DB and need to be synchronous?

**Comment by mtmail** [comment]
Synchronous only. If you worry about the terminal connection being open too long you can use the `screen` command (https://www.howtoforge.com/linux_screen). If you have other databases on the same machine they can still be accessed, but the machine will be under heavy CPU/disc load during the import.
