### ISSUE TITLE
Possibility to suggest keys and values via form like iD

### ISSUE THREAD

**Issue by yopaseopor** [openstreetmap/Nominatim#1244]
To adjust the search we want to do, could it be possible to attach a form which suggest some keys and values like iD suggestion of the item to edit does? Also with the possibility to restrict the search and the number of results.

**Comment by mtmail** [comment]
I don't quite understand the question. Can you give an example or two?

Restricting number of results already works, see the `limit` parameter http://nominatim.org/release-docs/latest/api/Search/

**Comment by lonvia** [comment]
Closing because of missing feedback.

**Comment by yopaseopor** [comment]
Hi! sorry for the delay. 

My suggestion is with a form and a predictive search that gives you something like iD presets.

Example: you want to search a parking, and also you want that parking it is free and people with disabilities  so when you put in your search parking , nominatim can suggest some options like free or fee, or access customers, residents, disabled, etc.
Also when you suggest a name predictive search can suggest some propierties of the name I want to search if I know it: What thing do I want to search? A park? A street? Also if you want to search a name for a street nominatim can suggest addr:street, highway...
