### ISSUE TITLE
useless escaping of "/" in JSON result

### ISSUE THREAD

**Issue by MinnieTheMoocher** [openstreetmap/Nominatim#1256]
Requesting a Nominatim result in JSON format returns a JSON output
which contains unnecessarily escaped forward slashes.
Compared to that, the XML output format is correct.

Example:

requesting this
`https://nominatim.openstreetmap.org/search?format=json&limit=1&q=Hamburg,Germany`
returns
```
[
   {
      "place_id": "114035",
      "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright",
      "osm_type": "node",
      "osm_id": "20833623",
      "boundingbox": [
         "53.390341",
         "53.710341",
         "9.840654",
         "10.160654"
      ],
      "lat": "53.550341",
      "lon": "10.000654",
      "display_name": "Hamburg, 20095, Deutschland",
      "class": "place",
      "type": "city",
      "importance": 0.859144260142488,
      "icon": "https:\/\/nominatim.openstreetmap.org\/images\/mapicons\/poi_place_city.p.20.png"
   }
]
```

The escaping does not really hurt but looks strange. Correct would be:
```
[
   {
      "place_id": "114035",
      "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
      "osm_type": "node",
      "osm_id": "20833623",
      "boundingbox": [
         "53.390341",
         "53.710341",
         "9.840654",
         "10.160654"
      ],
      "lat": "53.550341",
      "lon": "10.000654",
      "display_name": "Hamburg, 20095, Deutschland",
      "class": "place",
      "type": "city",
      "importance": 0.859144260142488,
      "icon": "https://nominatim.openstreetmap.org/images/mapicons/poi_place_city.p.20.png"
   }
]
```

Compared to that, the XML format does not have that flaw:
requesting this
`https://nominatim.openstreetmap.org/search?format=xml&limit=1&q=Hamburg,Germany`
correctly returns the following (note the forward slashes in URLs):
```
<searchresults timestamp="Thu, 29 Nov 18 18:07:47 +0000" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="Hamburg,Germany" polygon="false" exclude_place_ids="114035" more_url="https://nominatim.openstreetmap.org/search.php?q=Hamburg%2CGermany&exclude_place_ids=114035&format=xml&accept-language=de%2Cen-US%3Bq%3D0.9%2Cen%3Bq%3D0.8">
   <place place_id="114035" osm_type="node" osm_id="20833623" place_rank="16" boundingbox="53.390341,53.710341,9.840654,10.160654" lat="53.550341" lon="10.000654" display_name="Hamburg, 20095, Deutschland" class="place" type="city" importance="0.85914426014249" icon="https://nominatim.openstreetmap.org/images/mapicons/poi_place_city.p.20.png"/>
</searchresults>
```

See also:
https://stackoverflow.com/questions/3020094/how-should-i-escape-strings-in-json

**Comment by lonvia** [comment]
JSON formatting is entirely left to PHP's json_encode() functions. There is an `JSON_UNESCAPED_SLASHES` parameter for it and I'm not sure why we did not activate that when adding `JSON_UNESCAPED_UNICODE`. Might just have been an oversight. The internets suggest that escaping slashes is only useful when embedding json inside a `<script>` section. This is not something anybody should do with a response from the nominatim server. So I think we are safe there. The only thing that needs to be checked, if we are including it as part of our own html response.

**Comment by MinnieTheMoocher** [comment]
Could you point me to the source which suggests escaping forward slashes?
I can not imagine any usecase where that would be really needed.
Anyway: escaping must always be done context-sensitively, i.e., it depends on the language you are outputting to. Here, in JSON, it definitely is not necessary. If anybody puts that JSON into some other place (embedding it somewhere else etc.), then that again is a separate operation which has to apply its own escaping rules.
The unnecessary slash escaping should be removed here IMHO, it just adds confusion.

**Comment by mtmail** [comment]
For the json/jsonv2/geojson formats the results are serialized here https://github.com/openstreetmap/Nominatim/blob/master/lib/lib.php#L62

In PHP forward slashes are escaped by default. Starting PHP 5.4 one can set `JSON_UNESCAPED_SLASHES`. We already set `JSON_UNESCAPED_UNICODE` so pretty similar. PHP keep the old behaviour default for backward compatibility.

For HTML format the results are serialized inside a `<script>` block https://github.com/openstreetmap/Nominatim/blob/master/lib/template/address-html.php#L117 (there's several `*-html.php` templates). Here the escaping for forward slash should probably remain.

https://stackoverflow.com/questions/1580647/json-why-are-forward-slashes-escaped/9735430#comment74928050_1580682

**Comment by MinnieTheMoocher** [comment]
thank you!
