### ISSUE TITLE
Wrong parent id for some locations in Moldova on localhost

### ISSUE THREAD

**Issue by UnKn0wn27** [openstreetmap/Nominatim#1257]
I stumbled across a problem while analyzing the given data. Some of locations have the wrong parent id localy but on nominatim they are mapped correcly. What is the problem and is there a way to fix it?

A few examples:
local data(wrong answer):
![busila_local](https://user-images.githubusercontent.com/29236212/49294418-93c4a580-f4bb-11e8-8fe6-b8f4b55e4240.png)

nominatim(right answer)
![busilna_nomi](https://user-images.githubusercontent.com/29236212/49294448-ac34c000-f4bb-11e8-9b2a-485e49ae0a7e.png)

This one is strange since in the osm file it clearly has it tagged:

	<node id="264479954" lat="47.389907" lon="27.8122173" version="5" timestamp="2011-12-29T18:46:56Z" changeset="0">
		<tag k="name" v="Bușila"/>
		<tag k="is_in" v="Ungheni"/>
		<tag k="place" v="village"/>
		<tag k="name:ru" v="Бушила"/>
		<tag k="is_in:country" v="Moldova;MD"/>
	</node>

local data(wrong answer):
![bubuieci_local](https://user-images.githubusercontent.com/29236212/49294465-b5259180-f4bb-11e8-9b7f-60cceb056292.png)

nominatim(right answer)
![bubuieci_nomi](https://user-images.githubusercontent.com/29236212/49294582-0cc3fd00-f4bc-11e8-9604-cc495339fc19.png)

I went and downloaded the latest data from: https://download.geofabrik.de/europe/moldova.html
and updated my database. Also went and downloaded the last version from git.

I there a solution here?

**Comment by lonvia** [comment]
Geofabrik extracts are known to miss the occasional boundary way on the outer ends of the extract. Try what is described in [this trac ticket](https://trac.openstreetmap.org/ticket/4399) to fix that. Or use an extract that cuts the country with a buffer to guarantee that all boundaries are included.

**Comment by mtmail** [comment]
* https://wambachers-osm.website/boundaries/ (level 2 = country)
* or directly https://www.openstreetmap.org/relation/58974 (bottom left there's a "Downloa XML" link), but you need to add '/full` to the URL otherwise ways are just referenced and not included

**Comment by UnKn0wn27** [comment]
Thank you!

**Comment by UnKn0wn27** [comment]
i downloaded the xml file from https://www.openstreetmap.org/relation/58974/full and updated the db but it still shows me the errors mentioned aboved.
