### ISSUE TITLE
Reverse only update / Optimise Update

### ISSUE THREAD

**Issue by DuzAwe** [openstreetmap/Nominatim#1259]
Howdy, 

I ran `./utils/update.php --import-osmosis-all` after setting up the use of daily diffs and noticed the update process is limited to 2GB of Memory is there a way to alter this or to run daily diffs only for reverse only?

I currently have a 10 day waiting time on Rank 26.

**Comment by mtmail** [comment]
You can set `--osm2pgsql-cache`, default is `2000`.

The osm2pgsql step is only the first part of an update. If you say rank 26 is slow that's the place indexing. You can add more threads `--index-instances` (default is 1) if you have spare CPU cores. During initial import you probably used as many instances as possible, while during updates it's assumed you want to run them in the background and not affect users.

The next release of Nominatim will have a reverse-only mode.  https://github.com/openstreetmap/Nominatim/pull/1242/files

**Comment by DuzAwe** [comment]
Thanks mtmail, Just so I am 100% on the next steps on my side. You are saying to run an update with `./utils/update.php --import-osmosis-all` with modifiers. My import is already completed, it took about a day. I'm am now just trying to update the import with the daily diffs.

**Comment by lonvia** [comment]
Something sounds fishy here. If your initial import took a day and your update now reports 10 days for indexing of rank 26, then your initial import likely never finished. Could you give details how you did the initial import and how exactly your updates?

**Comment by DuzAwe** [comment]
Import
`wget https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf`

`./utils/setup.php --osm-file planet-latest.osm.pbf --all --osm2pgsql-cache 32000 2>&1 | tee setup.log`

Left running in a detached screen over the course of a day (started around 9) it was complete when I checked on it around 11 the following morning.

Update
Edit setttings/local.php
`// base URL of the replication service
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day/');
// How often upstream publishes diffs
@define('CONST_Replication_Update_Interval', '86400');
// How long to sleep if no update found yet
@define('CONST_Replication_Recheck_Interval', '7200');`

`./utils/update.php --init-updates`
`./utils/update.php --import-osmosis-all`

Took the better part of a day to reach rank 26 and then ground to a halt claiming 10 days to completion.

**Comment by mtmail** [comment]
Does `setup.log` suggest the import completed? How long was spent on rank 30 for example.

Can you run the queries `select count(*) from placex; select count(*) from placex where indexed_status!=0;` (0 = indexed). Those unindexed should only be a small fraction.

**Comment by DuzAwe** [comment]
The tail of the set up log (I can't copy paste, ask vsphere why), says "error text 8: deadlock deteced Detail: Process 6664 waits for sharelock on transaction 14287103"

**Comment by mtmail** [comment]
So the initial import never finished correctly. We've seen the deadlock warning before, something about database threads stepping on each other's feet and it rarely happens (never happened for any of my planet installs).

You can resume the initial import http://nominatim.org/release-docs/latest/admin/Faq/#can-a-stoppedkilled-import-process-be-resumed or keep the update process you started running. The first option will use more CPU cores and thus will be faster.

**Comment by lonvia** [comment]
To add to that: if you have already set up updates, then indexing has gone into a less efficient mode that can handle updates but takes longer. Before resuming the import as described in the link @mtmail posted, you should put the system back into "import mode" by running `./utiils/setup.php --create-functions`. Finish the import as described, then switch back to "update mode" with `./utiils/setup.php --create-functions --enable-diff-updates`.

**Comment by DuzAwe** [comment]
Thanks guys, so it ran instantly and is now sitting with a blinking cursor after all 4 ranks are done. It says each rank is 0 in 0 @ 0.00000 per second.

**Comment by lonvia** [comment]
I presume you found out that later ranks actually do something and finished by now?

**Comment by DuzAwe** [comment]
It never progressed further than 4. It's still updating, claiming now 6 days left (It has been paused a few times to allow other work to be done in the terminal)
