### ISSUE TITLE
Strange Admin Data in Ethopia

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1261]
Hello, 

accessing the following reverse lookup: https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=9.068195&lon=38.733673&zoom=42&accept-language=en&addressdetails=1

I get a strange JSON back (admin level2 =  level4 = Adis Ababa and no Ethiopia in the admin section):
`{"type":"FeatureCollection","geocoding":{"version":"0.1.0","attribution":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","licence":"ODbL","query":"9.068195,38.733673"},"features":[{"type":"Feature","properties":{"geocoding":{"place_id":"246458928","osm_type":"way","osm_id":"651242370","type":"residential","accuracy":0,"label":"Gulele_08_1741 St, Kolobo, American Gibi, Addis Ababa, 29303, Ethiopia","name":"Gulele_08_1741 St","street":"Gulele_08_1741 St","postcode":"29303","city":"Addis Ababa","state":"Addis Ababa","country":"Ethiopia","admin":{"level2":"Addis Ababa","level4":"Addis Ababa"}}},"geometry":{"type":"Point","coordinates":[38.7335750834153,9.06808308755197]}}]}`

I have no clue how this can happen, since the address line correctly contains Ethiopia, so it looks a bit like an issue with the level 2 determination?

**Comment by mtmail** [comment]
Yes, there seem to be two `admin_level=2` in the address line list https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=651242370&class=highway The places are tagged correctly in OSM data. Nominatim needs more logic.

The `format=geocodejson` got introduces recently and it's the first format returning the admin levels. The `formatted`/`label` string also goes through the address lines top-to-bottom (small to large) but ignored the admin_level values.

**Comment by InI4** [comment]
Sigh. A mere "admin levels must increase along hierarchy" might have helped?!

As our little project tries to obtain political hierarchies from Nominatim and old format=json isn't exactly bug free either, this is bad news for us. We are currently using the format=json structures, but manually fix them. Still wonder, how we could one day export such fixes to help you and us, but our data structure is tailored to our use case, so I hardly see a way of automated matching.

**Comment by mtmail** [comment]
So Vienna (https://www.openstreetmap.org/node/17328659), Berlin (https://www.openstreetmap.org/node/240109189), Copenhagen (https://www.openstreetmap.org/node/13707878), Oslo (https://www.openstreetmap.org/node/20981158) are also tagged wrong? That's why I assumed the places were ok. Of course you're right, cities are not countries.

**Comment by lonvia** [comment]
Sigh, it obviously means level of the administrative entity this thing is the capital for. The wiki even [mentions that use](https://wiki.openstreetmap.org/wiki/Key:admin_level). Need to have a look in the data, but I wouldn't be surprised, if we have a 50/50 use where half the time it refers to the place's level, half the time to the capital level.

**Comment by Megachip** [comment]
@mtmail ... interesting. Should be discussed in changeset why these tagged as admin_level 2

**Comment by lonvia** [comment]
So the full discussion about admin_level on places can be found here: https://lists.openstreetmap.org/pipermail/tagging/2014-May/017502.html The only conclusion that can be drawn here is that admin_level on place nodes can mean anything and are best ignored.

At the moment I've only changed the heuristics to compute the admin level names. That should fix the initially reported issue. The admin_levels on places are not used anywhere else, so this shouldn't create problems anywhere else. But good to know for any future changes to the boundary to place matching.

**Comment by InI4** [comment]
Oops, that was fast, yes, inital use case appears to be fixed now. Thx.
