### ISSUE TITLE
Search for "Walbrook, London" doesn't find the street called "Walbrook" in the City of London

### ISSUE THREAD

**Issue by RoToRa** [openstreetmap/Nominatim#1264]
The search for "Walbrook, London":

https://nominatim.openstreetmap.org/search.php?q=Walbrook%2C+London

Only finds two unrelated buidings with that name in London, but not the street in the City of London, that is:

https://nominatim.openstreetmap.org/details.php?place_id=69422069

However searching for just "Walbrook" or explicitly "Walbrook, City of London" do find it:

https://nominatim.openstreetmap.org/search.php?q=Walbrook
https://nominatim.openstreetmap.org/search.php?q=Walbrook%2C+City+of+London

I first thought it may be an issue with "London" != "City of London", but other streets work fine. For example the neighbouring street "Bucklersbury" is found with "Bucklersbury, London"

https://nominatim.openstreetmap.org/search.php?q=Bucklersbury%2C+London

**Comment by lonvia** [comment]
Tricky one but clearly a bug. The right street is found first as a full match and then again as a partial result with a discarded housenumber=london. The result is that Nominatim considers it an imperfect match and only shows it in the second batch of results (when using "Show more results").
