### ISSUE TITLE
Update another osm.pbf file

### ISSUE THREAD

**Issue by parsispresswala** [openstreetmap/Nominatim#1270]
I have successfully implemented Nominatim and it is working fine for me. But now I want to set another file with previous one.I have use following command for update.

./utils/update.php --import-file /home/parsis/newData.osm.pbf

But it is not working properly, only shows country name.

- `address: {
country: "Saudi Arabia",
country_code: "sa"
}`
- `address: {
country: "Nigeria",
country_code: "ng"
}`

Expecting following kind of result.

`address: {
road: "LBS Marg",
suburb: "T Ward",
city_district: "Zone 6",
city: "Mumbai",
county: "Greater Bombay",
state_district: "Mumbai Suburban",
state: "Maharashtra",
postcode: "400082",
country: "India",
country_code: "in"
}`

**Comment by parsispresswala** [comment]
I got solution. I need to do Rank by using following command.
- /utils/update.php --index

What if I am inserting new data which does not exist in .osm.pbf file, then how should I insert data in nominatim?
what is the flow of inserting? How many table will reflect?

**Comment by lonvia** [comment]
You need to convert your data into OSM format and then import it the same way as other data. How to do that in detail is out of scope for this issue tracker. You can ask on the [mailing list](https://lists.openstreetmap.org/listinfo/geocoding).
