### ISSUE TITLE
Update state not saved if reindexing is needed

### ISSUE THREAD

**Issue by estadtherr** [openstreetmap/Nominatim#1274]
We had an error on our database server that aborted the indexing operation after applying an "osmosis" changeset. This left the `indexed` state as `f` in the `import_status` database table when the next iteration of the `import-osmosis` loop started. The updater correctly skipped the download/ingest of a new changeset and skipped to the `nominatim` index call. However, the subsequent attempt to update `import_osmosis_log` failed with this error (from the Postgres logs):

```
... postgres[9010]: [2-1] ERROR: syntax error at or near "," at character 128
... postgres[9010]: [2-2] STATEMENT: INSERT INTO import_osmosis_log(batchend, batchseq, batchsize, starttime, endtime, event) values ('15/11/2018 19:33:02',3236496,,'2019-01-02 19:00:06','2019-01-02 19:10:39','index')
```

It appears that `$iFileSize` is never set in this case, leading to the error we saw.

**Comment by lonvia** [comment]
Indeed. It could be read from the database when the reading of the new changeset is skipped. However, I wonder if that field shouldn't simply be always NULL for the indexing step. There is no file involved after all and the batchsize is already available in the first log entry.
