### ISSUE TITLE
Reverse warmup fails: "Uncaught Error: Cannot use object of type Nominatim\Result as array"

### ISSUE THREAD

**Issue by louispotok** [openstreetmap/Nominatim#1276]
This is a new Nominatim install, import succeeded. I'm on AWS, I saved the post-import volume to an AMI and then created a new instance from that AMI. I tried running the warmup script, but the reverse warmup throws an error. Running `--search-only` works fine. And I'm able to actually query in the forward and reverse directions, but I'd like to be able to run the full warmup script.

> $ utils/warm.php -v
> Warm reverse:
-60.05, 32.7 = .49.46, 176.98 = .-3.02, -132.14 = .0.61, -9.66 = .4.73, 163.35 = .23.29, -28.43 = .-52.84, -138.35 = .-67.36, -110.77 = .68.85, 10.89 = .16.6, 130.73 = .-75.01, 3.05 = .29.9, 135.13 = .34.85, -20.64 = .-40.38, -68.69 = .8.88, -59.46 = .-6.16, -146.21 = .-54.26, -9.72 = .-77.47, 32.97 = .28.14, 32.92 = .-32.09, -52.8 = .-11.4, -162.69 = .80.8, 27.83 = .-4.73, 84.1 = .-47.38, 93.01 = .68.32, 68.2 = .57.3, -90.93 = PHP Fatal error:  Uncaught Error: Cannot use object of type Nominatim\Result as array in /srv/nominatim/Nominatim/build/utils/warm.php:41
Stack trace:
#0 {main}
  thrown in /srv/nominatim/Nominatim/build/utils/warm.php on line 41

The line numbers in my warm.php look a little different from what I see [here](https://github.com/openstreetmap/Nominatim/blob/ec4e3c36af238ae3c31a2f5eb727fe2a22f6d054/utils/warm.php#L41), but my line 41 is:
`if ($aLookup && $aLookup['place_id']) {`

Also, I can't find anything about the warmup script in the documentation - is the procedures for warming up a new server documented somewhere?

Any help would be much appreciated!

Edit: on a fresh instance, forward-search fails due to timeout even after `warm.php --searchonly` runs.

**Comment by lonvia** [comment]
I've fixed the warm.php script but I can't say that the script is extensively maintained.

I never really found the need to warm caches. After a couple of requests the database is already in a usable state. If you have slow-running queries then the cause is unlikely cold caches. Please check out similar issues for hints how to debug slow queries.
