### ISSUE TITLE
Barbara-Siedlung, Darmstadt

### ISSUE THREAD

**Issue by Erfc** [openstreetmap/Nominatim#1278]
The neighbourhood Barbara-Siedlung 
https://nominatim.openstreetmap.org/details.php?place_id=64475180
is falsely named as Parent of a number of Parks, Motorways and Residentials etc., although it covers only few streets.

**Comment by mtmail** [comment]
Lacking exact boundaries a lot is guessing by distance. Best approach is to replace the OSM node with a relation by the same name and tagged with `type`, `boundary` and if applicable `admin_level`. For example https://www.openstreetmap.org/relation/1647643

**Comment by lonvia** [comment]
Closing as data issue.
