### ISSUE TITLE
Extremely far away results when using viewbox and bounded

### ISSUE THREAD

**Issue by arvindkartik** [openstreetmap/Nominatim#1280]
When using viewbox and bounded, nominatim returns results belonging to countries so far away.

Example:[ Searching for "168 West" with viewbox "-86.7762972,40.4125641,-85.6029468,39.5132439" and bounded set to 1.](https://nominatim.openstreetmap.org/search.php?q=168%20West&viewbox=-86.7762972,40.4125641,-85.6029468,39.5132439&bounded=1&addressdetails=1&format=json) returns result for Serbia with place_id="200303923".

Another example: [Searching for "Park" with viewbox "-122.1,36.9,-122,37" and bounded set to 1.](https://nominatim.openstreetmap.org/search.php?q=park&viewbox=-122.1,36.9,-122,37&bounded=1&addressdetails=1&format=json) returns a result from France with place_id = "199544829". 

It seems that for both the examples, the results are coming due to a postal code match.
- For the first example, the returned result has postal_code "168"
- For the second example, the returned result has postal_code "PARK". However it is due to an incorrect entry on a different node which I've edited now on OSM. So this example may not work lately.

**Comment by bhachet** [comment]
Same issue here. It seems like the viewbox isn't _totally_ ignored though : a same request, with or without a viewbox, doesn't return the same results.
- [Search with "q=55", "bounded=1" and "viewbox=[...]" (a french town) : 2 results, none in the viewbox, none even in Europe](https://nominatim.openstreetmap.org/search?q=55&format=json&bounded=1&viewbox=0.854209,43.357565,0.918556,43.390130)
- [Search with "q=55" : 10 results](https://nominatim.openstreetmap.org/search?q=55&format=json&bounded=1&viewbox=0.854209,43.357565,0.918556,43.390130)
