### ISSUE TITLE
building on debian jessie (8.11)

### ISSUE THREAD

**Issue by jeremy-rutman** [openstreetmap/Nominatim#1285]
I'd like to put up a nominatim server on a debian jessie box. 
Looking at instructions here http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-16/ or for ubuntu-18 it seems I need postgres , so I decided to go for postgres10 and followed https://www.postgresql.org/download/linux/debian/ .
Then I also need php , but am not sure which version? `apt-get install php `hits 'unable to locate package'. Would I be better off installing debian9 , or should I continue installing latest versions of php and hope for the best?

**Comment by mtmail** [comment]
Anything from PHP 5.4 to 7.3 is supported. We're not happy about supporting 5.x but there's still operating systems that install them by default. https://secure.php.net/supported-versions.php

**Comment by jeremy-rutman** [comment]
thanks. the build seems to have gone ok. Trying 
`nominatim@dap-jupyter01:~/Nominatim-3.2.0$ ./utils/setup.php --osm-file data/antartica-latest.osm --all [--osm2pgsql-cache 28000] 2>&1 | tee setup.log`  as per guide, i hit 

`bash: ./utils/setup.php: @PHP_BIN@: bad interpreter: No such file or directory`
I imagine I should replace PHP_BIN with the path to php binary, or define an environment var?

**Comment by jeremy-rutman** [comment]
I modified locale vars, setting things to en_US.UTF-8 but still hit this:
```
nominatim@dap-jupyter01:~/Nominatim-3.2.0/build$ sudo nano /etc/locale.gen 
nominatim@dap-jupyter01:~/Nominatim-3.2.0/build$ sudo locale-gen
Generating locales (this might take a while)...
  en_US.UTF-8... done
  en_US.UTF-8... done
  en_US.ISO-8859-1... done
Generation complete.
nominatim@dap-jupyter01:~/Nominatim-3.2.0/build$ ./utils/setup.php --osm-file ../data/antartica-latest.osm --all --osm2pgsql-cache 28000 2>&1 | tee setup.log
2019-01-23 23:49:47 == module path: /srv/nominatim/Nominatim-3.2.0/build/module
2019-01-23 23:49:47 == Create DB
createdb: database creation failed: ERROR:  encoding "UTF8" does not match locale "en_US"
DETAIL:  The chosen LC_CTYPE setting requires encoding "LATIN1".
ERROR: Error executing external command: createdb -E UTF-8 -p 5432 nominatim
Error executing external command: createdb -E UTF-8 -p 5432 nominatim
nominatim@dap-jupyter01:~/Nominatim-3.2.0/build$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

**Comment by jeremy-rutman** [comment]
this fix [here](https://stackoverflow.com/questions/13115692/encoding-utf8-does-not-match-locale-en-us-the-chosen-lc-ctype-setting-requires)  finally did it...sheesh
