### ISSUE TITLE
How to tune the performance of Nominatim Reverse Geocoding Application

### ISSUE THREAD

**Issue by LawrenceWlt** [openstreetmap/Nominatim#1290]
We are trying to figure out why a reverse geocode is taking approx 500ms 

I've tried to look at each segment to figure out where the bottle neck is
This is what I've found:

Running the query directly to the Postgresql takes 3-8ms. 
(The Postgresql can handle 500 concurrent connections) 

The Apache server is running on 8 core cpus. 
Analyzing the Apache access logs: it can only handle betwee 14-21 request served per sec. (we are pushing a lot more at it but its only serving this amount per sec, and is often taking 3.5 sec per request when sending 20 requests a sec, If I just send 1 request a sec its approx 500ms)

Requesting via the browser, and using chrome dev tool bar,  it takes about 300ms on the "TTFB waiting time"
its only a 1ms initial connection (Ping), and It only takes 3ms for content download.

It appears the bottle neck seems to be on the nominatium/Apache section
I would really want to know the time spent to convert the request to a query and also the time taken to process the data from the PSQL to the response, if anyone knows how I could log this data somewhere that would help pin point further.
What should I do reduce to the waiting time (TTFB)?

Has anyone else come accross this issue, or help me speed up the process
If you need any more info please ask

Below is a Nominatim response time on Google chrome. Their TTFB is only 204ms.

URL: https://nominatim.openstreetmap.org/reverse.php?format=json&lat=-1.40400838851929&lon=35.1109580993652&zoom=18&extratags=1&addressdetails=1%22

![pasted_image_at_2019-01-25__3_10_pm](https://user-images.githubusercontent.com/45232860/51749154-afb18580-20bf-11e9-8288-d06083f1219f.png)

**Comment by mtmail** [comment]
It's hard to compare do to different hardware, result caching (including memcached) and how "warm" the database is due to similar recent queries or what parts of tables are already in operating system cache.

nominatim.osm.org uses Apache2 plus php-fpm to speed up the PHP stack. https://en.wikipedia.org/wiki/List_of_PHP_accelerators  If you want to try nginx instead of Apache see https://github.com/openstreetmap/Nominatim/blob/master/vagrant/Install-on-Ubuntu-18-nginx.sh

**Comment by lonvia** [comment]
> Running the query directly to the Postgresql takes 3-8ms.
> (The Postgresql can handle 500 concurrent connections)

Are you sure about these numbers? There are always multiple queries involved in reverse request. On the 12-core machine used for nominatim.openstreetmap.org average time for processing a reverse request is 40ms. And this is only if the number of parallel connections to postgres is below around 15. More and it raises to 60-100ms. Also, these numbers are only true for the latests Nominatim release. Before it was around 100ms for the best case. If you have file or database logging enabled, you'll find that the time it actually takes to process the requests (executing all of the website/reverse.php script) is logged there. (And if you are looking for speed, you rather want file logging than database logging.)

**Comment by quade1664** [comment]
Thanks Everyone, some very useful info here

> > Running the query directly to the Postgresql takes 3-8ms.
> > (The Postgresql can handle 500 concurrent connections)
> 
> Are you sure about these numbers? 
I think this is just config stuff, not real world testing


>On the 12-core machine used for nominatim.openstreetmap.org average time for processing a reverse request is 40ms. And this is only if the number of parallel connections to postgres is below around 15. More and it raises to 60-100ms. 

If you look at the test above using https://nominatim.openstreetmap.org/reverse.php?format=json&lat=-1.40400838851929&lon=35.1109580993652&zoom=18&extratags=1&addressdetails=1%22
The results (in green on the image) say 204ms
When you say 40ms or 60-100ms is this a direct query using PSQL or using dev tools in chrome as I have highlighted?

>Also, these numbers are only true for the latests Nominatim release. Before it was around 100ms for the best case. 
Our version is approx 6 months old, would this be an old version?

>If you have file or database logging enabled, you'll find that the time it actually takes to process the requests (executing all of the website/reverse.php script) is logged there. (And if you are looking for speed, you rather want file logging than database logging.)
That would be very helpful where do I turn this one and look for the results

What we are looking for is to speed these up a lot
Unfortunately the machine requesting the data is not on a LAN with the Nominatim server, but they are in the same data centre, and the ping time on a 200kb packet is 1ms.
But we are still seeing slow times from start to end
You mention 40ms as a best case, I assume we need 12 cores and fast CPU's to get this result?
This is really helpful for a target, and i'll use chrome dev tools (the green bar) for testing this target

**Comment by lonvia** [comment]
> When you say 40ms or 60-100ms is this a direct query using PSQL or using dev tools in chrome as I have highlighted?

They are the numbers from the mentioned munin plugin. Whatever you read in chrome in the end depends on your web server setup, network connection etc. That's a system administrations problem and has little to do with Nominatim itself.

> Our version is approx 6 months old, would this be an "old version"?

The latest release is 3.2.0.

> That would be very helpful where do I turn this one and look for the results

http://munin-monitoring.org/

> You mention 40ms as a best case, I assume we need 12 cores and fast CPU's to get this result?
> Its currently a 32Gb Ram, 8 Core Cpu, SSD VM on Digital Ocean

This is surely not a machine that is able to handle high load. I doubt that you get anything better than the 500ms you see now. If you need really high throughput with a planet-wide installation, you'll want 96+ GB RAM, 12 cores (i.e. 24 hyperthreads) CPU, SSD (preferably NVMe) and all on bare metal.

Closing here as this is more of a system administrations discussion. Please use the [geocoding mailing list](https://lists.openstreetmap.org/listinfo/geocoding) for this kind of discussion.

**Comment by quade1664** [comment]
Thank you !
