### ISSUE TITLE
nominatim : Database Size is too large

### ISSUE THREAD

**Issue by parsispresswala** [openstreetmap/Nominatim#1292]
I have updated some countries in nominatim databse but it is taking much space. I have read that database takes physical storage before creating other tables. Should I delete below mentioned tables from nominatim once geocoding starts working.
- Planet_osm_nodes
- Planet_osm_ways
- Planet_osm_rels
Does this affect geocoding process.

**Comment by lonvia** [comment]
You  can run `./utils/setup --drop` after the import is finished. The resulting database can be used for querying but is not updatable anymore (including adding more countries).

**Comment by parsispresswala** [comment]
@lonvia Should I take dump of tables? Whenever I need to update I can use those tables. Is it feasible solution? And  if i don't drop table how much HDD I need to update world.

**Comment by mtmail** [comment]
You said you don't have enough disk space. I don't see how dumping tables and later restoring the same tables helps with disk space.

The whole world needs about 700GB currently. After you run `./utils/setup --drop` it might go down by 200GB.

**Comment by parsispresswala** [comment]
@mtmail Yes you are right. I was being silly. If it takes 700 GB, I can arrange.
