### ISSUE TITLE
Updation failed with HTTP 404 Error

### ISSUE THREAD

**Issue by kaustubhlohiya** [openstreetmap/Nominatim#1306]
I recently installed Nominatim and everything is fine but when i run the update it gives the following error

 ./utils/update.php --init-updates
```
WARNING: resetting cache memory to 454
2019-02-12 05:29:39 == WARNING: resetting threads to 1
2019-02-12 05:29:39 == module path: /srv/nominatim/Nominatim-3.2.0/build/module
2019-02-12 05:29:39 == Create Functions
Summary of warnings:

  * resetting threads to 1

2019-02-12 05:29:40 == Setup finished.
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
Done. Database updates will start at sequence 2153 (2019-02-10T18:00:55Z)
```

The following is my local.php file

```
<?php
@define('CONST_Website_BaseURL', '/nominatim/');
@define('CONST_Pyosmium_Binary', '/srv/nominatim/.local/bin/pyosmium-get-changes');
// base URL of the replication service
@define('CONST_Replication_Url', 'https://download.geofabrik.de/asia/india-updates/');
// How often upstream publishes diffs
@define('CONST_Replication_Update_Interval', '86400');
// How long to sleep if no update found yet
@define('CONST_Replication_Recheck_Interval', '900');
```

Any help will be appreciated. Thanks

**Comment by lonvia** [comment]
These 404 messages can be safely ignored. It is bogus (and needs to be fixed in pyosmium). The initialization of the update process went well.

**Comment by kaustubhlohiya** [comment]
Thanks for the prompt reply. Just one more doubt because when I check for update, it gives the following that new update is available.

./utils/update.php --check-for-updates

```
WARNING: resetting cache memory to 415
New data available (2153 => 2154).

```

However the data is not getting updated.

**Comment by lonvia** [comment]
What command did you run to actually update the data? --check-for-updates only looks if new data is available.

**Comment by kaustubhlohiya** [comment]
I ran ./utils/update.php --init-updates

For which i am getting those 404 message

**Comment by MoustafaMahgoub** [comment]
hello did you manage to solve the issue

**Comment by kaustubhlohiya** [comment]
Yes, it was merely memory issue.

**Comment by MoustafaMahgoub** [comment]
THanks for replying
i have 12847 available memory, did you change something in the code files to use them all or what!
