### ISSUE TITLE
Updates with https behind proxy

### ISSUE THREAD

**Issue by knowname** [openstreetmap/Nominatim#1309]
I have a Nominatim installation behind a proxy.
This is working fine until i want to start the updates and run `./utils/update.php --init-updates` with a replication URL which is HTTPS (https://download.geofabrik.de/europe/dach-updates) and not HTTP (http://download.geofabrik.de/europe/dach-updates).

```
nominatim@server:~/Nominatim/build$ ./utils/update.php --init-updates
2019-02-19 13:14:25 == module path: /srv/nominatim/Nominatim/build/module
2019-02-19 13:14:25 == Create Functions
Summary of warnings:

2019-02-19 13:14:25 == Setup finished.
PHP Warning:  file_get_contents(): Peer certificate CN=`www.openstreetmap.org' did not match expected CN=`download.geofabrik.de' in /srv/nominatim/Nominatim/lib/lib.php on line 41
PHP Warning:  file_get_contents(https://www.openstreetmap.org/api/0.6/node/6277323832/1): failed to open stream: Cannot connect to HTTPS server through proxy in /srv/nominatim/Nominatim/lib/lib.php on line 41
ERROR: Cannot determine date of database.
Cannot determine date of database.
```

I have the suspicion that https://bugs.php.net/bug.php?id=76196 could be causing the problem.
As a workaround i installed `php-curl` and replaced https://github.com/openstreetmap/Nominatim/blob/af97682cca17e9e3e5e9c986d14b091506866f93/utils/update.php#L84 with
```
    $ch =  curl_init(CONST_Replication_Url.'/state.txt');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    $sBaseState = curl_exec($ch);
    curl_close($ch);
```
---
Operating system: Ubuntu 18.04 as Docker Container
Nominatim version: v3.2.0
hardware configuration: sufficient

**Comment by lonvia** [comment]
I'm not sure if we should work around this on our side or not.

**Comment by knowname** [comment]
Your call. 
Since this is an edge case and the bug seems to be on the PHP-side it might not be necessary changing anything on yours - i can live with that. On the other hand it wouldn't hurt much.

**Comment by Vrumfondel** [comment]
I would say this is not nominatim specific. The intermediate certificate of the proxy needs to be added to the php certificate store, then it works. Had the same issue here in our environment ....

**Comment by lonvia** [comment]
Alright, closing this as a PHP issue.
