### ISSUE TITLE
boundingbox parameter is missing from details endpoint

### ISSUE THREAD

**Issue by csimpi** [openstreetmap/Nominatim#1310]
Unfortunately there are many differences between `search.php`'s and `reverse.php`'s endpoint I have to use the details page to get the same response format, but some reason the `boundingbox` parameter is missing from the details page. 

I think the best way would be to make the `search.php`'s and `reverse.php`'s response format same (for example icon is missing from reverse's endpoint) it would save some resources and would solve all of the problems.

**Comment by lonvia** [comment]
Please read https://operations.osmfoundation.org/policies/nominatim/, in particular the section about using the details page for debugging only. The details endpoint is not open for feature requests, sorry.

**Comment by csimpi** [comment]
@lonvia 
Thank you for your answer, let me clarify my question a little bit:
1. Yes, I've read that I know about that, but still, the bounding box is missing and would be necessary even for debugging only (especially for debugging).
2. I understand that the details endpoint is not open for feature requests though, that's why I proposed a solution that would not affect the details endpoint, with that flow you could even save some resources also. Should I open a task (with a better title) for that? If you are open for fine-tuning the search and reverse responses I can work on it and send a PR.
3. As the Nominatim Wiki says I may install a standalone version to my server then I can use the details.php as much as I want to, so (I think) you shouldn't completely close the development of the details.php endpoint. 

Thank you for this awesome open-source project, I'll try to contribute as much as I can :)
