### ISSUE TITLE
search with viewbox bounded only

### ISSUE THREAD

**Issue by Arnaud49** [openstreetmap/Nominatim#1311]
Hello !

I can't figure how to do a search only on a bounded viewbox ? without any query ?
I want all establishment in this area.

How can I do ?

https://nominatim.openstreetmap.org/search?format=json&limit=20&viewbox=2.393867340087891,48.84358571785511,2.3904705047607426,48.84472294197522&bounded=1&q=

I know there is something :
https://nominatim.openstreetmap.org/search?format=json&limit=20&viewbox=2.393867340087891,48.84358571785511,2.3904705047607426,48.84472294197522&bounded=1&q=[restaurant]

**Comment by mtmail** [comment]
>  I want all establishment in this area.

Nominatim requires a query (place name or address).

You can use https://wiki.openstreetmap.org/wiki/Overpass_API for a list of all map features in an area. Though even there you probably want to filter a bit, otherwise you end up with every tree, lamp post and traffic light.

**Comment by Arnaud49** [comment]
Thank you but i'm using my own nominatim database. How can I filter to retrieve only place, establishment, etc ... ? I don't want the tree or anything useless for me :p

**Comment by Arnaud49** [comment]
I can retrieve results if I specified amenity=restaurant for exemple :
https://nominatim.openstreetmap.org/search?format=json&limit=20&viewbox=2.3295736312866215,48.87467945221622,2.368454933166504,48.8547480868576&bounded=1&amenity=restaurant

but I want all amenity, and I can't do amenity=all

**Comment by lonvia** [comment]
As @mtmail said, you are using the wrong tool. Nominatim is not designed for this kind of job. It is a search engine. Overpass is what you are looking for.
