### ISSUE TITLE
Query Issue with Austin, MN vs Austin, Minnesota

### ISSUE THREAD

**Issue by RedBaron2** [openstreetmap/Nominatim#1312]
I will add one more to the list of issues.
Query for [Austin, MN](https://nominatim.openstreetmap.org/search?q=Austin,%20MN&countrycodes=US&format=xml&addressdetails=1&limit=1)
This returns
`<city>Austin</city>`
`<county>Travis County</county>`
`<state>Texas</state>`
`<country>USA</country>`
`<country_code>us</country_code>`
You change the Query
[Austin, Minnesota](https://nominatim.openstreetmap.org/search?q=Austin,%20Minnesota&countrycodes=US&format=xml&addressdetails=1&limit=1)
`<city>Austin</city>`
`<county>Mower County</county>`
`<state>Minnesota</state>`
`<country>USA</country>`
`<country_code>us</country_code>`
I had thought that it was a coding issue on my end, but after plugging in the city, state directly. The same buggy return is presented.
My guess is that the query is not passing a secondary check to verify the State Abbreviation, and instead is going on the most popular search for that City.

**Comment by mtmail** [comment]
Which opens the further (data) question why the city (admin_level=8) exists twice: https://www.openstreetmap.org/relation/137800 https://www.openstreetmap.org/way/34444256

I can rule out postal code issues here. It seems Austin, Texas gets a higher importance score than Austin, Minnesota by text match and moves to position 1 (Austin, Minnesota is position 2). Both have wikipedia tags set already.

**Comment by RedBaron2** [comment]
The main question is still that the City is given more importance than the State. It shouldn't make any difference if the State is spelled out Completely or if the Abbreviation is used.

**Comment by mtmail** [comment]
Understood. I'm just listing some recent data issues to rule those out.

**Comment by lonvia** [comment]
Leave out the limit parameter and just use the first result, that works fine.

Looking into solving that on the API side...
