### ISSUE TITLE
Reverse Geocoding not working Highway entrance/exit

### ISSUE THREAD

**Issue by Vrumfondel** [openstreetmap/Nominatim#1317]
When trying to reverse-geocode an highway.motorway_link the next "other" object is used for reverse geocoding. 
Example:
E8.4390875/N49.9730703333333

**Comment by mtmail** [comment]
I think motorway_link are not imported into the Nominatim database.

Adding more information:

https://nominatim.openstreetmap.org/reverse.php?format=html&lat=49.9730703333333&lon=8.4390875&zoom=18

The `highway=motorway_link` https://www.openstreetmap.org/way/365244832

Small circle: search position, blue circle: result position
![image](https://user-images.githubusercontent.com/3727288/53579049-23402a00-3b79-11e9-83be-6222c975f723.png)

**Comment by Vrumfondel** [comment]
Addition: Same issue for highway=trunk_link

**Comment by lonvia** [comment]
Highway links are only imported into Nominatim when they are named. This is a measure to keep the database size in check for nominatim.openstreetmap.org. You can change the behaviour for your own installation in the latest master version by [modifying the style config](http://nominatim.org/release-docs/develop/admin/Import-and-Update/#filtering-imported-data).

**Comment by Vrumfondel** [comment]
Hi there!
I now tried as recommendes: Latest master of Nominatim.
In addition I changed the import-full.style template to contain what I understood from the docu to include all links, even when unnamed.
But I got still the same, links are not in the DB. 
Any Idea what I'm missing?

`
{
    "keys" : ["highway"],
    "values" : {
        "no" : "skip",
        "turning_circle" : "skip",
        "mini_roundabout" : "skip",
        "noexit" : "skip",
        "crossing" : "skip",
        "traffic_signals" : "main,with_name",
        "service" : "main,with_name",
        "cycleway" : "main,with_name",
        "path" : "main,with_name",
        "footway" : "main,with_name",
        "steps" : "main,with_name",
        "bridleway" : "main,with_name",
        "track" : "main,with_name",
        "byway": "main,with_name",
        "motorway_link" : "main",
        "trunk_link" : "main",
        "primary_link" : "main",
        "secondary_link" : "main",
        "tertiary_link" : "main",
        "" : "main"
    }
},
`
