### ISSUE TITLE
Reverse doesn't return city, state when GB postcode is found

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1319]
As reported in https://help.openstreetmap.org/questions/68204/how-to-get-always-a-city-from-gps-coordinates

For https://nominatim.openstreetmap.org/reverse?format=json&lat=51.6185115&lon=-0.7130883&pretty=1 no suburb, city, state is returned although it's a dense populated location. Place found is https://www.openstreetmap.org/node/5210122817

```
display_name: "HP13 7DT, United Kingdom"
address: {
  postcode: "HP13 7DT"
  country: "United Kingdom"
  country_code: "gb"
}
```

**Comment by lonvia** [comment]
Postcode points shouldn't be returned by reverse (or search, for that matter) at all.
