### ISSUE TITLE
nativecode=ERROR:  relation "place" does not exist

### ISSUE THREAD

**Issue by kimjohans** [openstreetmap/Nominatim#1320]
Hello,

using the setup.php script, i got following error:

```
Reading in file: /home/osrm/osrm-backend/europe-latest.osm.bz2
Using XML parser.
Processing: Node(2233879k 206.2k/s) Way(2800k 0.43k/s) Relation(0 0.00/s)Killed
ERROR: 1
select * from place limit 1 [nativecode=ERROR:  relation "place" does not exist
LINE 1: select * from place limit 1
                      ^]
```

script call as user "nominatim":
`~/Nominatim-3.2.0/build$ ./utils/setup.php --osm-file /home/osrm/osrm-backend/europe-latest.osm.bz2 --all --osm2pgsql-cache 2000 2>&1 | tee setup.log`

used os = ubuntu 18 LTS

complete log from last call:
```
2019-03-03 09:36:30 == module path: /home/nominatim/Nominatim-3.2.0/build/module
2019-03-03 09:36:30 == Create DB
2019-03-03 09:36:31 == Setup DB
Postgres version found: 10.6
Postgis version found: 2.4
 set_config
------------

(1 row)

2019-03-03 09:36:41 == Import data
osm2pgsql version 0.96.0 (64 bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
Mid: loading persistent node cache from /tmp/flatnode.file
Mid: pgsql, cache=2000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/osrm/osrm-backend/europe-latest.osm.bz2
Using XML parser.
Processing: Node(2233730k 209.6k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Killed
ERROR: 1
select * from place limit 1 [nativecode=ERROR:  relation "place" does not exist
LINE 1: select * from place limit 1
                      ^]
```

I looked around and found other answers, which means "missing places is no problem" (f.eg. https://help.openstreetmap.org/questions/34880/notice-table-place-does-not-exist-skipping). With several failed runs like above i cannot sign that statement at all. I have a problem with importing the data and the missing table.

Thanks.

**Comment by mtmail** [comment]
Another user reported the same yesterday https://help.openstreetmap.org/questions/68221/nominatim-setup-with-latest-planet-pbf-always-fails Nominatim executes osm2pgsql in the import step so their issue list seems more relevant.

https://github.com/openstreetmap/osm2pgsql/issues/

I found an older https://github.com/openstreetmap/osm2pgsql/issues/159 and https://github.com/openstreetmap/osm2pgsql/issues/855 reporting similar errors. 

If you open an issue there add how much RAM your machine has. The 2000MB cache size seems low for Europe. I usually use 24000 or 28000 for the whole world. If I remember correctly Europe is about a third of the data size of the world.

**Comment by lonvia** [comment]
There is not much point in opening an issue with osm2pgsql. It runs out of memory and gets OOM killed. This is a configuration problem. Hard to say why exactly without knowing the hardware configuration and postgres setup.

**Comment by ifle** [comment]
I have similar issue with a small file. 
Below small example of osm file
If I change the ID to small number all works as expected
```xml

<?xml version='1.0' encoding='UTF-8'?>
<osm version="0.6">  
  <node id="4397146512140" lat="32.087819012" lon="34.885033122">    
    <tag k="addr:street" v="sdssd" />
    <tag k="addr:city" v="sdss" />
  </node>
</osm>

```

**Comment by lonvia** [comment]
@ifle that's completely unrelated. See https://github.com/openstreetmap/osm2pgsql/issues/290 for your issue.

Closing this issue here as the original poster did not provide any further information.

For anyone stumbloing upon this issue because they see:

```
Killed
ERROR: 1
select * from place limit 1 [nativecode=ERROR:  relation "place" does not exist
LINE 1: select * from place limit 1
```

This is likely a configuration error and not a nominatim bug. Please use the [geocoding mailing list](https://lists.openstreetmap.org/listinfo/geocoding) to ask for help and clarification.
