### ISSUE TITLE
Is there is a way to update the nominatim database from not osm source like json file?

### ISSUE THREAD

**Issue by ifle** [openstreetmap/Nominatim#1322]
Is there is a way to update the nominatim database from data source like json file or another not osm source?
For example likeLike this
`
{
  "Addresses" : [
   "Address" : "bla bla",
   "Lat" : 2232323,
   "Long" : -2232323,
}]
`

**Comment by mtmail** [comment]
There isn't. You'd need to convert your data into *.osm file format.
