### ISSUE TITLE
Can't get a GB postcode to work

### ISSUE THREAD

**Issue by evilexecutable** [openstreetmap/Nominatim#1323]
I have the postcode, which as per the screenshot, has a long and lat associated with it, but still, get no result.

![image](https://user-images.githubusercontent.com/6544968/53802192-1d5f9580-3f39-11e9-922c-ac62192dac2a.png)

**Comment by mtmail** [comment]
Which version of Nominatim have you installed?

Is the screenshot of your system or the nominatim.osm.org one?

Can you post the SQL query?

Does searching for the postcode without space `AB101JH` work? Do searches for other postcodes work?

**Comment by evilexecutable** [comment]
Hi mtmail,

Using the latest build of Nominatim. The screenshot is my system.
No, no other post code, or searching without spaces works.

The SQL query I used to get that list was
`SELECT country_code, postcode, st_x(geometry), st_y(geometry) FROM location_postcode;`

Thanks

**Comment by mtmail** [comment]
Do you see any records unindexed (`select count(*) from placex where indexed_status=1;`)? That would point to the initial setup having not finished. If so you could run http://nominatim.org/release-docs/latest/admin/Faq/#can-a-stoppedkilled-import-process-be-resumed

Does `SELECT word_id, word_token, word, class, type, country_code, operator, coalesce(search_name_count, 0) as count FROM word WHERE word_token in (' ab10 1jh');` show any records?

https://nominatim.openstreetmap.org/search.php?q=AB10+1JH&debug=1 shows tokenization and search candidates. Can you post the output from your machine? I think github support *.html files as attachment.

**Comment by evilexecutable** [comment]
@mtmail 

> select count(*) from placex where indexed_status=1;
I have a count of 5868508.

> SELECT word_id, word_token, word, class, type, country_code, operator, coalesce(search_name_count, 0) as count FROM word WHERE word_token in (' ab10 1jh');
Returns nothing.

I have attached the debug .html file that came from our server.

[nominatim_debug.txt](https://github.com/openstreetmap/Nominatim/files/2931602/nominatim_debug.txt)

**Comment by evilexecutable** [comment]
Thanks, I'll leave this running and get back to you.

**Comment by evilexecutable** [comment]
@mtmail 

Good news. The (lack of) indexing caused the issue. As it turned out, our hypervisor was rebooting every night and we didn't catch on, so the indexing was never completing. Whoopsie!

Thank you for your help.
