### ISSUE TITLE
Nominatim in load-balanced pattern

### ISSUE THREAD

**Issue by MaheshVyomSharma** [openstreetmap/Nominatim#1326]
I was looking to install nominatim as a load-balanced service on premise. I encountered an error during import of data as _nominatim.so_ was inaccessible to the remote server hosting postgres. 

> ERROR: Failed to load nominatim module. Reason:
CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/srv/nominatim/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text); [nativecode=ERROR:  permission denied for language c]

I came across https://github.com/openstreetmap/Nominatim/issues/423 and a post here states that configuring nominatim with remote postgres server is not straight forward. 
Is there anybody who has succeeded in the attempt I am trying to make? 
I am looking to host the entire planet data, eventually.

**Comment by mtmail** [comment]
You need to compile nominatim.so on the database server as well. From the installation instructions that's at least the `cmake` and `make` steps while you can ignore webserver setup or data import.

If you don't have access (filesystem, ssh) to the database server, e.g. a managed service on a cloud provider, then installing nominatim.so won't work.

**Comment by MaheshVyomSharma** [comment]
@mtmail thanks!
