### ISSUE TITLE
Search for "banc à Grenoble" turns to "bank à Grenoble"

### ISSUE THREAD

**Issue by ssandon** [openstreetmap/Nominatim#1327]
Hi,

A search for "banc à Grenoble" turns into "bank à Grenoble" results.
While "bench à Grenoble" works :/

http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/FR

Use both the website https://nominatim.openstreetmap.org or the API via JSON request.

Thank you.

**Comment by mtmail** [comment]
The first result I see is BNP Paribas, so I might have different settings (browser language, viewpost).. Can you post the full URL of the JSON request you tried?

**Comment by ssandon** [comment]
What I mean is banc should be understood as bench not bank.

https://nominatim.openstreetmap.org/search?q=banc%20%C3%A0%20Grenoble&format=jsonv2
returns the same as
https://nominatim.openstreetmap.org/search?q=banque%20%C3%A0%20Grenoble&format=jsonv2

it should not.

**Comment by ssandon** [comment]
https://nominatim.openstreetmap.org/search?q=bench%20%C3%A0%20Grenoble&format=jsonv2
is the correct answer. but bench is an english word for banc.

**Comment by mtmail** [comment]
As a work around use https://nominatim.openstreetmap.org/search?q=[amenity=bench]%20Grenoble&format=jsonv2

**Comment by lonvia** [comment]
This really isn't fixable as long as we support multi-lingual terms. There are simply languages where 'banc' means 'bank'.
