### ISSUE TITLE
What is wrong with this custom osm file?

### ISSUE THREAD

**Issue by ifle** [openstreetmap/Nominatim#1329]
What is wrong with this custom osm file? I created it and able to load it but search return no result

```xml

<osm version="0.6" timestamp="2019-03-11T10:54:30Z">  
  <node id="4397146717069" lat="32.707009302" lon="35.299710997" timestamp="2019-03-11T10:54:34Z" version="1" changeset="1" />
  <node id="4397146717070" lat="32.706872388" lon="35.299398996" timestamp="2019-03-11T10:54:34Z" version="1" changeset="1" />  
  
  <way id="4397146848352" timestamp="2019-03-11T10:54:38Z" version="1" changeset="1">
    <nd ref="4397146717069" />
    <nd ref="4397146717070" />
    <tag k="addr:city" v="City1" />
    <tag k="addr:street" v="Street1" />
    <tag k="addr:interpolation" v="even" />
    <tag k="addr:housenumber" v="28-36" />
  </way>
  <way id="4397146848351" timestamp="2019-03-11T10:54:38Z" version="1" changeset="1">
    <nd ref="4397146717069" />
    <nd ref="4397146717070" />
    <tag k="addr:city" v="City1" />
    <tag k="addr:street" v="Street1" />
    <tag k="addr:interpolation" v="odd" />
    <tag k="addr:housenumber" v="29-33" />
  </way>
</osm>  

```

**Comment by mtmail** [comment]
I think the house numbers belong on the nodes, like https://www.openstreetmap.org/way/202495466 and would probably require 4 nodes to keep them separate.

After installing Nominatim, did you import only this file? Or start with another file, e.g. a country, and loaded this additionally? How many places do you see in the `placex` table?

To be honest I'd need to run the import myself to check what the database contains. I does sound like https://github.com/openstreetmap/Nominatim/issues/148 a limitation of Nominatim where `addr:city` get ignored making streets without an administrative boundary (city) or place (https://wiki.openstreetmap.org/wiki/Key:place) nearby unfindable.

For testing try to create a rectangular city as well, just 4 nodes.

**Comment by ifle** [comment]
Thanks for your answer. 
Do you mean that I need to use nodes for house interpolation. 
Start house number will be first ref of the nd tag and end house will be end ref. 
How to deal with situations when 1 node may contains more then one house number, like in my example.
I have DB of house numbers as interpretation and need to import them to nominatem and photon
Thanks

```xml

<osm version="0.6" timestamp="2019-03-11T10:54:30Z">  
  <node id="4397146717069" lat="32.707009302" lon="35.299710997" timestamp="2019-03-11T10:54:34Z" version="1" changeset="1" >
    <tag k="addr:housenumber" v="28" />
    <tag k="addr:city" v="City1" />
    <tag k="addr:street" v="Street1" />
  </node>
  <node id="4397146717070" lat="32.706872388" lon="35.299398996" timestamp="2019-03-11T10:54:34Z" version="1" changeset="1" />  
    <tag k="addr:housenumber" v="36" />
    <tag k="addr:city" v="City1" />
    <tag k="addr:street" v="Street1" />
  </node>
  
  <node id="4397146717069" lat="32.707009302" lon="35.299710997" timestamp="2019-03-11T10:54:34Z" version="1" changeset="1" >
    <tag k="addr:housenumber" v="29" />
    <tag k="addr:city" v="City1" />
    <tag k="addr:street" v="Street1" />
  </node>
  <node id="4397146717070" lat="32.706872388" lon="35.299398996" timestamp="2019-03-11T10:54:34Z" version="1" changeset="1" />  
    <tag k="addr:housenumber" v="33" />
    <tag k="addr:city" v="City1" />
    <tag k="addr:street" v="Street1" />
  </node>
  
  <way id="4397146848352" timestamp="2019-03-11T10:54:38Z" version="1" changeset="1">
    <nd ref="4397146717069" />
    <nd ref="4397146717070" />    
    <tag k="addr:interpolation" v="even" />    
  </way>
  
  <way id="4397146848351" timestamp="2019-03-11T10:54:38Z" version="1" changeset="1">
    <nd ref="4397146717069" />
    <nd ref="4397146717070" />    
    <tag k="addr:interpolation" v="odd" />    
  </way>
</osm>  

```

**Comment by lonvia** [comment]
If that is the only data you are trying to import then this won't work. Nominatim has been developed specifically for processing OSM data. It needs house number nodes, street geometries and administration polygons and then processes from searchable addresses from them . addr:* tags are largely ignored.

Please be aware that adding custom data to Nominatim is not something that is currently officially supported by the software. It is possible but requires a lot of fiddling and reading through the code to understand the internal data structures and possibly even changing some things internally. You are welcome to try and ask specific questions about internals on the [geocoding mailinglist](https://lists.openstreetmap.org/listinfo/geocoding) when you get stuck but it's not a topic for this issue tracker. Sorry.
