### ISSUE TITLE
Search for "Johannes-Schlaf-Str. 99425 Weimar" returns wrong ZIP Code

### ISSUE THREAD

**Issue by christian2701** [openstreetmap/Nominatim#1330]
Hi,

a search for "Johannes-Schlaf-Str. 99425 Weimar" returns the wrong ZIP Code 99423:

https://nominatim.openstreetmap.org/search.php?q=Johannes-Schlaf-Str.+99425+Weimar&polygon_geojson=1&viewbox=

In my opinion the data in OpenStreetMap is correct and Nominatim also finds the ZIP Code 99425 in the Debug mode:

https://nominatim.openstreetmap.org/search.php?q=Johannes-Schlaf-Str.+99425+Weimar&polygon_geojson=1&debug=1

Thank you!

**Comment by mtmail** [comment]
Thanks a lot.

Looks like two postcodes are added to the address hierarchy (the table) on https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=25912386&class=highway

99423 is calculated nightly. It's a center point of all postcodes with that value. 99425 is a relation with proper boundaries. The relation should be chosen.
