### ISSUE TITLE
Call to undefined method PDOException::message

### ISSUE THREAD

**Issue by geoneutrino** [openstreetmap/Nominatim#1332]
i got this error due to a db access problem
thrown in lib/DB.php line 61
$sErrMessage = $e->message();

i assume this should be
$sErrMessage = $e->getMessage();
then it works

**Comment by mtmail** [comment]
Thanks a lot. That looks like a debugging left-over from a couple of days ago. Fix in https://github.com/openstreetmap/Nominatim/pull/1334
