### ISSUE TITLE
Error with table 'place': Import failing for US data (.pbf) format

### ISSUE THREAD

**Issue by MaheshVyomSharma** [openstreetmap/Nominatim#1338]
Hello,

I have a CentOS 7.x VM with 4 CPUs, 16G RAM running Postgres 9.2.
My goal is to **import all of US data** using Nominatim, but encountering the classic issue with the table 'place'.
The approach I took is this:

- downloaded the data for each zone of US individually from geofabrik.de

- merged them all using the [parallel processing](https://wiki.openstreetmap.org/wiki/Osmconvert#Parallel_Processing) and generated the file _us-ne-so-mw-we-pa.osm.pbf_

- gave this command to start importing the data from my Nominatim build directory
**./utils/setup.php --osm-file ~/data/us-ne-so-mw-we-pa.osm.pbf --all --osm2pgsql-cache 9000 2>&1 | tee us-all.log**

Even though I gave about 9G as osm2pgsql cache, it failed with 
_

> select * from place limit 1 [nativecode=ERROR:  relation "place" does not exist
> LINE 1: select * from place limit 1
>                       ^]

_

At any time I assumed the free memory available was 12G (in reality, there was about 1G+ more always). 
Any zone's data, individually, would get processed easily. 
Am I doing anything wrong here? Should I be using a server with a bigger configuration?

**Comment by mtmail** [comment]
The `select * from place limit 1 ` is run after the osm2pgsql process. Is there any previous output? Any errors in the postgresql log file?

If osm2pgsql crashes in the middle, e.g. after already imported million of places, then it's most likely memory or lost postgresql connection (database server crashed, hardware issue, timeout if it's on a remote server). If it stops before importing anything then it might be the database connection or *.pbf file.

Are you using the flatnode file setting? http://nominatim.org/release-docs/latest/admin/Import-and-Update/#flatnode-files It's optional but saves disc space.

**Comment by lonvia** [comment]
As per #1320: use the geocoding mailinglist to inquire about your setup.
