### ISSUE TITLE
How to make small import?

### ISSUE THREAD

**Issue by danilkinanton** [openstreetmap/Nominatim#1339]
Please help!
How to make such import?
I need only state, region, province, district, county, municipality, city , town.

**Comment by mtmail** [comment]
In the current stable version of Nominatim (version 3.2) it requires editing code. `osm2pgsql` (https://github.com/openstreetmap/osm2pgsql) is used to import and update data. The transformation and filtering happens in a plugin `output-gazetteer`. The logic (and name https://en.wikipedia.org/wiki/Gazetteer) goes back years. Basically in your local https://github.com/openstreetmap/osm2pgsql/blob/5482234a7a326530a6b0af85f9e82c454df8e879/output-gazetteer.cpp you need to remove those lines mentioning `highway`, `railway`, `aerialway`, `waterway`, `postcode`, `shop` and many more. I take back the "basically", I know it's a tedious process.

In the master version of Nominatim (to be released) this process is easier. https://nominatim.org/release-docs/develop/develop/Import/  The default style imported is `import-street.style`. https://github.com/openstreetmap/Nominatim/tree/master/settings/ In you local `build/settings/local.php` add a line to overwrite `CONST_Import_Style` value (default is in `settings/default.php`). 
Sounds like the `import-admin.style` will do.
