### ISSUE TITLE
Reverse Geocoding not working Highway entrance/exit 

### ISSUE THREAD

**Issue by Vrumfondel** [openstreetmap/Nominatim#1340]
This is a follow-up to Issue #1317 (seems I can't re-open it).

I now tried as recommendes: using latest master of Nominatim.
In addition I changed the import-full.style template to contain what I understood from the docu to include all links, even when unnamed.
But I got still the same, links are not in the DB.
Any Idea what I'm missing?

{ "keys" : ["highway"], "values" : { "no" : "skip", "turning_circle" : "skip", "mini_roundabout" : "skip", "noexit" : "skip", "crossing" : "skip", "traffic_signals" : "main,with_name", "service" : "main,with_name", "cycleway" : "main,with_name", "path" : "main,with_name", "footway" : "main,with_name", "steps" : "main,with_name", "bridleway" : "main,with_name", "track" : "main,with_name", "byway": "main,with_name", "motorway_link" : "main", "trunk_link" : "main", "primary_link" : "main", "secondary_link" : "main", "tertiary_link" : "main", "" : "main" } },

**Comment by mtmail** [comment]
Reformatted for readability:

```javascript
{
    "keys" : ["highway"],
    "values" : {
        "no" : "skip",
        "turning_circle" : "skip",
        "mini_roundabout" : "skip",
        "noexit" : "skip",
        "crossing" : "skip",
        "traffic_signals" : "main,with_name",
        "service" : "main,with_name",
        "cycleway" : "main,with_name",
        "path" : "main,with_name",
        "footway" : "main,with_name",
        "steps" : "main,with_name",
        "bridleway" : "main,with_name",
        "track" : "main,with_name",
        "byway": "main,with_name",
        "motorway_link" : "main",
        "trunk_link" : "main",
        "primary_link" : "main",
        "secondary_link" : "main",
        "tertiary_link" : "main",
        "" : "main"
    }
}
```

**Comment by Vrumfondel** [comment]
Maybe that helps debugging:
I manually checked my nominatim database: The example object for motorway_link (116004600) is in fact contained in my database in table "place". 
Nevertheless it is not considered when reverse geocoding.

**Comment by mtmail** [comment]
I setup a Nominatim instance for the region around Rüsselsheim (http://bboxfinder.com/#49.887114,8.136063,50.106928,8.623581) on http://116.203.149.43/nominatim/

Before import I modified the `settings/import-full.style` and overwrote `highway` section to the one listed above (copy&paste). The motorway is imported http://116.203.149.43/nominatim/details.php?osmtype=W&osmid=4007031&class=highway

When clicking on the motorway link way I can't see any jumps to nearby tracks.
http://116.203.149.43/nominatim/reverse.php?format=html&lat=49.974612235329964&lon=8.461595668442367&zoom=18

![image](https://user-images.githubusercontent.com/3727288/55341395-d8cb0980-54a6-11e9-9108-9b37be68dff1.png)

But when setting `zoom=16` there are jumps. I can understand if you want to set zoom=16 to exclude house number and POIs. Is that the case?

By default motorway links have an address rank of 27 (grayed out number in the table on http://116.203.149.43/nominatim/details.php?osmtype=W&osmid=4007031&class=highway), while motorways and other roads have 26. You can change the default in https://github.com/openstreetmap/Nominatim/blob/master/settings/address-levels.json It needs a re-import of the data.

**Comment by Vrumfondel** [comment]
Thanks for the explanation regarding address-ranks, but this is not the issue I see.

I'm now really confused:
using the exact same request on my nomination installation gives me a different result....
![nomin_new](https://user-images.githubusercontent.com/6260974/55381155-d782f680-5511-11e9-9149-9f6d65b4105e.jpg)

**Comment by mtmail** [comment]
> Is this rank 26 vs 27 ?

I change my local `settings/address-levels.json` so `motorway_link` is 27, then reimported (with my smaller bounding box a reimport took just 5 minutes). That certainly affects importance.

You could try adding &debug=1 to the URLs and see if the generated SQL is different.

**Comment by Vrumfondel** [comment]
I did some testing aswell,

but somehow the results are still not conclusive to me:

I changed the level for links to 26.
In zoom-level 16,17,18 the behavior is as expected - the Link is reversecoded correctly

For lower levels other objects with higher rank are chosen (I would consider this as expected behaviour).

But for higher zoomlevel, again the lake next to the road is responded.

Is this expected behaviour?

You can access my installation here:
[http://95.216.174.85/nominatim/reverse.php?format=html&lat=49.974586849044705&lon=8.461698782114887&zoom=19](url)

**Comment by yterletskyi** [comment]
@mtmail sorry for off-topic, could you please show how have you made the Nominatim take your `settings/import-full.style` file and reimport the database?
I'm struggling with exactly the same issue - I need to import unnamed roads.

**Comment by mtmail** [comment]
@Vrumfondel The `place_id` are created sequentially during an import. They are different between servers, often even different when you reimport on the same server. Difference here are expected.

On http://95.216.174.85/nominatim/details.php?osmtype=W&osmid=4007031&class=highway I don't see the address_rank=27 yet for the highway:motorway_link (first row in the table, way 4007031). Maybe there was a misunderstanding. You wrote "I changed the level for links to 26." but I wrote " change my local settings/address-levels.json so motorway_link is 27" earlier.

**Comment by mtmail** [comment]
@yterletskyi In your `settings/defaults.php` you will find a line
```php
@define('CONST_Import_Style', CONST_BasePath.'/settings/import-full.style');
```
Add such a line in your `build/settings/local.php` pointing to your new file. (note the difference between the base path, e.g. /some_path/Nominatim, and the build path, e.g. /some_path/Nominatim/build).
Delete the existing database using `dropdb <database_name>` (usually the name is nominatim), then follow the import instruction on http://nominatim.org/release-docs/3.2.0/admin/Import-and-Update/ like you did in the first import.
Happy to answer follow-up questions, but please open a new issue on https://github.com/openstreetmap/Nominatim/issues to keep the discussions separate.

**Comment by lonvia** [comment]
Solved in a9ae2c74571a56dc5b89a8a8ac1acc91b3f1e285. Please use `zoom=17` with your reverse query to also get the minor streets like links and you still need a custom import style.

**Comment by ngmip** [comment]
I think I have the same issue even with the fix applied.
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=-22.25071074316151&lon=166.4499145746231&zoom=17
The entrance of the highway is, for some reason ignored :-( and another unwanted road is picked.

**Comment by mtmail** [comment]
@ngmip This issue got closed a year ago. You can open a new issue with screenshots. Links to nominatim.openstreetmap.org are helpful but they don't show what you see on your installation. Also post the changes you made to your .style file.
