### ISSUE TITLE
Nominatim and Postgres in two different Docker container

### ISSUE THREAD

**Issue by phlegx** [openstreetmap/Nominatim#1341]
Docker best practice is that every process run in its own container. So it would be really nice if we could have a standalone Nominatim and Postgres Container.

However atm. we have the situation that not only the  Web server needs `nominatim.so` for string normalization during import, but also the Database server needs `nominatim.so` for string normalization during querying. 

So we cannot really split it without having nominatim.so (and maybe other files) on the Postgres container.

Maybe there is a possibility to make Nominatim and Postgres independent of each other?

**Comment by mtmail** [comment]
Did you find a work-around? I know the https://github.com/mediagis/nominatim-docker project doesn't address this yet. To my best knowledge users copy the `nominatim.so` file to the database server as part of the installation. https://docs.docker.com/develop/develop-images/multistage-build/ and it's `COPY` might be a way to automate it.

Nominatim calling methods from a .so file in PG/PSQL won't change. The benefits (speed during import and speed of querying) outweighs any installation steps one might need to add. We can document such a step, but rather avoid being too specific to deployment frameworks (docker, ansible, puppet, etc).

We want to rewrite the logic within the .so file (https://github.com/openstreetmap/Nominatim/labels/Transliteration). It will probably be based on other libraries (e.g http://site.icu-project.org/) making it even harder to offer an database function type replacement.

**Comment by phlegx** [comment]
Hi @mtmail! For now I just use the postgres Debian/Ubunut Docker image and just build Nominatim as well in that image. That way I have all files I need  (Wasn't sure previously if we need more files then just the `nominatim.so` )also in the Postgres image. 

Your solution with multistage build sounds also nice. Will have a look at this.

Maybe this `nominatim.so` module can be handled similar as the `Postgis` module for `PostgreSQL`? If one needs `Postgis` for `PostgreSQL`   one needs to addionally install it in Postgres as you surely know. See here under section `Additional Extensions` https://hub.docker.com/_/postgres

**Comment by lonvia** [comment]
`nomintatim.so is only required in the container where the database runs. You need to copy it over before starting the import.
