### ISSUE TITLE
Reverse geocoding by (lat, lon) is not precise

### ISSUE THREAD

**Issue by yterletskyi** [openstreetmap/Nominatim#1350]
Hi,
I faced that Nominatim reverse geocoding by coordinates (lat, lon) is not as precise as it is by `osm_id`. For example:
Nominatim reverse geocoding by coordinates (50.74624, 25.27389) returns next:
(http://nominatim.uaroads.com/nominatim/reverse?format=jsonv2&zoom=16&lat=50.74624&lon=25.27389)
```
"osm_type": "way",
"osm_id": 160657863,
"category": "highway", 
"type": "primary",
```
which is wrong.

Overpass API for the same address returns:
(https://overpass-turbo.eu/s/HN2)
```
"type": "way",
"id": 126761805,
"highway": "service",
```
which is correct.

Nominatim reverse geocoding by osm_id:
(http://nominatim.uaroads.com/nominatim/reverse?osm_id=126761805&osm_type=W&format=jsonv2&zoom=16)
```
"osm_type": "way",
"osm_id": 126761805,
"category": "highway",
"type": "service",
```
which is correct too.

So Nominatim is mathcing the point to a nearest big road, that is not true.
Alos, note that I'm using custom `*.style` profile for Nominatim while importing to include roads without names, because Way 126761805 is exactly the case.

Is it expected behavior for Nominatim reverse geocoding because Nominatim wiki says
`osm_id=<value> Please use this in preference to lat/lon where possible` ?
Or there is a mistake in my steps?

**Comment by lonvia** [comment]
Please post the custom style you are using. Also, the server is no longer reachable.

**Comment by yterletskyi** [comment]
@lonvia 
custom style: https://gist.github.com/yterletskyi/6f1438f1698d9a448e2daea5475002d4
The server is not reachable anymore and unfortunately cannot fix it now, sorry for that.
If the info I provided is not sufficient i'll try to recover the server.

**Comment by lonvia** [comment]
So there is still an issue with lookup for minor streets likely somewhere [here](https://github.com/openstreetmap/Nominatim/blob/master/lib/ReverseGeocode.php#L250) in the code. If I remember correctly, it worked okay, when you chose zoom level 20 (which shouldn't actually do something at all, but that's a different issue). I'll have test this locally.

**Comment by lonvia** [comment]
I've now added `zoom=17` as an in-between zoom level that returns major and minor streets. `zoom=16` will remain at the current behaviour and zoom in on the next major street.

You can update to most recent master (or just apply above commit) and it should work without a reimport.
