### ISSUE TITLE
Bad address resolution when label node not in boundary area

### ISSUE THREAD

**Issue by siffash** [openstreetmap/Nominatim#1352]
1. Find and open France (https://nominatim.openstreetmap.org/details.php?place_id=198319371).
2. Note that French Polynesia is marked on the map as part of France.
3. Scroll down to the section _Parent Of_, **French Polynesia is not on the list**.
4. If you find and open French Polynesia (https://nominatim.openstreetmap.org/details.php?place_id=198812185) and scroll down to the section _Address_, again you will see that it's part of France.

Expected behavior: France to be parent of French Polynesia.

**Comment by lonvia** [comment]
Nominatim uses the centre point of an area to determine parenthood. As French Polynesia has [a label node](https://www.openstreetmap.org/node/462226505) that one is used as centroid point. Unfortunately it is placed in the middle of nowhere.

**Comment by siffash** [comment]
@lonvia Is it because the label node points to an ocean? And is outside of the actual marked territory of the country?
Do you think this can be fixed somehow?

**Comment by lonvia** [comment]
Yes. You can simply move the label inside the area of French Polynesia and the problem will fix itself.

This can (and should eventually) also be fixed in Nominatim, which is why I haven't closed the ticket. It's just not of a particularly high priority as such cases are sufficiently rare.

**Comment by siffash** [comment]
Just did that :)
https://www.openstreetmap.org/changeset/69097303
Hopefully it'll be fixed one day, thank you.

**Comment by lonvia** [comment]
Nominatim has already picked that up.

**Comment by siffash** [comment]
That was fast. Thank you Sarah

**Comment by siffash** [comment]
@lonvia Hi Sarah, I found the same problem for [Wallis and Futuna](https://www.openstreetmap.org/relation/290162), again it's not part of [France](https://www.openstreetmap.org/relation/2202162). I couldn't fix it even after changing the [label node](https://www.openstreetmap.org/node/424298155).
