### ISSUE TITLE
Error after the final update command

### ISSUE THREAD

**Issue by MoustafaMahgoub** [openstreetmap/Nominatim#1353]
--init-updates
2019-04-10 10:42:16 == module path: /home/geoserver/customized-nominatim/build/module
2019-04-10 10:42:16 == Create Functions
ERROR: HTTP Error 404: Not Found
ERROR: HTTP Error 404: Not Found
Done. Database updates will start at sequence 2115 (2018-03-26T17:42:57Z)

(when I do the following command)
--import-osmosis-all
Currently at sequence 2115 (26/03/2018 20:42:57) - t indexed
/usr/local/bin/pyosmium-get-changes --server https://download.geofabrik.de/europe/germany/berlin-updates -o /home/geoserver/customized-nominatim/build/osmosischange.osc -s 30 -I 2115
/home/geoserver/customized-nominatim/build/osm2pgsql/osm2pgsql -klas --number-processes 1 -C 2000 -O gazetteer -S /home/geoserver/customized-nominatim/settings/import-full.style -d nominatim -P 5432 /home/geoserver/customized-nominatim/build/osmosischange.osc
osm2pgsql version 0.96.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
Mid: pgsql, cache=2000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Parsing gazetteer style file '/home/geoserver/customized-nominatim/settings/import-full.style'.
Using projection SRS 4326 (Latlong)

Reading in file: /home/geoserver/customized-nominatim/build/osmosischange.osc
Using XML parser.
COPY_END for place failed: FEHLER:  Relation »address_levels« existiert nicht
LINE 1: SELECT l.rank_search, l.rank_address FROM address_levels l
                                                  ^
QUERY:  SELECT l.rank_search, l.rank_address FROM address_levels l
       WHERE (l.country_code = NEW.country_code or l.country_code is NULL)
             AND l.class = NEW.class AND (l.type = classtype or l.type is NULL)
       ORDER BY l.country_code, l.class, l.type LIMIT 1
CONTEXT:  PL/pgSQL-Funktion placex_insert() Zeile 76 bei SQL-Anweisung
SQL-Anweisung »insert into placex (osm_type, osm_id, class, type, name,
                          admin_level, address, extratags, geometry)
        values (NEW.osm_type, NEW.osm_id, NEW.class, NEW.type, NEW.name,
                NEW.admin_level, NEW.address, NEW.extratags, NEW.geometry)«
PL/pgSQL-Funktion place_insert() Zeile 140 bei SQL-Anweisung
COPY place, Zeile 1: »N	316565527	amenity	disused:fast_food	\N	15	"city"=>"Berlin","housenumber"=>"153","street"=>"Müller...«

Error occurred, cleaning up
Error executing osm2pgsql: 1
( I tried http and https in for the download and it did not make any difference)

**Comment by lonvia** [comment]
My guess would be that you have imported with a different Nominatim version than with what you are trying updates now. But it's difficult to determine anything useful from a console dump without any context of what you were trying to do.

**Comment by MoustafaMahgoub** [comment]
Hello Ionvia thanks for answering , 
I have Nominatim 3.20 , I was trying to keep it up to date using pysomium.
I reached this command --init-updates
and it give me HTTP Error 404: Not Found , 
and then the next import command give me the upove error

**Comment by lonvia** [comment]
The missing table 'address_levels' does not exist in Nominatim 3.2. Please switch your software version of _Nominatim_ back to the same version you used for the import and try again.

**Comment by MoustafaMahgoub** [comment]
ok thank you , I will make sure of that 
Will this also solve the "ERROR: HTTP Error 404: Not Found"
for the . -init update command

**Comment by lonvia** [comment]
https://github.com/openstreetmap/Nominatim/issues/1306#issuecomment-462641509
