### ISSUE TITLE
Installation issue: Data file

### ISSUE THREAD

**Issue by tanjinprity4** [openstreetmap/Nominatim#1355]
./utils/setup.php --osm-file <data file> --all [--osm2pgsql-cache 28000] 2>&1 | tee setup.log

I am not sure what kind of data file is required here. Can you please provide me with an example?

**Comment by mtmail** [comment]
http://nominatim.org/release-docs/latest/admin/Import-and-Update/#initial-import-of-the-data

For single countries or continents go to https://download.geofabrik.de/ and use *.osm.pbf files, e.g. for https://download.geofabrik.de/europe/liechtenstein.html the `liechtenstein-latest.osm.pbf`

For the whole planet go to https://planet.openstreetmap.org/ and select the `Latest Weekly Planet PBF File`

For Planet and country extracts there are mirror servers/services listed on https://wiki.openstreetmap.org/wiki/Planet.osm#Downloading
