### ISSUE TITLE
how to get nearby address from postcode?

### ISSUE THREAD

**Issue by strivedge** [openstreetmap/Nominatim#1356]
i can't get proper data from this api https://nominatim.openstreetmap.org/search.php?format=json&countrycodes=US&postalcode=91411&city=Los+Angeles

**Comment by mtmail** [comment]
First do a postcode search. Then use the returned coordinates and do a reverse search. Example https://nominatim.openstreetmap.org/reverse.php?format=json&lat=34.1799751947752&lon=-118.459461808927

**Comment by strivedge** [comment]
When i try to get latitute longitute by this api https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&q=68945+Vista+Chino,+CA,+92234,+US&format=json&limit=1
i get blank array so i try to get lat long by this api https://nominatim.openstreetmap.org/search.php?format=json&countrycodes=US&postalcode=92234&city=Cathedral+City  but i can't get that lat long what i exactly looking for. there no data about address

**Comment by lonvia** [comment]
I'm sorry to say that your report does not make any sense whatsoever. You wee searching for a postcode. Nominatim returns you exactly that. The approximate position of the postcode you were looking for.

Now, if you are looking for an address, you have to ask for an address.  If you don't get a result for that address then chances are good that the data is simply not available in OpenStreetMap.
