### ISSUE TITLE
Travis PHP tests failed

### ISSUE THREAD

**Issue by patriksima** [openstreetmap/Nominatim#1357]
Hi,

I guess [specifying PHP version](https://docs.travis-ci.com/user/languages/php/#choosing-php-versions-to-test-against) in travis.yml is necessary for passing PHP tests. Otherwise it the latest version of PHPUnit is used ([because Travis uses phpenv](https://travis-ci.org/openstreetmap/Nominatim/jobs/520481187#L1101)). It causes error like this:

https://travis-ci.org/openstreetmap/Nominatim/jobs/520481187

`PHP Fatal error:  Declaration of Nominatim\AddressDetailsTest::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /home/travis/build/openstreetmap/Nominatim/test/php/Nominatim/AddressDetailsTest.php on line 108`

**Comment by patriksima** [comment]
Or someone has to fix the PHP tests. But it won't work with older PHP versions. Because void function not supported in PHP version < 7.1. Source https://www.php.net/manual/en/migration71.new-features.php

**Comment by mtmail** [comment]
Thanks a lot. I set the version to 7.1 now. https://github.com/openstreetmap/Nominatim/pull/1358

We still support PHP 5.6 (http://nominatim.org/release-docs/latest/admin/Installation/) so we're conservative.
