### ISSUE TITLE
Tag changes to end nodes of an interpolation don't end up in location_property_osmline

### ISSUE THREAD

**Issue by simonpoole** [openstreetmap/Nominatim#1360]
Nominatim 3.2.0

Changing the addr:housenumber tag of an end node does not propagate to location_property_osmline This will lead to duplicates if for example the end or start house number of an interpolation is newly mapped individually and the addr:housenumber tag is changed to the new start or end value.

**Comment by lonvia** [comment]
We even have a [failing test](https://github.com/openstreetmap/Nominatim/blob/master/test/bdd/db/update/interpolation.feature#L337) for that. The difficulty was that it is expensive to invalidate the interpolation.
