### ISSUE TITLE
associatedStreet not taken into account

### ISSUE THREAD

**Issue by Bibi56** [openstreetmap/Nominatim#1363]
For instance [12 Le Cap, Guidel](https://www.openstreetmap.org/search?query=12%2C%20Le%20Cap%2C%20Guidel) returns the hamlet Le Cap in Guidel. Not bad.
But as the house [12](https://www.openstreetmap.org/node/6257990581) exists the expected result is this node.
Notes:

- here the node is optimized: as the node is part of the `associatedStreet` it doesn't include the `addr:street` attribute. But even with `addr:street`, for instance 23 Le Cap, Guidel, the `addr:street` has been added for test.
- here there is no highway named Le Cap, Le Cap is the name of the hamlet and the roads remain unnamed, the numbers are for the hamlet.
- `associatedStreet` is of common use in France.

**Comment by lonvia** [comment]
The tagging is wrong. None of the streets in the relation has the name 'Le Cap'. In fact, the address is not even relative to the street, it's relative to the hamlet. Associated street relations cannot do that. What you are looking for is adding a tag addr:place=Le Cap to the house number nodes.

**Comment by Bibi56** [comment]
Addresses have been updated (and relation deleted). I close the ticket as Nominatim works now as expected. Thanks.
