### ISSUE TITLE
Searching for location gives http 500 exception

### ISSUE THREAD

**Issue by MDotSmit** [openstreetmap/Nominatim#1365]
Hi,

Some of the data i'm trying to resolve contains the address 'Ambassador Transit Lounge Terminal 2 Unit 03-036-123; Level 3 Next to Sun-Flower Garden; Departure Transit Lounge South; Passenger Terminal Building (PTB) 2; Singapore Changi Airport; Singapore Singapore Singapore'

When this is searched on nominatim.openstreetmap.org it gives a 500 exception

link: https://nominatim.openstreetmap.org/search.php?q=Ambassador+Transit+Lounge+Terminal+2+Unit+03-036-123%3B+Level+3+Next+to+Sun-Flower+Garden%3B+Departure+Transit+Lounge+South%3B+Passenger+Terminal+Building+%28PTB%29+2%3B+Singapore+Changi+Airport%3B+Singapore+Singapore+Singapore&polygon_geojson=1&viewbox=

Any help in figuring out what is wrong would be appreciated.

Kind Regards,

**Comment by mtmail** [comment]
It's too many words per phrase in the query string and the webserver process runs out of memory and crashes. There's a bit of code logic to pre-calculate how many word combinations will be generated but in some cases then the actual word list ends up too big (in bytes, not number of elements).

The query string is split into phrases by comma. So adding a comma between address parts, e.g. street vs city vs state vs country helps. In this case replacing the semicolons with commas.

**Comment by lonvia** [comment]
Too be fair: nothing will help with this kind of query. Nominatim only matches places/addresses that fully contain the terms you were looking for. In addition there is no support for searching for units, levels or descriptive terms like 'next to something'.
