### ISSUE TITLE
usage of same nominatim database

### ISSUE THREAD

**Issue by parsispresswala** [openstreetmap/Nominatim#1366]
Hello,
Can I use same nominatim database on another system?

I have done nominatim on my local system which is around 500 GB, but now I want same database on another aws ec2 server without going through any set up process. So can I use same database for nominatim? Will it work fine for me?

I can take backup of data and create zip and upload on server. Is there any other way to so this process? If yes, How am I able do that? If anyone can help, it would be appreciated. 

Thanks.

**Comment by mtmail** [comment]
Yes, you can create a copy of the database on/to another server and the Nominatim software will be able to use that.

**Comment by parsispresswala** [comment]
Thanks..
