### ISSUE TITLE
Allow using system osm2pgsql

### ISSUE THREAD

**Issue by Boskovits** [openstreetmap/Nominatim#1370]
I am packaging Nominatim for Guix System.
I wonder if there is a way currently to point the build system to the system osm2pgsql instead.
I have seen the original reasons why osm2pgsql was bundled, it boils down to:
1. always build osm2pgsql from source. (This is statisfied in Guix System, being a source based distribution)
2. use the proper version: this can be ensured by packagers.
Wdyt?

FYI:
On guix this package definition would list an osm2pgsql package as input, and only that version would be made available in the build environment.

**Comment by lonvia** [comment]
You can set the osm2pgsql to be used in your local configuration with `CONST_Osm2pgsql_Binary`. Note however that this is an expert option and you are completely on your own, when using that. Nominatim does not depend on released version of osm2pgsql but on very specific commits in between releases.

**Comment by lonvia** [comment]
I notice that you might be asking about the build step, not the execution. There the answer is: no, that's not possible and I'm mildly reluctant to add a switch because it tends to get abused.
