### ISSUE TITLE
curl and browser requests return different results (state instead of country)

### ISSUE THREAD

**Issue by tomschulze** [openstreetmap/Nominatim#1371]
i use the mediawiki geocoder function from the mediawiki/maps extension which uses `https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=ANYSTRING` for its queries.

`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=Georgia` in a browser window returns the country

`curl https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=Georgia` returns the US state

see also #1104; however, that does not fix my problem

is there a way to make sure that only the country is returned only by modifying the `q` parameter in the request url?

**Comment by mtmail** [comment]
> is there a way to make sure that only the country is returned only by modifying the q parameter in the request url?

That's not possible with just the `q=` parameter. Either `accept-language=`, `viewbox=&bounded=1`, `country=` or similar filters would need to be set. I had a look at the wiki extension (which uses the simplegeocode extension), there doesn't seem to be an easy to way to change that, other than forking or changing the source locally.

**Comment by tomschulze** [comment]
thanks for looking into this so quickly. then you may close the issue if there's nothing to add :)
