### ISSUE TITLE
No CORS header for "Bandwidth limit exceeded" response

### ISSUE THREAD

**Issue by simonepri** [openstreetmap/Nominatim#1373]
While using the search API, If you get temporarily blocked, the CORS header is not sent in the response.
![image](https://user-images.githubusercontent.com/3505087/57181703-477cf780-6e97-11e9-8e59-d0353ce29057.png)
![image](https://user-images.githubusercontent.com/3505087/57181704-4e0b6f00-6e97-11e9-8c4e-5dd6c44eac40.png)

**Comment by lonvia** [comment]
We don't give any guarantees if requests are not in line with the usage policy. The response is not in json either, so your website is bound to break in nasty ways anyway.

Sorry but closing as won't fix.

**Comment by simonepri** [comment]
@lonvia Thank you for your answer, I understand your point of view but I don't think it's a great design decision to leave the error page as is.

The requested to the Nominatim's APIs are limited per IP and not per ORIGIN (the website's DNS).
This means that if a user visits more than one website that uses the Nominatim's APIs respecting the usage policies the user can still be soft-banned.
