### ISSUE TITLE
Reverse geocoding: difference between 3.0.0 and 3.2.0

### ISSUE THREAD

**Issue by korstiaanS** [openstreetmap/Nominatim#1374]
Hi,

The past year I used version 3.0.0 and it worked great!
I recently created a new installation based on 3.2.0.
It also works fine BUT some results are not the same, and worse, some don't give a road?

As an example in 3.0.0 the result of the request

`http://10.0.0.101/nominatim/reverse?format=xml&lat=51.006900&lon=3.748850&zoom=16`

was

```
<reversegeocode timestamp="Thu, 09 May 19 13:20:06 +0200" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="format=xml&lat=51.006900&lon=3.748850&zoom=16">
<result place_id="80549234" osm_type="way" osm_id="277613056" ref="R4" lat="51.0073919" lon="3.7489087" boundingbox="51.0068306,51.0073919,3.7489087,3.7509327">
Buitenring Merelbeke, Flora, Merelbeke, Gent, Oost-Vlaanderen, Vlaanderen, 9820, België
</result>
<addressparts>
<road>Buitenring Merelbeke</road>
<neighbourhood>Flora</neighbourhood>
<town>Merelbeke</town>
<county>Gent</county>
<state>Vlaanderen</state>
<postcode>9820</postcode>
<country>België</country>
<country_code>be</country_code>
</addressparts>
</reversegeocode>

```

in 3.2.0 is this:

```
<reversegeocode timestamp="Thu, 09 May 19 13:20:15 +0200" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="format=xml&lat=51.006900&lon=3.748850&zoom=16">
<result place_id="86409287" osm_type="way" osm_id="277613054" lat="51.007282" lon="3.7490696" boundingbox="51.0069492,51.0073919,3.7489087,3.7498473">
Flora, Merelbeke, Gent, Oost-Vlaanderen, Vlaanderen, 9820, België
</result>
<addressparts>
<neighbourhood>Flora</neighbourhood>
<town>Merelbeke</town>
<county>Gent</county>
<state>Vlaanderen</state>
<postcode>9820</postcode>
<country>België</country>
<country_code>be</country_code>
</addressparts>
</reversegeocode>

```

As you can see, in the newer release no road is returned. Higher or lower zoom levels don't help.
Any reason why?
Any way to solve this?

Korstiaan

**Comment by mtmail** [comment]
You can click around in the map to test the search: https://nominatim.openstreetmap.org/reverse?format=html&lat=51.006900&lon=3.748850&zoom=16 The small red circle is the search position, the larger blue circle the result. 

![image](https://user-images.githubusercontent.com/3727288/57453023-90e99000-7265-11e9-85ac-09725562f7d8.png)


The result is a smaller, closer, unclassified road (https://www.openstreetmap.org/way/277613054), and it doesn't have a name which is the confusion here. The JSON output shows the empty name more clear while the XML output prints no attribute https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=51.006900&lon=3.748850&zoom=16

I think given the search coordinates the result is reasonable. I wouldn't say the person/vehicle is on Buitenring Merelbeke. "unnamed road" might be better readable for users. Scheldestraat might be a good second result (reverse geocoding only returns one result). If the buildings had house numbers or names in the OSM data those would get returned.

**Comment by korstiaanS** [comment]
Ah, ok.
So it seems that the map content is changed between my 2 releases.
So my output (no road) is the result of having a newer database.

Thanks for the explanation.
