### ISSUE TITLE
Installation issue on UBUNTU 18.04

### ISSUE THREAD

**Issue by moisesf** [openstreetmap/Nominatim#1376]
Following [(installation instructions)](https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/) i can't understand the line below:

_Make sure that system servers can read from the home directory:
chmod a+x $USERHOME_

How can i run that line if $USERHOME directory is owned by other user ? 
What is wrong ?

**Comment by mtmail** [comment]
Use the 'sudo' command to change permissions if necessary.

**Comment by moisesf** [comment]
I did. 
Now i got this:

_nominatim@XXXXXX:~/Nominatim$ ./utils/setup.php --osm-file brazil-latest.osm.pbf --all --osm2pgsql-cache 700 2 >&1 | tee setup.log
-su: ./utils/setup.php: Permission denied_

**Comment by mtmail** [comment]
Where does the `-su` come from in the output?

`2 >&1` There shouldn't be a space after the `2`

The script should be run as user `nominatim` in the build directory (the directory in which the `cmake` command was run). All files in the build directory should be owned by the user.

**Comment by moisesf** [comment]
It worked. I was running in Nominatim directory.
It would be nice if that was more clear in installation instructions.

**Comment by ederantonio** [comment]
hello I have a question in this step: construction and configuration

Get the source code of the version and unzip it

cd $ USERHOME
wget https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
tar xf Nominatim-3.4.1.tar.bz2

in the terminal this marks me, what's going on?

ubuntuserver@ubuntuserver-VirtualBox:/srv/nominatim$ wget https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
--2020-05-05 11:44:25--  https://nominatim.org/release/Nominatim-3.4.1.tar.bz2
Resolviendo nominatim.org (nominatim.org)... 138.201.190.130
Conectando con nominatim.org (nominatim.org)[138.201.190.130]:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 48539993 (46M) [application/x-bzip2]
Nominatim-3.4.1.tar.bz2: Permiso denegado

No se puede escribir a “Nominatim-3.4.1.tar.bz2” (Conseguido).
