### ISSUE TITLE
Using Nominatim on Amazon RDS (nominatim.so ?)

### ISSUE THREAD

**Issue by bgaillard** [openstreetmap/Nominatim#1377]
Hi, we wish to use Nominatim with Amazon RDS and perhaps Amazon Aurora.

When we execute our import we encounter the following errors.

```
CREATE FUNCTION
ERROR:  permission denied for language c
CREATE FUNCTION

CREATE FUNCTION
ERROR:  permission denied for language c
SET

ERROR:  permission denied for relation spatial_ref_sys
invalid command \.

ERROR:  function public.transliteration(text) does not exist
LINE 1: SELECT public.gettokenstring(public.transliteration(name))
                                     ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT public.gettokenstring(public.transliteration(name))
CONTEXT:  PL/pgSQL function public.make_standard_name(text) line 5 at assignment
```

With our teammates we understand that the import process need 2 functions written in C languages and compiled in `nominatim.so`. 

Amazon RDS or Amazon Aurora do not accept C functions, that's why we encounter the import error.

We searched in the documentation but did not found any information which indicates if `nominatim.so` is only used during the import or also during querying.

If `nominatim.so` is only required during the import we could import our data inside a PostgreSQL database executed in Docker and having `nominatim.so`. Then we could export our data and re-import it on our Amazon RDS or Aurora database.

So, is `nominatim.so` used during querying ? If yes do you have workaround to not use `nominatim.so` (perhaps an equivalent code for the functions in psql) ?

Thanks

**Comment by mtmail** [comment]
`nominatim.so` is used for import and querying, so managed database services (no disk access) don't work. We don't have a non-C workaround. In the future we'd like add a i18n library to the C functions so it would become even harder to write a psql equivalent. The Docker approach should work.

**Comment by bgaillard** [comment]
Hi @mtmail and thanks for your response, so we cannot use Amazon RDS neither Amazon Aurora with Nominatim.

> In the future we'd like add a i18n library to the C functions so it would become even harder to write a psql equivalent.

Ok, is this a performance consideration or something linked to features ? 

IMO without being able to use Nominatim with a Cloud Database Nominatim will not be very attractive in the future.

For now we'll install Nominatim with Docker but as is its definitely less robust than Amazon RDS or Aurora with multi-AZ and demands much more work to setup.

Hope this could convince you to not write too much features in C :grin:

**Comment by mtmail** [comment]
Performance mostly. Nominatim places a lot of logic inside the database to avoid back and forth data conversion between PHP and the database, especially during looping over places. That was an architecture decision from day (another to allow incremental, minutely, updates while many other geocoders to full index builds). The current character mappings in https://github.com/openstreetmap/Nominatim/tree/master/module could be (still lots of work) be converted into another language, e.g. PL/Lua, the possible unicode complexity is better handled with third-party tested libraries like http://site.icu-project.org/

**Comment by bgaillard** [comment]
Hi @mtmail, ok I understand, so we'll plan to manage Nominatim with Docker.

Thanks a lot for those clarifications !
