### ISSUE TITLE
updates for the whole planet - how?

### ISSUE THREAD

**Issue by tchwpkgorg** [openstreetmap/Nominatim#1378]
The fine manual at http://nominatim.org/release-docs/latest/admin/Import-and-Update/ describes how to update a single country and gives the following as an example:

```
// base URL of the replication service
@define('CONST_Replication_Url', 'https://download.geofabrik.de/europe/ireland-and-northern-ireland-updates');
```

How can I run the updates for the whole planet (my database was created from https://planet.openstreetmap.org/pbf/planet-latest.osm.pbf)?

**Comment by mtmail** [comment]
The URL for the planet is
```
  @define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day');
```
There's also a couple of mirrors, look for diffs=yes https://wiki.openstreetmap.org/wiki/Planet.osm#Downloading
