### ISSUE TITLE
Postal code 2970 (Hørsholm, Denmark) not found

### ISSUE THREAD

**Issue by rasmustaarnby** [openstreetmap/Nominatim#1380]
Searching for 2970, DK does not return expected result. 

There seems to be an issue when searching for specific postal codes, city, country combinations and a few postal codes are not mapped correctly to the city / municipality. 

I hope the following makes sense, I can include the search results, as per the contributing guidelines, if it makes it easier. I have left the out to not clutter this more than it already is. 

**Searches:** 

Search: 2970
Return: Anything but DK in results
Link: https://nominatim.openstreetmap.org/search.php?q=2970

Search: 2960
Return: Has Hørsholm, DK in the results 
https://nominatim.openstreetmap.org/search.php?q=2960

Search: 2970, DK
Return: One result in Poland
https://nominatim.openstreetmap.org/search?format=json&q=2970+DK

Search: 2960, DK
Return: Correct result
https://nominatim.openstreetmap.org/search?format=json&q=2960+DK

Search: 2970, Denmark
Search: 2970, Danmark
Return: Anything but DK in results
https://nominatim.openstreetmap.org/search?format=json&q=2960+Danmark

Search: 2960, Denmark
Search: 2960, Danmark
Return: Correct result on the wrong postal code
https://nominatim.openstreetmap.org/search?format=json&q=2960+Danmark

--- 

Now it becomes really interesting because if I use the city name in the search instead of the country it returns correctly.

Search: 2970 hørsholm
Return: One correct result
https://nominatim.openstreetmap.org/search.php?q=2970+hørsholm

Search: 2960 hørsholm
Return: Two correct results, except the postal code which is wrong
https://nominatim.openstreetmap.org/search.php?q=2960+hørsholm

The above searches are using the q= param but if I change the searches to use the specific params found here https://nominatim.org/release-docs/develop/api/Search/ it still doesn't find the correct results, in fact it returns fewer correct results. 

Wrong or empty results:
https://nominatim.openstreetmap.org/search?format=json&postalcode=2970&city=hørsholm
https://nominatim.openstreetmap.org/search?format=json&postalcode=2970

Correct results:
https://nominatim.openstreetmap.org/search?format=json&postalcode=2960&city=hørsholm

Even the correct result returns the correct postal code (2970) in the display name, despite I'm searching for 2960 which is the city "Rungsted":
"Hørsholm, Hørsholm Kommune, Region Hovedstaden, 2970, Danmark"

**Comment by mtmail** [comment]
Thanks a lot for all the examples.

When I add `&debug=1` https://nominatim.openstreetmap.org/search?format=json&q=2970+DK&debug=1 I see the valid-token list contains '2970-' and the first search candidate as well. That search then fails and the next search candidate searches are less and less relevant.

I can't explain where the dash comes from, I don't see any such postcodes (`2970-`) in my database. We'll investigate.

**Comment by mtmail** [comment]
@rasmustaarnby I removed a trailing dash from a postcode in Poland. https://www.openstreetmap.org/changeset/70241689 I think that fixed the queries. Can you confirm?

**Comment by rasmustaarnby** [comment]
@mtmail The queries returns the expected results now, so as far as I can see, everything is working. Nice job and thanks for the quick fix.
