### ISSUE TITLE
Nominatim/Apache doubles pagename

### ISSUE THREAD

**Issue by Zakrinichniy** [openstreetmap/Nominatim#1384]
![изображение](https://user-images.githubusercontent.com/50746436/57937869-8c5d5100-78cf-11e9-963f-a637715622cc.png)
When I'm pressing reverse search or anything I get link like this so my customers cannot use this service. Please help me sort out why this happen.

**Comment by mtmail** [comment]
In `build/settings/local.php` check the setting of the `CONST_Website_BaseURL` variable. It should be a URL including protocol and domain name, e.g.
  @define('CONST_Website_BaseURL', 'http://192.168.88.174:80/nominatim/');
Then you should be able to see the page on http://192.168.88.174:80/nominatim/reverse.php

**Comment by mtmail** [comment]
Please reopen if that config change didn't work.
