### ISSUE TITLE
HTTP 500 for out-of-memory should be handled and return formatted error message

### ISSUE THREAD

**Issue by mmd-osm** [openstreetmap/Nominatim#1385]
While testing something else, I noticed that the following Nominatim query returns an HTTP 500 error.

https://nominatim.openstreetmap.org/search.php?q=%E7%94%9F%E6%80%81%E7%8E%AF%E5%A2%83%E7%AD%89%E9%83%A8%E9%97%A8%E5%92%8C%E7%9B%B8%E5%85%B3%E5%9C%B0%E5%B8%82%E5%AF%B9%E8%BE%BD%E6%B2%B3%E6%B5%81%E5%9F%9F%E6%B0%B4%E6%B1%A1%E6%9F%93%E9%98%B2%E6%B2%BB%E5%B7%A5%E4%BD%9C%E6%8E%A8%E8%BF%9B%E4%B8%8D%E5%8A%9B&polygon_geojson=1&viewbox=

**Comment by mtmail** [comment]
The process runs out of memory (further explained https://github.com/openstreetmap/Nominatim/issues/1365#issuecomment-486472111). Nominatim should handle it better, we haven't found an easy way yet, but it's a relative rare event and the input query is usually not answerable.

**Comment by mmd-osm** [comment]
Thanks for your feedback. A quick search returns a few results based on `register_shutdown_function`. I haven't really tested it and don't know if this might be useful.

https://stackoverflow.com/questions/8440439/safely-catch-a-allowed-memory-size-exhausted-error-in-php

**Comment by mtmail** [comment]
Great find, I have a couple of test cases, plus the one in this issue, and will try prototyping that.
