### ISSUE TITLE
Add a record about post code "96741"

### ISSUE THREAD

**Issue by Emil-Zhou** [openstreetmap/Nominatim#1386]
Hi Guys,
How can I add a post code "96741" for 'Hawali' (HI) with the values of "HI 96741"? let it participate in geocoding process.

Details:
I have a geocoding address "4618 Puuwai Rd,96741-9330" 
here is the search candidate which should be correct, and has result
![image](https://user-images.githubusercontent.com/16344877/58016214-a09f8900-7b2f-11e9-9922-a21c9c5eacc5.png)
but there is no row of '96741' in location_postcode. just is 'HI 96741' 

 ps: here is another row for 'Hawali' (HI) in location_postcode, FYI
     SELECT * FROM location_postcode p WHERE p.postcode in ('HI 96819', '96819' )
     SELECT * FROM location_postcode p WHERE p.postcode in ('HI 96761', '96761' )

so I want add a row for postcode "96741" with value of 'HI 96741'.

The point is that I think it is wrong to directly manipulate the database manually, because it doesn't update other tables including: work, search_name, placex.

Thanks,

**Comment by mtmail** [comment]
Here it's best to find the places in the master OSM data (on the openstreetmap.org website) and change their `addr:postcode` value (remove the 'HI ' part).

I usually use https://overpass-turbo.eu/s/JaQ (then click 'run') and use the editor on openstreetmap.org to change such places.

https://www.openstreetmap.org/node/1457211763
https://www.openstreetmap.org/node/2609285445

With your own Nominatim database you can also run a query

```
select place_id, osm_type, osm_id, postcode from placex where country_code='us' and upper(address->'postcode') like 'HI%' order by osm_type, osm_id;
 place_id | osm_type |   osm_id   | postcode
----------+----------+------------+----------
 16106045 | N        | 1457211763 | HI 96761
 27250028 | N        | 2609285445 | HI 96819
 52518213 | N        | 4231110390 | HI 96732
 57613609 | N        | 4686101289 | HI 96746
 64109206 | N        | 5391957021 | HI 96707
 65268046 | N        | 5557767128 | HI 96740
 73452347 | N        | 6294960585 | HI 96741
```

nominatim.openstreetmap.org updates the `location_postcodes` table once per night. If you run your own Nominatim server then you can run `utils/update.php --calculate-postcodes` from the Nominatim build directory.

**Comment by mtmail** [comment]
Closing as data issue. My previous answer has instructions how to fix the OSM data.

**Comment by Emil-Zhou** [comment]
Thanks, @mtmail
