### ISSUE TITLE
using cycleways for addresses?

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/Nominatim#1389]
I have noticed a strange geocoding result for the Fiumicino Airport:
https://nominatim.openstreetmap.org/search.php?q=fco&polygon_geojson=1&viewbox=
results in:

> Roma-Fiumicino Airport, Ciclabile Viale Coccia di Morto, Focene, Fiumicino, RM, Lazio, 00054, Italy

There is not an explicit address on the airport way, in this case there is a highway=cycleway running parallely (towards the airport area) along a road which itself runs along the airport (but with no entrances, those are kilometers away).

The actual entrances to the "airport" (Terminals) are around here: https://www.openstreetmap.org/way/325928707

The main reason I wrote here is the choice of the cycleway for addressing, even more as it is just a few meters away from a road.

**Comment by lonvia** [comment]
It's the closest named road to the airport. There are cases where addresses refer to a footway or cycleway. We can't just leave them out. If the airport has an official address, add the address to fix the issue.

**Comment by matkoniecz** [comment]
Is Nominatim aware about object type? Maybe it possible to exclude cycleway/footway matches for objects like airports.

**Comment by lonvia** [comment]
That's just patching up one particular one particular use case. It is also entirely unnecessary. We already have `addr:` tags to express addresses of an object.

**Comment by dieterdreist** [comment]
I have added the address as good as I could find it (no housenumber), but it still shows the cycleway: 
https://www.openstreetmap.org/way/22883270

**Comment by matkoniecz** [comment]
Is there `addr:housenumber` assigned to the airport?

**Comment by dieterdreist** [comment]
no, I did not find an address on their website: https://www.adr.it/azn-altre-inf-contatti
I found the housenumber "320" on a different, proprietary (not official) website, but it is not confirmed and it is not legally usable. 
There is a street address tag though, and if the middle of this street were taken, it would be quite ok:
https://www.openstreetmap.org/way/325928707

I do not understand why Nominatim ignores the explicit addr:street tag and prefers to show the cycleway as address.

**Comment by lonvia** [comment]
Not sure why it does not pick up the street. I need to look into that.

Note though that fixing that will do nothing to improve your routing. You are mixing up addresses and entrances (i.e. start/end points for routing). They are not necessarily the same. Nominatim computes the first, routing engines compute the latter from a point they are provided. You need to fix the routing engines to be more clever where to start from.

**Comment by dieterdreist** [comment]
I have expected that it would not fix the routing. What we should probably do is map the entrances to the terminals. You would usually have to know to which Terminal you have to go, or you would have to walk a lot anyway. The airport is currently mapped including the hotels, train station and motorway links, which means the „entrance“ to the airport would be at the intersection of the area with the access roads. Not sure this would be acceptable.
