### ISSUE TITLE
"error":"Unable to geocode"

### ISSUE THREAD

**Issue by uilll** [openstreetmap/Nominatim#1390]
Hello! I have a proper server of nominatim and it works very well in the browser, however, when I'm going to request a reverse geocode with a php file, for example, I get an "error" response: "Unable to geocode". I researched solutions and found:

```
// Create a stream
$opts = array('http'=>array('header'=>"User-Agent: StevesCleverAddressScript 3.7.6\r\n"));
$context = stream_context_create($opts);

// Open the file using the HTTP headers set above
$file = file_get_contents('http://nominatim.openstreetmap.org/search/q=Rome', false, $context);
```
Source: https://help.openstreetmap.org/questions/59788/calling-nominatim-with-file_get_contents

But, the solutions did not work on my server, I think I have a setting to enable the option via request via php, can anyone help me?

**Comment by mtmail** [comment]
On your private server the URL needs the `/nominatim/` path, on nominatim.openstreetmap.org that is not needed and might be confusing.

`file_get_contents` can open URLs but needs to be enabled. Check the `allow_url_fopen` directive in your `php.ini`. 

The `Unable to geocode` error can have multiple meanings. For example if you mix latitude and longitude the search position might simply be in an area where no results can be found, e.g. the Pacific Ocean or an area/country that wasn't imported.

A very basic script would be

```php
$server = 'myserver.mydomain.com'; // or IP address
$url = 'http://' . $server . '/nominatim/reverse.php?lat=' . urlencode($latitude) . '&lon=' . urlencode($longitude);
$contents = file_get_contents($url);
$results = json_decode($contents);
var_dump($results);
```

**Comment by uilll** [comment]
The "allow_url_fopen" is enabled, but your script worked, what was different from the other codes was the function "urlencode ()" that other codes did not have.

Thanks @mtmail
