### ISSUE TITLE
wiki-import specialphrases.sql

### ISSUE THREAD

**Issue by Emil-Zhou** [openstreetmap/Nominatim#1392]
Hi Guys,

there is an issues about `--wiki-import`, 

![image](https://user-images.githubusercontent.com/16344877/58308798-1dcf4480-7e35-11e9-88a5-2fa7bf9d71f7.png)

it can keep going, but the output file specialphrases.sql is 3.6 MB, and there are 1123 tables on the database after running the sql file.

if all goes well(I checked the other machines deployed for testing), the output file should be 6.0MB,  and there are 1125 tables on the database.

thanks.

**Comment by Emil-Zhou** [comment]
sometimes I repeat it, and it works.
![image](https://user-images.githubusercontent.com/16344877/58311826-7f46e180-7e3c-11e9-977c-39a6755e7227.png)
Maybe it's a network connection problem on my side.

Thanks.

**Comment by mtmail** [comment]
> there are 1125 tables on the database

That's normal. For partitioning (speed optimization) data is split into 250 tables, even for small countries. There's a bit of detail on https://nominatim.org/release-docs/latest/data-sources/Country-Grid/

**Comment by Emil-Zhou** [comment]
Thanks for your information.
