### ISSUE TITLE
External DB: Database server failed to load /srv/nominatim/Nominatim/build/module/nominatim.so module

### ISSUE THREAD

**Issue by nguyenhoangnhon** [openstreetmap/Nominatim#1397]
Hi All, 
Please help me fix this issue . I setup a Nominatim server with a external database and i get a error when importing data. Here is my log:

nominatim@lab:~/Nominatim/build$ ./utils/setup.php --osm-file /srv/nominatim/data/vietnam_latest.pbf --all 2>&1 | tee setup.log
2019-05-29 03:17:47 == module path: /srv/nominatim/Nominatim/build/module
2019-05-29 03:17:47 == Create DB
2019-05-29 03:17:48 == Setup DB
Postgres version found: 10
Postgis version found: 2.4
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /srv/nominatim/Nominatim/build/module/nominatim.so module

  thrown in /srv/nominatim/Nominatim/lib/DB.php on line 61

**Comment by killer3dfx** [comment]
Hello, did you find answer? i have the same problem.

**Comment by mitsuruyi** [comment]
no answer? I have the same issue but in different line

**Comment by lonvia** [comment]
http://nominatim.org/release-docs/latest/admin/Faq/#website-reports-could-not-load-library-nominatimso
