### ISSUE TITLE
Error in street name

### ISSUE THREAD

**Issue by hiagodotme** [openstreetmap/Nominatim#1402]
The name of the street is incorrect. The correct name is "Rua Luíz Figueiredo Filho" 

https://nominatim.openstreetmap.org/details.php?place_id=112172739

**Comment by mtmail** [comment]
If you click the link next to 'OSM' you can see the road (way) on the main openstreetmap.org website: https://www.openstreetmap.org/way/156734211

On that page there is a 'edit' feature in the top navigation. https://www.openstreetmap.org/edit?way=156734211#map=16/-20.8294/-49.3777

Thanks for helping to fix OpenStreetMap! https://www.openstreetmap.org/fixthemap
