### ISSUE TITLE
Internal Server Error when memory quota is exhausted

### ISSUE THREAD

**Issue by Guillaumevk** [openstreetmap/Nominatim#1404]
Hello and thank you so much for your excellent work.

I get a 500 error when making this request:
- URL: https://nominatim.openstreetmap.org/search.php?q=Divyasree+Trinity+Building+Plot+No.+6+Hi+Tech+City+Layout+Survey+Number+64+Madhapur+Village+Serilingampally+Ranga+Reddy+District+Hyderabad+Telangana+500081+India
- Details: Allowed memory size of 209715200 bytes exhausted (tried to allocate 20480 bytes)

**Comment by lonvia** [comment]
Indeed but #1388 is live, so I guess it didn't really fix the issue.

**Comment by mtmail** [comment]
During creation of the out-of-memory response we try to allocate memory for the HTML/XML reponse and that fails. I've read one can pre-allocate during startup and release in the error handler but the release doesn't happen fast enough. I'll see if there's other work-arounds.

**Comment by lonvia** [comment]
Ah, I assumed #1388 did handle that situation. I'm actually okay with sending back a 500 as well in that case.

**Comment by lonvia** [comment]
Indirectly resolved in #1412 by avoiding out-of-memory conditions.
