### ISSUE TITLE
Directions from/to here fails

### ISSUE THREAD

**Issue by jluttine** [openstreetmap/Nominatim#1405]
Trying to get directions by choosing "from here" and "to here" from the map fails:

![Peek 2019-06-17 15-05](https://user-images.githubusercontent.com/2195834/59603234-8e564200-9111-11e9-85aa-58615140d5b5.gif)

When choosing the other point, it complains about the other. Any ideas what is wrong?

**Comment by lonvia** [comment]
Duplicate of https://github.com/openstreetmap/openstreetmap-website/issues/1874
