### ISSUE TITLE
How can i update us_postcode sql file from Tiger 2018 data. 

### ISSUE THREAD

**Issue by ZhaoYubing** [openstreetmap/Nominatim#1410]
Hi Guys,

Currently the `us_postcode ` file has been created from Tiger 2017 data. Is there a guide about update it as Tiger 2018.

Here is my plan :
1. update the us_postcode file following my needs.
2. run the command `utils/update.php --calculate-postcodes`
Is there anything else I should pay attention to?

By the way, I reviewed the source code about `placex`, I'm not sure that the postcode of the record in placex will be updated after carrying out my plan. I'm starting to try it 

Thanks

**Comment by mtmail** [comment]
There's no guide (yet). I started with data-sources scripts and guides in https://github.com/openstreetmap/Nominatim/tree/master/data-sources The documentation gets published on http://nominatim.org/release-docs/latest/ (left side navigation 'external data sources').

@lonvia might have the SQL she used somewhere (https://github.com/openstreetmap/Nominatim/commit/e080ccbcf83448f56ea8773e739ecd4f37cad63e)

```
Location has been computed as the centroid over all
lines of a given postcodes. Then all postcodes which
cover a radius of more than 0.9 have been removed.
```

I'll be happy to document the process.

**Comment by lonvia** [comment]
I didn't keep the SQL statements but it should be easy enough to recreate them from above statements. It would be interesting to see how much of a difference there is between 2017 and 2018.

**Comment by mtmail** [comment]
@Emil-Zhou The `us_postcodes.sql` contains the SQL statements to recreate the file at the top. `Data has been created from Tiger 2017 data as follows: ...`

**Comment by Emil-Zhou** [comment]
Thanks, I'll give it a try.
