### ISSUE TITLE
return less accurate matches (without exclude_place_ids)

### ISSUE THREAD

**Issue by eliboni** [openstreetmap/Nominatim#1413]
Is it possible to get less exact results  at the first round? For example:
https://nominatim.openstreetmap.org/search.php?q=grimsel&limit=5
returns just one result, but I'd like it to return also grimselpass which is the 1st option when  I exclude the exact match:
https://nominatim.openstreetmap.org/search.php?q=grimsel&exclude_place_ids=16845790

thx

**Comment by mtmail** [comment]
In the first search it found its best match, a hotel whose name matches the search query. When you click 'more results' it tries to find partial matches like Gimselstrasse, Gimselbrunnen, Gimselpass. Doing partial match search for each search would add unnecessary database queries, there's currently no URL parameter to force a second search.

With grimsel specifically you could rename the first result (the hotel, https://www.openstreetmap.org/node/1570631405) into "Hotel Grimsel", then Nominatim will have to do two searches.

**Comment by eliboni** [comment]
Unfortunately this behavior make nominatim impractical for several searches, try "GARMISCH" for example, anywhere in Europe this would refer to Garmisch-Partenkirchen city in Germany. Nominatim perfect matched results are two minor streets in US. I've several other examples. It would be nice if "limit=n" parameter could be honored with partial matches as well.

**Comment by mtmail** [comment]
Can you check if http://photon.komoot.de/ fits the purpose? It uses exports of the Nominatim database, but a different search approach.

**Comment by eliboni** [comment]
Yep, appreciate your suggestion - I had a look at photon, there are still gaps, but it performs slightly better for these searches. For example in several cities in Europe  the name is a concatenation of different words but it is unlikely a user will type the full name, just the first word and then hit search button - perhaps a non exact match on city name could help but I understand this is a complex topic.
