### ISSUE TITLE
Weird issue with Italian state names for accept-language=it in reverse lookup

### ISSUE THREAD

**Issue by jeffrey-friedl** [openstreetmap/Nominatim#1416]
https://nominatim.openstreetmap.org/reverse?accept-language=it&format=json&lat=41.8691&lon=13.1939

This returns a "state" of "LAZ" (the "short_name") instead of the "Lazio" ("name") one would expect.  Or am I incorrect to expect "name" over "short_name"?

I tried adding namedetails=1 so that I could access the various names myself, but could not get that option to work... I found that it had no impact on the result.

I'd appreciate ideas on how to get "Lazio" in this scenario. Thanks!

**Comment by lonvia** [comment]
There is already a discussion about short_name in #783. Problem here is that the usage of the tag seems to be shifting. It used to be a shorter version of the full name (e.g. 'New York' for the full 'New York City'). So it made perfect sense to show short_name in favour of the name in the results. Now it is increasingly used to put in abbreviations like LAZ. Personally, I find it very annoying to abuse an existing tag like that but I fear it's a loosing battle.

Anyway, closing here as a duplicate. Feel free to comment on #783.

Regarding your question: you can't really get full name details for address parts at the moment.

**Comment by jeffrey-friedl** [comment]
Thank you Ionvia. I'm not sure how I missed #783 when checking existing bugs. My bad.
