### ISSUE TITLE
France Métropolitaine <> France mismatch

### ISSUE THREAD

**Issue by Marc-marc-marc** [openstreetmap/Nominatim#1420]
a [query](https://nominatim.openstreetmap.org/search.php?q=France+métropolitaine) for France métropolitaine reply with the relation "France" for the 1st match (both are not the same, the 1st is a part of the 2nd)
in [this match](https://nominatim.openstreetmap.org/details.php?place_id=198319371), I have found `France métropolitaine (alt_name)` but osm doesn't have this alt_name.
I looked at the recent history of the relation, I didn't find it.
where nominatim find it ?
related to https://github.com/drolbr/Overpass-API/issues/532

**Comment by Marc-marc-marc** [comment]
how this merge is made ? because both describe a country with the same name ?

however i have fixed wrong tags on the geodesic node used as label but a  [query](https://nominatim.openstreetmap.org/search.php?q=France+métropolitaine) for "France métropolitaine" still reply "Relation France (2202162)". "France métropolitaine (alt_name)" is still present for Nominatim in [France place_id=198319371](https://nominatim.openstreetmap.org/details.php?place_id=198319371)
but it didn't find it in osm anymore
[overpass](https://overpass-turbo.eu/s/KI2) don't find any alt_name for this value
[taginfo](https://taginfo.openstreetmap.org/search?q=%3DFrance+m%C3%A9tropolitaine) only found one name/name:fr/wikipedia not linked to relation France

**Comment by lonvia** [comment]
The names only get deleted when the relation gets updated. In the meantime the label change was reverted: https://www.openstreetmap.org/changeset/72226819

Closing as a data issue.
