### ISSUE TITLE
France - saisie nom de place ** France _ enter place name

### ISSUE THREAD

**Issue by RV0-github** [openstreetmap/Nominatim#1423]
Bonjour
Quand je saisie "place Edouard Herriot" au lieu de "place du Président Edouard Herriot"
OSM affiche "aucun résultat"
Pour réaliser la capture d'écran jointe je me suis déplacé manuellement jusqu'à la place en question.
je n'attend pas de réponse, je signale un disfonctionnement
****************************************
Hello
When I enter "Place Edouard Herriot" instead of "Place du Président Edouard Herriot"
OSM displays "no results"
To make the attached screenshot I moved manually to the place in question
I'm not waiting for an answer, I'm reporting a malfunction
![Paris_place Herriot](https://user-images.githubusercontent.com/52787649/61051921-8a54d180-a3ea-11e9-9bff-42ca2674f279.JPG)

**Comment by mtmail** [comment]
It's a know limitation of Nominatim, it can't find places if a word is missing. Tracked in https://github.com/openstreetmap/Nominatim/issues/94
