### ISSUE TITLE
Nominatim update fail

### ISSUE THREAD

**Issue by uilll** [openstreetmap/Nominatim#1424]
Hello everyone, when I try to update my server I get this error. I've already made other updates, but now this error appears.

`./utils/update.php --import-osmosis --no-npi
` 
response

````
WARNING: resetting cache memory to 495
/home/nominatim/Nominatim/osm2pgsql/osm2pgsql -klas -C 495 -O gazetteer -d nominatim -P 5432 /home/nominatim/Nominatim/data/osmosischange.osc
osm2pgsql SVN version 0.85.0 (64bit id space)

Using projection SRS 4326 (Latlong)
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=495MB, maxblocks=63360*8192, allocation method=11
Mid: pgsql, scale=10000000 cache=495
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /home/nominatim/Nominatim/data/osmosischange.osc
Entity: line 1696: parser error : AttValue: ' expected
Entity: line 1696: parser error : attributes construct error
Entity: line 1696: parser error : Couldn't find end of Start Tag node
/home/nominatim/Nominatim/data/osmosischange.osc : failed to parse
Error occurred, cleaning up
Error: 1
```

Can anyone help me on this error?

**Comment by lonvia** [comment]
What version of Nominatim is this?

**Comment by uilll** [comment]
3.3.0

**Comment by mtmail** [comment]
What was the Nominatim version before? Nominatim 3.3.0 comes with osm2pgsql version 0.96.0. Did you run the compile step (recreating the build directory and running `cmake` and `make`) and database migrations?

**Comment by uilll** [comment]
Sorry, the version is 2.3, I followed this tutorial https://gist.github.com/malkitsingh/737ea34abec5b079a84dd39e3b0dc2d2

**Comment by mtmail** [comment]
Nominatim 2.3 is from year 2014 http://nominatim.org/release-history/ Too many things have changed to list here, the database schema between version 2.x and 3.x is so different a complete reimport of the database is needed. It's a big step to version 3.

It's best to use the instructions on http://nominatim.org/release-docs/latest/ On the bottom left you will see links to specific instructions for Ubuntu 16 and 18. If you're familiar with Docker there's also the separate project https://github.com/mediagis/nominatim-docker

**Comment by uilll** [comment]
Ok, I Will upgrade to 3.x. Thanks for help!
