### ISSUE TITLE
ubuntu fresh apache / nginx installation

### ISSUE THREAD

**Issue by jdvjdv82** [openstreetmap/Nominatim#1425]
hello

you are using composer at
`composer global require "squizlabs/php_codesniffer=*"
    sudo ln -s ~/.config/composer/vendor/bin/phpcs /usr/bin/`

,but the composer does not have to be installed, since it is missing in apt-get install part before

please also check this
`Alias /nominatim $USERHOME/build/website`
since 
`$USERHOME = /srv/nominatim`
then you are missing Nominatim directory in between
so it should be
`Alias /nominatim $USERHOME/Nominatim/build/website`

thank you

**Comment by mtmail** [comment]
`phpcs` and thus PHP `composer` is optional, only needed if you want to run the test suite. We should make that more clear.

Which page URL were you looking at? Or did you look at the `vagrant/Install-on-...` scripts directly? Did you install a stable release http://nominatim.org/release-history/ or the latest master of Nominatim?

**Comment by jdvjdv82** [comment]
hi,

i followed ubuntu 18.04 guide from
[https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/](url)

so i have version from this link
`git clone --recursive git://github.com/openstreetmap/Nominatim.git`

**Comment by mtmail** [comment]
Thanks a lot. Our documentation used to be split on multiple domains (wiki vs nominatim.org) so it's sometimes not clear where users checked.

I added a pull request https://github.com/openstreetmap/Nominatim/pull/1428 to point out the phpunit packages and php composer are optional.

The `Alias /nominatim` looks alright though. Inside the script (.sh files) it assumes you install as user `vagrant` inside a Vagrant virtual machine. There the build directory is not a subdirectory of the Nominatim directory. When the script is transformed to a webpage https://github.com/openstreetmap/Nominatim/issues/url the `##DOCS` instructions overwrite anything previous in the line and it assumes you install as user `nominatim`, there the build directory is a subdirectory of the Nominatim directory.
