### ISSUE TITLE
ubuntu 18.04 import error

### ISSUE THREAD

**Issue by kvadom** [openstreetmap/Nominatim#1431]
Hi. I'm trying to install nominatim on my ubuntu 18.04 regarding to next manual
https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/

During data import [regarding to that manual](https://nominatim.org/release-docs/latest/admin/Import-and-Update/) we catch an error:
```
./utils/setup.php --osm-file /srv/nominatim/nominatimdata/ukraine-latest.osm.pbf --all --osm2pgsql-cache 28000 2>&1 | tee setup.log

PHP Warning:  Use of undefined constant CONST_BasePath - assumed 'CONST_BasePath' (this will throw an Error in a future version of PHP) in /srv/nominatim/Nominatim/utils/setup.php on line 3
PHP Warning:  require_once(CONST_BasePath/lib/init-cmd.php): failed to open stream: No such file or directory in /srv/nominatim/Nominatim/utils/setup.php on line 3
PHP Fatal error:  require_once(): Failed opening required 'CONST_BasePath/lib/init-cmd.php' (include_path='.:/usr/share/php') in /srv/nominatim/Nominatim/utils/setup.php on line 3
```
Thanks for the quick response!

**Comment by mtmail** [comment]
> `/srv/nominatim/Nominatim/utils/setup.php`

You should change into the build directory first, then `./utils/setup.php`. It's either `/srv/nominatim/Nominatim/build` or `/srv/nominatim/build`, I think the former in the documentation.

**Comment by lonvia** [comment]
Given that the file is not executable and doesn't have a shebang, I think we can close this as user error rather than documentation error.

**Comment by monkeytroy** [comment]
This docs say run this command:  `./utils/setup.php --osm-file <data file> --all 2>&1 | tee setup.log`

If it's not executable how is that user error?   What is the correct way to run this?   

Trying:  `php ./utils/setup.php --osm-file <data file> --all 2>&1 | tee setup.log`

Does then run the setup.php code, but I get the same error as the original.

**Comment by mtmail** [comment]
@monkeytroy Open a new issue with a new complete question. Add a URL when talking about "This docs".
