### ISSUE TITLE
Index of /nominatim

### ISSUE THREAD

**Issue by saydulk** [openstreetmap/Nominatim#1435]
I am using Centos 7 Linux. I have install nominatim on /var/www/html but it shows Index of /nominatim

please help 

![Screenshot from 2019-07-22 14-28-33](https://user-images.githubusercontent.com/1058663/61617741-2c977380-ac8d-11e9-8bdf-4771504ffbd9.png)
![Screenshot from 2019-07-22 14-28-41](https://user-images.githubusercontent.com/1058663/61617743-2d300a00-ac8d-11e9-8d2c-8ffab3d0311a.png)
![Screenshot from 2019-07-22 14-28-51](https://user-images.githubusercontent.com/1058663/61617744-2d300a00-ac8d-11e9-9002-20b547164ef0.png)

**Comment by mtmail** [comment]
The `build` directory looks empty. Which installation instructions did you follow?

Please post the relevant section of the Apache configuration. While http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/ sets up `Alias` nowhere does it say the files need to be `/var/www/html`

Did the database import finish without errors? What does the database query `SELECT indexed_status, count(*) FROM placex GROUP BY indexed_status;` print?

**Comment by saydulk** [comment]
Yes I have used this link http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/

http://144.202.6.242/Nominatim/
http://144.202.6.242/nominatim/

![Screenshot from 2019-07-22 18-24-29](https://user-images.githubusercontent.com/1058663/61632183-0930f080-acae-11e9-85ac-584deb5e56d8.png)

**Comment by mtmail** [comment]
User didn't answer questions.
