### ISSUE TITLE
FR location_postcode error

### ISSUE THREAD

**Issue by drzraf** [openstreetmap/Nominatim#1437]
`https://nominatim.openstreetmap.org/search?country=fr&postalcode=54600&addressdetails=1&debug=1`

- Actual: _Liverdun_: https://www.openstreetmap.org/relation/113073
- Expected: _Villers-lès-Nancy_: https://www.openstreetmap.org/relation/52397

But **none** of these two entries got their (currently correct) postcodes recently changed inside OSM.

From the code, the value inside `location_postcode` (which here is apparently wrong) is loaded straight from `placex` table.

- Could it be that https://github.com/openstreetmap/Nominatim/blob/master/lib/setup/SetupClass.php#L550 introduced this error?
- Or is `placex` wrong in the first place? 
- Is there many more cases like this?

**Comment by mtmail** [comment]
Yes, that's the logic. Nominatim also has a nightly update (`sql/update-postcodes.sql`).

I found https://www.openstreetmap.org/node/3366032784 using Overpass (https://overpass-turbo.eu/s/KZE) which is far off the city Nancy and likely causes the center point calculation to be off.

We had a couple of similar reports in the past, multiple countries. We don't have a good automated way to report these to local OSM mappers without creating (yet another) OSM validation tool.

**Comment by mtmail** [comment]
![image](https://user-images.githubusercontent.com/3727288/61735292-f5f05480-ad83-11e9-90e4-f09f591d337c.png)

**Comment by drzraf** [comment]
A tool reporting non-contiguous postcode would be helpful. In mainland it's probably very unfrequent and the fact that a single node having a wrong postcode affect the accuracy of nominatim for a whole city is a big dangerous.

**Comment by lonvia** [comment]
Closing as data error.
