### ISSUE TITLE
Wrong address of buiding

### ISSUE THREAD

**Issue by datnguyen0126** [openstreetmap/Nominatim#1439]
The coordinates Latitude: 16.070256999999998, Longitude: 108.2206801 is mgm technology partner VietNam building. It show correct house number and county but the road name is "Phan Châu Trinh", not "Phan Đình Phùng" as xml result returned.

**Comment by lonvia** [comment]
This is a data issue. The `addr:street` tag must be exactly the same as the `name` of the street it refers to (i.e with Đường) . Please [fix it in OpenStreetMap](https://www.openstreetmap.org/fixthemap).
