### ISSUE TITLE
Uppercase sz (ẞ) does not get recognized as such

### ISSUE THREAD

**Issue by hellow554** [openstreetmap/Nominatim#1440]
In germany, we have a lot of streets ending with *-straße* (which is street btw).

So, let's take for example the "Felstraße" (which is also very common in germany with a few hundred cities who have such street).

Now, nominatim is kind of case insensitive, e.g. it doesn't matter if I use [feldweg](https://nominatim.openstreetmap.org/search.php?q=feldweg) or [FELDWEG](https://nominatim.openstreetmap.org/search.php?q=FELDWEG). But if I use the [capital ẞ](https://en.wikipedia.org/wiki/Capital_%E1%BA%9E) nominatim can't find [FELDSTRAẞE](https://nominatim.openstreetmap.org/search.php?q=FELDSTRAẞE) anymore (but [FELDSTRAßE](https://nominatim.openstreetmap.org/search.php?q=FELDSTRAßE) of course works ;) )

**Comment by mtmail** [comment]
Thanks for the wikipedia link, it lists the Unicode. Adding this to our 'transliteration' list. We currently use a static list and that hasn't been updated in a while.

**Comment by lonvia** [comment]
Oh dear, that's horrible. The obvious proper solution is to avoid this character altogether. ;)

On a more serious note: this will get fixed with #1279 only. Closing here as a duplicate.
