### ISSUE TITLE
Building Polygon Box Co-Ordinate not found

### ISSUE THREAD

**Issue by cgvaghela** [openstreetmap/Nominatim#1441]
I Have fire this address - 605 Murl Drive, irving TX, USA
But not polygon point.
That is House but in OSM it's display as street that's why polygon not display.

Can you help me with this please
1) **605 Murl Drive, irving TX, USA**
2) 2120 Glenhaven Drive, Lewisville, TX, USA

I Need roof measurement that's why I must need polygon point.

Thank You in advance

**Comment by lonvia** [comment]
Nominatim is built on OpenStreetMap data. If you need building outlines, please download the appropriate extract of OpenStreetMap data and extract it from there. Nominatim is the wrong tool for you.
