### ISSUE TITLE
Incorrect Street Name

### ISSUE THREAD

**Issue by fishcharlie** [openstreetmap/Nominatim#1442]
When making a GET request to https://nominatim.openstreetmap.org/search/KDEN?format=json, the display name includes `Terminal West Commercial Vehicles` as the street name it looks like. If you look at https://www.openstreetmap.org/relation/112192, the `addr:street` tag is `Peña Blvd`.

Any reason why the discrepancy? Seems like it could be an issue with the data itself on OSM, but not quite sure how to fix it so Nominatim returns correct data here.

**Comment by lonvia** [comment]
That's a fallout from #1389 which now makes the result worse for this example. The centroid is obviously not better than the point-on-surface.

**Comment by fishcharlie** [comment]
@lonvia Looks like this was fixed! https://www.openstreetmap.org/search?query=Denver%20International%20Airport#map=12/39.8491/-104.6960 is now displaying `Denver International Airport, 8500, Peña Boulevard, Denver, Denver County, Colorado, 80249, USA`.

Thanks so much!
