### ISSUE TITLE
creating the db error: no data

### ISSUE THREAD

**Issue by kostjaz** [openstreetmap/Nominatim#1446]
Hello!
I'm trying to create DB on mu ubuntu 18.04 server, and I got a strange problem and I have no idea that to do with it :-(

/srv/nominatim/build/utils/setup.php --osm-file /srv/pbf/russia-latest.osm.pbf --all --osm2pgsql-cache 7000 2>&1 | tee setup.log

2019-07-29 15:55:22 == module path: /srv/nominatim/build/module
2019-07-29 15:55:22 == Create DB
2019-07-29 15:55:25 == Setup DB
Postgres version found: 10
Postgis version found: 2.4
2019-07-29 15:55:34 == WARNING: optional external GB postcode table file (/srv/nominatim/data/gb_postcode_data.sql.gz) not found. Skipping.
2019-07-29 15:55:34 == WARNING: optional external US postcode table file (/srv/nominatim/data/us_postcode_data.sql.gz) not found. Skipping.
2019-07-29 15:55:34 == Import data
osm2pgsql version 0.96.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=7000MB, maxblocks=112000*65536, allocation method=11
Mid: pgsql, cache=7000
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Parsing gazetteer style file '/srv/nominatim/settings/import-full.style'.
Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping

Reading in file: /srv/pbf/russia-latest.osm.pbf
Using PBF parser.
Processing: Node(304870k 2193.3k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Killed
ERROR: No Data
string(7) "No Data"

**Comment by kostjaz** [comment]
Sorry friends, that looks like a server problem, not a Nominatim issue.
I tried to create the DB with a small region, not a whole Russia, and it worked perfect.

**Comment by lonvia** [comment]
The relevant output is `Killed` in the 3rd lowest line. You've run out of memory. You'll find a couple of closed issues here and in the osm2pgsql repo with hints about that.
