### ISSUE TITLE
Nominatim Update

### ISSUE THREAD

**Issue by oepscina** [openstreetmap/Nominatim#1447]
HI,

When I do update.php --init-updates
it returns, ERROR: HTTP Error 404: Not Found
days ago I ruun the same without this problem...

in mi local.php I have:

 @define('CONST_Pyosmium_Binary', '/home/develop/.local/bin/pyosmium-get-changes');
 @define('CONST_Replication_Url', 'https://download.geofabrik.de/north-america/mexico-updates/');
@define('CONST_Replication_Update_Interval', '86400');
@define('CONST_Replication_Recheck_Interval', '900');

When I run update.php --check-for-updates...
New data available (2322 => 2326).

How Can I fix This issue?

**Comment by lonvia** [comment]
As said in about half a dozen other issues already: this message can be ignored. (And, yes, it was there already 'days ago' unless you had a major update of pyosmium in between.)
