### ISSUE TITLE
Reverse Geocode Coords in roads

### ISSUE THREAD

**Issue by oepscina** [openstreetmap/Nominatim#1448]
HI,

Im getting this reverse response in some cases...

 [place_id] => 1719107
    [licence] => Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright
    [osm_type] => way
    [osm_id] => 625631355
    [lat] => 26.0255235994988
    [lon] => -98.1729720376263
    [display_name] => 26.0256348,-98.1729336, Nuevo Santana, Reynosa, Tamaulipas, 88780, México
    [address] => Array
        (
            [road] => 26.0256348,-98.1729336
            [neighbourhood] => Nuevo Santana
            [county] => Reynosa
            [state] => Tamaulipas
            [postcode] => 88780
            [country] => México
            [country_code] => mx
        )

    [boundingbox] => Array
        (
            [0] => 26.0255
            [1] => 26.0378777
            [2] => -98.1729754
            [3] => -98.1711544
        )

)

In the address road puts some coords...

How can fix this?

**Comment by mtmail** [comment]
Somebody gave the road this (wrong) name. https://www.openstreetmap.org/way/625631355 You can edit it on OpenStreetMap https://www.openstreetmap.org/fixthemap Closing as data issue.
