### ISSUE TITLE
Not get housenumber with zoom 18?

### ISSUE THREAD

**Issue by theAlinux** [openstreetmap/Nominatim#1455]
i did items in documentation, 

http://35.246.82.247/search?q=broad+lane&format=json&addressdetails=1&limit=10&countriescode=gb&zoom=18

but not get housenumber?

**Comment by mtmail** [comment]
https://en.wikipedia.org/wiki/Broad_Lane is a place (villiage). You didn't search for a house number so the result is relevant enough.

**Comment by theAlinux** [comment]
but i want to i whatever write to get housenumber? what will i do?

**Comment by mtmail** [comment]
If you search Nominatim will tell you where the address is located. It will not add new housenumbers (no housenumber that isn't already in the query) https://nominatim.openstreetmap.org/search?q=135+pilkington+avenue,+birmingham&format=json&addressdetails=1

**Comment by lonvia** [comment]
The `zoom` parameter can only be used for reverse. There is no equivalent for search.
