### ISSUE TITLE
State is abbreviated when used in Google Sheets.

### ISSUE THREAD

**Issue by GAZ082** [openstreetmap/Nominatim#1456]
Hi! This request:

`https://nominatim.openstreetmap.org/reverse?format=json&lat=-36.081370&lon=-69.368744&zoom=10&addressdetails=1`

When run with the URL in a browser the data is returned fine. The "state" is Mendoza. But for some reason when I use this in a Google Sheets script instead of Mendoza it returns "Mza." an abbreviation. This is not for all states just for this case in particular (I'm using just a few in my dataset).

How can avoid this?

Thanks!

**Comment by mtmail** [comment]
The browser adds an https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language HTTP header, with Argentina either `es` or `es-ar` or similar.

Scripts don't set that header. You can add `&accept-language=es` to the URL.

```
curl 'https://nominatim.openstreetmap.org/reverse?format=json&lat=-36.081370&lon=-69.368744&zoom=10&addressdetails=1&accept-language=es' | jq '.address'

{
  "county": "Distrito Río Grande",
  "state_district": "Departamento Malargüe",
  "state": "Mendoza",
  "country": "Argentina",
  "country_code": "ar"
}
```

**Comment by GAZ082** [comment]
@mtmail thanks a lot!
