### ISSUE TITLE
Search query finds toilets, but not specific restaurant

### ISSUE THREAD

**Issue by carstenhag** [openstreetmap/Nominatim#1457]
Hello, so I tried searching for this restaurant: https://nominatim.openstreetmap.org/details.php?place_id=25118499.

* los baños sunshine: Works, but the "sunshine" part is new on their name and nobody will search with this term included.

* los baños: Finds cities and other things. Seems okay to me, as there is no more context.

* los baños Denia: This one *should* find the restaurant, but it sadly doesn't. It finds toilet amenities (baño means toilet, bath or bathroom).

* los baños sunshine denia: Doesn't find anything, sadly.

**Comment by carstenhag** [comment]
On OSM's ID only toilets are showing up on the worldwide search. The restaurant does not show up. Searching for "los baños sunshine"

**Comment by mtmail** [comment]
Nominatim has a list of "special phrases" to look for points of interest. https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/ES That's how "banos <address>" will return any place tagged as toilet nearby.

I agree the "bar" part of the name is something users wouldn't search for. Nominatim only finds places by their full name(s). If the restaurant has another name people use it makes sense to add another tag, e.g. `local_name`. Or use `name` and have the longer name be the `official_name`.

**Comment by carstenhag** [comment]
Thanks @mtmail, I've seen on the wiki that I can also use `short_name`, which I have now tagged. It finds the place just right now. Thanks!
