### ISSUE TITLE
 Database server failed to load /srv/nominatim/Nominatim/build/module/nominatim.so module

### ISSUE THREAD

**Issue by lsxlsx** [openstreetmap/Nominatim#1458]
New installation on Ubuntu 18. Cant import osm file

osm@osm:/srv/nominatim/Nominatim/build$ ./utils/setup.php --osm-file /osm_maps/edit.osm --all  2>&1 | tee setup.log
2019-08-10 01:24:18 == module path: /srv/nominatim/Nominatim/build/module
2019-08-10 01:24:18 == Create DB
2019-08-10 01:24:19 == Setup DB
Postgres version found: 10
Postgis version found: 2.4
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /srv/nominatim/Nominatim/build/module/nominatim.so module

  thrown in /srv/nominatim/Nominatim/lib/DB.php on line 61
osm@osm:/srv/nominatim/Nominatim/build$ ls -l /srv/nominatim/Nominatim/build/module/nominatim.so
-rwxrwxrwx 1 osm osm 297992 Aug 10 00:19 /srv/nominatim/Nominatim/build/module/nominatim.so
Please guide what to do?

**Comment by mtmail** [comment]
Is the database on the same server? If it's remote the the file needs to exist on that server. Can the database user (`postgres`) access the file, that needs execute permissions on the parent directories?

**Comment by lsxlsx** [comment]
Yes, it was permissions problem. Thanks!

**Comment by killer3dfx** [comment]
Hello, i still have the issue but in Centos, can you help me?

**Comment by mtmail** [comment]
@killer3dfx http://nominatim.org/release-docs/latest/admin/Faq/#website-reports-could-not-load-library-nominatimso If that fails open a new issue

**Comment by mantesat** [comment]
Same thing occurred during afresh installation on Fedora 31. DB is postgresql 9.6. Any insights?

**Comment by killer3dfx** [comment]
Had to switch to ubuntu in my case.

Samir Lissa
