### ISSUE TITLE
US TIGER Data Is Different Between My Instance and Official Instance

### ISSUE THREAD

**Issue by nettookit-geo** [openstreetmap/Nominatim#1460]
I have imported TIGER data according to the data importing instruction [Nominatim Data Import](https://nominatim.org/release-docs/latest/admin/Import-and-Update/), TIGER data is  downloaded from link: https://nominatim.org/data/tiger2018-nominatim-preprocessed.tar.gz, but I find there are some differences between the TIGER data I have imported from above source and the official instance after the import is done.

For street: way 481601152

location_property_tiger in my instance has data as: 
 startnumber | endnumber | interpolationtype | postcode 
-------------+-----------+-------------------+----------
        1201 |      1299 | all               | 17404

But when I was checking the Nominatim Official instance using debug mode, https://nominatim.openstreetmap.org/search.php?q=1101+Carlisle+Rd%2C+York%2C+PA+17404&debug=1, I find query: 
"SELECT place_id FROM location_property_tiger WHERE parent_place_id in (70590540,195408584,120532804,178826158,189394517,89550691,195389624,179789242,188810131,178826454,195026392,189395109,197318949,120104587,188458996,189292611,178828782,267495624,195531128,179336960,119175707,89132370,267495626,267495627,136088742,196752504,198099271,179335629,71278412,179199665,69919702,70076602,196752351,198099229,70600086,153337676,70756863,69919613,70600011,70588763) and (interpolationtype='odd' or interpolationtype='all') and 1101>=startnumber and 1101<=endnumber"

returns back result as " Ids from Tiger table:  '228509371'"
Final result for this query is as: 
Post-filter results:  0 => 'osm_type' => 'T'
                           'osm_id' => 481601152
                           'class' => 'place'
                           'type' => 'house'
                           'admin_level' => 
                           'rank_search' => 30
                           'rank_address' => 30
                           'place_id' => 228509371
                           'parent_place_id' => 178828782
                           'housenumber' => 1101
                           'country_code' => 'us'
                           'langaddress' => '1101, Carlisle Road, Holly Heights, West Manchester Township, York County, Pennsylvania, 17404, USA'
                           'placename' => 
                           'ref' => 
                           'lon' => '-76.767525'
                           'lat' => '39.963913'
                           'importance' => 0.421
                           'addressimportance' => '7.85696242021766'
                           'extra_place' => 
                           'addresstype' => 'place'
                           'aBoundingBox' => 0 => '39.963863'
                                             1 => '39.963963'
                                             2 => '-76.767575'
                                             3 => '-76.767475'
                           'label' => 'House'
                           'name' => '1101, Carlisle Road, Holly Heights, West Manchester Township, York County, Pennsylvania, 17404, USA'
                           'foundorder' => -0.76979624202177

Which seems like the TIGER data in Nominatim Official instance is different from my instance. Does anyone else have the same issue? Is there anything I can do to avoid the inconsistency on TIGER data?

**Comment by lonvia** [comment]
What is the result when you search for '1101, Carlisle Road, York County, PA' on your instance?

The TIGER data is matched against the current state of the database on import. The matches might differ slightly depending on when exactly the import happened even when the TIGER data imported is exactly the same. The data on the openstreetmap.org instance has been imported quite a while ago, so it is only natural that you see differences when you import now. In the end you should get a very similar search result even when the street match was against a different OSM way.

**Comment by nettookit-geo** [comment]
My result is as followed which does not have TIGER interpolation result:

[{"place_id":192022327,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":603480756,"boundingbox":["39.9620053","39.963887","-76.767325","-76.7623153"],"lat":"39.9631504","lon":"-76.765117","display_name":"Carlisle Road, York, York County, Pennsylvania, 17404, USA","class":"highway","type":"primary","importance":0.42000000000000004,"geojson":{"type":"LineString","coordinates":[[-76.7623153,39.9620053],[-76.762526,39.9620773],[-76.7629015,39.9622088],[-76.7633092,39.9623815],[-76.7642265,39.9627557],[-76.765117,39.9631504],[-76.7654604,39.9632861],[-76.7659432,39.9634629],[-76.7671728,39.9638403],[-76.767325,39.963887]]}},{"place_id":191249641,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":598037724,"boundingbox":["39.9702712","39.9742297","-76.7872286","-76.7816126"],"lat":"39.9729026","lon":"-76.7850087","display_name":"Carlisle Road, Fairway, Shiloh, York County, Pennsylvania, 17404, USA","class":"highway","type":"primary","importance":0.41000000000000003,"geojson":{"type":"LineString","coordinates":[[-76.7816126,39.9702712],[-76.7820065,39.9706816],[-76.7835068,39.9719365],[-76.7850087,39.9729026],[-76.7872286,39.9742297]]}},{"place_id":207471544,"licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":598037722,"boundingbox":["39.969598","39.9698675","-76.7812189","-76.7808596"],"lat":"39.9696458","lon":"-76.7809634","display_name":"Carlisle Road, Holly Heights, West Manchester Township, York County, Pennsylvania, 17404, USA","class":"highway","type":"primary","importance":0.41000000000000003,"geojson":{"type":"LineString","coordinates":[[-76.7812189,39.9698675],[-76.7809634,39.9696458],[-76.7808596,39.969598]]}}]

I imported TIGER data about two weeks ago using Nominatim 3.3.0 data importing script.

**Comment by lonvia** [comment]
Have you enabled TIGER in your local configuration (`@define('CONST_Use_US_Tiger_Data', true);` in your settings/local.php)? Have you rerun the function import (`./utils/setup.php --create-functions --enable-diff-updates --create-partition-functions`) _after_ changing the configuration option?

If yes, then check if the TIGER data is in your table:
`SELECT p.osm_type, p.osm_id, p.name->'name', t.* FROM location_property_tiger t, placex p WHERE t.startnumber = 1101 and t.endnumber = 1199 and t.interpolationtype = 'odd' and t.partition = 2 and t.postcode = '17404' and t.parent_place_id = p.place_id;`

That should give you a couple of results and one of them should have 'Carlisle Road' in the name.

**Comment by nettookit-geo** [comment]
Yes, I have enabled TIGER in my local configuration and reran the function import.

There is no result have 'Carlisle Road'  in the name:

osm_type |  osm_id   |     street_name      
----------+-----------+----------------------
 W        | 104402667 | West Princess Street
 W        | 187612006 | Greenbriar Road
 W        |   6679492 | Birch Alley
 W        |   6720321 | Sarazen Way
 W        |   6734134 | Burgard Street
 W        |   6680312 | Drexel Street
 W        |   6702422 | Gunnison Road
 W        |   6679729 | West Poplar Street
 W        |   6718587 | Conewago Avenue
 W        |   6712218 | Laurel Drive
 W        |   6741090 | Paul Alley
 W        | 481897475 | West King Street
 W        |   6719743 | Olson Street
 W        | 104402672 | West College Avenue
 W        |   6730430 | Fireside Court
 W        | 610808047 | West Locust Street
 W        |   6723646 | Priority Road
 W        |   6729999 | Fairlane Drive
 W        |   6675280 | Continental Road
 W        |   6741027 | Mill Creek Road
(20 rows)

And I tried:
`SELECT p.osm_type, p.osm_id, p.name->'name' as name, t.startnumber, t.endnumber, t.interpolationtype  FROM location_property_tiger t, placex p WHERE t.postcode = '17404' and t.parent_place_id = p.place_id and p.name->'name' = 'Carlisle Road';`

 osm_type |  osm_id   |     name      | startnumber | endnumber | interpolationtype 
----------+-----------+---------------+-------------+-----------+-------------------
 W        | 700727144 | Carlisle Road |        1200 |      1298 | all
 W        | 254183109 | Carlisle Road |         700 |       798 | all
 W        | 481601152 | Carlisle Road |        1201 |      1299 | all
 W        | 187602673 | Carlisle Road |        1504 |      1598 | all
 W        | 187602672 | Carlisle Road |         900 |       914 | all
 W        | 482141583 | Carlisle Road |        2833 |      2899 | all
 W        | 187602672 | Carlisle Road |         916 |       998 | all
 W        |  53512650 | Carlisle Road |         837 |       899 | all
 W        | 187602672 | Carlisle Road |        1016 |      1094 | all
 W        | 187602673 | Carlisle Road |        1600 |      1678 | even
 W        | 481602140 | Carlisle Road |        1300 |      1356 | all
 W        | 598037722 | Carlisle Road |        1680 |      1698 | even
 W        | 187602672 | Carlisle Road |         836 |       898 | all
 W        | 603480756 | Carlisle Road |         915 |      1099 | all
 W        |  53512650 | Carlisle Road |         909 |       913 | all
 W        |  53512650 | Carlisle Road |         801 |       835 | all
(16 rows)

No TIGER street segment that have startnumber as 1101 and endnumber as 1199.

**Comment by lonvia** [comment]
So the difference is that nominatim.org is using TIGER data from 2016 which still has the house number. The 2018 data suspiciously looks like it has a typo in there:

```
SELECT tiger_line_import(ST_GeomFromText('LINESTRING(-76.766254 39.963640,-76.765976 39.963543,-76.765531 39.963406,-76.765240 39.963292,-76.764969 39.963185,-76.764599 39.963024,-76.764027 39.962775,-7
6.763419 39.962525,-76.763145 39.962409,-76.762920 39.962320,-76.762671 39.962234,-76.762410 39.962147)',4326), '1099', '915', 'all', 'Carlisle Rd', 'York, PA', '17404');
```

i.e. a housenumber range from 1099 to 915.

There is nothing we can do about that. You can use the 2016 data but it is likely worse in other places.

**Comment by mtmail** [comment]
Tiger 2019 (https://github.com/openstreetmap/Nominatim/pull/1474) has 

```
'801', '835', 'all', 'Carlisle Rd', 'York, PA', '17404'
'826', '700', 'all', 'Carlisle Rd', 'York, PA', '17404'
'836', '898', 'all', 'Carlisle Rd', 'York, PA', '17404'
'899', '837', 'all', 'Carlisle Rd', 'York, PA', '17404'
'900', '914', 'all', 'Carlisle Rd', 'York, PA', '17404'
'916', '998', 'all', 'Carlisle Rd', 'York, PA', '17404'
'1016', '1094', 'all', 'Carlisle Rd', 'York, PA', '17404'
'1199', '903', 'all', 'Carlisle Rd', 'York, PA', '17404'
'1200', '1298', 'all', 'Carlisle Rd', 'York, PA', '17404'
'1299', '1201', 'all', 'Carlisle Rd', 'York, PA', '17404'
'1504', '1598', 'all', 'Carlisle Rd', 'York, PA', '17404'
'1600', '1678', 'even', 'Carlisle Rd', 'York, PA', '17404'
'1698', '1680', 'all', 'Carlisle Rd', 'York, PA', '17404'
'2833', '2899', 'all', 'Carlisle Rd', 'York, PA', '17404'
```

**Comment by lonvia** [comment]
Now I wonder if the assumption that start < end is wrong.

**Comment by mtmail** [comment]
@lonvia We ensure `startnumber` < `endnumber` in https://github.com/openstreetmap/Nominatim/blob/master/sql/tiger_import_start.sql#L21 during import. At least I can't find a `startnumber` > `endnumber` in my database.

**Comment by nettookit-geo** [comment]
@tarnh That's the query we got from our user, maybe Nominatim should think about how to be more flexible like other geocoding providers.

**Comment by tarnh** [comment]
@nettookit-geo Which geocoder do you use to serve your API?

The underlying problem is that the street is mapped as "East Duane Avenue" (→ E Duane Avenue) in OSM with no alternative names.

**Comment by nettookit-geo** [comment]
We create our own geocoder which blends open-source (Nominatim, PostGIS Geocoder) and open-data (OpenAddresses) solutions together with our own address parser. Check us if interested: [NetToolKit Geo](https://www.nettoolkit.com/geo/about)

**Comment by nettookit-geo** [comment]
We create our own geocoder which blends open-source and open-data solutions together with our own address parser, check out our websit for more information: [NetToolKit Geo](https://www.nettoolkit.com/geo/about)

**Comment by mtmail** [comment]
Both of you know the Duane Avenue query is from the netoolkit homepage and not the TIGER related query this issue is about. That’s offtopic. Use their homepage/contact-us page to discuss that further.
