### ISSUE TITLE
Geber appears incorrectly in address

### ISSUE THREAD

**Issue by markuskallander** [openstreetmap/Nominatim#1461]
Geber appears in the address here and I think it should not. I think Geber is a very small area not really close or related to this area. I reported in OpenStreetMap but was directed here. Here is the URL with the incorrect address: https://nominatim.openstreetmap.org/reverse.php?format=html&lat=59.260516137974605&lon=18.12131524085999&zoom=18.

**Comment by lonvia** [comment]
Geber is mapped as a [place=hamlet](https://www.openstreetmap.org/node/1958791443). Is that right? Doesn't look like there is anything there in that area.

**Comment by markuskallander** [comment]
Yes, I think the categorization is correct, however, I am not 100% sure where it is.

**Comment by lonvia** [comment]
See the provided link: https://www.openstreetmap.org/node/1958791443 On the satellite it looks like a garden plot.

**Comment by lonvia** [comment]
This seems to have solved itself in the data.
