### ISSUE TITLE
Location Name wrong (Via Ariosto, Cagliari, Italy)

### ISSUE THREAD

**Issue by monicacamba** [openstreetmap/Nominatim#1464]
As you can see on google maps
https://www.google.it/maps/place/39%C2%B013'30.9%22N+9%C2%B007'37.5%22E/@39.2248797,9.1262887,19.5z/data=!4m14!1m7!3m6!1s0x12e7346c5c9ede73:0xfd4d58e57b71aa4!2sPiazza+Michelangelo,+Cagliari+CA!3b1!8m2!3d39.2249853!4d9.1268513!3m5!1s0x0:0x0!7e2!8m2!3d39.225244!4d9.1270802
in Cagliari there is a square named "Piazza Michelangelo", and of course this name refers to all the four streets delimiting it.
if you look at the result of the following query
https://nominatim.openstreetmap.org/search.php?q=piazza+michelangelo&polygon_geojson=1&viewbox=
you see the following names: via michelangelo, via ariosto in two of the square sides

**Comment by lonvia** [comment]
That's a data issue that needs to be fixed directly in OpenStreetMap. See [OSM Fix the map](https://www.openstreetmap.org/fixthemap) for more info.
