### ISSUE TITLE
Wrong street name when clicking Show address on a street

### ISSUE THREAD

**Issue by markuskallander** [openstreetmap/Nominatim#1467]
When clicking Show address on "Maria Röhls väg" (street name) it shows "Vera Nilssons väg" in the address: https://www.openstreetmap.org/search?whereami=1&query=59.26068%2C18.12171#map=19/59.26068/18.12171. If I zoom out a bit it shows the correct street name.

**Comment by lonvia** [comment]
It shows you the address of [Kaffreepet](https://www.openstreetmap.org/way/713494469) which is exactly under the given position. Looks perfectly correct to me.

**Comment by lonvia** [comment]
NB: Please have a look at the [this FAQ](http://nominatim.org/release-docs/latest/api/Faq/#2-when-doing-reverse-search-the-address-details-have-parts-that-dont-contain-the-point-i-was-looking-up) before posting further "bugs".

**Comment by mtmail** [comment]
The https://nominatim.openstreetmap.org/reverse.php?format=html&lat=59.26068&lon=18.12171&zoom=21 interface is a bit more helpful compared to openstreetmap.org. The small red circle shows the search position, the larger blue circle the result.
