### ISSUE TITLE
Address right but wrong city in specific coordinate.

### ISSUE THREAD

**Issue by kevin-argus** [openstreetmap/Nominatim#1468]
Hi,
on Lat: -36.816940 Lon: 174.750290 we get:
Auckland Northern Motorway, Northcote Point, Kaipatiki, Auckland, 0627
which is pretty much right except "Kaipatiki" is not the right city, it should be Auckland.
URL Request:
https://nominatim.openstreetmap.org/reverse?lat=-36.81694&lon=174.75029&format=json&zoom=30
JSON response here:

{
  "place_id": 102532481,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 119983818,
  "lat": "-36.8169494975663",
  "lon": "174.750326739307",
  "display_name": "Auckland Northern Motorway, Northcote Point, Kaipatiki, Auckland, 0627, New Zealand",
  "address": {
    "road": "Auckland Northern Motorway",
    "suburb": "Northcote Point",
    "city": "Kaipatiki",
    "state": "Auckland",
    "postcode": "0627",
    "country": "New Zealand",
    "country_code": "nz"
  },
  "boundingbox": [
    "-36.8199899",
    "-36.816863",
    "174.749659",
    "174.7503491"
  ]
}

**Comment by mtmail** [comment]
Auckland (https://www.openstreetmap.org/relation/2094141) is tagged `admin_level=4` (usually a state), Kaipatiki (https://www.openstreetmap.org/relation/2094145) is tagged `admin_level=8` (usually a city).

That follows the tagging scheme for New Zealand described on https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

Currently we don't have the flexibility to label a place differently, in this case as local board (https://en.wikipedia.org/wiki/Kaip%C4%81tiki_Local_Board surprisingly not listed on https://en.wikipedia.org/wiki/Auckland_Council#Local_boards) based on local are, in this case the district of Auckland. It's the drawback of forcing many different administrative level constructs of the world into a unified hierarchy. Similar with arrondissements and quarters in Paris and boroughs of London.

I could argue Auckland should be both state and city, it's tagged as `place=city` already but Nominatim will still assign it as state.

https://lists.openstreetmap.org/listinfo/talk-nz would know how the admin_level got assigned.

**Comment by kevin-argus** [comment]
Hi,
Thanks for your quick response. I understand the issue now.
The only remark I would like to add is that under the Auckland Wards and local boards ([https://en.wikipedia.org/wiki/Auckland_Council#Wards_and_local_boards](https://en.wikipedia.org/wiki/Auckland_Council#Wards_and_local_boards)) you can see Kaipatiki Local Board under North Shore.

Thanks,
K.

**Comment by lonvia** [comment]
There are a couple of 'city states' in the world that have this problem. We basically would need to look at the place designation which is slightly tricky because the boundary relations normally don't have it.

Closing in favour of #774, which describes the same issue for German Kreisstädte.
