### ISSUE TITLE
Database query failed

### ISSUE THREAD

**Issue by legale** [openstreetmap/Nominatim#1472]
Hello i have just installed local nominatim server. I have set up local.php config and tried to open
localhost/nominatim. I'm using external postgres server with Europe installed by the imposm.

I got this error:

Internal Server Error
Nominatim has encountered an internal error while accessing the database. This may happen because the database is broken or because of a bug in the software.

Details
Database query failed
If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used.

How to find the problem?

P.S. This is my local.php:
```
<?php
 @define('CONST_Website_BaseURL', '/nominatim/');
 @define('CONST_Database_DSN', 'pgsql:host=46.138.119.132;port=65432;user=osm;password=osm;dbname=osm');

```

**Comment by mtmail** [comment]
> I'm using external postgres server with Europe installed by the imposm.

imposm is a different geocoder. The database tables are not compatible. You'd need to run Nominatim setup to fill the database http://nominatim.org/release-docs/latest/admin/Import-and-Update/
