### ISSUE TITLE
Unavailable address and wrong street name

### ISSUE THREAD

**Issue by diegolamonica** [openstreetmap/Nominatim#1480]
I discovered that [this address](https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=138836547&class=highway) is wrong.
Indeed the street's name is **Via Sibilla Aleramo**. Instead **Via VIII Marzo** is the one unnamed nearby the circle.

Please provide to correct the issue.
Thanks a lot and good job!
Diego

**Comment by mtmail** [comment]
OSM doesn't have a central place to report data issues, Nominatim is "only" a search engine. Similar to wikipedia you can edit the street names yourself (The "edit" button on https://www.openstreetmap.org/way/138836547) or add a note to the map so a local OSM mapper will double-check https://www.openstreetmap.org/fixthemap

The Italian OSM community has a mailing list for help and questions https://lists.openstreetmap.org/listinfo/talk-it

Closing here as data issue.
