### ISSUE TITLE
Problem finding Shevchenko boulevard

### ISSUE THREAD

**Issue by KonesoN** [openstreetmap/Nominatim#1481]
Does not return lat lat correctly. And for some reason returns two
Value: Шевченка(street) + county
https://nominatim.openstreetmap.org/search?street=%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%B0+56&city=%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%8C%D0%B5&country=%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&county=%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D1%96%D0%B2%D1%81%D1%8C%D0%BA%D0%B8%D0%B9+%D1%80%D0%B0%D0%B9%D0%BE%D0%BD&format=json

Value: Шевченка(Boulevard)
https://nominatim.openstreetmap.org/search?street=%D0%A8%D0%B5%D0%B2%D1%87%D0%B5%D0%BD%D0%BA%D0%B0+56&city=%D0%97%D0%B0%D0%BF%D0%BE%D1%80%D0%BE%D0%B6%D1%8C%D0%B5&country=%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D0%B0&county=+&format=json

In my city there is Shevchenko boulevard and street

**Comment by mtmail** [comment]
> Does not return lat lat correctly.

What would be the correct position in your opinion?

> or some reason returns two [streets]

It's two long street sections https://www.openstreetmap.org/way/112190515 and https://www.openstreetmap.org/way/132423270 Nominatim doesn't connect or merge them at search time. It's unclear which of the sections would be the better result.

> In my city there is Shevchenko boulevard and street

Yes, there is. Please explain the problem.

**Comment by KonesoN** [comment]
> It's two long street sections https://www.openstreetmap.org/way/112190515 and https://www.openstreetmap.org/way/132423270 Nominatim doesn't connect or merge them at search time. It's unclear which of the sections would be the better result.

How can I find 56 number?

> Yes, there is. Please explain the problem.

When searching for "Shevchenko" without specifying 'county', he finds a boulevard. With an indication of 'county', finds the street

**Comment by mtmail** [comment]
> How can I find 56(example) number?

In OpenStreetMap at those two street section nobody added buildings or house numbers yet. It's missing data. The few building added have no house numbers. https://www.openstreetmap.org/#map=17/47.84256/35.18890

> When searching for "Shevchenko" without specifying 'county', [Nominatim] finds a boulevard. With an indication of 'county', finds the street

The streets are inside the specified county Шевченківський район (https://www.openstreetmap.org/relation/2825881) The boulevard is outside. It looks like the boulevard belongs to a different county Вознесенівський район (https://www.openstreetmap.org/relation/2825879)
