### ISSUE TITLE
Fishmore - there is no such place

### ISSUE THREAD

**Issue by margarethawkes** [openstreetmap/Nominatim#1486]
https://nominatim.openstreetmap.org/details.php?place_id=271043624
Sorry I live just up the road from here, and I can assure you that there is no village/hamlet called Fishmore here. Someone has entered the wrong information and I can't find out how to correct it.

Please can you change the entry. [https://nominatim.openstreetmap.org/details.php?place_id=271043624](url)
![Annotation 2019-09-04 180648](https://user-images.githubusercontent.com/30260900/64276041-daf63000-cf3e-11e9-96b5-3a72c2a97822.png)
![Annotation 2019-09-04 180436](https://user-images.githubusercontent.com/30260900/64276042-daf63000-cf3e-11e9-9053-40bfc71eb6f4.png)

The outline for Walton on Thames is also wrong. I should know, this is where I live, A large chunk of Walton is excluded. Just where are you getting your information from.

**Comment by mtmail** [comment]
Thanks for improving the map and the screenshots.

OpenStreetMap a community driven project, similar to Wikipedia and everybody can add and change information. I'm not saying users add wrong information on purpose, but mistakes happen with 2 million edits per day.

https://www.openstreetmap.org/fixthemap is one entry point explaining how you can make changes or how to leave a message on the map. https://osmuk.org/ is the UK organisation helping the effort.

> Just where are you getting your information from.

You can contact the user who made the last edit to the place https://www.openstreetmap.org/changeset/72953558 Those with multiple edits also have a "view history" on the bottom left https://www.openstreetmap.org/relation/9274278 I see the last edit was by https://www.openstreetmap.org/user/LivingWithDragons who I know personally and is very friendly and responsive to feedback.

There's no central place to report data issues. Closing here as Nominatim is "only" a search engine relying on the underlying data to be correct.

**Comment by SomeoneElseOSM** [comment]
I noticed this and mentioned it to someone on IRC who's more local than me and they've deleted it.  They also found a possible old source of the name: https://www.geograph.org.uk/photo/932956 (though of course it's certainly not a town).

**Comment by SK53** [comment]
Further info:

I used to live & work in the area & I have never heard of Fishmore. Nor is it shown on recent Ordnance Survey maps. Even if it does exist at best it is the name of a housing estate based on the former farm which used to exist where the reservoir is located. However, [other evidence](https://www.geograph.org.uk/photo/932956) suggests that this is not the case. It is certainly not a town. I have therefore [deleted the node](https://www.openstreetmap.org/changeset/74099933), and commented on the [changeset](https://www.openstreetmap.org/changeset/72953558).

I would expect nominatim to then start using a more accurate approximation of Walton.
