### ISSUE TITLE
Not getting a city - only city_district

### ISSUE THREAD

**Issue by FabianL1** [openstreetmap/Nominatim#1487]
Hey,

Sometimes I've an issue that I only see city_district but not the city where the district belongs to.

E.g.
https://nominatim.openstreetmap.org/search?postalcode=47226&format=json&addressdetails=1&country=Deutschland

If you read about this, Rheinhausen is part of Duisburg. But it is only showing city_district. 

When I use the same zipCode but add a street:
https://nominatim.openstreetmap.org/search?postalcode=47226&format=json&addressdetails=1&country=Deutschland&street=G%C3%BCnterstra%C3%9Fe

It shows me the city correctly.

Expected:
Show city for the first query too.

**Comment by FabianL1** [comment]
Is there any update on this? :)

**Comment by lonvia** [comment]
Looks like the city gets cancelled out by the postcode when collecting the address parts. Clearly a bug that needs fixing.

**Comment by FabianL1** [comment]
Thanks a lot - that fixed the issue for many cities :)

**Comment by FabianL1** [comment]
Hey - found another case. Can you reopen:
https://nominatim.openstreetmap.org/search?postalcode=53179&format=json&addressdetails=1&country=Deutschland

**Comment by lonvia** [comment]
No, that's a data issue. Bonn is a kreisfreie Stadt and therefore only the county is available. There are a couple of issues that discuss that already.

**Comment by FabianL1** [comment]
But would it not make sense to still show city? It is also a city https://de.wikipedia.org/wiki/Bonn
