### ISSUE TITLE
Import Fails ERROR: No Data string(7) "No Data"

### ISSUE THREAD

**Issue by renedlog** [openstreetmap/Nominatim#1488]
I tried to follow the Nominatim Setup Guide for Centos 7 on:
https://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/

But in the end, it seems I cannot import the data. I've already setup Nominatim a couple of times on Ubuntu without any problem but in this special case I need CentOS due to Company restrictions.

Here the last output of the command line:
```
[nominatim@ch01s7a7 build]$ ./utils/setup.php --osm-file /var/tmp/planet-latest.osm.pbf --all
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /srv/nominatim/Nominatim/lib/cmd.php on line 125
2019-09-06 07:15:54 == module path: /srv/nominatim/build/module
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /srv/nominatim/Nominatim/lib/cmd.php on line 125
2019-09-06 07:15:54 == Create DB
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /srv/nominatim/Nominatim/lib/cmd.php on line 125
2019-09-06 07:15:55 == Setup DB
Postgres version found: 9.02
PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /srv/nominatim/Nominatim/lib/cmd.php on line 134
2019-09-06 07:15:55 == WARNING: Postgresql is too old. extratags and namedetails API not available.
Postgis version found: 2
 set_config
------------

(1 row)

PHP Warning:  date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /srv/nominatim/Nominatim/lib/cmd.php on line 125
2019-09-06 07:16:00 == Import data
osm2pgsql version 0.96.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2255MB, maxblocks=36080*65536, allocation method=11
Mid: pgsql, cache=2255
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels
Parsing gazetteer style file '/srv/nominatim/Nominatim/settings/import-full.style'.
Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping

Reading in file: /var/tmp/planet-latest.osm.pbf
Using PBF parser.
Processing: Node(1666300k 1350.3k/s) Way(0k 0.00k/s) Relation(0 0.00/s)ERROR: No Data
string(7) "No Data"
[nominatim@ch01s7a7 build]$ 
```

Also with the cache set (--osm2pgsql-cache 28000) it results in the same problem.
The only related issue (except the killed message) is:
https://github.com/openstreetmap/Nominatim/issues/1446

An OOM should not be the source of the problem... the system never used more than 70%

**Comment by mtmail** [comment]
See http://nominatim.org/release-docs/latest/admin/Faq/#php-timzeone-warnings to get rid of the timezone warnings.

Can you import a smaller country first to see if the installation itself was successful? In tests we use Luxembourg or Monaco. (http://download.geofabrik.de/europe.html) Then maybe a country 1GB size like South America (http://download.geofabrik.de/). Then we can rule out many issues. If those work and the whole planet of 50GB fails we can assume it's something related to scale, e.g. not enough RAM, unstable system (for example, network mounted storage, bad memory chips).

Any reason you're still using Postgresql 9.2? It should work but in our test suite we stopped testing the version years ago.

**Comment by renedlog** [comment]
@mtmail thank you for your response. Seems it is working with small countries. I've tried to import "Liechtenstein" and it worked successfully. So the problem must be something in the setup. 

Virtualized CentOS on VMware 
4x vCPU
32GB Ram
>1TB disk (network) mounted 

I guess this is a non-supported setup, so feel free to close the ticket if so.

**Comment by mtmail** [comment]
Thanks for the update. We had a report network mounted storage can be less stable in https://github.com/openstreetmap/Nominatim/issues/877#issuecomment-356878253 The osm2pgsql install step can't be interrupted. Later in the installation you might have seen "Rank 6, Rank 7, ..." and that can be restarted (http://nominatim.org/release-docs/latest/admin/Faq/#can-a-stoppedkilled-import-process-be-resumed).
