### ISSUE TITLE
20 US states are missing on the details page for USA

### ISSUE THREAD

**Issue by siffash** [openstreetmap/Nominatim#1490]
Steps to reproduce:
1) Search for USA
2) Go to the details page and navigate to the section Parent Of
3) Notice that only 30 US states are present in the Administrative list

Note that currently USA has 50 states.

**Comment by mtmail** [comment]
The database query has a limit of 500 child places it returns for performance. Some places can have thousands of children. If you search for a place not in the list like California or South Carolina you'll see the USA is the parent.

**Comment by siffash** [comment]
Hi @mtmail thanks for the reply. I know about the 500 children limit, but I don't think that's the issue here. I counted all child places of [USA](https://nominatim.openstreetmap.org/details.php?place_id=197597979), there are 103 of them.

**Comment by siffash** [comment]
Actually there **is** a difference between e.g. Alabama which is in the USA's child places list, and California which is not. Both of them have USA in the Address section. However Alabama has USA there **with** a link to details page, while California has USA there with **no** link to details page.

**Comment by lonvia** [comment]
The interesting question is: what do you need this information for? Parenting is an internal feature of Nominatim and not really relevant for any objects with rank level < 30. Does the fact that these states are missing have any influence on search results for you?

**Comment by mtmail** [comment]
On my local planet installation from about 2 months ago I find all states on the detail page of USA. So the software and database queries seems fine. The database on osm.org might need to be refreshed.

Well 50 plus
* American Samoa
* D.C. (Federal District, not a statte)
* Guam
* Liberty Island (not sure if admin_level=4 is correct but that's a different discussion https://www.openstreetmap.org/relation/9791559)
* Northern Mariana Islands
* Puerto Rico
* United States Virgin Islands

**Comment by siffash** [comment]
@mtmail do you think the data in OSM has been corrupted since then?

**Comment by mtmail** [comment]
Ah, sorry, my answer was confusing. I did a fresh install 2 months ago and then daily updates. The nominatim.osm.org server was fresh installed earlier (1 year ago) and then minutely updates.

I suspect there might have been a software issue in the past which was fixed since then and the database of nominatim.osm.org needs to be refreshed. By refresh I mean each state in the country needs to be checked again where it belongs in the hierachy. I don't have access to that database so I can't doublecheck.

But as lonvia says if searches work fine then it's less of a priority.

**Comment by siffash** [comment]
I want to install and use Nominatim to retrieve administrative information to use it in another project. Currently I'm checking if I can rely on that information and whether it's correctly computed. Since you suspect that the problem is with the old installation on osm servers and a fresh installation will compute everything correctly, I will double-check that when I install Nominatim on my machine. Thanks for the help.

**Comment by mtmail** [comment]
Only importing admin level places should be enough then. http://nominatim.org/release-docs/latest/admin/Import-and-Update/#filtering-imported-data
