### ISSUE TITLE
Reverse Geocoding - Ferry terminal in NZ returns with wrong name

### ISSUE THREAD

**Issue by kevin-argus** [openstreetmap/Nominatim#1491]
For the lat=-36.80906 lon=175.02562 we get 渡船口.
This is a ferry station in NZ.

https://nominatim.openstreetmap.org/reverse?lat=-36.80906&lon=175.02562&format=json&zoom=30&accept-language=en

{
  "place_id": 17554763,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "node",
  "osm_id": 1686597509,
  "lat": "-36.8093488",
  "lon": "175.0261373",
  "display_name": "渡船口, Donald Bruce Road, Surfdale, Waiheke, Auckland, 1081, New Zealand",
  "address": {
    "ferry_terminal": "渡船口",
    "road": "Donald Bruce Road",
    "suburb": "Surfdale",
    "city": "Waiheke",
    "state": "Auckland",
    "postcode": "1081",
    "country": "New Zealand",
    "country_code": "nz"
  },
  "boundingbox": [
    "-36.8094488",
    "-36.8092488",
    "175.0260373",
    "175.0262373"
  ]
}

**Comment by mtmail** [comment]
Nominatim returns the data in the OpenStreetMap database. If you know the English name for the place you can add it on https://www.openstreetmap.org/node/1686597509 (link "edit" in the top navigation) or add a note for a local mapper https://www.openstreetmap.org/fixthemap

It's part of "Halfmoon Bay - Waiheke Island Vehicle Ferry" (https://www.openstreetmap.org/way/11025041) and the destination is called "Halfmoon Bay Ferry Terminal". Maybe this one is "Waiheke Island Ferry Terminal". I'm only guessing.

Closing as data issue.
