### ISSUE TITLE
Database server failed to load /srv/nominatim/Nominatim/build/module/nominatim.so module

### ISSUE THREAD

**Issue by killer3dfx** [openstreetmap/Nominatim#1492]
New Centos 7 Installation. Cant import osm file.

 ./utils/setup.php --osm-file /home/centos/build/colombia-latest.osm.bz2 --all --osm2pgsql-cache 28000 2>&1 | tee setup.log
2019-09-09 18:19:07 == module path: /home/centos/build/module
2019-09-09 18:19:07 == Create DB
2019-09-09 18:19:08 == Setup DB
Postgres version found: 11
Postgis version found: 2.5
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /home/centos/build/module/nominatim.so module

  thrown in /home/centos/Nominatim/lib/DB.php on line 61

**Comment by mtmail** [comment]
Does the file exist? Does the file exist on the server the database is on? What are the permission on the file and parent directory?

**Comment by killer3dfx** [comment]
Thanks for your response.

$ ls -l $USERHOME/build/module/nominatim.so
-rwxr-xr-x. 1 centos centos 342328 Sep  9 18:58 /home/centos//build/module/nominatim.so

ls -l
total 137180
-rw-rw-r--. 1 centos centos     23985 Sep  9 18:56 CMakeCache.txt
drwxrwxr-x. 4 centos centos       264 Sep  9 18:58 CMakeFiles
-rw-rw-r--. 1 centos centos      1933 Sep  9 18:56 cmake_install.cmake
-rw-rw-r--. 1 centos centos 140383466 Sep  8 21:43 colombia-latest.osm.pbf
-rw-rw-r--. 1 centos centos       999 Sep  9 18:56 CTestTestfile.cmake
-rw-r--r--. 1 centos centos      2263 Sep  9 18:56 DartConfiguration.tcl
drwxrwxr-x. 5 centos centos       130 Sep  9 18:57 docs
-rw-rw-r--. 1 centos centos     37402 Sep  9 18:56 Makefile
-rw-rw-r--. 1 centos centos      1618 Sep  9 18:56 mkdocs.yml
drwxrwxr-x. 3 centos centos       114 Sep  9 19:07 module
drwxrwxr-x. 3 centos centos       111 Sep  9 18:58 nominatim
drwxrwxr-x. 5 centos centos       206 Sep  9 18:58 osm2pgsql
drwxrwxr-x. 2 centos centos        43 Sep  9 19:00 settings
-rw-rw-r--. 1 centos centos       375 Sep  9 19:08 setup.log
drwxrwxr-x. 3 centos centos        23 Sep  9 18:56 Testing
drwxrwxr-x. 2 centos centos       174 Sep  9 18:56 utils
drwxrwxr-x. 2 centos centos       195 Sep  9 18:56 website

**Comment by mtmail** [comment]
Is the database on the same server?

Which operating system user starts the database? On centos the default is `postgres`, but double-check.

That user needs to be able to access the file. Try
```bash
sudo -u postgres ls -la /home/centos/build/module/nominatim.so
```

I think the parent directories need to be readable and executable by all  (`chmod a+x /the/directory/`) unless user `postgres` is also in the group `centos`.

Our installation instructions http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/ use a user `nominatim` and directory `/src/nominatim/` which makes permission easier. Also note the SELinux Security setting near the end of the instruction if yo use SELinux.

**Comment by killer3dfx** [comment]
I had to make an install but for Ubuntu, everything wenk ok, thanks for your help.

**Comment by toton6868** [comment]
I am also getting a similar error for Ubuntu. 
```
2020-11-03 21:39:16 == module path: /srv/nominatim/build/module
2020-11-03 21:39:16 == Create DB
2020-11-03 21:39:16 == Setup DB
Postgres version found: 12
Postgis version found: 2.5
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /srv/nominatim/build/module/nominatim.so module

  thrown in /srv/nominatim/Nominatim-3.5.2/lib/DB.php on line 61
```
I am following [this](https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/) documentation.

I am using **Postgresql 12** and **PostGIS 2.5**. I am running the Apache server on the `8081` port.

After every prerequisite installation, I have created nominatim user. After that I have changed the user to nominatim by `sudo su - nominatim` and `make` nominatim in `/srv/nominatim` directory. The building was errorless. But when I am trying to run `./utils/setup.php --osm-file /srv/nominatim/Nominatim-3.5.2/data/map.osm.pbf --all 2>&1 | tee setup.log` command it is returning the above error. The `nominatim.so` file permission is as follows
```
-rwxrwxrwx 1 nominatim nominatim 308800 Nov  3 21:03 /srv/nominatim/build/module/nominatim.so
```
even i have tried with `chmod a+x /srv/nominatim` and `chmod a+x /srv` but there is no luck.

**Comment by mtmail** [comment]
@toton6868 Please open a new issue. This one got closed over a year ago.

**Comment by toton6868** [comment]
@mtmail I have opened a new one #2042 2042
