### ISSUE TITLE
Street assigned to wrong city

### ISSUE THREAD

**Issue by FelixCali** [openstreetmap/Nominatim#1493]
https://nominatim.openstreetmap.org/details.php?place_id=80436516

The "Lord Street" in Leigh does not contain Leigh in its address hierarchy, although it clearly is in Leigh. Instead, it is mapped to Wigan. This might be caused by the circumstance that apparently the city Wigan and Wigan Council are treated as the same by Nominatim. This also results in the suburb of Westleigh being linked to Wigan as well.

**Comment by mtmail** [comment]
In OSM data Leigh only exists as node (center point) https://www.openstreetmap.org/node/27329912 Nominatim does a best guess given the data. It knows the street is in Wigan (https://www.openstreetmap.org/relation/146938) and then ignores the other cities even if they're closer. Best approach is to add boundary data to Leigh.
