### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 838860800 bytes exhausted (tried to allocate 4096 bytes) in /srv/nominatim/lib/setup/SetupClass.php on line 442

### ISSUE THREAD

**Issue by ankailou** [openstreetmap/Nominatim#1494]
**Operating System**: Ubuntu 18.04, on AWS, inside of a Docker image running on Kubernetes 12.0 on an m5.4xlarge instance
**Hardware Configurations**: Running on Kubernetes on an m5.4xlarge instance, with 56gb RAM limit, 14 CPU limit
**Postgres version**: 10
**Postgis version**: 2.4
**PHP version**: 7.2
**Postgres configurations:**
```
max_connections = 100
shared_buffers = 2GB
maintenance_work_mem = 10GB
work_mem = 50MB
effective_cache_size = 24GB
synchronous_commit = off
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
wal_buffers = 16MB
default_statistics_target = 100
max_locks_per_transaction = 256
```
Nominatim version: 3.3.0, from http://www.nominatim.org/release/Nominatim-3.3.0.tar.bz2

I am encountering this error:
```
2019-09-03 04:54:57 == Load Data
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 0 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 1 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 2 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 3 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 4 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 5 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 6 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 7 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 8 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 9 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 10 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 11 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 12 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
INSERT INTO placex (osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry) SELECT osm_type, osm_id, class, type, name, admin_level, address, extratags, geometry FROM place WHERE osm_id % 14 = 13 and not (class='place' and type='houses' and osm_type='W'          and ST_GeometryType(geometry) = 'ST_LineString') and ST_IsValid(geometry)
insert into location_property_osmline (osm_id, address, linegeo) SELECT osm_id, address, geometry from place where class='place' and type='houses' and osm_type='W' and ST_GeometryType(geometry) = 'ST_LineString'
PHP Fatal error:  Allowed memory size of 838860800 bytes exhausted (tried to allocate 4096 bytes) in /srv/nominatim/lib/setup/SetupClass.php on line 442
PHP Fatal error:  Allowed memory size of 838860800 bytes exhausted (tried to allocate 4096 bytes) in Unknown on line 0
PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217736 bytes) in Unknown on line 0
```
on the "Load Data" step of a full planet import.

This is the command that I'm running:
```
sudo -u nominatim /srv/nominatim/build/utils/setup.php \
     --enable-debug-statements --verbose \
     --osm-file $NOMINATIM_DATA_PATH/$NOMINATIM_DATA_LABEL.osm.pbf \
     --all --osm2pgsql-cache 24000
```

I'm fairly positive that I have enough RAM on my machine and the `memory_limit` in my `php.ini` is set to `-1` so I don't think there's a hard limit that I can increase. I'm completely lost where the numbers "838860800" and "1073741824" are coming from in terms of allowed memory size.

I looked up the specific line (SetupClass.php on line 442) where the error seemed to come from and I found a while loop waiting for an async pg query to complete. Is it possible that this loop is eating all the mem in my system?

**Comment by ankailou** [comment]
I can also confirm that I don't encounter this issue when I use a smaller osm.pbf like http://download.geofabrik.de/asia/maldives-latest.osm.pbf

This only seems to happen for me when I try setup for a full planet.

**Comment by mtmail** [comment]
Your hardware seems suitable for a planet import.

It's the first report of this error or around these lines of code. To even get to 800 megabyte I can only guess PHP tries to print a huge error message/stack that basically includes all data.

Do you see any errors in the Postgresql log files? One of the most common failures is Postgresql crashing during the data import. Sometimes it's limitations of hardware (simply running out of RAM) or instable hardware (bad RAM, network failures with network mounted storage). When I say "common" I mean what users report, I'm sure much more installations work fine and we never get feedback for those.

There is a https://lists.openstreetmap.org/listinfo/geocoding mailinglist, maybe somebody else saw the issue before.

Thanks for the very detailed report (all version numbers, full command run, `-enable-debug-statements`) and trying a small country!

**Comment by ankailou** [comment]
The possibility that Postgres might be crashing didn't occur to me. I'm sure the machine I'm running the import on has ample memory for both Nominatim and Postgres. The setup makes it past the `import-data` step, but breaks at the `load-data` step. So Postgres is running and the nominatim table is about 200-300gb in size before hitting that error. Postgres logs may shed some light on this. I kicked off another full planet import approximately 8 hours ago. It should take quite a long time for the import to reach the step where its failing again. I can report on Postgres logs then. 

I'm pretty sure it's not bad hardware since I've cycled through several new m5.4xlarge instances and EBS volumes and I've been able to consistently reproduce this error. 

The specific line (SetupClass.php on line 442) seems to suggest PHP is waiting on a result from an async process and never gets one, which leads to the while loop eating up all the memory. The reference to `in Unknown on line 0` in the subsequent error messages seems to suggest than the other async processes are also running out of memory too. Does that sound like a correct assessment of what may be happening? Is there any way to access that huge error/stack trace that PHP may be trying to print? The error logs I got through `--verbose` and `--enable-debug-statements` are not quite descriptive enough.

**Comment by ankailou** [comment]
I found these logs in my postgres logs:
```
2019-09-13 20:42:04.545 UTC [195] CONTEXT:  PL/pgSQL function placex_update() line 671 at RAISE
2019-09-13 20:42:04.545 UTC [195] LOG:  could not send data to client: Connection reset by peer
2019-09-13 20:42:04.545 UTC [195] CONTEXT:  PL/pgSQL function placex_update() line 671 at RAISE
2019-09-13 20:42:04.545 UTC [195] STATEMENT:  update placex set indexed_status = 0 where place_id = $1
2019-09-13 20:42:04.546 UTC [190] WARNING:  Checked for nearest way (<NULL>)
2019-09-13 20:42:04.546 UTC [190] CONTEXT:  PL/pgSQL function placex_update() line 322 at RAISE
2019-09-13 20:42:04.546 UTC [195] FATAL:  connection to client lost
```
For some reason the PHP import code and the postgres database are losing their connection to each other momentarily.

**Comment by mtmail** [comment]
That's likely the root cause. We heard from users whose installation on older slower hardware took one or even more then two weeks but it finished on the first try.

I don't have a good recommendation on why the database connection would fail, that goes too much into system administrator. If the database is on a separate host maybe put both on the same host.

Doublecheck if you disabled `fsync` and `full_page_writes`
http://nominatim.org/release-docs/latest/admin/Installation/#setup-of-the-server
you can enable it again after the import.

**Comment by lonvia** [comment]
The 50GB postgres logfile come from setting `--enable-debug-statements`. It enables logging within our SQL triggers. It's for development only and it is very, very verbose. You must not use this option when importing the planet. Remove the option and you should be fine. (You can leave `--verbose`. That just adds some additional messages in the PHP code.)

**Comment by ankailou** [comment]
@lonvia Thanks for the tip. I'll give that a try.
