### ISSUE TITLE
Wrong Name

### ISSUE THREAD

**Issue by michaellr86** [openstreetmap/Nominatim#1496]
https://nominatim.openstreetmap.org/details.php?place_id=191772878

The park name should be: Marapikurrinya Park

Supporting Evidence from the local gov.:
https://www.porthedland.wa.gov.au/news/upcoming-marapikurrinya-park-upgrades-to-improve-accessibility/3634

**Comment by mtmail** [comment]
Nominatim returns the data in the OpenStreetMap database. If you know the correct name for the place you can add it on https://www.openstreetmap.org/way/565053818 (link "edit" in the top navigation) or add a note for a local mapper https://www.openstreetmap.org/fixthemap

Thanks a lot for improving OpenStreetMap

Closing as data issue.

**Comment by lonvia** [comment]
@michaellr86 Could you say who pointed you to this issue tracker for reporting? I'm asking because we are suddenly getting a lot of data issue reports and am curious where they come from.

**Comment by michaellr86** [comment]
I work for the local gov. and we were holding an event there. Facebook pulls data from openstreet maps directly/indirectly, so we initiated the name correction.

Kind regards,
[cid:image003.jpg@01D56C8D.D68FE240]
Michael Rodrigues
Marketing and Communications Officer
PO Box 41 Port Hedland WA 6721
(08) 9158 9318
0413 970 608
mrodrigues@porthedland.wa.gov.au<mailto:mrodrigues@porthedland.wa.gov.au%0d>
www.porthedland.wa.gov.au<http://www.porthedland.wa.gov.au/>
www.facebook.com/townofporthedland<http://www.facebook.com/townofporthedland>


The Town of Port Hedland would like to acknowledge the Kariyarra, Ngarla, and Nyamal people as the Traditional Custodians of the Town of Port Hedland lands. We recognise their strength and resilience and pay our respects to their Elders past and present.
