### ISSUE TITLE
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /srv/nominatim/build/module/nominatim.so module

### ISSUE THREAD

**Issue by timkatee** [openstreetmap/Nominatim#1497]
I get this error when trying to import data. It also comes when using ./utils/setup.php --create-functions. I have followed all the instructions from http://nominatim.org/release-docs/3.2.0/appendix/Install-on-Centos-7/  . Kindly note am running postgresql 9.6

**Comment by mtmail** [comment]
It was last reported 7 days ago https://github.com/openstreetmap/Nominatim/issues/1492 and there's a couple of debugging steps listed there. The user gave up and installed Ubuntu though.

**Comment by timkatee** [comment]
> It was last reported 7 days ago #1492 and there's a couple of debugging steps listed there. The user gave up and installed Ubuntu though.

I have checked the thread but it doesn't clearly state how the problem was sloved on centos 7. Any help would be greatly appreciated.

**Comment by mtmail** [comment]
Does the file exist?

Does the file exist on the server the database is on?

What are the permission on the file and parent directory?

Which operating system user starts the database? On centos the default is postgres, but double-check.

That user needs to be able to access the file. Try `sudo -u postgres ls -la /the/path/to/build/module/nominatim.so`

**Comment by timkatee** [comment]
> Does the file exist?
> 
> Does the file exist on the server the database is on?
> 
> What are the permission on the file and parent directory?
> 
> Which operating system user starts the database? On centos the default is postgres, but double-check.
> 
> That user needs to be able to access the file. Try `sudo -u postgres ls -la /the/path/to/build/module/nominatim.so`

The nominatim server and the database server are on the same server. 
Parent directory : drwxrwxr-x 11 nominatim nominatim 4096 Sep 16 10:53 build
File : -rwxr-xr-x 1 nominatim nominatim 342336 Sep 16 10:55 /srv/nominatim/build/module/nominatim.so

For the database this is how it looks like

postgres=# \du
                                 List of roles
     Role name     |                   Attributes                   | Member of 
-------------------+------------------------------------------------+-----------
 apache            | Superuser, Create role, Create DB              | {}
 nominatim         | Superuser, Create role, Create DB              | {}
 pg_signal_backend | Cannot login                                   | {}

**Comment by mtmail** [comment]
Thanks a lot, that looks good.

Does the postgresql log file give any more information?

Can you point me to the CentOS image you use? With our Vagrant test setup I wasn't able to replicate the same error last week so I wonder if our test setup uses the wrong operating system base image.

**Comment by timkatee** [comment]
> Thanks a lot, that looks good.
> 
> Does the postgresql log file give any more information?
> 
> Can you point me to the CentOS image you use? With our Vagrant test setup I wasn't able to replicate the same error last week so I wonder if our test setup uses the wrong operating system base image.

I think the issue has something to do with postgresql96 not being able to load the file. I have installed the postgresql from the centos repository and fails at this point ...

ERROR: Minimum supported version of Postgresql is 9.3.
string(47) "Minimum supported version of Postgresql is 9.3."

Is there a way I can have the installation still work with version 9.2?

**Comment by lonvia** [comment]
My guess would be that our [instructions for SELinux](http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/#adding-selinux-security-settings) no longer work. The Vagrant image we use comes without SELinux if I remember correctly. From the output above I would try the following:

```
sudo semanage fcontext -a -t httpd_sys_content_t "/srv/nominatim/build/(website|lib|settings)(/.*)?"
sudo semanage fcontext -a -t lib_t "/srv/nominatim/build/module/nominatim.so"
sudo restorecon -R -v /srv/nominatim/build
```

**Comment by timkatee** [comment]
> My guess would be that our [instructions for SELinux](http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/#adding-selinux-security-settings) no longer work. The Vagrant image we use comes without SELinux if I remember correctly. From the output above I would try the following:
> 
> ```
> sudo semanage fcontext -a -t httpd_sys_content_t "/srv/nominatim/build/(website|lib|settings)(/.*)?"
> sudo semanage fcontext -a -t lib_t "/srv/nominatim/build/module/nominatim.so"
> sudo restorecon -R -v /srv/nominatim/build
> ```

My SELinux is not enabled

**Comment by timkatee** [comment]
This was being caused by postgres not being able to load the file. I had installed postgres 9.6. I tweaked nominatim file to allow lower version of postgres, 9.2 and it passed this stage.

**Comment by lonvia** [comment]
Well, everybody is free to shoot their own foot, of course. Just let me make the official position clear: tweaking the minimum allowed postgres version will break your import. **Don't do it.**

(NB: the next guess would have been, that you have linked your nominatim.so against the wrong version of the postgres server libraries. You would see that in the postgres logs when trying to load the module.)

**Comment by timkatee** [comment]
> Well, everybody is free to shoot their own foot, of course. Just let me make the official position clear: tweaking the minimum allowed postgres version will break your import. **Don't do it.**
> 
> (NB: the next guess would have been, that you have linked your nominatim.so against the wrong version of the postgres server libraries. You would see that in the postgres logs when trying to load the module.)

Yeah, it broke, some functions guess didn't exist, now am back to posgresql 9.6 but with the same error as above.

Will appreciate any help.

**Comment by mtmail** [comment]
Delete (or rename) the `build` directory and recreate it (make a copy of the `build/settings/local.php` if you made changes). On http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/ look for the section "build Nominatim in there", the cmake and make steps create the nominatim.so file.

Take special note of the output of `cmake` and which postgresql version it finds. For example
```
-- Found PostgreSQL: /usr/lib64 (found version "9.2.24")
Libraries used to build: /usr/lib64/libboost_system-mt.so
/usr/lib64/libboost_filesystem-mt.so/usr/lib64/libpq.so
/usr/lib64/libz.so-lpthread/usr/lib64/libexpat.so
/usr/lib64/libbz2.so/usr/lib64/libproj.so
```

**Comment by mtmail** [comment]
With a little luck CentOS 8 is released in 7 days (https://wiki.centos.org/About/Building_8) and defaults to a new postgresql version.

**Comment by timkatee** [comment]
> With a little luck CentOS 8 is released in 7 days (https://wiki.centos.org/About/Building_8) and defaults to a new postgresql version.

Thanks very much for the help and feedback, will definitely test on that and provide feedback.
