### ISSUE TITLE
special_phrases not working

### ISSUE THREAD

**Issue by gittan443** [openstreetmap/Nominatim#1499]
I'm following the official installation guide of nominatim 3.20 and this step errors out:

./utils/specialphrases.php --wiki-import > specialphrases.sql
psql -d nominatim -f specialphrases.sql

nominatim_1   | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
nominatim_1   | psql:specialphrases.sql:2622: ERROR:  function make_standard_name(unknown) does not exist
nominatim_1   | LINE 1: select getorcreate_amenityoperator(make_standard_name('ATM i...

My google skills and experience with Nominatim are hindering me to be able to search for pubs in an area.

Skipping specialphrases allows me successfully to build (a dockerized) Nominatim server.

**Comment by mtmail** [comment]
Any reason you installing Nominatim 3.2, not the latest 3.3? http://nominatim.org/release-history/

`specialphrases.php` takes data from https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/FR (one page per language) and puts them into the `specialphrases.sql` file. So it's possible your sql file is different from mine. Can you post what is in the `specialphrases.sql` file around line 2622? Or post the full file here.

**Comment by gittan443** [comment]
Typo on my side, I'm running 3.3:

ENV NOMINATIM_VERSION v3.3.0

# Based on
# https://switch2osm.org/manually-building-a-tile-server-lts-lts/

# Install dependencies
RUN apt-get update && apt-get install -y git-core
# Set up environment and user

WORKDIR /src

RUN git clone --recursive https://github.com/openstreetmap/Nominatim --progress
RUN cd ./Nominatim && git checkout tags/$NOMINATIM_VERSION && git submodule update --recursive --init --progress


[specialphrases.zip](https://github.com/openstreetmap/Nominatim/files/3620838/specialphrases.zip)

**Comment by mtmail** [comment]
I ran `psql -d nominatim -f specialphrases.sql` and can import your file without problems.

Does the function exist in your database? Try running the query `select make_standard_name(' abc-def ');`

Did the main import of data (the `./utils/setup.php --osm-file ...` command) finish fine? https://nominatim.org/release-docs/latest/admin/Import-and-Update/

There's a separate https://github.com/mediagis/nominatim-docker/tree/master/3.3 project which might be a good basis for your dockerfile.

**Comment by mtmail** [comment]
With `git clone` you run the latest version. For a production server you probably want to use a stable release https://nominatim.org/release-history/

**Comment by gittan443** [comment]
setup.log is attached, but yes, I't works flawless. 

postgres@nomdb:~$ psql
psql (10.6 (Debian 10.6-1.pgdg90+1))
Type "help" for help.

postgres=# \c nominatim
You are now connected to database "nominatim" as user "postgres".
nominatim=# select make_standard_name(' abcdef ');
 make_standard_name 
--------------------
 abcdef
(1 row)

Note, the DB is in a different container and nominatim.so is exported from container(nom) -> container(DB)-> using a shared volume.

For special_phrases, I restrict languages with local.php to only 2 languages (using all results in error for me).

When running it interactively as per your command above it loads perfectly. I guess it is an issue with environment variables in my dockerfile and not with the Nominatim code. Sorry! Thanx for the help!

If I solve it in my project soon, I'll include the solution for others to read, otherwise feel free to close the ticket.

[setup.zip](https://github.com/openstreetmap/Nominatim/files/3624563/setup.zip)

**Comment by gittan443** [comment]
Yes, the error was completely on my side:

```
    #psql -h $PGHOST -p $PGPORT -U $PGUSER -w -f specialphrases.sql
    echo "PGHOST=${PGHOST} PGPORT=${PGPORT} PGUSER=${PGUSER}"
    echo "psql -d nominatim -f specialphrases.sql"
    psql -d nominatim -f specialphrases.sql
```
I ran psql with postgres user instead of nominatim user. My bad!

**Comment by gittan443** [comment]
Yes, the error was completely on my side:

```
    #psql -h $PGHOST -p $PGPORT -U $PGUSER -w -f specialphrases.sql
    echo "PGHOST=${PGHOST} PGPORT=${PGPORT} PGUSER=${PGUSER}"
    echo "psql -d nominatim -f specialphrases.sql"
    psql -d nominatim -f specialphrases.sql
```
I ran psql with postgres user instead of nominatim user. My bad!
