### ISSUE TITLE
Allow matches for shorter substring

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#1500]
Neither https://www.openstreetmap.org/search?query=bg%C5%BC%2C+Krak%C3%B3w#map=19/50.06471/19.95153 nor https://www.openstreetmap.org/search?query=BG%C5%BB%2C+Krak%C3%B3w#map=19/50.06471/19.95153 matches https://www.openstreetmap.org/node/4442413531#map=19/50.06471/19.95119

I would expect that "BGŻ" or "BGŻ" would match bank with "bgż bnp paribas" name, especially in cases where "bgż" is not matching anything else.

**Comment by lonvia** [comment]
Works both for me.

**Comment by matkoniecz** [comment]
List of results changed, now it is displaying nearby ATM.

Still, bank is unmatched.

**Comment by lonvia** [comment]
That's because the ATM is tagged with brand=BGZ now, which makes this a perfect match. the banks do appear when clicking on 'More results'.

For matching of partial strings see #94. Closing as duplicate here.
