### ISSUE TITLE
Cannot found "Cecilia Silva Colagrande" located in Bragança Paulista, SP - Brazil

### ISSUE THREAD

**Issue by Brand00wn** [openstreetmap/Nominatim#1501]
I think this one is a new street... Google Maps already can found it, but Nominatium don't.

**Comment by mtmail** [comment]
Somebody will need to add the street name to the OpenStreetMap database. https://www.openstreetmap.org/#map=17/-22.92773/-46.53319

If you know where the street is you can do it https://www.openstreetmap.org/fixthemap https://welcome.openstreetmap.org/ We can't copy from Google Maps, it's licensed data. Once added the Nominatim search software should be able to find it.

Closing here as data issue.
