### ISSUE TITLE
Why detail.php doesn't retrieve the hamlets in its hierarchy

### ISSUE THREAD

**Issue by HubertNo** [openstreetmap/Nominatim#1503]
For example I have this request in France for the village Prat :
https://nominatim.openstreetmap.org/details.php?place_id=198454702&format=json&hierarchy=1

If I look the result, in hierarchy tag, I can found in class=place type : locality, farm, isolated_dwelling but no hamlet.

If I search for hamlet for exemple Kerguidu : 
https://nominatim.openstreetmap.org/details.php?place_id=27427180
I can found an place:hamet but the place:village Prat is greyed. 

My question is simple, why can I found farm, isolated_dwelling with detail.php but not hamlet ? and why in the sheet of the hamlet, the village appear but greyed ?

Is there a way to find the hamlet with detail.php ?
Thanks.

**Comment by mtmail** [comment]
In Nominatim's hierarchy model villages and hamlets have the same address rank. https://github.com/openstreetmap/Nominatim/blob/master/settings/address-levels.json

A village can't be a child of a hamlet or vice-versa. They're seen as equal.

I think what you're saying is that in France a hamlet is always a child of a village? It's not clear from https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative

Nominatim makes a decision which of the nearby villages or hamlets is the closest (by distance) and selects one. Those too far away appear greyed out in the list.

farm, isoleted_dwelling have an address rank of 22 and 20. They can be children of villages or hamlets.

**Comment by HubertNo** [comment]
Thank you for your answer.
It doesn't solve my problem, but it helps me to understand.
