### ISSUE TITLE
Import data using a 2GB ram VPS Server

### ISSUE THREAD

**Issue by cristianormoraes** [openstreetmap/Nominatim#1504]
I would like to ask if there are a way to import data using a 2GB, I'm trying and trying to importing using:

**sudo -u postgres ./setup.php --osm-file brazil-latest.osm.pbf --all --osm2pgsql-cache 312 2>&1 | tee setup.log**

I tried to import monaco-latest.osm.pbf and works fine and nominatim ruim fine too, but while import brazilian osm , i got this error:

**Reading in file: /srv/nominatim/Nominatim/build/utils/brazil-latest.osm.pbf
Using PBF parser.
Processing: Node(65390k 503.0k/s) Way(0k 0.00k/s) Relation(0 0.00/s)Killed
ERROR: No Data
string(7) "No Data"**

**Comment by mtmail** [comment]
`setup.php` calls `osm2pgsql` (https://github.com/openstreetmap/osm2pgsql) which connects to the postgresql database server to import places.

The "No Data" error usually means the postgresql server crashed and that usually means the computer didn't have enough memory. Checking memory usage when it runs or looking at the postgresql server log files can give more hints.

With Brazil I'd say you need 4-6GB of RAM for the first import. After the import Nominatim will work fine with less RAM for querying.
