### ISSUE TITLE
computed postalcode is wrong for Belfaux, Switzerland

### ISSUE THREAD

**Issue by florentx** [openstreetmap/Nominatim#1506]
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=194734552&class=highway

The postal code for Belfaux is always 1782, but it's reported incorrectly as 1721 and 1772 in the API.

**Comment by lonvia** [comment]
This is a data issue There are a [couple of housenumbers mapped](https://osm.li/VwD) with that postcode but there is no information that all of Belfaux is 1782. In particular, there is no address with that house number near the street you mention.
