### ISSUE TITLE
Region off by one

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/Nominatim#1510]
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=427311148&class=building
not only lies within
https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3369180&class=boundary
but also closer to its center.

However for some reason the next door neighbor region
https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=3369179&class=boundary
is returned instead, on top and in bold, in the list.

**Comment by mtmail** [comment]
The building (https://www.openstreetmap.org/way/427311148) is assigned to a street a bit further north using the `addr:street` tag.

Nominatim looks up address hierarchy by the street, not the house number, which can often go wrong if a street crosses city or even country borders.

Usually checking exactly where the house is against everything the road crosses (very long roads could cross many villages) would be slow. But in this case Nominatim already has multiple village candidates and could use more logic to select the correct one.

(Distance in the table is rounded to 0, the raw distance Nominatim uses is "Qingdong Village"=0.0103140971516797, "Qingfu Village"=0.0126995779502792)

https://overpass-turbo.eu/s/MD6

![image](https://user-images.githubusercontent.com/3727288/65695421-d32a3700-e077-11e9-8fed-4494bbed8318.png)

**Comment by jidanni** [comment]
OK, on https://www.openstreetmap.org/way/427311148
let's take a look 'addr:street	慶福街'
https://www.openstreetmap.org/search?query=%E6%85%B6%E7%A6%8F%E8%A1%97#map=19/24.18987/120.86389

```
Search Results
Results from OpenStreetMap Nominatim
Tertiary Road 慶福街, Qingfu Village, Wuyaokeng, Dongshi District, Taichung, 42351, TW

Tertiary Road 慶福街, Qingdong Village, 麻竹坑頭, Dongshi District, Taichung, 42351, Taiwan

Tertiary Road 慶福街, Qingfu Village, Beilong, Dongshi District, Taichung, 42351, TW

Tertiary Road 慶福街, Qingfu Village, Dapingjiao, Dongshi District, Taichung, 42351, TW

Tertiary Road 慶福街, Qingfu Village, 軟埤坑, Dongshi District, Taichung, 42351, TW

Residential Road 青福街, 清水里, Qingshui, Tucheng District, New Taipei, 23653, TW
```

Well, none of them (top priority seems to be short bridge segments) even
list the closest same named segment we actually drive on,
https://www.openstreetmap.org/way/228962642 .

Nor nearby segment, https://www.openstreetmap.org/way/704234166 .

Anyway indeed often a house is just over a ridge line, putting it in
district B, when its road, and thus official address, etc. are in
district A and it would be smart to still say district A. But in this
case we see a total breakdown.

Also one could say well those segments of the road should all be joined.
But sometimes the surface or number of lanes etc. are different, right?

P.S., I've written [quite a lot](https://www.jidanni.org/geo/house_numbering/) about house numbering in Taiwan.

**Comment by mtmail** [comment]
Conceptually it's already hard to merge the street sections (OSM ways) together, just think about a round-about, dual lanes or a bridge which has a different name. It's not (yet) attempted though for performance reason. Nominatim does a lot at search time and would need to lookup all the other streets by name name in another database query. Other search engines which put more logic in regular data build processes have an advantage here. As you observed searching for the road name will give a list but it's unsorted.

> often a house is just over a ridge line, putting it in district B, when its road, and thus official address, etc. are in district A

We'll check if Nominatim can set the hierarchy different (based on building, not street) here.

The https://www.jidanni.org/geo/house_numbering/ page is great!

**Comment by jidanni** [comment]
Well all I know is
https://www.openstreetmap.org/search?whereami=1&query=25.8601%2C-97.4099#map=15/25.8601/-97.4099
magically always knows which side of an international border it is on, while
https://www.openstreetmap.org/search?whereami=1&query=24.20302%2C120.86496#map=17/24.20302/120.86496
on the other hand can't even get the village right.

**Comment by lonvia** [comment]
There are a couple of tickets about this already. Closing here.

**Comment by jidanni** [comment]
Maybe you could link one of them here so I can find it. Thanks.
