### ISSUE TITLE
Search returning result outside of viewbox with bounded=1

### ISSUE THREAD

**Issue by TheDziekan** [openstreetmap/Nominatim#1512]
From my understanding when using `bounded=1` search should only give results that are inside provided `viewbox`.  So when using `viewbox=52.25, 20.97, 52.27, 20.99&bounded=1` search result with coordinates ```"lat": "52.2621474", "lon": "20.9863369"``` should be included But result with coordinates ```"lat": "52.2115691", "lon": "20.9750474"``` should be not included (excluded). because `52.2115691` is not in the `52.25<x<52.27` range.

Query I'm using:
```
https://nominatim.openstreetmap.org/search?q=Bitwy, Warszawa&viewbox=52.25, 20.97, 52.27, 20.99&bounded=1&format=jsonv2
```

Query with result I'm expecting:
```
https://nominatim.openstreetmap.org/search?q=Bitwy pod Rokitną, Warszawa&viewbox=52.25, 20.97, 52.27, 20.99&bounded=1&format=jsonv2
```

Am I understanding it wrong? Am I using it wrong? What can I do to get the results I'm expecting?

**Comment by lonvia** [comment]
The format for the viewbox parameter is `<x1>,<y1>,<x2>,<y2>` or `<lon1>,<lat1>,<lon2>,<lat2>`.

**Comment by TheDziekan** [comment]
> The format for the viewbox parameter is `<x1>,<y1>,<x2>,<y2>` or `<lon1>,<lat1>,<lon2>,<lat2>`.

Everything works fine now. Thank you! For me `<x>` represents horizontal lines and that is how latitude is drawn on the maps. Know it's clear that they meant position of longitude on x axis. It would be great to have documentation updated to  `<lon1>,<lat1>,<lon2>,<lat2>` to avoid confusion. Especially that bounding box returned by api uses completely different format of: `Comma separated list of min latitude, max latitude, min longitude, max longitude.`
