### ISSUE TITLE
Not getting Street Address

### ISSUE THREAD

**Issue by techsolic** [openstreetmap/Nominatim#1515]
Hello, 
I install Nominatim on my server and import data from geofabrik.de for GCC only.
https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf

Its working fine but the issue is in zoom level even at zoom level-18 i am not getting street address.

When i try to fetch address using level 18 on nominatim.openstreetmap.org it return complete address
https://www.screencast.com/t/nQSSNAErA0q
and when i try same query param on my server i receive only area address 
https://www.screencast.com/t/a7Vf0n4t

**Comment by lonvia** [comment]
Did the installation finish successfully? Please provide a link to the installation log.

**Comment by techsolic** [comment]
@lonvia Thank you for your response.

It was hint actually when i check the log there was issue during installation after fixing that it works fine. Thanks Appreciated
