### ISSUE TITLE
Quarters are not shown in addresses

### ISSUE THREAD

**Issue by A67-A67** [openstreetmap/Nominatim#1516]
Example: [here](https://www.openstreetmap.org/search?whereami=1&query=51.9960%2C4.3548#map=16/51.9960/4.3548) when I ask for the address almost on the place-node of Voorhof, this name isn't shown in the address. It shows Poptahof (a nearby neighbourhood within Voorhof) but not Voorhof.

It seems Nominatim skips one step in the [urban place hierarchy](https://wiki.openstreetmap.org/wiki/Key:place#Populated_settlements.2C_urban). So it shows neighbourhoods and suburbs but not the quarters, even when the name of the quarter is a name that people actually use like Voorhof.

PS. place=quarter has been [approved ](https://wiki.openstreetmap.org/wiki/Proposed_features/place%3Dquarter) more than 7 years ago.

**Comment by lonvia** [comment]
The change is in production, however note that I have not updated existing entries in the database. The quarters will sort themselves out with time.
