### ISSUE TITLE
Result without `osm_id` and `osm_type`

### ISSUE THREAD

**Issue by Gustry** [openstreetmap/Nominatim#1521]
I have this request to Nominatim:
https://nominatim.openstreetmap.org/search?q=ho%20chi%20minh&format=geojson

The second result (index 1) doesn't have `osm_id` and `osm_type`, compare to other result. From which source this point is coming? Is Nominatim using another source than OSM?
Why these `osm_*` are missing from this result? So I'm not sure if it's a bug or a feature?

Thanks

**Comment by lonvia** [comment]
The results is an artificatial postcode centroid. We compute them from the available postcodes in OSM. So they are an aggregate that do not have ids themselves.

The other data that might be returned potentially without an OSM id are housenumbers in the US when they come from the TIGER dataset.

**Comment by Gustry** [comment]
Ok, thanks. So I might get non OSM object when it's `type=postcode`?

Is-it somewhere in the documentation?

Thanks for your answer. I will close the ticket because you have answered it.
