### ISSUE TITLE
Wrong city returned

### ISSUE THREAD

**Issue by danielematteucci** [openstreetmap/Nominatim#1522]
Searching for
Modena, Viale Vittorio Veneto
returns
Viale Vittorio Veneto, Novi di Modena,

**Comment by lonvia** [comment]
What is the issue? What do you expect?

**Comment by lonvia** [comment]
Reporter did not answer follow-up questions. Closing.

**Comment by danielematteucci** [comment]
Apologize for delay, the message was in spam.
I search the address "**Modena**, Viale Vittorio Veneto".
The geocoding returns "Viale Vittorio Veneto, **Novi** di Modena", that is another city.

**Comment by lonvia** [comment]
Please read https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md#when-reporting-bad-search-results
