### ISSUE TITLE
PHP message: PHP Notice:  Uninitialized string offset: 0 in /srv/nominatim/website/search.php on line 53

### ISSUE THREAD

**Issue by MatthiasLohr** [openstreetmap/Nominatim#1523]
Hi,

my logs are full with the following error:
```
PHP message: PHP Notice:  Uninitialized string offset: 0 in /srv/nominatim/website/search.php on line 53
```

In the [Code](https://github.com/openstreetmap/Nominatim/blob/master/website/search.php#L53) is:
```php
if (!$oGeocode->getQueryString()
    && isset($_SERVER['PATH_INFO'])
    && $_SERVER['PATH_INFO'][0] == '/'
) {
```

Maybe there is a check for `&& strlen($_SERVER['PATH_INFO']) > 0` missing?

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Thank you for merging so fast. Can you please issue a patch release? Thanks!

**Comment by lonvia** [comment]
There is going to be a new release within the next month anyway because there is a [bug in osm2pgsql](https://github.com/openstreetmap/osm2pgsql/pull/960) that I consider critical. I kindly ask for your patience until then.
