### ISSUE TITLE
Minutely updates for a region

### ISSUE THREAD

**Issue by julienfastre** [openstreetmap/Nominatim#1525]
I have a working installation of Nominatim, which covers the whole Europe.

Applying a daily diff for whole Europe (which are available using geofabrik) lasts for... a couple of days. 

However, applying minutely diff from the whole world works perfectly well. But I think that fill the database with objects without Europe. 

This is not a huge problem, but I would like to avoid it.

Using osmium-tool, we get the possibility to extract subset of minutely diff:

```bash
osmium extract -p europe.poly -o diff.eu.osc.gz diff.osc.gz
```
I think I can use the process described in #60 to apply this filter on the minutely diff before processing it with `update.php`.

I was also thinking about adding an option to the file `update.php` to add this possibility to extract part of the data from a polygon file. This would require another dependencies (`osmium-tools`). 

Is it a good idea, or not ?

If this is a good idea, I can prepare a PR.

**Comment by lonvia** [comment]
I recommend to rather find out what's going wrong with the daily updates. It should be possible to apply those easily. I've had reports of people doing that successfully. Applying a daily diff of Europe shouldn't take longer than half an hour.

Can you describe your setup in more detail? (Nominatim version and config, hardware configuration, OS, Postgresql version and configuration tweaks that you have done)

**Comment by julienfastre** [comment]
I use:

* nominatim version 3.3.0 (hum... I realize I use the HEAD of master branch)
* postgresql 11.5
* postgis 2.5 
* Intel Xeon-E 2288G - 8c/ 16t - 3.7GHz
* Gb RAM
* 2 ssd / nvme disk in software RAID 1

Configuration of postgresql (difference with the original `postgreql.conf` file installed by package) :

```
shared_buffers = 2GB
work_mem = 50MB
maintenance_work_mem = 10GB
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
effective_cache_size = 24GB
```

Any idea ?

**Comment by matkoniecz** [comment]
> Gb RAM

It seems that you missed number here.

**Comment by lonvia** [comment]
This looks all good (assuming it's 32GB RAM by the looks of the rest).  So the next question would be: where does it hang? Can you provide the log of a an update run that takes so long?

**Comment by julienfastre** [comment]
> > Gb RAM
> 
> It seems that you missed number here.

Yes, it is 32GB ram


> This looks all good (assuming it's 32GB RAM by the looks of the rest). So the next question would be: where does it hang? Can you provide the log of a an update run that takes so long?

Hum, logs are now deleted, but it was blocking at the step "Using XML parser".

**Comment by lonvia** [comment]
Interesting. If you never saw a line like `Processing: Node(440k 440.0k/s) ` appear, then you have definitely hit a bug somewhere with osm2pgsql or with the update configuration. It's well worth going back to the setup and trying again. If you can produce a new log, then that might give a hint what is going on.

**Comment by julienfastre** [comment]
ok: I am going to make a new install on a new server the same way (I kept an ansible script for that), and we will investigate further. I will work on this end of this week / begin of next week.

Do you think I will have to re-install the whole europe data, or just one country will be enough ?

**Comment by lonvia** [comment]
Probably a good idea to try with a small country first. If you don't see the problem there, you can still try Europe.
