### ISSUE TITLE
Possible to add indexable tag, to allow searching for generic terms?

### ISSUE THREAD

**Issue by gitressa** [openstreetmap/Nominatim#1527]
Say we have a community center open for the public called **Culturestation XYZ**, another one called **Culture center ABC**, a third one called something entirely different, etc.

But they one thing they all have in common is that they are all Culture centers open for the community. It would be great to be able to find all places when you search for the generic term "culture center", if we assume this is the word people use for this sort of place. So in essence, is it possible to tag places, fx with a word like "culture center" and get it indexed, to ensure they would all be shown in the search result?

**Comment by gitressa** [comment]
PS. Would adding the generic term to the `alt_name` field work?

**Comment by gitressa** [comment]
To answer myself, terms added via the `alt_name` tag gets indexed and are searchable. Still, it would probably be better with a dedicated, indexed field to generic terms, since using an `alt_name` field might not always be ideal.

**Comment by lonvia** [comment]
Se #2944 for current thoughts on that topic.
