### ISSUE TITLE
Error on Data Import.

### ISSUE THREAD

**Issue by comrade001** [openstreetmap/Nominatim#1529]
When i run  ./utils/setup.php --osm-file mexico-latest.osm.pbf --all
I got this error:
PHP Warning:  Use of undefined constant STDOUT - assumed 'STDOUT' (this will throw an Error in a future version of PHP) in /srv/nominatim/Nominatim/lib/cmd.php on line 200
PHP Warning:  Use of undefined constant STDERR - assumed 'STDERR' (this will throw an Error in a future version of PHP) in /srv/nominatim/Nominatim/lib/cmd.php on line 201
ERROR: unable to run command:createdb -E UTF-8 -p 5432 nominatim
string(57) "unable to run command:createdb -E UTF-8 -p 5432 nominatim"

**Comment by mtmail** [comment]
Which operating system and version and which PHP version are you running?

**Comment by comrade001** [comment]
CentOS 7 and PHP 7.2.23

**Comment by mtmail** [comment]
The PHP warning seems unrelated, I haven't seen that yet in PHP 7.2 I think. I'll check how easy it is to work around the warning or open a separate issue.

As for the error: what happens when you run `createdb -E UTF-8 -p 5432 nominatim` in your terminal? Maybe `createdb` is not found and/or needs to be added to the `$PATH`? We have example install instructions for CentOS 7 at http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/

**Comment by comrade001** [comment]
`[abrahamsa@vps build]$ createdb -E UTF-8 -p 5432 nominatim
[abrahamsa@vps build]$ sudo su postgres
[sudo] password for abrahamsa:
bash-4.2$ psql
psql (9.2.24)
Type "help" for help.

postgres=# \l
                                  List of databases
   Name    |   Owner   | Encoding  |  Collate   |   Ctype    |   Access privileges
-----------+-----------+-----------+------------+------------+-----------------------
 nominatim | abrahamsa | UTF8      | en_US.utf8 | en_US.utf8 |
 postgres  | postgres  | SQL_ASCII | C          | C          |
 template0 | postgres  | SQL_ASCII | C          | C          | =c/postgres          +
           |           |           |            |            | postgres=CTc/postgres
 template1 | postgres  | UTF8      | en_US.utf8 | en_US.utf8 |
(4 rows)

postgres=#
`

**Comment by comrade001** [comment]
I am following the instructions of the [](http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/) to the letter and I get to the same place, any recommendations?

**Comment by lonvia** [comment]
What is the first line in `build/utils/setup.php` (the one that starts with '#!')? Have you changed anything with the default settings of php?

**Comment by comrade001** [comment]
@lonvia my setup.php looks like:
```
nominatim@vps.94177.tapirsolutions.net [~]# cd build/utils/
nominatim@vps.94177.tapirsolutions.net [utils]# ls
country_languages.php  export.php  importWikipedia.php  query.php  setup.php  specialphrases.php  update.php  warm.php
nominatim@vps.94177.tapirsolutions.net [utils]# cat setup.php
#!/bin/php -Cq
<?php
require_once(dirname(dirname(__FILE__)).'/settings/settings.php');
require_once(CONST_BasePath.'/utils/setup.php');
nominatim@vps.94177.tapirsolutions.net [utils]#

```

**Comment by lonvia** [comment]
Looks okay, too. Although I do see that you are now running under a different user. Does the createdb command also work under user nominatim?

**Comment by lonvia** [comment]
Reporter did not answer follow-up questions. Closing.

**Comment by jonsonasMafjiozas** [comment]
@comrade001 I have the same issue, were you able to fix it? any help is much appreciated

**Comment by comrade001** [comment]
Terminé instalandolo con ayuda de Docker y a la fecha no he tenido ni un solo error. Espero la información te sirva. Saludos.
