### ISSUE TITLE
Nominatim not updating some relations

### ISSUE THREAD

**Issue by txtor** [openstreetmap/Nominatim#1530]
Hello. I run a nominatim instance with Europe data since 10 months with daily updates. Since Feb 12th some (a lot of) relations do not update in placex, although these relations update in planet_osm_rels. If I run an sql query for all records that are not up to date, I get the following:

```sql
select count(*), min((r.tags::hstore->'osm_timestamp')::timestamp) ts_from, max((r.tags::hstore->'osm_timestamp')::timestamp) ts_to
from placex x 
	inner join planet_osm_rels r on r.id=x.osm_id
where x.osm_type='R'
	and (x.extratags->'osm_version')::int != (r.tags::hstore->'osm_version')::int;
```	

      count |       ts_from       |        ts_to
     -------+---------------------+---------------------
      73753 | 2019-02-12 12:18:31 | 2019-10-21 20:13:10
 
On exactly Feb 12th I happened to fix an error in my update script which had caused the nominatim update to run in an endless loop. I killed the process and since then the script stops after the first update, if no more data is available. 

Any idea what can cause nominatim to update planet_osm_rels but not placex for some relations?

CentOS Linux release 7.6.1810 (Core)
PostgreSQL 10.6
Postgis  2.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1
Nominatim: https://github.com/woodpeck/Nominatim/tree/everything-in-extratags
git rev-parse HEAD => e706a71958ce2c359309fd47f66b2458575aad50

[Added on Oct 24th] The date Feb 12th above is incorrect. It is March 12th since when updates do not work properly and also when the script fix took place.

**Comment by lonvia** [comment]
Looks like your fixed update script now misses the indexing step after importing the change.

**Comment by txtor** [comment]
Thank you for your comment. It does run the indexing step, actually. A lot of relations get indexed every day, but a lot of them do not.

```sql
nominatim=# select batchend,batchseq,event from import_osmosis_log order by endtime desc limit 4;
      batchend       | batchseq | event
---------------------+----------+--------
 2019-10-22 20:18:00 |     2409 | index
 2019-10-22 20:18:00 |     2409 | import
 2019-10-21 20:18:01 |     2408 | index
 2019-10-21 20:18:01 |     2408 | import

 nominatim=# select indexed_date::date, count(*) from placex where osm_type='R' and indexed_date>'2019-10-20' group by indexed_date::date order by 1 desc;
 indexed_date | count
--------------+-------
 2019-10-23   |   761
 2019-10-22   |   893
 2019-10-21   |   823
 2019-10-20   |   531

```

After executing the following manually, some relations that are included in this changeset are not indexed and remain outdated.
```sql
  wget http://download.geofabrik.de/europe-updates/000/002/403.osc.gz
  gzip -d 403.osc.gz
  ./update.php --import-diff ../../Nominatim/data/403.osc --index
```

**Comment by lonvia** [comment]
If the change to the relation is not relevant for the search index, then there is no update in placex. That's entirely normal and ensures that updates are efficient.

So the question is: are relations not updated that have relevant changes (for example a change in the `name` tag) in above case. If yes, which ones are they?

**Comment by txtor** [comment]
Example: Relation ID  1239634 Heidesheim am Rhein was a municipality, since Jul 1st 2019 it is part of Ingelheim am Rhein. Changeset 71774496 reflects this change. OSM data is correct and Heidesheim has admin_level=9. But in my Nominatim instance it has admin_level=8, even after running:
```
 ./update.php --import-relation 1239634 --import-from-main-api --index
```

**Comment by txtor** [comment]
Another example. Relation ID 533536 Baunatal is not present in my placex, even after running:
```
./update.php --import-relation 533536 --import-from-main-api --index
```

This relation happens to have been for some hours having type=election instead of type=boundary on May 2nd 2019, which would explain missing the record in placex this day. The error was corrected, but my nominatim instance did not recover.

This is not the only municipality to be affected by this concrete changeset. The following relations are missing in my placex for the same reason.

```
Bad Arolsen     R       162356
Bad Emstal      R       453738
Bad Karlshafen  R       1112227
Bad Wildungen   R       443584
Baunatal        R       533536
Breuna          R       162612
Calden          R       455491
Diemelsee       R       199139
Diemelstadt     R       162250
Edertal         R       443585
Grebenstein     R       455422
Habichtswald    R       454707
Hofgeismar      R       1112226
Immenhausen     R       531865
Korbach         R       198578
Lichtenfels     R       198603
Liebenau        R       455279
Naumburg        R       453721
Oberweser       R       1112225
Reinhardshagen  R       943199
Schauenburg     R       533415
Trendelburg     R       1112223
Twistetal       R       198579
Volkmarsen      R       162251
Wahlsburg       R       1112228
Waldeck         R       199138
Willingen       R       198593
Wolfhagen       R       452969
Zierenberg      R       454616
```

**Comment by txtor** [comment]
The problem persists -- there are every day some relations with relevant changes that do not get updated in my nominatim instance, although planet_osm_rels contains the last version, while some other relations are updated correctly. The problem applies also to new relations, that are not created in our nominatim instance.

The nominatim instance had existed for some time updating normally, the update problem appeared the same day I killed a running update process and it persists since then. Is this just correlation or cause-effect?

Has someone experienced a similar problem with a nominatim instance? Any pointers? 
Any ideas about what could possibly break nominatim updates?

**Comment by lonvia** [comment]
I haven't see anything like that for release or master version.

You are running an old version of Nominatim with a custom hack on top. I recommend changing to the latest release of Nominatim. The full extratags can now be configured in the style file, see https://github.com/openstreetmap/Nominatim/pull/1277#issue-243120706. I would recommend a full reimport given that the database is corrupted already.

**Comment by txtor** [comment]
Thank you. Yes, I am going to do that.

In the new instance I would like to check if updates are complete, because if they are not it means I have an error in my installation or update scripts. But with the latest release of Nominatim I cannot check for ``(x.extratags->'osm_version')::int != (r.tags::hstore->'osm_version')::int`` because tags in planet_osm_rels does not contain osm_version nor osm_timestamp. Is it possible to make osm2pgsql store this tags in planet_osm_rels, too?

**Comment by lonvia** [comment]
See https://github.com/openstreetmap/osm2pgsql/pull/905 for meta tags in the place tables and a discussion on whether to put it in the middle tables. You might get away with hacking `--extra-attributes` into the osm2pgsql command line but I would strongly recommend against that. Processing the meta tags makes updates and imports significantly slower because suddenly all new data is processed while Nominatim goes to certain lengths to ensure that only the data that is actually needed and has changed in a way that matters for geocoding is imported/updated.

**Comment by txtor** [comment]
Thanks a lot for the information.

Closing the issue because it won't be further followed, although the problem's cause wasn't elucidated.
