### ISSUE TITLE
CentOS7, postgresql 9.2 - Failed to establish database connection:could not find driver

### ISSUE THREAD

**Issue by dengyichao** [openstreetmap/Nominatim#1533]
Operating system: centos7, when I execute the import data statement, I report the following error. The database cannot be connected. The PostgreSQL version is 9.4. Do you know where I configured it wrong? Or how to configure it in PHP? (I don't know PHP language ~ ~)

`[nominatim@localhost build]$ ./utils/setup.php --osm-file ../data/china-latest.osm.pbf --all 2>&1 | tee setup.log
2019-10-25 11:12:03 == module path: /srv/nominatim/Nominatim/build/module
2019-10-25 11:12:03 == Create DB
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Failed to establish database connection:could not find driver

  thrown in /srv/nominatim/Nominatim/lib/DB.php on line 36`

**Comment by mtmail** [comment]
Which version of Nominatim are you installing? Is PostgreSQL 9.4 the default on CentOS 7 or did you install it later? (I think 9.2 is the default, but I might be wrong).

Assuming version 3.3:

In `build/settings/local.php` you will find a line like `@define('CONST_Database_DSN', 'pgsql:dbname=nominatim');`. If you don't have the file create it, if you don't have the line you can copy it from `build/settings/settings.php`. The DSN format and how to add username, password or such is explained on https://www.php.net/manual/en/ref.pdo-pgsql.connection.php

"could not find driver" sounds more like an installation issue. Try reinstalling the `php-pgsql` yum package.

**Comment by dengyichao** [comment]
Thank you for your guidance. 
Because the default installation of 9.2 indicates that the version is too low in the import, I manually upgrade it to 9.4. After the upgrade, the driver will not be found in the import~~~
[nominatim@localhost build]$  ./utils/setup.php --osm-file ../Nominatim-3.4.0/data/china-latest.osm.pbf --all 2>&1 | tee setup.log
2019-11-01 12:56:15 == module path: /srv/nominatim/build/module
2019-11-01 12:56:15 == Create DB
2019-11-01 12:56:16 == Setup DB
Postgres version found: 9.02
ERROR: Minimum supported version of Postgresql is 9.3.
string(47) "Minimum supported version of Postgresql is 9.3."

**Comment by dengyichao** [comment]
Sorry I forgot to provide the environment data:

CentOS Linux release 7.7.1908 (Core)
Nominatim 3.4.0
PHP 5.4.16 (cli) (built: Oct 30 2018 19:30:51)
psql (PostgreSQL) 9.2.24
Postgis-utils-2.0.7-2.el7.x86_
postgis-2.0.7-2.el7.x86_64

All my configurations are based on https://nominatim.org/release-docs/latest/appendix/install-on-centos-7/ and there is no problem with permissions

**Comment by mtmail** [comment]
I created https://github.com/openstreetmap/Nominatim/pull/1548 to update the install instructions to use postgresql 11. That should work on a new system.

If you want to upgrade databases on existing systems guides like
https://www.shernet.com/postgresql/upgrading-to-postgresql-10-on-centos-7/
https://blog.andreev.it/?p=4381
might help.

**Comment by dengyichao** [comment]
Hello, after I upgraded the database and PostGIS, he showed that the database could not be loaded. I gave Chmod 777 the permission of the file, including its parent class path

[nominatim@localhost build]$  ./utils/setup.php --osm-file ../Nominatim-3.4.0/data/china-latest.osm.pbf --all 2>&1 | tee setup.log
2019-11-04 15:07:02 == module path: /srv/nominatim/build/module
2019-11-04 15:07:02 == Create DB
2019-11-04 15:07:03 == Setup DB
Postgres version found: 9.06
Postgis version found: 2.4
PHP Fatal error:  Uncaught Nominatim\DatabaseError: [500]: Database server failed to load /srv/nominatim/build/module/nominatim.so module
  thrown in /srv/nominatim/Nominatim-3.4.0/lib/DB.php on line 61

My upgrade configuration and directory permissions are:

-rwxrwxrwx. 1 nominatim nominatim  532820931 Oct 30 16:49 china-latest.osm.pbf
chmod -R 777 nominatim/

postgis24_96-utils-2.4.8-5.rhel7.x86_64
postgis24_96-2.4.8-5.rhel7.x86_64

**Comment by dengyichao** [comment]
[nominatim@localhost module]$ sudo -u postgres ls /srv/nominatim/build/module/nominatim.so 
[sudo] password for nominatim: 
/srv/nominatim/build/module/nominatim.so

**Comment by dengyichao** [comment]
nominatim=# \du
                             List of roles
 Role name |                   Attributes                   | Member of 
-----------+------------------------------------------------+-----------
 apache    |                                                | {}
 nominatim | Superuser, Create role, Create DB              | {}
 postgres  | Superuser, Create role, Create DB, Replication | {}

**Comment by mtmail** [comment]
Could it be SELinux related? We have a couple of commands in https://github.com/openstreetmap/Nominatim/blob/master/vagrant/Install-on-Centos-7.sh to mark the file as allowed. Maybe if the file changed (recompiled) those commands need to be rerun again.

**Comment by dengyichao** [comment]
Hello, I don't think so. After upgrading PostgreSQL, I went through the document again.

**Comment by mtmail** [comment]
Can you try to recreate the `build` directory? The `cmake` step caches some assumption (e.g. which libraries to link to). 

```
cd /srv/nominatim/
cp build/settings/local.php /tmp/
rm -r build
mkdir build
cd build
cmake ../Nominatim
make
cp /tmp/local.php settings/local.php
```

I also worry the `chmod -R 777 nominatim/` in your output made files writeable to everybody. There's little (SELinux) security when files can be changes by any user on the system.

Any relevant lines from the postgresql server logs or SELinux logs (`audit.log`, https://wiki.gentoo.org/wiki/SELinux/Tutorials/Where_to_find_SELinux_permission_denial_details) mentioning nominatim or nominatim.so would also help.

For testing you can also temporarily disable SELinux https://www.revsys.com/writings/quicktips/turn-off-selinux.html

**Comment by dengyichao** [comment]
You are so wonderful. Thank you very much for your careful help. I am in the normal warehouse.
