### ISSUE TITLE
Bounding box in output not explained in documentation

### ISSUE THREAD

**Issue by FelixCali** [openstreetmap/Nominatim#1534]
The bounding box which is given for each result in the output as mentioned in output.md is never actually explained anywhere. I assume, it is meant as a suggestion as to which zoom level and center point to use for the map view  when displaying the result (is that true?).

But it is unclear 
1. What it actually represents (e.g. it could also be the outermost coordinates of the given result's shape)
2. How to use it

I would suggest adding the answers to this to the output.md.

**Comment by mtmail** [comment]
Yes, it's just the outermost coordinates. I'll add some more wording. There's also cases around the antimeridian where the boundingbox is useless (as the map would zoom to the whole world) and that should be noted there.

https://nominatim.openstreetmap.org/search.php?q=alaska&format=html&limit=1
https://nominatim.openstreetmap.org/search.php?q=alaska&format=json&limit=1
