### ISSUE TITLE
Wrong city returned

### ISSUE THREAD

**Issue by danielematteucci** [openstreetmap/Nominatim#1538]
What is the issue? What do you expect?

Ionvia, I look for "Viale Vittorio Veneto, city MODENA"
And the geocoding returns the coordinated of "Viale Vittorio Veneto, city NOVI DI MODENA"

So, the street is the same, but the city is wrong.

_Originally posted by @lonvia in https://github.com/openstreetmap/Nominatim/issues/1522#issuecomment-541585468_

**Comment by lonvia** [comment]
There is still not more information than in the original ticket. Please read https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md#when-reporting-bad-search-results
