### ISSUE TITLE
Unable to geocode "0" addresses 

### ISSUE THREAD

**Issue by james2432** [openstreetmap/Nominatim#1541]
https://www.openstreetmap.org/search?query=2%20Tiffany%20Crescent%2C%20ottawa#map=19/45.32448/-75.90467

Resolves fine.

https://www.openstreetmap.org/search?query=0%20Tiffany%20Crescent%2C%20ottawa#map=19/45.32448/-75.90467

Does not.

https://www.openstreetmap.org/way/473030197#map=19/45.32415/-75.90395

Yes that's the accurate address. We've asked the city.

**Comment by lonvia** [comment]
Fixed in #1544.
