### ISSUE TITLE
Degraded performance of nominatim.openstreetmap.org API

### ISSUE THREAD

**Issue by ptodorov0** [openstreetmap/Nominatim#1543]
Not sure if this is the place to discuss a problem with the free nominatim.openstreetmap.org API. Since 10:10 GMT yesterday (10/29/2019) some of the requests to nominatim.openstreetmap.org/reverse.php are answered slowly and some are timing out completely.

In my case, the requests to the API are working for 30 minutes without any issues and then it starts to answer slowly (3+ seconds) and requests are timing out for several minutes and than it returns back to normal again. Do you have any information about the server status? It is a free service after all so I am sorry if I'm asking for too much.

**Comment by mtmail** [comment]
I think it's tracked in https://github.com/openstreetmap/operations/issues/337
