### ISSUE TITLE
computed PostalCode how does it really work ?

### ISSUE THREAD

**Issue by fabella01** [openstreetmap/Nominatim#1546]
Hi,
i try for example this link: 
https://nominatim.openstreetmap.org/details.php?place_id=270872672

the informations given by nominatim are ->

Computed Postcode | K32 WV18
Address Tags | Dublin (city)13 (housenumber)Matello Place (street)

When i check the database ireland*.osm, the only information that i have about this postal code is:

&lt;way id="505078947" version="2" timestamp="2019-04-19T13:56:26Z" uid="0" user=""&gt;
     &lt;nd ref="4951113850"/&gt;
     &lt;nd ref="4951113851"/&gt;
     &lt;nd ref="......." /&gt;
     &lt;nd ref="4951113850"/&gt;
     &lt;tag k="addr:city" v="Balbriggan"/&gt;
     &lt;tag k="addr:postcode" v="K32 WV18"/&gt;
     &lt;tag k="addr:street" v="Clonard Road"/&gt;
     &lt;tag k="building" v="school"/&gt;
  &lt;/way&gt;

When you look at the information given by the detail, I did not find the relation (or the computation) allowing to reach the node containing "addr: postal code".

An explanation to help?
thanks a lot

**Comment by mtmail** [comment]
Looks like the same feature requests as https://github.com/openstreetmap/Nominatim/issues/607

> how does it really work ?

One per night all same postcodes are grouped together and a center point is calculated. The calculation is pretty basic (see `sql/update-postcodes.sql`). In some countries one postcode is often one place, in others one postcode can be the result of 1000s of places. There's no logic to create boundaries or relations. While calculated postcodes are a database records, they're separated from places (`place` table) and don't have a `osm_id` or `place_id`.

What originally brought you to the details.php page? Which address did you search for? Did you open this issue to ask for clarification or report a bug?

**Comment by lonvia** [comment]
Please also read https://www.openstreetmap.org/user/lonvia/diary/43143 for details on postcode computation.
