### ISSUE TITLE
Boundary data for San Francisco, CA, USA is wrong

### ISSUE THREAD

**Issue by krazytechbizsolutions** [openstreetmap/Nominatim#1547]
When I search for San Francisco CA, it correctly shows San Francisco, but the boundaries are incorrect. It covers much of the surrounding sea and there is An island also shown incorrectly...

**Comment by krazytechbizsolutions** [comment]
![Screenshot_20191101-192559](https://user-images.githubusercontent.com/44490884/68071144-97cd0780-fd9d-11e9-9a82-1b00963a7e4a.jpg)

**Comment by mtmail** [comment]
Nominatim is a software to search over OpenStreetMap data. The place https://www.openstreetmap.org/relation/111968 is returned which represents San Fransciso.

If you disagree with data of that place contact local mappers. https://www.openstreetmap.org/fixthemap https://lists.openstreetmap.org/listinfo/talk-us-sfbay
