### ISSUE TITLE
How can i see my local state.txt?

### ISSUE THREAD

**Issue by itz-sudo** [openstreetmap/Nominatim#1552]
I want to write some script to compare my local nominaitm sequence number and online nominatim sequence number. In order to do that, i would like to use state.txt. But i don't see it in my local. How can i generate it?

**Comment by mtmail** [comment]
The `utils/update.php` script (which calls `utils/check_server_for_updates.py`) does something like that.

```
$ /srv/nominatim/Nominatim/build/utils/update.php --check-for-updates
Database up to date.
```

If it's not up-to-date it prints something like `New data available (2500=> 2499).`

**Comment by itz-sudo** [comment]
@mtmail thank you so much. This will help me. By the way, is it possible to create state.txt for my local nominatim db, so that i can access via apache like this 127.0.0.1:80/replication/hour/state.txt. similar to how we are checking in online https://planet.openstreetmap.org/replication/hour/state.txt

**Comment by mtmail** [comment]
Probably, but that sound like too much work.

The `/status.php` URL already returns a parse-able date of the last database update.

```
curl -S http://localhost:80/nominatim/status.php?format=json
{"status":0,"message":"OK","data_updated":"2019-10-29T14:13:06+00:00"}
```

You could add the sequence number there. E.g. add a method to `lib/Status.php` running a database query like
```
$aLastState = $oDB->getRow('SELECT sequence_id FROM import_status');
```
and have `website/status.php` add that to the returned JSON.

**Comment by itz-sudo** [comment]
Thanks a lot. This works
