### ISSUE TITLE
Import fails on Oracle Linux 8 when password is supplied in locale.php

### ISSUE THREAD

**Issue by GenuineGuineapig** [openstreetmap/Nominatim#1553]
Hi, I've encoutered a problem when a password is specified in the locale.php. 

My locale.php: 
`<?php
   @define('CONST_Database_DSN', 'pgsql:dbname=nominatim;host=10.0.2.11;user=nominatim;password=password');
   @define('CONST_Website_BaseURL', 'http://10.0.2.11:8080/');
   @define('CONST_Database_Web_User', 'nominatim');`

The problem I'm encountering is that the script will complain about not finding createdb and psql (which both are there and function fine), and finally crash when it comes to the CREATE EXTENSION IF NOT EXISTS part.

The output is like this:
2019-11-05 11:19:21 == module path: /srv/nominatim/build/module
2019-11-05 11:19:21 == Create DB
Execute: createdb -E UTF-8 -p 5432 nominatim -U nominatim -h 10.0.2.12
could not find a "createdb" to execute
2019-11-05 11:19:22 == Setup DB
Postgres version found: 10
could not find a "psql" to execute
could not find a "psql" to execute
psql: could not find own program executable
ERROR: pgsql returned with error code (1)
string(34) "pgsql returned with error code (1)"
 

I'm not sure what exactly is causing this, however I found a workaround: Since nominatim sets the password as an environmental variable, one can simply set the variable PGPASSWORD=yourpassword infront of calling the php script, resulting in an successful import.

Versions:
PHP 7.2.11
Nominatim 3.3.0
PostGIS 2.5
PostgresQL 10.6
Oracle Linux 8

**Comment by mtmail** [comment]
> Since nominatim sets the password as an environmental variable

Just to clarify: Nominatim doesn't set that environment variable. But when executing the `psql` shell command psql will also look at the environment variable you set.

> [utils/setup.php] will complain about not finding createdb and psql (which both are there and function fine)

I've seen that when the directory of those binaries isn't in the `$PATH` environment variable, e.g. `/usr/pgsql-11/bin`. Then I add it in my environment, e.g.
```
    echo 'PATH=$PATH:/usr/pgsql-11/bin' > .bash_profile
    source .bash_profile
```
but forget to do the same for user `nominatim`.

Can you share the password? Or give a hint if there's anything special about the password? I see the value doesn't get escaped (https://www.php.net/manual/en/function.escapeshellarg.php) when the shell command string is generated so a space, quote (', ") or semicolon will make it fail. I'll add escaping but having a real test case would help.

**Comment by GenuineGuineapig** [comment]
> Just to clarify: Nominatim doesn't set that environment variable. But when executing the psql shell command psql will also look at the environment variable you set

Okay, I you're the expert here :-). I only saw that it's put relatively early in the ENV variable for proc_open and figured that it'll be for the environment for the process. (https://github.com/openstreetmap/Nominatim/blob/master/lib/setup/SetupClass.php#L888) Guess I was wrong. 

> I've seen that when the directory of those binaries isn't in the $PATH environment variable, e.g. /usr/pgsql-11/bin.

That was my initial guess too, however I made sure that they are in the path. I ran it as root aswell as the postgres user on the box; behavior stayed the same. Another thing is that createdb seems to work, as the database is created afterwards (and I have to drop it so that it doesn't complain about it already existing..) and also that the Returncode is zero, as it clearly steps into setupDB instead of failing.

>Can you share the password?

Sure, it is "ChangeMe!" (without quotation marks). When the setup is over, I add the password in the exact fashion to the locale.php again, and nominamtim works as intended.

**Comment by mtmail** [comment]
I was wrong. Indeed the password is never put into the shell command but rather set as environment variable.

https://github.com/openstreetmap/Nominatim/pull/1555 adds proper escaping. I tested it with a `ChangeMe!` password and ran a full setup/import.

PHP PDO (database abstraction) library can't handle spaces in passwords, the DSN configuration string can't be parsed if a password contains `=` or `;`, but otherwise any other password should work now.
