### ISSUE TITLE
Where is nominatim.xml?

### ISSUE THREAD

**Issue by MatthiasLohr** [openstreetmap/Nominatim#1554]
Hi,

I just realized, that my webserver is complaining about the missing file `nominatim.xml`. In `lib/template/includes/html-header.php`, it's referenced:
```html
<link href="nominatim.xml" rel="search" title="Nominatim Search" type="application/opensearchdescription+xml" />
```
But it's not in the repository and it's the only reference, so I assume that (for now) it is not to be generated. How to create that file/where to find it?

Best regards
Matthias

**Comment by mtmail** [comment]
I can't find such a file in any history (going back 10 years) in the repository. I think only https://nominatim.openstreetmap.org/nominatim.xml uses it. 

You'd basically place that file in the `build/website/` directory and replace the URL in `<Url ...` with yours. https://developer.mozilla.org/en-US/docs/Web/OpenSearch

Browsers still support such a file, it allows users to quickly add the current website as a search engine. That said I think users rarely do, it's from a time when the address box and search box in browsers were still separate. Example https://www.oldies.com/about/opensearch.cfm I've read Mozilla is deprecating support somewhat https://discourse.mozilla.org/t/deprecation-of-opensearch-xml-add-ons-current-users/46868

**Comment by MatthiasLohr** [comment]
Then I would suggest being consistent: Either add the file `nominatim.xml` or remove the reference from the html header.

It would also be possible to do a check (since it's a PHP file): If `nominatim.xml` is there, add the reference, otherwise do not add it.

**Comment by lonvia** [comment]
The line should be in the fork for openstreetmap only. I'll look into that.

**Comment by MatthiasLohr** [comment]
Thanks :)
