### ISSUE TITLE
Valid ZIP Codes Not Populating Information

### ISSUE THREAD

**Issue by eegler-32bj** [openstreetmap/Nominatim#1561]
The following strings return no results in Nominatim:
"214TH ST SE BOTHELL WA 98021"
"BOTHELL WA 98021"

The string "98021" retrieves two unrelated locations: A bus stop in San Diego County, CA, and another bus stop in the Canary Islands.

While the string 
"214TH ST SE BOTHELL WA" retrieves information similar to expectations but with a Postcode value of 9802133.

Similarly, the following strings do not return results:
"TX 6 MISSOURI CITY TX 77459"
"MISSOURI CITY TX 77459"

The string "77459" returns results for a bus stop in Rome, Italy, while the string "TX 6 MISSOURI CITY TX" returns results with the correct postcode value, but no OSM value assigned to it.

**Comment by mtmail** [comment]
* When searching for just a postcode, 4 digit or 5 digit, add the country as well. Many countries have 5 digit postcodes, Nominatim has no idea which country you mean.

* The postcode 98021, US is indeed not in OpenStreetMap data yet. Somebody has to add it. For example one could see the postcode on a primary source like https://www.stonemeadowfarmsliving.com/Contact.aspx and add it a building of those apartments https://www.openstreetmap.org/way/441372460

* The postcode 9802133, US look like an error. This building has the postcode https://www.openstreetmap.org/way/567157037 all others nearby just 98021. Somebody needs to edit the building

* 77459 is found when you add 'US', 'United States' or 'Texas' to the query. But the result seems to point to a '77459-' postcode of the building https://www.openstreetmap.org/way/427273489 That looks like an error. There's another 668 addresses with the postcode 77459. I'd say fixing the building will make the postcode calculation use the other 668 ones.

* Missouri City has a weird shape https://www.openstreetmap.org/relation/114550 It's the official boundaries which probably don't reflect what people living there see as the city limits.

We have a bit of background how postcode calculation works, it runs once per night (London, UK timezone) https://www.openstreetmap.org/user/lonvia/diary/43143

I know I'm vague on who will fix the OpenStreetMap data. You can fix it https://www.openstreetmap.org/fixthemap https://welcome.openstreetmap.org/ or find a local group of mappers to help https://openstreetmap.community/ There's no central issue tracker for data problems.

**Comment by mtmail** [comment]
I worked on some invalid US postcode data cleanup.

* `98021` is now found on my installation, but not on nominatim.osm.org. Could be places with that postcode need to be force-updated in that database. On a new nominatim installation the query would likely work

```
Nominatim/build$ ./utils/query.php --search '98021' --limit 1'
  "-122.216101308712",
  "47.7903094603821",
  "Bothell, Washington, 98021, USA"
```

* As above `214TH ST SE BOTHELL WA 98021` works on my installation now and returns `214th Street Southeast, Canyon Park, Bothell, Snohomish County, Washington, 98012-7134, USA`

* `TX 6 MISSOURI CITY TX 77459` works now https://nominatim.openstreetmap.org/search.php?q=TX+6+MISSOURI+CITY+TX+77459 (`Alvin Sugarland Road` is also `TX 6`, some roads, especially state highways, can have multiple names, https://www.openstreetmap.org/way/422711697)
