### ISSUE TITLE
Need state_code(ISO_3166-2) in the search response

### ISSUE THREAD

**Issue by mathavan-m** [openstreetmap/Nominatim#1562]
Hai,
	Is it possible to get state_code(ISO_3166-2) in response for the following apis Search and Reverse.

Thanks

**Comment by lonvia** [comment]
The state code is part of the [addressdetails](http://nominatim.org/release-docs/latest/api/Search/#output-details).

**Comment by lonvia** [comment]
Ah, sorry, state code, not country code. We don't do that.
