### ISSUE TITLE
Nominatim in Docker

### ISSUE THREAD

**Issue by winsento** [openstreetmap/Nominatim#1565]
Hello.

Maybe we can add docker support for Nominatim. We can combine with my project: https://github.com/mediagis/nominatim-docker

**Comment by lonvia** [comment]
This has been discussed a couple of times and the answer is still: no. We simply can't handle support for this.

**Comment by doelink413** [comment]
Hello. So it means that we can directly download the Nominatim in docker and combine with the osrm right?

**Comment by mtmail** [comment]
@doelink413 What lonvis is saying is that we cannot handle docker support. Both time and experience-wise.

**Comment by doelink413** [comment]
> @doelink413 What lonvia is saying is that we cannot handle docker support. Both time and experience-wise.

Thank you. So the support of docker is still not stable and we best to install it in a server like the official document?

**Comment by mtmail** [comment]
We do our best to help when you run into issues with any installation instructions on http://nominatim.org/release-docs/latest/ (including the script in https://github.com/openstreetmap/Nominatim/tree/master/vagrant).

For docker you'd need to ask in https://github.com/mediagis/nominatim-docker/

**Comment by doelink413** [comment]
It looks so good. Thank you very much.

**Comment by lonvia** [comment]
@winsento I see you now send people over to this issue tracker to rally for support. I am not amused. I'm sorry if you find maintenance and community support too much work, but off-loading this to us is not a solution. We are busy enough with keeping the software itself running. We cannot do docker. Please remove the note from your repo. Locking this issue.
