### ISSUE TITLE
Can't search with housenumbers & nominatim return search results in a weird format.

### ISSUE THREAD

**Issue by Magnuspil** [openstreetmap/Nominatim#1567]
Hi,

When we try to search for an address with a house number (e.g. Testroad 4, 4400 Testcity)
It can't locate it, only half the times. The output doesn't show housenumbers, and the postcode is not placed before city. Is this format: Roadname + House number, Postcode + City, Country)

Here is our raw code: https://gist.github.com/Magnuspil/9d85c709b0af0943a6ee34367c72a58e
How come we can't search with house numbers all the time, and how come our dropdown doesnt show the housenumber? 

Lastly, is it possible somehow to create that above format?

Thank you very much in advance!

**Comment by mtmail** [comment]
The ordering of postcode<->city and housenumber<->street doesn't matter. It helps to set a comma, I see you already do that.
To give a meaningful answer you should list a couple of addresses that can't be found. The format looks alright, I'd say it's missing data. OpenStreetMap after all doesn't have all streets in the world (yet).

**Comment by Magnuspil** [comment]
> The ordering of postcode<->city and housenumber<->street doesn't matter. It helps to set a comma, I see you already do that.
> To give a meaningful answer you should list a couple of addresses that can't be found. The format looks alright, I'd say it's missing data. OpenStreetMap after all doesn't have all streets in the world (yet).

Hi,

Thank you for a quick answer.
As an example, the following address can't be found: _vindingvej 4, 8654 Bryrup_ when entering in search input as a whole. If we separate the query, and typing _vindingvej 4_, it successfully finds the correct address, and it can find the city aswell by typing only postalcode and city name (query entry: 8654 Bryrup). It successfully find the address by typing: _Vindingvej 4, 8654_ (no cityname) It just fails when entering it as one full query.

The main issue is, the format on the dropdown. It shows no housenumber when searching and the output format should just be Road + housenumber, postalcode + city, Region, Country. Would that even be possible?

**Comment by mtmail** [comment]
I found the house in the OpenStreetMap data, so we can rule out missing data at least. https://www.openstreetmap.org/node/973792685 https://nominatim.openstreetmap.org/details?osmtype=N&osmid=973792685

On quick glance I'd say the the boundaries of the village https://www.openstreetmap.org/relation/9640722 are too strict. And you say it's a city.

The returned address format is very simple only. It orders all address components from small (name or house number) to large (country) for all countries. It's a old feature request to format it based on country, have less components or order them differently. https://github.com/openstreetmap/Nominatim/issues/213 lists another library one can use, I'm not sure if it can be used in a browser/JS environment. In your script you use &format=json If you use &format=jsonv2&addressdetails=1 you could use the address components and construct a more fitting string.

**Comment by lonvia** [comment]
Basically the same issue as with US postal towns where the administrative areas are smaller than the postal areas, see #1120. Closing here.
