### ISSUE TITLE
Unable to get building in nominatim

### ISSUE THREAD

**Issue by james2432** [openstreetmap/Nominatim#1569]
https://www.openstreetmap.org/way/68586619#map=19/45.44560/-75.64566

https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=68586619

Nominatim doesn't seem to be picking it up.

More examples:
https://www.openstreetmap.org/way/68586354
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=68586354
https://www.openstreetmap.org/way/68586284
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=68586284

**Comment by lonvia** [comment]
Not quite sure what happened there. Either a glitch in the update files or the last changes on these buildings fixed a geometry issue by moving around nodes. In any case, reimporting then worked without issues.
