### ISSUE TITLE
state.txt: failed 404 Not Found

### ISSUE THREAD

**Issue by ahinckel** [openstreetmap/Nominatim#1571]
Good afternoon Dear,

I would like support regarding upgrading the database with the /opt/osm/nominatim/utils/setup.php --ososis-init command

As of 2019/03/11 was working correctly, but is now displaying the error message.

PHP Warning: file_get_contents (http://download.geofabrik.de/south-america/brazil-updates/000/001/001/.state.txt): failed to open stream: HTTP request failed! HTTP / 1.1 404 Not Found  in /opt/osm/Nominatim-2.5.1/utils/setup.php on line 638
ERROR: unable to get state file
unable to get state file

Has the directory changed where updates are being made available? How can I solve the problem?

Software used
Nominatim-2.5.1
osmosis 0.47

thank you already the support!

**Comment by mtmail** [comment]
geofabrik only keeps the last 90 days of files. If your data was last updated in March you need to start a complete reimport.

**Comment by ahinckel** [comment]
thanks for the feedback!
I'll be performing the procedure and soon return

Att

**Comment by mtmail** [comment]
Open a new issue if you run into trouble. If you can also update the software. Nominatim 2.5.1 is 3 years old http://nominatim.org/release-history/

**Comment by ahinckel** [comment]
Good Morning

After re-importing the map, it did not present the previously reported issue. This is presenting the message below, but I believe it is something with the update time, I will be trying to update in the coming days.

2019-11-19 11:03:15 Replication Delay is 777659
/opt/osm/osmosis/bin/osmosis --read-replication-interval workingDirectory=/opt/osm/Nominatim-2.5.1/settings --simplify-change --write-xml-change /opt/osm/Nominatim-2.5.1/data/osmosischange.osc
Nov 19, 2019 9:03:15 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMAÇÕES: Osmosis Version 0.45
Nov 19, 2019 9:03:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMAÇÕES: Preparing pipeline.
Nov 19, 2019 9:03:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMAÇÕES: Launching pipeline execution.
Nov 19, 2019 9:03:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFORMAÇÕES: Pipeline executing, waiting for completion.
Nov 19, 2019 9:03:17 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
GRAVE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read the changeset file 000/002/428.osc.gz from the server.
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.downloadReplicationFile(BaseReplicationDownloader.java:135)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.download(BaseReplicationDownloader.java:264)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:304)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:383)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Server returned HTTP response code: 429 for URL: http://download.geofabrik.de/south-america/brazil-updates/000/002/428.osc.gz
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.downloadReplicationFile(BaseReplicationDownloader.java:109)
        ... 4 more

Nov 19, 2019 9:03:17 AM org.openstreetmap.osmosis.core.Osmosis main
GRAVE: Execution aborted.

Att

**Comment by ahinckel** [comment]
> Open a new issue if you run into trouble. If you can also update the software. Nominatim 2.5.1 is 3 years old http://nominatim.org/release-history/

yes i will be evaluating the update. We are currently using Nominatim in conjunction with Python-generated Tiles.

**Comment by mtmail** [comment]
HTTP status 429 usually means the server is overloaded and you can try again later. https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

**Comment by ahinckel** [comment]
Thanks for the help, I was able to upgrade successfully.

The Nominatim system is awesome

Att
