### ISSUE TITLE
'No search results found' when searching by full address

### ISSUE THREAD

**Issue by KSENI** [openstreetmap/Nominatim#1572]
Hi,
Now when find for address with street, number, country and postcode, for example, "ул. Мира, 34А, Екатеринбург, Свердловская обл., Россия, 620078" search result is empty.

Earlier than November 15, exactly for such a string search result was.

Steps to introduce:
1. go to https://nominatim.openstreetmap.org/
2. insert into search "ул. Мира, 34А, Екатеринбург, Свердловская обл., Россия, 620078"

Factual result:
No search results found
![image](https://user-images.githubusercontent.com/5185332/69134582-86903480-0ad9-11ea-8d37-172e83cd5419.png)

Expected result:
For search "ул. Мира, 34А, Екатеринбург, Свердловская обл., Россия, 620078" result like "ул. Мира, 34А, Екатеринбург"
![image](https://user-images.githubusercontent.com/5185332/69134722-c525ef00-0ad9-11ea-879c-89a0e373cb34.png)

link to the OSM object: https://www.openstreetmap.org/way/79164683

**Comment by lonvia** [comment]
Nominatim does not know the abbreviation "обл." for "область". Searching with the unabbreviated word works fine. I've added it to the [list of abbreviations to be implemented](https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#.D0.A0.D1.83.D1.81.D1.81.D0.BA.D0.B8.D0.B9_-_Russian). It will be a bit though until we update the list. See also #1208.
