### ISSUE TITLE
New GB postcode November file

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1573]
A new file got released. I converted it according to http://nominatim.org/release-docs/develop/data-sources/GB-Postcodes/ and placed it on https://downloads.opencagedata.com/public/gb_postcode_data.201911.sql.gz (35MB)

Compared to August file: 4743 new postcodes, 2347 removed.

**Comment by lonvia** [comment]
Updated on nominatim.org. Thanks.
