### ISSUE TITLE
update tuto for centOS 7

### ISSUE THREAD

**Issue by Fighter777** [openstreetmap/Nominatim#1575]
Hello, the tutorial for cent 7 is not complete. (https://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/)
Nominatim 3.4 requires postgresql >= 9.3 but centOS can only install version 9.2.

It misses the installation of postgresql 10 (for example).

https://tecadmin.net/install-postgresql-server-centos/

Thank you in advance.

**Comment by mtmail** [comment]
The instruction script was already updated https://github.com/openstreetmap/Nominatim/blob/master/vagrant/Install-on-Centos-7.sh with postgresql 11.

@lonvia Can you refresh the documentation on nominatim.org? I can't see it in the http://nominatim.org/release-docs/develop/ yet either.

**Comment by Fighter777** [comment]
ok, nice.


thank you !!

**Comment by lonvia** [comment]
I hopefully now fixed the automatic updates of the development docs. We should be back to nightly updates. Now we only need to get a process in place for updating the current release docs.

**Comment by Fighter777** [comment]
good job, thx :)
