### ISSUE TITLE
Setting up nominatim, planet, osm2pgsql runs out of memory on 32GB RAM

### ISSUE THREAD

**Issue by afendin** [openstreetmap/Nominatim#1577]
I even tuned my postgresql.conf following docs. What could go wrong?
![Снимок экрана_2019-11-23_06-08-31](https://user-images.githubusercontent.com/14954126/69472291-9f426800-0dc1-11ea-8d63-08f7a02dfb83.png)

**Comment by mtmail** [comment]
The screenshot in the background reads “out of memory”.

**Comment by afendin** [comment]
> The screenshot in the background reads “out of memory”.

I undestood this perfectly. The problem is, I followed official docs and I believe that my system has enough memory to handle planet import.

**Comment by mtmail** [comment]
Can you check the ‘vm. overcommit_memory’ kernel setting. osm2pgql should be able to use more memory than available and swap, this oom-killer seem to eager to kill the process. osm2pgsql defaults the cache size to about 75% of RAM, with 16000 you limited it to 50%, that is worth trying with 24000.

**Comment by lonvia** [comment]
> I undestood this perfectly. The problem is, I followed official docs and I believe that my system has enough memory to handle planet import.

The official docs state also that you need system administration experience to install Nominatim. We cannot help you with that. We don't know your system and certainly can't magically solve your problems after a quick look at a random screenshot.

Once again a general remainder that this is a bug tracker for the Nominatim software and not a general help forum.
