### ISSUE TITLE
"boul" is not expanded to match "boulevard"

### ISSUE THREAD

**Issue by jarek** [openstreetmap/Nominatim#1579]
What I did: searched for "800 boul rene-levesque ouest, montreal"

Test URL: https://nominatim.openstreetmap.org/search.php?q=800+boul+rene-levesque+ouest%2C+montreal

Result got: No search results found

Result expected: same as when using "boulevard" or "blvd" instead of "boul": https://nominatim.openstreetmap.org/search.php?q=800+blvd+rene-levesque+ouest%2C+montreal : https://nominatim.openstreetmap.org/details.php?place_id=24890010 aka https://www.openstreetmap.org/node/2428622898

Additional info: 
- "boul" or "boul." is the Canadian French abbreviation for "boulevard" (don't know about Metropolitan French)
- OSM tags are addr:housenumber=800 + addr:street=Boulevard René-Lévesque Ouest
- the street itself (without the housenumber) is also not findable
- this happens for other streets with name including "boulevard" in Québec, this one is just a test case

Impact: unable to search using a street classifier abbreviation

**Comment by matthewdarwin** [comment]
Same issue in Ottawa: https://www.openstreetmap.org/search?query=boul%20jeanne%20d%27arc%20N%2C%20ottawa#map=19/45.46971/-75.54639

**Comment by mtmail** [comment]
@jarek Can you add the abbreviation to https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations ?

**Comment by jarek** [comment]
@mtmail it is in fact there in the "Canadian" section

**Comment by lonvia** [comment]
That's good then. Thanks for checking. There is no ETA at the moment when the list will be imported again because it is blocked on #1208. Closing here.
