### ISSUE TITLE
Wrong postcode returned in reverse geocode

### ISSUE THREAD

**Issue by ErwanTremiot** [openstreetmap/Nominatim#1584]
Hi,

I know this problem is related to OSM data but I would like to known how to correct OpenStreetMap data in order to have Nominatim returning the correct postcode.

I have a reverse query (https://nominatim.openstreetmap.org/reverse/?lat=43.59878333&lon=3.905075&format=geocodejson&osm_type=R&zoom=17) that returns me the following postcode: 34064 MONTPELLIER CEDEX 2. The expected postcode is 34000.

By digging in the debug page of Nominatim I found that:
- there is a place of type postcode that comes from the node 4716035931 in OSM. This node is about 2.7km away from the reverse location.
- there is a boundary (28722) with an attribute addr:postcode=34000;34070;34080;34090 that contains my reverse query

What I'm expecting is:
- since I specified an osm_type to R, the Node should be ignored
- since my coordinates are within a boundary with a postcode tag, the postcode of this boundary is returned

**Comment by mtmail** [comment]
Thanks for checking the places and listing your findings.

That weird postcode `34064 MONTPELLIER CEDEX 2` originates from this place https://www.openstreetmap.org/way/283339491 Can you correct it? Nominatim will update the postcode calculates once per night.

With Overpass API https://overpass-turbo.eu/ I see most postcodes around those coordinates are indeed 34000 so Nominatim should choose that.

Nominatim currently doesn't support multiple postcodes per place. Here it's a city https://www.openstreetmap.org/relation/28722 but I've also seen streets, especially from imports, that have two (one for each side).

**Comment by ErwanTremiot** [comment]
Tanks for your response.

I cannot correct this place since the address and postcode are correct.

There are two types of postcodes in France:
 * the normalized type (postcodes 34000, 34070, 34080 and 34090 for Montpellier) represents a post office that covers a part of or the entire city
 * the CEDEX (Courrier d'Entreprise à Distribution EXceptionnelle; Corporate Mail with Exceptional Distribution) that is affected to a specific corporation. In this case it's a public institution and the postcode associated to the place is its CEDEX postcode

Would a boundary for each postcode of the city solve this issue?

**Comment by mtmail** [comment]
Are CEDEX (https://en.wikipedia.org/wiki/Postal_codes_in_France#CEDEX) numbers like PO Boxes in the United States, assigned to individual businesses? Do they loose information when shortened to just the number?

Postcodes are assigned by postal companies (state owned or private). We see them an hint where a place is (address search) but returning the exact postcode for each address would try to duplicate their database.

> Would a boundary for each postcode of the city solve this issue?

Yes, likely. Though it sounds like a lot of work. Nominatim supports those, here's an example of Germany https://www.openstreetmap.org/relation/1158938

**Comment by lonvia** [comment]
It's not really clear from the internet where the CEDEX part should belong but clearly 'Montpellier' is not part of the postcode. So something is wrong in the data here.

Independent of that, there is an issue with our postcode centroids and such organisational postcodes. We should be able to detect when there is a single postcodes with a lot of different postcodes around it and reduce the radius for which it applies.

**Comment by ErwanTremiot** [comment]
@mtmail CEDEX are assigned to individual businesses but they are not always physical PO as in the United States (as I understand it from https://en.wikipedia.org/wiki/Post_office_box). The mail arrives directly to the business office.

Regarding the address structure in France:
 * the postcode five digits are unique and are specific to the business (in case of CEDEX)
 * the postcode have to be followed by the city name (regardless of CEDEX)
 * the CEDEX term is added behind the city
 * CEDEX can be followed by a number indicating the delivering post office when there is multiple post offices in a city or the number of the "Arrondissement" (an administrative boundary abo the city level). This number can also be a PO when the business rent one.

Thus, the place https://www.openstreetmap.org/way/283339491 postcode tag is indeed wrong. It should only contains the postcode 34064. But I don't know where I should put the CEDEX information. Moreover since this poscode is specific to the business correcting it will not solve my issue.
Maybe I should put the complete address in addr:full and remove the specific tags.

**Comment by mtmail** [comment]
Germany has a similar system with roughly 5000 of 13000 postcodes belonging to businesses. Few of them are mapped.

In France I checked the Nominatim database and only 12 have the text "CEDEX" behind the number, less than 50 have a city name. So it seems the consensus how to map them it just using the number. That's best discussed on https://lists.openstreetmap.org/listinfo/talk-fr

**Comment by ErwanTremiot** [comment]
Hi @mtmail,

Thanks for correcting this issue in OSM. Sadly it didn't solve my issue since the digit part is also specific to the business.
Has a workaround we have updated our middleware script (that we are using to migrate from Addok to Nominatim) to retrieve the postcode from another source.
The source that I am using is https://www.data.gouv.fr/fr/datasets/fond-de-carte-des-codes-postaux/. It's a bit old, but it solves my issue.
