### ISSUE TITLE
Update:  replication URL not reachable

### ISSUE THREAD

**Issue by harryhahn** [openstreetmap/Nominatim#1586]
Hi

 ./utils/update.php --init-updates

it Returns

> 
> PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /srv/nominatim/utils/update.php on line 85
> PHP Warning:  file_get_contents(https://download.geofabrik.de/europe/germany-updates//state.txt): failed to open stream: php_network_getaddresses: getaddrinfo failed: Temporary failure in name resolution in /srv/nominatim/utils/update.php on line 85
> 
> Cannot find state.txt file at the configured replication URL.
> Does the URL point to a directory containing OSM update data?
> 
> ERROR: replication URL not reachable.
> string(30) "replication URL not reachable."

i cannot see the an  error in the URL.

**Comment by mtmail** [comment]
Test the same URL with `wget` or `curl` on the server. If it fails it could be a network/firewall issue. If it's only from within PHP then PHP might not be able to access resolv.conf, like https://www.digitalocean.com/community/questions/how-to-resolve-temporary-failure-in-name-resolution-issue or if lucky it's really temporary, e.g. local DNS server down.

**Comment by lonvia** [comment]
Nominatim is a complex piece of software and runs in a complex environment. Installing and running Nominatim is something for experienced system administrators only who can do some trouble-shooting themselves. We are sorry, but we can not provide installation support. We are all doing this in our free time and there is just so much of that time to go around. You can ask questions on the mailing list or on help.openstreetmap.org.

**Comment by harryhahn** [comment]
:-) Sorry and Thanks
