### ISSUE TITLE
Error Cmake build /home/nominatim/Nominatim 

### ISSUE THREAD

**Issue by hadanhtoi** [openstreetmap/Nominatim#1587]
Following the [,Nominatim document](https://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/) i got this error :
**$cmake /home/nominatim/Nominatim**
`Found PythonInterp: /bin/python3 (found suitable version "3.6.8", minimum required is "3") 
-- Added test: regression-test-pbf (needs Python with psycopg2 module)
-- Found PostgreSQL: /usr/pgsql-11/lib (found version "11.6") 
-- PostgreSQL include dirs: /usr/pgsql-11/include;/usr/include/
-- PostgreSQL library dirs: /usr/pgsql-11/lib
-- PostgreSQL libraries:    pq
**CMake Warning at CMakeLists.txt:59 (message):
  pyosmium-get-changes not found (required for updates)**

-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1") 
-- Using PHP binary /bin/php
-- Looking for bswap_32
-- Looking for bswap_32 - found
**-- Looking for bswap32
-- Looking for bswap32 - not found**
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nominatim/build`

**$make**

`[ 72%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/util.cpp.o
[ 75%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/wildcmp.cpp.o
Linking CXX static library libosm2pgsql.a
[ 75%] Built target osm2pgsql_lib
Scanning dependencies of target osm2pgsql
[ 77%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql.dir/osm2pgsql.cpp.o
Linking CXX executable osm2pgsql
[ 77%] Built target osm2pgsql
Scanning dependencies of target nominatim_lib
[ 80%] Running external makefile /usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk
/home/nominatim/Nominatim/module/Makefile:11: warning: overriding recipe for target `install'
/usr/pgsql-11/lib/pgxs/src/makefiles/pgxs.mk:238: warning: ignoring old recipe for target `install'
make[3]: /opt/rh/llvm-toolset-7/root/usr/bin/clang: Command not found
make[3]: *** [nominatim.bc] Error 127
make[2]: *** [/home/nominatim/Nominatim/module/dummy] Error 2
make[1]: *** [module/CMakeFiles/nominatim_lib.dir/all] Error 2
make: *** [all] Error 2`

What should I do @@ ?

**Comment by mtmail** [comment]
> `clang: Command not found make`

You need to install that somehow on your system. How compilers are installed and configured is unrelated to the Nominatim software.

**Comment by hadanhtoi** [comment]
hi @mtmail  so, What should I do with **warning CMake Warning at CMakeLists.txt:59 (message):
pyosmium-get-changes not found (required for updates)**  ?

**Comment by mtmail** [comment]
That can be ignored for the initial import and index.

Later you might want to setup regular (daily or minutely) data updates but it's not requited. How to install osmium is described further down on the  page http://nominatim.org/release-docs/latest/admin/Import-and-Update/#updates

> bswap32

As far as I know that's not required on Linux system, only on BSD type operating systems (like FreeBSD)

**Comment by lonvia** [comment]
Nominatim is a complex piece of software and runs in a complex environment. Installing and running Nominatim is something for experienced system administrators only who can do some trouble-shooting themselves. We are sorry, but we can not provide installation support. We are all doing this in our free time and there is just so much of that time to go around. You can ask questions on the mailing list or on help.openstreetmap.org.
