### ISSUE TITLE
wrong postal code and building:levels for house in Ottawa, Canada

### ISSUE THREAD

**Issue by idallen** [openstreetmap/Nominatim#1588]
https://www.openstreetmap.org/search?query=22%20Oak%20Street%2C%20Ottawa%2C%20Ontario%2C%20Canada#map=19/45.40653/-75.71425

The postal code should be K1R 6S9, not K1R 6R9

The building:levels should be 3 not 1

**Comment by mtmail** [comment]
After login on openstreetmap.org you can edit the building in the editor. See screenshot. 

Direct questions about how to map to https://www.openstreetmap.org/fixthemap https://help.openstreetmap.org/ or a Canada specific group https://openstreetmap.community/ (click on Canada for a list).

![image](https://user-images.githubusercontent.com/3727288/69912514-abb26a80-142a-11ea-883e-283471fa4087.png)

**Comment by matthewdarwin** [comment]
Building is improved.

https://www.openstreetmap.org/way/481791719#map=19/45.40653/-75.71425
https://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Roof
