### ISSUE TITLE
Enclosing township name lost in Taiwan

### ISSUE THREAD

**Issue by jidanni** [openstreetmap/Nominatim#1591]
https://www.openstreetmap.org/search?whereami=1&query=24.1018%2C121.6053#map=14/24.1019/121.6052 gives:
> Jingmei Village, Sanzhan, [XXX,] Hualien County, Taiwan Province, Taiwan

Misses the enclosing https://en.wikipedia.org/wiki/Xiulin,_Hualien township (Should be at XXX above).

Perhaps a USA standard is being used, where e.g., one does not use townships in Wisconsin postal addresses.

**Comment by lonvia** [comment]
Sanzhan hamlet gets same rank as Xiulin town and Jinmei Village an even lower rank due to the admin_level. This will be fixed once we have sorted out #213. Closing here.
