### ISSUE TITLE
Brasil 5+3 digits postcode not found, ideally fallback to 5 digit search

### ISSUE THREAD

**Issue by marceloagil** [openstreetmap/Nominatim#1592]
When I search in map a zipCode 69049-630, it throws this result:
(This is close to Italy, I guess is "Croacia")
![image](https://user-images.githubusercontent.com/17890658/69922518-b0533f00-147b-11ea-9db0-cbd6f1667118.png)

But the real result should be Manaus, Brasil:
![image](https://user-images.githubusercontent.com/17890658/69922522-b6e1b680-147b-11ea-9718-9bf41057b280.png)

How to fix this?

The endpoint I'm using:
https://nominatim.openstreetmap.org/search?format=json&limit=3&q=69049-630

**Comment by mtmail** [comment]
Add `&countrycodes=br` receive only results in Brazil. http://nominatim.org/release-docs/latest/api/Search/

OpenStreetMap data doesn't have any address or building with that postcode yet, somebody (could be you) would need to add it. https://www.openstreetmap.org/fixthemap (Copying from commercial licensed data like Google Maps is not allowed).

I see a nearby place with postcode `69049-190` https://www.openstreetmap.org/way/433369605 Nominatim should calculate a center for 69049 at least to find the broad area. We have an unfinished search logic change in https://github.com/openstreetmap/Nominatim/pull/1302 but it will also require us to change the postcode center point calculation logic. http://nominatim.org/release-docs/develop/develop/Postcodes/

**Comment by lonvia** [comment]
Closing as data issue.

We really need to add a big fat warning somewhere that Nominatim is not the right tool for postcode searches and will not be in the foreseeable future.

**Comment by marceloagil** [comment]
Hi mtmail thanks for your answer but add &countrycodes=br did not work.
