### ISSUE TITLE
Moscow Region, Russia

### ISSUE THREAD

**Issue by Gotfrid** [openstreetmap/Nominatim#1593]
There is an issue that Khimki is stated as an adminstrative part of Moscow, whereas in fact, it is administrative unit of Moscow Region. 
Thank you!

**Comment by mtmail** [comment]
Please follow the "When Reporting Bad Search Results" guidelines in https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md

**Comment by mtmail** [comment]
City "Khimki" (no admin level set, place=city, https://www.openstreetmap.org/relation/181326) is completely inside "Moscow Oblast" (admin_level=4, border_type=region, https://www.openstreetmap.org/relation/51490) and completely outside of "Moscow" (admin_level=4, https://www.openstreetmap.org/relation/102269).

Nominatim sets this hierarchy https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=181326&class=place 
The next higher level to "Khimki" is set to "Northern Administrative Okrug" (admin_level=5). That is both in Moscow and Moscow Oblast.

Overpass-Turbo query to overlap areas: https://overpass-turbo.eu/s/OGi

I think what you're saying is admin_level=5 should be skipped. That makes it a part of https://github.com/openstreetmap/Nominatim/issues/1080 a bigger Nominatim project with no easy solution.

Data is OSM looks mapped/tagged alright.

**Comment by lonvia** [comment]
It looks like the reimport has fixed this issue. Khimki is now correctly assigned Msocow Oblast. Or maybe the data got fixed. Closing here.
