### ISSUE TITLE
Errors on update 

### ISSUE THREAD

**Issue by jah-** [openstreetmap/Nominatim#1594]
Hi there I need to update the initial import (world import) but when I try that I get an error:

```
$  ./utils/update.php --init-updates

CONST_Pyosmium_Binary not configured.
You need to install pyosmium and set up the path to pyosmium-get-changes
in your local settings file.

ERROR: CONST_Pyosmium_Binary not configured
string(36) "CONST_Pyosmium_Binary not configured"

```

I follow the instructions of [main doc site](https://nominatim.org/release-docs/latest/admin/Import-and-Update/) 

my settings/local.php:

```
<?php
@define('CONST_Website_BaseURL', '/');
@define('CONST_Replication_Url', 'https://planet.openstreetmap.org/replication/day/');
@define('CONST_Replication_Update_Interval', '86400');
@define('CONST_Replication_Recheck_Interval', '900');
@define('CONST_Pyosmium_Binary', '/srv/nominatim/.local/bin/pyosmium-get-changes');
```

Thanks in advance for your help.

**Comment by lonvia** [comment]
As the error says: it can't find the CONST_Pyosmium_Binary variable.

Nominatim is a complex piece of software and runs in a complex environment. Installing and running Nominatim is something for experienced system administrators only who can do some trouble-shooting themselves. We are sorry, but we can not provide installation support. We are all doing this in our free time and there is just so much of that time to go around. You can ask questions on the mailing list (see below) or on help.openstreetmap.org.

Closing here. If you find that there is an issue with the installation docs, then feel free to open a new issue suggesting an appropriate improvement to help others to not run into the same problem.

**Comment by mtmail** [comment]
I can't see anything wrong here.

Add a debug statement like `echo "inside local.php\n";` to the local.php file so see if it gets called at all.

Background: `./utils/update.php` uses `require_once ... settings.php` which near the top required the local.php file. `@define` will keep the first value, calling it several times won't overwrite the previously set value.

**Comment by jah-** [comment]
thanks for your comments @mtmail by an unkown reason the update.php command ignores the local.php file, but after I insert the pyosmium-get-changes file path in the settings.php file then I run the command with success.

**Comment by dwikyrestu** [comment]
I know is late, But it happen for me because i missing "<?php" in /build/settings/local.php. Add that in top of file worked for me
