### ISSUE TITLE
update fails 

### ISSUE THREAD

**Issue by jah-** [openstreetmap/Nominatim#1598]
Hi, I have an issue with the update process when I try to update the database:

```
blocked_pid | blocked_user | blocking_pid | blocking_user |                                        blocked_statement                                         | current_statement_in_blocking_process 
-------------+--------------+--------------+---------------+--------------------------------------------------------------------------------------------------+---------------------------------------
        2298 | nominatim    |         2297 | nominatim     | DELETE FROM place WHERE osm_type = 'W' AND osm_id = 483539514 and class = any(ARRAY['building']) | COPY place FROM STDIN
(1 row)
```
The update hangs on this query, and I don't how fix to continue the update.

this is the cmdline that I ran:
```
:~/Nominatim-3.4.0/build$ ./utils/update.php --import-osmosis-all
Currently at sequence 2602 (28/10/2019 00:57:29) - 1 indexed
/srv/nominatim/.local/bin/pyosmium-get-changes --server https://planet.openstreetmap.org/replication/day/ -o /srv/nominatim/Nominatim-3.4.0/build/osmosischange.osc -s 30 -I
2602
/srv/nominatim/Nominatim-3.4.0/build/osm2pgsql/osm2pgsql -klas --number-processes 1 -C 2000 -O gazetteer -S /srv/nominatim/Nominatim-3.4.0/settings/import-full.style -d nominatim -P 5432 --flat-nodes /srv/nominatim/Nominatim-3.4.0/data/planet.bin /srv/nominatim/Nominatim-3.4.0/build/osmosischange.osc
osm2pgsql version 1.2.0 (64 bit id space)

Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=2000MB, maxblocks=32000*65536, allocation method=11
Mid: loading persistent node cache from /srv/nominatim/Nominatim-3.4.0/data/planet.bin
Mid: pgsql, cache=2000
Parsing gazetteer style file '/srv/nominatim/Nominatim-3.4.0/settings/import-full.style'.
Using projection SRS 4326 (Latlong)

Reading in file: /srv/nominatim/Nominatim-3.4.0/build/osmosischange.osc
Using XML parser.
Processing: Node(2558k 15.5k/s) Way(114k 0.73k/s) Relation(0 0.00/s)
```

In addition I see a proccess in a waiting state, the process is related to this situation:
`
postgres  2298 24706  1 14:05 ?        00:01:30 postgres: 10/main: nominatim nominatim [local] DELETE waiting
`

I ran and then cancel and re-run the whole update whitout changes.

There's any suggestion or alternative to that situation?

Thanks in advance.

**Comment by mtmail** [comment]
Looks like it describes this issue from 8 days ago https://github.com/openstreetmap/osm2pgsql/pull/1008

Can you try installing the latest version of osm2pgsql? Then add an entry `@define('CONST_Osm2pgsql_Binary', CONST_InstallPath.'/osm2pgsql/osm2pgsql');` in `build/settings/local.php` pointing to where you installed it.

**Comment by jah-** [comment]
@mtmail hi, thanks for your answer!

I have **osm2pgsql version 0.94.0 (64 bit id space)** 
there isn't more updated version via package manager, I think that's not the latest version, but maybe 
there's more updated version in git repo.

Please, can you tell me what's the suggested version ( I prefer do not compile the binary if I can do that)

Thanks again!

**Comment by mtmail** [comment]
You had osm2psql 1.2.0 before (I see it in your output). The available versions on package managers (like Debian/apt-get) are too old. Version 0.94 is from 2017.

There hasn't been a new release since the fix got added https://github.com/openstreetmap/osm2pgsql/releases so compiling is needed:

Based on the paths I see in your output
```bash
cd /srv/nominatim/Nominatim-3.4.0
mv osm2pgsql osm2pgsql.old.$$
git clone https://github.com/openstreetmap/osm2pgsql.git
cd build
cmake .. && make
osm2pgsql/osm2pgsql --version
# osm2pgsql version 1.2.0 (64 bit id space)
```

This will recompile Nominatim (source code didn't change) but also osm2pgsl (new source code). When you initially installed Nominatim that already included all osm2pgsql dependencies. At least with Nominatim 3.4 those should be still working.

**Comment by jah-** [comment]
Hi, based on your comments, I take a look and...

```
:~/Nominatim-3.4.0/build$ osm2pgsql/osm2pgsql --version
osm2pgsql version 1.2.0 (64 bit id space)

Compiled using the following library versions:
Libosmium 2.15.3
Lua support not included
```

And then I add the stanza to my local.php

`@define('CONST_Osm2pgsql_Binary', CONST_InstallPath.'/osm2pgsql/osm2pgsql');
`

Thank for your reply, I run the update process again and wait for the results.

**Comment by jah-** [comment]
But I think the command will fail again if I not include the fix, I need to compile anyway.

Thanks for your time.

**Comment by jah-** [comment]
Hi @mtmail there's no issues whit the update, after I compile the source whit the fix as you was suggested the process y running ok.

Thanks a lot.
