### ISSUE TITLE
Mention API usage policy in API documentation.

### ISSUE THREAD

**Issue by dietercastel** [openstreetmap/Nominatim#1602]
Hi all,

I was experimenting with the Nominatim API and (unknowingly) forgot to set the User-Agent. The error page of the failed API call lead me to the informative policy page below:

[https://operations.osmfoundation.org/policies/nominatim/](https://operations.osmfoundation.org/policies/nominatim/)

I wish I would have known in advance! So to fix that I think it would be good to clearly mention this policy in the API documentation e.g. on this page:
[https://nominatim.org/release-docs/develop/api/Overview/](https://nominatim.org/release-docs/develop/api/Overview/)

I can create a PR for that if in agreement but I always like to hear some feedback first.

**Comment by lonvia** [comment]
Problem is that these docs are for Nominatim the software, while the usage policy is for the service on nominatim.openstreetmap.org. The website there does have the link to the usage policy. We could make it more prominent there.

**Comment by lonvia** [comment]
I've added links to the policy in the footer and in the help dropdown.
