### ISSUE TITLE
How to back up on external drive whole WORKING ubuntu system with nominatim? 

### ISSUE THREAD

**Issue by Zakrinichniy** [openstreetmap/Nominatim#1605]
Hello all, I have Ubuntu 18.04 and installed nominatim, checked it, that working properly, tried to clone with CloneZilla, I've changed drives, checked postgres and apache2 services, but they don't work, even logs are empty.
So there is a quesstion - how to back up it properly?

**Comment by lonvia** [comment]
We are sorry, this is an issue tracker. We can not provide this kind of installation support. We are all doing this in our free time and there is just so much of that time to go around. You can ask questions on the mailing list (see below) or on help.openstreetmap.org.
