### ISSUE TITLE
Error  value too long on full import

### ISSUE THREAD

**Issue by txtor** [openstreetmap/Nominatim#1606]
Hello.  I had the problem of issue #1550, thanks a lot for fixing it.
After checking out the new version of osm2pgsql, though, I get an error when starting to index.
```
Starting rank 4
  Done 26 in 1 @ 26.000000 per second - Rank 4 ETA (seconds): 3.000000
  Slow place_id 121093201
  Done 45 in 2 @ 22.500000 per second - Rank 4 ETA (seconds): 2.622222
  Slow place_id 120900910
index_placex: UPDATE failed: ERROR:  value too long for type character varying(2)
CONTEXT:  PL/pgSQL function placex_update() line 123 at assignment
ERROR: error status 1 running nominatim!
string(33) "error status 1 running nominatim!"
'''

Data: Europe, full import
osm2pgsql version 1.2.0 3a045d7f15adc05d34a719da4266418e9663b322
Nominatim 3.4.0
psql (PostgreSQL) 10.11

**Comment by liKe2k1** [comment]
Got the same error on a fresh Ubuntu 18.04 install:

`Starting rank 4
  Done 47 in 1 @ 47.000000 per second - Rank 4 ETA (seconds): 1.212766
index_placex: UPDATE failed: ERROR:  value too long for type character varying(2)
CONTEXT:  PL/pgSQL function placex_update() line 123 at assignment
ERROR: error status 1 running nominatim!
string(33) "error status 1 running nominatim!"`

Data: Europe, full import
osm2pgsql version 1.2.0 (64 bit id space)
nominatim version 3.4.0
psql (PostgreSQL) 10.11

**Comment by lonvia** [comment]
Typo in style file. `is_in_country` should be `is_in:country`.

**Comment by liKe2k1** [comment]
This should be also fixed in the other *.style files (We use import-address.style)

**Comment by mtmail** [comment]
@liKe2k1 Can you create a quick pull request like https://github.com/openstreetmap/Nominatim/pull/1607 ?

**Comment by txtor** [comment]
> @liKe2k1 Can you create a quick pull request like #1607 ?

done
