### ISSUE TITLE
Centos install make error

### ISSUE THREAD

**Issue by ness31** [openstreetmap/Nominatim#1611]
Hello,
while installing nominatim locally, I get the following error running make:

Scanning dependencies of target osm2pgsql_lib
[  2%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/db-copy.cpp.o
[  5%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/expire-tiles.cpp.o
[  7%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/geometry-processor.cpp.o
[ 10%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/id-tracker.cpp.o
[ 12%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle-pgsql.cpp.o
[ 15%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/middle-ram.cpp.o
[ 17%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/node-persistent-cache.cpp.o
[ 20%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/node-ram-cache.cpp.o
[ 22%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/options.cpp.o
[ 25%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/osmdata.cpp.o
[ 27%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/osmium-builder.cpp.o
[ 30%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/gazetteer-style.cpp.o
[ 32%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-gazetteer.cpp.o
[ 35%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-multi.cpp.o
[ 37%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-null.cpp.o
[ 40%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output-pgsql.cpp.o
[ 42%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/output.cpp.o
[ 45%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/parse-osmium.cpp.o
[ 47%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/pgsql.cpp.o
[ 50%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/processor-line.cpp.o
[ 52%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/processor-point.cpp.o
[ 55%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/processor-polygon.cpp.o
[ 57%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/reprojection.cpp.o
[ 60%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/sprompt.cpp.o
[ 62%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/table.cpp.o
[ 65%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/taginfo.cpp.o
[ 67%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/tagtransform.cpp.o
[ 70%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/tagtransform-c.cpp.o
[ 72%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/util.cpp.o
[ 75%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql_lib.dir/wildcmp.cpp.o
Linking CXX static library libosm2pgsql.a
[ 75%] Built target osm2pgsql_lib
Scanning dependencies of target osm2pgsql
[ 77%] Building CXX object osm2pgsql/CMakeFiles/osm2pgsql.dir/osm2pgsql.cpp.o
Linking CXX executable osm2pgsql
[ 77%] Built target osm2pgsql
Scanning dependencies of target nominatim_lib
[ 80%] Running external makefile /usr/pgsql-12/lib/pgxs/src/makefiles/pgxs.mk
/srv/nominatim/Nominatim-3.4.0/module/Makefile:11: AVERTISSEMENT : surchargement de la recette pour la cible « install »
/usr/pgsql-12/lib/pgxs/src/makefiles/pgxs.mk:241: AVERTISSEMENT : ancienne recette ignorée pour la cible « install »
make[3]: /opt/rh/llvm-toolset-7/root/usr/bin/clang : commande introuvable
make[3]: *** [nominatim.bc] Erreur 127
make[2]: *** [/srv/nominatim/Nominatim-3.4.0/module/dummy] Erreur 2
make[1]: *** [module/CMakeFiles/nominatim_lib.dir/all] Erreur 2
make: *** [all] Erreur 2

Can you please tell me where it comes from ?
Thanks in advance.

**Comment by lonvia** [comment]
Not fluent in French, but `make[3]: /opt/rh/llvm-toolset-7/root/usr/bin/clang : commande introuvable` might give a hint.

Nominatim is a complex piece of software and runs in a complex environment. Installing and running Nominatim is something for experienced system administrators only who can do some trouble-shooting themselves. We are sorry, but we can not provide installation support. We are all doing this in our free time and there is just so much of that time to go around. This is not the right place if you need help. You can ask questions on the mailing list or on help.openstreetmap.org.

**Comment by ness31** [comment]
ok I understand thanks, just for info I get it right using:
make CLANG=true
