### ISSUE TITLE
Reverse look up not returning correct result

### ISSUE THREAD

**Issue by DuzAwe** [openstreetmap/Nominatim#1616]
Hi, 

Lat long 37.386575999999998,-5.987628 should return.

`{"place_id":"177797416","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"relation","osm_id":"2960979","lat":"37.38677865","lon":"-5.98728119057872","place_rank":"30","category":"tourism","type":"hotel","importance":"0","addresstype":"tourism","display_name":"Casas de la Judería, Callejón Dos Hermanas, San Bartolomé, Casco Antiguo, Seville, Sevilla, Andalusia, 41004, Spain","name":"Casas de la Judería","address":{"hotel":"Casas de la Judería","pedestrian":"Callejón Dos Hermanas","neighbourhood":"San Bartolomé","suburb":"Casco Antiguo","city":"Seville","county":"Sevilla","state":"Andalusia","postcode":"41004","country":"Spain","country_code":"es"},"boundingbox":["37.386453","37.3874062","-5.9876655","-5.9859047"]}`

But its returning 

`{"place_id":"75463283","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"way","osm_id":"28115578","lat":"37.3865562","lon":"-5.98788239353671","place_rank":"26","category":"highway","type":"pedestrian","importance":"0.1","addresstype":"highway","name":null,"display_name":"San Bartolomé, Casco Antiguo, Seville, Sevilla, Andalusia, Spain","address":{"neighbourhood":"San Bartolomé","suburb":"Casco Antiguo","city":"Seville","county":"Sevilla","state":"Andalusia","country":"Spain","country_code":"es"},"boundingbox":["37.3862853","37.3868172","-5.9882483","-5.9873673"]}`

**Comment by mtmail** [comment]
Please follow https://github.com/openstreetmap/Nominatim/blob/master/CONTRIBUTING.md

If you run your own installation of Nominatim add version number, what data got imported.

**Comment by mtmail** [comment]
Dumping minified JSON isn't readable.

**Comment by mtmail** [comment]
Coordinate (small red circle) is on a street.

https://nominatim.openstreetmap.org/reverse.php?format=html&lat=37.386575999999998&lon=-5.987628&zoom=21

![image](https://user-images.githubusercontent.com/3727288/71189852-c3d81580-2283-11ea-84e2-afa1d1996326.png)

That position is on the square https://nominatim.openstreetmap.org/details?osmtype=W&osmid=28115578 and only next to the hotel https://nominatim.openstreetmap.org/details?osmtype=R&osmid=2960979

Nominatim doesn't import building boundaries and "sees" only the center of the hotel. I think it's not unreasonable to get the square returned. One could argue the square is mapped too large and could exclude the street, then the street name would likely get returned.

The hotel is assigned to street "Calle Santa María la Blanca"
https://nominatim.openstreetmap.org/details?osmtype=R&osmid=2960979
You could add addr: tags (https://wiki.openstreetmap.org/wiki/Key:addr) to assign the hotel to the correct street (based on their website and wherever their main entrance is for example).

https://www.openstreetmap.org/relation/2960979




https://nominatim.openstreetmap.org/reverse.php?format=html&lat=37.386575999999998&lon=-5.987628&zoom=21

**Comment by DuzAwe** [comment]
Data Unminfied below. One form Nom 3.0.0 the other from 3.2.0 the planet file is from Aug 2017.

reverse.php?format=jsonv2&lat=37.386575999999998&lon=-5.987628 is used on both installs. The newer install returns the street and the older returns the hotel. I have inherited the older install and am trying to create a failover, As it stands now the results from the second install all seem to be different from the first.  This is with data installed being idenetical.

`{
    "place_id":"177797416",
    "licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright",
    "osm_type":"relation",
    "osm_id":"2960979",
    "lat":"37.38677865",
    "lon":"-5.98728119057872",
    "place_rank":"30",
    "category":"tourism",
    "type":"hotel",
    "importance":"0",
    "addresstype":"tourism",
    "display_name":"Casas de la Judería, Callejón Dos Hermanas, San Bartolomé, Casco Antiguo, Seville, Sevilla, Andalusia, 41004, Spain",
    "name":"Casas de la Judería",
    "address": {
        "hotel": "Casas de la Judería", "pedestrian": "Callejón Dos Hermanas", "neighbourhood": "San Bartolomé", "suburb": "Casco Antiguo", "city": "Seville", "county": "Sevilla", "state": "Andalusia", "postcode": "41004", "country": "Spain", "country_code": "es"
    }
    ,
    "boundingbox":["37.386453",
    "37.3874062",
    "-5.9876655",
    "-5.9859047"]
}`

`{
    "place_id":"75463283",
    "licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright",
    "osm_type":"way",
    "osm_id":"28115578",
    "lat":"37.3865562",
    "lon":"-5.98788239353671",
    "place_rank":"26",
    "category":"highway",
    "type":"pedestrian",
    "importance":"0.1",
    "addresstype":"highway",
    "name":null,
    "display_name":"San Bartolomé, Casco Antiguo, Seville, Sevilla, Andalusia, Spain",
    "address": {
        "neighbourhood": "San Bartolomé", "suburb": "Casco Antiguo", "city": "Seville", "county": "Sevilla", "state": "Andalusia", "country": "Spain", "country_code": "es"
    }
    ,
    "boundingbox":["37.3862853",
    "37.3868172",
    "-5.9882483",
    "-5.9873673"]
}`

**Comment by mtmail** [comment]
The reverse algorithm changed in version 3.2. https://github.com/openstreetmap/Nominatim/releases/tag/v3.2.0

I think the best failover is a 1:1 clone of both software and data. The database table and indices can change between minor version so they shouldn't for example access the same database http://nominatim.org/release-docs/latest/admin/Migration/#310-320

With the current reverse algorithm and these coordinates setting the `addr:` tags of the hotel can help.
