### ISSUE TITLE
Using WMTS map tile

### ISSUE THREAD

**Issue by ness31** [openstreetmap/Nominatim#1618]
Hello, i do have my local nominatim instance working perfectly but i would like to be able to use my own wmts service for the html format basemap.
Changing the "@define('CONST_Map_Tile_URL'," parameter in the settings doesn't work.
Any idea ?
Thanks

**Comment by mtmail** [comment]
We use the HTML output you see on https://nominatim.openstreetmap.org/ only for testing/debugging.

It is basically HTML pages (`/lib/template/*-html.php`) using [leafletjs](https://leafletjs.com/). In your own installation you will need to add Javascript logic to `website/js/nominatim-ui.js` and if you need further files add them to `lib/template/includes/html-footer.php`. Note, that you have a `Nominatim/website/` directory and a `build/website/` directory. The `build/website/` is what the webserver (e.g. Apache2) runs.

https://github.com/mtmail/nominatim-ui/ is the HTML frontend extracted from the main project. It's still work-in-progress. Same logic, no PHP, a build process. Maybe that's easier to work with, depends on what type of website programming tools you usually use.

For different tile types (vector, wmt) you probably need a leaflet plugin https://leafletjs.com/plugins.html If you run into problems with leaflet use their help pages or https://help.openstreetmap.org/ Nominatim has no plans to support different tile types.

Please direct more questions to
