### ISSUE TITLE
level info for indoor meeting room

### ISSUE THREAD

**Issue by clement-igonet** [openstreetmap/Nominatim#1621]
I'm using nominatim for searching some rooms by their name inside a building.
I get good results except I miss level information to well localize the room inside the building.
Could we add "level" key/value as API reply ?

**Comment by mtmail** [comment]
If you run your own Nominatim instance you can add data into the `extra` hash (postgresql hstore type). http://nominatim.org/release-docs/latest/develop/Import/

Look for `website` or `wikipedia` in
https://github.com/openstreetmap/Nominatim/blob/master/settings/ import-full.style
There's many other OSM tags you might not need to import for a rooms-inside-building search.

You then need to add &extratags=1 to the search URL to get the hash returned, e.g. https://nominatim.openstreetmap.org/search.php?q=hamburg+altona&limit=1&format=jsonv2&extratags=1

**Comment by clement-igonet** [comment]
Tks @mtmail.
However, I do not aim to run my own Nominatim instance.
As I'm working on little areas, if I had to find a solution by myself, I would generate replies adopting Nominatim format, from overpass json data as input.
My real goal is to let other projects rely on level info from their Nominatim requests, like OpenLevelUp project.

**Comment by lonvia** [comment]
There is a plan to switch the nominatim.org instance to full extratags, see #405. That will also give you the level tag.

It is unlikely that Nominatim will ever support search for indoor features beyond that, simply because it is not high enough on the todo list that I ever see us getting around to that. It requires some substantial database restructuring. There is an open ticket  (#587) for addr:unit already. The same restrictions apply for any indoor tagging.

**Comment by clement-igonet** [comment]
OK. Thks. I'll use a home made solution, but compliant to Nominatim reply format.

**Comment by lonvia** [comment]
Alright. Combining Nominatim and Overpass for such special applications is definitely a good way to go. I gave a talk about that at the [last SOTM](https://media.ccc.de/v/sotm2019-1331-customizing-search-for-special-interest-maps).

I'll close this ticket in favour of the other two. Watch out for those if you think they help your use-case. Especially #405 should arrive really soon.
