### ISSUE TITLE
Special phrases import issue

### ISSUE THREAD

**Issue by tomaszkus97** [openstreetmap/Nominatim#1629]
Hi, I've successfully installed Nominatim on Ubuntu VM and imported whole planet data, following instructions: http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-18/
Nominatim works well. I wanted now to use secial phrases search, so tried to import wiki data using command:

./utils/specialphrases.php --wiki-import > specialphrases.sql psql -d nominatim -f specialphrases.sql

But it gives mi error:
-bash: specialphrases.sql: Permission denied
I have listed nominatim db tables and such table doesn't exist. 
Whan Am I doing wrong?

**Comment by mtmail** [comment]
It should run as two separate commands. The first writes the file, the second imports it. I think the error message indicates it was run as one.

```
./utils/specialphrases.php --wiki-import > specialphrases.sql


psql -d nominatim -f specialphrases.sql
```

**Comment by tomaszkus97** [comment]
The error indicates that i had no permission to create such file in directory.
Is is solved now.
