### ISSUE TITLE
13900 Lincoln Park Dr not found

### ISSUE THREAD

**Issue by mulhamjundi** [openstreetmap/Nominatim#1630]
Hi,
I have this address below, can be seen in the OSM, but it showing "No results found", and that lead to address not showing in our application by using APU calls. any other address working fine for us.

13900  Lincoln Park Dr, Herndon, VA 20171, USA

**Comment by lonvia** [comment]
Please provide a link to the OSM object that has the address.

**Comment by mulhamjundi** [comment]
If I search for the full address: "13900 Lincoln Park Dr, Herndon, VA 20171, USA" will get no results found.
https://www.openstreetmap.org/search?query=13900%20Lincoln%20Park%20Dr%2C%20Herndon%2C%20VA%2020171%2C%20USA%20#map=19/38.92617/-77.42806

BUT if I search only for: "13900 Lincoln Park Dr" will get the correct address/information.
https://www.openstreetmap.org/search?query=13900%20Lincoln%20Park%20Dr#map=19/38.92609/-77.42856

**Comment by mtmail** [comment]
The building had the name "13900 Lincoln Park Dr" and I see somebody changed to be an address again, that's good. https://www.openstreetmap.org/way/262058759/history

The nominatim.osm.org database still shows the already changed name https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=262058759&class=building (that's bad).

What is also missing is a street. A building might have a `addr:housenumber` but the value of `addr:street` or `addr:place` needs to exist in OpenStreetMap data as well.

I don't know which of the street is called "Lincoln Park Drive", e.g. https://www.openstreetmap.org/way/262558034 might be, but somebody needs to add a name to the relevant street for the full address of the building to be found.

**Comment by lonvia** [comment]
Is "13900 Lincoln Park Dr" really the full name of the building? If it's just it's address, then please remove the name tag.

**Comment by lonvia** [comment]
Closing as data issue.
