### ISSUE TITLE
Freeland, WA

### ISSUE THREAD

**Issue by rltennal** [openstreetmap/Nominatim#1631]
address lookups for Freeland, WA located at approximately 48.009353,-122.526545 error out.  Search for "Freeland WA" lead to Freeland NY.  Is there a way to get this fixed?

**Comment by lonvia** [comment]
Looks like a data error in OpenStreetMap. There is no place named Freeland at the coordinates but there is an unnamed village. You can [fix the map yourself](https://www.openstreetmap.org/fixthemap).

**Comment by rltennal** [comment]
Thanks for the tip.  I am way to new at this to take that on.  Like I have only been playing around with it for about three weeks.
