### ISSUE TITLE
Database size increasing on updates

### ISSUE THREAD

**Issue by hoeller** [openstreetmap/Nominatim#1633]
Nominatim 3.2.0
PHP 7.2

My installation is updated weekly via cronjob and `update.php --import-osmosis`
Is it the intended behavior that the Postgres DB grows continuously, or should old entries get removed some way?

**Comment by mtmail** [comment]
OSM data grows over time, people keep adding new places (more than they delete). Scroll down to the graphs on https://wiki.openstreetmap.org/wiki/Stats

Thus the Nominatim database will grow over time. That said when adding and deleting rows in a postgresql database it will fragment (in simple terms the database marks rows as deleted but might not free the space). Running a regular https://www.postgresql.org/docs/current/sql-vacuum.html helps, it can run in the background, e.g. after your weekly cronjob. If you have enough disk space you could also recreate indices https://github.com/rory/pgindexrebuild
