### ISSUE TITLE
Reverse Lookup Administrative Layer Lost 

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1634]
We consume Nominatim as Webservice for reverse lookups using the geocodejson format. We massively cache the lookup results in our own, much smaller database.

Since last night (10ths of January) we experience that intermediate administrative layers in many places, but mainly in German are being skipped. To make a random example. 

_Landkreis Tübingen_ is now delivered as a direct sibling of _Baden Würtenberg_, wheras it used to be delivered as a child of _Regierungsbezirk Tübingen_ which was child of _Baden Würtenberg_:

https://nominatim.openstreetmap.org/reverse?format=json&lat=48.517514&lon=9.059601&zoom=42&accept-language=en&addressdetails=1

Is this an deliberate change? Or is this a bug?

Similar but not yet carefully analyzed/not yet enough data issues seem to happen in Japan and the USA (our database only fills on user demand and does not completely mirror Nominatim structures).

**Comment by lonvia** [comment]
Yes, that was a [deliberate change](https://github.com/openstreetmap/Nominatim/pull/1414) as Regierungsbezirke are not really part of an address in Germany.

These things are configurable, so you can set up your own database and get them back (and by the sounds of it you are using the webservice at a scale where you should be doing that anyway).

**Comment by InI4** [comment]
Unfortunately project resources (time, money) do not allow spinning up my own ìnstance. As I am the only developer and operator of a tiny private project and especially I only need a tiny part of the Nominatim database. My systems cautiously samples it from Nominatim but keeps a differently focused local hierarchy as visualized here: https://www.badge-r-s.de/rulers.php?id=100000.

Nominatim is only being rechecked about every few weeks. This is, where my database now slowly gets crowded by duplicates in different hierarchy positions. Totally breaks my application.

You do not accidentally have an suggestion how to retrieve my mean/lean simplified subset of information without setting up my own Nominatim?

Remark: The deliberate change seems a bit strange to me, as I still get "Landkreis" in Bavaria, which is neither part of an address. So from my perspective it changed from fairly complete but too much, to incomplete, but still too much, at least in some places.

**Comment by mtmail** [comment]
Nice game and thanks for the kind words on https://www.badge-r-s.de/wiki/doku.php?id=nominatim I see you're well aware of some of the drawbacks as well.

The change was introduced in July, slowly with data updates the boundaries are removed, you might still see some until the full database gets reimported (or a new server installed). With many changes it's unrealistic for the nominatim.osm.org to get fully reimported.

Nominatim was the last OSM based geocoder I'm aware of that still returned the Regierungsbezirk (admin_level=7) in Germany. Users asked for it to be skipped for years. I doublechecked osmnames, photon, jrg, cosmogony.world (no API afaik) and they don't return it.
https://wiki.openstreetmap.org/wiki/Search_engines lists more. I see them on https://wambachers-osm.website/boundaries/ but you'd have to write your own import/geocoder/point-in-polygon search.

**Comment by InI4** [comment]
Sigh and Thanks. That is the point, seems like doing the decode is a whole project by itself.

These policies are per country? I mean, it seems like we still get meaningful hierarchy in other countries, all problems spotted so far seem to be in Germany.

**Comment by lonvia** [comment]
You can run your own mini-instance of Nominatim with admin boundaries only, see [Filtering Imported Data](http://nominatim.org/release-docs/latest/admin/Import-and-Update/#filtering-imported-data). You can also use osmium to extract and build the administrative boundaries you need directly from the OSM planet file. wambacher's admin boundaries have already been mentioned by @mtmail.

As for the main instance, its main purpose is to be a search database, the hierarchy is just a by-product that will be adjusted as necessary to optimize the search. At the moment only Germany and Belgium are affected but others are bound to follow in the coming months.
