### ISSUE TITLE
Germany, Frankfurt am Main

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1640]
Querying a place in Frankfurt am Main via 
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=50.119698&lon=8.639374&zoom=42&accept-language=en&addressdetails=1
there is a now new intermediate layer "geocoding:city: Frankfurt" between Frankfurt am Main and Bockenheim.  Wasn't there a few weeks ago.

**Comment by lonvia** [comment]
I've opened #1643 for you where you can collect all the examples you find to be wrong and I'll have a look in due time.
