### ISSUE TITLE
USA, Pennsbury Township

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1641]
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=39.877073&lon=-75.669708&zoom=42&accept-language=en&addressdetails=1

there is an admin 6 level "Chester County", which is reflected in the label, but is lacking from the geocoding (i.e. between state and city).

**Comment by lonvia** [comment]
I've opened #1643 for you where you can collect all the examples you find to be wrong and I'll have a look in due time.
