### ISSUE TITLE
Germany, Großkühnau

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#1642]
https://nominatim.openstreetmap.org/reverse?format=geocodejson&lat=51.855291&lon=12.176971&zoom=42&accept-language=en&addressdetails=1

The actual village Größkühnau is reflected in label and admin level 9, but is not contained in the city, state, country geocoding. 

The label introduces Brambach, which can be found nowhere else

**Comment by lonvia** [comment]
I've opened #1643 for you where you can collect all the examples you find to be wrong and I'll have a look in due time.
