### ISSUE TITLE
Updates deleting relations from DB

### ISSUE THREAD

**Issue by arvindkartik** [openstreetmap/Nominatim#1644]
After a full planet import using the latest nominatim release 3.4.1 last week, I've started daily updates. I noticed that certain relations are missing from the DB. 

On debugging, it appears that during updates certain relations are getting deleted - instead of simply updating them - from the DB.

Examples:
https://www.openstreetmap.org/relation/8649 -> Ile-de-France (Last updated on 17th Jan 2020)
https://www.openstreetmap.org/relation/8569 -> Lake Garda (Last updated on 20th Jan 2020). 

These two relations mentioned above were recently updated, and it was deleted from the DB by the update process. 

Querying the `placex` table for the respective osm_id returned valid rows until the data got indexed (for its address rank) during the respective update sequence that contained the changes. After the indexing process has completed for the particular id, the `placex` table no more returned any rows for the said osm_id.

I have another server where I havent run any updates and this relation exists there.

On an older nominatim server (having code before 3.4.0) that has daily updates running, this relation was updated successfully.

Could this be a side effect of the new osm2pgsql bug fixes in #1550?

Config:
```Ubuntu   : 16.04LTS
Memory   : 96GB RAM
CPU      : 8core/16threads
Postgres : 10
Postgis  : 2.4

**Comment by lonvia** [comment]
I've just checked the two OSMF nominatim servers and they still have those two relations. They are both running on the latest Nominatim with a recently reimported database and minutely updates. So it's more likely that something is wrong with your setup.

If you are using a flatnode file, please ensure that it is still there and that the Nominatim configuration still points to the same file.

If all is well on that front, check if the relations are still available in `planet_osm_rels` and have the same data as you can see on the OSM website.

**Comment by mtmail** [comment]
I run several 3.4.1 Nominatim servers with daily updates, oldest fresh import about 3 weeks ago. I don't see those relations missing.

**Comment by arvindkartik** [comment]
Thanks for helping out @lonvia and @mtmail.

You're right about the flatnode file, I have deleted it after the import process. I'll re-import and update again with the flatnode file and see if this problem persists.

Strangely, our older servers do not have flatnode too (but was imported with flatnode), but these relations still exists and updated. 

These relations do exist in `planet_osm_rels` on all servers and it is matching the data as on OSM website

**Comment by lonvia** [comment]
Ok, I'll add a note to the installation instructions to keep the flatnode file around for updates.
