### ISSUE TITLE
Indexing fails with out-of-memory with postgis 3.0

### ISSUE THREAD

**Issue by lelabo-marc** [openstreetmap/Nominatim#1645]
Hi,

While trying a new setup of Nominatim with a country ('France') file from https://www.geofabrik.de/, I noticed my screened process fail.

I had to rerun it multiples time, but each time it's failing to index the 30th rank with an
 `Out of Memory` error.

I decided to run this command one last time, watching a system-monitoring tool (htop):
- **./utils/setup.php --index --index-noanalyse**

The process starts with 30 GB of free RAM before eating it whole. The memory seems to never be released/keep increasing over time.

It happens that at least 7 threads are eating a lot of memory with the following command:
-  **postgres: 12/main: nominatim nomintim [local] UPDATE**

My first assumption is that there is some issue with the `nominatim` binary used for indexing. 

**Config:**

```
Memory   : 32GB RAM
CPU      : 8core
Postgres : 12
Postgis  : 3.0.0
```

**Comment by lonvia** [comment]
It is PostgreSQL that runs out of memory while processing the query, not nominatim. What is the minor version of your Postgresql? What changes did you make to the Postgresql server configuration file?

**Comment by lelabo-marc** [comment]
My postgresql version: **12.1**

The changes made to `/etc/postgresql/12/main/postgresql.conf`

```
        listen_addresses = '*'
        shared_buffers  = 2GB
        work_mem = 50MB
        maintenance_work_mem = 10GB
        fsync = off
        full_page_writes = off
        synchronous_commit = off
        checkpoint_timeout = 10min
        checkpoint_completion_target = 0.9
        max_wal_size = 2GB
        effective_cache_size = 24GB
```

**Comment by lonvia** [comment]
Nothing unusual. It might be that the autovacuum gets in your way. Try setting `autovacuum_work_mem=512MB` and also `autovacuum_max_workers = 1`. The default is to use 3 autovacuum workers and each gets `maintenance_work_mem` memory. So in the worst case they eat up 30GB of your memory.

**Comment by lelabo-marc** [comment]
I tried your settings. The memory consumption is very reasonable until rank 30th (below 3G) but it keeps increasing during the process of the 30th rank.

![After ~2h30](https://user-images.githubusercontent.com/7324915/72909226-f4a1e380-3d36-11ea-8b27-73ad65052874.png)

After 3h of indexation, I reached a state where the counter of the progression was stuck. I waited a few minutes and decided to stop it before reaching `Out of Memory` exception.

![After 3h. Max capacity reached!](https://user-images.githubusercontent.com/7324915/72909415-434f7d80-3d37-11ea-89ac-0a95e882fcba.png)

**Comment by lonvia** [comment]
I've checked my recent import of the planet on a Postgresql 12.1 system and I see that it is indeed piling up a bit of memory over time but not more than a total of 20GB.

Can you try with Postgres 11 and see if the problem persists?

**Comment by lonvia** [comment]
I've just run into a similar issue on my test machine after switching to Postgresql 12.1 with Postgis 3.0. Previous successful imports always were done with Postgis 2.5. So maybe Postgis is the culprit here. Looking into it.

**Comment by lelabo-marc** [comment]
I did not have time yet to setup a new machine with Postgres 11, but when I could, I would try with both version of postgis.

**Comment by lonvia** [comment]
I'm running the same import with psql 12.1 and postgis 2.5 now. I'll let you know if it works.

**Comment by lonvia** [comment]
The import hasn't finished yet but it got much farther than with Postgis 3.0, so I guess we have the culprit. 

There are [a couple of memory leaks](https://trac.osgeo.org/postgis/query?status=assigned&status=closed&status=new&status=reopened&description=~leak&milestone=PostGIS+3.0.1&col=id&col=summary&col=status&col=owner&col=type&col=priority&col=milestone&desc=1&order=id) reported and fixed in Postgis 3.0. In particular the ones in the WKB/WKT parsers might be an issue. I'll try and dig a little bit deeper into it when I find the time.

It might also be wise to close and reopen the connection to Postgresql regularly. This might help mitigating issues with memory leaks. In the meantime, please stay with Postgis 2.5.

**Comment by lonvia** [comment]
#1675 implements regular closing of database connections. This solves the out-of-memory issues on my machine. However, the import is horribly slow. The query planner is not doing well with some of the queries. This is tracked in #1677. In the meantime, my recommendation remains to stay with Postgis 2.5.

**Comment by lelabo-marc** [comment]
Ok, thanks for your time on this issue. I saw you detailed some parameters for deploying with Postgres12.
I will try a new deployment with those and PostGIS 3.1.0alpha1 in which they fixed some of the leaks.
