### ISSUE TITLE
Tuning results

### ISSUE THREAD

**Issue by mpaine-act** [openstreetmap/Nominatim#1646]
I am getting different results from our own "default" installation versus what https://nominatim.openstreetmap.org/search returns, whereas the later returns much better results.  Is the demo website using different defaults than what is posted in this github repository's website?

Does the OSM PBF source play a role in the results?  I am using 

- Postgres version 10, Nominatim master build, Ubuntu 18.04.3
- https://download.geofabrik.de/north-america/us/california/norcal-latest.osm.pbf
- https://nominatim.org/data/tiger2019-nominatim-preprocessed.tar.gz
- https://www.nominatim.org/data/wikimedia-importance.sql.gz
- https://www.nominatim.org/data/us_postcode_data.sql.gz
- @define('CONST_Replication_Url', 'http://download.geofabrik.de/north-america/us/california/norcal-updates');

I using viewbox in search, such as: https://nominatim.openstreetmap.org/search.php?format=json&q=1600%20franklin&viewbox=-122.645261,37.913290,-121.368301,37.423391&bounded=1&addressdetails=1

It should be mentioned in the above search, on my localhost system the address does not return given address.  Why is unknown.

**Comment by mtmail** [comment]
nominatim.osm.org uses pretty much the same install instructions but with all extras (US postcodes, GB postcodes, TIGER etc) like you do. There's no reason why somebody wouldn't be able to install the same on their servers.

The code on nominatim.osm.org can be big ahead testing new features, you usually see them in the master branch in git. The data can be behind because a change in, for example importing or updating, would require a full reimport of the database and doing that regularly is not possible.

I get a result for that query on my installation.

> Does the OSM PBF source play a role in the results?

It can near the boundardies, e.g. when streets are stripped. And some files might be missing the highest level place. E.g. I used a file for Ireland once and it had all states, streets etc but there was no place Ireland. I've use the norcal file a couple of months ago for testing and saw no problems.

Can you run `./utils/check_import_finished.php` in the build directory in the off-chance that an index is missing?

Can you run these database queries to make sure the housenumber got imported and points to the Franking Street?
```
select name->'name' from placex where osm_type='N' and osm_id=3927998688;
select name->'name' from placex where place_id=(select parent_place_id from placex where osm_type='N' and osm_id=3927998688);
```

When you do a reverse search, does the housenumber get found? https://nominatim.openstreetmap.org/reverse.php?lat=37.80541&lon=-122.26875&zoom=18&format=html

**Comment by lonvia** [comment]
Reporter did not answer follow-up questions. Closing.

**Comment by atajadod** [comment]
> 
> 
> nominatim.osm.org uses pretty much the same install instructions but with all extras (US postcodes, GB postcodes, TIGER etc) like you do. There's no reason why somebody wouldn't be able to install the same on their servers.
> 
> The code on nominatim.osm.org can be big ahead testing new features, you usually see them in the master branch in git. The data can be behind because a change in, for example importing or updating, would require a full reimport of the database and doing that regularly is not possible.
> 
> I get a result for that query on my installation.
> 
> > Does the OSM PBF source play a role in the results?
> 
> It can near the boundardies, e.g. when streets are stripped. And some files might be missing the highest level place. E.g. I used a file for Ireland once and it had all states, streets etc but there was no place Ireland. I've use the norcal file a couple of months ago for testing and saw no problems.
> 
> Can you run `./utils/check_import_finished.php` in the build directory in the off-chance that an index is missing?
> 
> Can you run these database queries to make sure the housenumber got imported and points to the Franking Street?
> 
> ```
> select name->'name' from placex where osm_type='N' and osm_id=3927998688;
> select name->'name' from placex where place_id=(select parent_place_id from placex where osm_type='N' and osm_id=3927998688);
> ```
> 
> When you do a reverse search, does the housenumber get found? https://nominatim.openstreetmap.org/reverse.php?lat=37.80541&lon=-122.26875&zoom=18&format=html

Sorry for the late response.
**check_import_finished.php** return everything fine.
we also get the result with our address from the two queries you provided. 
Unfortunately we don't event get the correct result unless we add street to the search, so in our test the link below returns right result (of course we are doing it against our localhost):
>https://nominatim.openstreetmap.org
/search.php?format=json&q=1600%20franklin%20street&viewbox=-122.645261,37.913290,-121.368301,37.423391&bounded=1&addressdetails=1
>
but by removing the "street" from the search, our local copy of nominatim does not return our address 
>https://nominatim.openstreetmap.org/search.php?format=json&q=1600%20franklin&viewbox=-122.645261,37.913290,-121.368301,37.423391&bounded=1&addressdetails=1
>
**Here is an screenshot**
![Nominatim comparison](https://user-images.githubusercontent.com/22226147/73381353-6d92c500-427a-11ea-81b7-3da36426949d.PNG)
As you can see the middle one is wrong even though the search is the same as the top one!

**Comment by lonvia** [comment]
I see nothing wrong with the result you get. It matches '1600 Franklin' exactly and is well within the viewbox you have given. Zoom out a bit and you see a green rectangle depicting the viewbox.

As a general rule: you cannot expect the best search results searching for such generic terms. There are 71 objects with name Franklin street in the bbox you gave. Which one gets returned tends to be a bit random.

**Comment by atajadod** [comment]
Thank you Ionvia. 
I was wondering why the Nominatim website returns the different result (and it is more relevant in this case) compare to my installation. 
If I query placex table with the place_id from the first result I get it returns nothing.
```
select name->'name' from placex where place_id=1550206;
```
so why does it even comes first? shouldn't Nominatim automatically prioritize the result which have placex? 
I do apologize if what I does not make any sense as I am not familiar with Nominatim algorithm or database structure, I am just trying to make sense of what I see.

![image](https://user-images.githubusercontent.com/22226147/73667515-385eec00-4659-11ea-867c-e382b92d6796.png)

**Comment by mtmail** [comment]
Data from TIGER or house number interpolation results don't have an entry in the `place_x` table. Their attached street might have such an entry (that's what the `details` button will link to) but the house number itself is likely in one of the `location_property_*` tables.

nominatim.osm.org result might be more relevant but as @lonvia explained it can be by luck. Nominatim's database allows incremental updates, it is updated minutely, the code/logic/algorithms are updated irregular as well.

I think that's about as much individual support we can give.

**Comment by mpaine-act** [comment]
Thank you everyone for all the answers.

**Comment by lonvia** [comment]
Nominatim searches for addresses by first looking up the street and then checking if there is a matching house number for it. For such an unspecific query as 'Franklin' the first part yields a lot of results. For performance reasons, Nominatim doesn't look through all of them. And all other things being equal, it is random which ones it looks up. Again 'Franklin' is really not a lot to go on here. The osm.org instance happens to contain the street next to the house number you are looking for. Yours doesn't. It's bad luck.

If you don't care too much about performance or know that you always have bounded queries, you can tune the number of streets Nominatim looks at in your instance. Just change the hard-coded number in  [SearchDescription.php](https://github.com/openstreetmap/Nominatim/blob/master/lib/SearchDescription.php#L716). We could probably make that configurable.

**Comment by mpaine-act** [comment]
One idea I had to work around this issues, if we even want to call them that, is for a new lat/long "epicenter" parameter for search.php to sort the results by that location outwards, since our needs is to have a localized experience.  This would work in conjunction with the viewBox parameter.

Have you seen something like idea this considered before?

**Comment by lonvia** [comment]
Yes, photon does something like that and that has proven to be very difficult to weigh correctly.

Viewbox also works as a weight is you leave out the `bounded=1` parameter. Could also be better tuned though, see #824.
