### ISSUE TITLE
House building not using its own street tag, residential landuse, nor nearest street name

### ISSUE THREAD

**Issue by williamsp** [openstreetmap/Nominatim#1649]
For example:
This house building (A1, also all other houses in this landuse) address
https://nominatim.openstreetmap.org/details.php?place_id=227540421

Is not using:
- its own street tag (Ciputat Residence One)
- residential landuse it belong to: https://nominatim.openstreetmap.org/details.php?place_id=228336576
- nearest named street: https://nominatim.openstreetmap.org/details.php?place_id=206881765)

But instead using street name (Jalan Makmur) that a bit far: https://nominatim.openstreetmap.org/details.php?place_id=207313077

Can you check them?
Other houses like this one has address correctly rendered:
https://nominatim.openstreetmap.org/details.php?place_id=229083703 by not using Jalan Cimandiri Raya as its street address

**Comment by lonvia** [comment]
You tagged the house with `addr:street=Ciputat Residence One`. That means there must be a street with that name. If the house number refers to a residence use `addr:place=Ciputat Residence One`.

**Comment by williamsp** [comment]
Hi, can you tell me what's the difference one between [this No.A1 house](https://nominatim.openstreetmap.org/details.php?place_id=227540421) and [this No.1 house](https://nominatim.openstreetmap.org/details.php?place_id=229083703)?

On the second, [landuse:residential Green Urban Townhouse](https://nominatim.openstreetmap.org/details.php?place_id=225772457) registered as address at rank 22. But on the first one, [landuse:residential Ciputat Residence One](https://nominatim.openstreetmap.org/details.php?place_id=228336576) is not, and Jalan Makmur is used at rank 26.

Both of them don't have `addr:place` tag. And also have nearby street mentioned in their `addr:street`, [here](https://nominatim.openstreetmap.org/details.php?place_id=206881765) and [here](https://nominatim.openstreetmap.org/details.php?place_id=228430031) respectively. If we use the same approach, they must be _Ciputat Residence One and Green Urban Townhouse_ OR _Jalan Makmur and Jalan Cimandiri Raya_. But somehow the result is _Jalan Makmur and Green Urban Townhouse_.

Anyway, thanks for suggesting `addr:place`. I will try it.

**Comment by lonvia** [comment]
Nominatim is a bit picky on which changes of one object cause an update of another (that's for performance reasons). In this case, it doesn't automatically update all houses around a street when the addr:* tags change. So you see the new parenting for your house only when it is next updated for some other reason. In the first case, this happened, in the second, it didn't.

NB: please don't use `addr:street` and `addr:place` together on the same building. The housenumber should either refer to a street or to some place. It cannot refer to both at the same time.

**Comment by williamsp** [comment]
I get it now. Thank you for the information. I'm closing this issue now.
