### ISSUE TITLE
Wikipedia importance dump file not found

### ISSUE THREAD

**Issue by FazlanFarook** [openstreetmap/Nominatim#1650]
I have downloaded the Wikipedia files according to the documentation and moved the files under the /srv/nominatim/Nominatim/data folder but I am still getting the error that 
"Wikipedia importance dump file not found"

For download the used the below commands in the ubuntu 18.04
wget https://www.nominatim.org/data/wikipedia_article.sql.bin
wget https://www.nominatim.org/data/wikipedia_redirect.sql.bin

**Comment by mtmail** [comment]
Sounds like you use the latest (master or 3.4.1) version of Nominatim where the filenames changed. See the new wget command in http://nominatim.org/release-docs/develop/admin/Import-and-Update/
