### ISSUE TITLE
Wrong result: Frederiksberghallerne

### ISSUE THREAD

**Issue by prosaole** [openstreetmap/Nominatim#1654]
Searching for Frederiksberghallerne gives no result. 
https://www.openstreetmap.org/search?query=frederiksberghallerne#map=5/48.531/38.848

You get the correct result by searching for "Frederiksberg hallerne", but Frederiksberghallerne should really be a search alias for that.
https://www.openstreetmap.org/search?query=frederiksberg%20hallerne#map=18/55.67610/12.49712

**Comment by mtmail** [comment]
> but Frederiksberghallerne should really be a search alias for that.

You can add e.g. an `alt_name` (https://wiki.openstreetmap.org/wiki/Key:name) to the feature (https://www.openstreetmap.org/way/147562559)

If you think it's more generic for Danish and "Something hallerne" should always be equal to "Somethingallerne" then we have https://wiki.openstreetmap.org/wiki/Name_finder:Abbreviations#Dansk_-_Danish See the German "...universität" on the same page for an example (suffix, concatenated)

**Comment by prosaole** [comment]
It is unclear to me how to edit the abbreviation page when we are not talking about an abbreviation: I have never seen "hallerne" being abbreviated.

But I think it is reasonable for a Danish name to have the following aliases (aliases should not be shown, but if you search for the alias you should find the original):

foohal = foo hal
foo hal = foohal
foohallen = foo hallen
foo hallen = foohallen
foohallerne = foo hallerne
foo hallerne = foohallerne

Can you help edit the wiki to that effect?

**Comment by lonvia** [comment]
I've edited the wiki.
