### ISSUE TITLE
searching for q=russia with limit=5 won't respond with the country russia

### ISSUE THREAD

**Issue by markus-bergelt** [openstreetmap/Nominatim#1656]
searching for russia with a limit of 5 wont respond with the country in first place whereas a limit of 10 does the job. 
No country in results: https://nominatim.openstreetmap.org/search?format=json&q=russia&limit=5
As expected: https://nominatim.openstreetmap.org/search?format=json&q=russia&limit=10

**Comment by mtmail** [comment]
Somebody created second Russia a day ago https://www.openstreetmap.org/relation/10654839

Several of their commits already got reverted https://www.openstreetmap.org/changeset/80322391 I see about deleting this as well.

**Comment by mtmail** [comment]
OK, the small Russia inside Egypt is deleted now in OSM data. https://nominatim.openstreetmap.org/search?format=html&q=russia&limit=5
