### ISSUE TITLE
Response codes 

### ISSUE THREAD

**Issue by yosraf** [openstreetmap/Nominatim#1659]
why status codes are not mentioned in  response returned by the api when i use /search , /reverse and lookup endpoints ?

**Comment by mtmail** [comment]
Do you have an example?

The API returns [HTTP status codes](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes).

```
curl -I 'https://nominatim.openstreetmap.org/reverse.php?lat=50&lon=7&format=jsonv2'
HTTP/2 200
date: Tue, 04 Feb 2020 13:57:12 GMT
server: Apache/2.4.29 (Ubuntu)
content-type: application/json; charset=UTF-8
```

```
curl -I 'https://nominatim.openstreetmap.org/reverse.php?format=jsonv2'
HTTP/2 400
date: Tue, 04 Feb 2020 13:56:29 GMT
server: Apache/2.4.29 (Ubuntu)
content-type: application/json; charset=UTF-8
```

```
curl -I 'https://nominatim.openstreetmap.org/something'
HTTP/2 404
date: Tue, 04 Feb 2020 13:58:42 GMT
```

**Comment by yosraf** [comment]
![issue](https://user-images.githubusercontent.com/56304893/73752207-c83b8d80-4760-11ea-8cd1-3e48ad3df541.png)

**Comment by mtmail** [comment]
Check the documentation of your tool how it handles HTTP status codes.

**Comment by yosraf** [comment]
> Check the documentation of your tool how it handles HTTP status codes.

ok ,thank you
