### ISSUE TITLE
What does address component "address29" represent?

### ISSUE THREAD

**Issue by bidabil** [openstreetmap/Nominatim#1662]
Hi ! 

When trying to reverse these : http://atll.hostaplast.com/nominatim/reverse?format=json&lat=36.77618515&lon=3.05828603472308

I noticed that address is ` "address29": "Place Emir Abdelkader"`

`{
  "place_id": 743978,
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright",
  "osm_type": "way",
  "osm_id": 355559012,
  "lat": "36.77618515",
  "lon": "3.05828603472308",
  "display_name": "Place Emir Abdelkader, Alger Centre, Sidi M'Hamed, Alger - الجزائر, الجزائر",
  "address": {
    "address29": "Place Emir Abdelkader",
    "pedestrian": "Place Emir Abdelkader",
    "town": "Alger Centre",
    "county": "Sidi M'Hamed",
    "state": "Alger - الجزائر",
    "country": "الجزائر",
    "country_code": "dz"
  },
  "boundingbox": [
    "36.7760136",
    "36.7763549",
    "3.0581641",
    "3.0584054"
  ]
}`
is it normal ?

**Comment by mtmail** [comment]
That's normal.

Nominatim sees a feature of rank 29 but can't give the rank a label. As fallback it creates 'address'+rank. This output might be more clear http://atll.hostaplast.com/nominatim/details.php?osmtype=W&osmid=355559012&class=place

Rank 2 is country, rank 4 is state, rank 6 is county, ... house numbers are 28. But for 29 there's no good label. You can treat is as 'other' (very small address feature) or use it as the name of the place. Here it's the name of the square, it's similar with the nearby pharmacy, fast food restaurant or doctor's office.
