### ISSUE TITLE
Bad request with specific city and admin boundary

### ISSUE THREAD

**Issue by IgorEliezer** [openstreetmap/Nominatim#1668]
I tried to search this city "Pará de Minas" (https://nominatim.openstreetmap.org/search.php?q=Par%C3%A1+de+Minas) but Nominatim was returning two results as if the city and its admin boundary were two separate entities.

I had the same issue with suburbs in the past, it returned the place and the boundary as two results. It was simple to solve: make a minor edit in the relation and Nomination liked the boundary with the place and problem solved.

Now I tried to do the same thing: edit the relation by removing and adding members back and changing members order without deleting the relation itself.

If you type in the Search "Pará de Minas", it returns one result as City and the minimap shows the boundary. Ok, but when I click on the result:

```
Bad Request
Nominatim has encountered an error with your request.

Details
Please select a place id
If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used.

https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=315339&class=place
```

---

### New info:

1) This link https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=315339&class=place given by Nominatim as City doesn't work. But if you change its class to boundary https://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=315339&class=boundary, it works.

2) The place as admin_center: https://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=246671466&class=place

3) Also this city/municipality has the same issue: "Patos de Minas" https://nominatim.openstreetmap.org/search.php?q=Patos+de+Minas

**Comment by lonvia** [comment]
Fix is live now. That was a very old hack that changed the class of boundaries in certain circumstances. I just removed it.

NB: **please** do not make nonsensical edits in OSM just to force an update in Nominatim. This is a recipe for pissing off your fellow mappers.

**Comment by IgorEliezer** [comment]
This is issue was opened because an advertising agent who works on behalf of town/cityhalls informed us that a couple of places were returning as I said above in his site at workplace.

Thank you. :)
