### ISSUE TITLE
Can nominatim reverse support a POST request

### ISSUE THREAD

**Issue by bidabil** [openstreetmap/Nominatim#1669]
Hi,

I was trying to reverse a `lat` and `lon` data using post request like that :

```
{
  "lat":"36.77618515",
  "lon":"3.05828603472308",
}
```
the result was : 

```
<?xml version="1.0" encoding="UTF-8" ?>
<error>
    <code>400</code>
    <message>Need coordinates or OSM object to lookup.</message>
    </error>
```

I want to get a Json format response by using a Json Post request ... is that possible ? 

Thanks a lot

**Comment by lonvia** [comment]
No, sorry, that is not possible and we have no plans to support that. Please use a GET request with the appropriate parameters.
