### ISSUE TITLE
Internal Server Error: database nominatim does not exist

### ISSUE THREAD

**Issue by misbahulhoque** [openstreetmap/Nominatim#1680]
I have followed all the instructions from https://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-16/ to setup nominatim in linux server (ubuntu 16.04). I have configured apache2 as mention on that page.
When I am accessing http://localhost/nominatim I am getting the attached page as internal error.
![DBError](https://user-images.githubusercontent.com/10755555/74566147-718c3b80-4f38-11ea-81cb-fe01d61f2b42.jpg)

Thanks in advance.

**Comment by mtmail** [comment]
Did you import data? What is the output of `./utils/check_import_finished.php` (run from the build directory)?

**Comment by misbahulhoque** [comment]
@mtmail 
No, I did not import data. The out of ./utils/check_import_finished.php is,
-bash: ./utils/check_import_finished.php: No such file or directory

**Comment by mtmail** [comment]
Ah ok, the `./utils/check_import_finished.php` is new and not part of Nominatim 3.4.1 yet.

To create the database follow https://nominatim.org/release-docs/latest/admin/Import-and-Update/

**Comment by misbahulhoque** [comment]
@mtmail : imported database country_name.sql from the data directory to nominatim. When I am trying to access localhost/nominatim it is showing the attached error. I tried to use some queries along with localhost/nominatim/search...
![Error](https://user-images.githubusercontent.com/10755555/74574260-c0da6800-4f48-11ea-9422-af655d3661a2.jpg)

**Comment by mtmail** [comment]
> imported database country_name.sql from the data directory to nominatim.

Read the documentation again https://nominatim.org/release-docs/latest/admin/Import-and-Update/ Nowhere does it say anything about importing *.sql files.

**Comment by lonvia** [comment]
Nominatim is a complex piece of software and runs in a complex environment. Installing and running Nominatim is something for experienced system administrators only who can do some trouble-shooting themselves. We are sorry, but we can not provide installation support. We are all doing this in our free time and there is just so much of that time to go around. You can ask questions on the mailing list or on https://help.openstreetmap.org/ but do so only after you have carefully read and understood the installation documentation we provide.
