### ISSUE TITLE
New GB postcode February 2020 file

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#1681]
A new file got released on http://www.ordnancesurvey.co.uk/opendatadownload/products.html#CODEPO. I converted it according to http://nominatim.org/release-docs/develop/data-sources/GB-Postcodes/ and placed it on https://downloads.opencagedata.com/public/gb_postcode_data.202002.sql.gz (35MB)

**Comment by lonvia** [comment]
Copied to nominatim.org.
