### ISSUE TITLE
support more cuisine types

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/Nominatim#1686]
A search for “greek restaurant in rome” doesn’t yield any result, while “pizza in rome” does. Could the latter behavior be extended to all common cuisine types?

**Comment by lonvia** [comment]
Nominatim is foremost a search engine for geographic names, it is not a POI search machine or a search engine that turns free form text into the appropriate OSM tagging. Once the search for geographic names works perfectly, we can revisit that goal. But for the moment: no, sorry, the limited support for tag type search will not be extended.

**Comment by dieterdreist** [comment]
I understand that resources are limited and this is seen as out of scope, but then the things like “pizza in hildrizhausen” should also be removed, just like fuel and all the other poi stuff. Nobody can understand that pizza is working but greek restaurant is out of scope.
