### ISSUE TITLE
Use nomination server as tile server

### ISSUE THREAD

**Issue by Kofl** [openstreetmap/Nominatim#1696]
Hi,

sorry to post here, but we didnt found any other possibility.
Can the nominatim server also be used as openstreet map tile server?
It seems to use the same data source imported into postgres.

Thanks for any tipps,
Thomas

**Comment by mtmail** [comment]
Both can run on the same server, but it's separate installations, separate databases, in effect the data will be on the server duplicate as the database schemas are incompatible.

**Comment by Kofl** [comment]
Bad news, but thanks a lot for the fast repsonse.
