### ISSUE TITLE
Update of linked places should trigger an update of the linkee

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/Nominatim#170]
Needed so that changes in names are merged in correctly.

**Comment by lonvia** [comment]
Needs a test case.

**Comment by lonvia** [comment]
Example: http://www.openstreetmap.org/relation/340756 has linked place http://www.openstreetmap.org/node/1081751552 but when name:es changed from '2' ot 'Marbella' (version 14 to 15) the updated names in the relation weren't updated. Not even a forced place update helped.

**Comment by zstadler** [comment]
There seems to be a couple of duplicates for this issue, each with a test case.

On Apr 22, 2016 @lonvia provided a test case at [#433](433#issuecomment-213124756):
> The changeset at fault is: http://www.openstreetmap.org/changeset/38207753. By removing the name tag from the relation, Nominatim is no longer able to match name and relation. So the link between the two was removed but the place node was not reindexed.

@zstadler provided a test case at #623:
> When looking for "[Kfar Shemuel](http://nominatim.openstreetmap.org/search.php?q=Kfar+Shemuel&polygon=1&viewbox=)", the result is [node 461613375](http://www.openstreetmap.org/node/461613375) - tagged with "name:en"="Kfar Chabad" rather than [way 93463884](https://www.openstreetmap.org/way/93463884) - tagged with "name:en"="Kfar Shemuel"

A related discussion was https://forum.openstreetmap.org/viewtopic.php?id=54376 (in German)

Please remove the "test needed" tag and give this issue higher priority.

Thanks!

**Comment by zstadler** [comment]
For some reason, when looking for the above example, "[Kfar Shemuel](http://nominatim.openstreetmap.org/search.php?q=Kfar+Shemuel&polygon=1&viewbox=)", the result is empty rather than [way 93463884](https://www.openstreetmap.org/way/93463884) - tagged with "name:en"="Kfar Shemuel"
