### ISSUE TITLE
road assigned to wrong hamlet/village: can't fix it

### ISSUE THREAD

**Issue by andrearicci** [openstreetmap/Nominatim#1700]
Hello, I was renaming a road in OSM that the town council changed. When I checked it in Nominatim I found it assigned to the wrong hamlet: (place:hamlet) Montecolognala instead of San Feliciano. In OSM I can't find any associacion with Montecolognola for that road. Where is it coming from? How can I fix it?
https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=26211668&class=highway
all the remaining information are correct.
Thank you

**Comment by mtmail** [comment]
I see you added `is_in:city=San Feliciano` 20min ago. Now https://nominatim.openstreetmap.org/search.php?q=Via+Val+di+Rana%2C+Perugia returns
`Via Val di Rana, Le Piagge, San Feliciano, Perugia, Umbria, 06063, Italy`. San Feliciano is a `place=villiage` but it looks you get the expected result now, doesn't it?

**Comment by lonvia** [comment]
adding `is_in:*` is one possibility, adding an approximate place area for San Feliciano another. There is not much we can do on the Nominatim side because as long as only place nodes are mapped for all the little villages, it remains a guessing game where something belongs to.
