### ISSUE TITLE
addr:place with addr:district addr:subdistrict

### ISSUE THREAD

**Issue by prasadrajuv** [openstreetmap/Nominatim#1701]
addr:street also necessary including addr:place sometimes in villages. some document says addr:street not to use with addr:place when used.

**Comment by mtmail** [comment]
Please add specific examples and links to those documents.

**Comment by prasadrajuv** [comment]
Hyderabad india so many areas are reffered as Hyderabad as city.  If
himayat nagar is added as places it also has street names.
And also my area is Sanjay gandhi nagar, jeedimetla, Hyderabad 500055. We
don't have street names. Jeedimetla well-known to reach by public
transportation. Sanjay gandhi nagar is required to reach my place.
 And also district and sub district required to identity most places in
india

**Comment by mtmail** [comment]
Please add specific search queries you used, ideally the full URL, the results and what was missing or should be added to the results. We don't want to guess and have limited time to research.

> Hyderabad india so many areas are reffered as Hyderabad as city.

Sorry, I don't understand. https://nominatim.openstreetmap.org/search.php?q=Hyderabad+india returns (1. result) a state (2. result) a city and all other results are not cities.

**Comment by prasadrajuv** [comment]
Will you add fields district and sub district which are new specifications in places json read somewhere

**Comment by mtmail** [comment]
No. “Read somewhere” is not enough a reason. You’re not answering specific questions. Closing.
