### ISSUE TITLE
No result with limit=1

### ISSUE THREAD

**Issue by micw** [openstreetmap/Nominatim#1708]
Hello,
I get no result for the (IMO valid) query:

https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&featuretype=postcode&limit=1&q=04821%20Waldsteinberg

When I set the limit to 2 or more, I get the (single) result.

**Comment by txtor** [comment]
There is just one place with this name. The same happens on the osm website, just one result.
https://www.openstreetmap.org/search?query=04821%20waldsteinberg

What else do you expect?

**Comment by mtmail** [comment]
With `&limit=1` there is zero results. That's unexpected.

**Comment by lonvia** [comment]
That was already fixed with #1705. The DB just wasn't reimported, so the change only gradually takes affect over time.

NB: `featuretype=postcode` is ignored in this query. The returned result is for Waldsteinberg not the postcode.

**Comment by micw** [comment]
@lonvia I do not understand how that fix is related to the fact that a one-result query returns zero results with limit=1. Are you sure that the fix applies to this issue (I have no way/idea to verify it)?

**Comment by lonvia** [comment]
I've forced an update for Waldsteinberg in the database. You get a result now. Before updating, the search returned the linked place which was then dropped again on the account of being linked.

**Comment by micw** [comment]
Affirmative, thank you a lot for clarification!
