### ISSUE TITLE
Empty "new_query_log" table

### ISSUE THREAD

**Issue by Pauxis** [openstreetmap/Nominatim#1712]
We have some issues on our nominatim server which has been installed in 2016 and never touched since then. All people who did the setup on this are now gone and I'm trying to understand it little by little.

One of the issues is that the table 'new_query_log' of 'nominatim' schema is > 700 GB and I would like to empty it. 
My idea would be to do a truncate table since they are so many rows in it and they seem "useless", but is there any risk of crashing nominatim doing so? 

Thanks for your help

**Comment by mtmail** [comment]
In the `build/settings` directory you will find a configuration file `local.php` which overwrites any settings from the `settings.php` file. There you can set

```
@define('CONST_Log_DB', false);
// Set to a file name to enable logging to a file.
@define('CONST_Log_File', false);
```

If you run `php-fpm` then you will need to restart that service. php-fpm was not part of the installation instructions so it's unlikely. If not then no restart is necessary.

Now truncate the database table https://www.postgresql.org/docs/9.4/sql-truncate.html

There will be a spike is disk access when the rows are deleted but not Nominatim crashes.

Newer versions of Nominatim have both set to `false` by default.

If you decide to upgrade to a newer version you'd need a full reinstall. Migrating from version to version http://nominatim.org/release-history/ is too much work.

**Comment by lonvia** [comment]
To add to that: You can truncate the table any time, the table only contains logs. As long as the table is there, Nominatim will do fine. So just don't delete and recreate the table. The OSM servers used to have a weekly cronjob that removed any entries older than X weeks.
