### ISSUE TITLE
Address Hoby Mosse 351 225 91 Lund Sverige not found

### ISSUE THREAD

**Issue by sorenmichaelsen** [openstreetmap/Nominatim#1715]
Searching for Hoby Mosse 351 225 91 Lund Sverige does not bring a result.
However the location can be found here: 55.7712711 , 13.1407436

It is as if the street does not have a name?

Street: Hoby Mosse
Number: 351
zip: 225 91
City: Lund
Country: Sverige
https://nominatim.openstreetmap.org/search.php?q=Hoby+Mosse+351+22591+Lund+Sverige&polygon_geojson=1&viewbox=

**Comment by sorenmichaelsen** [comment]
That was fast!!

I am new here. Is this the correct way to report faulty addresses ?

**Comment by krahulreddy** [comment]
I am not one of the maintainers. But I think you can sign up at https://www.openstreetmap.org and start mapping(https://www.openstreetmap.org/fixthemap). It even has tutorials on how to edit maps. https://www.openstreetmap.org/help might help you get started.

> I am new here. Is this the correct way to report faulty addresses ?

https://nominatim.openstreetmap.org => About & Help => Report problem with results
![Screenshot from 2020-03-23 19-49-45](https://user-images.githubusercontent.com/31247036/77326243-87fb9300-6d3f-11ea-8d82-a2bb68c47cc6.png)
Hope this helps

**Comment by sorenmichaelsen** [comment]
Thank you very much!! Have a great day
