### ISSUE TITLE
Inconsistent results when using digits versus spelled out numbers

### ISSUE THREAD

**Issue by simlay** [openstreetmap/Nominatim#173]
Specifically, it fails when querying for an address.

Example:
[Digits](http://nominatim.openstreetmap.org/search.php?q=2323+2nd+Avenue+Seattle%2C+WA+98121) - Works as expected.
[Spelled out street number](http://nominatim.openstreetmap.org/search.php?q=2323+Second+Avenue+Seattle%2C+WA+98121) - Fails.

**Comment by lonvia** [comment]
Closing here in favour of #298.
