### ISSUE TITLE
 gb postcodes data and searching failures

### ISSUE THREAD

**Issue by ruffle-b** [openstreetmap/Nominatim#221]
[I posted this as a question on OpenStreetMap Help and was advised to submit it as a new issue]

I'm trying to use Nominatim to get the Lat/Long for GB Postcodes and struggling. To avoid pounding on OpenStreetMaps's servers I've setup my own Nominatim with the gb_postcode_data but it doesn't seem to get used.

If I query like so:

wget -O - -q "http://mynominatim.somewhere/search?format=xml&postalcode=KA2 9AE&country=gb"

I get no result (same result if I use nominatim.openstreetmap.org for the above query).

wget -O - -q "http://mynominatim.somewhere/search?format=xml&postcode=KA2 9AE&country=gb"

I get no result (using nominatim.openstreetmap.org I get the centroid for the GB admin boundary polygon returned).

wget -O - -q "http://mynominatim.somewhere/search?format=xml&q=KA2 9AE&country=gb"

Returns a place in Wales but the KA2 9AE postcode is in Dundonald, Scotland (the same query on nominatim.openstreetmap.org returns no result). However using "PE8 6XH" as the postcode in the above query I get sensible results from both the official and my nominatim. Huh?

I've checked and "KA2 9AE" is in the gb_postcode_data.sql.gz file so why's it not being used? 

Why the different results from 'my' nominatim and the official one?

I'm probably doing something stupid but I can't work out what. Enlightenment would be greatly appreciated.

**Comment by lonvia** [comment]
There is a [known issue](https://trac.openstreetmap.org/ticket/4910) with normalization of GB postcodes which hits you here.

If you are just interested in lat/lon why don't you just directly query the gb_postcode table?

**Comment by ruffle-b** [comment]
I was trying to simplify the query/problem in the above. What I'd like is the lat/long for an address but searching on the address for the example above failed so my program, currently, reverts to using just the postcode.... which fails :-(

The full query was of the form:

wget -O - -q "http://mynominatim.somewhere/search?format=xml&q=Drybridge Road,Olympic Business Park,Dundonald,KA2 9AE&country=gb"

That fails to find anything so my program reverts to using just the postcode as show above in an attempt to get 'close enough'.

My Nominatim Postgres database isn't accessible to the client generating the http queries so I guess I'll have to do something different as a postcode only fallback.

As a comment (and speaking from the blissful position of knowing nothing about Nominatim's internal workings!) would it not make sense when a query has just the postcode and country=gb like so:

wget -O - -q "http://mynominatim.somewhere/search?postcode=KA2 9AE&country=gb"

for Nominatim to return the info from the gb_postcode database instead of a) nothing or b) the GB centroid ?

**Comment by lonvia** [comment]
If it's really addresses you are trying to geocode, use the workaround described in the trac ticket, comment 4. Then the addresses will at least be found. A direct query for the postcode will still return odd results, though.

**Comment by ruffle-b** [comment]
Thanks. I tried that (made postgres grind it's teeth for a while!) but it makes zero difference to the examples above.

As it stands, I'm unsure how to proceed as I'd rather get no response than a wrong'un. Am I safe to include a postcode in an address query (I understand that just a postcode is doomed to failure).

**Comment by lonvia** [comment]
Fixed with #782.
