### ISSUE TITLE
doesn't find house with part of street name

### ISSUE THREAD

**Issue by ghost** [openstreetmap/Nominatim#312]
Search for "Drij Dreven 2, Heusden-Zolder". Then search for "De Drij Dreven 2, Heusden-Zolder".
Both should find the house [De Drij Dreven 2 (way 232427735)](http://osm.org/way/232427735), but only the latter does.
I added a test case for this [on the wiki](https://wiki.openstreetmap.org/wiki/Nominatim/TestCases#BE).
"De" is an article in Dutch (it means "the") and you should be able to find a road without typing it.

**Comment by dhorions** [comment]
Thanks for adding this!

**Comment by lonvia** [comment]
Closing in favour of #753.
