### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by mdeweerd** [openstreetmap/Nominatim#320]
Hi
I've been looking a bit into performance.  While the Postgresql queries do not seem to be the bottleneck, I suggest two improvements.

I did some analysis with POWA 1.2.
The slowest query types took 7ms, 5ms and 1ms.  I could optimize the 5ms a tiny bit (about 10%) and the 1ms query a lot.

The 5 ms query uses the function below, the query is:

```
SELECT placex.place_id, PARTITION, osm_type, osm_id, class, TYPE, admin_level, housenumber, street, isin, postcode, country_code, parent_place_id, linked_place_id, rank_address, rank_search, COALESCE ( importance, ? - ( rank_search::FLOAT / ? ) ) AS importance, indexed_status, indexed_date, wikipedia, calculated_country_code, get_address_by_language ( place_id, ARRAY [ ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ] ) AS langaddress, get_name_by_language ( name, ARRAY [ ?, ?, ?, ?, ?, ?, ?, ?, ?, ? ] ) AS placename, get_name_by_language ( name, ARRAY [ ? ] ) AS REF, ( CASE WHEN centroid IS NULL THEN st_y ( st_centroid ( geometry ) ) ELSE st_y ( centroid ) END ) AS lat, ( CASE WHEN centroid IS NULL THEN st_x ( st_centroid ( geometry ) ) ELSE st_x ( centroid ) END ) AS lon FROM placex WHERE place_id = ?

CREATE OR REPLACE FUNCTION get_name_by_language(name hstore, languagepref TEXT[]) RETURNS TEXT
  AS $$
DECLARE
--  search TEXT[];
  result TEXT;
--  found BOOLEAN; -- Not used
BEGIN
  IF name is null THEN
    RETURN null;
  END IF;
  FOR j IN 1..array_upper(languagepref,1) LOOP
    IF name ? languagepref[j] THEN
      result:=trim(name->languagepref[j]);
      IF result != '' THEN
        return result;
      END IF;
    END IF;
  END LOOP;
  -- anything will do as a fallback - just take the first name type thing there is
  result := trim((avals(name))[1]);
  RETURN result;
END;
$$
LANGUAGE plpgsql IMMUTABLE;
```

The query that took 1ms could be optimized by adding an index.  The average query time dropped from 1ms down to 0.06ms. The query type is:

```
SELECT address_place_id FROM place_addressline WHERE place_id = ? ORDER BY abs ( cached_rank_address - ? ) ASC, cached_rank_address DESC, isaddress DESC, distance DESC LIMIT ?
```

The index I added is:
    CREATE INDEX place_id_etc ON place_addressline USING btree (place_id, cached_rank_address, isaddress, distance)

**Comment by lonvia** [comment]
I've commited the streamlined get_name_by_language() function with minor formatting changes in 9fb2bf36be7edf63720a4b2514d3e8ab9173558f.

For the index suggestion I need to do some performance tests on a planet-wide database first. Such an index should possibly replace the idx_place_addressline_place_id index on place_addressline.

**Comment by lonvia** [comment]
Some size measurements:

* INDEX USING btree (place_id, cached_rank_address, isaddress, distance) 22 GB
* INDEX USING btree (place_id, cached_rank_address, isaddress) 17 GB
* INDEX USING btree (place_id) 16 GB

As the query normally has a `limit 1`, I suspect that the variant (without distance) shows a similar performance improvement as the first. Could you do some tests to confirm? A 5% penalty in terms of size is quite ok, 40% would be a bit too much.

**Comment by mdeweerd** [comment]
Very old ticket - working good enough.
