### ISSUE TITLE
--osmosis-init download wrong state.txt

### ISSUE THREAD

**Issue by grzeg15** [openstreetmap/Nominatim#359]
At January 31-st I loaded test country Andorra (from http://download.geofabrik.de/europe/andorra-latest.osm.pbf). A few steps then in the script it is command 'setup.php --osmosis-init' and I see it downloaded wrong state.txt file (http://download.geofabrik.de/europe/andorra-updates/000/000/999.state.txt). Correct url is .../000/001/053.state.txt (probably). 
I analyzed that the issue and I found that geofabrik touch the directory 000 and change it the modified date. Then sorting directories are wrong. I changed the line 599 and 614 in the setup.php to "?C=N;O=A;F=1" and now init osmosis downloaded correct file .../000/001/048.state.txt (I think so).

**Comment by esyscoder** [comment]
The same problem with: http://download.geofabrik.de/europe/poland-updates/
 Command downloads last state from `000` not from `001` .  
After manual download, incremental update works fine.

**Comment by lonvia** [comment]
If the modified date on the server changes, the whole algorithm is bound to fail. The only real fix is to change the algorithm completely and read the state.txt of every change.

**Comment by jot82** [comment]
Having the same issue, for some reason the script descends into the 000 folder although current state files are stores in 001... I guess this is broken since sequence numbers got larger than 999?

**Comment by csbrown** [comment]
I have a similar error where nominatim cannot download state files.  Is it possible to import the planet file WITHOUT the state file updates?  I don't need daily updated info, I just need info that is <= 2 years old or so.  Perhaps setup.php has such an option?

**Comment by lonvia** [comment]
Downloading the wrong state file should normally not be fatal and errors can be safely ignored. Are you saying that the import stops if the wrong state file is loaded? (If that happens, the import can be continued without loss of data with `./utils/setup.php --index --create-search-indices`.)

In any case, if you don't need updates, try the --drop option. This will skip the state file download and also regain a lot of space in the end by dropping tables that are only needed for updates and not for normal operations.

**Comment by CaracalSef** [comment]
It seems that I have the same problem, but I don't know how to correct it.
My data: Data: 2015/12/04 22:21 GMT
I am using this command to update: ./update.php --import-osmosis-all --no-npi
and I get: Caused by: java.io.FileNotFoundException: http://download.geofabrik.de/europe/romania-updates/000/000/998.state.txt

**Comment by lonvia** [comment]
It's time to switch to pyosmium for updates and drop the hacky state search code.
