### ISSUE TITLE
move postcode areas into separate table

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#403]
For postal code that share the same prefix we create additional places (`placex` table) during index time. Those places represented by a centroid only, not a polygon as one would expect.

For example for the UK postcode `SW1A 2AA` the postcode area is `SW1A`, for the German postcode `10013` it's `10013`.
https://developer.here.com/rest-apis/documentation/geocoder/topics/coverage-geocoder.html lists various country specific postcode formats. Special consideration should be given to outlier detections (e.g. typos).

The centroid is not recalculated when places in OSM are modified. There's also no process, e.g. script, to start recalculation or to delete a postcode area from Nominatim.

As a first step we want to move the postcode areas into a new table. Later we can write scripts to regularly update the areas. Or if that calculations turns out to very expensive offer downloads of pre-calculated areas.

Table schema (TBD):
- area postcode
- country
- centroid
- geometry

**Comment by hridayns** [comment]
Hi mtmail, 

I have setup a development environment on Vagrant with Nominatim installed and the OSM data for Monaco downloaded. I’m trying to understand what exactly needs to be done to solve the issue. 

What I understand from your post - 
Problem:  The centroid for postal code areas is not recalculated everytime a person changes the bounding box area with iD or other editors.

Solution: To create a separate table with the columns ‘area postcode’,’ country’, ‘centroid’ and ‘geometry’ in which centroid is recalculated everytime someone makes a change to the bounding box area with iD or other editors.

What I need to clarify – 
1.	By places, do you mean the bounding box of a postal area?
2.	Does the centroid get calculated based on the bounding box? Or can a particular postal area have a centroid without a bounding box?
3.	The placex table stores centroid column data in a coded form. Is there some sort of method to convert this to a pair of coordinates which is then shown on the map?
4.	Even if downloads for pre-calculated areas are offered, wouldn’t the areas still need to be updated when someone changes the bounding box of a postal area?

Regards,
Hriday

**Comment by lonvia** [comment]
Postcodes in OSM are not explicitly mapped but appear as part of addresses mapped for houses or POIs. So for each postcode, there are many point coordinates available. On import, Nominatim computes a centroid of all those points and adds the resulting point as an artifical object to the placex table (see utils/setup.php, section calculate-postcodes). This ticket talks about adding these points into a separate table instead.

**Comment by joh-klein** [comment]
How does this relate to #746?

**Comment by lonvia** [comment]
There is no relation to #746 at all.

**Comment by lonvia** [comment]
Implemented in #782.
