### ISSUE TITLE
Include diet key into extratags (or rather the full tag set)

### ISSUE THREAD

**Issue by pmerle** [openstreetmap/Nominatim#405]
Hi,

I've noticed that the "cuisine" key is included in the new extratags=1 output, but not the "diet" key. This makes it difficult to search for vegan restaurants because "cuisine" is deprecated for tagging vegan places. Instead the "diet" tag should be used. Why are not all available keys included in the extratags?

If this issue gets resolved, how long would it take to get the nominatim.openstreetmap.org service reflect the change? Only on a new release or quicker?

Many thanks

**Comment by lonvia** [comment]
I don't take requests for adding specific tags to extratags at the moment but I'm open to the idea to open up extratags in general for all kinds of tags. However, I would like to be able to add a blacklist, similar to the deleted tags in the [osm2pgsql style](https://github.com/openstreetmap/osm2pgsql/blob/master/default.style) to get rid of the worst import tags.

On openstreetmap.org we are normally tracking the master branch, so such a change would appear rather sooner than later.
