### ISSUE TITLE
Bug regarding stop words e.g. for "University of Paris Descartes"

### ISSUE THREAD

**Issue by rossnet** [openstreetmap/Nominatim#415]
This is a reminder ticket about a bug that has already a workaround on nominatim.openstreetmap.org

On the current stable release 2.5.0 there is a problem with stopwords that makes the searchterm like "University of Paris Descartes" to have zero results. As mentioned there is a resultset for the search on osm.org: http://nominatim.openstreetmap.org/search.php?q=University+of+Paris+Descartes

The fix can be achieved by patching Geocode.php on three points:

https://git.openstreetmap.org/nominatim.git/blob/HEAD:/lib/Geocode.php#l1291
https://git.openstreetmap.org/nominatim.git/blob/HEAD:/lib/Geocode.php#l1299
https://git.openstreetmap.org/nominatim.git/blob/HEAD:/lib/Geocode.php#l1305

Thanks a lot to lonvia for her great work on Nominatim and for pointing out the issue!

**Comment by lonvia** [comment]
Those hacks are now part of mainline Nominatim. Stop word handling still needs fixing but this is a different issue.
