### ISSUE TITLE
Retrieve traditional chinese entries from openstreetmap not working

### ISSUE THREAD

**Issue by hpadhuka** [openstreetmap/Nominatim#434]
I want to retrieve both simplified and traditional Chinese entries from openstreetmap. E.g.

<node id="244082315" lat="43.558611" lon="126.228611" version="5"     timestamp="2014-01-21T10:07:18Z" changeset="20119519" uid="274857" user="Supaplex">
<tag k="name" v="永吉县"/>
<tag k="place" v="suburb"/>
<tag k="gns:DSG" v="ADM3"/>
<tag k="gns:UFI" v="-1936843"/>
<tag k="gns:UNI" v="6771391"/>
<tag k="name:vi" v="Vĩnh Cát"/>
<tag k="name:zh" v="永吉县"/>
<tag k="gns:ADM1" v="05"/>
<tag k="name:zh_pinyin" v="Yongji Xian"/>
<tag k="name:zh-simplified" v="永吉县"/>
<tag k="name:zh-traditional" v="永吉縣"/>
</node>
http://nominatim.openstreetmap.org/reverse?format=json&osm_type=N&osm_id=244082315&accept-language=zh

retrieves simplified entry.

http://nominatim.openstreetmap.org/reverse?format=json&osm_type=N&osm_id=244082315&accept-language=zh-TW does not work.

How can I retrieve traditional Chinese ?

**Comment by hpadhuka** [comment]
node id="244082315" lat="43.558611" lon="126.228611" version="5"     timestamp="2014-01-21T10:07:18Z" changeset="20119519" uid="274857" user="Supaplex"
tag k="name" v="永吉县"
tag k="place" v="suburb"
tag k="gns:DSG" v="ADM3"
tag k="gns:UFI" v="-1936843"
tag k="gns:UNI" v="6771391"
tag k="name:vi" v="Vĩnh Cát"
tag k="name:zh" v="永吉县"
tag k="gns:ADM1" v="05"
tag k="name:zh_pinyin" v="Yongji Xian"
tag k="name:zh-simplified" v="永吉县"
tag k="name:zh-traditional" v="永吉縣"

**Comment by mtmail** [comment]
You can add `&namedetails=1` which adds all name tags of a place to the results

http://nominatim.openstreetmap.org/reverse?format=json&osm_type=N&osm_id=244082315&accept-language=zh&namedetails=1

```
"address": {
    "county": "永吉县",
    "state_district": "吉林市",
    "state": "吉林省",
    "country": "中国",
    "country_code": "cn"
},
"namedetails": {
    "name": "永吉县",
    "name:vi": "Vĩnh Cát",
    "name:zh": "永吉县",
    "name:zh_pinyin": "Yongji Xian",
    "name:zh-simplified": "永吉县",
    "name:zh-traditional": "永吉縣"
},
"boundingbox": [
    "43.518611",
    "43.598611",
    "126.188611",
    "126.268611"
]
```

**Comment by lonvia** [comment]
I'm actually not sure what the current state in the OSM database is for transliteration variants. The accepted language code for that choice seems to be zh-TW and zh-CN but that is not used at all in the OSM DB: http://taginfo.openstreetmap.org/keys/name%3Azh-TW, http://taginfo.openstreetmap.org/keys/name%3Azh-CN. 

I can neither see a clear alternative mapping pattern. Taginfo [reports](http://taginfo.openstreetmap.org/search?q=name%3Azh).

```
162 793 name:zh
31 550 name:zh_pinyin
1 467 name:zh-yue
984 name:zh-hant
742 name:zh_py
722 name:zh-min-nan
457 name:zh-classical
304 name:zh-traditional
254 name:zh-py
```

name:zh-hant seems to emerge for traditional transcript. You can get those with `&accept-language=zh-hant`. Still with less than 1% of objects with Chinese name mapped with this, I wouldn't call it established mapping.

**Comment by lonvia** [comment]
This is an OSM data issue and cannot be fixed in Nominatim directly.
