### ISSUE TITLE
Vatican City country code

### ISSUE THREAD

**Issue by bjbschmitt** [openstreetmap/Nominatim#457]
Hi, I'm facing a small issue working with Nominatim due the fact that Vatican City country code is missing.

As can be verified in [https://nominatim.openstreetmap.org/details.php?place_id=143992614](https://nominatim.openstreetmap.org/details.php?place_id=143992614), its address field has no place:country_code associated.

For sake of comparison, here are the details for another country (Albania) [https://nominatim.openstreetmap.org/details.php?place_id=144919794](https://nominatim.openstreetmap.org/details.php?place_id=144919794) . It can be noticed that the second line of the address field contains the country's respective code ('al').

(additionally - and probably also related to this issue - I have noticed that the Vatican City field "Rank" is equal "Sea", while the same field is equal to "Country" for the other countries).

**Comment by lonvia** [comment]
There is something wrong with the country partition for Vatican city, nothing gets assigned into this partition. Possibly an error in the `country_osm_grid` table.

**Comment by mtmail** [comment]
Adding the raw response because the place_id is pointing to a random highway now (place_id gets regenerated during full re-imports).

```
$curl -s 'http://nominatim.openstreetmap.org/search.php?q=Vatican+City&format=jsonv2&addressdetails=1&limit=2&accept-language=en' | jq '.'
```

http://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=36989
http://nominatim.openstreetmap.org/details.php?osmtype=N&osmid=424311883

```javascript
[
  {
    "place_id": "3938635",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
    "osm_type": "node",
    "osm_id": "424311883",
    "boundingbox": [
      "39.3434912",
      "44.4634912",
      "9.8928349",
      "15.0128349"
    ],
    "lat": "41.9034912",
    "lon": "12.4528349",
    "display_name": "Vatican City",
    "place_rank": "7",
    "category": "place",
    "type": "state",
    "importance": 0.88056898289676,
    "icon": "http://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png",
    "address": {
      "state": "Vatican City",
      "country": "Vatican City",
      "country_code": "va"
    }
  },
  {
    "place_id": "177471542",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
    "osm_type": "relation",
    "osm_id": "36989",
    "boundingbox": [
      "41.9002044",
      "41.9073912",
      "12.4457442",
      "12.4583653"
    ],
    "lat": "41.9038101",
    "lon": "12.4531575923712",
    "display_name": "Vatican City",
    "place_rank": "3",
    "category": "boundary",
    "type": "administrative",
    "importance": 0.88056898289676,
    "icon": "http://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png",
    "address": {
      "country": "Vatican City"
    }
  }
]```

**Comment by lonvia** [comment]
Looks like this got fixed with the update of country_osm_grid. Please reopen, if you find another example where the country_code is actually missing.
