### ISSUE TITLE
Reverse Geocode with Tag Requirement

### ISSUE THREAD

**Issue by SuberFu** [openstreetmap/Nominatim#459]
How feasible is it to have reverse geocoding to only return result that contains a specific set of tags. For example, return the nearest result that contains at least a "City" or "Village".

I'm thinking about something like a new parameter like `required_tags` like follow (hopefully in correct Augmented BNF).

```
required_tag = "required_tag=" requirement_list 
requirement_list = tag *1("," tag )
tag = 1*(DIGIT / ALPHA)
```

The reverse geocode will search for the nearest point that contains at least one `tag` from the `requirement_list`.

EDIT: Checked out the code for a bit, perhaps I can modify the `lib/ReverseGeocode.php`'s `lookup()` function to conditionally insert additional where to require non-null tags.

Is `lib/lib.php`'s `getClassTypes()` the one to look up tag <> database-column mapping? Essentially, look in `label` in the value for what the resulting json/xml tag will be, and the key for the database column name?

EDIT2: Digged into the code more, it looks like it can only effeciently handles requiring a single tag.

**Comment by SuberFu** [comment]
Further question, am I correct to assume that all class name in `getClassTypes()` is of the form of
`class:type:admin_level` in the database?

**Comment by lonvia** [comment]
This is not really something Nominatim was made for. The [overpass API](http://wiki.openstreetmap.org/wiki/Overpass_API) does a much better job. You can also have a look at the Nominatim-based geocoding engine [Photon](https://github.com/komoot/photon). It comes with tag filters.

If what you actually want is reverse geocoding with results on city level, have a look at the zoom parameter.

**Comment by SuberFu** [comment]
If I can get it working, would you be willing to consider including the change in a pull request?

**Comment by lonvia** [comment]
Hard to say, as I'm not sure what you are trying to achieve.

**Comment by SuberFu** [comment]
Basically, something like photon's "with_tag" argument. So that I can reverse geocode to find the nearest object that's tagged as "place:city", for example.

**Comment by SuberFu** [comment]
Made a pull request that implements the osm_tag flag for reverse coding. Setting osm_tag will cause the reverse geocoding to only return result that matches the tag.
For example:
`osm_tag=place:city` returns nearest city.
`osm_tag=place:city,place:town` returns nearest city or town.

**Comment by lonvia** [comment]
Sorry, but I'm still not convinced you are using the right hammer for your nail. And you'll probably find that your code gives you some rather surprising answers for your particular examples because place tags are handled in a special way in Nominatim. So could you please explain the task for which you plan to use this query?

**Comment by SuberFu** [comment]
I want to locate the nearest city given the lat/lng. At least in the North America, the above query seems to work well (I only have the NA import).

**Comment by lonvia** [comment]
That's what the zoom parameter is for, i.e. http://nominatim.openstreetmap.org/reverse?lat=41.83295892&lon=-87.62190989&zoom=7 to get a result at city level. In contrast to the tag filtering it takes into account the admin boundaries. The results do have a few known oddities but I'd rather see those fixed than a new feature introduced with new quirks.

**Comment by SuberFu** [comment]
The issue I'm running into is that this query.
http://nominatim.openstreetmap.org/reverse?lat=30&lon=-100&zoom=7
Does not return the nearest city but the nearest county (which is not a city).

**Comment by SuberFu** [comment]
How about I constrain the admin_level instead? Change the `zoom` parameter that if you do something like `7-7`, it only returns the nearest result at admin level 7. `7-` for any admin level >= 7, `7-10` for admin level from 7 down to 10, and so on?

**Comment by SuberFu** [comment]
Dug into the database a bit more. here's a thought. Instead of messing around with `reverse`, perhaps a new api function called `nearby` that finds nearest point(s) that matches OSM tags.
I'm thinking of a query like the following.

```
SELECT pt.place_id, pt.name, ST_Distance(geography(ST_SetSRID(ST_Point(-100,30),4326)), geography(ST_Union(pt.geometry, ref.geometry))) As distance FROM placex AS pt
LEFT JOIN placex AS ref ON pt.linked_place_id=ref.place_id
WHERE pt.class='place' and pt.type='city'
and (ST_DWithin(ST_SetSRID(ST_Point(-100,30),4326), pt.geometry, 2) Or ST_DWithin(ST_SetSRID(ST_Point(-100,30),4326), ref.geometry, 2))
ORDER BY ST_Distance(geography(ST_SetSRID(ST_Point(-100,30),4326)), geography(ST_Union(pt.geometry, ref.geometry)))
limit 5;
```

The `ST_DWithin` distance would be tweaked over several queries (similar to the current reverse geocoding) until the right number is returned.

P.S. Tried OverpassAPI a bit, can't get the performance needed (need close to 20 request per seconds) and the API don't support getting nearest (so the search always boil down to "try an area", if no result, try bigger area, if multiple result, sort and get nearest).

**Comment by SuberFu** [comment]
Having tried previous query, turns out to have some timeout behavior if osm_tag is not defined. Turns out it's not using the geospatial index.

```
SELECT comb.place_id 
FROM (SELECT pt1.place_id, pt1.geometry FROM placex AS pt1 
      WHERE pt1.linked_place_id is null and ST_DWithin(ST_SetSRID(ST_Point(-96,30),4326), pt1.geometry, 0.2) 
      and (( pt1.class = 'place' and pt1.type = 'city' )) 
      UNION 
      SELECT pt2.place_id, ref.geometry FROM placex AS pt2 
      LEFT JOIN placex AS ref ON pt2.linked_place_id=ref.place_id 
      WHERE pt2.linked_place_id is not null and ST_DWithin(ST_SetSRID(ST_Point(-96,30),4326), ref.geometry, 0.2) and (( pt2.class = 'place' and pt2.type = 'city' ))
      ) AS comb 
  ORDER BY ST_Distance(geography(ST_SetSRID(ST_Point(-96,30),4326)), geography(comb.geometry)) ASC, ST_Area(comb.geometry) ASC limit 1
```

In short, it returns the nearest place with the given osm_tag. If multiple objects are equally close (for example, multiple places that contains the latlng itself, like a country and city, which result in distance of 0), return the smallest result in terms of area.
I'm currently working on an implementation that's derived from the `reverse` function called `nearby`. Performance with at least one fully defined osm_tag is pretty good (~50ms), without any tags is about ~700ms.

**Comment by lonvia** [comment]
POI search like this in Nominatim will not happen. Closing.
