### ISSUE TITLE
search for a street returns administrative region

### ISSUE THREAD

**Issue by zwn** [openstreetmap/Nominatim#473]
The search for "[střední, nová ves pod pleší](http://nominatim.openstreetmap.org/search.php?q=st%C5%99edn%C3%AD%2C+nov%C3%A1+ves+pod+ple%C5%A1%C3%AD&polygon=1&viewbox=)" returns 4 results. The first two are administrative regions city and suburb and only the third is the actual street (the fourth is railway stop). I would expect to get only the third result as the only result as that uses all search terms.

**Comment by zwn** [comment]
This is the expected result: http://nominatim.openstreetmap.org/details.php?place_id=76372014

**Comment by zwn** [comment]
This is the expected result: http://nominatim.openstreetmap.org/details.php?place_id=76372014

**Comment by mtmail** [comment]
Thanks Zbyněk for reporting!

It's pretty obvious the first and second result are in the same region but not precise enough. I see two result sets are merged in the background and the one on city-level dominates. Not sure yet why, needs more research.

**Comment by zwn** [comment]
Can I help in any way? I mean, can I do anything that does not require me to import whole planet.osm into postgresql db?

**Comment by lonvia** [comment]
Stredni is part of the name for http://www.openstreetmap.org/relation/435515 which appears in the address of all results. We do some reordering according to how well the result matches the query but in this particular case the vastly higher importance wins out. We'll probably need a reordering against well-known address formats (see #213) to get better reordering results without breaking stuff that works today.

**Comment by lonvia** [comment]
This is working at the moment but there is a larger issue about in which order to interpret a search query here. Closing here in favour of #929 which presents the opposite case.
