### ISSUE TITLE
Why is there ways in location_area_country

### ISSUE THREAD

**Issue by RemiBou** [openstreetmap/Nominatim#543]
In OpenStreetMap, countries and borders are flagged with the same admin level : 2. But in Nominatim for indexing we are interested only on the full country borders : the relation.

If i do this query

```
select placex.*
from location_area_country 
inner join placex on placex.place_id = location_area_country.place_id and placex.osm_type='W'
```

I should have no results. But I think you'll get some results on the production server because there is some indexing error like this one

http://nominatim.openstreetmap.org/details.php?place_id=3997564

Where the country is http://www.openstreetmap.org/way/46419230

The solution I found on my server is changing insertion into location_area_country which is in the method insertLocationAreaLarge by

```
IF EXISTS(SELECT * FROM placex WHERE place_id = in_place_id AND osm_type='R')
        INSERT INTO location_area_country values (in_partition, in_place_id, in_country_code, in_keywords, in_rank_search, in_rank_address, in_estimate, in_centroid, in_geometry);
    RETURN TRUE;
```

**Comment by lonvia** [comment]
That's for historical reasons, dating from the times before relations existed. Boundaries were modeled with closed ways then and some still are.  A year or two back, we discussed excluding all `boundary=adminstrative` ways but then there were still too many valid ones in the US. Maybe it's time to revisit that decision.
