### ISSUE TITLE
Handle wikipedia tags that differ on relation and place node better

### ISSUE THREAD

**Issue by dieterdreist** [openstreetmap/Nominatim#562]
I just noticed that there was maybe some recent tweaking which now leads to worse results. My example: I am within the Rome boundaries (if this matters, not sure), do search for "Roma", am logged in with default language set to english. I am looking at some other place on the map (e.g. north africa, while searching), e.g. http://www.openstreetmap.org/search?query=roma#map=14/39.5067/-1.1579
and I do NOT get the city of rome as any of the displayed search results, let alone the first, but I get suburbs and localities in Spain and hamlets in Australia, Mexico and Argentinia with this name. 
When I have Rome visible on the screen I get it as first result.

**Comment by lonvia** [comment]
This is a data issue. Somebody has changed the associated wikipedia page for Rome from the important main page to some unimportant subpage in [this changeset](http://www.openstreetmap.org/changeset/41469552). Nominatim derives the importance (and thus the result ranking) from the the wikipedia page, so the change has cause a deranking of Rome.

**Comment by dieterdreist** [comment]
I was looking for the place, not the administrave entity though. This is the node: http://www.openstreetmap.org/node/72959652

**Comment by lonvia** [comment]
Those are the same for Nominatim.

**Comment by dieterdreist** [comment]
Why is it not working then? The node has still the wikipedia link with the high rank...

**Comment by lonvia** [comment]
It's probably wise to use the maximum importance in cases where the wikipedia tags on place node and administrative boundary differ.
