### ISSUE TITLE
Multiple place with same osm_id

### ISSUE THREAD

**Issue by RemiBou** [openstreetmap/Nominatim#573]
Hi

` select osm_type,name->'name' from place where osm_id = 61083317;`

Returns 2 records, the conséquences are the following : 
- there is also two lines in placex
- only one of them has linked_place_id set to the osm id 76910
- you have two result when you search for "Corse" 

I can't find where the place table is filled, maybe it's osm2pgsql.

**Comment by lonvia** [comment]
An OSM object may appear multiple times in the place table when it has different functions. In your example "Corse" is a natural=island and a place=state. The unique key for place is defined as (osm_type, osm_id, class).

However, there is still a lot wrong in that example:
 * For http://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=76910 the relation should be linked to the place=state, not the natural:island.
 * The tagging of natural=island on the place node is simply wrong. natural should go on areas only. The correct tag for island on a node is place=island. Nominatim should ignore natural on nodes.

If you want a quick-fix for the particular example, simply delete the natural=island on the node and things will sort themselves out.

**Comment by RemiBou** [comment]
I'll need to reindex those placex right ?

**Comment by lonvia** [comment]
Well, yes, but that should all happen automatically if you fix the OSM data and then run updates on your Nominatim database.
