### ISSUE TITLE
Why is the `isaddress` value not always reliable in my export?

### ISSUE THREAD

**Issue by redox** [openstreetmap/Nominatim#584]
Hi guys,

I'm using the Nominatim XML export to associate to each street, its associated postcode, city & country. In the export, I'm not sure how to interpret the `isaddress=t|f` field of the `<address` nodes.

Often times, I have a `highway` feature with 2 `<state` nodes with value `postcode`:
 - first one has `isaddress="f"` and still, is the good one
 - second one has `isaddress="t"` and seems to be related (good structure & start with the right numbers) but still it's not the one.

```xml
  <feature place_id="688578" type="W" id="269797844" key="highway" value="residential" rank="26" importance="26" parent_place_id="215711" parent_type="N" parent_id="1212907470">
   <names>
    <name type="name">Rue des Ormes</name>
    <name type="name:fr">Rue des Ormes</name>
    <name type="name:gsw">Rustbamgass</name>
   </names>
   <adminLevel>15</adminLevel>
   <address>
    <state rank="8" type="N" id="1251610265" key="place" value="state" distance="0.533992456761799" isaddress="t"/>
    <state rank="11" type="P" id="211" key="place" value="postcode" distance="0.0153066880308778" isaddress="f"/>
    <state rank="11" type="P" id="243" key="place" value="postcode" distance="0.0122408969488243" isaddress="t"/>
    <county rank="12" type="R" id="7415" key="boundary" value="administrative" distance="0.18372252173117" isaddress="t"/>
    <county rank="14" type="R" id="4630050" key="boundary" value="administrative" distance="0.0230139208977625" isaddress="t"/>
    <city rank="16" type="R" id="71033" key="boundary" value="administrative" distance="0.0541318416579529" isaddress="t"/>
    <suburb rank="20" type="N" id="1212907470" key="place" value="suburb" distance="0.00326783611737206" isaddress="t"/>
   </address>
   <tags>
    <tag type="oneway">yes</tag>
   </tags>
   <osmGeometry>LINESTRING(7.7195288 48.5959967,7.7195075 48.5959326,7.7193456 48.5954495,7.7193445 48.5954312,7.7193416 48.5953811)</osmGeometry>
  </feature>
```

Last example I have is "rue des Ormes, Strasbourg, FRANCE" where the correct postcode (67200) has `isaddress="f"` and another one (67012) has `isaddress="t"`.

Any idea how to interpret that?

**Comment by lonvia** [comment]
The one with isadress="t" is the one that Nominatim has identified  as the most likely match for the given address and the one that will be shown in the result when searching. The other one is another candidate that might be valid as well. It will not be shown but when searching for the combination of rue des Ormes and that other postcode, you will get a result.

ThT said, your base problem in all that is that a) postcode coverage in the underlying OpenStreetMap is very patchy (there are often only some address points tagged with a postcode, there are no postcode areas) and b) Nominatim's alogorithm to match up the postcodes is even crappier (for a few issues with processing in Nominatim, see #403). So don't expect the postcode information to be precise.
