### ISSUE TITLE
Replication delay

### ISSUE THREAD

**Issue by SanyaBeer** [openstreetmap/Nominatim#604]
After full planet import I run:
`./utils/update.php --import-osmosis-all --no-npi`
After this osmosis output is: 
```
2017-01-05 07:39:16 Replication Delay is 135993600
/usr/bin/osmosis --read-replication-interval workingDirectory=/home/nominatim/Nominatim-2.5.1/settings --simplify-change --write-xml-change /home/nominatim/Nominatim-2.5.1/data/osmosischange.osc
янв 05, 2017 10:39:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.43.1
янв 05, 2017 10:39:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
янв 05, 2017 10:39:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
янв 05, 2017 10:39:16 AM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
```
Osmosis will be import 4 year changes? In nominatim site after import "Data last updated:
2012/09/13 00:04 GMT"

**Comment by lonvia** [comment]
This is wrong unless you have used a planet from 2012. What data did you import?

**Comment by SanyaBeer** [comment]
Prelatest planet, maby for 26.12.2016. I have idea import latest weekly changes file using osmosis manually. Maby this help fix this?

**Comment by SanyaBeer** [comment]
Or just update table import_status and set correct date from pbf file? I don't know why import.php do not update this information. I have some problems before with create indexes, deadblock transactions.

**Comment by lonvia** [comment]
Try running `./utils/setup.php --osmosis-init `, then check if there is a `settings/state.txt` and if the date in there makes sense. If not, then `--osmosis-init` is again broken. In that case you need to set your state file manually. Go to `http://planet.osm.org/replication/`, find the approriate state.txt file and copy it to `settings/state.txt`. Then try running update.php again. If all goes well, the import_status will be updated after the first round of updates.

**Comment by SanyaBeer** [comment]
Thank you! Problem will be in replication url. I try using osm mirror http://ftp5.gwdg.de/pub/misc/openstreetmap/planet.openstreetmap.org/replication/day and it download wrong state file. If setup http://planet.openstreetmap.org/replication/day state file download are correct. I don't know is this a bug or something else.

**Comment by lonvia** [comment]
Related to #359. closing here.
