### ISSUE TITLE
India is broken in country_osm_grid.sql

### ISSUE THREAD

**Issue by giggls** [openstreetmap/Nominatim#616]
Hello,

looks like India is almost nonexistant in country_osm_grid.sql. All we currently have is Sikkim Province.

I'm using this table for country dependent transliteration in https://github.com/giggls/mapnik-german-l10n

Regards

Sven

**Comment by lonvia** [comment]
There is now an amended version of the country_grid at http://lonvia.de/nominatim/country_grid.sql.gz. I need to find a more permanent place for this file. Due to its size it will no longer be possible to check it into the git repo.

**Comment by lonvia** [comment]
The file now has found a permanent home: http://www.nominatim.org/data/country_grid.sql.gz

Still need to include it in the setup process.
