### ISSUE TITLE
Geocoding Bad result with Paris district in ZipCode

### ISSUE THREAD

**Issue by batou76** [openstreetmap/Nominatim#618]
When we haven't result for a full address query, we call the api with ZipCode + City, but sometimes we have strange result if the district is specified in the query.

Example:

Geocoding : 34 rue Marx Dormoy, 75018 Paris 18 return no result, so we try with only 75018 Paris 18;
http://nominatim.openstreetmap.org/search?q=75018+paris+18&format=xml&limit=1 

It returns a result at Chili but not in Paris, so it's a problem to render this geocoding result.

**Comment by lonvia** [comment]
It's 'Paris 18' that's causing the trouble. In OSM the arrondissement is only known by longer names, see [relation 9531](http://www.openstreetmap.org/relation/9531). It is really difficult to fix that kind of error without adding special local knowledge. I'd lean toward adding the name in the OSM relation but that is something the French community needs to decide.

For the moment, two suggestions to improve your search results:

 * If you know that the result will be in France add `countrycodes=fr` as a parameter to your query to avoid results that are in Chile.
 * If a full result is not found, leave out the zip code and arrondissement numbers first. The zip code is more likely to be missing in OSM than the street.

**Comment by lonvia** [comment]
Closing as data issue that needs to be solved on the OSM side.
