### ISSUE TITLE
could not find PostgreSQL (missing: PostgreSQL_INCLUDE_DIR)

### ISSUE THREAD

**Issue by adlersantos** [openstreetmap/Nominatim#642]
Hi! I'm trying to install Nominatim on MacOS Sierra (10.12.3).

I've stumbled upon the following error when running the `$ cmake ..` command from within the `build` directory:

```
CMake Error at CMakeLists.txt:37 (add_subdirectory):
  The source directory

    /Users/adler/Nominatim/osm2pgsql

  does not contain a CMakeLists.txt file.


CMake Error at /usr/local/Cellar/cmake/3.8.0-rc1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_INCLUDE_DIR)
```

For my current postgres installation, I'm using the [Postgres app](https://postgresapp.com/) for OS X. Hope you can help!

**Comment by mtmail** [comment]
Looks like https://postgresapp.com/documentation/troubleshooting.html doesn't install header and include files to compile against. The Postgres of https://brew.sh/ does and tells you the paths during installation.

You might be the first person installing Nominatim on MacOS and we haven't supported it as platform. It's much easier to run a Linux virtual machine and install Nominatim in there. See https://github.com/twain47/Nominatim/blob/master/VAGRANT.md That's what I use on my iMac.

**Comment by lonvia** [comment]
Also make sure you have osm2pgsql actually cloned (run `git submodule update --init` to verify).
