### ISSUE TITLE
Geos 3.6 compat

### ISSUE THREAD

**Issue by melvyn-sopacua** [openstreetmap/Nominatim#648]
This affects the used osm2pgsl. Geos 3.6.x has made some members private, so it no longer compiles. FreeBSD now has 2 versions of geos in the ports tree, that can be installed simultaneously, but have different include path and library name.

Either way, Geos 3.6 cannot be used at the moment, so configure tests should be added for < 3.6.0. A simple test would be based on:
```
osm2pgsql/geometry-builder.cpp:272:25: error: calling
      a protected constructor of class 'geos::geom::GeometryFactory'
        GeometryFactory gf;
                        ^
/usr/local/include/geos/geom/GeometryFactory.h:420:2: note: declared protected
      here
        GeometryFactory();
        ^
```

**Comment by lonvia** [comment]
Switching to a non-geos osm2pgsql is in the works. A cmake check is still welcome and would need to be backported to the current release. Unfortunately, due to the nature of the break we can do nothing but bail out if the wrong geos version is used.

**Comment by melvyn-sopacua** [comment]
Would you like this upstream or in our main CMakeLists.txt? We deligate to osm2pgsl's CMakeLists.txt, but I don't mind to do it in ours.

**Comment by lonvia** [comment]
It's something for the Nominatim CMakeList. osm2pgsql is about to get rid of geos support in master.

**Comment by lifepillar** [comment]
Is it possible to work around this problem by using a pre-installed osm2pgsql?

**Comment by lonvia** [comment]
You can use the git master of Nominatim with the current osm2pgsql git master which has no longer any dependency on geos. Be aware, however, that databases are not compatible. If you already have an installation you have to reimport.

**Comment by lifepillar** [comment]
@lonvia Thanks, that got me past the osm2pgsql build step. I get other errors later on, but if I cannot figure out how to fix them, I'll open a new issue.

**Comment by lonvia** [comment]
The latest osm2pgsql without geos support is now merged. Nominatim master no longer has a direct dependency on geos.
