### ISSUE TITLE
No results when adding postal code to search query

### ISSUE THREAD

**Issue by meijdenmedia** [openstreetmap/Nominatim#650]
[No result](http://nominatim.openstreetmap.org/search.php?q=Jacob+Stolpstraat+4%2C+1462MV+Middenbeemster%2C+NL&addressdetails=1&format=json) vs [result](http://nominatim.openstreetmap.org/search.php?q=Jacob+Stolpstraat+4%2C+Middenbeemster%2C+NL&addressdetails=1&format=json)

The weird thing is that when you open 'result' you see the postcode matches the one given in the query string in the 'No result' link. The given street is currently in building process. For all other requests it's working perfectly.

[Result](http://nominatim.openstreetmap.org/search.php?q=Kalverstraat+3%2C+1012NX+Amsterdam%2C+NL&addressdetails=1&format=json) vs [result](http://nominatim.openstreetmap.org/search.php?q=Kalverstraat+3%2C+Amsterdam%2C+NL&addressdetails=1&format=json)

I hope somebody can help me out :)

**Comment by lonvia** [comment]
The postcode you see in the result comes from the building. It normally should find it's way back into the search index of the street (which is required if you want to be able to find it) but it doesn't. I suspect that when the street was updated, it didn't merge the postcodes again. Needs a test to confirm.

**Comment by PhilHa** [comment]
I've got a pretty similar problem:

Nominatim finds the municipality "Meisburg" ( [meisburg](http://nominatim.openstreetmap.org/search.php?q=meisburg&addressdetails=1&format=json) ) and also it's postal code "54570" ( [54570](http://nominatim.openstreetmap.org/search.php?q=54570&addressdetails=1&format=json) ).
But combining these two values it can't find anything ( [meisburg+54570](http://nominatim.openstreetmap.org/search.php?q=54570+meisburg&addressdetails=1&format=json) ).

But there is definitely a proper postal code boundary in osm ( [postalCode](http://www.openstreetmap.org/relation/1259858) ) and when adding any street to the queries of postal code ( [54570+Kirchstraße](http://nominatim.openstreetmap.org/search.php?q=54570+kirchstra%C3%9Fe&addressdetails=1&format=json) ) or the village name ( [Meisburg+Kirchstraße](http://nominatim.openstreetmap.org/search.php?q=meisburg+kirchstra%C3%9Fe&addressdetails=1&format=json) ) there are results with full information (village + postal code).

May there be a problem with the multipoygonal postal code and may there be a bug while checking if the villiage is within that area?

**Comment by lonvia** [comment]
Fixed with #782.

**Comment by aoreinoso** [comment]
I think I have the same problem today.

Sample: No resut with "Calle Periodista Francisco de Paula Terrón. Granada 18015" but with ""Calle Periodista Francisco de Paula Terrón. Granada "  I have results:
...
"Vía peatonal Calle Periodista Francisco de Paula Terrón, Cerrillo de Maracena, Chana, Granada, Comarca de la Vega de Granada, Granada, Andalucía, 18014, España"

"Vía peatonal Calle Periodista Francisco de Paula Terrón, Cerrillo de Maracena, Chana, Granada, Comarca de la Vega de Granada, Granada, Andalucía, 18015, España"
...

Thanks

**Comment by mtmail** [comment]
@aoreinoso Please open a new issue. This issue got closed 2 years ago.
