### ISSUE TITLE
index idx_placex_rank_search fails with "failed to find parent tuple"

### ISSUE THREAD

**Issue by ksc-thom** [openstreetmap/Nominatim#653]
When importing DACH-data in a Nominatim 2.5 on Ubuntu 14.04, Postgres 9.6, Postgis  2.3.2 I repeatedly got an error 

nominatim@nominatim ERROR:  failed to find parent tuple for heap-only tuple at (548808,29) in table "placex"
nominatim@nominatim STATEMENT:  CREATE INDEX idx_placex_rank_search ON placex USING BTREE (rank_search) ; 

in the search-index stage. I rerun several times with
./utils/setup.php create-search-indices --threads 4
and got the above error or "number of items mismatch in GIN entry tuple"

Finally I succeeded by reducing the number of threads to one. Is there a race condition possible?

Thomas

**Comment by lonvia** [comment]
This sounds like your database is corrupted. I strongly recommend to check the hard disk and RAM for failures.

**Comment by ksc-thom** [comment]
Hi Sarah,
I tested the RAM with Memcheck and it really found defect RAM. Thank you for your reply!
