### ISSUE TITLE
Can't handle more than 20 Chinese characters

### ISSUE THREAD

**Issue by leesiongchan** [openstreetmap/Nominatim#654]
20 Chinese characters (Success)
https://nominatim.openstreetmap.org/search?q=%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94&accept-language=en%2C*%3Bq%3D0.5&format=json

21 Chinese characters (500)
https://nominatim.openstreetmap.org/search?q=%E6%88%91%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94%E5%96%94&accept-language=en%2C*%3Bq%3D0.5&format=json

**Comment by lonvia** [comment]
The number of words that are allowed in a query is intentionally limited. Chinese characters are considered one word per character. Does this limit provide a practical problem?

**Comment by leesiongchan** [comment]
We faced this problem when we used `formatted_address` given by Google Maps, turns out the address is longer than expected.

**Comment by lonvia** [comment]
I'd need a more concrete example where that many characters are needed in search. The word limit exists precisely to avoid that people dump random output from other programs into the openstreetmap.org instance.

**Comment by alexander-kucheryavenko** [comment]
Hi @lonvia, 

Maybe here is the case where we need to handle more then 20 characters, but not 100% sure.

`中国 安徽省 宣城市 郎溪县 郎溪县人民医院 九楼 护士站 黎琪 收`
Looks like this is and address of some hospital in China, please check this case if its possible. 

Thanks.

Best regards.

**Comment by mtmail** [comment]
Source seems to be https://community.travelchinaguide.com/forum2.asp?i=79271

**Comment by lonvia** [comment]
Resolved in #1412.
