### ISSUE TITLE
No polygonpoints field returned 

### ISSUE THREAD

**Issue by widy-sky** [openstreetmap/Nominatim#655]
I try to call this 
url http://nominatim.openstreetmap.org/search.php?q=jakarta+barat&format=json&polygon=1
the result show the "polygonpoints" field but if I call this url http://nominatim.openstreetmap.org/search.php?q=jakarta+selatan&format=json&polygon=1
there is no "polygonpoints" field returned at the result. Hope anybody help to fix this...thanks

**Comment by mtmail** [comment]
Thanks for reporting

The `&polygon=` parameter is deprecated. It works for "simple" polygons but seems to fail for complex multipolygons. https://wiki.openstreetmap.org/wiki/Nominatim#Parameters

Both
http://nominatim.openstreetmap.org/search.php?q=jakarta+selatan&format=json&polygon_text=1
and
http://nominatim.openstreetmap.org/search.php?q=jakarta+selatan&format=json&polygon_geojson=1
work.
