### ISSUE TITLE
Error executing external command:  -i -d nominatim -P 5432 -t 15 -r 26

### ISSUE THREAD

**Issue by ARSimmons** [openstreetmap/Nominatim#657]
I've installed a new server using [this installation guide](https://github.com/openstreetmap/Nominatim/blob/master/docs/install-on-ubuntu-16.md). It has been running for just shy of 2-3 days, and I just got this error.

PL/pgSQL function insertsearchname(integer,bigint,character varying,integer[],integer[],integer,integer,double precision,geometry,geometry) line 922 at SQL statement
PL/pgSQL function placex_update() line 349 at assignment
ERROR: Error executing external command: /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 15 -r 26
Error executing external command: /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 15 -r 26

Troubleshooting ideas? 2-3 days doesn't sound adequate for a planet file...

**Comment by mtmail** [comment]
Can you check the Postgres log files? Especially for an entry "FATAL:  connection to client lost" ? That would indicate either a network issue (if the database is not on the same host). Or other messages where the disc ran full. Last week somebody reported a crash that turned out to be faulty RAM chip on their system.

Related: https://github.com/openstreetmap/Nominatim/issues/409

2-3 days setup time for a planet file is possible. 16 cores, 64+GB RAM, fast SSD discs. If for example you don't have SSD it can take 1-2 weeks.

**Comment by ARSimmons** [comment]
@mtmail hm. I'm looking but I don't see much in the logs (possibly because the log setting was really turned down by me).

...If this local instance of nominatim w/ planet load "was" working, what would be a good way to test?

**Comment by lonvia** [comment]
It looks like you were in the indexing step. At this point you can just continue the import with the following command:

    ./utils/setup.php --index --create-search-indices --create-country-names

Turn up the postgres log level before continuing. If it fails again, see that you can get a more extensive error message. The message above just tells where the problem happened. It is unfortunately missing the actual error, so not much to go on.

**Comment by ARSimmons** [comment]
@lonvia 

Ok. I did that...after a few more days, I found this in the console. Is it installed? The syntax error (and why is ANALYZE mia?) seem odd...

(1 row)

 count
-------
   247
(1 row)

 count
-------
 11688
(1 row)

Setup finished.

real    3739m55.999s
user    251m1.936s
sys     315m16.240s
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils#
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils# ANALYZE
ANALYZE: command not found
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils# nominatim version 2.5
nominatim: command not found
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils#
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils# Starting indexing rank (26 to 30) using 15 threads
bash: syntax error near unexpected token `('
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils# Starting rank 26
Starting: command not found
root@ip-10-0-102-26:/srv/nominatim/Nominatim/build/utils# screen -ls

**Comment by lonvia** [comment]
Looks like you copied some odd stuff into the console while the setup was running. It has nothing to do with the setup.php command itself. The command finished successfully, so your database should be ready.

It's impossible to say what the initial error was unless you can provide a more extended error message. Likely candidates are  that postgres got restarted by somebody else. Closing for now. Please, reopen if you encounter the error again and can provide a more extensive error log.
