### ISSUE TITLE
Admin_level mappings are inconsistent, can the levels be returned explicitly?

### ISSUE THREAD

**Issue by IByte** [openstreetmap/Nominatim#662]
When using the addressdetails=1 parameter to Nominatim, mappings from the admin_level tag to keys such as village, town, county etc. appear to be somewhat unpredictable and inconsistent with the tables at http://wiki.openstreetmap.org/w/index.php?title=Tag:boundary%3Dadministrative#10_admin_level_values_for_specific_countries. An automated county lookup is hard to do if I can't tell in advance in what key the correct result will be.

A possible solution to this is returning the admin_level values explicitly without trying to map them to the keys addressdetails uses. If the admin levels are returned explicitly, I know I can find a Dutch municipality at admin level 8, for example. I propose the parameter adminlevels=1, which would return the actual admin levels as keys instead. (This would give the client software the ability to deal with the admin levels itself, instead of having to rely on approaches such as the one mentioned in #213.)

Example:

The API query below would give the following result (pretty-printed JSON):

Query:
http://nominatim.openstreetmap.org/reverse?lat=51.82766&lon=5.9256833&addressdetails=1&format=json&accept-language=nl&adminlevels=1

Result:
```
Array
(
    [place_id] => 33766406
    [licence] => Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright
    [osm_type] => node
    [osm_id] => 2804195365
    [lat] => 51.8276667
    [lon] => 5.925576
    [display_name] => 11, Nieuwe Holleweg, Beek, Berg en Dal, Stadsregio Arnhem Nijmegen, Gelderland, Nederland, 6573DT, Nederland
    [address] => Array
        (
            [house_number] => 11
            [road] => Nieuwe Holleweg
            [suburb] => Beek
            [village] => Berg en Dal
            [county] => Stadsregio Arnhem Nijmegen
            [state] => Gelderland
            [postcode] => 6573DT
            [country] => Nederland
            [country_code] => nl
        )

    [admin_levels] => Array
        (
            [admin_level_10] => Beek
            [admin_level_08] => Berg en Dal
            [admin_level_06] => Stadsregio Arnhem Nijmegen
            [admin_level_04] => Gelderland
            [admin_level_03] => Nederland
        )

    [boundingbox] => Array
        (
            [0] => 51.8275667
            [1] => 51.8277667
            [2] => 5.925476
            [3] => 5.925676
        )

)
```

**Comment by lonvia** [comment]
I lean more towards improving the addressdetails view in general. It should become an (ordered) array of hashes where we can add arbitrary additional information, e.g:

    address : [
        { 'admin_level' : 8, 'name' : 'Berg en Dal'},
        { 'admin_level' : 4, 'name' : 'Gelderland'},
        { 'admin_level' : 2, 'name' : 'Nederland', 'ref' : 'nl'}
     ]

**Comment by Megachip** [comment]
So, any way to fix this? html response is correct, the `display_name` (json)/`result` (xml) is correct but the `address` (json)/`addressparts` (xml) is totally rubbish. (at least in Thuringia).

**Comment by IByte** [comment]
I've taken a look at it myself, but the (lengthy) SQL code used to generate the address parts is arcane, to say the least, so it might take attention from someone who knows more about the internals of OSM/Nominatim.

**Comment by Megachip** [comment]
@lonvia so #704 should also belongs to that problem?

**Comment by lonvia** [comment]
Closing here in favour of #809.
