### ISSUE TITLE
Failures to unzip TIGER2015 data when running ./imports.php >?

### ISSUE THREAD

**Issue by ARSimmons** [openstreetmap/Nominatim#663]
Following the instructions from [ this installation guide](https://github.com/openstreetmap/Nominatim/blob/master/docs/Import_and_update.md) I tried:

`
>/srv/nominatim/Nominatim/build/utils# ./imports.php --parse-tiger /vol/tiger_data/ftp2.census.gov/geo/tiger/TIGER2015/EDGES`

And received a bunch of 

```
sh: 1: unzip: not found
Failed unzip (/vol/tiger_data/ftp2.census.gov/geo/tiger/TIGER2015/EDGES/tl_2015_72153_edges.zip)
Processing 78010...
sh: 1: unzip: not found
Failed unzip (/vol/tiger_data/ftp2.census.gov/geo/tiger/TIGER2015/EDGES/tl_2015_78010_edges.zip)
Processing 78020...
sh: 1: unzip: not found
Failed unzip (/vol/tiger_data/ftp2.census.gov/geo/tiger/TIGER2015/EDGES/tl_2015_78020_edges.zip)
Processing 78030...
sh: 1: unzip: not found
Failed unzip (/vol/tiger_data/ftp2.census.gov/geo/tiger/TIGER2015/EDGES/tl_2015_78030_edges.zip)

```

...the zips look like they are there (and as far as I can tell are correct). Should I try to unzip them before running ./imports.php?

**Comment by lonvia** [comment]
No, you have to install unzip.
