### ISSUE TITLE
Import Database

### ISSUE THREAD

**Issue by amisha2016** [openstreetmap/Nominatim#670]
Hi,
I have imported data on local server for Nominatim through the command 

> $sudo -u postgres ./utils/setup.php --osm-file ~/Downloads/ludhiana.pbf --all --osm2pgsql-cache 2300 | tee setup.log

After completion of a command there were around 792 relations in the database nominatim. I want to ask the meaning of the relations like <location_road_99> and so on. These type of relations are completely empty. How should I populate them with data? 

I am working on Ubuntu 14.04 LTS with postgresql-9.3-postgis-2.2.

![osmdata](https://cloud.githubusercontent.com/assets/17342222/24072701/e3b0cffa-0c10-11e7-8ede-1804aac5d22f.png)

Thanks in advance.

**Comment by mtmail** [comment]
That's fine. Data for `location_road` and others is split into 100+ tables for performance. With a small dataset it's expected that some tables remain empty.

**Comment by amisha2016** [comment]
Thanks @mtmail for your reply. Here all the splited tables are empty. If I want to populate them with data what should I do for that because on my server the max cache can be 2300(--osm2pgsql-cache 2300) which I have applied already.

**Comment by mtmail** [comment]
`./utils/setup.php` imports and indexes all data, there is no other tool needed. Did running the script without error? 

The area of http://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=1948490 looks small enough to finish on a machine with 2GB RAM.

Why are you looking at the table sizes? Is there another error you're trying to debug?

**Comment by lonvia** [comment]
Reporter did not answer follow-up questions. Closing.
