### ISSUE TITLE
endian.h

### ISSUE THREAD

**Issue by netluca1** [openstreetmap/Nominatim#672]
I followed the instructions but when I compile 2 errors occur 
One is endian.h  not found

[root@nominatim build]#  cmake3 $USERHOME/Nominatim
-- Building osm2pgsql 0.93.0-dev
-- Looking for include file termios.h
-- Looking for include file termios.h - found
-- Looking for include file libgen.h
-- Looking for include file libgen.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for lseek64
-- Looking for lseek64 - found
-- Looking for posix_fallocate
-- Looking for posix_fallocate - found
-- Looking for posix_fadvise
-- Looking for posix_fadvise - found
-- Looking for sync_file_range
-- Looking for sync_file_range - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off_t
-- Check size of off_t - done
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found EXPAT: /usr/lib64/libexpat.so (found version "2.1.0")
-- Found BZip2: /usr/lib64/libbz2.so (found version "1.0.6")
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
-- Found Osmium: /srv/nominatim/Nominatim/osm2pgsql/contrib/libosmium
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PostgreSQL: /usr/pgsql-9.6/lib/libpq.so (found version "9.6.2")
Libraries used to build: /usr/lib64/libboost_system-mt.so/usr/lib64/libboost_filesystem-mt.so/usr/pgsql-9.6/lib/libpq.so/usr/lib64/libz.so-lpthread/usr/lib64/libexpat.so/usr/lib64/libbz2.so/usr/lib64/libgeos.so/usr/lib64/libproj.so
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
Active compiler flags:
-- Added test: test-expire-tiles...
-- Added test: test-hstore-match-only...
-- Added test: test-middle-flat...
-- Added test: test-middle-pgsql...
-- Added test: test-middle-ram...
-- Added test: test-options-database...
-- Added test: test-options-parse...
-- Added test: test-options-projection...
-- Added test: test-output-multi-line-storage...
-- Added test: test-output-multi-line...
-- Added test: test-output-multi-point-multi-table...
-- Added test: test-output-multi-point...
-- Added test: test-output-multi-poly-trivial...
-- Added test: test-output-multi-polygon...
-- Added test: test-output-multi-tags...
-- Added test: test-output-pgsql-area...
-- Added test: test-output-pgsql-schema...
-- Added test: test-output-pgsql-tablespace...
-- Added test: test-output-pgsql-validgeom...
-- Added test: test-output-pgsql-z_order...
-- Added test: test-output-pgsql...
-- Added test: test-parse-diff...
-- Added test: test-parse-xml2...
-- Added test: test-pgsql-escape...
-- Added test: test-wildcard-match...
-- Found PythonInterp: /usr/bin/python (found version "2.7.5")
-- Added test: regression-test-pbf (needs Python with psycopg2 module)
-- Found PostgreSQL: /usr/pgsql-9.6/lib/libpq.so (found version "9.6.2")
-- Using osmosis at /etc/osmosis/bin/osmosis
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.1")
-- Looking for byteswap.h
-- Looking for byteswap.h - found
-- Looking for sys/endian.h
-- Looking for sys/endian.h - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /srv/nominatim/Nominatim/build

**Comment by lonvia** [comment]
This cmake output looks fairly normal and I don't see any error reported. It is normal that some lines report 'not found'. What is the compile error and on what system are you?

**Comment by netluca1** [comment]
the mistake relates that does not find the library endian.h 
"Looking for sys/endian.h - not found"
I am use RedHat7x64

**Comment by lonvia** [comment]
As I said, that's not an error. That's just the configuration system checking what is available and what isn't.
