### ISSUE TITLE
Odd string of postcodes for Basque County addresses

### ISSUE THREAD

**Issue by cbowdon** [openstreetmap/Nominatim#673]
It looks like some addresses in Basque County, Spain have a long string of postcodes associated instead of just one. For example, Boulevard Zumardia:

http://nominatim.openstreetmap.org/details.php?place_id=130574607

Previous edits and other search engines suggest the postcode should be just 20003 for that address. Is this an error?

**Comment by lonvia** [comment]
My favorite solution to the problem would be that these postcode collections are removed from the OSM data. But given that Nominatim needs to work with the data we have now, I think we need to simply ignore any postcodes with , or ; when merging postcodes back in for display.
