### ISSUE TITLE
Can't access localhost/nominatim

### ISSUE THREAD

**Issue by chrismarkos** [openstreetmap/Nominatim#677]
Closely followed the instructions for Ubuntu 16.04 (https://github.com/openstreetmap/Nominatim/blob/master/docs/install-on-ubuntu-16.md), but I get 403 Forbidden when I try to access localhost/nominatim.

> You don't have permission to access /nominatim/ on this server.
> Apache/2.4.18 (Ubuntu) Server at localhost Port 80

Any suggestions? Thank you in advance.

**Comment by mtmail** [comment]
Can you try adding `/search.php` to the URL?

In https://github.com/openstreetmap/Nominatim/blob/master/vagrant/install-on-ubuntu-16.sh we have a `DirectoryIndex search.php` line in/for the Apache configuration. I don't see that line in https://github.com/openstreetmap/Nominatim/blob/master/docs/install-on-ubuntu-16.md

**Comment by chrismarkos** [comment]
Adding the extra line in the Apache configuration worked, thank you!

I am now able to access localhost/nominatim/search.php., _however_, when I do a search I get 

> The requested URL /search.php was not found on this server.

and when I click on "reverse search" I get

> The requested URL /reverse.php was not found on this server.

**Comment by mtmail** [comment]
In your `<build directory>/settings/local.php` you can set

```php
@define('CONST_Website_BaseURL', 'http://'.php_uname('n').'/');
```
It sounds like adding '/nominatim/' to the path should work. No webserver restart required. If the file doesn't exists yet remember to add `<?php` to the first like similar to `settings/settings.php`.

**Comment by chrismarkos** [comment]
I did this:
`
@define('CONST_Website_BaseURL', 'http://'.php_uname('n').'/nominatim/');`

but it doesn't seem to work. I can still manually do the queries by changing the wrong ("ubuntu") part of the URL to "localhost/nominatim" though.

**Comment by mtmail** [comment]
Yes, play with that variable value. I've never seen an 'ubuntu' string in there. The HTML templates are using the variable like this

https://github.com/openstreetmap/Nominatim/blob/master/lib/template/search-html.php#L13

**Comment by chrismarkos** [comment]
That's weird, any changes I make in <build directory>/settings/local.php seem to be having no effect whatsoever.

**Comment by mtmail** [comment]
You should have two settings directories. On in the Nominatim directory `/home/ubuntu/Nominatim` I guess. And one in the build directory (`/srv/nominatim/Nominatim/build/` based on the Apache conf you posted above). The one in the build directory is used by the website.

**Comment by chrismarkos** [comment]
My bad, it's working perfectly now, thank you for your time!
