### ISSUE TITLE
Are housenumbers available for Italy (center)?

### ISSUE THREAD

**Issue by chrismarkos** [openstreetmap/Nominatim#681]
I've installed Nominatim and am interested in reverse geocoding requests in the center of Italy (downloaded from [http://download.geofabrik.de/europe/italy/centro.html](url) as suggested by the installation guide). Is there any way to get the housenumber along with the street name?

Also, is there a fundamental difference between zoom 16 and 17?

**Comment by mtmail** [comment]
Housenumbers are returned at zoom level 18 (the default), example http://nominatim.openstreetmap.org/reverse.php?format=html&lat=43.799814250152664&lon=11.224993765354158&zoom=18
that depends on the OpenStreetMap coverage of course (if mappers or import added housenumber data in that region)

For street only use level 16. I think 17 is a placeholder and has no effect.
