### ISSUE TITLE
Cannot redeclare getDB()

### ISSUE THREAD

**Issue by lifepillar** [openstreetmap/Nominatim#684]
I am using the current master. On trying to import a data set with this command:

```
cd build
./utils/setup.php --osm-file map.osm --all 2>&1 | tee setup.log
```
I get this error:

```
Fatal error: Cannot redeclare getDB() (previously declared in /Web/php/nominatim/lib/db.php:6) in /Web/php/nominatim/lib/DB.php on line 19
```

Any idea what the problem is and how I can fix it?

**Comment by mtmail** [comment]
The message is a bit misleading as PHP needs to load the file DB.php and instead re-loads Nominatim's db.php. To solve this make sure you have the Pear module 'DB' installed. 
```
 sudo pear install DB
```

**Comment by lifepillar** [comment]
The fact is, I do have it installed:

```php
<?php
require_once('DB.php');
var_dump(class_exists('DB', false));
?>
```

```sh
$ php test-db.php
bool(true)
```

**Comment by mtmail** [comment]
Any chance the test-db script loads the wrong DB class? For example if that class has a `getDBQuoted` method then it would be nominatim/lib/db.php

**Comment by lonvia** [comment]
How about just renaming Nominiatim's  `db.php` file? It is only referenced once in `init.php` as far as I can see, so that should be quick.

**Comment by lifepillar** [comment]
Same error. Anyway, I have created a VirtualBox image with a fresh Ubuntu system, I was able to install Nominatim there following the instructions in the Readme, and now it's loading my data. For my purposes that should be enough.

**Comment by lonvia** [comment]
We really should switch to mdb2.

Closing for now as it is not reproducible here. Please reopen if you can supply more information.
