### ISSUE TITLE
503 on service endpoint and website?

### ISSUE THREAD

**Issue by jasonglisson** [openstreetmap/Nominatim#687]
I'm not even sure where to report this issue. I've been getting 503 errors and service unavailable issues for the last few days. Nothing seems to be improving. I get it randomly on the Nominatim website as well. Anyone know what's going on?

**Comment by mtmail** [comment]
Do you have one or two example queries including the full domain name?

(Background: the software that runs http://nominatim.openstreetmap.org/ has a "report issues" link pointing here. But others can install the software as well on their servers so I want to make sure you see errors from a server under our control).

**Comment by lonvia** [comment]
We've been having trouble with some users abusing (or misusing) the service and making it unusable for everybody else.

**Comment by jasonglisson** [comment]
Thanks for replying. 

When my application tries to get access this endpoint, I get a 503. When I visit it, I get a 503, but when I refresh a few times, it comes through eventually.

https://nominatim.openstreetmap.org/reverse?format=json&lat=37.3740&lon=-92.0342
https://nominatim.openstreetmap.org/reverse?format=json&lat=32.8468&lon=-103.9873
https://nominatim.openstreetmap.org/reverse?format=json&lat=36.6018&lon=-104.8662

I actually just refreshed 3 times and and gave me a 503 again. It's basically any link with nominatim.openstreetmap.org goes down often.

Just saw lonvia's comment about user abuse. What exactly is happening that's hijacking the service?

**Comment by lonvia** [comment]
Somebody opening a lot of connections and then not responding. Should be better now.

**Comment by mtmail** [comment]
It's a free service run my volunteers on donated hardware and bandwidth and there's users who have no problem sending 100.000s of requests or trying to crawl every place on earth which can overload the servers. So by abuse we usually mean too many requests per second.
