### ISSUE TITLE
Nominatim update crashed

### ISSUE THREAD

**Issue by SrihariThalla** [openstreetmap/Nominatim#688]
We have encountered this error and the `update.php` process crashed with `Error 1`:

![screenshot 2017-03-25 12 25 57](https://cloud.githubusercontent.com/assets/7479937/24320189/3e5dbb08-1156-11e7-8ff1-de387045306c.png)

Thanks in advance!

**Comment by mtmail** [comment]
Looks like the issue described in http://blog.geofabrik.de/?p=403, https://lists.openstreetmap.org/pipermail/geocoding/2017-March/001859.html

**Comment by SrihariThalla** [comment]
Thanks @mtmail!
