### ISSUE TITLE
Search prioritises exact match over relevance

### ISSUE THREAD

**Issue by arschficken** [openstreetmap/Nominatim#689]
Run [a Nominatim search for osan korea](https://nominatim.openstreetmap.org/search.php?q=osan+korea). The only result is for a bus stop named "Osan", which happens to be the only exact match. Nominatim helpfully zooms in on this bus stop. Unfortunately, it is on the other side of the country to the city of Osan-si and its related Osan Air Base.

The only indication that this might not be the right Osan is the "Search for more results" button, which when clicked, does indeed show the more expected results, and refocus the map on Osan city.

Related [iD bug number 3930](https://github.com/openstreetmap/iD/issues/3930)

**Comment by lonvia** [comment]
Duplicate.

**Comment by arschficken** [comment]
@lonvia Which bug? #562?

**Comment by mtmail** [comment]
@arschficken I'm offended by your username. I think you should change it https://help.github.com/articles/changing-your-github-username/

**Comment by mtmail** [comment]
Nominatim preferring exact matches over distance/proximity is one of the unsolved issues of the search algorithm, going back to almost the beginning. This ticket is 4 years old https://trac.openstreetmap.org/ticket/4770. We haven't found a good balance between exact match, score/relevance and distance yet. I think the ID editor already sets bounds (focus point) which helps calculating the distance (to the map center). Currently there's no setting to force Nominatim to return un-exact matches as first result.
