### ISSUE TITLE
How to avoid “429 Too Many Requests” errors in local installation? 

### ISSUE THREAD

**Issue by lifepillar** [openstreetmap/Nominatim#693]
I need to map tens of thousands of addresses using a dedicated server, but after a while I start getting “too many requests” errors. Which parameters can I tweak to avoid that?

**Comment by lifepillar** [comment]
Never mind, this appears to be related to the library I use to send the queries (the geocoder Ruby gem).

**Comment by lifepillar** [comment]
For posterity, this is my issue with geocoder: https://github.com/alexreisner/geocoder/issues/1163.
Sorry for the noise and for accidentally hammering the public servers.

**Comment by mtmail** [comment]
thanks!
