### ISSUE TITLE
issue with osmline_update() function in Nominatim/sql/functions.sql

### ISSUE THREAD

**Issue by tonynovi** [openstreetmap/Nominatim#695]
I'm trying to run nominatim on Centos 7

after running setup.php i got the following message
(some tables created by script in DB before this)
> Functions
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
CREATE FUNCTION
ERROR:  RETURN must specify a record or row variable in function returning row
LINE 50:     RETURN 0;
                    ^
ERROR: pgsql returned with error code (3)
pgsql returned with error code (3)

I found the exact place in functions.sql for which the script shows the error

it is located in osmline_update() function on [line 1029](https://github.com/openstreetmap/Nominatim/blob/master/sql/functions.sql#L1029) where 0 is returned for the function with a Trigger type.

as I understand there should be something like RETURN NULL; or RETURN NEW;, but I don't exactly know what to choose.

do you have any ideas how to fix this?

**Comment by mtmail** [comment]
https://github.com/openstreetmap/Nominatim/blob/b3186d07f5860473c7d80185b9dfbb1804ff3ec3/sql/functions.sql#L1029 (just in case the code on the master branch changes).

Can you post which version of postgres (`psql --version`) and postgis (`select postgis_full_version();`) you're using? PostGIS has changed method, e.g. requiring additional parameters, in the past.

Does this error happen during an initial import of a database? Or any hint which place/data it affected?

**Comment by lonvia** [comment]
Definitely an error in our code. It should be `RETURN NULL`.

**Comment by tonynovi** [comment]
psql (PostgreSQL) 9.2.18
PostGIS 2.0.7

it was initial import (I followed steps from github documentation)
