### ISSUE TITLE
Special phrases update

### ISSUE THREAD

**Issue by Klofutar** [openstreetmap/Nominatim#696]
Could you please update the special phrases?  I added Slovenian language (https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/SL).

**Comment by lonvia** [comment]
Done now because we had a reimport. But on a general note: it won't help much to open a ticket about updating these special phrases until there is a tool to actually update them. As things are at the moment, they can only be updated on a full database reimport.
