### ISSUE TITLE
Feature name with comma

### ISSUE THREAD

**Issue by snodnipper** [openstreetmap/Nominatim#698]
It is not currently possible to search for Points of Interest (POI) where the feature name contains a comma.

For example,  "Winterthur Museum, Garden & Library" does not match the feature whereas "Winterthur Museum Garden & Library" does.

Caveats
The address provided on their [recruitment page](http://www.winterthur.org/?p=741#apply) is:
```
Human Resources
Winterthur Museum, Garden & Library
5105 Kennett Pike
Winterthur, DE 19735
```
but I do accept in this particular example they [also use](http://www.winterthur.org/?p=1049) the following (without a comma).

```
Winterthur 
5105 Kennett Pike (Route 52) 
Winterthur, DE 19735
```

Regardless, I believe features with a comma are valid names to be searched.

**Comment by lonvia** [comment]
I agree that this is a missing feature that would be nice to have but it is very unlikely that it is ever going to happen. The comma as separator of address parts is a very fundamental assumption in Nominatim's design. I don't know of any way to change that which would not result in a very hefty performance penalty. And that is simply not worth paying for the rare cases where the comma is part of a name.

So, I'm sorry to say that I have to close this as a 'won't fix' but anything else would be unrealistic.

**Comment by snodnipper** [comment]
Understood.  It is good to at least mark these issues as "wontfix" so that others can see limitations and maybe raise a business case to fund future development.

Thank you.

@AndrewRadburn

**Comment by lonvia** [comment]
Sidenote: photon, the elasticsearch frontend for nominatim, has no issues names with commas: http://photon.komoot.de/api/?q=Winterthur%20Museum,%20Garden%20&%20Library
