### ISSUE TITLE
street number suffixes ("st", "nd", "rd", "th") should work

### ISSUE THREAD

**Issue by tilmanb** [openstreetmap/Nominatim#70]
As per https://help.openstreetmap.org/questions/24457/should-th-and-nd-forms-of-numbered-streets-be-added-as-alt_names-to-motorways :

Street number suffixes should be optional, a search for "North 1 Street, Loisaida,  New York" and "North 1st Street, Loisaida,  New York" should both return http://www.openstreetmap.org/browse/way/5677637 , regardless of the actual name in the OSM database.

**Comment by lonvia** [comment]
Closing in favour of #298.
