### ISSUE TITLE
Reverse Geocoding Based on Poylgons

### ISSUE THREAD

**Issue by pproenca** [openstreetmap/Nominatim#705]
Hi,

While going through the codebase there's something that caught my attention: reverse geocoding is being done, in part, [based on the distance of a point, provided by the user, to the nearest centroid in database](https://github.com/openstreetmap/Nominatim/blob/master/lib/ReverseGeocode.php#L121-L130).
[IMO this seems like it's going to return weird results in some situations](https://github.com/openstreetmap/Nominatim/issues/143), is there a reason for using this search strategy against: searching within polygons, to find which one contains the point, and then find the nearest point within that polygon?

**Comment by lonvia** [comment]
There are two reasons why the code is like this: for one part, the code was written at a time where polygons were rare in the OSM database and most features expressed as points. For the other part, the code tries to minimize the number of database lookups. Assuming that most reverse geocoding requests are near something interesting like a building or a street, you'd want to start with querying those as you might get away with a single query.

The current algorithm has problems and improving it is on the todo list. A few thoughts are collected already in #512. And there are some other tickets tagged 'Reverse'. Closing here in favour of #512. If you like to get involved please continue the discussion there.
