### ISSUE TITLE
How to update Nominatim?

### ISSUE THREAD

**Issue by bubnenkoff** [openstreetmap/Nominatim#709]
I read a lot, but still can't understand is Nomanatim enough for updating itself? 
I read that exists some external tools like `osmupdate`, but if I will compile Nomanatim and will run `update.php --import-osmosis-all` would it enough to updating OSM? Or should I do some other manipulations?

And what about clipping territory? If I need to Clip Europe what should I do?

**Comment by lonvia** [comment]
Yes, that's enough. You need to install the osmosis tool and have an internet connection on your machine. Then `--import-osmosis-all` constantly downloads the newest data from the OSM server and updates the database.

If you want to keep an excerpt like Europe up to date, I recommend using the data diffs from http://download.geofabrik.de/. Note that these are only published daily. There is an example in docs/Import_and_update.md how to configure your system to use them.
