### ISSUE TITLE
Severe Error while trying to update data

### ISSUE THREAD

**Issue by maxze** [openstreetmap/Nominatim#710]
I have Nominatim running inside a Docker container, but the problem I'm having seems to be with Nominatim itself instead of the container. When I run

`./utils/update.php --import-osmosis-all --no-npi`

the output given is this:

> 
> 2017-04-28 06:34:17 Replication Delay is 691201
> /usr/bin/osmosis --read-replication-interval workingDirectory=/app/nominatim/settings --simplify-change --write-xml-change /app/git/data/osmosischange.osc
> Apr 28, 2017 6:34:17 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Osmosis Version 0.40.1
> Apr 28, 2017 6:34:18 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Preparing pipeline.
> Apr 28, 2017 6:34:18 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Launching pipeline execution.
> Apr 28, 2017 6:34:18 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Pipeline executing, waiting for completion.
> Apr 28, 2017 6:34:25 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
> SEVERE: Thread for task 1-read-replication-interval failed
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to open file for writing.
>         at org.openstreetmap.osmosis.xml.common.BaseXmlWriter.initialize(BaseXmlWriter.java:142)
>         at org.openstreetmap.osmosis.xml.v0_6.XmlChangeWriter.process(XmlChangeWriter.java:42)
>         at org.openstreetmap.osmosis.set.v0_6.impl.ChangeSimplifierImpl.flushCurrentChanges(ChangeSimplifierImpl.java:59)
>         at org.openstreetmap.osmosis.set.v0_6.impl.ChangeSimplifierImpl.process(ChangeSimplifierImpl.java:78)
>         at org.openstreetmap.osmosis.core.sort.v0_6.SortedHistoryChangePipeValidator.process(SortedHistoryChangePipeValidator.java:62)
>         at org.openstreetmap.osmosis.set.v0_6.ChangeSimplifier.process(ChangeSimplifier.java:39)
>         at org.openstreetmap.osmosis.core.sort.v0_6.ChangeSorter.complete(ChangeSorter.java:64)
>         at org.openstreetmap.osmosis.replication.v0_6.ReplicationDownloader.processComplete(ReplicationDownloader.java:93)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:288)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:349)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.FileNotFoundException: /app/git/data/osmosischange.osc (Permission denied)
>         at java.io.FileOutputStream.open(Native Method)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
>         at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
>         at org.openstreetmap.osmosis.xml.common.BaseXmlWriter.initialize(BaseXmlWriter.java:129)
>         ... 10 more
> 
> Apr 28, 2017 6:34:25 AM org.openstreetmap.osmosis.core.Osmosis main
> SEVERE: Execution aborted.
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
>         at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
>         at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
>         at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:606)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:328)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:408)
>         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:351)
>         at org.codehaus.classworlds.Launcher.main(Launcher.java:31)
> 
> Error: 1

Aside from the updating process everything works fine.

**Comment by mtmail** [comment]
The important line seems to be
```
Caused by: java.io.FileNotFoundException: /app/git/data/osmosischange.osc (Permission denied)
```
Can you change the directory permissions?

**Comment by maxze** [comment]
I tried to change the file permissions using "sudo -u root chmod -R o+rw /app/git/data/osmosischange.osc"

and got:

chmod: cannot access '/app/git/data/osmosischange.osc': No such file or directory

I can change the permissions on the "data" folder, but the file in question doesn't seem to be there.

**Comment by mtmail** [comment]
The first line of the error says osmosis wants to write the file and that fails. You need to change the permissions of the directory so the file can be created.

**Comment by maxze** [comment]
Weird, that was the first thing I did and the error kept showing up. I did it again now and it _seems_ to work, but I'll report back again after the update is completed. Thank you, mtmail. 👍 :)
