### ISSUE TITLE
Accidentally cancelled process (database already exists (pgsql://@/nominatim))

### ISSUE THREAD

**Issue by tanzeelrana** [openstreetmap/Nominatim#712]
I accidentally cancelled the process. Here are a few last lines of the process: 

` Done 1488793 in 19931 @ 74.697357 per second - Rank 30 ETA (seconds): 37221.117188
  Done 1488803 in 19932 @ 74.694107 per second - Rank 30 ETA (seconds): 37222.601562
  Done 1488811 in 19932 @ 74.694511 per second - Rank 30 ETA (seconds): 37222.292969
  Done 1488823 in 19933 @ 74.691368 per second - Rank 30 ETA (seconds): 37223.699219
  Done 1488836 in 19933 @ 74.692017 per second - Rank 30 ETA (seconds): 37223.203125
  Done 1488848 in 19934 @ 74.688873 per second - Rank 30 ETA (seconds): 37224.609375
  Done 1488860 in 19935 @ 74.685730 per second - Rank 30 ETA (seconds): 37226.011719
  Done 1488899 in 19935 @ 74.687683 per second - Rank 30 ETA (seconds): 37224.519531
  Done 1488944 in 19936 @ 74.686195 per second - Rank 30 ETA (seconds): 37224.656250
  Done 1488999 in 19936 @ 74.688957 per second - Rank 30 ETA (seconds): 37222.542969
  Done 1489057 in 19937 @ 74.688118 per second - Rank 30 ETA (seconds): 37222.187500
  Done 1489109 in 19937 @ 74.690727 per second - Rank 30 ETA (seconds): 37220.187500
  Done 1489151 in 19938 @ 74.689087 per second - Rank 30 ETA (seconds): 37220.445312
  Done 1489196 in 19938 @ 74.691345 per second - Rank 30 ETA (seconds): 37218.714844
  Done 1489248 in 19939 @ 74.690208 per second - Rank 30 ETA (seconds): 37218.585938
  Done 1489304 in 19939 @ 74.693016 per second - Rank 30 ETA (seconds): 37216.437500
  Done 1489362 in 19940 @ 74.692177 per second - Rank 30 ETA (seconds): 37216.078125
  Done 1489379 in 19940 @ 74.693031 per second - Rank 30 ETA (seconds): 37215.425781
  Done 1489409 in 19941 @ 74.690788 per second - Rank 30 ETA (seconds): 37216.140625
  Done 1489457 in 19942 @ 74.689453 per second - Rank 30 ETA (seconds): 37216.164062
  Done 1489502 in 19942 @ 74.691704 per second - Rank 30 ETA (seconds): 37214.441406
  Done 1489534 in 19943 @ 74.689568 per second - Rank 30 ETA (seconds): 37215.078125
  Done 1489585 in 19943 @ 74.692123 per second - Rank 30 ETA (seconds): 37213.121094
  Done 1489639 in 19944 @ 74.691086 per second - Rank 30 ETA (seconds): 37212.914062
  Done 1489684 in 19944 @ 74.693344 per second - Rank 30 ETA (seconds): 37211.187500
  Done 1489740 in 19945 @ 74.692406 per second - Rank 30 ETA (seconds): 37210.906250
`

`postgres@tanzeel:~/Documents/osrm/Nominatim/build$ ./utils/setup.php --osm-file ../../data/canada-latest.osm.pbf --all 2>&1 | tee setup.log
tee: setup.log: Permission denied
Create DB
ERROR: database already exists (pgsql://@/nominatim)
database already exists (pgsql://@/nominatim)
postgres@tanzeel:~/Documents/osrm/Nominatim/build$ ./utils/update.php --help`

The command I was running : 
`./utils/setup.php --osm-file ../../data/map.osm.pbf --all 2>&1 | tee setup.log`

I ran this yesterday. It has been over 24 hours. Is this normal ?

**Comment by lonvia** [comment]
Read the [FAQ](http://wiki.openstreetmap.org/wiki/Nominatim/Installation/Troubleshooting#I_accidentally_killed_the_import_process_after_it_has_been_running_for_many_hours._Can_it_be_resumed.3F).

**Comment by tanzeelrana** [comment]
@lonvia I follow the instructions from the FAQ but I still get the same error. 

`postgres@tanzeel:~/Documents/osrm/Nominatim/build$ ./utils/setup.php --index --create-search-indices --index-noanalyse --threads 4 --osm-file ../../data/canada-latest.osm.pbf --all 2>&1 | tee`

setup.log tee: setup.log: Permission denied

WARNING: resetting threads to 2

Create DB

ERROR: database already exists (pgsql://@/nominatim)

database already exists (pgsql://@/nominatim)

**Comment by tanzeelrana** [comment]
Nvm, I removed the --all flag and it worked. where can I find the list of flags and details about them ? 
Thanks for the reply again :)
