### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by tanzeelrana** [openstreetmap/Nominatim#713]
I am getting the following error 

[Mon May 01 05:14:10.603775 2017] [:error] [pid 5230] [client ::1:36750] PHP Fatal error:  require_once(): Failed opening required '/home/tanzeel/Documents/osrm/Nominatim/lib/init-website.php' (include_path='.:/usr/share/php') in /home/tanzeel/nominatim/build/website/search.php on line 5

**Comment by lonvia** [comment]
Most likely your `CONST_BasePath` in build/settings/settings.php or build/settings.local.php points to a bad path. I cannot say how that happened. You might want to delete (or move away) your build path and do the build step again. This will not destroy any imports you have already made.

**Comment by tanzeelrana** [comment]
I am not sure I think it had something to do with the user I was logged in, not sure though but I can not reproduce it. If it happens again I am going to document each step. For now gonna close the issue. thanks for the quick reply, Cheers
