### ISSUE TITLE
Nominatim search should find "wikidata" tags (feature request)

### ISSUE THREAD

**Issue by bjohas** [openstreetmap/Nominatim#714]
It would be great if the Nominatim search could find wikidata tags.

Example: this node is tagged with 
http://www.openstreetmap.org/node/4799496476#map=19/39.91500/4.17852
wikidata=Q27956344.

However, the search
http://www.openstreetmap.org/search?query=Q27956344
doesn't return anything.

Thanks!

**Comment by lonvia** [comment]
This is a bit of a special request because search wouldn't be for a name or address but for an OSM object with a specific key and value. Nominatim might not be the right place to do that. Normally you'd do something like that via Overpass API.

**Comment by EdwardBetts** [comment]
Wikidata is becoming a central store of identifiers for the semantic web. 

The schema.org project is considering the use of Wikidata identifiers, see https://www.wikidata.org/wiki/Wikidata:Schema.org

I could imagine somebody looking at the Wikidata page for San José in Costa Rica and wanting to search for it on OSM. San José is ambiguous, there is more than one place with that name. If the user could copy and paste the Wikidata ID (Q3070) into OSM the search is unambiguous.

Nominatim could be changed to index the OSM wikidata tag. The search API can check if the search query is a Q followed by digits, then return the matching result.

**Comment by MrIbrahem** [comment]
you can quarry it in  [](url)http://88.99.164.208/wikidata/ : 
`SELECT ?osmId WHERE {  ?osmId osmt:wikidata wd:Q27956344. } `

**Comment by lonvia** [comment]
What you are asking for is not a search, it is a lookup of OSM data by a key of an external database. That is out of scope for Nominatim. There are other tools which can do that better. Overpass API comes to mind.

**Comment by bjohas** [comment]
I do think it's important to think of this from the users perspective, and tbh I am not quite sure how the whole search setup for OSM works. However, I do know that I sometimes have difficulty finding stuff via OSM, and I do think incorporating the wikidata tag would be helpful...
