### ISSUE TITLE
Limit value restrictions

### ISSUE THREAD

**Issue by heisRichard** [openstreetmap/Nominatim#715]
Hi, I'm trying to establish what the upper numerical value for the query string parameter "limit" is I'm guessing 50 based on my experience so far, can anyone confirm? For example this querywill cap at 50 items despite the request of 100.

http://nominatim.openstreetmap.org/search?q=mcdonald%27s&countrycodes=gb&format=xml&polygon=1&addressdetails=1&limit=100

**Comment by lonvia** [comment]
Yes, there is a hardcoded limit of 50.

**Comment by heisRichard** [comment]
Thank you.

**Comment by heisRichard** [comment]
Thank you for the information.
