### ISSUE TITLE
Query string results accuracy

### ISSUE THREAD

**Issue by heisRichard** [openstreetmap/Nominatim#716]
Hi, 

The following: 
http://nominatim.openstreetmap.org/search?q=gloria+jeans&countrycodes=au&format=html&polygon=1&addressdetails=1&limit=50 

returns approx 30 results where the stores are called Gloria Jeans, if you click more info you do get more results but the name is Gloria Jean's Coffee -- is there a way to write a better query that would catch more of the results and respect the limits applied?

**Comment by lonvia** [comment]
No, the limit is not a maximum, it's more of an upper bound.

**Comment by heisRichard** [comment]
Thank you.
