### ISSUE TITLE
Logic of [] notation in search query

### ISSUE THREAD

**Issue by heisRichard** [openstreetmap/Nominatim#717]
in the following:

http://nominatim.openstreetmap.org/search?q=gloria+jeans+[cafe]&countrycodes=au&format=xml&polygon=1&addressdetails=1&limit=50

I would expect/hope that the addition of [cafe] would limit the results to results that included "gloria jeans" of a type=cafe it instead seems to be getting results including gloria jeans but also other things...

My results have been better excluding [cafe].

I guess a better example might be doing a search for "Costa + [cafe]" with the intent to return "Costa Coffee" without other places such as "Costa Rica"

Is my use of the [] correct. Thanks

**Comment by lonvia** [comment]
There are pub results because 'cafe' maps to amenity=pub in some language. This is a known limitation due to the multi-linugual nature of Nominatim.

I believe you are trying to use the Nominatim API for something that it wasn't made. Nominatim will not give you complete POI lists. You should be using Overpass API for that.

**Comment by heisRichard** [comment]
Thanks for the information... I was genuinely using it for trying to form the correct queries in the first place.

Whilst I accept your point about cafe mapping to pub... how does that relate to Costa Rica.

Also it's worth nothing that when I did use [] it actually starting including other brands, making the general data less accurate.

**Comment by lonvia** [comment]
The [] notation is a bit special in that it searches for POIs of a given type both by name and location. I.e. your query "costa [cafe]" translates to "find cafes named costa and cafes around places named costa". That has historic reasons. The bracket notation predates special phrases which are recommended to use nowadays. However that doesn't cover the "POI named something" not very well either.

There are some good arguments for changing the meaning of the [] notation to mean "restrict results to the given type" which would effectively give you the naming feature you are looking for.

**Comment by lonvia** [comment]
Giving that some more thought, the meaning of "an amenity of the given type near the place named whatever" has some valid use cases as well. Say you want to search for cafes in a certain postcode area. The q= notation simply cannot be used to express the difference between the two with the bracket notation. You have to use the special terms in that case.
