### ISSUE TITLE
Issue on OSM.org not finding a building with a certain address

### ISSUE THREAD

**Issue by hubgitti** [openstreetmap/Nominatim#718]
Hi,

where should my report go, if nominatim on openstreetmap.org does not find a certain building with a certain address?

Hubgitti

**Comment by lonvia** [comment]
This is the right issue tracker.

**Comment by hubgitti** [comment]
Thanks,

it is about the following address:
Edelstauden 9 8081
on the building:
http://www.openstreetmap.org/way/316761916
is not found in nominatim. Just a bridge and a road segment is found.

Is there any explanation for that, is this a bug in nominatim?

See also the discussion in the Austrian forum:
https://forum.openstreetmap.org/viewtopic.php?id=53532

and the German forum:
https://forum.openstreetmap.org/viewtopic.php?id=58232

Hubgitti

**Comment by lonvia** [comment]
Nominatim always needs an actual place node for addresses with addr:place. This is deliberate, consider it a kind of sanity check. So for your example a place node named 'Edelstauden' is needed. It exists [here](http://www.openstreetmap.org/node/240124102) but is so far away that it is not considered anymore by Nominatim. I would recommend for cases like these to enter the place as an area (possibly elevating it to place=village even, I'm not entirely sure what the state is here).

**Comment by hubgitti** [comment]
Hi, thanks for your help!

I took some time to read the nominatim Wiki & FAQ and tried to learn about other things you mentioned:

So I now tried the following address:
Edelstauden 54, 8081
http://www.openstreetmap.org/way/316758105
It is very close to place "Edelstauden", but no hit.

I tried the following address in my hometown (I think the places are tagged wrong there (suburbs are tagged as villages), I'm currently having a discussion with the local group (Stammtisch Obersteiermark) to fix that)
Turmgasse 32, 8700
An isolated dwelling (http://www.openstreetmap.org/node/2432290366) is on the list, the suburb, which is much closer and more relevant; but wrongly tagged as village) Goess is not.

Thanks for taking the time, it is a very interesting topic for me, but the whole topic (not only nominatim but also places and administrative relations) are quite hard to understand for me.

Lg, Hubgitti

**Comment by lonvia** [comment]
So place=locality are actually not accepted as base for an address because they are meant to be 'unpopulated'. Try changing Edelstauden to place=hamlet or place=village.

**Comment by hubgitti** [comment]
Thanks for your reply, I updated the Austrian and German forum. Your solution is fine for me, I personally also just like the idea of  using "place=locality" for scattered buildings like the situation we have in "Edelstauden".  "place=village" or  "place=hamlet" sounds like a place which is more compact or distinct to me. Could we wait few days to close this thread or continue the discussion depending on the outcome in the forums?
