### ISSUE TITLE
How Nominatim calculate distance to territory?

### ISSUE THREAD

**Issue by bubnenkoff** [openstreetmap/Nominatim#720]
I need way to extract boundaries of the cities like:
![1231](https://cloud.githubusercontent.com/assets/6514326/25948617/ff6ba03c-365c-11e7-8bc5-9fc4ad9e37f5.png)

I know that nominatim can calculate distance to city/village/etc. So it can calculate object boundaries. But how it's do it?

**Comment by mtmail** [comment]
Nominatim either knows the (exact) boundaries from OpenStreetMap relations, example http://nominatim.openstreetmap.org/search.php?q=goereme&polygon_geojson=1
or knows only the center point, example
http://nominatim.openstreetmap.org/search.php?q=urgup&polygon_geojson=1

Nominatim doesn't generate/calculate boundaries. With center point only the search logic simply (and there's many cases where this approach can fail) looks for closest distance.
