### ISSUE TITLE
{q=} doesn't find a nominatim returned result

### ISSUE THREAD

**Issue by arungowtham** [openstreetmap/Nominatim#721]
Hi,

http://nominatim.openstreetmap.org/search?format=json&limit=1&q=Bucket%20Building

This responds with: display_name":"Bucket Building, Zoho Corporation, Grand Southern Trunk Road, Guduvancheri, Potheri, Kanchipuram district, Tamil Nadu, 603202, India"

Now when i try to search Nominatim for this complete address, it returns empty response.

http://nominatim.openstreetmap.org/search?format=json&limit=1&q=Bucket%20Building,%20Zoho%20Corporation,%20Grand%20Southern%20Trunk%20Road,%20Guduvancheri,%20Potheri,%20Kanchipuram%20district,%20Tamil%20Nadu,%20603202,%20India

What am i missing here.. How could i geocode that complete address ?

Thanks in advance for any help!

**Comment by lonvia** [comment]
The name contains a comma which Nominatim cannot handle. For more information see #698.
