### ISSUE TITLE
Is it's possible to cut zone of interest during loading/updating data in Nominatim?

### ISSUE THREAD

**Issue by bubnenkoff** [openstreetmap/Nominatim#723]
I need to load in DB OSM data for several countries  and be able automatically update them.

The updating solution is based on:
`./utils/update.php --import-osmosis-all --no-npi` and it's seems working. But problem that in configure.txt I can set source only for big region like Europe or particular country. But what I should to do if I need to load for example 3 different country and be able to update them?

I read that the are few cutting utils, but I can't understand how to use them inside updating procedure.

**Comment by lonvia** [comment]
Given that this is a regular question, I have added a FAQ entry:

https://github.com/openstreetmap/Nominatim/blob/master/docs/Faq.md#can-i-import-only-a-few-countries-and-also-keep-them-up-to-date
