### ISSUE TITLE
Incorrect address location due to transformed coordinates

### ISSUE THREAD

**Issue by juanmaneo** [openstreetmap/Nominatim#729]
I have incorrect address/location in OSM :

I enter coordinate 47.7869164517,8.5678526759 in Germany near frontier.

http://nominatim.openstreetmap.org/search.php?q=47.7869164517%2C8.5678526759&polygon_geojson=1&viewbox=

But the coordinate are transformed to 47.7921077,8.571674 so it gives me Switzerland instead of Germany.

http://nominatim.openstreetmap.org/details.php?place_id=127336933

see:

https://www.google.fr/maps/place/47%C2%B047'12.9%22N+8%C2%B034'04.3%22E/@47.7859794,8.5638938,16z/data=!4m5!3m4!1s0x0:0x0!8m2!3d47.7869165!4d8.5678527?hl=en

https://yandex.fr/maps/?mode=search&text=47.7869164517%2C8.5678526759&sll=2.341198%2C48.856929&sspn=0.494728%2C0.191657

**Comment by lonvia** [comment]
The result is expected. Nominatim does not give you the location information about the exact point you asked but returns you the closest object it has in its database. In this case it is the named path across the border. The unnamed paths next to the point are not saved in the database.

**Comment by juanmaneo** [comment]
@lonvia Thanks. I installed a local Nominatim. Can you direct me to "standard" way of completing Nominatim database (for points that are of interrest for me) in documentation ?
