### ISSUE TITLE
A question of Nominatim data update.

### ISSUE THREAD

**Issue by wangbingqian110** [openstreetmap/Nominatim#731]
I have completed the import of global data, and then I want to update the Nominatim data.I am using the default configuration file, I want to know how long it takes to complete the update work?
    Moreover, the URL in the configuration file is filled with "day" or "minute" or "hour", what is the difference between them?

**Comment by lonvia** [comment]
Updates can run forever to keep you up-to-date with the latest OSM data.

'day', 'minute', 'hour' refer to different sources of update data with different update frequencies. If you want to run updates continuously use 'minute', if you want to catch up once a day, use 'hour'.

**Comment by wangbingqian110** [comment]
@lonvia Thank you very much for giving me the answer. Can I update the Nominatim directly to replace the process of importing global data?

**Comment by lonvia** [comment]
No, you'd need to catch up on 10 years worth of data. Import a current planet and then use update to keep it up to date.

**Comment by wangbingqian110** [comment]
Okay, I understand, thank you very much for your answer.
