### ISSUE TITLE
amenity=gym deprecated, should be fitness_centre

### ISSUE THREAD

**Issue by coffeepotprotocol** [openstreetmap/Nominatim#732]
Taginfo
amenity=gym 1 024
leisure=fitness_centre 11 456
See
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dgym_(Don%27t_use)

**Comment by lonvia** [comment]
Objects with both tags are found by Nominatim. What exactly is the problem you want to report?

**Comment by coffeepotprotocol** [comment]
Oops, just checked this page, now I saw it's been updated the last time in 2015 :
http://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases

**Comment by coffeepotprotocol** [comment]
Was for this purpose :
https://bugs.launchpad.net/unav/+bug/1693326

**Comment by lonvia** [comment]
Please stop escalating unav tagging issues here. These have nothing to do with Nominatim. If unav chooses to implement its POI search against Nominatim (and I have repeatedly stated that this is not a good idea in general, search this issue tracker for similar issue) then it has to live with the known restrictions.
