### ISSUE TITLE
Import process is slow

### ISSUE THREAD

**Issue by Muneer94** [openstreetmap/Nominatim#733]
We are running reimport of osm data which is taking too long, this didn't happen before as it would take 2 days to finish the import process. We have tested by importing small extract before importing whole planet data it is fast for the small extract(`Luxembourg`). It has been 3 days and the import process still running currently it is at `Rank 16`. We are running this import on the same server we used before it's configuration is 64GB Ram with 8 cores and 1.5TB SSD.

**Comment by lonvia** [comment]
Find out what exactly has changed between the imports, that might give a clue.

**Comment by gopi-ar** [comment]
@lonvia what @Muneer94 means is that in terms of hardware used for import, it's the same as before, however imports are _much_ longer; this means either newer types of indexes that are causing hold-ups in `rank 16` or large addition of data since our last re-import a couple of months ago.

What would be the best way to verify this?

**Comment by lonvia** [comment]
Closing because reporter did not supply the requested information.

**Comment by lonvia** [comment]
I've just started a new planet import using the latest version from master on a machine with 32GB RAM and SSDs and after 12 hours it is already at the indexing step at rank 20. The problem must be somewhere in the software configuration of your machines. A common mistake is a bad postgres configuration when you switched versions and forget to customize the new one.

**Comment by Muneer94** [comment]
@lonvia We were running Nominatim on `PostgreSQL 9.6.1` and `PostGIS 2.3` after we encountered slow indexing speed (2/sec) during full planet import. We have tried running the import without wiki data but no luck. 

At last we have tested the import by downgrading the `PostgreSQL` to `9.5.7` (`PostGIS` at `2.3`) and it indexed at the rate of ~1000/sec and the whole process took ~2 days along with wiki data. I think the indexing speed is slow on PostgreSQL >= 9.6.1. #741 has fixed indexing at `Rank-16` but not after that.

Thanks for your help!

**Comment by lonvia** [comment]
Which version of Nominatim is this on (use `git rev-parse HEAD` to get the commit id)?

**Comment by Muneer94** [comment]
We are running Nominatim on 896421fe9f8dd9d49291417fe3d9389d71d967ca commit ID.

**Comment by lonvia** [comment]
Is that the version you started the import with or did you update to this version after you experienced the slowness? Note that the revert in b9cc47ee675a3ab9a4e2ff7e6bdaac7829fa5031 (which actually deals with the issue) actually requires you to restart the import from scratch. It won't have an effect otherwise.

**Comment by Muneer94** [comment]
Yes, we have started the import with the same version after the revert.

**Comment by lonvia** [comment]
To find the slow running query:

 - get the latest commit from master,
 - run the import up until where it becomes slow (if you have an import already running using that with an updated Nominatim is fine)
 - stop the import, then continue with `./utils/setup.php --create-functions --enable-debug-statements --index --threads 1 --index-noanalyse`
 - there will be a lot of debug output now, let it run for a couple of places until you find one that is obviously slow
 - either provide the output where you see the debug output hang for a bit and/or provide the postgresql log file part with a complete run of the place_update() trigger on a slow place
