### ISSUE TITLE
Unexpected Server Error from Odd Input

### ISSUE THREAD

**Issue by cjgibson** [openstreetmap/Nominatim#735]
The search query [q=KS, United States United States of America](https://nominatim.openstreetmap.org/search.php?q=KS,%20United%20States%20United%20States%20of%20America) appears to consistently result in a SQL query that times out prior to completion. I've attached the full log reported by the service here:
 [kansas_united_states_timeout.txt](https://github.com/openstreetmap/Nominatim/files/1029588/kansas_united_states_timeout.txt).

**Comment by lonvia** [comment]
I've observed those long queries on the osm.org instance as well. Thanks for finding an example query. This is a POI search in all of the US which really shouldn't be done for efficiency reasons (and not even what was intended). I'm looking into it.

**Comment by cjgibson** [comment]
@lonvia, thank you so much for the quick response and patch -- my local fix was to dedupe the input prior to attempting to geocode it. That is, `KS, United States United States of America` was reduced to `KS, United States of America`. Not sure if that helps in determining why this would have been considered a POI query, but it appears to "fix" this edge case.

**Comment by lonvia** [comment]
The POI query was an odd match of 'KS' against the normalized form of hotel in some Asian language. #742 has put a stop to those false matches.

You still might want to dedupe your queries as Nominatim does generally not do that. `KS, United States United States of America` does not return any results because of that.

**Comment by cjgibson** [comment]
Good to know: I currently have a (short) series of pre-processing functions that are applied to a query string before they hit Nominatim, I'll leave this one in place.
