### ISSUE TITLE
Enable HTTPS for nominatim.org

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/Nominatim#737]

**Comment by peslis** [comment]
+1 i have opened a ticket too . Nothing has been done yet. If you dont provide a source for the data with https  we cant get it to work on big projects

**Comment by mtmail** [comment]
@peslis I don't understand. Your organization doesn't allow you to download data files from http://nominatim.org/ unless https is enabled?

**Comment by peslis** [comment]
yes correct and i believe any organization with https wouldnt allow it

**Comment by lonvia** [comment]
@peslis nominatim.org is in no way related to nominatim.openstreetmap.org which you are trying to use. This ticket is only relevant for people who want to download additional data for their own installation of nominatim.

Also, before using nominatim.openstreetmap.org on big projects, please have a look at our [usage policy](https://operations.osmfoundation.org/policies/nominatim/).

**Comment by calimeroteknik** [comment]
Is anything blocking this?

SQL files downloaded via HTTP (e.g. country_grid.sql.gz) will be run as superuser on a postgres server.
Any MitM on the HTTP would therefore be granted arbitrary code execution with the same privileges as the server instance, which is what I was implying in https://github.com/openstreetmap/Nominatim/commit/e7c8b498d18129e3d31498136237a3edc20da486

Cheers, and a happy new year
