### ISSUE TITLE
Polygon lat/long output swapped?

### ISSUE THREAD

**Issue by drspangle** [openstreetmap/Nominatim#740]
I've been using leaflet-control-geocoder's Nominatim provider plugin to query the service, and retrieve the outlines of locations using polygon_geojson=1 with JSON output. These are rendered to a map. At first I thought that the results I was getting back were in some kind of weird projection, but it turns out that the coordinates have their latitude and longitude swapped.

For example: [Carnegie Mellon University](http://nominatim.openstreetmap.org/search?q=carnegie%20mellon%20university&format=jsonv2&polygon_geojson=1&addressdetails=1)

Note that the output says:
`"lat":"37.4102193","lon":"-122.059654765858"`
This is obviously correct, and we can verify this using another map provider:
[such as google maps](https://www.google.com/search?q=carnegie+mellon+university+silicon+valley&ie=utf-8&oe=utf-8#q=carnegie+mellon+university+silicon+valley+coordinates)

Now we look at the geojson field later in the output:
`"geojson":{"type":"Polygon","coordinates":[[[-122.0604981,37.4102704],[-122.060482,37.4103684],[-122.0603962,37.4104536], <snip>`

Is the reversed output supposed to be the intended behavior? For what purpose? When serialized this way, I'm forced to write a wrapper for the output which reverses the coordinates, but this is a difficult task if I want to support more than just Polygon or PolyLine output types. Seems to me that this should be consistent.

PS: It's a bit odd that the Silicon Valley campus shows up as the first search result for Carnegie Mellon University, as opposed to the main campus. Any ideas why this might be - maybe it's further west? The name is longer? Very strange.

**Comment by drspangle** [comment]
I've found out that the GeoJSON spec actually wants the lat/long to be reversed, so this issue doesn't really exist. Probably best to delete this.

For those that were confused like me, there's already methods in leaflet to convert between GeoJSON "coordinates" and proper LatLongs.

**Comment by mtmail** [comment]
Here's an overview which tools require which coordinate format. Yes, it's confusing https://macwright.org/lonlat/

You can copy&paste the following into http://geojson.io/ to view the expected outline for debugging
```
 {
    "type": "Polygon",
    "coordinates": [
        [
            [
                -122.0604981,
                37.4102704
            ],
            [
                -122.060482,
                37.4103684
            ],
            [
                -122.0603962,
                37.4104536
            ],
            [
                -122.0590873,
                37.4108755
            ],
            [
                -122.0588083,
                37.4102662
            ],
            [
                -122.0589746,
                37.4100361
            ],
            [
                -122.0586903,
                37.4098742
            ],
            [
                -122.0589424,
                37.4095588
            ],
            [
                -122.0592128,
                37.4095515
            ],
            [
                -122.0597954,
                37.4097548
            ],
            [
                -122.0600743,
                37.4098997
            ],
            [
                -122.0603586,
                37.4100829
            ],
            [
                -122.0604391,
                37.4101724
            ],
            [
                -122.0604981,
                37.4102704
            ]
        ]
      ]
    }
```
