### ISSUE TITLE
Slow place_id

### ISSUE THREAD

**Issue by merlinnot** [openstreetmap/Nominatim#741]
Indexing ranks 1-25 throw an enormous number of "slow place_id" messages. Indexing rank 26 takes half of the time as indexing rank 16, which makes no sense to me.

I'm building Nominatim as a Docker [image](https://github.com/9e15/nominatim-docker) using pretty decent hardware:
- 64-core Intel Haswell
- 240 GB RAM
- 4x NVME drives in RAID0

How can I check why the performance on lower ranks is so bad?

**Comment by mtmail** [comment]
I can't see anything obvious with the docker templates. The various postgres optimizations for the import (e.g. fsync=off) are in place, you're importing "only" Europe (1/3 of the size of the full planet in Openstreetmap) and with that hardware, 61 import threads, 120GB osm2psql cache it shouldn't be slow.

I'd guestimate the full import takes 24 hours with rank 30 being the slowest (number of places is just that much higher in rank 30).

Random thought is that 61 import threads might overload the database. Not the number of postgres connections, but simply all writing to the same tables. But first I'd check syslog and postgres logfiles for warnings and anything else that could slow down disc I/O.

P.S. can you add a license file to the docker github repository? It's really great work you've done there and even better that you made it public but it's unclear if others are allowed to reuse it.

**Comment by lonvia** [comment]
`autovacuum=off` is not a good idea. See if removing it improves the import times. Also, I see that you have extended logging enabled. How much data does that produce? That might be interfering.

Are you on some cloud service or on a real machine?

**Comment by lonvia** [comment]
So I was able to reproduce the issue with a postgres 9.6 from the original Postgres repos, this seems to be the only postgres version affected. There is a very odd problem with "char" type against char(1) which prevents the indexes from being used. I just pushed a fix. See if that solves the problem for you. If not, then please reopen.

**Comment by merlinnot** [comment]
@mtmail I've added license file, readme and mage huge improvements to overall process. Works like a charm now :) Disk IO is ridiculous with these disks in RAID0, write speed tops at 3GB/s, IOPS is very high too.

@lonvia Thanks for the tips with `autovacuum`, logging and for the fix, works really nice! I was using virtual machine with local disks, so I doubt it could have make some difference.

**Comment by lonvia** [comment]
The fix I committed wasn't enough. I've now completely reverted the use of the "char" type.

**Comment by merlinnot** [comment]
After the fix, the issue seemed to be resolved, but I wasn't importing such big datasets as before. I'll probably build an image for the entire planet in the next month, I'll get back to this issue if it will occur again.
