### ISSUE TITLE
wrong adress of Vingesbackevägen

### ISSUE THREAD

**Issue by qvarsell** [openstreetmap/Nominatim#744]
When searching for "Vingesbackevägen", it is not found. But if I search for "Vingesbackavägen" i find the road.

The street has the wrong name in your database.

The name of the street is "Vingesbackevägen" not "Vingesbackavägen".

Please change it.

Best regards
Mattias Qvarsell

**Comment by lonvia** [comment]
This is an issue with the underlying OpenStreetMap data, not with the search engine. You can fix the name of the street yourself. Please see http://www.openstreetmap.org/fixthemap for more information how to contribute to OpenStreetMap.
