### ISSUE TITLE
calculate-postcodes not working in master

### ISSUE THREAD

**Issue by kkoop** [openstreetmap/Nominatim#746]
The calculate-postcodes step in setup.php does no longer work for me in master. It seems to be related to the moving of address data into the address hstore. Actually I had to change two things to make it work again: 

The insert trigger of placex now expects the postcode to be in the address hstore, but setup.php passes it in the postcode column:
placex_insert trigger:
```
IF NEW.class in ('place','boundary') AND NEW.type in ('postcode','postal_code') THEN

        IF NEW.address IS NULL OR NOT NEW.address ? 'postcode' THEN
            -- most likely just a part of a multipolygon postcode boundary, throw it away
            RETURN NULL;
        END IF;
```
setup.php:
```
    $sSQL = "insert into placex (osm_type,osm_id,class,type,postcode,country_code,geometry) ";
   ...
```
After changing this to something along `insert ... address ... select ... hstore('postcode',postcode)` there were now calculated postcodes in placex, but still not as many as in the stable release 2.5.1 version. 

It seems most places have the postcode now in the address hstore, with the postcode column being empty (at least at this point in the import process). After changing the INSERT statement in setup.php to use `address->'postcode'` instead of `postcode` when calculating the postcode centerpoint, it seems to work now the same as in 2.5.1. 

My INSERT statement in setup.php now looks like this:
```
    $sSQL = "insert into placex (osm_type,osm_id,class,type,postcode,address,country_code,geometry) ";
    $sSQL .= "select 'P',nextval('seq_postcodes'),'place','postcode',poco,hstore('postcode',poco),country_code,";
    $sSQL .= "ST_SetSRID(ST_Point(x,y),4326) as geometry from (select country_code,address->'postcode' as poco,";
    $sSQL .= "avg(st_x(st_centroid(geometry))) as x,avg(st_y(st_centroid(geometry))) as y ";
    $sSQL .= "from placex where address?'postcode' group by country_code,poco) as x ";
    $sSQL .= "where ST_Point(x,y) is not null";

```

**Comment by lonvia** [comment]
Thanks for catching this. I've added a slightly modified variant of your fix and also fixed the import of additional US postcodes.

For those who already have a database without postcodes, it is safe to apply the code update and then run `./utils/setup.php --calculate-postcodes --index-noanalyse --index`. This will make postcodes searchable again. If you need the additional postcodes in addresses, a reimport is necessary (or just let things sort themselves out with time through updates).

**Comment by andrew-aladev** [comment]
@lonvia  You've missed `postcode` with `address` and commited it into the master branch. So we have no tests. Existing tests is just a joke. Please consider to add tests in future releases. Thank you.

**Comment by andrew-aladev** [comment]
We need to `./utils/setup.php --create-functions --calculate-postcodes` and than reindex.
