### ISSUE TITLE
Class 'Transliterator' not found

### ISSUE THREAD

**Issue by pedox** [openstreetmap/Nominatim#747]
Hi there i have something problem near here

```
PHP Fatal error:  Uncaught Error: Class 'Transliterator' not found in /srv/nominatim/Nominatim/lib/Geocode.php:922\nStack trace:\n#0 
/srv/nominatim/Nominatim/build/website/search.php(94): Nominatim\\Geocode->lookup()\n#1 
{main}\n  thrown in /srv/nominatim/Nominatim/lib/Geocode.php on line 922, 
referer: http://localhost/nominatim/search.php

```

it happen when im build this from master branch today.

any suggestion ?

**Comment by lonvia** [comment]
PHP intl extension is required since #742. Install the package `php-intl` and restart Apache.

**Comment by pedox** [comment]
Thanks mate, it's works 👍

**Comment by vorlost69** [comment]
Great man, i was getting nervous because i couldn't get it to work either.
apt-get install -y php-intl did it.
thank you :)

**Comment by mtmail** [comment]
(Sarah is a woman's name.)

**Comment by vorlost69** [comment]
ooh bummer excuse me :)

**Comment by fokerone** [comment]
Dear i have install php-intl but i have the same error in apache2 error log  :

 PHP Fatal error:  Uncaught Error: Class 'Transliterator' not found in /srv/nominatim/Nominatim-3.1.0/lib/Geocode.php:53\nStack trace:\n#0 /srv/nominatim/Nominatim-3.1.0/build/website/search.php(14): Nominatim\\Geocode->__construct(Object(DB_pgsql))\n#1 {main}\n  thrown in /srv/nominatim/Nominatim-3.1.0/lib/Geocode.php on line 53

any suggestion ?

**Comment by mtmail** [comment]
Try restarting the webserver (`service apache2 restart` on Ubuntu for example). If that doesn't solve it please open a new github issue (because this one got closed last year).

**Comment by Rajavelu** [comment]
Hi,
I am getting the same error, after installed php-intl too. 
I am using nginx server in centos7.

Thanks in advance for any help.
