### ISSUE TITLE
Certain values leading to an error with Geocoding

### ISSUE THREAD

**Issue by leafbomb** [openstreetmap/Nominatim#748]
Passing certain values do not return a latitude and longitude such as `Europe, Warsaw` which leads to an error however `Europe, London` works fine.

**Comment by lonvia** [comment]
Europe (the continent) is not really included in the OpenStreetMap data, so it is to be expected that there are no result when it is included in the query. I don't see any errors though, there is just a list with zero entries returned which is Nominatim's standard behavior when no results are found.
