### ISSUE TITLE
Error executing ./utils/specialphrases.php

### ISSUE THREAD

**Issue by khamooshi** [openstreetmap/Nominatim#749]
When I execute this line:
./utils/specialphrases.php --wiki-import > specialphrases.sql

I get the following error:
PHP Fatal error: Class 'Transliterator' not found in /path/Nominatim/build/utils/specialphrases.php on line 22

It used to work few days ago!

**Comment by khamooshi** [comment]
Scripts in docs/ folder needs to be updated with php-intl

**Comment by lonvia** [comment]
Duplicate of #747.
