### ISSUE TITLE
No postal code in results for Reverse Geo Lookup

### ISSUE THREAD

**Issue by ka4ok85** [openstreetmap/Nominatim#751]
For certain Latitudes and Longtitudes there is no Postal Code in result data set. E.g. http://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&lat=47.612625&lon=-122.34128

Is this issue related to #746 or does that work as designed?

p.s. I use http://nominatim.openstreetmap.org/ specifically, not local data copy.

Thanks

**Comment by lonvia** [comment]
This is related to #746 as well. Closing here in favour of #750, which tracks progress on how to get back the postcodes into nominatim.openstreetmap.org.
