### ISSUE TITLE
Search for country by ISO code doesn't work for certain codes

### ISSUE THREAD

**Issue by asgathea** [openstreetmap/Nominatim#754]
Hi,

in a project I'm contributing to, country information is requested the following way: https://nominatim.openstreetmap.org/search?format=json&q=de&addressdetails=1&featuretype=country

This works for most countries, but the query returns an empty array for certain ISO3166-1:alpha2 codes, for example for IL (Israel): https://nominatim.openstreetmap.org/search?format=json&q=il&addressdetails=1&featuretype=country

`[ ]`

I also found this to be the case for ET (Ethiopia), LA (Laos) and PH (Philippines). However, information is properly returned when using the country's name like https://nominatim.openstreetmap.org/search?format=json&q=israel&addressdetails=1&featuretype=country

`[
{
place_id: "172466171",
licence: "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
osm_type: "relation",
osm_id: "1473946",
boundingbox: [
"29.4533796",
"33.3356317",
"34.2674994",
"35.8950234"
],
lat: "30.8760272",
lon: "35.0015196",
display_name: "Israel",
class: "boundary",
type: "administrative",
importance: 0.92108248804556,
icon: "https://nominatim.openstreetmap.org/images/mapicons/poi_boundary_administrative.p.20.png",
address: {
country: "Israel",
country_code: "il"
}
}
]`

Then I researched if the ISO3166-1:alpha2 code was missing in the Israel relation, but it is present: http://www.openstreetmap.org/relation/1473946#map=8/31.415/35.081

Any idea what's wrong here?

**Comment by lonvia** [comment]
These country codes are all stop words in Nominatim and therefore get deleted. So with the current design it is impossible to look them up.

NB: isn't it a little bit of overkill to use an external server to look up country codes? Wouldn't a simple text file do?

**Comment by asgathea** [comment]
We are not only looking up the country codes, we also need the bounding box data. However, using the country names in the cases mentioned above seems to be a proper workaround for us.

Thank you for your explanation!
