### ISSUE TITLE
Not all data gets updated

### ISSUE THREAD

**Issue by anthologist** [openstreetmap/Nominatim#755]
I initially imported a merge between Germany+Argentina from geofabrik, and I need to get the maps daily updated with the script at issue #60 .
The script works, the logs show that a lot is running and everything seems fine, but in the last week the "Data last updated:" string on the top of Nominatim page stopped at 2017/06/11 . I checked some random cities and looks like some are updated, some are not (they look stacked at May 31th).
Why is this happening? Is there a way to fix without rebuilding the database from scratch?
Edit: btw, some of the cities date is 2017/06/14, so after the "Data last updated:" string.

**Comment by lonvia** [comment]
It is quite normal that not all data in the database shows the latest date as only the places that have actual changes will be updated.

As for the 'Data last updated: ' string, the `--import-diff` command does not update the overall database date. Add the following command to your update script to set the date yourself from the diffs you are importing with the following command:

    echo "UPDATE import_status SET lastimportdate = '" `./utils/osm_file_date.py <diff-file.osc>` "'" | psql -d nominatim

**Comment by anthologist** [comment]
But the data from Openstreet shows a more recent date than mine. Example:
as of today Rome from nominatim.openstreetmap.org 2017-06-17
Rome from my server (updated today)                          2017-06-15

I get the data from geofabrik, they offer daily updates. Does this mean geofabrik data is not really updated to the last one?
Btw I don't have the osm_file_date.py script.

**Comment by lonvia** [comment]
I wouldn't expect Rome to be in a Germany+Argentinia extract at all.

> Btw I don't have the osm_file_date.py script.

Please state which version of Nominatim you are running.

**Comment by anthologist** [comment]
I changed my map data and it now includes also Italy... sorry for the confusion. My question is still the same.

> Please state which version of Nominatim you are running.
Version 2.5, installed reading this https://github.com/openstreetmap/Nominatim/blob/master/docs/install-on-ubuntu-16.md

**Comment by mtmail** [comment]
Jumping in because I know lonvia will ask the same question.

The instructions on that page say `git clone --recursive git://github.com/openstreetmap/Nominatim.git`, so it wasn't any of the stable versions (http://www.nominatim.org/).

Can you run `git log` to see which exact commit got cloned?

**Comment by anthologist** [comment]
Oops you're right, sorry.

commit d023578f9062d9a4c9ab7b677f2dcf3883629ab5
Author: Sarah Hoffmann <lonvia@denofr.de>
Date:   Sat May 27 17:47:39 2017 +0200

**Comment by lonvia** [comment]
So the difference in Rome is due to some changes in the code your version of Nominatim does not have yet (5a5691b5b76a02615ed08f4912f219034f589feb to be precise). I really wouldn't worry about it too much. The difference between your setup and the setup on nominatim.osm.org will occasionally lead to slightly different data. Your updates are working fine.

Regarding the script, it is probably easiest to just download [the script from the master version](https://github.com/openstreetmap/Nominatim/blob/master/utils/osm_file_date.py) and use that. You need to install pyosmium to use it. As the same user that runs the updates, run:

    pip install --user osmium

(You may need to install `python-pip` first.)

**Comment by anthologist** [comment]
I see, thank for your support. Just one last question, does nominatim.osm.org use the 2.5.1 stable version?
