### ISSUE TITLE
Preserve place_id as "eternal" ID 

### ISSUE THREAD

**Issue by ppKrauss** [openstreetmap/Nominatim#758]
As applications with [google.com/place-id](https://developers.google.com/places/place-id), that  use some idea of "ID preservation warranty" of the API... The Nominatim API at the `nominatim.openstreetmap.org` database instance can preserve serial numbers and its relations with "canonical places", as countries, cities, main rivers, main streets, etc.

Or use an internal control to relate place_id with [Wikidata item ID](https://www.wikidata.org/wiki/Help:Items) of the named place. 

PS: supposing that in nowadays Nominatim has no support to its internal ID preservation.

**Comment by lonvia** [comment]
This rather touches on the generic topic of stable IDs for OpenStreetMap object and is as such outside the scope for Nominatim.
