### ISSUE TITLE
How to get all the states of a country?

### ISSUE THREAD

**Issue by wangbingqian110** [openstreetmap/Nominatim#760]
hello:
I want to get all states of the country by a URL, return json format or xml format, how should I do?

**Comment by lonvia** [comment]
Nominatim is not the right tool for this. Have a look at https://osm.wno-edv-service.de/boundaries/

**Comment by wangbingqian110** [comment]
Hello:
Thank you for your answer. I only want to get the name of the state that belongs to this country. Do you have any way?

**Comment by lonvia** [comment]
No. You need to extract the information from the data from the link above. Or extract the data from Wikipedia or Wikidata or the CIA Fact Book, they should have these hierarchies as well. You can do this once, put it in a file and then read from there as needed. No need to consult a web service.
