### ISSUE TITLE
Search by osm_tag

### ISSUE THREAD

**Issue by Krychool** [openstreetmap/Nominatim#762]
Hello,

I don't know if it is a problem or I don't understand somthing.
I have tried to search electronics shop in my city. I used following URL:

**http://nominatim.openstreetmap.org/search?format=json&q=shop+electronics&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979**

There is no results but when I'm using this url:

**http://nominatim.openstreetmap.org/search?format=json&q=electronics+shop&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979**

I got some results. Similarly I have tried use these URLs:

**http://nominatim.openstreetmap.org/search?format=json&q=shoes+shop&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979**

AND

**http://nominatim.openstreetmap.org/search?format=json&q=shop+shoes&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979**

I have no results. It makes me confused beacuse when I'm looking shoes shop named Deichmann or CCC I'm getting correct results. with class=shop and type=shoes.

**http://nominatim.openstreetmap.org/search?format=json&q=deichmann&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979**

As I said I don't know if this is a problem or I don't understand how search engine works. I hope I can get some helpe here :)

**Comment by mtmail** [comment]
Have a look at the special phrases list.
https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases
https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN

For English (default) `shoe shops` works http://nominatim.openstreetmap.org/search?format=json&q=shoe+shops&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979

To get results in Polish add the `accept-language` parameter
http://nominatim.openstreetmap.org/search?format=json&q=Sklep%20obuwniczys&limit=10&bounded=1&viewbox=18.192614,52.182255,18.332689,52.329979&accept-language=pl

**Comment by Krychool** [comment]
Thanks for your response. I understand everything now.
