### ISSUE TITLE
Strange behavior on <addressparts><county> on some zoom levels

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#764]
Seems the reverse api setting the county element wrong on LDS:
It is correct in the ref attribute
Examples:
http://nominatim.openstreetmap.org/reverse?format=xml&lat=52.0235740&lon=13.8689230&zoom=18&addressdetails=1extratags=1&namedetails=1&accept-language=en
http://nominatim.openstreetmap.org/reverse?format=xml&lat=52.12347175&lon=13.8689230&zoom=18&addressdetails=1extratags=1&namedetails=1&accept-language=en

**Comment by mtmail** [comment]
Can you copy&paste the relevant part(s) of the XML and what values you think should change? 

We usually look at the place details http://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=40924539 and then the sorting of the `admin_level` column.

Unterspreewald (http://www.openstreetmap.org/relation/1389282) set as `admin_level=7` looks alright according to https://wiki.openstreetmap.org/wiki/DE:Grenze

**Comment by lonvia** [comment]
LDS?

**Comment by Megachip** [comment]
> We usually look at the place details http://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=40924539 and then the sorting of the  admin_level  column.

Yeah, thats correct, but reverse giving the wrong county ignoring level 6 (which is the county).
On zoom <10 county is set correct.

> Can you copy&paste the relevant part(s) of the XML and what values you think should change?

```xml
<result boundingbox="52.0279253,52.0286263,13.8741517,13.8805184" lon="13.877233" lat="52.0284171" osm_id="40924539" osm_type="way" place_id="80057273" ref="Archedamm">Archedamm, Schlepzig, Unterspreewald, Landkreis Dahme-Spreewald, Brandenburg, 15910, Germany</result>
<addressparts>
<path>Archedamm</path>
<city>Schlepzig</city>
<county>Unterspreewald</county>
<state>Brandenburg</state>
<postcode>15910</postcode>
<country>Germany</country>
<country_code>de</country_code>
</addressparts>```
should have 
`<county>Landkreis Dahme-Spreewald</county>`

I think this will match also more to the description [here](https://wiki.openstreetmap.org/wiki/DE:Grenze#Kreisgrenzen_-_admin_level.3D6).

**Comment by mtmail** [comment]
I figured LDS = Landkreis Dahme-Spreewald

**Comment by lonvia** [comment]
Nominatim matches admin level 7 and 6 both to 'county', so that just one of them wins. Solving this needs a different format for the address details. There are some suggestions already in #662. Closing here as a duplicate.
