### ISSUE TITLE
Reverse query help

### ISSUE THREAD

**Issue by maxicabanillas78** [openstreetmap/Nominatim#769]
How to increase reverse server query
I have 1500 query per second and several of it brings null
That I can modify to umentar the consultations

root@ip-172-31-9-0:/home/ubuntu# netstat -an | grep :80 | wc -| netstat -an | grep :80 | wc -l
1574
root@ip-172-31-9-0:/home/ubuntu# netstat -an | grep :80 | wc -| netstat -an | grep :80 | wc -l
1739

**Comment by lonvia** [comment]
This issue lacks information. Is that on a private installation? What hardware? What data was imported? Altogether 1500 queries/s does actually sound very good.
