### ISSUE TITLE
Weight on searches with accented characters

### ISSUE THREAD

**Issue by davidajnered** [openstreetmap/Nominatim#772]
When searching for "Rö" like in the Swedish town "Röstånga" only results starting with "Ro" are returned. Weighting the results and sorting with "Rö" above "Ro" would be preferred.

**Comment by lonvia** [comment]
Again, please state what you expect to find when searching for "Rö".

**Comment by davidajnered** [comment]
I expect to find results with "Ö", not "O", in the top of the search results. I'm not searching for "Romania" or "Rostov", there's no Ö in those names.

![screenshot from 2017-07-24 07-51-17](https://user-images.githubusercontent.com/247504/28509964-cfe5042a-7045-11e7-90be-d1243417d9b7.png)

**Comment by lonvia** [comment]
Well, there simply are no results for "rö". All the results you get are for "ro". There is a normalization at work here that maps "o" and "o" together, mostly for the benefit of being able to type "o" when you mean "ö". It is true that it is less likely that a search query works the other way around but the way the normalization works, it is not possible to make the distinction and likely will never be. In any case, this particular example is a case of garbage-in-garbage-out. Nominatim does limited accent weighting  although that works only if there are sensible results to be expected.
