### ISSUE TITLE
Locations with accented characters not included in search result

### ISSUE THREAD

**Issue by davidajnered** [openstreetmap/Nominatim#773]
When searching for "Röstång" like in the Swedish town "Röstånga" only "Rostang" in France shows up in the results.

Might be somewhat related to https://github.com/openstreetmap/Nominatim/issues/772

**Comment by lonvia** [comment]
I don't quite understand the issue here. "Röstånga" works perfectly fine, so accents obviously work. What do you expect to find? Please link to the relevant OSM object.

**Comment by davidajnered** [comment]
I expect "Röstånga" to end up in the search results for the search term "Röstång" (without the last a). Searching for the whole word is fine, so yes accents work, but I was expecting better string comparison (and sorting, see #772 ).

**Comment by lonvia** [comment]
Nominatim does not do partial word search or 'search-as-you-type'. Use [photon](https://github.com/komoot/photon) if you require that.
