### ISSUE TITLE
 Structured Query returns wrong result: Nürnberg

### ISSUE THREAD

**Issue by elcid** [openstreetmap/Nominatim#774]
This query: https://nominatim.openstreetmap.org/search.php?city=N%C3%BCrnberg&country=Deutschland 

delivers the wrong location: Nürnberg, Tann (VGem), Landkreis Rottal-Inn, Lower Bavaria, Bavaria, Germany (Hamlet)

Otherwise by using query string, the web service return the correct city:
https://nominatim.openstreetmap.org/search.php?q=N%C3%BCrnberg&country=Deutschland

Any explanation or suggestion (if the case) how to fix this?

Thanks

**Comment by lonvia** [comment]
That 's a known issue with German 'Kreisstädte' which cannot be found reliably with structured queries. (The problem being that they are mapped as counties in OSM not as a town.) I thought this was reported before but I can't see to find any older issue.

**Comment by elcid** [comment]
I found this Issue:
https://trac.openstreetmap.org/ticket/5300

**Comment by RedBaron2** [comment]
I will add one more to the list of issues.
Query for [Austin, MN](https://nominatim.openstreetmap.org/search?q=Austin,%20MN&countrycodes=US&format=xml&addressdetails=1&limit=1)
This returns
`<city>Austin</city>`
`<county>Travis County</county>`
`<state>Texas</state>`
`<country>USA</country>`
`<country_code>us</country_code>`
You change the Query
[Austin, Minnesota](https://nominatim.openstreetmap.org/search?q=Austin,%20Minnesota&countrycodes=US&format=xml&addressdetails=1&limit=1)
`<city>Austin</city>`
`<county>Mower County</county>`
`<state>Minnesota</state>`
`<country>USA</country>`
`<country_code>us</country_code>`
I had thought that it was a coding issue on my end, but after plugging in the city, state directly. The same buggy return is presented.
My guess is that the query is not passing a secondary check to verify the State Abbreviation, and instead is going on the most popular search for that City.

**Comment by mtmail** [comment]
Hi @RedBaron2. Can you submit this as a new issue? You use `q=` which isn't a structured query (e.g. `city=...&state=...`) so it seems unrelated.

**Comment by RedBaron2** [comment]
@mtmail 
I will submit it as a new issue then

**Comment by FelHell** [comment]
The problem with the German "Kreisstädte" still exists, for example for Augsburg:
* https://nominatim.openstreetmap.org/?city=Augsburg&state=Bayern&country=Deutschland
* https://nominatim.openstreetmap.org/?q=Augsburg,Bayern,Deutschland

...and for Nuremberg:
* https://nominatim.openstreetmap.org/?city=Nürnberg&state=Bayern&country=Deutschland
* https://nominatim.openstreetmap.org/?q=N%C3%BCrnberg,Bayern,Deutschland

It would be nice if this issue could be fixed. It's surprising that a city like Augsburg is replaced with a small village like Augsberg.

**Comment by lonvia** [comment]
Please be aware that the fix will only gradually take effect on nominatim.openstreetmap.org because the database has not been reimported. There are also some boundary relations in OSM that still need an appropriate hint regarding their city status (either a place=city tag on the relation or linking of the place=city node as a member with a 'label' role).

**Comment by micw** [comment]
@lonvia Could you trigger a forces update for Nürnberg to verify that fix?
That could cause https://nominatim.openstreetmap.org/search?format=json&addressdetails=1&featuretype=city&q=90411%20N%C3%BCrnberg to return a record, right?
