### ISSUE TITLE
Incorrect zip code for Mechanicsburg, PA in Grantham village area

### ISSUE THREAD

**Issue by pmacMaps** [openstreetmap/Nominatim#777]
"2608 Shingus Circle, Mechanicsburg, PA 17055" is a valid and real address.  However, no search results are found.

If I type "2608 Shingus Circle, PA" it shows the correct location. However, is shows it as Shingus Circle, Rosegarden, Cumberland County, Pennsylvania, 17027, United States of America.

Addresses in the old Grantham zip code use the Mechanicsburg 17055 zip code.  This address locator should be updated to do this.  I don't mind fixing this, but I've never edited in OSM, although I am a GIS professional.

**Comment by lonvia** [comment]
The ZIP codes are taken from the old Tiger imports. You'll see `tiger:left` and `tiger:right` tags with the 17027 on [Shingus Circle](http://www.openstreetmap.org/way/12345589). The easiest way to fix that (given that there are no actual address points yet available in that area where the postcode should actually go) is to remove the erronous `tiger:*` tags and replace them with a single `postcode=<zip code>` tag. If you don't feel up to the task, leave a note and maybe a mapper picks that up.

In any case, this is not an issue with the search software but with the data. So this is not really the right place to report this. Closing as data issue.
