### ISSUE TITLE
Question: What happens if data update is interrupted?

### ISSUE THREAD

**Issue by alejo90** [openstreetmap/Nominatim#780]
I'm setting up a nominatim server and I want to keep it up to date. I was thinking of running `./utils/update.php --import-osmosis-all` in a daemon managed by systemd but I'm concerned about what would happen if for whatever reason it gets interrupted. Is this a good idea? Thanks in advance.

**Comment by lonvia** [comment]
The script can be interrupted any time and should simply pick up where it was stopped when restarting (potentially redoing a bit of the work as it has to start from the last known consistent state). There is one thing to be careful about when running it via systemd: the script starts a lot of programs to do the actual work. These normally don't get killed when the update script itself gets killed. So be sure all child processes are done before restarting the script or you might end up with inconsistent data.

**Comment by alejo90** [comment]
Thanks @lonvia
