### ISSUE TITLE
lookup returns "short_name" as city instead of name or address:city

### ISSUE THREAD

**Issue by 3add3287** [openstreetmap/Nominatim#783]
Hi

when doing lookups for coordinates nomination returns short_name instead of name. This is problematic b/c
- A number of places have unofficial names, nick names or abbreviations listed with the short_name tag.
- The key definition doesn't mandate that short_name is an official name (so these entries are not actually incorrect). Reference: http://wiki.openstreetmap.org/wiki/Key:name
- The official (non-short, i.e. full) name is official and recognized everywhere
- Anyone looking for an address for a set of coordinates seems to be most likely interested in an accurate address, not a short version. Considering the length of the full address I don't see how using the short name helps keeping the result significantly shorter (beside it being less/not useful)

Example below:
$ curl -H "Content-Type: text/json; charset=UTF-8" 'http://nominatim.openstreetmap.org/search/49.039%2012.13?format=json&addressdetails=1'
[{"place_id":"93913350","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"114354222","boundingbox":["49.0386887","49.0388809","12.1291585","12.1294229"],"lat":"49.03878475","lon":"12.1292907023623","display_name":"13, Am Flachlberg, Brandlberg, Rgbg, Regensburg, OPf, Bayern, 93057, Deutschland","class":"building","type":"yes","importance":0.001,"address":{"house_number":"13","road":"Am Flachlberg","suburb":"Brandlberg",**"city":"Rgbg"**,"county":"Regensburg","state_district":"OPf","state":"Bayern","postcode":"93057","country":"Deutschland","country_code":"de"}}]

**Comment by lonvia** [comment]
Your first point is a data issue. short_name should be a recognizable, commonly used short version of the name, not a nick name (use alt_name for that) and not an abbreviation (might go into ref, although that's a stretch, too) and it should certainly be correct. As for wanting the full official name or the short form, there is an argument for both. What you really want for displaying results (which is the main use of nominatim) is the most commonly used name. I haven't done any systematic research but I'd say the shorter version is more likely to be used as long as it is reasonably distinctive.

**Comment by 3add3287** [comment]
I _might_ be a data issue _as well_ but that's IMHO not clear with the ambiguous definitions there. The English excludes abbreviations, which Rgbg is. The German version in the wiki does not mention any of that. But even with nick names and abbreviations excluded, a "recognizable, commonly used short version of the name" as describe by the wiki is too vague and indistinctive.
Not that "name" is suddenly 100% clear and distinctive - it seems only the definition of "official_name" would fit that. However, while "common default name" for the name key is vague, the reference to street signs makes this distinctive enough as that gets very close to an official short name.

Aside from the definition of the keys in openstreetmap, a number of use cases for Nominatim reverse lookups I see include using the resulting data. For that using city = short_name does seem to come with a number of problems that "name" wouldn't "name" is defined as a short common form but doing it in a context of official names due to the street sign reference.

The same applies to "OPf" for admin_level=5 relation that Regensburg is in. I've seen it being referred to as OPf only very few times outside a Openstreetmap context, but it seems somewhat official and maybe common. But what is common? That depends on the audience, and I'd say that 99% of the people seeing the output above would not have any idea what it means and no parsing algorithm could make any sense of it - unless it's using OSM data.

I can see the short_name being useful in some cases. My argument is that for the majority of the cases it's not useful. In that context I can totally see returning short_name and official_name being returned as separate fields, but not used to form the more distinct fields like "city" (or state, country etc). If the short common form was enough, for countries and states the abbreviation/codes (be it country code, ISO3166-1 or -2) could be used - they are often as if not more common than abbreviations. That wouldn't make short_name incorrect data though...

**Comment by tuukka** [comment]
I have a similar point of view as @3add3287 and have reinstated the established definition of short_name in the OSM wiki for now: `Common abbreviation, useful for searching (recognized by Nominatim).` As Nominatim is not the only system using `short_name` anymore, the definition can't be interpreted as "whatever Nominatim does".

Functionality should trump aesthetics in OSM: `name` is what should be displayed on the map and in search results. `short_name` should be used to supply short names and abbreviations that the user can type in to find the place that they have in mind. That is how e.g. Pelias search and reverse lookup interpret short_name.

**Comment by shrddr** [comment]
The wiki says don't put abbreviations in short_name because of a nominatim issue. Nominatim issue says don't put abbreviations in short_name because it's forbidden by the wiki. Hmm smells like a circular reference

**Comment by MaskedBit** [comment]
I'm getting different results for "display_name" depending on what I use to send the request.  If I request the URL [(https://nominatim.openstreetmap.org/search?city=Los+Angeles&state=CA&country=us&format=jsonv2)]" using the Java Spring RestTemplate or from the command line with curl, I get:
`"display_name" : "LA, Los Angeles County, California, USA"`
but if I use a browser (Firefox in this case), the result is:
`"display_name":"Los Angeles, Los Angeles County, California, USA"`
I would assert that, first, the short name should never be returned in the display_name field, and second, the result should not depend on how the request was made.  It appears nominatim is differentiating based on the request headers.

**Comment by lonvia** [comment]
Nominatim looks at the languages you ask for in your request headers. That's not a bug, it's a feature.

For a full list of name tags, use `namedetails=1`.

**Comment by Shragel** [comment]
If you use EN as the language its short. 
If you use en as the language its long.

**Comment by jeffrey-friedl** [comment]
The wiki explicitly says that the "short_name" is intended for _searching_, so perhaps it's best not to use it as any kind of display name, or, at most, as a last-ditch effort when both the language-localized name and the raw "name" don't exist?
