### ISSUE TITLE
Address returned for park includes hiking trail

### ISSUE THREAD

**Issue by bikeoid** [openstreetmap/Nominatim#786]
The address returned for Table Rock State Park  http://nominatim.openstreetmap.org/details.php?place_id=173952204 lists:

Table Rock State Park, 
Pinnacle Mountain Trail, 
Pickens County, 
South Carolina, 
United States of America

  "Pinnacle Mountain Trail" is unexpected since it is a simple hiking trail http://www.openstreetmap.org/way/399546592#map=17/35.03278/-82.70570&layers=C  .  It is not a member of any relation but close to the center of the park multi-polygon.

  The park defined by relation http://www.openstreetmap.org/relation/6386165 is not contained within a city polygon, and seems to be too far from nearby cities for them to be chosen.

  I added is_in:city=Pickens to the park multipolygon to try to give the postal mailing city in place of the hiking trail 24 hours ago, but it doesn't appear to have any effect.   The "Data last updated" date appears to be much newer than that edit.

  Is there a better way to tag a hint for an admin level to replace the hiking trail?

**Comment by lonvia** [comment]
I have increased the rank for leisure=park. The change is live already but note that it has only an effect on objects that are added/modified from now on. The city designation for this particular park will still be a bit odd, I'm afraid, but that has to do with sub-optimal handling of place nodes and as such is a different issue (which is quite a bit harder to fix).
