### ISSUE TITLE
Requesting data from openstreetmap.nominatim that is being blocked

### ISSUE THREAD

**Issue by peslis** [openstreetmap/Nominatim#788]
Hello ,
in my website i use the leaflet search with the nominatim.openstreetmap. But as i try to request the data from openstreet i get this error because the connection isnt secure. Is there a link to a website that is under an https service?
This is the error i get :
leaflet-search.js:490 Mixed Content: The page at ‘https://gopartner.000webhostapp.com/home.php’ was loaded over HTTPS, but requested an insecure script ‘http://nominatim.openstreetmap.org/search?format=json&q=gte&json_callback=L.Control.Search.callJsonp’. This request has been blocked; the content must be served over HTTPS.

**Comment by lonvia** [comment]
nominatim.openstreetmap.org is https-enabled. If https is not used, then this is not an issue with nominatim but with leaflet-search.
