### ISSUE TITLE
Please change.

### ISSUE THREAD

**Issue by ByViking** [openstreetmap/Nominatim#790]
Schellenberg is a part of Neunkirchen am Brand, Landkreis Forchheim, Oberfranken, Bayern not a part of Dormitz (VGem)

**Comment by lonvia** [comment]
This is a data issue. The [place node of Schellenberg](http://www.openstreetmap.org/node/4996348225) is clearly inside the [boundary of Dormitz](http://www.openstreetmap.org/relation/2985212). You need to fix this issue in the OSM data if it is wrong.
