### ISSUE TITLE
Wrong street name inherited by node within area

### ISSUE THREAD

**Issue by ujos** [openstreetmap/Nominatim#791]
For the following node Search returns incorrect address:
Expected: EPAM Systems, 114, Opolska
In fact:  EPAM Systems, 114, Aleja 29 Listopada

Node is created within boundaries of building which has address "Opolska 114"

Search: https://www.openstreetmap.org/search?query=epam%2Ckrakow#map=19/50.08739/19.95464
Node: https://www.openstreetmap.org/node/4519074184
Building: https://www.openstreetmap.org/way/337757651

**Comment by lonvia** [comment]
This kind of works. You'll see that the address is correct now that the database happened to be recreated. I suspect that there is something wrong with updates. I need to create a couple of test cases for that.

**Comment by lonvia** [comment]
Should be fixed with d1ca73f813465de8102f79ac71dbe71d8ba320da.
