### ISSUE TITLE
Unable to update nominatim

### ISSUE THREAD

**Issue by spin0us** [openstreetmap/Nominatim#792]
Following the [official documentation](http://nominatim.org/release-docs/latest/Import-and-Update), i got this error :
```
root@myhost:/srv/nominatim/Nominatim/build# ./utils/update.php --import-osmosis-all
Currently at sequence 2606900 (04/09/2017 01:57:57) - t indexed
/usr/local/bin/pyosmium-get-changes --server http://planet.openstreetmap.org/replication/minute -o /srv/nominatim/Nominatim/build/osmosischange.osc -s 30 -I 2606900
Traceback (most recent call last):
  File "/srv/nominatim/Nominatim/utils/osm_file_date.py", line 3, in <module>
    import osmium
ImportError: No module named osmium
ERROR: Error getting date from diff file.
Error getting date from diff file.
```
I used full planet import (with no problem).
```
root@myhost:/srv/nominatim/Nominatim/build# cat settings/local.php
<?php
 @define('CONST_Website_BaseURL', '/nominatim/');
 @define('CONST_Osm2pgsql_Flatnode_File', '/var/nominatim/flatnode.file');
 @define('CONST_Pyosmium_Binary', '/usr/local/bin/pyosmium-get-changes');
```
```
root@myhost:/srv/nominatim/Nominatim/build# find / -name 'pyosmium-get-changes'
/usr/local/bin/pyosmium-get-changes
```
Don't know what to do ...
My server is Ubuntu 16.04.3 (Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz with 63GB RAM and 2 x 1TB nvme)

**Comment by stevewolfe555** [comment]
I too am getting a very similar error.

`Traceback (most recent call last):
  File "/home/stephen/.local/bin/pyosmium-get-changes", line 22, in <module>
    from osmium.replication import server as rserv
ImportError: No module named osmium.replication
ERROR: Error running pyosmium tools
Error running pyosmium tools
`

**Comment by lonvia** [comment]
How did you install pyosmium?

**Comment by stevewolfe555** [comment]
this first `sudo apt-get install python-pip python-dev build-essential 
`

Then
`sudo pip install --upgrade pip`

Then 
`sudo apt-get install python-setuptools`

Then 
`sudo pip install --user osmium`

**Comment by lonvia** [comment]
Does it work after `pip install --user osmium`? (Note the lack of `sudo`).

**Comment by stevewolfe555** [comment]
Well i could only get it to install as sudo.

`Collecting osmium
  Using cached osmium-2.13.0.tar.gz
Installing collected packages: osmium
  Running setup.py install for osmium ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsGzvb/osmium/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i1Naoi-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    libosmium found in 'libosmium-2.13.1'
    running install
    error: [Errno 13] Permission denied: '/home/stephen/.local/lib/python2.7'
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-vsGzvb/osmium/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i1Naoi-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-vsGzvb/osmium/
`

**Comment by lonvia** [comment]
Well, that's actually a result of using --user with sudo. It has messed up your home directory. Change back the owner of all files in .local with `sudo chown -R stephen /home/stephen.local`. Then try again.

**Comment by stevewolfe555** [comment]
ah I thought I might have messed up permissions somewhere.

I have run it again and it says.

`Requirement already satisfied: osmium in ./.local/lib/python2.7/site-packages`

So I tried to run `./utils/update.php --init-updates` from the build folder and get this.

`Functions
CREATE FUNCTION
CREATE FUNCTION
ERROR:  permission denied for language c
ERROR: pgsql returned with error code (3)
pgsql returned with error code (3)
ERROR: Error running setup script
Error running setup script`

Any ideas on that?

**Comment by stevewolfe555** [comment]
If i run are user nomnimatim I get the error I started with.

`sudo -u nominatim ./utils/update.php --init-updates`

**Comment by stevewolfe555** [comment]
Ahh fixed it, reinstalled it as user nominatim

**Comment by stevewolfe555** [comment]
@lonvia Thank you.

Do you know if there is a guide on how to add additional datasets without disturbing the current loaded on?

**Comment by spin0us** [comment]
Still the same problem for me. It says `ImportError: No module named osmium` even if i got no problem with installation part.

**Comment by lonvia** [comment]
@spin0us You seem to be running the import and updates as root. That is not supported. You are on your own there, I'm afraid.

**Comment by jhward** [comment]
I too am having a similar problem 
This is what I'm getting when I run " ./utils/update.php --init-updates" on a CentOS 7 box

`[nominatim@itrack03 build]$ ./utils/update.php --init-updates
2018-04-22 20:59:50 == Create Functions
NOTICE:  drop cascades to function get_addressdata(bigint,integer)
NOTICE:  drop cascades to function get_wikipedia_match(hstore,character varying)
Summary of warnings:


2018-04-22 20:59:50 == Setup finished.
Traceback (most recent call last):
  File "/srv/nominatim/osmium-2.14.0/tools/pyosmium-get-changes", line 22, in <module>
    from osmium.replication import server as rserv
  File "/srv/nominatim/osmium-2.14.0/tools/osmium/__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: No module named _osmium
ERROR: Error running pyosmium tools
Error running pyosmium tools
[nominatim@itrack03 build]$`
