### ISSUE TITLE
Always Reporting Error

### ISSUE THREAD

**Issue by Patchivic** [openstreetmap/Nominatim#794]
I'm receiving below error each time I'm searching for any address.
`Error Domain=NSCocoaErrorDomain Code=3840 "JSON text did not start with array or object and option to allow fragments not set." UserInfo={NSDebugDescription=JSON text did not start with array or object and option to allow fragments not set.}`

**Comment by lonvia** [comment]
This is not a nominatim error. Please either find out about any underlying issue with Nominatim or report it whereever exactly you where trying to do a search.

That said there was a short server outage about two hours ago, which is the likely cause of this message.
