### ISSUE TITLE
Wrong Location

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#799]
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=52.41347725281853&lon=12.842056268127637&zoom=13

should return "Groß Kreutz" but returned "Plötzin".

**Comment by lonvia** [comment]
This is a known issue with the current reverse implementation. It looks first for the nearest road and then returns the town where that road is in. There is a lengthly discussion about improvements in #512 already, so closing here as duplicate.
