### ISSUE TITLE
Enable ability to ignore Apartment/APT/Floors 

### ISSUE THREAD

**Issue by skorasaurus** [openstreetmap/Nominatim#80]
In many cases, especially with apartment complexes in the USA, there will be multiple people sharing the within the same building, the difference being a separate Apartment/Unit number which may not be mapped yet. 

i.e. 
Richard fairhurst | 1012 Prospect Avenue, Apt 10 
Sir Twain | 1012 Prospect Avenue, Apt 15 

Even if the apartments or unit numbers aren't mapped yet, it would be helpful to direct the person to the apartment building, 1012 Prospect Avenue. 

Tested this on nominatim on osm.org: if I search for 1012 Prospect Avenue, Apt 11 I do not receive any results. 
But if I am searching for just 1012 Prospect Avenue, results are returned.

**Comment by hrfuller** [comment]
Bump. I am having the same issue: apartment numbers causing searches to return empty.

**Comment by zolrath** [comment]
I'm also having this issue. Are there any plans to stop apartment numbers from breaking Nominatim?

**Comment by lonvia** [comment]
Sure at some point but it is not very high on the todo list at the moment, sorry.

**Comment by lonvia** [comment]
If that gets done, then by adding support for addr:unit. So closing this in favour of #587.
