### ISSUE TITLE
Looking to confirm a corrupted Postgres database.

### ISSUE THREAD

**Issue by cjgibson** [openstreetmap/Nominatim#800]
I found that my local installation of Nominatim has stopped updating, and fails while attempting to index the 30th rank of the most recent diff, as shown below:

```
$ /srv/nominatim/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 1 -r 30
nominatim version 3.0.1

Starting indexing rank (30 to 30) using 1 threads
Starting interpolation lines (location_property_osmline)
  Done 0 in 0 @ 0.000000 per second - FINISHED

Starting rank 30
index_placex: UPDATE failed: ERROR:  unexpected chunk number 0 (expected 1) for toast value 11918252 in pg_toast_2187265
CONTEXT:  PL/pgSQL function placex_update() line 104 at assignment
```

I'm not at all experienced with the intricacies of Nominatim's indexing scheme, but a quick google search seems to suggest that the root cause here is likely a corrupted Postgres database. Just looking to confirm if that is the case, and if it isn't, what steps I can take to attempt and rectify the above.

Thanks in advance.

**Comment by lonvia** [comment]
Yes, that is a corrupted database, I'm afraid. If you can find the affected table and rows, you might be able to just remove the corrupted parts and reimport the OSM data behind it (using one of the ./utils/update.php --import-node/way/relation functions). Otherwise a reimport might be in order.

**Comment by cjgibson** [comment]
Thanks for the confirmation @lonvia -- thankfully this particular instance is running out of a backed up VM, so with a little luck I should be able to avoid a full reimport. Fingers crossed!
