### ISSUE TITLE
Search fails with queries that include place names

### ISSUE THREAD

**Issue by francislavoie** [openstreetmap/Nominatim#801]
I'm using https://github.com/smeijer/leaflet-geosearch which works by displaying the results of the typed query, then when clicking on a result, it searches the resulting `display_name` to drill down to a specific result. This seems to fails if the query for the specific result begins with a place name.

Related issue I posted on that project: https://github.com/smeijer/leaflet-geosearch/issues/144

Example: I first type "rogers centre" in the search, and I get these results:

http://nominatim.openstreetmap.org/search?format=json&q=rogers%20centre

Then I click on the first result, which does a search for this:

http://nominatim.openstreetmap.org/search?format=json&q=Rogers%20Centre,%201,%20Blue%20Jays%20Way,%20CityPlace,%20Old%20Toronto,%20Toronto,%20Ontario,%20M5V%201J4,%20Canada

**Comment by lonvia** [comment]
The example you give hits bug #164. There are some other cases where searching for the display_name does not work, in particular in relation to postcodes.

As you note in the other ticket, there really isn't any need for resending the query line that. A reverse query with osm_id and osm_type is definitely the way to go. It will be considerably faster.

**Comment by francislavoie** [comment]
Awesome, thanks for confirming!
