### ISSUE TITLE
Internal server error 

### ISSUE THREAD

**Issue by carlopost** [openstreetmap/Nominatim#804]
Dear reader,

We are getting the following error when placing a marker:

<html>
<head><title>Internal Server Error</title></head>
<body>
<h1>Internal Server Error</h1>
<p>Nominatim has encountered an internal error while accessing the database.
This may happen because the database is broken or because of a bug in
the software. If you think it is a bug, feel free to report
it over on <a href="https://github.com/openstreetmap/Nominatim/issues">
Github</a>. Please include the URL that caused the problem and the
complete error details below.</p>
<p><b>Message:</b> Could not get places for search terms.</p>
<p><b>SQL Error:</b> DB Error: syntax error</p>
<p><b>Details:</b> <pre><pre>
SELECT place_id, ( SELECT count(*) FROM ( SELECT unnest(ARRAY[18584968,20846233]) INTERSECT SELECT unnest(nameaddress_vector) ) s) as exactmatch FROM search_name WHERE name_vector @> ARRAY[3315GK] and array_cat(nameaddress_vector,ARRAY[]::integer[]) @> ARRAY[132645,119898,1469865] ORDER BY (CASE WHEN importance = 0 OR importance IS NULL THEN 0.75-(search_rank::float/40) ELSE importance END) DESC, exactmatch DESC LIMIT 20 [nativecode=ERROR: syntax error at or near "GK"
LINE 1: ...h FROM search_name WHERE name_vector @> ARRAY[3315GK] and ar...
^]</pre></pre></p></body></html>

Can you please look at this

Best regards

Carlo Post
programmer at NWWI
mailto:c.post@nwwi.nl

**Comment by lonvia** [comment]
The fix is now live. If it does not fix your particular use case, then please add the request that causes the faults.
