### ISSUE TITLE
Polygon_* parameters return no polygon points

### ISSUE THREAD

**Issue by pesho318i** [openstreetmap/Nominatim#810]
Hello,

I noticed that for many addresses the polygon_* parameters return no polygon info.

For example the following request:
http://nominatim.openstreetmap.org/search.php?q=prinsengracht+697+amsterdam&polygon_svg=1&format=xml
// the response contains only geosvg="cx="4.8842905" cy="-52.365469599999997""

However, if I use polygon=1 (which is deprecated according to the Nominatim Wiki), I do get polygon points in the response.
http://nominatim.openstreetmap.org/search.php?q=prinsengracht+697+amsterdam&polygon=1&format=xml
// the response contains polygonpoints="[[4.8842905,52.3655196],[4.8843258553391,52.365504955339],[4.8843405,52.3654696],[4.8843258553391,52.365434244661],[4.8842905,52.3654196],[4.8842551446609,52.365434244661],[4.8842405,52.3654696],[4.8842551446609,52.365504955339]]"

**Comment by lonvia** [comment]
This behaviour is expected. The result for that query is an OSM node, so we only have a point geometry available. `The polygon=1` used to cheat in that case by creating an artificial circle around that node. The newer polyfon_* functions don't do that anymore, they just return the geometry of the object as is. If you want to have the circle back, you need to create it on the client side when a point is returned.

**Comment by pesho318i** [comment]
Thanks @lonvia,

I did not realize that the polygon=1 always returns 8 points that form a circle-like polygon around the resulting node.

I was actually aiming at getting the polygon points of a particular building (given the lat/lon or address). Can I do this with a Nominatim forward or reverse search? So far I could get results only for a very limited set of locations. Please let me know if this is doable (and if not, can you recommend another approach).

Enjoy your day!

**Comment by mtmail** [comment]
When you look at Prinsengracht 697, it's an address node in OSM. The building (polygon) is separate and not linked to the node.

https://www.openstreetmap.org/node/2729942658
https://www.openstreetmap.org/api/0.6/node/2729942658 (XML)

Nominatim ignores map features (e.g. buildings) that don't have a name, address or other address-like reference.

You'd need to import OSM data into your own database and search for building that cover the search location.

If it's a limited set of locations you could try a bounding-box search using https://wiki.openstreetmap.org/wiki/Overpass_API and inspect each returned building.

**Comment by pesho318i** [comment]
@mtmail, thaks for the suggestion. I'll give it a try with the Overpass API.

Cheers!
