### ISSUE TITLE
Nearby non-convex county returned for a place

### ISSUE THREAD

**Issue by n1vux** [openstreetmap/Nominatim#811]
Puerto Rico Hurricane Mapathon [Diary entry](http://www.openstreetmap.org/user/Alan%20Bragg/diary/42461
) location tag footer shows Dewey Library, East Cambridge as being in Suffolk County. It should say Middlesex.
[pic](https://photos.google.com/share/AF1QipNipUBriMsukkOHc0eNL4uW2o4YLAPRSBfqd6fqoZMS1BfQIfNoyiCjauw4rO8c5Q?key=TEtISWF2NkI3VzJDLWYtd0YyaDNucUtxSXprd2J3)

My guess would be that complex county outlines are expanded to bounding boxes and convex hulls, and point inclusion is tested on the bounding box and convex hull before being tested on the actual outline if more than one county is still in plausible. If so, I would expect both Middlesex and Suffolk counties to be plausible after convex hull tests, but if final selection is by actual inclusion (not closest to medial point or some such "optimization") Suffolk should be rejected.

Oddly, [East Cambridge](http://www.openstreetmap.org/node/158877265) correctly has `is_in` Middlesex Co.

[Suffolk](http://nominatim.openstreetmap.org/details.php?place_id=178582859)
[Middlesex](http://nominatim.openstreetmap.org/details.php?place_id=178394187)
[Dewey Lib](http://nominatim.openstreetmap.org/details.php?place_id=20802731)
API [query](http://nominatim.openstreetmap.org/search?q=Dewey+Library&format=xml&polygon=1&addressdetails=1) and results 
```xml
<searchresults timestamp="Mon, 09 Oct 17 13:56:40 +0000" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="Dewey Library" polygon="true" exclude_place_ids="20802731" more_url="http://nominatim.openstreetmap.org/search.php?q=Dewey+Library&exclude_place_ids=20802731&addressdetails=1&polygon=1&format=xml&accept-language=en-US%2Cen%3Bq%3D0.7%2Cfr%3Bq%3D0.3"><place place_id="20802731" osm_type="node" osm_id="1982225149" place_rank="30" boundingbox="42.3613541,42.3614541,-71.0834647,-71.0833647" polygonpoints="[[-71.0834147,42.3614541],[-71.083379344661,42.361439455339],[-71.0833647,42.3614041],[-71.083379344661,42.361368744661],[-71.0834147,42.3613541],[-71.083450055339,42.361368744661],[-71.0834647,42.3614041],[-71.083450055339,42.361439455339]]" lat="42.3614041" lon="-71.0834147" display_name="Dewey Library, Main Street, East Cambridge, Cambridge, Suffolk, Massachusetts, 02118, United States of America" class="amenity" type="library" importance="0.201" icon="http://nominatim.openstreetmap.org/images/mapicons/amenity_library.p.20.png"><library>Dewey Library</library><road>Main Street</road><neighbourhood>East Cambridge</neighbourhood><town>Cambridge</town><county>Suffolk</county><state>Massachusetts</state><postcode>02118</postcode><country>United States of America</country><country_code>us</country_code></place></searchresults>
```

**Comment by lonvia** [comment]
Looks like a tagging error for Middlesex county. The admin_level is missing from the boundary relation and so Nominatim can't put it at the right place in the address hierarchy.

**Comment by n1vux** [comment]
On Tue, Oct 10, 2017 at 3:50 PM, Sarah Hoffmann
<notifications@github.com> wrote:
>
> Looks like a tagging error for Middlesex county. The admin_level is missing from the boundary relation and so Nominatim can't put it at the right place in the address hierarchy.

Thanks.

Worse, it is intentional.

note="There is not and should not be any admin_level (6 or otherwise)
tag set here, as there is effectively no county-level government here"
  Changeset "Eight counties in Massachusetts have no county
administration (therefore no admin_level value) "
http://www.openstreetmap.org/changeset/50237304
by well known armchair mapper SteveA

There are still county courts, and Towns are assigned by County still,
and deeds are registered with a County Registrar, so this is
narrow-minded pedantry. We have only minor elective offices at County
(Registrar and Sheriff,  none with power to Tax or Govern) but we do
have Administration.

I seem to recall this was discussed on Talk-us.
I guess we need to have another talk with SteveA.
He should leave Mass to talk-us-mass and not rely upon Wikipedia's
political science  ... we know what is done at county level here.
And Nominatum doesn't believe we don't have counties (and it's right
because we do)

If the rule is what the signs say, we still have entering COUNTY signs ...


-- 
Bill Ricker
bill.n1vux@gmail.com
https://www.linkedin.com/in/n1vux

**Comment by lonvia** [comment]
There seems to be a misconception here that the existence of admin_level implies existence of administration. That's clearly wrong. And if the argument would hold, then I would expect Middlesex-North and Middlesex-South to be mapped with something like admin_level=7. This would also solve the problem with the address in a half-way reasonable manner.

In any case, this is clearly a tagging issue and nothing Nominatim can do anything about it. So closing here. I would suggest that you rise the issue again on the talk-us list.
