### ISSUE TITLE
Reverse - using lat/lon - returned polygon not containing given point?

### ISSUE THREAD

**Issue by jbostoen** [openstreetmap/Nominatim#815]
hi

Case: trying to get a polygon (admin boundary) from XY-coordinates

Is there something on my end I'm forgetting? 
This query gives a polygon, but the given point is not in it.
https://nominatim.openstreetmap.org/reverse?&format=json&lat=46.69160088652035&lon=2.2409939035123068&addressdetails=1&zoom=10&polygon_geojson=1

A little more to the north, getting a different but also wrong polygon
https://nominatim.openstreetmap.org/reverse?&format=json&lat=46.699371618553414&lon=2.242023871774027&addressdetails=1&zoom=10&polygon_geojson=1

Still a little more to the north, I get the sort of polygon I'd expect for the points above. Clearly something exists that I'd actually expect to be returned in both queries above.
https://nominatim.openstreetmap.org/reverse?&format=json&lat=46.70949544007243&lon=2.246143744820902&addressdetails=1&zoom=10&polygon_geojson=1

The reason I'm combining it with '**addressdetails**' (which might be the reason why things go wrong), is because it seemed that **zoom level does not relate the same to city, county, suburb-level across various places**. In some regions, for the same level I'd get the city border; for other suburbs (which gets too specific).

--

Definitely not just because of addressdetails.

Correct: point in the west of a polygon for Fointaines-Saint-Claire:
https://nominatim.openstreetmap.org/reverse?&format=json&lat=49.36881494713063&lon=5.236951431917297&addressdetails=0&zoom=10&polygon_geojson=1

Incorrect: point to the east in that same polygon.
https://nominatim.openstreetmap.org/reverse?&format=json&lat=49.366551274646554&lon=5.260941109346497&addressdetails=0&zoom=10&polygon_geojson=1

**Comment by lonvia** [comment]
That's intended, see also the [Nominatim FAQ](http://nominatim.org/faq#point-outside-address).
