### ISSUE TITLE
Which tags use nominatim to create address hierarchic?

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#816]
Example:
https://nominatim.openstreetmap.org/details.php?place_id=77074436

Lobmachtersen is a part of Ortschaft Südost, thats fine, but Ortschaft Südost isn't part of Lobmachtersen ... so how to prevent nominatim to show/create that false Hierarchie?

Added node 240090399 as label to relation 3413861 as suggested in #766 . But not sure if this is enough?

**Comment by lonvia** [comment]
Yes, that's enough. Nominatim just needs to ignore the newly linked places.
