### ISSUE TITLE
Search for adress is leading to street only, not to house number

### ISSUE THREAD

**Issue by mtz93** [openstreetmap/Nominatim#826]
Hello guys,

i am facing a problem with a street. When i am looking for some specific adress, nominatim will only lead me to the street itself. But this only happens for a few house numbers. 

Example: 

> http://nominatim.openstreetmap.org/search/Am%20Freibad%2015%2073579%20Schechingen?format=xml&addressdetails=1&limit=1&polygon_svg=1

This will give me everything i need including house number.

> http://nominatim.openstreetmap.org/search/Am%20Freibad%203%2073579%20Schechingen?format=xml&addressdetails=1&limit=1&polygon_svg=1

This will not return the house number and only lead me to the street. Doesnt matter if i use the given URLs on the top or look it up on http://nominatim.openstreetmap.org/ itself. But on the other hand, if you look up the coordinates where these buildings are placed on OSM, it will give me the exact adress including house number when i use the URL for Search with LatLon-Coordinates.

Do you know what the problem might be? Thank you very much.

**Comment by mtmail** [comment]
Strange. Coverage of the street looks complete. 
http://tools.geofabrik.de/osmi/?view=addresses&lon=9.91332&lat=48.87575&zoom=18&overlays=buildings,buildings_with_addresses,postal_code,entrances_deprecated,entrances,no_addr_street,street_not_found,place_not_found,misformatted_housenumber,nodes_with_addresses_defined,nodes_with_addresses_interpolated,interpolation,interpolation_errors,connection_lines,nearest_points,nearest_roads,nearest_areas,addrx_on_nonclosed_way

And removing the limit=1 shows the second result has the house number 
http://nominatim.openstreetmap.org/search/Am%20Freibad%203,%2073579%20Schechingen?format=xml&addressdetails=1

**Comment by lonvia** [comment]
This is coleteral damage from the recent postcode rewrite. '3' is interpreted as a postcode and then ignored. We need to change the ranking of results, so that those results where parts are ignored are ranked lower.

**Comment by mtz93** [comment]
I just found out that if you put the house number into first position the search works fine if you use nominatim via URL.

"1 Am Freibad 73579 Schechingen"

> http://nominatim.openstreetmap.org/search/3%20Am%20Freibad%2073579%20Schechingen?format=xml&addressdetails=1&limit=1&polygon_svg=1

But if you look it up on nominatim.openstreetmap.org itself it wont work for house number 1. The rest works fine.

"1 Am Freibad 73579 Schechingen" on https://nominatim.openstreetmap.org => does not work
Every other house number => works

**Comment by mtz93** [comment]
Seems to work perfectly fine since today or yesterday. Thanks
