### ISSUE TITLE
Specifying postalcode in query returns empty result

### ISSUE THREAD

**Issue by Misiu** [openstreetmap/Nominatim#830]
Hi there,
I've noticed issue when specifying postalcode in query.
For example if I do this query:
http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1
I get this result:
```
[{
		"place_id": "79051022",
		"licence": "Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright",
		"osm_type": "way",
		"osm_id": "30607429",
		"boundingbox": ["53.1456401", "53.1460007", "16.7433174", "16.7437247"],
		"lat": "53.1457846",
		"lon": "16.7435335",
		"display_name": "Doktora Franciszka Witaszka, Śródmieście, Piła, powiat pilski, województwo wielkopolskie, 64-920, Polska",
		"class": "highway",
		"type": "residential",
		"importance": 0.125,
		"address": {
			"road": "Doktora Franciszka Witaszka",
			"city_district": "Śródmieście",
			"town": "Piła",
			"county": "Piła",
			"state": "województwo wielkopolskie",
			"postcode": "64-920",
			"country": "Polska",
			"country_code": "pl"
		}
	}
]
```
as You can see in response there is **"postcode": "64-920"**.

When I add postalcode to query parameters (according to http://wiki.openstreetmap.org/wiki/Nominatim#Parameters) and do this query:
http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=62-920
I get no results.

I thought that I can specify postalcode to refine search results.

Is this a bug?
**EDIT**
I just noticed that removing dash from postalcode helped.
Now this query: http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=62920 returned result.

This should be mentioned in wiki or better option would be to allow postalcode format as is returned in results. In Poland we have two digits, dash and three digits ( for example 12-345)

**Comment by lonvia** [comment]
You did try with the wrong postcode (62-920 instead of 64-920). But there was still a bug in the software here. Fixed now and the query with 64-920 works fine again:

http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=64-920

**Comment by Misiu** [comment]
@lonvia sorry for placing wrong link and thank You for quick fix :)

I've noticed that right now I can specify **64-920** or **64920** as postalcode and I get same result. Is this intended behavior?

For example this two give me same result:
http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=64-920
http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=64920

Thing get worst when I specify wrong postalcode:
http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=63-920
or wrong format (without slash) and wrong postalcode:
http://nominatim.openstreetmap.org/search?country=Poland&city=PI%C5%81A&street=WITASZKA&format=json&addressdetails=1&postalcode=60920
still same result.

So for four different postalcodes (64-920, 64920, 63-920, 60920) I get exact same result.

**Comment by lonvia** [comment]
Yes, that is intended. Postcode data in OSM is very patchy and Nominatim often has to take a guess which postocde belongs to an address. To make sure that addresses still can be found, even when Nominatim takes the wrong guess, proper matching of the postcode is now optional. It will still be used  to choose the right result when multiple matches are found.

**Comment by Misiu** [comment]
@lonvia thanks for quick reply and clarification.
This makes thing bit complicated for me - I wanted to use Nominatim primarily for geocoding (getting coordinates from addresses) and secondly to validate addresses. I think that my only option is to query Nomitatim and compare results from address details with those I have specified in query.

One additional question: I'm quite new to OpenStreetMaps and Nominatim, so I don't know where I can report errors regarding postalcodes. I'll be grateful if You could point me to correct place.
