### ISSUE TITLE
No results, when using REST-API with city, street parameters instead of q parameter

### ISSUE THREAD

**Issue by Wackanabel** [openstreetmap/Nominatim#832]
The following search request returns no result:

http://nominatim.openstreetmap.org/search?format=json&street=4+Am+Bach&city=Bielefeld&country=DE&postalcode=33602&limit=50&format=json

I think one result should be returned. I'm facing the same problem for a lot of different addresses. A few days before everything was fine with these results.

When I use the search on https://nominatim.openstreetmap.org/ ("33602 Bielefeld, Am Bach 4") one result is returned. Also the following request returns one result:

http://nominatim.openstreetmap.org/search?format=json&q=33602+Bielefeld%2C+Am+Bach+4&limit=50&format=json

**Comment by Wackanabel** [comment]
Never experienced such a fast feedback! Thank you very much!!

**Comment by lonvia** [comment]
Your welcome. :) The fix is now live on nominatim.openstreetmap.org.
