### ISSUE TITLE
Wrong/Missing County on different Zoom levels on reverse search in addressparts (json/xml)

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#833]
County Correct
https://nominatim.openstreetmap.org/reverse.php?lat=50.68315&lon=12.09996&zoom=09&format=xml
County Wrong
https://nominatim.openstreetmap.org/reverse.php?lat=50.68315&lon=12.09996&zoom=10&format=xml

everything fine on result
everything fine on html

https://nominatim.openstreetmap.org/reverse.php?lat=50.6648353&lon=14.6294255815753&zoom=09&format=xml
https://nominatim.openstreetmap.org/reverse.php?lat=50.6648353&lon=14.6294255815753&zoom=10&format=xml

**Comment by lonvia** [comment]
Have you considered that maybe Nominatim is not the right geocoder for you? There are OSM-based alternatives, for example OsmNames, Carmen and Pelias. How about you given them a try?

**Comment by InI4** [comment]
@lonvia for one, we've been testing various services before chosing Nominatim and then it looked, like it performed well and offered good quality. 

The other point is, we've set up our project around nominatim in various aspects and also now allready have a running data structure based on what we got from Nominatim during last year. To be honest the inconsistency looks kind of simple, when you get the string and the html right, I have no idea how it can be, that the xml is unfixable wrong?

**Comment by Megachip** [comment]
@lonvia thanks for the tips, but seems not useable.
Can't find reverse search on osmNames, can't even find carmen ~~and mapzen (pelias) seems to use the same code like nominatim, cause I've got the same wrong results.~~

Looks like something was changed in results? In India Zoom level >09 didn't give any result anymore :/
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=19.90751&lon=86.150665&zoom=09&format=xml
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=19.90751&lon=86.150665&zoom=10&format=xml

**Comment by Megachip** [comment]
The other thing, in the region Am Mellensee (rel. 176780) everything was fine for one year and now (not sure, possible since a month or less) something gone wrong (like in the example). Checked the relations and nodes and can't see any sufficient changes.

**Comment by lonvia** [comment]
This behaviour is as expected, see also [Nominatim FAQ](http://nominatim.org/faq#address-and-zoom) and the comments in #764.

I'm sorry if Nominatim did not turn out as expected during your evaluation and that you are now stuck with it. But spamming this issue tracker with dozens of duplicates of what is essentially the same issue will achieve nothing other than drain the motivation of the developers. If you believe that the data was better a year ago, I recommend that you get a OSM planet from that time and a Nominatim 2.4 and install that on your own servers. That should get you back to the state where you were. However, I have to warn you. The basic algorithms behind the issues you are reporting haven't changed in the last 5 years, so the improvement may be limited.

**Comment by Megachip** [comment]
@lonvia thats not my intention. But when I'm adding the bugs to (in my option the same issue), you or mtmail (or lnl4) tells me, I should do a separate ticket ... and if I do make separate tickets, you told me not to do that. 

My intention is just to help to improve nominatim and help to find/squeeze bugs. 

If the data, nominatim gives is wrong, it should not the solution to tell the user that he should use an older version where data was right. It should be the target to prevent nominatim to provide wrong data. (just my honestly opinion)

P.S. The FAQ tells me "There is a common misconception" ... so, is there a plan to fix the conception?

For Am Mellensee... It's hard to understand, why nominatim acts different on same data structures... 
Examples:
https://nominatim.openstreetmap.org/reverse.php?lat=52.1415496&lon=13.3650454&zoom=14
https://nominatim.openstreetmap.org/reverse.php?lat=52.1415496&lon=13.3650454&zoom=13

https://nominatim.openstreetmap.org/reverse.php?lat=52.16793015&lon=13.366652980083&zoom=14
https://nominatim.openstreetmap.org/reverse.php?lat=52.16793015&lon=13.366652980083&zoom=13

And, as some others mentioned: why is the html output of the same request correct while xml/json is wrong.
