### ISSUE TITLE
unable to geocode valid location

### ISSUE THREAD

**Issue by simon1tan** [openstreetmap/Nominatim#836]
Using node-geocoder, tried to geocode '990 Palm Street, San Luis Obispo, CA' and it returned with just the street, says streetNum undefined. At first, I thought something was wrong with node-geocoder but punching the same address into the nominatim website also fails. Across the street is 995 Palm and that works fine. Funny thing is, this was the first address I used and already 100% failure rate. What are the odds of that? Apparently very high.

**Comment by lonvia** [comment]
This is a data error, not an error with Nominatim. http://www.openstreetmap.org/way/45596746 should have a tag `addr:street` instead of `addr:street:name`. Imports...
