### ISSUE TITLE
Searching for New York City by parameter does not find city

### ISSUE THREAD

**Issue by docfresh** [openstreetmap/Nominatim#837]
Querying the API like this

http://nominatim.openstreetmap.org/search?city=New+York&state=New+York&countrycodes=US&limit=1&format=json

Does not return New York City.  However, querying it by the debug front end does return it:

http://nominatim.openstreetmap.org/search.php?q=New+York&polygon_geojson=1&viewbox=

**Comment by lonvia** [comment]
Duplicate of #774.
