### ISSUE TITLE
In some cases in India Zoom level >09 didn't give any result anymore :/

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#838]
Examples:
https://nominatim.openstreetmap.org/reverse.php?lat=19.90751&lon=86.150665&zoom=09&format=xml
https://nominatim.openstreetmap.org/reverse.php?lat=19.90751&lon=86.150665&zoom=10&format=xml

https://nominatim.openstreetmap.org/reverse.php?lat=19.912675&lon=86.153412&zoom=09&format=xml
https://nominatim.openstreetmap.org/reverse.php?lat=19.912675&lon=86.153412&zoom=10&format=xml

**Comment by Megachip** [comment]
Cause it's also happens between zoom level 9 and 10, it's possible belongs to #833 
But in this issue it format independent

**Comment by mtmail** [comment]
Zoom level 10 is city and higher (county, state etc), see the dropdown field on http://nominatim.openstreetmap.org/reverse.php?lat=20.00000&lon=0.00000&zoom=2&format=html

So for those Indian coordinates Nominatim looks for a county type result at least for level 9 (found) and city type result on level 10 (not found). I don't see a city nearby so the search coordinates so it looks like returning no results here is fine.

https://www.openstreetmap.org/node/481077178 doesn't have city boundaries (polygon, relation) defined so it's always a bit of guesswork how big the city is. If you have local knowledge you can add such a boundary.

**Comment by Megachip** [comment]
@mtmail so in this case, it is not an issue of nominatim, it's just the missing data on OSM!?

**Comment by mtmail** [comment]
Kind of. The search logic starts a the search position and if nothing gets founds (zoom=20 looks for a house number, zoom=10 for a city) then it slowly increases the search radius and tries again. After a couple of steps it needs to stop for the results not to become irrelevant to the search. Examples are searches in the middle of oceans or remote areas.

In this case the city (center point, node) is too far away. Looks like 10km. The search position 2km closer to the city seems to find the city
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=19.898471023853403&lon=86.13186836242677&zoom=10

If the city had the boundaries of the city limits (polygon) set then it might make the cut to be included. So it's not missing OSM data, just data that could be extended/improved. The street the search position is on doesn't have a name either for example (not relevant for zoom=9 or 10).

**Comment by lonvia** [comment]
It's some bug in PlaceLookup likely from the latest refactoring. If you look at the debug output you'll see that it looses the result along the way. It shouldn't be doing that.
