### ISSUE TITLE
Hyphenated housenumber are not always found

### ISSUE THREAD

**Issue by moltamas93** [openstreetmap/Nominatim#845]
Address don't always seem to be found in photon if it spans multiple housenumber with a hyphen. It seems that only addresses with name are found, plain housenumbers are not found. Nominatim seems to find all addresses regardless.

Not found by photon: József utca 48-50
http://nominatim.openstreetmap.org/search.php?q=Budapest+J%C3%B3zsef+utca+48-50
http://photon.komoot.de/api/?q=Budapest+J%C3%B3zsef+utca+48-50

Found by photon: Budapest Kazinczy utca 23-27
http://nominatim.openstreetmap.org/search.php?q=Budapest+Kazinczy+utca+23-27
http://photon.komoot.de/api/?q=Budapest+Kazinczy+utca+23-27

**Comment by lonvia** [comment]
This is a bug tracker for Nominatim. Please use the [photon issue tracker](https://github.com/komoot/photon/issues/) with issues with photon.
