### ISSUE TITLE
Inconsistent address detection

### ISSUE THREAD

**Issue by dhnguyen92** [openstreetmap/Nominatim#846]
Hi,

I have some problem with address detection/completion of Nominatim.

My input address is "langemarckstraße 272, essen, 45309, Germany", and the output is None.

If I remove the zip code and country: "langemarckstraße 272, essen", I get the correct output address which is "272, Langemarckstraße, Schonnebeck, Stadtbezirk VI, Essen, Regierungsbezirk Düsseldorf, North Rhine-Westphalia, 45309, Germany".

And if I set the input address to "272, Langemarckstraße, Schonnebeck, Stadtbezirk VI, Essen, Regierungsbezirk Düsseldorf, North Rhine-Westphalia, 45309, Germany" again, the output is None.

You can check this on http://map.project-osrm.org

I also found some other address which have the same problem.

**Comment by lonvia** [comment]
The introduction of postcode terms resulted in too many permutations of query segmentations. I've added a [temporary hack](http://git.osm.org/nominatim.git/commitdiff/63f53be) for osm.org which gives preference to special terms (postcode, country, housenumber) over normal address parts. It solves this particular problem but let's see if that causes issues with other stuff.

**Comment by lonvia** [comment]
Preference added as a permanent solution now.
