### ISSUE TITLE
Searching "City, State" returns results ahead of the city itself

### ISSUE THREAD

**Issue by skylerbunny** [openstreetmap/Nominatim#847]
I think Nominatim wants to assume that if I search for a "City, State" string, that the first thing it should return is the place node for the populated place in question. However, depending upon whether I abbreviate the state, this does not happen:

"Sutherland Springs, Texas" returns the hamlet by that name first, which is what I would expect.

However...

"Sutherland Springs, TX" returns a series of unnamed primary roads which contain "TX" (not case sensitive) in their refs. For example, https://nominatim.openstreetmap.org/details.php?place_id=131960111

I don't know Nominatim's code deeply enough to know if "TX 87;TX 97" is intended to be a valid part of a Nominatim reverse geocoded address (which may itself be a bug or be leading TO this bug). You can see that hit by searching for "29.2469899,-98.022931".

In any event, I would assume that whether I search for "Sutherland Springs, Texas" or "Sutherland Springs, TX" that I'm supposed to get the same first hit: https://www.openstreetmap.org/node/151370016

**Comment by lonvia** [comment]
Interesting. That is actually an unintended side-effect of the tentative fix for #846. Giving address terms a higher penalty has given searches with partial matches (i.e. 'TX' in 'TX 97') an unintended boost. I've given partial terms in the name now the same penalty as address terms. That helps with the particular example. Let's see how it does otherwise.

**Comment by skylerbunny** [comment]
I seem to get an interesting reversal of this phenomena, as evidenced in trying to download things in Overpass Turbo's wizard. (This is as of 11/27, trying it today.)

type:way and waterway=* in "Grant County, Wisconsin" <- returns nothing.
type:way and waterway=* in "Grant County, WI" <- Returns what I would expect, waterways in that county.

**Comment by lonvia** [comment]
The Wisconsin example seems to work for me.

**Comment by lonvia** [comment]
No further issues have popped up. I have merge the change with the penalty in b94229fb8eeb75cd7799b80539c2d4b525f43442.
