### ISSUE TITLE
setup.php references missing address column in placex table

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#850]
In the step `calculate-postcodes` the SQL contains an `address` hstore column.
https://github.com/openstreetmap/Nominatim/blob/master/utils/setup.php#L512

I don't see such a column in the `placex` table.https://github.com/openstreetmap/Nominatim/blob/master/sql/tables.sql

 There is one in the `location_property_osmline` table. At this step in the setup the `location_property_osmline` table is still empty though.

**Comment by lonvia** [comment]
The address column is inherited from place through
 
```
   LIKE place INCLUDING CONSTRAINTS,
```

If you don't find it in your database then you are likely using an outdated osm2pgsql.

**Comment by mtmail** [comment]
That was it! I messed up my private fork pointing to an old submodule version. Thanks you so much!
