### ISSUE TITLE
placex table schema repeats column

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#851]
https://github.com/openstreetmap/Nominatim/blob/master/sql/tables.sql

```sql
CREATE TABLE placex (
  place_id BIGINT NOT NULL,
  parent_place_id BIGINT,
  linked_place_id BIGINT,
  importance FLOAT,
  indexed_date TIMESTAMP,
  geometry_sector INTEGER,
  rank_address SMALLINT,
  rank_search SMALLINT,
  partition SMALLINT,
  indexed_status SMALLINT,
  LIKE place INCLUDING CONSTRAINTS,
  wikipedia TEXT, -- calculated wikipedia article name (language:title)
  country_code varchar(2),
  housenumber TEXT,
  postcode TEXT,
  centroid GEOMETRY(Geometry, 4326)
) {ts:search-data};
```

`utils/setup.php` returns the error
```
NOTICE:  table "place_addressline" does not exist, skipping
NOTICE:  table "placex" does not exist, skipping
ERROR:  column "housenumber" specified more than once  <----
ERROR:  relation "placex" does not exist
```
in Postgresql 9.5, Ubuntu 16 LTE.

After removing the lines
```sql
  country_code varchar(2),
  housenumber TEXT,
  postcode TEXT,
```
it works.

I checked the `CREATE TABLE ... LIKE ...` documentation and can't tell if that's a bug in the syntax and if Postgresql is supposed to handle duplicate column names in this case.

**Comment by lonvia** [comment]
Neither of these columns are present in `place` anymore. Are you using an outdated version of osm2pgsql?

**Comment by mtmail** [comment]
That was it! I messed up my private fork pointing to an old submodule version. Thanks you so much!
