### ISSUE TITLE
Address miss state in api resp reverse by id

### ISSUE THREAD

**Issue by nozerov** [openstreetmap/Nominatim#852]
Hello,
making this api call
http://nominatim.openstreetmap.org/reverse?format=jsonv2&osm_type=N&osm_id=289558781&addressdetails=1
Im getting correct display name:
"display_name":"Phillip Island, Norfolk Island, Australia" (with state which is Norfolk Island)
but address array is not correct:
"address":{"island":"Phillip Island","country":"Australia","country_code":"au"} (no state in array)

is there a way to work around such issues?

**Comment by lonvia** [comment]
This is a data error. http://www.openstreetmap.org/node/424311679 has a place=country tag for Norfolk Island and that means that it competes with Australia for the address list and looses. (The display name is computed in a slightly different manner and allows two entities of the same level when they have a different name.) Change the node to place=state and the address list should fix itself.
