### ISSUE TITLE
Nominatim isn't updating districts in Telangana, India

### ISSUE THREAD

**Issue by adivik2000** [openstreetmap/Nominatim#853]
Previous 10 districts in the state of Telangana, India got split into 31 new districts. As @lonvia had mentioned in irc, as the area is now shrunk and divided, nominatim is rejecting the updated boundaries. Needs a manual db update.

Here's a list of all the new districts and relations(in the Parent of - Administrative section) -> https://nominatim.openstreetmap.org/details.php?place_id=178876735

**Comment by lonvia** [comment]
I hope I got them all. The following relations were affected:

* https://www.openstreetmap.org/relation/2022179
* https://www.openstreetmap.org/relation/7255986
* https://www.openstreetmap.org/relation/2022180
* https://www.openstreetmap.org/relation/2022134
* https://www.openstreetmap.org/relation/7699117
* https://www.openstreetmap.org/relation/2022227
* https://www.openstreetmap.org/relation/2022181

@adivik2000 Could you please recheck that all districts are now correct?

For those who want to update their own installation, fixing those in the database is unfortunately not easy. For each relation find out the place id. Now stop updates, then issue the following SQL to get rid of the old relations: `SELECT place_force_delete(<place_id>)`. Now you can reimport the new relations from the command line with the following command: `./utils/update.php --import-relation <osm id>`. Restart updates.

**Comment by adivik2000** [comment]
@lonvia Erm. The updated relations have now gone missing on Nominatim now. Also, returns a bad request. Ex. For the relation Warangal Urban on OSM (https://www.openstreetmap.org/relation/2022181), its Nominatim page https://nominatim.openstreetmap.org/details.php?place_id=179587232 shows an unknown place id

**Comment by lonvia** [comment]
Bother. I tested with one relation and that worked fine. And then I did the rest in a batch, which didn't work at all.  Tried again and it looks better now. Note that all relations have received a new place ID. That is normal because they were reimported from scratch.

For database admins: it looks like you need to reindex the database after deleting the old relations.

**Comment by adivik2000** [comment]
All good now. Thanks @lonvia . Do close the issue. :)
