### ISSUE TITLE
Broken polygon list only shows one entry

### ISSUE THREAD

**Issue by lonvia** [openstreetmap/Nominatim#854]
The list of broken polygons at the [`/polygons.php`](http://nominatim.openstreetmap.org/polygons.php) endpoint only shows the first entry even though it reports that there are around 20 broken polygons.

**Comment by mtmail** [comment]
Setting the `days` parameter displays 12 http://nominatim.openstreetmap.org/polygons.php?days=9999

The table skips duplicates
```
    if (isset($aSeen[$aRow['type'].$aRow['id']])) continue;
    $aSeen[$aRow['type'].$aRow['id']] = 1;
```
so that might explain the remaining missing 8.

**Comment by lonvia** [comment]
So the default for `days` is wrong. I would expect the default to be to show as many results as possible. I will implement that.
