### ISSUE TITLE
Calculated postal codes

### ISSUE THREAD

**Issue by maxerickson** [openstreetmap/Nominatim#855]
The issue came up on the US mailing list:

https://lists.openstreetmap.org/pipermail/talk-us/2017-November/018140.html

There was some missing data, no "POI" style tag on http://www.openstreetmap.org/node/4965058619 and now the current Nominatim results make sense.

Having not looked into the code, I expect the node was treated as a postcode because of the addr: tags, but not having a housename or housenumber.

I wonder if the calculation should account for incomplete POIs (checking tags like name, website)?

**Comment by lonvia** [comment]
This is correct behaviour. As there are generally no postcode boundaries in OSM, Nominatim computes postcode centroids from all addr:postcode it can find in the database.  Any places that do not have a postcode themselves (or are in an administrative area that has a postcode, which will be inherited) get the postcode assigned from the closest computed centroid.

So whatever changed to make the postcode of Coolidge Corner right again, it was not the change to the node you mention.

**Comment by maxerickson** [comment]
Aggregating across the available post codes makes sense. Here's a couple additional results where I don't think promoting the OSM node to place:postcode makes sense:

http://nominatim.openstreetmap.org/details.php?place_id=60153572

https://nominatim.openstreetmap.org/details.php?place_id=222442183

Or is "promoting the OSM node to place:postcode" just not a good understanding of where the results are coming from?

**Comment by lonvia** [comment]
I don't understand what your problem is. Are the postcodes wrong on these nodes? Then delete or fix the addr:postcode tag. If there are correct, there should not be a problem to take them into account when guessing missing postcodes for objects around.
