### ISSUE TITLE
failure to resolve "One Market Place"

### ISSUE THREAD

**Issue by RichMorin** [openstreetmap/Nominatim#856]
The "Manchester Grand Hyatt San Diego" is located at "1 Market Place".  However, some web pages (eg, https://www.hyatt.com/content/dlp/en/sandiego/hotels.html) list it as being at "One Market Place", which Nominatim fails to resolve. I believe this to be an instance of a more general problem in handling spelled-out numbers in addresses.

-r

**Comment by lonvia** [comment]
Duplicate of #173.
