### ISSUE TITLE
city polygon by osm id

### ISSUE THREAD

**Issue by martinmakesitwork** [openstreetmap/Nominatim#857]
How can i get the same result as this, by using just the osm id:
http://nominatim.openstreetmap.org/search/de/sachsen/chemnitz?format=json&polygon=1&addressdetails=1

If i try this the polygon is missing:
http://nominatim.osm.org/reverse?osm_type=N&osm_id=20830918&format=json&polygon=1&addressdetails=1

Even this just brings up the center coordinates but not the whole polygon of the city:
http://nominatim.osm.org/reverse?osm_type=N&osm_id=20830918&format=json&polygon_geojson=1&addressdetails=1

**Comment by mtmail** [comment]
The `&polygon=1` is deprecated (https://wiki.openstreetmap.org/wiki/Nominatim) so when we added the feature to the reverse search you have to use the more specific parameters

http://nominatim.osm.org/reverse?osm_type=R&osm_id=387687&format=json&polygon_geojson=1&addressdetails=1

or `polygon_text=1`

**Comment by martinmakesitwork** [comment]
Thank you for the fast answer. I have a new insight as well. The following link works exacly how ive expected.
http://nominatim.osm.org/reverse?osm_type=R&osm_id=62594&format=json&polygon_geojson=1

And now i can formulate my actual problem. I need to transform my osm_id´s of the type node to such ones of relation. How can i achieve this?
