### ISSUE TITLE
get osm_id (type relation) by using osm_id (type node)

### ISSUE THREAD

**Issue by martinmakesitwork** [openstreetmap/Nominatim#858]
How can i get the osm_id (type relation) by using osm_id (type node) of a city or village?

osm_id (**type relation**): http://nominatim.osm.org/reverse?osm_type=R&osm_id=62594&format=json&polygon_geojson=1
osm_id (**type node**): http://nominatim.osm.org/reverse?osm_type=N&osm_id=20830918&format=json&polygon_geojson=1

**Comment by martinmakesitwork** [comment]
![hmm](https://user-images.githubusercontent.com/19605697/33336812-6ca6aa2c-d471-11e7-852e-c805b7742a99.PNG)

...ok, it seems like the information is somewhere. But how can i query is through an api?

**Comment by mtmail** [comment]
In the OSM data the relation, e.g. http://www.openstreetmap.org/relation/191645 can have a member pointing to a node, in this case http://www.openstreetmap.org/node/240076989

Have a look at the XML http://www.openstreetmap.org/api/0.6/relation/191645 `<member type="node" ref="240076989" role="label"/>` With Chemnitz it's `admin_centre`.

While Nominatim internally uses database fields to look up a relation from a node that is not exposed by an API endpoint. In fact node and relation often represent the same place and Nominatim tries to only return one.

You'd have to generate a mapping using other OSM tools. Might be a question for https://help.openstreetmap.org/

**Comment by martinmakesitwork** [comment]
Thank you a lot for your great insights.

**Comment by martinmakesitwork** [comment]
This is the way how i can achieve it:

http://www.openstreetmap.org/api/0.6/node/240076989/relations

By just appending "relations" to my first link.

**Comment by mtmail** [comment]
Awesome, didn't know that.
