### ISSUE TITLE
linked_place_id not included in export

### ISSUE THREAD

**Issue by JonathanMontane** [openstreetmap/Nominatim#864]
Is there a way to add linked places relationships to the export?

From what I gathered, `linked_place_id` seems to be used to link a `place` to a `boundary`. I may have missed something but this does not seem to be included in Nominatim exports, leaving many `place` features as orphans with no relationships.

For instance, here is the city of New York as a `place`:
```xml
  <feature place_id="242548" type="N" id="61785451" key="place" value="city" rank="16" importance="16" parent_place_id="" parent_type="" parent_id="">
   <names>
    <name type="alt_name">New York City</name>
    <name type="name">New York</name>
    ...
    <name type="official_name">New York City</name>
    <name type="short_name">NYC</name>
   </names>
   <adminLevel>15</adminLevel>
   <countryCode>US</countryCode>
   <tags>
    <tag type="population">8550405</tag>
    <tag type="website">http://www.nyc.gov</tag>
    <tag type="wikipedia">en:New York City</tag>
   </tags>
   <osmGeometry>POINT(-73.9865812 40.7305991)</osmGeometry>
  </feature>
```
It has no parent, and no address. Yet, when looking at the database directly, we can see that this feature has a `linked` relationship to the OSM object `relation 175905`, which itself has a parent (New York State).

This was tested with both Nominatim 2.4.0 and Nominatim 3.0.1. The export command I ran is
```sh
nominatim -e -F "/mnt/data/new-york-latest.osm.pbf.xml"
```

Did I miss something? Is there a command line argument I am not aware of? Thanks.

**Comment by mtmail** [comment]
You're running the right command. It's a rarely used feature, not needed for any typical operation of the geocoder. I almost forgot it exists.

The code hasn't been touched in 6 years. https://github.com/openstreetmap/Nominatim/blob/master/nominatim/export.c, entirely possible that the `linked_place` database column didn't even exist back then.

Looks like there's a couple of SQL queries and later the fields are read by position (`13` here) and printed
```c
    xmlTextWriterWriteAttribute(writer, BAD_CAST "parent_id", BAD_CAST PQgetvalue(querySet.res, 0, 13));
```
so adding another field seems straight forward. `cmake` and `make` for compiling the code. There's no C tests for the binary other than feature tests for the import.

A pull request would be nice. At the same time I think you're the first person to report anything related to the export feature in years.

Personally for my projects I create SQL queries like
```SQL
SELECT row_to_json(t) FROM (
  SELECT place_id, hstore(name) AS names, ST_AsText(geometry) AS geometry, ... FROM placex WHERE ...
) t
```
and then run `/bin/cat the_query.sql | psql -A -t nominatim > output.jsonl` (http://jsonlines.org/)

**Comment by lonvia** [comment]
I 'm not sure we should resurrect the export feature. As @mtmail says, it is much easier to directly dump data from the database. And if we updated it, it would be a good idea to move away from xml and towards a more suitable format like geojson. But somebody would have to convince me first that the export is really useful. @JonathanMontane, may I ask what you use the export function for?

**Comment by raphi** [comment]
Thanks @mtmail ! Indeed we will migrate to querying the DB directly at some point but for now we still use this export a lot. That being said, I still think an export feature does makes sense since all the processing you do on OSM data is valuable itself. Ok we will open a PR with the fix next week.

@lonvia we are using Nominatim in [Algolia Places](https://community.algolia.com/places/) mostly as a pre-processor.
