### ISSUE TITLE
Different geocoding with same query, between online site and local

### ISSUE THREAD

**Issue by GFCGitHum** [openstreetmap/Nominatim#869]
Online:
http://nominatim.openstreetmap.org/reverse.php?format=json&lat=44.48641&lon=11.34532&zoom=18
Result:
```js
{
  "place_id": "18491940",
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
  "osm_type": "node",
  "osm_id": "1704538428",
  "lat": "44.4863541",
  "lon": "11.3454138",
  "display_name": "11, Viale dodici Giugno, Santo Stefano, Bologna, BO, Emilia-Romagna, 40124, Italia",
  "address": {
    "house_number": "11",
    "road": "Viale dodici Giugno",
    "suburb": "Santo Stefano",
    "city": "Bologna",
    "county": "BO",
    "state": "Emilia-Romagna",
    "postcode": "40124",
    "country": "Italia",
    "country_code": "it"
  },
  "boundingbox": [
    "44.4862541",
    "44.4864541",
    "11.3453138",
    "11.3455138"
  ]
}
```

Local Nominatim 3.0.1 Map Italy from GeoFabrik with updates:
http://192.168.20.45/nominatim/reverse.php?format=json&lat=44.48641&lon=11.34532&zoom=18
Result without HouseNumber:
```js
{
  "place_id": "5020659",
  "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
  "osm_type": "way",
  "osm_id": "132262802",
  "lat": "44.4862325",
  "lon": "11.3458722",
  "display_name": "Viale dodici Giugno, Santo Stefano, Bologna, BO, Emilia-Romagna, 40124, Italia",
  "address": {
    "road": "Viale dodici Giugno",
    "suburb": "Santo Stefano",
    "city": "Bologna",
    "county": "BO",
    "state": "Emilia-Romagna",
    "postcode": "40124",
    "country": "Italia",
    "country_code": "it"
  },
  "boundingbox": [
    "44.4857658",
    "44.4870114",
    "11.3447494",
    "11.3471325"
  ]
}```

Thanks for help

**Comment by mtmail** [comment]
just adding for information
- updated GFCGitHum's comment with json markdown styling
- Search point is the red dot
![image](https://user-images.githubusercontent.com/3727288/34213911-0224ac1c-e5a1-11e7-9be4-5ae070ec9bc5.png) http://nominatim.openstreetmap.org/reverse.php?format=html&lat=44.48641&lon=11.34532&zoom=18
- house number node hasn't been changed in 2 years
- street last changed two months ago, that was correcting the position of nodes on the northern part http://osmhv.openstreetmap.de/changeset.jsp?id=53237563 and renaming `Viale XII Giugno` => `Viale dodici Giugno`

**Comment by GFCGitHum** [comment]
Hi mtmail thanks for reply. This is my html:

![immagine](https://user-images.githubusercontent.com/33733335/34214638-57f0e9f6-e5a3-11e7-8720-9f59c3fb84cc.jpg)

I made a query on the Nominatim DB table placex for this osm_id and i found only rank 26.
My map is http://download.geofabrik.de/europe/italy-latest.osm.pbf 
You use Geofabrick?
 
rank_address	rank_search	partition	indexed_status	osm_id	osm_type	class	type	name	admin_level	address	extratags	wikipedia	country_code
26	26	28	0	132262802	W	highway	residential	"name"=>"Viale dodici Giugno"	15		"lanes"=>"2", "oneway"=>"yes"		it

Thanks
Franco

**Comment by lonvia** [comment]
nominatim.osm.org runs a completely different version (latest master from here) of Nominatim on a different version of the OSM data. There are bound to be differences between the results.

To get to the bottom of the problem you should first check if the house number is in your database. You can do that for example with the query: http://192.168.20.45/nominatim/reverse.php?osm_type=N&osm_id=1704538428

If you cannot find the house number object, something has gone wrong with your import. If it is there, then the difference is likely due to the different Nominatim versions.

**Comment by GFCGitHum** [comment]
Hi lonvia,

thanks for your help, result is:

http://192.168.20.45/nominatim/reverse.php?osm_type=N&osm_id=1704538428 

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<reversegeocode timestamp="Wed, 20 Dec 17 22:25:08 +0100" attribution="Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright" querystring="osm_type=N&osm_id=1704538428">
<result place_id="432885" osm_type="node" osm_id="1704538428" lat="44.4863541" lon="11.3454138" boundingbox="44.4862541,44.4864541,11.3453138,11.3455138">Italia</result>
<addressparts>
<country>Italia</country>
<country_code>it</country_code>
</addressparts>
</reversegeocode>

Which version runs online? Where can I find it?

Thanks
Franco

**Comment by lonvia** [comment]
Your data is not properly indexed. Are you sure the import run through right to the end? Please check that the table `placex` has the index `idx_placex_rank_search`. If it does't have it run the following command to finish the import:

    ./utils/setup.php --index --create-search-indices --create-country-names

If the index is there only run `./utils/setup.php --index`.

**Comment by GFCGitHum** [comment]
Hi,

I have all index

![image](https://user-images.githubusercontent.com/33733335/34231524-b60a71ea-e5dc-11e7-9b64-b90312fca05a.png)

... I run yours commands, but you know the num. version online and the wiki for deploy it?

**Comment by lonvia** [comment]
nominatim.osm.org is pretty much exactly on the code from this repository. Installation instructions are [here](https://github.com/openstreetmap/Nominatim/blob/master/docs/Installation.md).

**Comment by GFCGitHum** [comment]
Hi,

thanks again for your help.
Your link is exactly what I use, but the website looks different.
Look at the red circles

Online:
![image](https://user-images.githubusercontent.com/33733335/34232513-dbb59164-e5e0-11e7-84cf-eb05a2e239c8.png)

Local:
![image](https://user-images.githubusercontent.com/33733335/34232610-683fd23e-e5e1-11e7-9841-9d4c7f58f959.png)
