### ISSUE TITLE
"ul." may be safely discarded from searches for Polish roads - (short for street in polish)

### ISSUE THREAD

**Issue by matkoniecz** [openstreetmap/Nominatim#87]
"Kraków, ul. Pędzichów 27" fails to find location, but "Kraków, Pędzichów 27" is successful.

**Comment by GaspardPO** [comment]
It seems to me that this problem was addressed and this issue can be closed.
And it also seems that it should be closed in favor of #298

**Comment by matkoniecz** [comment]
https://www.openstreetmap.org/search?query=Krak%C3%B3w%2C+ul.+P%C4%99dzich%C3%B3w+27#map=19/50.07202/19.93947 now works, so it is fixed

**Comment by kopciak** [comment]
@matkoniecz example does not work anymore, as well as other queries with "ul". There seems to be a regression.

**Comment by lonvia** [comment]
Looks like the Polish community has decided to completely get rid of street designations. Nominatim can go from 'ulica' to 'ul' but not from nothing to 'ul'. Might get better with #2944. But in the grand scheme of things the tagging is rather unfriendly to data users, so this will never work well.

**Comment by matkoniecz** [comment]
> Looks like the Polish community has decided to completely get rid of street designations.

I think we never had them. Polish community has some weird ideas about street names (expanding actual street name to full name of a person, irregardless of actual street name and "fixing" some "incorrect" street names, for example) but skipping "Ulica" matches general norms in Polish language and Polish cartography.

I checked for example https://www.openstreetmap.org/way/24216183/history that has versions dating back to 2008 and it never had "ulica" in name.

**Comment by matkoniecz** [comment]
> And it also seems that it should be closed in favor of https://github.com/osm-search/Nominatim/issues/298

that one seems specifically about ordinals

> https://www.openstreetmap.org/search?query=Krak%C3%B3w%2C+ul.+P%C4%99dzich%C3%B3w+27#map=19/50.07202/19.93947 now works, so it is fixed

Does not work anymore, so I would want to reopen.

But given 

> Might get better with https://github.com/osm-search/Nominatim/issues/2944. But in the grand scheme of things the tagging is rather unfriendly to data users, so this will never work well.

it seems that it would be closed anyway.

**Comment by lonvia** [comment]
> but skipping "Ulica" matches general norms in Polish language and Polish cartography.

And that's exactly the tagging error here. "name" should not contain the label of the street you want to see rendered in cartagrophy. It should contain it's name. Polish Wikipedia at least seems to think the name is 'Ulica Pędzichów', so I take it that the designation is part of the name, it is just normally omitted.

Nominatim could add a rule that expands every street name with a 'Ulica' in Poland. But first of all, I expect it would go wrong for all the streets which have a different designation ('Aleja Pokou' for example) and second, it only patches up the problem for one software. That's were I usually draw the line and say: this needs a better representation in the data.

**Comment by matkoniecz** [comment]
The problem is that "Pędzichów" is the common name, not "Ulica Pędzichów". In similar way, Manchester may be considered as having full name "City of Manchester" if Wikipedia is to be believed, but it will have `name=Manchester`

BTW, Nominatim also fails to find "City of Manchester".

It is not really a tagging for renderer.

> so I take it that the designation is part of the name, it is just normally omitted.

Yes, but it is omitted so typically that it is not part of the common name. Polish Wikipedia has its own share of using super-official naming forms. For example https://pl.wikipedia.org/wiki/Park_Krakowski_im._Marka_Grechuty is using `official_name` not the actually used name of https://www.openstreetmap.org/way/25506183

**Comment by lonvia** [comment]
It's simple really. Either "Pędzichów" is the only common name, then the complaint that "ul . Pędzichów" isn't found is mute. Or "Ulica Pędzichów" is the official name and should be found, then it should be added to OSM.

**Comment by matkoniecz** [comment]
The problem is that 

- "ul. Pędzichów" is sometimes used format
- street name is "Pędzichów"
- actually checking whether "Ulica Pędzichów" or "Pędzichów" is the official name is tricky at best and I failed to establish it
- in typical use "ulica" is typically omitted or treated as implied not as part of the name (also in orthography, for example in upcoming reform it will have special capitalisation rules, with say "Aleja 29 Listopada" but "ulica 29 Listopada" (see https://rjp.pan.pl/zmiany-pisowni ).

Though "Berlin city" or "city Berlin" and "street Pędzichów" is not being interpreted by Nominatim either, so maybe anyone geocoding Polish addresses with Nominatim should add this transform on its own and do not expect Nominatim to handle it?

Or maybe it is at least `alt_name` and we should add bunch of `alt_name` tags across Poland...

test case where it happens:

https://www.openstreetmap.org/search?query=PL%2C%20Schodnia%2C%20ul.%20Brzozowa%201#map=17/41.64220/-71.27670

https://www.openstreetmap.org/search?query=PL%2C%20Schodnia%2C%20Brzozowa%201#map=19/50.67688/18.19886

**Comment by lonvia** [comment]
Note that there is #2944 in the works. Once implemented, that should solve the problem.
