### ISSUE TITLE
Indexing  buildings that happen to be relations. 

### ISSUE THREAD

**Issue by hdrs** [openstreetmap/Nominatim#870]
I realise the "nominatim indexing relations" thing  has bounced around for a while, often on the subject of large and nebulous routes and such. 

I just improved the geometry of a middle school by adding the holes in the building outline, turning a way into a relation. It then dropped out of nominatim.  This seems to be a bit of a problem, the location is significant, has an unambiguous name and is well defined semantically. 

Here is the school

http://www.openstreetmap.org/relation/7831801#map=19/40.71311/-74.35959

Could nominatim be changed to index relations that happen to be building in addition to whatever else is done right now? 

  Thanks,
   S D

**Comment by mtmail** [comment]
In this case wouldn't the address belong to an area (way) `amenity=school` including buildings, parking, sport venues, while the building is just a `building=school` with or without an entrance node? https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dschool

I see the college (http://www.openstreetmap.org/way/284532252) and hospital (http://www.openstreetmap.org/way/288859416) in the same town is tagged like that.

**Comment by hdrs** [comment]
In this case that would work, yes, and i could make that chaange. 

But it is still the case that many named buildings might need name search despite  being a  relation.

**Comment by lonvia** [comment]
Nominatim can process multipolygon relations just like any other area. Your multipolygon is broken, see http://tools.geofabrik.de/osmi/?view=areas&lon=-74.35964&lat=40.71340&zoom=18&opacity=0.73 That is why it does not appear in the search.

**Comment by hdrs** [comment]
Oh, thanks for that Ionvia.  I will fix it and give it a try.

**Comment by lonvia** [comment]
Needed a bit of a kick on the server-side because changes to the way/nodes in the relation don't automatically trigger an update of the relation but it works now: http://nominatim.openstreetmap.org/details.php?osmtype=R&osmid=7831801
