### ISSUE TITLE
not searching

### ISSUE THREAD

**Issue by engragy** [openstreetmap/Nominatim#872]
hiii every one
I am trying to install nominatim using installation instructions for Ubuntu 16.04 (64 bit), i have used an extract from geofabrik.de for Egypt 
but after completing the installation when i visit the "localhost/nominatim" i see this site which i don't think is ok
![01](https://user-images.githubusercontent.com/33456164/34458537-a54f02ee-edde-11e7-815b-f7fa8e1b7c13.png)

even when i try to search for any thing the browser will head to something like `http://osm/search.php?q=maadi+street&polygon_geojson=1&viewbox=` and outputs Server not found

could you please help with this problem

**Comment by mtmail** [comment]
Looks like CONST_Website_BaseURL is not set.

Check the last section of http://nominatim.org/release-docs/latest/Install-on-Ubuntu-16 about the local.php configuration file.

**Comment by engragy** [comment]
the local.php file was created as i did review the instruction many times, but i added  `?>` at the end of the file an then it worked for me this wasn't in the instructions i think

can you please tell me how to make nominatim get tiles from my tile server

many thanks ...

**Comment by mtmail** [comment]
Look for @define('CONST_Map_Tile_URL', 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'); and related lines in https://github.com/openstreetmap/Nominatim/blob/master/settings/defaults.php Copy those lines to your local.php and change them to your needs

**Comment by fazlerabbi37** [comment]
I am reopenning this issue as I am facing the same problem in Ubuntu 16.04 LTS even after setting the ``CONST_Website_BaseURL`` to ``http://server_ip/nominatim``. At the Network option of Chrome's ispect element I can see that may css files are missing as it is trying to GET ``http://server_ip/nominatim/server_host_name/css/leaflet.css`` Which is suppose to be ``http://server_ip/nominatim/css/leaflet.css``
