### ISSUE TITLE
Import Issue connction postgreSQL

### ISSUE THREAD

**Issue by stoffl6781** [openstreetmap/Nominatim#876]
HI i have a problem with the first intial the file DACH 
Prozess `ubuntu@ip-172-31-38-206:~/Nominatim/build$     wget -O /home/ubuntu/Nominatim/data/country_osm_grid.sql.gz http://www.nominatim.org/data/country_grid.sql.gz`
and
`./utils/setup.php --osm-file ../../data/dach-latest.osm.pbf --all 2>&1 | tee setup.log`

after 1:50 h or else: 

```
2018-01-05 12:09:45 == Reanalysing database
NOTICE:  no non-null/empty features, unable to compute statistics
NOTICE:  no non-null/empty features, unable to compute statistics
Latest data imported from 2018-01-04T21:43:08Z.
2018-01-05 12:09:47 == Calculate Postcodes
2018-01-05 12:11:07 == Index ranks 0 - 4
nominatim version 3.0.1

Connection to database failed: FATAL:  sorry, too many clients already

ERROR: Error executing external command: /home/ubuntu/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 95 -R 4
Error executing external command: /home/ubuntu/Nominatim/build/nominatim/nominatim -i -d nominatim -P 5432 -t 95 -R 4
postgres@ip-172-31-22-117:~/Nominatim/build$ exit
```

what can i do? - can i update the databas without erase the Datbase nominatim? (2H for import) 

after this error, i think i can easy update the Database - with : 

> ./utils/update.php --init-updates
but this don't work for me: 
```
postgres@ip-172-31-22-117:~/Nominatim/build$ ./utils/update.php --init-updates
@define('CONST_Pyosmium_Binary', '/home/ubuntu/.local/bin/pyosmium-get-changes');

// base URL of the replication service
@define('CONST_Replication_Url', 'http://download.geofabrik.de/europe/dach-updates');
// How often upstream publishes diffs
@define('CONST_Replication_Update_Interval', '86400');
// How long to sleep if no update found yet
@define('CONST_Replication_Recheck_Interval', '900');
@define('CONST_Pyosmium_Binary', '/home/ubuntu/.local/bin/pyosmium-get-changes');

// base URL of the replication service
@define('CONST_Replication_Url', 'http://download.geofabrik.de/europe/dach-updates');
// How often upstream publishes diffs
@define('CONST_Replication_Update_Interval', '86400');
// How long to sleep if no update found yet
@define('CONST_Replication_Recheck_Interval', '900');
2018-01-05 12:43:28 == Create Functions
NOTICE:  drop cascades to function get_addressdata(bigint,integer)
NOTICE:  drop cascades to function get_wikipedia_match(hstore,character varying)
Summary of warnings:


2018-01-05 12:43:28 == Setup finished.
sh: 1: /nonexistent: not found
ERROR: Error running pyosmium tools
Error running pyosmium tools
```

i have install the pip with: 
```
sudo apt-get install python-pip
sudo apt-get install libboost-python-dev
```
```
ubuntu@ip-172-31-22-117:~/Nominatim/build$ pip install --user osmium
Requirement already satisfied: osmium in /home/ubuntu/.local/lib/python2.7/site-packages
```

I am grateful for any help
thank you

**Comment by lonvia** [comment]
### Regarding the import problem

Nominatim wants to use too many threads (95 threads, to be precise).  I would suggest to reduce the number of threads using the `--threads` option. You can continue the import at the point where it stopped with the following command:

    ./utils/setup.php --threads 32 --index --create-search-indices --create-country-names

Alternatively, you can increase the number of connections that Postgres allows. Look out for the option `max_connections` in your postgres configuration.

It would be interesting to know why Nominatim wants to use so many threads. What kind of CPUs does your system have?

### Regarding the update issue

It looks like you have a syntax error in your `settings/local.php`. My guess would be that you have forgotten to add the initial line which should be `<?php`. ( I admit that the documentation is not very clear. I'll have a look at that.)

**Comment by stoffl6781** [comment]
yes that work fine for us. 
how long dit the import running on a ahcine AWS 96Core, 398 GB RAM?

It ist the second day that it rund? - ist this normal? 

thank you

**Comment by lonvia** [comment]
No, that's not normal. As a rule of thumb, at the point where the import errored out you should be through one quarter to third of the import. So the remainder should not take longer than 6h for you. If it takes longer, than your postgres is likely not configured well. Have a look again at the [Postgres tuning section in the Installation manual](http://nominatim.org/release-docs/latest/Installation). You can cancel the import, adjust the postgres settings (don't forget to restart postgres) and then continue the import with the command above as long as you are still in the indexing phase (the one that prints something with `Rank XX ETA`).

**Comment by stoffl6781** [comment]
after i change some in the postgres.conf on a ubuntu amazon server, i cant log in to the console. I have erease the postgres and reinstall it - than it works. 

`could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432/.s.PGSQL.5432"?`

if i change with `nano` some letter in this file, i have problems with the login.

**Comment by lonvia** [comment]
Sorry but this is a Postgres issue, I can't help with those here.
