### ISSUE TITLE
make error error: unknown type name 'uint'; did you mean 'int'

### ISSUE THREAD

**Issue by xming4321** [openstreetmap/Nominatim#879]
[ 79%] Building CXX object nominatim/CMakeFiles/nominatim.dir/geometry.cpp.o
[ 81%] Building C object nominatim/CMakeFiles/nominatim.dir/import.c.o
[ 84%] Building C object nominatim/CMakeFiles/nominatim.dir/index.c.o
In file included from /Users/xming/project/work/service-nominatim/nominatim/index.c:18:
/Users/xming/project/work/service-nominatim/nominatim/index.h:17:5: error: unknown type name 'uint'; did you mean 'int'?
    uint table;
    ^~~~
    int
/Users/xming/project/work/service-nominatim/nominatim/index.c:441:5: error: use of undeclared identifier 'uint'; did you mean 'int'?
    uint        table;
    ^~~~
    int
/Users/xming/project/work/service-nominatim/nominatim/index.c:443:14: error: use of undeclared identifier 'uint'; did you mean 'int'?
    table = (uint)(thread_data->table);
             ^~~~
             int
/Users/xming/project/work/service-nominatim/nominatim/index.c:443:14: error: use of undeclared identifier 'lint'

**Comment by lonvia** [comment]
see CONTRIBUTING.md

**Comment by xming4321** [comment]
Nominatim version  Nominatim-3.0.0 

just make

os:mac os 10.13.1

**Comment by lonvia** [comment]
I´ve pushed a commit to master which may or may not fix the problem, I can't test it. Please note that MacOS is not officially supported, so you are largely on your own here. Feel free to suggest improvements that make it work on MacOS if you find some, However, there is little chance you'll get further help if you just dump error output without any explanation.

**Comment by b-oern** [comment]
Same Issue on esp32-2432S022C
