### ISSUE TITLE
countrycodes=FR should keep "Alpes" in the result set

### ISSUE THREAD

**Issue by drzraf** [openstreetmap/Nominatim#883]
When searching _Alpes_ with countrycodes=fr I would expect the "Alps" (the mountains, covering a significative portion of the french territory) to show up.
It seems that the relation has no country associated, *but* it actually covers France (and `is_in` = `Europe`) *and* wikidata [says](https://www.wikidata.org/wiki/Q1286?uselang=en-US) country=FR

* Request:
`https://nominatim.openstreetmap.org/search?format=json&limit=5&countrycodes=fr&polygon_geojson=0&accept-language=fr_FR&q=alpes`

* Expected:
https://www.openstreetmap.org/relation/2698607#map=7/46.006/10.818

* Actual:
French places with ~0 pertinence in the top5 results (eg: "Alpes" inside the name of streets)

**Comment by lonvia** [comment]
This is not fixable. Every place is assigned exactly one country. countrycodes restricts to that country. There are no guarantees what happens to objects that cross borders.

**Comment by drzraf** [comment]
> This is not fixable. Every place is assigned exactly one country.

so we are left with workaround, the only I can think of is duplicating the area using another country code ?
