### ISSUE TITLE
Errors during installation

### ISSUE THREAD

**Issue by edqallen** [openstreetmap/Nominatim#887]
Installing on Ubuntu 14 LTS w/ pg 9.3 according to the instructions here: https://wiki.openstreetmap.org/wiki/Nominatim/Installation there are some errors in the specialphrases_countries.sql SQL script output upon reaching the **Add special phrases** step.  The first script results in the error:

```
psql:data/specialphrases_countries.sql:1: ERROR:  syntax error at or near "@"
LINE 1: @define('CONST_Postgresql_Version', '9.3');
        ^
```

followed by two identical errors about the `@` symbol on different lines.

specialphrases.sql had the same three errors at the start.

**Comment by lonvia** [comment]
Check that you have `<?php` in the first line of your `settings/local.php`. Next one to report this owes me a beer.

**Comment by edqallen** [comment]
Sorry about that!  I feel like somewhere along the way, the install instructions told me to just put those two or three lines in the file and didn't mention the opening tag.  I thought it was weird at the time but figured maybe it was being used with `file_get_contents` + `eval` or something.

Anyway it sounds like I'm not alone in not creating that file incorrectly, so why not include an empty one that has the opening tag but nothing else?

**Comment by mtmail** [comment]
The Nominatim 3.x documentation is more clear http://nominatim.org/release-docs/latest/Install-on-Ubuntu-16 (bottom of page).

I think it was just a coincidence that 3 users had the same/similar issue with Nominatim 2.5 this month.
