### ISSUE TITLE
instead of roads, buildings are returned

### ISSUE THREAD

**Issue by stoffl6781** [openstreetmap/Nominatim#892]
HI,
Why do we get a building back on a query and not the node off the street?
reverse?lat=47.16259&lon=9.79599&format=jsonv2

this is a point on a higway and not on a building. 
We often have the same in cities or places. 

or is there a solution that only roads are evaluated? 
I have tryed witch osm_type=W or &dedupe=1 with the same result. 

https://screencast.com/t/84NP0uUwsV

thnak you

**Comment by mtmail** [comment]
You can set the `zoom` to 16 (street). See https://nominatim.openstreetmap.org/reverse.php?format=html&lat=47.16259&lon=9.79599&zoom=16 for example. The red circle is the search point, the blue circle the result.
