### ISSUE TITLE
Lavander Ct is misspelled

### ISSUE THREAD

**Issue by zmb5000** [openstreetmap/Nominatim#894]
https://nominatim.openstreetmap.org/details.php?place_id=67004910

Hi there!
The address attached to the link above is misspelled. Lavander is actually spelled Lavender. If there is anything you need me to do or validate, please let me know. Thank you!

**Comment by mtmail** [comment]
I see you edited the name already https://www.openstreetmap.org/changeset/55748094#map=19/28.54186/-81.28885 so there's nothing else to be done. The Nominatim search updates almost every minute with changes. Thanks!
