### ISSUE TITLE
Reverse Lookup, Intermediate Layers Mix into Address

### ISSUE THREAD

**Issue by InI4** [openstreetmap/Nominatim#895]
We really love Nominatim and especially use the reverse lookup from your server. However occasionally there is a glitch, that results include wrong intermediate address layers. We've seen this in several places over Europe, but to demonstrate look at the following request into Stockholm:

`http://nominatim.openstreetmap.org/reverse?format=json&lat=59.388479&lon=17.928314&zoom=17&accept-language=en&addressdetails=1&email=frank+nominatim@spieleck.de`

The resulting JSON looks like:

```
{
    "place_id": "76026549",
    "licence": "Data © OpenStreetMap contributors, ODbL 1.0. http://www.openstreetmap.org/copyright",
    "osm_type": "way",
    "osm_id": "27156753",
    "lat": "59.38808995",
    "lon": "17.9287281100575",
    "display_name": "Rinkeby Torg, Rinkeby-Kista stadsdelsområde, Stockholm, Landskapet Uppland, Stockholms län, Svealand, 16343, Sweden",
    "address": {
        "pedestrian": "Rinkeby Torg",
        "city_district": "Rinkeby-Kista stadsdelsområde",
        "county": "Stockholm",
        "state_district": "Landskapet Uppland",
        "state": "Stockholms län",
        "postcode": "16343",
        "country": "Sweden",
        "country_code": "se"
    },
    "boundingbox": [
        "59.3878469",
        "59.3883289",
        "17.9280629",
        "17.9293972"
    ]
}
```

What really hurts our automated processing is the `state_district` part: _Stockholm_ and _Landskapet Uppland_ are adjacent regions, but the above hierarchy implies, _Stockholm_ is nested below _Uppland_. Moreover in our samples it looked like whole _Stockholm_ is being split into two areas, each part placed hierarchically below the one of the two major adjacent regions. 

Is this immanent to the search method, or can this be fixed?

It looks a bit like `state_district` should simply be `empty/void/null` but might remain prefilled by some previous (?) match to the place to be reversed?! But I haven't yet looked at the code.

**Comment by mtmail** [comment]
The adjacent regions (provinces, `admin_level=4`) you mean are likely https://www.openstreetmap.org/relation/54220 and https://www.openstreetmap.org/relation/54391

I see a `boundary=historic` on "Landskapet Uppland" https://www.openstreetmap.org/relation/4108474, so does it even make sense to be part of the results?

**Comment by InI4** [comment]
Thanks, for looking into it @mtmail. You are right about the regions. IMHO the line
  `"state_district": "Landskapet Uppland", `
is useless and /or irritating at least as long as it is labeled as an existing boundary. I mean when it was labeled as being historic in some way, my client could get rid of it, but so I have just a split Stockholm.

**Comment by lonvia** [comment]
The relation should have disappeared from the address when it was retagged from `boundary=administrative` to `boundary=historic`. I suspect it didn't because the ranks are not recomputed when only the tags of a relation are changed. This would be a bug in Nominatim.

**Comment by InI4** [comment]
Hello, is there anything I can add to this case by now?

**Comment by InI4** [comment]
Nothing changed, why it is closed? Didn't you state that would be a bug in Nominatim?

**Comment by lonvia** [comment]
The bug in the updating process indeed has been fixed since February. It just happens that the production database wasn't able to sort itself out because the entry for this particular OSM object was messed up. Fixed manually now.

**Comment by InI4** [comment]
Whow cool, that was fast! I was only rechecking above test and was puzzled. Thank you!
