### ISSUE TITLE
Cannot update nominatim data

### ISSUE THREAD

**Issue by kechap** [openstreetmap/Nominatim#898]
Hello, I firstly posted this [here ](https://github.com/mediagis/nominatim-docker/issues/34) but the issue is actually related to nominatim and not the docker container. 

I am trying to update my nominatim data. The first import was done for europe. I tried running the following command. 
`sudo docker exec -it openstreetmaps_nominatim_1 sudo -u nominatim src/utils/update.php --import-osmosis-all`

The output is the following
> 
> 2018-01-29 09:21:09 Replication Delay is 21603559
> /usr/bin/osmosis --read-replication-interval workingDirectory=/app/src/settings --simplify-change --write-xml-change /app/src/data/osmosischange.osc
> Jan 29, 2018 9:21:09 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Osmosis Version 0.40.1
> Jan 29, 2018 9:21:09 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Preparing pipeline.
> Jan 29, 2018 9:21:09 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Launching pipeline execution.
> Jan 29, 2018 9:21:09 AM org.openstreetmap.osmosis.core.Osmosis run
> INFO: Pipeline executing, waiting for completion.
> Jan 29, 2018 9:21:09 AM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
> SEVERE: Thread for task 1-read-replication-interval failed
> org.openstreetmap.osmosis.core.OsmosisRuntimeException: Unable to read the state from the server.
>         at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:105)
>         at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:60)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.download(BaseReplicationDownloader.java:237)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:279)
>         at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:349)
>         at java.lang.Thread.run(Thread.java:745)
> Caused by: java.io.FileNotFoundException: http://download.geofabrik.de/europe-updates/000/001/528.state.txt
>         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1674)
>         at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:91)
>         ... 5 more

I think that it tries to find the file `http://download.geofabrik.de/europe-updates/000/001/528.state.txt`

which doesn't exist. Why am I getting this? Is there a way to fix it?

**Nominatim version: 2.5**
**Postgresql version: 9.3**
**Postgis version: 2.1**
**RAM/etc: irrelevant**

**Comment by mtmail** [comment]
I can only confirm that geofabrik.de doesn't keep the files any longer (looks like 3 months). A fresh import is the easiest approach now.

**Comment by kechap** [comment]
@mtmail The last import took 20 days to complete. Are you sure that this is my best option?

**Comment by lonvia** [comment]
If your initial import file was older than 3 months you are out of luck. There is also the distinct possibility that the state setup in Nominatim 2.5 is broken again. If so, this won't get fixed anymore as Nominatim 3.x with a better working mechanism has been out for half a year now. You might get away though with manually setting up the Osmosis state file. Consult the Osmosis documentation if you want to try.
