### ISSUE TITLE
When i configure and build Nominatim after use { make } . I get following Error ? How to resolve my issues 

### ISSUE THREAD

**Issue by balajiputhiran** [openstreetmap/Nominatim#903]
I followed by this URL for installation reference 👍

http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-16/

I got this error only past two weeks 

system:@ubuntu-085:/srv/nominatim/Nominatim-3.1.0/build$ make
[ 74%] Built target osm2pgsql_lib
Linking CXX executable osm2pgsql
/usr/bin/ld: libosm2pgsql.a(reprojection.cpp.o): undefined reference to symbol 'log@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libm.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [osm2pgsql/osm2pgsql] Error 1
make[1]: *** [osm2pgsql/CMakeFiles/osm2pgsql.dir/all] Error 2
make: *** [all] Error 2

What should i do ?. Evan i didn't idea about this what is my problem ?I hope you anyone help me

**Comment by mtmail** [comment]
First time I see this error and I've installed version 3.1 on three separate Ubuntu 16 servers recently.

Your best option forward is to check the requirements in https://github.com/openstreetmap/osm2pgsql/blob/master/README.md and try to compile osm2pgsql separately first.

**Comment by mtmail** [comment]
https://github.com/openstreetmap/Nominatim/issues/908 suggests compiling worked. Closing.
