### ISSUE TITLE
Bandwidth Error 429 Too many requests

### ISSUE THREAD

**Issue by Textras** [openstreetmap/Nominatim#906]
Hi there. Our distributed team is getting 429 errors on our reverse geo-code lookup on multiple browsers in multiple countries and even with old apk's. But the site seems to work. No matter where our call comes from, we keep being pointing to the 429 bandwidth error URL, but we are only over because we had a mishandled call that kept trying repeatedly on failure. That is now fixed. We have also never seen this before and have used it without change for well over a year and a half. 

The 429 error does not explain why our entire team is getting an error, so wondering if any ideas? Status wiki page looks good too. Thanks

https://wiki.openstreetmap.org/wiki/Platform_Status

$.getJSON('http://nominatim.openstreetmap.org/reverse?json_callback=?&format=json', {lat: lat, lon: lon}, function(data) {

**Comment by mtmail** [comment]
The server(s) automatically block (return HTTP 429) by high-number-of-requests per IP address for a couple of hours. The blocks are also removed automatically, so it maybe possible it's already removed by the time you read this. https://operations.osmfoundation.org/policies/nominatim/

**Comment by lonvia** [comment]
To add to that: the server is having trouble with abusive clients at the moment, so you might see more 429 responses than usual. We are aware of the situation and are busy trying to get the situation back to normal. If you make sure your queries include one of the following three items, 429 blocks are less likely: a) valid HTTP referrer, b) email parameter, c) non-stock HTTP user agent.
