### ISSUE TITLE
 When i run this command in my ubuntu PC ./utils/setup.php --osmosis-init ---- I got this error ? How to resolve this problem anyone help me 

### ISSUE THREAD

**Issue by balajiputhiran** [openstreetmap/Nominatim#908]
PHP Warning:  file_get_contents(http://www.openstreetmap.org/api/0.6/node/4944807321/1): failed to open stream: Connection timed out in /home/next/Nominatim-2.5.1/utils/setup.php on line 593
PHP Notice:  Undefined offset: 1 in /home/next/Nominatim-2.5.1/utils/setup.php on line 595
PHP Warning:  file_get_contents(http://planet.openstreetmap.org/replication/minute/?C=M;O=D;F=1): failed to open stream: Connection timed out in /home/next/Nominatim-2.5.1/utils/setup.php on line 599
ERROR: Cannot read state file directory.
Cannot read state file directory.

>

**Comment by mtmail** [comment]
There's a network connection problem between your computer and the target website.

**Comment by lonvia** [comment]
Please note that the diff setupin Nominatim 2.x, which causes the error above,  is known to be buggy and will not be fixed. Nominatim 3.x uses a much more reliable implementation. If you are installing a new database please only do so with the latest release.
