### ISSUE TITLE
&amp;(HTML Encode) is not supported

### ISSUE THREAD

**Issue by Jaysds1** [openstreetmap/Nominatim#913]
Original URL: https://nominatim.openstreetmap.org/reverse?format=json&lat=43.59343&lon=-79.64572
Result: 

> {"place_id":"79721647","licence":"Data © OpenStreetMap contributors, ODbL 1.0. http:\/\/www.openstreetmap.org\/copyright","osm_type":"way","osm_id":"35116372","lat":"43.5936012","lon":"-79.6460577","display_name":"City Centre Transit Terminal – Square One, 200, Rathburn Road West, City Centre, Erindale, Mississauga, Peel Region, Ontario, L5B 3C1, Canada","address":{"bus_station":"City Centre Transit Terminal – Square One","house_number":"200","road":"Rathburn Road West","neighbourhood":"City Centre","suburb":"Erindale","city":"Mississauga","county":"Peel Region","state":"Ontario","postcode":"L5B 3C1","country":"Canada","country_code":"ca"},"boundingbox":["43.5934005","43.5938019","-79.646351","-79.6457644"]}

HTML Encoded URL: https://nominatim.openstreetmap.org/reverse?format=json&amp;lat=43.59343&amp;lon=-79.64572
Result: 

> Bad Request
Nominatim has encountered an error with your request.
Details: Need coordinates or OSM object to lookup.
If you feel this error is incorrect feel file an issue on Github. Please include the error message above and the URL you used.

**Comment by lonvia** [comment]
What exactly are you reporting?

**Comment by Jaysds1** [comment]
A Search bug.

**Comment by lonvia** [comment]
URLs need URL encoding. If you HTML-encode an URL then the result is garbage and Nominatim tells you so. Nothing unusual here.

**Comment by Jaysds1** [comment]
But it's the fact that Nominatim doesn't decode it and I don't encode the URL on purpose, I just get an error when I'm trying to get the contents in PHP and the function to call for that encodes the URL.
I already found the fix and made a [pull request](https://github.com/Jaysds1/Nominatim/pull/1) anyways.

**Comment by mtmail** [comment]
`&` => `&amp;` is HTML encoding (https://secure.php.net/manual/en/function.htmlspecialchars.php), The `&` is a valid character in URL and doesn't need encoding (https://secure.php.net/manual/en/function.urlencode.php). It looks like something on your end does HTML encoding on a URL. Intentional or not, the server shouldn't add logic to clean that up.

**Comment by Jaysds1** [comment]
First I tried it on my localhost then moved it to my website and it still happens.

As from what I [researched](https://duckduckgo.com/?q=%26+and+%26amp+file_get_contents&t=brave&ia=web) file_get_contents encodes it.
I found a solution for my side, thanks everyone.
