### ISSUE TITLE
Parse plus+codes

### ISSUE THREAD

**Issue by gjvnq** [openstreetmap/Nominatim#914]
It would be really nice to support [plus+codes](https://plus.codes). They are essentially "universal zip codes", this is, a more compact way of encoding the coordinates (longitude and latitude). Ex: 58FM44J3+75 is the same as -20.8692880, -46.8970670 (technically plus+codes encode a rectanglar area, but we can just return the coordinates of the center point to make things simple) 

This should be "easy" to as there is a [page about it for developers](https://plus.codes/developers) and a few [reference implementations](https://github.com/google/open-location-code) in multiple programing languages on GitHub.

**Comment by lonvia** [comment]
My understanding of plus+codes is that they are purely a coordinate transformation (from lat/lon to text) and as such can be entirely on the client side, using a bounded search when the code is a mix of plus code and place name. I don't think there is any need to burden the server side with the computation.

**Comment by gjvnq** [comment]
Because then all aps that use Nominatim will support plus codes, including the OpenStreetMap website and the osm editor app Vespucci.

**Comment by lonvia** [comment]
This is a policy decision I prefer to leave to the clients.

**Comment by gjvnq** [comment]
Many clients may not have enough information to deal with "abbreviated plus codes". Ex: ```VXQQ+WP Washington, DC``` would require all clients to know a lot of relevant features, which can require a lot of storage, and analyse if this code is in the District of Columbia or in Washington State.

Leaving this to Nominatim will make developers app much easier and will reduce the risk of inconsistencies between apps using Nominatim.

**Comment by lonvia** [comment]
You can achieve all that by implementing a client-side library for developers to use.

After some consideration, I've decided that this is out of scope. Closing.

**Comment by chatelao** [comment]
Would it be an option, if I could provide a push request?

**Comment by lonvia** [comment]
No. New features are not just a question of delivering a PR. Once they are there, they stay forever and need to maintained. PlusCodes can be implemented completely on the client-side, which gives users a lot more flexibility, if and how they want it handled. I recommend that you do a PR for your favourite geocoding library instead.

**Comment by chatelao** [comment]
Danke für die nette und ausführliche Antwort.

Sarah Hoffmann <notifications@github.com> schrieb am So., 12. Mai 2019,
11:11:

**Comment by Cj-Malone** [comment]
FYI this has been brought up again. https://community.openstreetmap.org/t/plus-codes/84969/15
