### ISSUE TITLE
Wrong importance on Nominatim OSM search API results

### ISSUE THREAD

**Issue by octohedron** [openstreetmap/Nominatim#916]
When searching for `Dubai` in the website, it's returning a list with the city of `Dubai` at the top, so I guess the importance of the city in the United Arab Emirates, is the highest.

When doing a search request to the Nominatim OSM search API, I'm getting a village in Uganda called Dubai as the result with the highest priority, which is not right.

These are the results of the API call for https://nominatim.openstreetmap.org/search?q=Dubai&format=json

```
[
    {
        "place_id": "226938824",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright",
        "osm_type": "node",
        "osm_id": "5404871640",
        "boundingbox": [
            "2.9270179",
            "2.9670179",
            "30.941206",
            "30.981206"
        ],
        "lat": "2.9470179",
        "lon": "30.961206",
        "display_name": "Dubai, Arua, Northern Region, Uganda",
        "class": "place",
        "type": "village",
        "importance": 0.17875,
        "icon": "https://nominatim.openstreetmap.org/images/mapicons/poi_place_village.p.20.png"
    },
    {
        "place_id": "16284768",
        "licence": "Data © OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright",
        "osm_type": "node",
        "osm_id": "1404229008",
        "boundingbox": [
            "2.78168",
            "2.82168",
            "44.06159",
            "44.10159"
        ],
        "lat": "2.80168",
        "lon": "44.08159",
        "display_name": "Dubai, Buurhakaba بورحكب, Buur Hakaba بورحكب, Bay باي, Soomaaliya الصومال",
        "class": "place",
        "type": "suburb",
        "importance": 0.1725,
        "icon": "https://nominatim.openstreetmap.org/images/mapicons/poi_place_village.p.20.png"
    },
    [...]
]
```

And this is the wesbite results for `Dubai` as search parameter.

<img width="713" alt="screen shot 2018-02-13 at 11 45 09" src="https://user-images.githubusercontent.com/7332540/36143309-6b345ddc-10b3-11e8-890c-c7f17797699c.png">

There is something clearly wrong with my request or the server because Dubai in UAE should have the highest priority always, unless you are searching from Uganda.

**Comment by mtmail** [comment]
A quick fix for you - until we've figured out what is going on - is to set a request language in the API call because that's what your browser sets in the background. (The OSM website also takes the current map view position into consideration for ranking).

   * `curl -s 'https://nominatim.openstreetmap.org/search?q=Dubai&format=jsonv2&accept-language=en'`
or
   * `curl -s --header 'accept-language: en' 'https://nominatim.openstreetmap.org/search?q=Dubai&format=jsonv2'`

**Comment by mtmail** [comment]
I made the node (place=city, https://www.openstreetmap.org/node/31248510) the admin_centre of the relation (admin_level=4, https://www.openstreetmap.org/relation/3766483) now.

**Comment by octohedron** [comment]
@mtmail Thanks for the quick fix, now it's not finding some pretty well known places like `Guanacaste Province`

https://nominatim.openstreetmap.org/search?q=Guanacaste+Province&accept-language=en&format=json

Is this expected?

**Comment by mtmail** [comment]
Are you saying the state was found before? I'd say the state https://www.openstreetmap.org/relation/3222919 (and all others in Coasta Rica) need `name:en` tag, e.g. `Guanacaste Province` because Nominatim can't find the "Province" (english word) part of the query.

**Comment by octohedron** [comment]
Do you know if there are many places without the `name:en` tag?
What about other places in different languages like Spanish, French, etc?
`Guanacaste Province` is a pretty big and known place https://en.wikipedia.org/wiki/Guanacaste_Province

**Comment by mtmail** [comment]
If a user from Lituania wants to find https://lt.wikipedia.org/wiki/Gvanakast%C4%97s_provincija then the underlying OSM data (https://www.openstreetmap.org/relation/3222919) needs to contain the Lituanian name for the province.

Do you have an OSM account? It's fairly easy to edit tags of places.

**Comment by octohedron** [comment]
Unfortunately I cannot edit potentially so many places and add the missing translations, I would only use the API for the most widely used languages, or English if the database is complete enough.

I guess I'll find out how many places are missing while using it and decide if it's complete enough or I should switch to google maps.
