### ISSUE TITLE
Use a variable process count for osm2pgsql

### ISSUE THREAD

**Issue by otbutz** [openstreetmap/Nominatim#917]
The `setup.php` currently invokes osm2pgsql with a fixed process count of `1`:
https://github.com/openstreetmap/Nominatim/blob/master/utils/setup.php#L206

Wouldn't it be possible to take the `threads` parameter into account like here:
https://github.com/openstreetmap/Nominatim/blob/master/utils/setup.php#L65

**Comment by lonvia** [comment]
The setting actually has no effect at all. The post-processing stage of osm2pgsql, where this would have an effect, is not used at all for the gazetteer output.
