### ISSUE TITLE
Reverse lookup on building returns surrounding boundary

### ISSUE THREAD

**Issue by Dr-Mx** [openstreetmap/Nominatim#921]
Hi there,
I'm trying to reverse search a shop (https://www.openstreetmap.org/way/367347050) using 'building' zoom (18) and Nominatim is returning the surrounding boundary=protected_area (https://www.openstreetmap.org/way/558086882) instead.
https://nominatim.openstreetmap.org/reverse.php?format=html&lat=50.845233877862&lon=0.47869384288788&zoom=18

Is there anything I can do, i.e. using a parameter or editing OSM, to get the building as a result?
Thanks for your time.

**Comment by mtmail** [comment]
just adding a link confirming the place is in the Nominatim database https://nominatim.openstreetmap.org/details.php?osmtype=W&osmid=367347050

**Comment by mtmail** [comment]
Looks like it's related to an open issue where polygons of high address rank are discarded to improve query speed. https://github.com/openstreetmap/Nominatim/issues/512#issuecomment-251801298

Does a forward search help you? https://nominatim.openstreetmap.org/search.php?q=beauty+shop+near+50.845233877862%2C+0.47869384288788 The shop type needs to be pretty specific, there's no generic 'shop near <coords or address>'. https://wiki.openstreetmap.org/wiki/Nominatim/Special_Phrases/EN

**Comment by Dr-Mx** [comment]
In my specific case I'm using it to lookup an element under the users cursor, so when they right click the map and query a place, it returns related data in a pop-up.  (http://bexhill-osm.org.uk/#19/50.84525/0.47870)

As you say, it may be related to an open issue, so I may explore some geocoding alternatives in the meantime.  Thank you.

**Comment by mtmail** [comment]
Afaik the https://www.openstreetmap.org/query?lat=50.84520&lon=0.47868 website uses the https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL for their right-click "query features", which is basically "give me a list of everything around these coordinates". With that API you can also filter by types, it's very powerful.

Now assuming you got the beauty shop returned you could do a second API call to Nominatim to get its full - somewhat formatted - address. https://nominatim.openstreetmap.org/lookup.php?osm_ids=W367347050&format=json (`osm_ids` can take a comma separated list to return more than one result).

![image](https://user-images.githubusercontent.com/3727288/36256333-c2d185ec-1252-11e8-8fc6-e5caa797461d.png)

**Comment by Dr-Mx** [comment]
Fantastic!  As I'm using the Overpass API already to get tags this looks to be a great solution.  Thanks again.
