### ISSUE TITLE
False "400 Bad Request" with hierarchy.php

### ISSUE THREAD

**Issue by foodev** [openstreetmap/Nominatim#922]
When I want to lookup the hierarchy for a place with its `place_id` (using `/hierarchy.php?format=json&place_id=...`) I often get a `400 Bad Request`

> Bad Request
> 
> Nominatim has encountered an error with your request.
> 
> Details: Unknown place id.

from Nominatim.

But when I try to open the corresponding details page to check, I can find the place. So it seems the `place_id` exists.

Unfortunately I can't provide any URL, since the `place_id` is unique for my Nominatim installation...

**Comment by mtmail** [comment]
Can you post an example or two with the osm_type (node, way, relation) and osm_id? Those are listed on e.g. https://nominatim.openstreetmap.org/details.php?place_id=179458768

**Comment by foodev** [comment]
Some examples:

- way 30472548
- way 34023518
- way 5061409
- way 4428556

It seems all are osm_type `way`...

**Comment by lonvia** [comment]
I'm sorry to say that `hierarchy.php` is currently unmaintained and unsupported. I will take PRs that fix issues like this but otherwise it is a won't fix.
