### ISSUE TITLE
Searching for Orange County, Vermont gives result in California.

### ISSUE THREAD

**Issue by EdwardBetts** [openstreetmap/Nominatim#929]
https://nominatim.openstreetmap.org/search.php?q=Orange+County%2C+Vermont

Searching for Orange County, Vermont returns one result: Vermont, Walnut, Irvine, Orange County, California.

Adding the country returns the correct result (Orange County, Vermont, USA).

**Comment by lonvia** [comment]
The interpretation 'Vermont in Orange County' has for some reason a higher rank than 'Orange County in Vermont'. Needs checking why.

**Comment by EdwardBetts** [comment]
A similar example: (Jefferson County, Missouri) vs (Jefferson County, Missouri, USA).

**Comment by lonvia** [comment]
This is an opposite case for #473. When searching for "střední, nová ves pod pleší", the different search rank prevents the wrong county etc. to be shown. I'm not sure if there is a ranking that satisfies both search queries.

**Comment by lonvia** [comment]
The fix for #988 now ensures that both results show up.
