### ISSUE TITLE
Viewbox is not used when searching restaurants or shops.

### ISSUE THREAD

**Issue by MaartenDeen** [openstreetmap/Nominatim#930]
https://nominatim.openstreetmap.org/search.php?q=mcdonald%27s&polygon_geojson=1&viewbox=7.98706%2C49.94503%2C9.19968%2C49.50113
Viewbox is in Germany, result is in Texas, USA

https://nominatim.openstreetmap.org/search.php?q=kruidvat&polygon_geojson=1&viewbox=6.16575%2C51.36926%2C6.17049%2C51.36759
Viewbox is at shop Kruidvat in Venlo, result is in Amsterdam, 130 km away

To show that this is not related to having a website tag:
https://nominatim.openstreetmap.org/search.php?q=sint+maria&polygon_geojson=1&viewbox=5.97762%2C51.32981%2C5.98209%2C51.32813
Viewbox is at a restaurant called Sint Maria, results are tram stops and churches 100's of km away.

**Comment by mtmail** [comment]
By default the viewbox is treated as hint, not filter. Add `&bounded=1` to your query https://wiki.openstreetmap.org/wiki/Nominatim

**Comment by mtmail** [comment]
Checking the viewbox checkbox adds `viewbox=somecoordinates` to the request URL, it doesn't add `bounded=1` to the requests URL.

Try
https://nominatim.openstreetmap.org/search.php?q=mcdonald%27s&viewbox=4.702148,46.830134,15.908203,55.128649&bounded=1&format=jsonv2

Or since that's the bounding box for Germany (http://bboxfinder.com/#46.830134,4.702148,55.128649,15.908203) but still includes some regions outside Germany you can also try the country filter instead.

https://nominatim.openstreetmap.org/search.php?q=mcdonald%27s&countrycodes=de&format=jsonv2

The nominatim.openstreetmap.org website is meant for debugging, there's many URL parameters it doesn't support.

**Comment by MaartenDeen** [comment]
The question why this is not a problem for streets remains. Why do I get results in the neighborhood when I search on a street name without the bounded=1 option and why do I not get results in the neighborhood when I seach on a shop name.

**Comment by mtmail** [comment]
Please provide an example or two for streets searches.

**Comment by MaartenDeen** [comment]
Any street will do? Molenstraat is a commonly used streetname in the Netherlands, here the viewbox is picked up without having to use bounded=1
https://nominatim.openstreetmap.org/search.php?q=molenstraat&polygon_geojson=1&viewbox=5.99601%2C51.32412%2C6.00549%2C51.32077

**Comment by mtmail** [comment]
So the viewbox was used to rank nearby results higher; it's expected to see results in the Nederlands on top. If you click "search for more results" a couple of times it also includes Molenstraat in the United States and Belgium.

Maybe this example helps.

* "Downing Street", no viewbox: shows results from around the world
```
curl -s 'https://nominatim.openstreetmap.org/search.php?q=downing+street&format=jsonv2&limit=5' | jq '.[] | .display_name'
"Downing Street, St. James's, Covent Garden, City of Westminster, London, Greater London, England, SW1, UK"
"Downing Street, Market Ward, Cambridge, Cambridgeshire, East of England, England, CB2 3EJ, UK"
"Downing Street, Cloverdale, Etobicoke, Toronto, Ontario, M9B 3R6, Canada"
"Downing Street, Curtis-Champa Streets Historic District, Denver, Denver County, Colorado, 80205, United States of America"
"Downing Street, Quality Hill Historic District, Denver, Denver County, Colorado, 80209, United States of America"
```

* "Downing Street", viewbox around central United States: shows results from around the world. Colorado results rank high but the one in London is still highest.
```
curl -s 'https://nominatim.openstreetmap.org/search.php?q=downing+street&format=jsonv2&viewbox=-116.96045%2C42.76315%2C-88.72559%2C34.18000&limit=5' | jq '.[] | .display_name'
"Downing Street, St. James's, Covent Garden, City of Westminster, London, Greater London, England, SW1, UK"
"Downing Street, Swallow Hill Historic District, Denver, Denver County, Colorado, 80205, United States of America"
"Downing Street, Curtis-Champa Streets Historic District, Denver, Denver County, Colorado, 80205, United States of America"
"Downing Street, Quality Hill Historic District, Denver, Denver County, Colorado, 80209, United States of America"
"Downing Street, Decatur, Macon County, Illinois, 62521, United States of America"
```

* "Downing Street", viewbox around central United States: shows results from the United States only.
```
curl -s 'https://nominatim.openstreetmap.org/search.php?q=downing+street&format=jsonv2&viewbox=-116.96045%2C42.76315%2C-88.72559%2C34.18000&limit=5&bounded=1' | jq '.[] | .display_name'
"Downing Street, Curtis-Champa Streets Historic District, Denver, Denver County, Colorado, 80205, United States of America"
"Downing Street, Swallow Hill Historic District, Denver, Denver County, Colorado, 80205, United States of America"
"Downing Street, Quality Hill Historic District, Denver, Denver County, Colorado, 80209, United States of America"
"Downing Street, Decatur, Macon County, Illinois, 62521, United States of America"
"Downing Street, Maryland Heights, St. Louis County, Missouri, 63043, United States of America"
```

**Comment by lonvia** [comment]
So there is a problem with viewbox on POI level only. It's not that the viewbox is not taken into account but that the viewbox factor is multiplied with the importance factor which happened to be 0 for POIs without any special wikipedia tags. That zero effectively cancels out the viewbox. I've pushed a quickfix to nominatim.osm.org, lets see how that works out but this really needs some more thinking about what the proper importance should be.

Note that this does not solve the McDonald's problem which is one of misplaced wikipedia tags.

**Comment by yvecai** [comment]
Is it the viewbox that is taken into account in ranking or the distance of the result to the viewbox center? Cause a viewbox depends highly on the zoom level.
