### ISSUE TITLE
Docker (and docker-compose.yml)

### ISSUE THREAD

**Issue by Firefishy** [openstreetmap/Nominatim#931]
It would be great if nominatim shipped with a `Dockerfile` and a `docker-compose.yml` to help developers get started sooner.

I have an itch... maybe I'll follow in a week or 2 with a scratch (PR) ;-)

**Comment by mtmail** [comment]
Did you see https://github.com/mediagis/nominatim-docker ? I'll add a link

**Comment by lonvia** [comment]
@mtmail has added a link to the mediagis docker in #934.
