### ISSUE TITLE
CentOS 7 + vagrant installation script = permission issue with nominatim.so, warning Postgresql is too old

### ISSUE THREAD

**Issue by KUTlime** [openstreetmap/Nominatim#932]
I am struggling with Nominatim installation on Centos 7.
The install script for Centos has several issues and the installation could not be completed on clean Centos 7 Out-Of-Box.
I fixed some issues at my fork but I am stuck on:

**2018-02-21 08:31:32 == WARNING: Postgresql is too old. extratags and namedetails API not available.
Postgis version found: 2

ERROR: Failed to load nominatim module. Reason:
CREATE FUNCTION nominatim_test_import_func(text) RETURNS text AS '/home/gina/build/module/nominatim.so', 'transliteration' LANGUAGE c IMMUTABLE STRICT;DROP FUNCTION nominatim_test_import_func(text); [nativecode=ERROR:  could not access file "/home/gina/build/module/nominatim.so": Operace zamítnuta]**

Já = Me in Czech

![2018-02-20_160101](https://user-images.githubusercontent.com/8374320/36470539-7d19ec9a-16eb-11e8-97d4-5d74da7f0a2a.png)

I transferred the ownership of whole build folder, added 777 but still getting this error.

In addition, PostgresSQL version in yum repository is quite old (v9.2) and Nominatim drops some functionality.

Perhaps my issue is related to the old version of database?

**Comment by mtmail** [comment]
Likely. I created https://github.com/openstreetmap/Nominatim/pull/933/files which should give you hints how to install postgresql 9.5 and postgis 2.4.

I can't help much in how to deinstall any old versions (other than trying `yum list post*` and `yum remove`). But you said "on clean Centos 7 Out-Of-Box" so maybe you can start from a clean system again.

```could not access file "/home/gina/build/module/nominatim.so":``` When I tested with Postgresql 9.2 the `cmake` command failed and thus the .so file wasn't generated during the installation. Worked when I had 9.5.

**Comment by KUTlime** [comment]
I already adopted the installation script to PostgreSQL v9.6, because this was a version which worked for me on Ubuntu. I didn't have time to verify the results, I will check it on Monday, but your code look pretty much same like mine in my [fork.](https://github.com/KUTlime/Nominatim/blob/master/vagrant/Install-on-Centos-7-pg96.sh)

Reverting back to fresh, clean CentOS is easy, I did it like one hundred times pass three days because of issues in the vagrant install script.

**Comment by lonvia** [comment]
I just tried the vagrant script with a vanilla bento/centos7-4 box and everything worked fine. There is no reason Postgresql 9.2 should not work. You won't have the extratags and namedetails options in the API but that is not an error.

Could you please both describe exactly what the issues with Postgres 9.2 are?

I think the bento box does not have SELinux enabled and I just noticed that the instructions there might be a little bit out of date pointing to the source instead of the build directory. That would explain that nominatim.so is not accessible but has nothing todo with the postgres version.

**Comment by KUTlime** [comment]
@lonvia I used the latest iso downloaded from centos.org, putted into VM in Hyper-V and I tried to use the vagrant script to install it. There is no way how the script could work. A _clean_ CentOS doesn't have wget package and there are some sudo prefixs missing.

The problem with PG v9.2 is stated in my first post - no access to nominatim.so.

**Comment by mtmail** [comment]
Hmm. Maybe the `bento/centos` Vagrant images add some magic, I can't seem to find a list of differences. Will try the centos.org provided ones https://app.vagrantup.com/boxes/search?provider=virtualbox&q=centos&sort=downloads&utf8=%E2%9C%93

**Comment by lonvia** [comment]
@mtmail Have you tried changing the SELinux instructions so they point to the build directory, i.e `$USERHOME/Nominatim` -> `$USERHOME/build`? The fix might really be as simple as that.

**Comment by KUTlime** [comment]
I think it isn't important to get it running on some specific version of CentOS if there is some equivalent version of CentOS where it is OK.
I think what is **really** important to inform other newbie users like me which version of CentOS should we used.

@lonvia I changed the script to point to `$USERHOME/build` but it doesn't solve the access issue.

**Comment by mtmail** [comment]
I think I have a solution. If you set `USERHOME=/opt/nominatim` instead of `USERHOME=/home/gina` then it works with SELinux enabled. My guess is that SELinux doesn't allow `lib_t` type files in user directories at all via a different permission.

Other CentOS users didn't run into the issue because http://nominatim.org/release-docs/latest/appendix/Install-on-Centos-7/ says `/srv/nominatim`.

We never saw the issue in our Vagrant VM because the base image has SELinux disabled.

I'll prepare a PR with an centos.org image, SELinux enabled, update the paths, add wget etc.

**Comment by KUTlime** [comment]
@mtmail I've adopted your suggestion from https://github.com/openstreetmap/Nominatim/pull/933/files
I successfully installed and imported some data into PostgreSQL v9.6 on vanilla CentOS from www.centos.org 

The script is here: https://github.com/KUTlime/Nominatim/blob/master/vagrant/Install-on-Centos-7-pg96.sh

I suggest to extend the main Nominatim repo with the installation script(s) for vanilla CentOS instances.

**Comment by KUTlime** [comment]
My joy was premature. The website is not accessible from other computers. If I use ping towards PC where is Nominatim hosted, it OK. When I try access website withing the PC, website is shown.
When I try it from other PC from local network, I receive connection timeout.

Any suggestion?

**Comment by KUTlime** [comment]
Firewall problem. :-(
```
sudo firewall-cmd --zone=public --permanent --add-service=http
sudo firewall-cmd --zone=public --permanent --add-service=https
sudo systemctl restart firewalld.service
```

**Comment by hadanhtoi** [comment]
hi @mtmail  hi everybody, I use /home/nominatim for $USERHOME for installation and got error : 
`CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_LIBRARY_DIRS
  PostgreSQL_CONFIG_DIR PostgreSQL_INCLUDE_DIRS PostgreSQL_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindPostgreSQL.cmake:173 (find_package_handle_standard_args)
  osm2pgsql/CMakeLists.txt:117 (find_package)`
And when I relogged in, $USERNAME have became to 'root' and $USERHOME have lost. 
What should I do?

**Comment by hadanhtoi** [comment]
And I have another question, What different between use /home/nominatim and /srv/nominatim ?

**Comment by mtmail** [comment]
This github issue got closed 16 months ago. Please use https://help.openstreetmap.org/
