### ISSUE TITLE
Incorrect City Name

### ISSUE THREAD

**Issue by Jaysds1** [openstreetmap/Nominatim#942]
HI,

So the problem here is that I get an incorrect city name when using my local and remote website to get the address using coordinates.

https://nominatim.openstreetmap.org/reverse?lat=43.52519295&lon=-79.7048307321863&zoom=18&addressdetails=1&email=support@miservic.com&format=json

Returns:
> {"place_id":"81299343","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https://osm.org/copyright","osm_type":"way","osm_id":"38116690","lat":"43.52519295","lon":"-79.7048307321863","display_name":"3570, Colonial Drive, Erin Mills, **Ont**., Peel Region, Ontario, L5L 5Z7, Canada","address":{"house_number":"3570","road":"Colonial Drive","suburb":"Erin Mills","city":"**Ont.**","county":"Peel Region","state":"Ontario","postcode":"L5L 5Z7","country":"Canada","country_code":"ca"},"boundingbox":["43.5246873","43.5254926","-79.7053025","-79.7044762"]}
Expected:
> {"place_id":"81299343","licence":"Data © OpenStreetMap contributors, ODbL 1.0. https:\/\/osm.org\/copyright","osm_type":"way","osm_id":"38116690","lat":"43.52519295","lon":"-79.7048307321863","display_name":"3570, Colonial Drive, Erin Mills, **Mississauga**, Peel Region, Ontario, L5L 5Z7, Canada","address":{"house_number":"3570","road":"Colonial Drive","suburb":"Erin Mills","city":"**Mississauga**","county":"Peel Region","state":"Ontario","postcode":"L5L 5Z7","country":"Canada","country_code":"ca"},"boundingbox":["43.5246873","43.5254926","-79.7053025","-79.7044762"]}

**Comment by lonvia** [comment]
This is a data error that needs to be fixed by editing the data in OpenStreetMap.

https://www.openstreetmap.org/relation/1954127 has a tag `short_name=Ont.` which is obviously not the name of the city.
