### ISSUE TITLE
using 'admin_centre' beside 'label'

### ISSUE THREAD

**Issue by Megachip** [openstreetmap/Nominatim#943]
Most 'vilages' etc. in germany seems to added as 'admin_centre' instead of 'label' to boundary relation. Why nominatim didn't interpret 'admin_centre' as member?

So we could prevent results like Germany -> Saxony -> Magdeburg -> Sülzetal (which is not part of magedeburg) -> Beyendorf (which should be part of Beyendorf-Sohlen and not vice versa) -> Beyendorf-Sohlen -> Beyendorf-Sohlen

**Comment by lonvia** [comment]
It is used but with some restrictions as admin_centre does not always point to the same object but regularly to the capital instead.

**Comment by Megachip** [comment]
@lonvia so adding the node as label is still suggested?
