### ISSUE TITLE
Address not found, in spite of complete address:* tags on building

### ISSUE THREAD

**Issue by TO-92** [openstreetmap/Nominatim#950]
Opening a new issue as advised by @lonvia:

I am currently investigating a user note on OpenStreetMap where an address is not found even though it is correctly tagged.

**Case 1**
First of all, this works as expected, just to make sure that the underlying OSM data is not entirely wrong:
[Monningstraße 57, 45478 Mülheim](https://nominatim.openstreetmap.org/search.php?q=Monningstra%C3%9Fe+57%2C+45478+M%C3%BClheim)

**Case 2**
This is the query in question:
[Monningstraße 126, 45478 Mülheim](https://nominatim.openstreetmap.org/search.php?q=Monningstra%C3%9Fe+126%2C+45478+M%C3%BClheim)
Instead of locating the actual address it just returns the street.

This is the object that should be found but isn't:
https://nominatim.openstreetmap.org/details.php?place_id=95202861

Nominatim drops the addr:street tag here (because "Monningstraße" is too far away?) and attaches the building to the nearby "Steinbruchweg".

**Case 3**
Surprisingly the query [Monningstraße 60, 45478 Mülheim](https://nominatim.openstreetmap.org/search.php?q=Monningstra%C3%9Fe+60%2C+45478+M%C3%BClheim) does not find the requested address either, even though the [building](https://nominatim.openstreetmap.org/details.php?place_id=93658321) is right next to the street this time and the nearby house number 57 was correctly found.

In this case Nominatim gets the street right, but unfortunately Monningstraße marks the boundary between the cities of Duisburg and Mülheim, and while the _buildings_ along the street belong to Mülheim, the _street_ itself happens to be on Duisburg ground. Consequently the computed address (with the buildings attached to the street and the addr:city tag dropped) is something like "Monningstraße 60, Duisburg", which obviously cannot be found when searching for an address in Mülheim.

@lonvia 
> please confirm that this is not a data error where Monningstr is mapped incompletely.

Can you point me to what might be missing or incomplete? I tried adding `postal_code=45478` to the street, but that didn't help.

**Comment by lonvia** [comment]
Case 3 is the known issue of buildings on roads close to boundaries. There is some discussion in #785 already.

> Can you point me to what might be missing or incomplete? I tried adding postal_code=45478 to the street, but that didn't help.

It seems a tad unusual that a house is so far away from the street it belongs to addresswise. One possibility is that the Monningstr used to go all the way down to the building along what is now Grenzweg and Rundweg or maybe even still does. It would help if a local could confirm the situation.

It is possible to increase the search radius for the street that belongs to an address. It would have a performance impact for the indexing, though. Needs to be checked if it is noticeable.

**Comment by TO-92** [comment]
Well, I am a semi-local - I lived in MH-Speldorf some years ago and we occasionally walked our dog up there, but I never had a reason to look at the street signs. I agree with you that probably the whole street used to be Monningstraße, and then Duisburg decided to rename the upper part while Mülheim kept the old addresses on their side. Actually I planned to take a trip to Mülheim today and see what's up, but it was so freezing cold that I preferred to stay at home. ;) Maybe next week then.

But now that I discovered the "streets near boundaries" issue I'm not sure anymore if increasing the search radius would make things any better. Since house numbers 60 to 66 are already assigned to the wrong city, wouldn't the computed address just switch from "Steinbruchweg 126, Mülheim" to "Monningstraße 126, Duisburg" which would be just as wrong?

**Comment by lonvia** [comment]
That's true, I'm afraid. It would likely match against the southern piece of track but that is still on the wrong side of the border. Both issues need to be fixed to make it correct.

**Comment by TO-92** [comment]
Well, there you are:

![Monningstr.126](https://c1.staticflickr.com/5/4780/26884686498_ce7083d695_o.jpg)

To increase the challenge there is no house number on the building itself or at the gate, and no street signs anywhere near. The above sign is located some 400m to the east, at the corner of Katzenbruch / Blötter Weg. I wonder if they ever successfully get UPS or Hermes deliveries, because unless you know in advance where the house is - possibly by using the search function on OSM if it worked ;) - you have no chance to find it. (There is a similar situation with [Mülheimer Str. 290, Duisburg](https://nominatim.openstreetmap.org/search.php?q=Mülheimer+Str.+290%2C+Duisburg), but luckily here the house is still close enough to the street and far enough from any boundary.)

It's nice to have a hierarchy like Country > State > City > District > Street > House, but reality doesn't always work like that. In fact we have a paradox here because the street itself is entirely on the Duisburg side of the boundary, while all the buildings belong to Mülheim. Strictly speaking a search for "Monningstraße, Mülheim" should yield no result at all because there is no street with that name within the city boundaries, while "Monningstraße _housenumber_, Mülheim" should return the house corresponding to that address.

And to be honest, I think most people who input an address just want to find where it is on the map but don't care whether that address belongs to an administrative entity called "Linksruhr" or "Neudorf Süd" or "Mitte II", so they would be perfectly happy with a direct match on the addr:* tags.

But regarding this particular issue, can you predict what would happen if I put a "name=Monningstraße" tag on the little driveway leading to the house? Would that help as a workaround for the time being, or would that mess up all the other addresses for that street?

**Comment by lonvia** [comment]
Thanks for taking the field trip. I will add this case to my growing collection of insane addressing ideas.

I'll increase the search radius for named streets a bit. Please don't tag any service streets for the search engine, this problem really needs to be fixed in Nominatim. There are plans for using the postal address (the addr:* stuff) as well as the geographic location, #148, it'll just take a while to get that done.

**Comment by lonvia** [comment]
I've deployed the version with the increased search radius and reindexed the address. Now the street is correct and even the postcode, but as expected, the city is still Duisburg: https://nominatim.openstreetmap.org/search.php?q=Monningstraße+126%2C+45478
