### ISSUE TITLE
Incorrect Address

### ISSUE THREAD

**Issue by RodySmith** [openstreetmap/Nominatim#953]
I've been trying to get this corrected and one email I got was from Nick at github.com. He said:

"Hey @RodySmith Thanks for your feedback, Automatic uses Mapbox's geocoder under the hood. If you could report future problems via: https://github.com/mapbox/geocoder-feedback that would be great!"

But the link got a 404 not found error. I did get to a request form and tried that. I was then told (by Tom Hughes at GitHub) that no one at GitHub could help. He sent me to this link. Here is the issue: apparently the geocoder is reporting my address as 7235 South Vine Street, Littleton CO 80122. My address is 7241 South Vine Street, Centennial CO 80122. A CSV file from the Automatic app reports the Lat/Lon as 39.58563/-104.96438. (Note if I enter that Lat/Lon into Google Maps it goes direct to my house.)
Can you correct this?
Thank you!

**Comment by mtmail** [comment]
I understand how this is confusing. It's three different companies who answered, plus github.com as a forum (nobody you talked to works at github).

In https://github.com/openstreetmap/openstreetmap-website/issues/1775#issuecomment-369393706 Nick corrected the link to https://www.mapbox.com/geocoder-feedback/ Please add your feedback there, Mapbox.com will be able to look into it.

**Comment by simonpoole** [comment]
BTW it seems as if the address is more or less correct in OSM/Nominatim (interpolated naturally but still),. https://www.openstreetmap.org/search?query=7241%20South%20Vine%20Street%2C%20Centennial%20CO%2080122#map=19/39.58586/-104.96415
