### ISSUE TITLE
way import slower than node import by five orders of magnitude

### ISSUE THREAD

**Issue by shallot** [openstreetmap/Nominatim#954]
Hi,

With Nominatim 3.1.0, I tested importing a few European countries on a local test KVM VM with magnetic disks in RAID0, and it worked reasonably well. The way processing went e.g. Way(56182k 1.80k/s) and Way(3871k 3.38k/s). Node import went quite fast as well. Relation import was much slower.

Then I started a test machine with SSD disks on OVH, copied all the binaries over, installed all the prerequisites, and tried to import the whole of Europe, but after 24h only got as far as this:

```
time /srv/nominatim/Nominatim/build/utils/setup.php --osm-file /opt/import/europe-latest.osm.pbf --all --osm2pgsql-cache 5120 --threads 2
2018-02-28 03:02:05 == Create DB
2018-02-28 03:02:05 == Setup DB
Postgres version found: 9.5
Postgis version found: 2.2
2018-02-28 03:02:10 == WARNING: external UK postcode table not found.
2018-02-28 03:02:10 == Import data
osm2pgsql version 0.93.0-dev (64 bit id space)

Using projection SRS 4326 (Latlong)
NOTICE:  table "place" does not exist, skipping
Allocating memory for dense node cache
Allocating dense node cache in one big chunk
Allocating memory for sparse node cache
Sharing dense sparse
Node-cache: cache=5120MB, maxblocks=81920*65536, allocation method=11
Mid: loading persistent node cache from /opt/flatnode/europe.flatnode
Mid: pgsql, cache=5120
Setting up table: planet_osm_nodes
Setting up table: planet_osm_ways
Setting up table: planet_osm_rels

Reading in file: /opt/import/europe-latest.osm.pbf
Using PBF parser.
Processing: Node(2045878k 702.3k/s) Way(2668k 0.03k/s) Relation(0 0.00/s)
```

It's not looking optimistic at this point...

The IOPS load was on the order of 200 during the first part of the operation, and for Ways it got down to 20, while at the same time the calculated disk utilization remains as high as 100%.

I tried to check if this is I/O contention and ran a fio test in parallel on the same disk, but got another 250-350 IOPS out of it easily (`sudo fio --name=rand-read --ioengine=libaio --directory=/opt/ --iodepth=32 --rw=randread --invalidate=1 --bsrange=1k:1k,4k:4k --size=512m --time_based --do_verify=1 --direct=1 --group_reporting --numjobs=1 --runtime=15`).

I believe I followed the installation guide for Ubuntu 16 recommendations appropriately for the hardware size which is 8 GB RAM, 4 vCPUs in this VM. The modified PostgreSQL settings on it are the same as those on my earlier test VMs:

```
shared_buffers = 1GB
work_mem = 32MB
maintenance_work_mem = 1GB
fsync = on
synchronous_commit = off
full_page_writes = off
checkpoint_timeout = 10min
checkpoint_completion_target = 0.9
effective_cache_size = 6GB
```

I noticed now that fsync was mistakenly left on. Would that matter? It doesn't sound like it really should, when everything else is disabled anyway. It was like that on my previous imports, too, and didn't seem to have the same effect.

This is how the processes look:

```
% ps -L -u nominatim
  PID   LWP TTY          TIME CMD
10544 10544 pts/1    00:00:01 script
10545 10545 pts/2    00:00:00 bash
14092 14092 pts/2    00:00:00 setup.php
14717 14717 pts/2    00:00:00 sh
14718 14718 pts/2    00:47:23 osm2pgsql
14718 14727 pts/2    00:04:09 _osmium_read
14718 14728 pts/2    00:05:03 _osmium_pbf_in
14718 14729 pts/2    00:25:58 _osmium_worker
14718 14730 pts/2    00:25:56 _osmium_worker
```

```
% ps auxfw | grep '[p]'ostgres
postgres 27266  0.0  0.6 1246088 49744 ?       S    Feb23   0:23 /usr/lib/postgresql/9.5/bin/postgres -D /var/lib/postgresql/9.5/main -c config_file=/etc/postgresql/9.5/main/postgresql.conf
postgres 27275  0.0 13.6 1247524 1086536 ?     Ss   Feb23   2:25  \_ postgres: checkpointer process
postgres 27276  0.0  2.0 1246088 162604 ?      Ss   Feb23   0:17  \_ postgres: writer process
postgres 27277  0.0  0.2 1246088 19020 ?       Ss   Feb23   0:55  \_ postgres: wal writer process
postgres 27278  0.0  0.0 1246464 4440 ?        Ss   Feb23   0:40  \_ postgres: autovacuum launcher process
postgres 27279  0.0  0.0 148544  2440 ?        Ss   Feb23   0:41  \_ postgres: stats collector process
postgres 14241  0.0  0.2 1553276 17580 ?       Ss   Feb28   0:00  \_ postgres: nominatim nominatim [local] idle
postgres 14719  0.5 13.2 1353220 1058624 ?     Ss   Feb28   8:03  \_ postgres: nominatim nominatim [local] COPY
postgres 14722  0.0  0.1 1253524 12040 ?       Ss   Feb28   0:00  \_ postgres: nominatim nominatim [local] COPY
postgres 14724  0.0  1.8 1253984 145664 ?      Ss   Feb28   0:43  \_ postgres: nominatim nominatim [local] COPY
postgres 14725  0.0  0.1 1253564 12676 ?       Ss   Feb28   0:00  \_ postgres: nominatim nominatim [local] COPY
```

Stracing them indicates that they're active, but sluggish (8k socket reads dripping along).

From everything I've googled, I figured ways and relations imports have to be significantly slower, but this seems excessive. Is there anything that can be done?

Let me know if I can provide more information.

TIA.

**Comment by lonvia** [comment]
Please note that this a bug issue tracker for Nominatim not a help forum. If you have questions about the installation process please use the [geocoding mailing list](https://lists.openstreetmap.org/listinfo/geocoding).

**Comment by shallot** [comment]
@lonvia this was not a help forum request, this was a bug report about how the program is behaving erratically. Can you please spend a modicum of effort trying to understand user bug reports?

**Comment by mtmail** [comment]
Are you running `VPS Cloud 3` VM? https://www.ovh.co.uk/vps/vps-cloud.xml Unlike their `VPS SSD` https://www.ovh.co.uk/vps/vps-ssd.xml the storage is network mounted and can show unreliable performance https://www.lowendtalk.com/discussion/94181/ovh-vps-cloud-disk-i-o-performance

Not sure if your I/O contention test would strictly hit the same physical disc with the network abstraction. Or how disk utilization is calculated in that setup.

Too bad the `VPS SSD` offers only goes to 40GB.

Switching `fsync` off in the postgresql has advantages later in the installation.

My latest planet install was
```
Processing: Node(4181183k 4043.7k/s) Way(451967k 116.55k/s) Relation(5359900 4612.65/s)
```
but big word of caution because that's a huge dedicated server with NVMe RAID. Possible this is about the maximum one can do with current (year 2017) hardware.

**Comment by shallot** [comment]
@mtmail yes, and I actually read that post at LET earlier, but I didn't expect the pattern to be like this - it is just consistently slow with Ways, there are no ups and downs. Is it possible that the Ways calculation is really that taxing on I/O and in such a different way that an underlying Ceph filesystem impacts it so much? This could then be documented, given that discouraging magnetic drives is documented already.

**Comment by shallot** [comment]
The curious thing is that an import of just e.g. France on that same machine resulted in Node(381375k 497.9k/s) and Way(32563k 29.98k/s). So maybe there's another kind of bottleneck - the complexity of the  Ways calculation didn't seem to impact performance in that case. It would be good if there was some concrete analysis in the documentation of how to estimate and assess performance.

**Comment by mtmail** [comment]
Will you upgrade to different hardware of keep the installation running on the `VPS Cloud 3`?

**Comment by shallot** [comment]
At this point I'm not quite sure what the logical course of action would be. Do I need more I/O or perhaps more RAM is a priority in order to handle the whole of Europe?

**Comment by lonvia** [comment]
I was dead serious when I pointed out that this issue tracker is not the right place to discuss installation constraints. And it certainly isn't the place to discuss the merits of cloud providers. Please use the mailinglist.
