### ISSUE TITLE
three stages of osm2pgsql import processing strictly linked

### ISSUE THREAD

**Issue by shallot** [openstreetmap/Nominatim#955]
Hi,

I noticed that while the first stage of utils/setup.php is running, the "Import data" with osm2pgsql, if I Ctrl+C it while processing ways, it rolls everything back and the next run has to redo the Node import. Sounds as if all four COPY commands are in the same PostgreSQL transaction.

Would it be possible to split those stages? The updates have a synchronization indicator, so it seems like this could have something like that, too. That way, a subsequent run with the same input file and parameters could continue where it left off.

This is with Nominatim 3.1.0 / osm2pgsql 0.93.0-dev.

TIA.

**Comment by lonvia** [comment]
No, that's not possible because the processing is interlinked.
