### ISSUE TITLE
repeated initial import with flatnode seems significantly slower

### ISSUE THREAD

**Issue by shallot** [openstreetmap/Nominatim#956]
Hi,

I noticed how if I re-run an aborted import, the database is rolled back - cf. https://github.com/openstreetmap/Nominatim/issues/955 - but the specified flatnode file remains as is. With europe-latest.osm.pbf, that came up to 41 GB. If I keep it, the next Node import runs at ~50k/s; if I remove it and it gets regenerated anew, the next Node import runs at ~700k/s.

Is this normal? If it can't be avoided, perhaps document it at http://nominatim.org/release-docs/latest/Import-and-Update?

TIA

**Comment by lonvia** [comment]
That is normal, in particular when the RAM available is significantly smaller than the size of the file. The documentation already gives recommendations about hardware.

**Comment by shallot** [comment]
So why not actually document this in particular? There's nothing about this issue at http://nominatim.org/release-docs/latest/Installation#Hardware either. I don't think it's a common use case that people will use >41 GB RAM machines for the import of Europe by default, when the only option discussed is 32 GB for the planet, and there's hints elsewhere that Europe data is half the planet data (likewise undocumented above), so any reasonable person would be thinking 16-32 should be enough. This seems like a perfectly reasonable pitfall to document.
