### ISSUE TITLE
utils/setup.php could apply rank limits

### ISSUE THREAD

**Issue by shallot** [openstreetmap/Nominatim#959]
Hi,

I found it somewhat confusing that the initial import didn't support the `--index-rank` option that the update process had. It seems to be hardcoded to run 0-4, 5-25, 26-30 in the `--index` or `--all` mode. 

Would it make sense to be able to clamp that with command-line options?
Especially at the end of the interval, there's a significant reduction in runtime if that can be done.

TIA.

**Comment by lonvia** [comment]
No, that would not make sense. The setup script does automatically the right thing to make sure that all data is indexed when it is finished and that it doesn't repeat what already has been done when restarted.
