### ISSUE TITLE
nominatim.org shows 2 sets of installation instructions

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#960]
After the switch to mkdocs we have two sets of documentation which already show slight differences. On top the URLs are so similar it's hard to spot.

First set
   * http://nominatim.org/release-docs/latest/Import-and-Update it says
      * "35GB of free space"
      * 2015 TIGER data
   * http://nominatim.org/release-docs/latest/Installation
      * "you will need about 500GB of hard disk space"

Second set
   * http://nominatim.org/release-docs/latest/admin/Import-and-Update/
      * "40GB of free space"
      * 2017 TIGER data
   * http://nominatim.org/release-docs/latest/admin/Installation/
      * "you will need about 600GB of hard disk space"

**Comment by lonvia** [comment]
The second is the up-to-date one. I've removed the first.
