### ISSUE TITLE
add network-mounted/cloud storage note hardware recommendations

### ISSUE THREAD

**Issue by mtmail** [openstreetmap/Nominatim#961]
Basically add a disclaimer that network-mounted storage can have negative performance impact and one should always prefer in-machine (instance) storage. Not sure yet about the wording.

http://nominatim.org/release-docs/latest/admin/Installation/#hardware

AWS for example has two types of SSDs https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html, OHV's cloud storage uses CEPH in the background, with VMware we got a report that the network storage was a bottleneck.

**Comment by twain47** [comment]
For AWS I'd be tempted to add a recommendation for i3.2xlarge. The machine has local ssd storage and is just big enough to process a full planet file (although it is getting close to needing i3.4xlarge)

**Comment by lonvia** [comment]
I would suggest to collect these kind of reports on a wiki page where everybody can add their experience. I'm reluctant to include anything more than the current hardware recommendations in the official documentation because it is not maintainable.
