### ISSUE TITLE
Farnborough is missing!

### ISSUE THREAD

**Issue by nicholasgriffinVF** [openstreetmap/Nominatim#966]
In title.

Location:

https://www.google.com/maps/place/Farnborough/@51.2794022,-0.7750589,14.75z/data=!4m5!3m4!1s0x48742ac28424763b:0x8deb0ce49313925d!8m2!3d51.2868939!4d-0.752615?hl=en-GB

**Comment by SomeoneElseOSM** [comment]
Data error (nothing to do with Nominatim), introduced in https://www.openstreetmap.org/changeset/52747456 , resolved in https://www.openstreetmap.org/changeset/56942486 .

**Comment by mtmail** [comment]
Thanks @SomeoneElseOSM ! Database auto-updated and the place is found again https://www.openstreetmap.org/search?query=Farnborough

**Comment by nicholasgriffinVF** [comment]
Thanks for that, didn't realize it was fixable via OpenStreetMap.

**Comment by nicholasgriffinVF** [comment]
By the way, we've noticed something else, When getting a location within Loughborough it generally returns as Charnwood and not Loughborough I'm trying to figure out how we should fix this, any suggestions?

**Comment by SomeoneElseOSM** [comment]
@nicholasgriffinVF I'd be tempted to ask the Loughborough question at https://help.openstreetmap.org/questions/ or in a GB forum such as https://lists.openstreetmap.org/listinfo/talk-gb or #osm-gb on IRC (see https://wiki.openstreetmap.org/wiki/IRC ).  It's likely to do with the various admin levels there or "nodes vs ways", and people local to the area will be able to answer if you tell them what exactly you're asking Nominatim for and what you're expecting.
