### ISSUE TITLE
Address not found, in France

### ISSUE THREAD

**Issue by geraldbigot** [openstreetmap/Nominatim#976]
Hi,
I got a problem with this city : 
Pleumeur-Bodou, Lannion, Côtes-d'Armor, Brittany, 22560, France (City)
In my app, it's not found whereas Trebeurden (same postal code) is found
Thanks
Gérald

**Comment by mtmail** [comment]
I get a result for that query

https://nominatim.openstreetmap.org/search.php?q=Pleumeur-Bodou%2C+Lannion%2C+C%C3%B4tes-d%27Armor%2C+Brittany%2C+22560%2C+France&polygon_geojson=1

https://nominatim.openstreetmap.org/search.php?q=Pleumeur-Bodou&polygon_geojson=1

![image](https://user-images.githubusercontent.com/3727288/37487672-935fb2f6-2892-11e8-9e53-ccde3183bedd.png)

**Comment by geraldbigot** [comment]
Yes, I see it was recognized but, in my CRM (which is linked to nominatim), I need to fill Pleumeur-Bodou%2C+Lannion to be ok (not only the city Pleumeur-Bodou as usual)

**Comment by mtmail** [comment]
You can set the `&viewbox` parameter to give Nominatim another hint where the user is located, e.g. setting it to whole of France or the the bounds of the map in the browser. https://wiki.openstreetmap.org/wiki/Nominatim#Special_Keywords

To look for a systematic error we'd need the exact URL and parameters that is send to the nominatim.openstreetmap.org server.

**Comment by lonvia** [comment]
Closing after no further response from the original reporter.
