### ISSUE TITLE
UK postcodes missing

### ISSUE THREAD

**Issue by stevewolfe555** [openstreetmap/Nominatim#980]
Hello,

This might be lack of understanding but should Nominatim be able to find any UK postcode via a search of it?

When I search "en10 6ad" after running the British isles install I get no results.

search.php?q=en10+6ad&polygon_geojson=1&viewbox=

But when I search other postcodes I get results, its seems to have about a 50% hit rate..

**Comment by JensHumrich** [comment]
Using the normal search 
https://www.openstreetmap.org/search?query=en10 6ad 
leads to one result:
Postleitzahl Broxbourne, EN10 6AD, Vereinigtes Königreich
But I am unable to click on this result or edit it :(

**Comment by stevewolfe555** [comment]
Its the local install i am having issues with.

**Comment by mtmail** [comment]
@stevewolfe555 Can you check if it's an issue with spaces in the query? https://github.com/openstreetmap/Nominatim/issues/927 Nominatim 3.1 has a more generic postcode handling than 3.0 and some special logic for GB postcodes was removed.

Nominatim queries two sources: one is OpenStreetMap, tough of course only a fraction of addresses/businesses have a full postcode attached, the second is Ordnance Survey (postcode file on http://nominatim.org/).

@JensHumrich What you see is results from the latter. We get the location from the postcode file but there's no OSM object and instead of returning a nearby it ends up un-clickable on 
https://www.openstreetmap.org/search?query=en10%206ad On https://nominatim.openstreetmap.org/search.php?q=en10+6ad the 'details' link is misleading because it does show a OSM object.

I'll check where the GB postcode logic got lost.

**Comment by stevewolfe555** [comment]
@mtmail are you also saying it will only work for business postcodes? 

Or will it work for residential

**Comment by mtmail** [comment]
The Ordnance Survey contains all GB postcodes, 1.7 million. The issue is that Nominatim doesn't handle the space correctly. So
https://nominatim.openstreetmap.org/search.php?q=en10+6ad
work, but
https://nominatim.openstreetmap.org/search.php?q=en106ad
doesn't.

Do you see that pattern in the postcodes you tried?

**Comment by stevewolfe555** [comment]
http://167.99.89.223/nominatim/search.php?q=En10+6ad&polygon_geojson=1&viewbox=


Just tried this

**Comment by mtmail** [comment]
GB postcodes are optional during the http://nominatim.org/release-docs/latest/admin/Import-and-Update/

Check if they got imported into the `location_postcode` table.

```nominatim=# select country_code, count(*) from location_postcode group by country_code order by count(*) desc limit 5;
 country_code |  count
--------------+---------
 gb           | 1702551
 nl           |  464421
 us           |   58003
 ca           |   39958
 br           |   27279
```

If not then it should be possible to import them now:
1. download and extract the file from http://nominatim.org/
2. import into the `gb_postcode` table, e.g. `cat <file> | psql nominatim`
3. run `build/utils/setup.php --calculate-postcodes`
4. check counts in `location_postcode` again

**Comment by JensHumrich** [comment]
So, in general Nomatim is able to find postcodes. How did you install your local machine? Is the data point you can find online available in the data set you loaded into your local machine?

**Comment by stevewolfe555** [comment]
I'll run the update again and see what I get.

**Comment by stevewolfe555** [comment]
Okay re did the install and got this.

Summary of warnings:

  * external UK postcode table not found.
  * wikipedia article dump file not found - places will have default importance
  * wikipedia redirect dump file not found - some place importance values may be missing

I downloaded the files was I meant to tell it I had?

**Comment by mtmail** [comment]
Do you remember where you downloaded them to? The `setup.php` looks in

    if (file_exists(CONST_BasePath.'/data/gb_postcode_data.sql.gz')) {

and `CONST_BasePath` is something like `Nominatim`. In the same directory where you'd also see a `us_postcode.sql` file. Or maybe you extracted the files after download? http://nominatim.org/release-docs/latest/admin/Import-and-Update/#uk-postcodes

My instructions above (https://github.com/openstreetmap/Nominatim/issues/980#issuecomment-374954353) should still work to add the GB postcode data manually after an existing install. It uses temporary tables so you can run that even during production.

Adding wikipedia ranking data after an install isn't possible I'm afraid. That would need a full reimport of the data. http://nominatim.org/release-docs/latest/admin/Import-and-Update/#wikipedia-rankings

**Comment by stevewolfe555** [comment]
That file was there, this is what i dont understand. All the files where in the correct DIR.

Could you give more detail as to this.

import into the gb_postcode table, e.g. cat <file> | psql nominatim
run build/utils/setup.php --calculate-postcodes
check counts in location_postcode again

**Comment by mtmail** [comment]
Assuming you have Nominatim installed on `/srv/nominatim/Nominatim` and the build directory in `/srv/nominatim/build/` (that's the default in the Ubuntu16 instructions, but you might have those in another's user home directory which is fine).

0. login as the user who installed Nominatim. For example `sudo -u nominatim`
1. This imports the *.sql file into the database `zcat /srv/nominatim/Nominatim/data/gb_postcode_data.sql.gz | psql nominatim`
2. uses data from the gb_postcode table and rewrites the location_postcode table `cd /srv/nominatim/build/; utils/setup.php --calculate-postcodes`
3. login to postgresql `psql nominatim`
4. run the SQL query `select count(*) from location_postcode where country_code='gb';`. It should say 1.7 million

**Comment by stevewolfe555** [comment]
Ah that's the issue it installed into Nomination 3.1


So the scrips would not have found it.

**Comment by stevewolfe555** [comment]
Hi I have been running utils/setup.php --calculate-postcodes for 20 + hours now and its still not completing.

is there any logs i can tail to see whats going on?

The server is a 8cpu 32gb ssd

**Comment by mtmail** [comment]
That's a surprising long time. It runs https://github.com/openstreetmap/Nominatim/blob/master/sql/update-postcodes.sql so you could check for the size of the temporary tables.

**Comment by stevewolfe555** [comment]
I dropped the DB and am rebuilding it after making sure all data files where there.

See how it goes this time.

**Comment by stevewolfe555** [comment]
Seems too be all working now thanks guys.
