### ISSUE TITLE
A question about update on planet_osm_nodes, planet_osm_ways and planet_osm_rels tables

### ISSUE THREAD

**Issue by marco110** [openstreetmap/Nominatim#983]
Hi, I notice there are three tables in the database: planet_osm_nodes, planet_osm_ways and planet_osm_rels, I want to know does the planet_osm_ways and planet_osm_rels table update when update the data?

Thanks !

**Comment by mtmail** [comment]
Yes. When you followed the setup of the upgrade process (http://nominatim.org/release-docs/latest/admin/Import-and-Update/#updates) then those tables will be kept uptodate, e.g. on a daily schedule. The update process then uses the updated data to reindex (update the `placex`, `search_name` tables for example).

**Comment by marco110** [comment]
Thank you very much!
