### ISSUE TITLE
Questions about query results

### ISSUE THREAD

**Issue by wangbingqian110** [openstreetmap/Nominatim#984]
Hello：
   I have some problems that have troubled me for a long time. I hope someone can help me.
   First,when the keyword I want to query is ‘hotel’, for 
example,"http://nominatim.openstreetmap.org/search.php？format=json&q='hotel'&polygon_geojson=1&addressdetails=1&limit=100". I expected to get a variety of hotels, but all I get is name with "hotel" place." Why is this?
  Second, I set limit=100, but the return result is only 50 at most. Why is this?
Thank you!

**Comment by mtmail** [comment]
In your example query you want a list of hotels in the whole world?

Try "hotels near Las Vegas, USA". That's documented in "special phrases" on https://wiki.openstreetmap.org/wiki/Nominatim

I think the limit of 50 results is reasonable. On your own server you cam change that in the function set_limit in lib/Geocode.php

**Comment by wangbingqian110** [comment]
Thank you very much for your answer. I understand it. There is also a problem. For example, when I search for ‘university near Las Vegas, USA’, the results may not include all the universities in Las Vegas. Why is that?

**Comment by mtmail** [comment]
Nominatim searches for universities around the center of Las Vegas.

**Comment by wangbingqian110** [comment]
@mtmail Do you mean that the search keyword is "University near Las Vegas Center"? I tried this but it didn't work. . .

**Comment by lonvia** [comment]
This all has been discussed in detail in other tickets already. POI search works as is. It will give you neither particularly exact nor complete results. This is not going to be fixed any time soon. You should consider using a different tool for your task. Have a look at Overpass API.

**Comment by wangbingqian110** [comment]
Ok! I understand, thank you very much for your answer.
