### ISSUE TITLE
Create index for planet_osm_ways table

### ISSUE THREAD

**Issue by marco110** [openstreetmap/Nominatim#985]
Hi, I have a request to query ways in planet_osm_ways, so I create index for id using btree
 in planet_osm_ways table, but it failed. I tried it several times, and I failed. Who can tell me why? Following is the error information and schema of planet_osm_ways.
Thanks!

![image](https://user-images.githubusercontent.com/20534952/37761903-dbb49022-2df5-11e8-9279-16faa2e26a36.png)
![schema](https://user-images.githubusercontent.com/20534952/37762180-92e9728a-2df6-11e8-8492-d1c46235bc5c.PNG)

**Comment by mtmail** [comment]
That's a postgresql question unrelated to Nominatim. Try https://help.openstreetmap.org or postgresql forums. (Also check for error messages in the postgresql server log file)

**Comment by marco110** [comment]
Thanks!
