### ISSUE TITLE
Street address does not line up with actual location, help wanted

### ISSUE THREAD

**Issue by mixmacsr568** [openstreetmap/Nominatim#995]
85 Country Club Drive, Atkinson, NH 03811 does not land on the actual location.  how do I edit this? @

**Comment by mtmail** [comment]
The easiest is probably to create a node for the club house and move all `addr:` tags to that node. Or a closed way with `building=yes` of course.

But I need to send you to the talk-us mailing list https://lists.openstreetmap.org/listinfo/talk-us or alternatively https://help.openstreetmap.org/tags/tagging/ That's where the pro mappers hang out and they can help you navigate the ins and outs of mapping golf courses https://wiki.openstreetmap.org/wiki/Tag:leisure=golf%20course?uselang=en-US (or where to put address tags in general).
