### ISSUE TITLE
place=locality is not considered in site relation

### ISSUE THREAD

**Issue by polarbearing** [openstreetmap/Nominatim#996]
We are using addr:place for the addresses of the [Stadtbahnbögen in Berlin](https://de.wikipedia.org/wiki/Stadtbahnb%C3%B6gen_%28Berlin%29), which are kind of a virtual street. 
Following the requirement described in #912, I've added place=locality to the site relation. 

While the node object, [example](https://nominatim.openstreetmap.org/details?osmtype=N&osmid=2707660451), is considered by nominatim, the [relation](https://nominatim.openstreetmap.org/details?osmtype=R&osmid=3563707) gets a "Bad request - Details: Please select a place id".  

As a side question, alt_name would work?

**Comment by lonvia** [comment]
Couple of things that go wrong here:

1. `place=locality` is not accepted as a base for addr:place on the grounds that it is described as an uninhabited place in the wiki
2. `site` relations are not recognized by Nominatim at all (see #463)
3. address nodes should not be a member of the site relations

2) clearly needs fixing in Nominatim, 3) should be fixed in the OSM data. That leaves 1).

It is possible to allow place=location as a base for addresses but I don't think the tag is particularly well suited for this situation. The places are not uninhabited after all. In fact, none of the place=* tags seems to fit particularly well. I'd probably go for a simple building=yes. Unfortunately, this won't work with the addressing then either. There are two suggestions for such building addresses in the answer to https://help.openstreetmap.org/questions/62684/addrplace-for-cases-where-building-name-replaces-street-name. None of them is ideal, I'm open for suggestions.

**Comment by skylerbunny** [comment]
I think it's probably a bad idea to be using place=locality tags to force a thing to be seen by Nominatim in conjunction with other tags. It feels like a good cheat to do it, but ultimately is a form of 'tagging for the renderer'.

place=locality has a real place in the database. I use it to mark historical railway stations, unincorporated communities which may have a sign marking them but no meaningful population, or freeway interchanges and railway junctions with a well known name but again, no population. I like the current description of 'locality', which describes it as sort of a sandbox for someday creating new tags, features, and relationships when they are fleshed out:

" to name an unpopulated location _for which there is no extant feature to which the tag could be associated_" (emphasis mine). In other words, if there is another tag that a locality should be better tagged with, THAT tag should be used and then the locality tag on the feature should be removed. At that point, it's up to Nominatim, OpenStreetMap Carto, etc. to properly use said tag.

**Comment by polarbearing** [comment]
> place=locality ... to mark ... unincorporated communities which ... have ... no meaningful population

According to [wikipedia](https://en.wikipedia.org/wiki/Category:Unincorporated_communities_in_the_United_States), a "unincorporated community is a populated place...", thus you are contradicting yourself. I'd use 'hamlet' for them.

Using ```place=locality``` for the Stadtbahnbögen is not ideal, I agree, since they are distributed all over Berlin inner city. They are uninhabited (nobody living in them), but used for businesses (storage, shops, restaurants). Was ```place=location``` (7 uses in taginfo, no wiki) meant to be an alternative, or a typo for locality? Even uninhabited places could have a legitimate address. 

The Stadtbahnbögen are not one single building but plenty separate adjacent buildings, having gaps where the rail runs over a bridge. To include them in a site relation was the most logical thing to do, thus solving (2) by fixing #463 seems reasonable. 

For (3), the wiki is unspecific about address nodes in site relations. Would they hurt?

**Comment by skylerbunny** [comment]
If I recall correctly, if the places you are marking have an address (housenumber, street, postcode, etc.) you don't need to also add place=locality to it to have Nominatim pick it up. It puts them into the database because it has addr: tags.

**Comment by skylerbunny** [comment]
I THINK (although the team would have to confirm it) another way you may be able to handle this is to use a landuse tag. For instance, this isn't labeled with an address, but as a mall, a collection of buildings, is tagged with landuse=retail, and Nominatim knows what it is. https://nominatim.openstreetmap.org/details.php?place_id=139624403

**Comment by lonvia** [comment]
It so happens that I did some on the site research in the Stadtbögen just now and it seems that businesses generally add the streetname to the address. So I'd probably just tag them with addr:housenumber=<Stadtbogennummer>, addr:housename=Stadtbögen, addr:street=<as appropriate>.

In any case, this is still no real use case for having place=locality taken into account for addresses, which was the original request. So closing as won't fix here. The request for site relations remains open, of course. That part is perfectly valid.
