### ISSUE TITLE
Error executing osm2pgsql: 137 

### ISSUE THREAD

**Issue by marco110** [openstreetmap/Nominatim#998]
Hi, there is a error when updating nominatim but no more error information just "Error executing osm2pgsql: 137 ".

Who can tell me why it throw this exception and where should i find the log file?

Thanks!

**Comment by marco110** [comment]
And the following are the details:
![image](https://user-images.githubusercontent.com/20534952/38243176-420573f6-3769-11e8-9cac-970ad8e8e151.png)

**Comment by lonvia** [comment]
This is likely an out-of-memory error. Check your system logs (dmesg) for any OOM error messages. If nothing is there, check the postgres logs for unusual messages.

**Comment by marco110** [comment]
Thanks lonvia, and  I found an error log: function transliteration(text) does not exist at character 23.
But the update tool has been running for two weeks and it didn't throw an exception until yesterday, and there is no a "nominatim.so" file under the module folder, I think it is very strange. And how should i do and just add a "nominatim.so" file to module folder?

Thanks

**Comment by mtmail** [comment]
The `/srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so` gets created by the `cmake/make` commands in the http://nominatim.org/release-docs/latest/appendix/Install-on-Ubuntu-16/#installing-nominatim step. Are you sure the file is missing? If it was missing then the initial data import would've failed already. With rerunning cmake and make you can recreate it.

Does the `function transliteration(text) does not exist at character 23.` error message have a timestamp? It might be old and unrelated to the current osm2pgsql issue.

**Comment by marco110** [comment]
No, the /srv/nominatim/Nominatim-3.1.0/build/module/nominatim.so file is not missing, and the error "function transliteration(text) does not exist at character 23." is the latest error.

2018-04-04 11:08:27 UTC [26371-1] ERROR:  function transliteration(text) does not exist at character 23
2018-04-04 11:08:27 UTC [26371-2] HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-04-04 11:08:27 UTC [26371-3] QUERY:  SELECT gettokenstring(transliteration(name))
2018-04-04 11:08:27 UTC [26371-4] CONTEXT:  PL/pgSQL function public.make_standard_name(text) line 5 at assignment
	automatic analyze of table "nominatim.public.placex"

I rerun the update tool and it throw this error.

**Comment by marco110** [comment]
I am sorry that I notice this error message was always there but the nominatim.so file is not missing, and I don't know where is wrong.

Thanks.

**Comment by marco110** [comment]
Finally, I found a system log:
 kernel: [683540.905021] Out of memory: Kill process 25421 (osm2pgsql) score 832 or sacrifice child
 kernel: [683540.910819] Killed process 25421 (osm2pgsql) total-vm:59176840kB, anon-rss:13567576kB, file-rss:1744kB

Then I set the cache is 2000MB when updating and the RAM of my machine is 16GB, it failed too, and can you tell me how should I do?
Thanks.

**Comment by mtmail** [comment]
Ok. That kernel error message makes sense. 

`Error executing osm2pgsql: 137` If a process exits with 128+9 when usually it got killed externally and the operating system running out of memory is such a likely cause.

I don't know what else is running on your machine and using memory. Or your swap memory settings. I would try rerunning the command with different `osm2pgsql-cache` values, e.g.
`/srv/nominatim/Nominatim/build/utils/update.php --import-osmosis-all --osm2pgsql-cache 1000`
(http://nominatim.org/release-docs/latest/admin/Import-and-Update/#setting-up-the-update-process) and/or try to stop other processes to free memory. Maybe even a reboot help.

You can run the `update.php` multiple times. I keep track of what it last updated.

**Comment by marco110** [comment]
Thanks a lot, but there no other processes running on my machine, I also remember that the hard disk capacity is not much, and I will do more test for it in a few days.

**Comment by lonvia** [comment]
It is fair to assume that you have at least Potsgresql and Apache running on your machine. Both can use a lot of memory when configured badly. You should also check that you allow overcommitting memory. Finally, I would recommend to try working with smaller changes. Use hourly diffs instead of daily diffs. You can switch the replication source but you need to setup the process again with `./utils/update --init-updates` after changing `CONST_Replication_Url`.

Before doing any further experiments, you should run `./utils/setup.php --create-functions --enable-diff-updates` to enable extended processing for diffs again. That got switched off when you run create-functions without the second parameter.

**Comment by marco110** [comment]
Thanks, I have done a test  and I set  cache to 1GB and it failed too. For hourly diffs, I think I don't have much cost to run it because I need to shut  down the machine every day on AWS.

**Comment by marco110** [comment]
Thanks lonvia, but anything going well after I restarted the machine and I don't know why.
